### ISSUE TITLE
I would like to try translating immich's web application into Chinese

### ISSUE THREAD

**Issue by PolarisGitYHNL** [immich-app/immich#10014]
### The bug

I'm very sorry, I'm not very familiar with GitHub, so I submitted this in the bug. If there are any errors in the submission, I apologize.
As the title suggests, I would like to try translating immich's web application into Chinese. I am a college student in Chinese Mainland, and my English is not very good, so I am a big head when facing pure English web applications. As a computer science major, I have taken the course of Web and HTML, so I would like to try translating web interfaces. But I am not particularly familiar with the structure and other working principles of immich, so I would like to contact the developers for some assistance.
Of course, the above is my relatively simple idea. Regardless of whether it will be successful in the end, I want to contribute my own efforts to the open-source project immich.

### The OS that Immich Server is running on

Synology-DSM-Docker

### Version of Immich Server

---

### Version of Immich Mobile App

---

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
```

### Your .env content

```Shell
---
```

### Reproduction steps

```bash
---
```

**Comment by bo0tzz** [comment]
We've just set up Weblate, soon you'll be able to contribute translations there.

**Comment by jrasm91** [comment]
https://hosted.weblate.org/projects/immich/immich/

**Comment by PolarisGitYHNL** [comment]
tks
I have given about 50 suggestions.

**Comment by PolarisGitYHNL** [comment]
now 206
