### ISSUE TITLE
Issue with navbar in Android

### ISSUE THREAD

**Issue by davydes** [immich-app/immich#10010]
### The bug

Device: Xiaomi Pad 5 Pro 5G

Nav bar look as below:

![photo_2024-06-06_14-33-54 (2)](https://github.com/immich-app/immich/assets/1126233/35b91240-1f4c-411e-9165-b98fd6aa9e33)

On Search and other pages it's ok:

![photo_2024-06-06_14-33-54](https://github.com/immich-app/immich/assets/1126233/2bbb1c23-b5f6-4010-b1ca-dd9adb0f28c5)

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

1.105.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
...
```

### Your .env content

```Shell
...
```

### Reproduction steps

```bash
1. Open main page in app
```

**Comment by theleshek** [comment]
Same here!
