### ISSUE TITLE
[BUG] If the OAuth user signs in before the admin user is created, the web interface doesn't go through the admin user creation proces

### ISSUE THREAD

**Issue by alextran1502** [immich-app/immich#1001]
**Describe the bug**
If the OAuth user signs in before the admin user is created, the web interface doesn't go through the admin user creation process.

**To Reproduce**
1. Create a new instance with the OAuth feature.
2. Login with OAuth user.
3. Navigate to the web and click on getting started.
4. The redirect will be going to the login form instead of the admin user creation form.

**Expected behavior**
This is debatable:
Scenario 1: The first OAuth user that sign in will be made admin
Scenario 2: Correctly determined there is no admin user yet to show the admin creation form.

**System**
- Server Version: 1.36.1
- Mobile App Version: 1.36.1

**Comment by alextran1502** [comment]
Also, a good chance to work on #351 as well.

**Comment by Mortein** [comment]
Scenario 3...?

If using OAuth, a user's current group membership should be used to grant the Admin role on login (every login).
In some instances, there could be more than one administrator, there may be no administrators, or a user may have the admin group temporarily added.

**Comment by bo0tzz** [comment]
My opinion on this is the following: I think we should always have a local admin user first, to prevent lockouts. That would also be a necessity if we want to move the oauth configuration into the web interface instead of using env vars.

**Comment by alextran1502** [comment]
I agree with @bo0tzz here

**Comment by jrasm91** [comment]
Unless there are strong opinions otherwise, I think the first user to login should be made an admin. I can add that logic to the oauth login flow.

**Comment by alextran1502** [comment]
@jrasm91 I would like to keep the first login flow on the web intact regardless of whether OAuth is enabled. The user can link the OAuth account to the admin account later after creating the first admin account on the web. My reason is that I want to keep the diversification of creating an admin account as small as possible.

**Comment by jrasm91** [comment]
OK, so the fix would instead be changing the web "isAdminUserExist" logic to work as expected? Right now it assumes if user count > 0 there is an admin.

**Comment by bo0tzz** [comment]
Fixing that logic to actually check for an admin user is definitely a good idea. I think we should also stick with the requirement of creating an admin account before the app can be used. That was enforced previously, but the oauth setup 'circumvents' it. That can be resolved just by moving the oauth config into the web config panel instead of using env vars.

**Comment by jrasm91** [comment]
I don't think admin setup logic needs to be coupled with how we store configuration.

The requirement you're describing is to prevent (non-admin) user from signing up until after there's a local admin. I think we could do that just by adding an is local admin check before registering a new user.

**Comment by bo0tzz** [comment]
I'm not saying we need to hard-couple them, but just that if oauth config happens via the admin panel then there will necessarily need to be an admin user before oauth can be set up. That's not a specific enforcement in code, but just something that happens 'naturally'. Adding an extra check to only allow oauth login if there is already an admin can't hurt, of course.

**Comment by jrasm91** [comment]
Yeah, that makes sense. IMO, having a specific check for this would be less likely to lead to related bugs in the future. 

We could add the check to the user repository create method that should be used anytime a new user is created. This would also take care of any new user creation processes that get added in the future.
