### ISSUE TITLE
[BUG] (WEB) Albums page unvailable/redirects when deleting user

### ISSUE THREAD

**Issue by Simonh2o** [immich-app/immich#1004]
The Albums page is unavailable, and redirects to URL/auth/login (logs you out) when you delete a user that you've shared an album with. Just seeing HTTP redirect (OAuth) URL/auth/login in the console. Restoring (I was within the 7 days time limit) the deleted user account brings the albums page back. Happens on web latest version 1.36.1. 

Expected behavior: Albums page works and the deleted user account is removed from the Shared album(s) ?

Apologies if this is raised prematurely, didn't find any similar open issues and have not tested this thoroughly yet.

**Comment by alextran1502** [comment]
Hello the PR to fix this has been opened. It should be fixed in the upcoming patch

https://github.com/immich-app/immich/pull/1002

**Comment by Simonh2o** [comment]
Totally missed that, my bad!

**Comment by alextran1502** [comment]
@Simonh2o Should be fixed in 1.36.2 now
