### ISSUE TITLE
[Feature]: Add checkfield to check all photos.

### ISSUE THREAD

**Issue by PrzemekSkw** [immich-app/immich#1007]
### Feature detail

I have very large collection and it took very long time to check every months separate.
Regards.

### Platform

Mobile App

**Comment by alextran1502** [comment]
Hello, what would be the use case of checking all assets?

**Comment by PrzemekSkw** [comment]
> Hello, what would be the use case of checking all assets?

I want to share my all photos with my wife.

**Comment by jcastro** [comment]
This would be really helpful to select all and delete them as well

**Comment by alextran1502** [comment]
@jcastro Deleting will be better handled without interfering with the rendering portion of the app. Please follow #774 for such a feature

@PrzemekSkw There will be a better feature called sharing with partners, which handles this request. Please follow #637 for the process
