### ISSUE TITLE
[Feature]: Backup to another Drive

### ISSUE THREAD

**Issue by ZsZolee** [immich-app/immich#1013]
### Feature detail

I would love to see a simple backup solution to make daily/weekly a backup to another drive/folder from every uploaded picture/video. Is it possible? I'm trying now to resolve manually with rsync scheduling, but it's not easy (I'm a noob to linux).

### Platform

Server

**Comment by bo0tzz** [comment]
It's generally not recommended to use a tool like rsync for backups, since it would also synchronize deletions. I don't have a specific recommendation, but I suggest you take a look at [this list of backup tools](https://github.com/awesome-foss/awesome-sysadmin#backups) and pick one of them. Everybody's backup setup is different, so I don't think this is something to add into Immich itself.

**Comment by jpmiller25** [comment]
@ZsZolee I recommend 
[Duplicati](https://hub.docker.com/r/linuxserver/duplicati). 
It runs in docker, very easy to use, can back up to local file system or many different cloud providers, it can do incremental and smart backup retention (eg daily from last week, weekly for last month, monthly prior to that). 

I use it to back up all my config to AWS. I'm not currently using it for photos but I should lol. If you set it up I'm curious to know if you run into any challenges etc.

**Comment by ZsZolee** [comment]
> @ZsZolee I recommend [Duplicati](https://hub.docker.com/r/linuxserver/duplicati). It runs in docker, very easy to use, can back up to local file system or many different cloud providers, it can do incremental and smart backup retention (eg daily from last week, weekly for last month, monthly prior to that).
> 
> I use it to back up all my config to AWS. I'm not currently using it for photos but I should lol. If you set it up I'm curious to know if you run into any challenges etc.

I'm using FreeFileSync and installed it based on this manual: https://github.com/pmkees/build-FreeFileSync-on-raspberry-pi
