### ISSUE TITLE
bug(web): Viewer crashes when shared link metadata is off

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#10130]
### The bug

`Uncaught (in promise) TypeError: can't access property "lastIndexOf", e is undefined`

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

v1.106.1

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. create individual share with metada turned off
2. access that shared link
3. click to photo
4. viewer crashes
```

**Comment by zackpollard** [comment]
Can confirm I can see the same behavior, will take a look into this.
