### ISSUE TITLE
I think your able to get a grant / money!

### ISSUE THREAD

**Issue by PrivacyOsint2** [immich-app/immich#1015]
I have trying to find projects on privacy/ f-droid. 
Watch this video:
https://www.youtube.com/watch?v=vawcnCv1_1w

Email them I think you could get some money. If I were you, I would do a video with him on YouTube channel because this will blow up!!

I wish you the best of luck! I am donating $5 per month because I believe in the project. I do use the F-droid for many years/ please keep the trackers out of the app like other solutions! Great work!

There are other solutions such photo sync - no f-droid version.

Email:
louis@futo.org
or look in description.

**Comment by alextran1502** [comment]
Nice, thank you for the info!
