### ISSUE TITLE
Images in duplicate detection have massive JSON tooltips

### ISSUE THREAD

**Issue by ZtereoHYPE** [immich-app/immich#10164]
### The bug

When I hover over images in the new duplicate detection screen, massive tooltips appear. Note that these are the native browser tooltips and not some system screen-reader or browser extension.

I tested this only with Firefox for now.

![Screenshot from 2024-06-11 21-57-15](https://github.com/immich-app/immich/assets/57519662/40f3be50-b6d8-46ba-8018-cf66a0850a83)

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.106.2

### Version of Immich Mobile App

v1.106.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I don't think it's relevant so I'm excluding it from this report, but if you still want it please do tag me.
```

### Your .env content

```Shell
same as above
```

### Reproduction steps

```bash
1. Open immich on the web
2. Navigate to the duplicate detection page
3. Hover over any of the images in the page and leave your cursor stationary for around half a second.

The tooltip should appear.
```

**Comment by alextran1502** [comment]
Not a bug, I explicitly put it there since I don't want to include all of the exif data to the interface
