### ISSUE TITLE
[BUG] [OIDC] Don't bind user to E-Mail but to Open ID sub

### ISSUE THREAD

**Issue by akoyaxd** [immich-app/immich#1019]
**Describe the bug**
If I use Open ID to login and a user changes the E-Mail in the IDP (like Authentik), Immich creates a new account on the next login

**Task List**

**To Reproduce**
1. Install Immich
2. Setup OAuth accordingly to the docs.
3. Login with OAuth
4. Change E-Mail address in the IDP
5. Logout and Login again to Immich
6. New user in Immich is created

**Expected behavior**
Immich recognizes the user by the unique Open ID `sub` attribute and logs the use in.  
Icing on the cake: The E-Mail get's updated in the Immich Database.

**System**
all

**Additional context**
My IDP is Authentik

**Comment by christiaangoossens** [comment]
When resolving this, keep in mind the migration from local to OIDC. 

If I create an account with an email not using OIDC and then configure OIDC, I want to have that same account used when I login with that email.

Thus, link sub to the user on first login, by first attempting to match email.

**Comment by alextran1502** [comment]
> When resolving this, keep in mind the migration from local to OIDC.
> 
> If I create an account with an email not using OIDC and then configure OIDC, I want to have that same account used when I login with that email.
> 
> Thus, link sub to the user on first login, by first attempting to match email.

@christiaangoossens I believe you can currently do that already. The OIDC account and the existing email on Immich is "linked"

**Comment by christiaangoossens** [comment]
> > When resolving this, keep in mind the migration from local to OIDC.
> > 
> > If I create an account with an email not using OIDC and then configure OIDC, I want to have that same account used when I login with that email.
> > 
> > Thus, link sub to the user on first login, by first attempting to match email.
> 
> @christiaangoossens I believe you can currently do that already. The OIDC account and the existing email on Immich is "linked"

That's indeed currently how it works, but natively changing the claim to `sub` breaks that. Therefore, a solution proposed here should keep not breaking this in mind.

**Comment by alextran1502** [comment]
@jrasm91 Tagging Jason FYI

**Comment by jrasm91** [comment]
Yeah, this makes sense.

1. If sub matches, it's a linked user
2. If email matches, it's the first login for a linked user, so save the sub
3. Otherwise, register a new user (and save the sub)
