### ISSUE TITLE
The photo is displayed in the wrong direction

### ISSUE THREAD

**Issue by PolarisGitYHNL** [immich-app/immich#10208]
### The bug

The photo is displayed in the wrong direction.
The photo source file is a vertical photo, and it displays normally in both the Synology album and MT Photos (another Docker based album), as shown in the following figure:
<img width="1916" alt="image" src="https://github.com/immich-app/immich/assets/165972224/9f412f9e-2ef6-4d01-8676-bae686837fcf">
<img width="1919" alt="image" src="https://github.com/immich-app/immich/assets/165972224/362457e6-4d49-4a64-8278-d75073f5d774">
In IMMICH, the shape of the thumbnail is normal and displayed as a vertical version, as shown in the following figure:
<img width="1919" alt="image" src="https://github.com/immich-app/immich/assets/165972224/b57854a5-3908-4cd7-a210-05497c2333d8">
However, the images and photos in the thumbnail are folded down to display horizontally, as shown in the following figure:
<img width="1919" alt="image" src="https://github.com/immich-app/immich/assets/165972224/313256d7-f51c-4b42-95c1-33e44f780d20">
The same applies to displaying errors in mobile apps:
![image](https://github.com/immich-app/immich/assets/165972224/346ec6a5-b9cd-4848-a6be-68b8d200512b)

### The OS that Immich Server is running on

Sinology DSM docker

### Version of Immich Server

v1.106.2

### Version of Immich Mobile App

v1.106.1

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Perhaps the problem is unrelated to this
```

### Your .env content

```Shell
Perhaps the problem is unrelated to this
```

### Reproduction steps

```bash
None
```

**Comment by bo0tzz** [comment]
Does the EXIF of the files have any rotation metadata?

**Comment by Snowknight26** [comment]
libraw probably needs an update.

Potential workaround: https://github.com/immich-app/immich/issues/9845#issuecomment-2145840833

**Comment by PolarisGitYHNL** [comment]
> Does the EXIF of the files have any rotation metadata?
YES
One line in EXIF:
Orientation Rotate 270 CW

**Comment by PolarisGitYHNL** [comment]
sorry
my mistake(I have reopened it)

**Comment by jrasm91** [comment]
Can you refresh metadata and then refresh thumbnails for this picture and let me know if it is still orientated incorrectly?

![image](https://github.com/immich-app/immich/assets/4334196/df37e42a-9f6f-45fc-88fa-4964b9763e26)

**Comment by dennisfrijlink** [comment]
Same issue here. For me its's only on vertical orientated photos. Some thumbnails are good orientated and some are not. Same device, same resolution and same orientation.

**Comment by dennisfrijlink** [comment]
Also noticed that when opening the detail page of the photo the orientation is still wrong but after zoom the photo rotates 90deg to the correct view.

**Comment by theorician** [comment]
I'm seeing the same issue on 109.2. I've refreshed metadata and thumbnails for an image and it's still sideways. It shows fine everywhere else. It's an Oly raw ORF with Orientation: Rotate 90 CW set in the EXIF.

**Comment by its0keke** [comment]
Not positive if I'm seeing the same issue, but I've got a jpg image with a `Rotate 180` xmp tag that was set by Digikam. When Immich generated the thumbnails, the rotation isn't applied.

**Comment by danieldietzler** [comment]
Most likely this is fixed. If it's still an issue, please provide a sample file.
