### ISSUE TITLE
OAuth - Login has to be granted every time since 1.106

### ISSUE THREAD

**Issue by Str1atum** [immich-app/immich#10201]
### The bug

I have a setup with Authelia and OAuth configuration which used to work perfectly.
Since 1.106 without changing anything on Authelia or the overall setup, my Safari browser prompts to grant Authelia access to immich on every single launch - which was not previously the case.

![Screenshot 12 06 2024 um 12 14 37 PM](https://github.com/immich-app/immich/assets/76776216/84257896-53b3-498a-b72d-b6ef35016525)

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

1.106.2

### Version of Immich Mobile App

1.106.1

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
standard
```

### Your .env content

```Shell
standard
```

### Reproduction steps

```bash
Close browser
Open immich in browser
```

**Comment by alextran1502** [comment]
Can you try with an incognito view or a different browser to see if this is a caching issue?

**Comment by DX37** [comment]
Try to clean browser cache. I encountered this issue right now and cache cleaning helped.

**Comment by bencefr** [comment]
Same happened, cleaning the cache fixes it.
