### ISSUE TITLE
[Bug]: Recover the account before the delete script starts

### ISSUE THREAD

**Issue by NeleB54Gold** [immich-app/immich#1022]
### Feature detail

i'm so stupid i requested deletion of the only admin account on immich, how can i cancel it?
I stopped the docker before it can start delete everything, please HELP

### Platform

Server

**Comment by jrasm91** [comment]
If you have access to the database you can null out the deleted at column for the user to undo it. 

Or, I wonder if you can create a second admin account and then use that to undo the first one.

**Comment by NeleB54Gold** [comment]
> If you have access to the database you can null out the deleted at column for the user to undo it.
> 
> Or, I wonder if you can create a second admin account and then use that to undo the first one.

How can I read the postgre database in order to change it/add a new account?

**Comment by alextran1502** [comment]
Assuming your database name is `immich` and your database user is `postgres` (default value from Immich)

1. Attach to the Postgres container
2. execute `psql -U postgres -d immich`
3. Then execute 
```sql
UPDATE users
SET "deletedAt" = null
WHERE email = 'your-admin-email';
```

Should be good to go.

**Comment by jrasm91** [comment]
Maybe it would be good to add some checks that prevent deleting the admin account 😛.

It also might be worthwhile to add some cli commands to help with resolving some of these database related fixes, like make a user an admin, etc.

**Comment by alextran1502** [comment]
> Maybe it would be good to add some checks that prevent deleting the admin account 😛.
> 
> It also might be worthwhile to add some cli commands to help with resolving some of these database related fixes, like make a user an admin, etc.

From the PR deleting user I remember I saw that check 🤔

**Comment by alextran1502** [comment]
> > Maybe it would be good to add some checks that prevent deleting the admin account 😛.
> > It also might be worthwhile to add some cli commands to help with resolving some of these database related fixes, like make a user an admin, etc.
> 
> From the PR deleting user I remember I saw that check 🤔

damnit I missed it

**Comment by NeleB54Gold** [comment]
> Assuming your database name is `immich` and your database user is `postgres` (default value from Immich)
> 
> 1. Attach to the Postgres container
> 2. execute `psql -U postgres -d immich`
> 3. Then execute
> 
> ```sql
> UPDATE users
> SET "deletedAt" = null
> WHERE email = 'your-admin-email';
> ```
> 
> Should be good to go.

I'm sorry, I'm not an expert with docker, how can I find the immich name to attach?
I tried with immich, immich-app, immich_app, but maybe is an ID from the conteiner idk

**Comment by jrasm91** [comment]
You can run docker ps to get a list of running containers, or docker ps -a to include ones that are stopped.

Also, it'd probably be easier to assist/chat/help if you posted on discord, instead of using this GitHub issue.

**Comment by alextran1502** [comment]
With `docker ps` you will see a list below
<img width="1633" alt="Screenshot 2022-11-26 at 15 10 26" src="https://user-images.githubusercontent.com/27055614/204109067-ff025583-3926-4867-a990-4cf3516fc64c.png">

Then using the command below to get into the container

```
docker exec -it immich_postgres bash
```

**Comment by NeleB54Gold** [comment]
![Cattura](https://user-images.githubusercontent.com/51356760/204109331-dfcc4f06-6167-43b2-9471-b719567c8618.PNG)
Ok, I recovered my account, but why the other account is still there?
I deleted the "salvatore"'s account, and when I clicked on it too many time (yes, I know, sometimes I'm really stupid), probably some ID changed in order to delete my account, because, how can I delete myself from my profile?

**Comment by alextran1502** [comment]
> ![Cattura](https://user-images.githubusercontent.com/51356760/204109446-a8e3bdc1-65b3-4293-abcb-668f06bc64a1.PNG)
> 
> Ok, I recovered my account, but why the other account is still there? I deleted the "salvatore"'s account, and when I clicked on it too many time (yes, I know, sometimes I'm really stupid), probably some ID changed in order to delete my account, because, how can I delete myself from my profile?

So the `salvator` account is a non-admin account, correct?

**Comment by NeleB54Gold** [comment]
> > ![Cattura](https://user-images.githubusercontent.com/51356760/204109446-a8e3bdc1-65b3-4293-abcb-668f06bc64a1.PNG)
> > Ok, I recovered my account, but why the other account is still there? I deleted the "salvatore"'s account, and when I clicked on it too many time (yes, I know, sometimes I'm really stupid), probably some ID changed in order to delete my account, because, how can I delete myself from my profile?
> 
> So the `salvator` account is a non-admin account, correct?

Correct, now the schedule delete go to 3 December, it's 7 days later, maybe I need to update immich to be sure that it can be deleted that day, but it's ok, the salvatore have no media files on it, it was only an account management test for me

**Comment by alextran1502** [comment]
The delete action will trigger 7 days grace period where you can recover the account.

I wonder how did you delete the admin account in the first place. Or do you mean you were deleting the non-admin account `salvatore`? Note that the admin account doesn't show up in the user management.

**Comment by NeleB54Gold** [comment]
> The delete action will trigger 7 days grace period where you can recover the account.
> 
> I wonder how did you delete the admin account in the first place. Or do you mean you were deleting the non-admin account `salvatore`? Note that the admin account doesn't show up in the user management. 

As I said before, I was constantly clicking on the button to delete Salvatore's account, and I don't know how, and I scheduled the deletion to mine, because it wouldn't let me login anymore and when i updated with the request on the database i was able to login again. Oof, really, I want to help, but this time was totally random

**Comment by alextran1502** [comment]
Hmm strange, but good report, though. I will take a look at the continuation clicking on the button. I guess we can close this issue.

**Comment by NeleB54Gold** [comment]
> Hmm strange, but good report, though. I will take a look at the continuation clicking on the button. I guess we can close this issue.

Yes, thank you all for the instant help!

**Comment by jrasm91** [comment]
I think there is a bug where email is not uniquely enforced at the database level so two request (submit button clicked twice quickly) can cause two accounts with the same email to be successfully created. I know we patched the UI for this, but maybe there are two accounts with the same email and that has led to this weird situation/behavior. 

Can you use SQL to list all the users? I bet there are two with the same email, one or both are admins.

**Comment by NeleB54Gold** [comment]
> I think there is a bug where email is not uniquely enforced at the database level so two request (submit button clicked twice quickly) can cause two accounts with the same email to be successfully created. I know we patched the UI for this, but maybe there are two accounts with the same email and that has led to this weird situation/behavior. 
> 
> Can you use SQL to list all the users? I bet there are two with the same email, one or both are admins.

Oh, ok, I'm on my phone now, sorry for Termius quality lol
![20221126_230935.jpg](https://user-images.githubusercontent.com/51356760/204110769-8fc5fdff-b320-417c-af11-589835902b6c.jpg)

**Comment by jrasm91** [comment]
Looks normal/good, so there goes that theory!
