### ISSUE TITLE
the "info" pane shows json content rather than date, people, places, albums on mobile

### ISSUE THREAD

**Issue by diyoyo** [immich-app/immich#10282]
### The bug

Hi, I remember a time when the info panel that appears from the bottom of the screen on the Android version would show similar kind of info as the web version.
Now, all I see is a json object with "advanced information".

Is it a bug or something that can be changed in the settings?
Thanks.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.106.3

### Version of Immich Mobile App

v1.106.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Choose a picture in the mobile version
2. Swipe up or click the (i)
3. Observe.
...
```

**Comment by alextran1502** [comment]
Go to the app settings > Advanced > disable the Troubleshooting toggle
