### ISSUE TITLE
missing mobile translations for "x years ago" and months

### ISSUE THREAD

**Issue by JordyEGNL** [immich-app/immich#10280]
### The bug

The following texts are not yet translated in the mobile app and not available to translate in Localizely

- "x years ago" for memories
- Months on the main page

Screenshot for reference, my Immich app is set to "Dutch (nl_NL)"
![thumbnail](https://github.com/immich-app/immich/assets/65036298/6b91c4da-9768-4c14-b140-da71f79b013f)

### The OS that Immich Server is running on

n/a

### Version of Immich Server

n/a

### Version of Immich Mobile App

v1.106.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. Set your Immich mobile app to anything other than English
2. Look at the texts mentioned in the description
3. Texts are not translated
```

**Comment by NYCgirlLearnsToCode** [comment]
Hi @JordyEGNL I saw this on https://goodfirstissues.com/ . I'm interested in fixing it, will you assign it to me?

**Comment by bo0tzz** [comment]
@NYCgirlLearnsToCode there's already an open PR for this in #10324, unfortunately.
