### ISSUE TITLE
Website: iOS: People: Set date of birth: day not selectable 

### ISSUE THREAD

**Issue by bw1faeh0** [immich-app/immich#10325]
### The bug

When setting date of birth of a person using safari on iOS (iPad) it is not possible to select the day.

![IMG_2020](https://github.com/immich-app/immich/assets/29235332/e19fc91f-bb17-40e8-8e4c-164e18518820)

### The OS that Immich Server is running on

De ian

### Version of Immich Server

1.106.4

### Version of Immich Mobile App

1.106.3

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
Try to set date of birth of a person using safari on an iPad.
```

**Comment by alextran1502** [comment]
Fixed
