### ISSUE TITLE
bug(web): Clicking back button from search result returns page to top

### ISSUE THREAD

**Issue by ddshd** [immich-app/immich#10341]
### The bug

- Make a search query
- Click a result that is below the fold
- Click (<-) back button
- *The page has scrolled back to the top*

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

na

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
na
```

### Your .env content

```Shell
na
```

### Reproduction steps

```bash
See description
```

**Comment by bo0tzz** [comment]
#3114
