### ISSUE TITLE
New/edited library files appear in trash

### ISSUE THREAD

**Issue by ajpanton** [immich-app/immich#10347]
### The bug

If I have the Immich trash open in my web browser, and then add a new file (or edit an existing file) to my external library, they all appear in my browser as trashed files. However, if I refresh the page, or just exit and re-enter the trash, they aren't actually there.

Here I just edited a (quite old) image in my external library:
![trash](https://github.com/immich-app/immich/assets/9302631/b96c948c-7d13-4a32-8a23-45ee13575d50)

### The OS that Immich Server is running on

Truenas SCALE app

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Have Immich automatically detect changes in an external library.
2. Open trash in Immich in a web browser.
3. Add a new photo to the external library, or edit an existing file.
4. See the new or edited file appear in trash.
```

**Comment by bo0tzz** [comment]
Dupe: #8979
