### ISSUE TITLE
[BUG] (WEB) Video preview and videos won't load on Safari

### ISSUE THREAD

**Issue by Simonh2o** [immich-app/immich#1035]
Safari is unable to load video previews or play videos directly. In developer tools preview it reads "An error occurred trying to load the resource." It shows http status 206 as well as content-type video/mp4. Sadly only been able to with nginx reverse proxy, let me know if you need me to test directly. I've attached some screenshots of the results.
- Immich web version v1.36.2

<img width="907" alt="Screen Shot 2022-11-29 at 11 11 38 PM" src="https://user-images.githubusercontent.com/44584359/204661302-96b58278-5959-4f6e-8f74-ffee6d389296.png">
<img width="794" alt="Screen Shot 2022-11-29 at 11 14 44 PM" src="https://user-images.githubusercontent.com/44584359/204661310-69bfe60e-9895-438b-8b49-a7e9fb282117.png">

**Comment by bo0tzz** [comment]
Does it work in Firefox/chrome?

**Comment by Simonh2o** [comment]
> 

Yep

**Comment by alextran1502** [comment]
Hello,


1. What do you mean by this?
```
Sadly only been able to with nginx reverse proxy
```

2. Where did the video get uploaded, iPhone or Android?

**Comment by alextran1502** [comment]
Is your setup custom, please provide the docker-compose and .env file as well as any other context that can help us to trouble shoot the issue

**Comment by Simonh2o** [comment]
> Hello,
> 
> 1. What do you mean by this?
> 
> ```
> Sadly only been able to with nginx reverse proxy
> ```
> 
>  2. Where did the video get uploaded, iPhone or Android?

1. Can't access immich locally atm, only externally through nginx proxy.
2. File was uploaded via Android, same version.

-Correction: No issues on Chrome, but on Firefox the video loads but there's just a black screen. Getting http status 200.

**Comment by alextran1502** [comment]
This is a known issue for H.265 MP4 file, which is not transcoded to H264 to be played on the web.

You can follow this issue #203 for when it is supported

**Comment by alextran1502** [comment]
I am closing this one for now. As it is a known issue and has a related issue opened already.

Thank you for reporting.
