### ISSUE TITLE
IPv6 Support on Kubernetes

### ISSUE THREAD

**Issue by RomLecat** [immich-app/immich#10397]
### The bug

Immich cannot connect to Redis in Kubernetes in Dual-Stack mode because it only resolves IPv4 for Redis service, when the service is IPv6-only (and not configurable due to Bitnami's Redis chart).

It results in the following error in loop (because the service only has AAAA record and no A records):

```
Error: getaddrinfo ENOTFOUND immich-redis-master
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3007,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'immich-redis-master'
}
```

### The OS that Immich Server is running on

K8s v1.28.10

### Version of Immich Server

1.106.4

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Run Immich with its Helm chart on a dual-stack (or IPv6-only) K8s cluster
```

**Comment by bo0tzz** [comment]
I'm not quite sure where this is going wrong, but it doesn't quite seem like an Immich issue to me. This seems like either an issue with the bitnami chart or kubernetes dns, or with how the redis library we use resolves the address.

**Comment by RomLecat** [comment]
The Bitnami charts indeed lacks configuration by not providing ipFamily and/or ipFamilyPolicy, but an IPv6-only service should be working in the first place.

Kubernetes DNS works fine, tested by installing ping in the pod then running:

```
root@immich-server-954d7b649-mqgj6:/usr/src/app# ping immich-redis-master
PING immich-valkey-master(immich-redis-master.immich.svc.cluster.local (<ipv6-prefix-redacted>:701::2:c924)) 56 data bytes
^C
--- immich-redis-master ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

root@immich-server-954d7b649-mqgj6:/usr/src/app# ping immich-redis-master -4
ping: immich-redis-master: Address family for hostname not supported
```

This is expected because the service is IPv6-only, so AAAA records works fine but querying A returns not host.

It does looks likes an error in ioredis: https://github.com/redis/ioredis/blob/main/lib/redis/RedisOptions.ts#L201
This issue: https://github.com/mastodon/mastodon/issues/27043 seems to mention a workaround by setting ?family= in the URL. Is there a way to provide a full Redis URL to Immich ?

**Comment by bo0tzz** [comment]
You can set REDIS_URL (see https://immich.app/docs/install/environment-variables#redis), which expects base64-encoded json matching the RedisOptions type you linked.

**Comment by RomLecat** [comment]
Thanks, that did work!
It does not seem very "standard" however, REDIS_URL usually refers to an URL like this : "redis://hostname:port/?options".

**Comment by bo0tzz** [comment]
It was done this way to support redis sentinel, which I believe isn't possible through that (admittedly more sensible) URL format.
