### ISSUE TITLE
Deleting all photos for a date in memory lane causes page to freeze

### ISSUE THREAD

**Issue by ben-basten** [immich-app/immich#10415]
### The bug

Deleting all photos for a date in memory lane causes the page to freeze, with an error in the browser console. This bug only occurs when all photos for a date are deleted. A page refresh is required to resume using immich.

### The OS that Immich Server is running on

Demo instance

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A - demo instance
```

### Your .env content

```Shell
N/A - demo instance
```

### Reproduction steps

```bash
1. Open a memory lane memory
2. Scroll down to see the asset grid with all photos for that date
3. Select all photos in the asset grid, using the checkboxes
4. Delete the photos using the ellipses menu in the top right of the screen
```

### Relevant log output

```shell
Uncaught (in promise) TypeError: m[18] is undefined
    Immutable 43
11.BOQw4eMJ.js:1:9630
```

**Comment by jrasm91** [comment]
Fixed in #12649
