### ISSUE TITLE
[BUG] iOS automatic backup no longer working in 1.37.0 build.73

### ISSUE THREAD

**Issue by raisinbear** [immich-app/immich#1041]
First off thanks for constantly improving this service! I've only been following for a couple of months and the progress is impressive to say the least. You guys rock :)

**Describe the bug**
I just updated to the latest iOS app **on two different devices** and upon starting it, new assets are no longer automaticall uploaded to the server, although automatic uploads are enabled. There is not even a brief sign of the process indicator on the cloud symbol at the top right, which I always saw even when there were no new assets. Uploads still work when manually triggered under the backup section. (Anecdotally, uploads also started after deleting assets through the app.) I tried logging out and completely reinstalling the app, but that didn't change anything. I noticed there is a new "Logs" section. Sadly I cannot export the log via the share button at the top. All apps I try to export to either say something along the lines of "failed to retrieve file" or the share sheet just hangs. So here's a screenshot:

![IMG_2458](https://user-images.githubusercontent.com/68740188/204992999-38e774cd-4f33-4fad-8ee6-e2ae77bb6127.png)

What I'm seeing on both devices on each start is the line "No Asset On Device - Abort Backup Process" (#6). Even if there are new images. Those then start to appear with a crossed out cloud symbol in the timeline and are correctly accounted for in the backup section of the app as not uploaded.
When there is **no** unsynced image on the phone, I actually see the progress indicator on the cloud symbol at the top.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [ x ] I have read thoroughly the README setup and installation instructions.
- [ x ] I have included my `docker-compose` file.
- [ x ] I have included my redacted `.env` file.
- [ x ] I have included information on my machine, and environment.

[docker-compose.yml.txt](https://github.com/immich-app/immich/files/10130289/docker-compose.yml.txt)
[env.txt](https://github.com/immich-app/immich/files/10130291/env.txt)

**To Reproduce**
1. Update to latest iOS app.
2. Make sure to have not yet synced images on your device.
3. Open iOS app.

**Expected behavior**
As in previous versions, new assets are correctly identified as such upon app start up and automatically uploaded to the server.

**Screenshots**
![IMG_2458](https://user-images.githubusercontent.com/68740188/204992999-38e774cd-4f33-4fad-8ee6-e2ae77bb6127.png)

**System**
- Phone OS [iOS, Android]: `iOS 16.1.1`
- Server Version: `1.37.0`
- Server OS: raspbian buster (32-bit)
- Mobile App Version: `1.37.0 build.73`

**Additional context**
-

**Comment by alextran1502** [comment]
Hmm I can't seem to reproduce this behavior. Do you mind take a screenshot of the backup screen and the Home Screen when you just open the app?

**Comment by raisinbear** [comment]
Sure! Thanks for the quick reply.

Home screen with one missing image (the one with the pen on the yellow piece of paper):
![IMG_2486](https://user-images.githubusercontent.com/68740188/205005643-0f047a4f-fe8a-4a3f-acf4-75d3577f9ac1.png)

Backup screen that now shows 2 missing images as the screenshot above was taken and not uploaded either:
![IMG_2487](https://user-images.githubusercontent.com/68740188/205005636-6e2bf4bc-e7fa-4232-973a-b5b72d9cc19e.png)

**Comment by raisinbear** [comment]
One more thing I just noticed is that automatic backup would work *if the app opens without splash screen*. I don't know what kind of app state that translates to in iOS. Usually when I close the app (swiping up) and open it again at some point, I see the splash screen. If I swipe up and immediately open it again - or if I lock the phone with the app open and wake it again - automatic backup would resume. So I guess reproducing the issue *may* require force closing the app, taking an image / screenshot and reopening.

**Comment by alextran1502** [comment]
> One more thing I just noticed is that automatic backup would work *if the app opens without splash screen*. I don't know what kind of app state that translates to in iOS. Usually when I close the app (swiping up) and open it again at some point, I see the splash screen. If I swipe up and immediately open it again - or if I lock the phone with the app open and wake it again - automatic backup would resume. So I guess reproducing the issue *may* require force closing the app, taking an image / screenshot and reopening.

Thanks, this narrows down where the problem might occur. I will check and let you know
