### ISSUE TITLE
[Feature]: Integrate with Android System Picture Picker

### ISSUE THREAD

**Issue by godismyjudge95** [immich-app/immich#1045]
### Feature detail

When using Android (and I would imagine iOS - but I have no experience with it) there are occasionally locations where an app can request Android to provide an image.  Android will open up a special picture picker view that will show local files, but there is an option in the sidebar to choose an app which will then allow you select images from that app.

It would be awesome if Immich would show up under these circumstances, as it would make picture selection from 3rd party apps possible without downloading the photos or going to Immich and choosing share from there.

Examples of where this would be useful:
- long press on homescreen, choose the change wallpaper button, choose Immich from the sidebar, finally choose the image to set as the wallpaper
- when texting/messaging someone, tapping the attach image button, choose Immich from the sidebar, finally choose images and send the message

For reference here is the android docs on it:  https://developer.android.com/training/secure-file-sharing

I am not sure if there is an equivalent iOS feature.

### Platform

Mobile App

**Comment by bo0tzz** [comment]
Duplicate of #992

**Comment by akostadinov** [comment]
Could you provide details how to use this feature? Should it be enabled somehow? I look at telegram and don't see how to attach stuff from immich.
