### ISSUE TITLE
[BUG] Copy image button in navbar doesn't work

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#1047]
**Describe the bug**
When clicking the copy image button on the navbar, it doesn't work.
The following error appears in the console log:
```
Uncaught (in promise) ReferenceError: ClipboardItem is not defined
    Immutable 45
index-581660b7.js:1:1230
    u Immutable
    AsyncFunctionThrow self-hosted:811
    Immutable 2
    forEach self-hosted:203
    Immutable 22
    InterpretGeneratorResume self-hosted:1819
    AsyncFunctionNext self-hosted:807
    Immutable 4
    forEach self-hosted:203
    Immutable 3
```

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Go to an image in Immich through the browser
2. Click on 'copy image' button
3. See error in console log

**Expected behavior**
I expected the image to be copied to my clipboard

**System**
- Phone OS [iOS, Android]: `Android 12`
- Server Version: `v1.37.0`
- Mobile App Version: `v1.36.1`

**Comment by bo0tzz** [comment]
Which browser/browser version are you using?

**Comment by alextran1502** [comment]
@JVT038 Do you use this feature while accessing your instance on http or https?

**Comment by JVT038** [comment]
Firefox 107.0.1

**Comment by JVT038** [comment]
> @JVT038 Do you use this feature while accessing your instance on http or https?

HTTPS, reverse proxy with NGINX proxy manager

**Comment by bo0tzz** [comment]
Firefox doesn't support copying images to the clipboard by default - you'll need to change a setting for it to work. See https://github.com/LuanEdCosta/copy-image-clipboard#enable-clipboard-api-features-in-firefox

**Comment by JVT038** [comment]
Thanks, it works now!
