### ISSUE TITLE
Bug in the date format when you want to edit the date and time

### ISSUE THREAD

**Issue by aloyer** [immich-app/immich#10482]
### The bug

![Capture d'écran 2024-06-19 110914](https://github.com/immich-app/immich/assets/64027900/ff518450-7816-40da-922b-15b87f236ce0)
When you edit teh date the year could have 6 digits instead of 4. It doesn't make sense

### The OS that Immich Server is running on

Ubuntu server 2023

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.4

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
No necessary in that context
```

### Your .env content

```Shell
No necessary in that context
```

### Reproduction steps

```bash
1. Edit time and chage the year

...
```

**Comment by bo0tzz** [comment]
Dupe: #8531
