### ISSUE TITLE
[BUG] Manual backup takes a while to start

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#1050]
**Describe the bug**
When I manually start a backup by pressing the 'Start backup' button at the bottom of the backup page, it takes around ~1 minute before any uploading starts.
It's a bit annoying that it doesn't start instantly.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Go to 'Backup page'
2. Click on 'Start backup'
3. Wait a while before anything happens

**Expected behavior**
I expected the app to start uploading (near) instantly

**System**
- Phone OS [iOS, Android]: `Android 12`
- Server Version: `v1.37.0`
- Mobile App Version: `v1.37.0`

**Comment by alextran1502** [comment]
How many asset do you have on the device? This process usually start instantly.

Have you tried using local IP to see if this is related to network issue?

**Comment by JVT038** [comment]
I think it's a network issue, you're right.
I've tried a local IP and it worked instantly.
I'm using an NGINX reverse proxy + Cloudflare, so I'll investigate those two services.

**Comment by alextran1502** [comment]
Thank you for the report. I will close this issue for now.
