### ISSUE TITLE
highlight photo to keep

### ISSUE THREAD

**Issue by krzemyczek** [immich-app/immich#10503]
### The bug

it's very non-intuitive behavior when the photo which is highlighted is the one which will be kept. the problem is that we click "trash" button, so every time when i delete duplicate i have to ignore this button to not be confused.

It would be more intuitive when the photo with "trash" tag would be highlighted to red, because we will click button "trash", so yea. the same when we add photos to album. we select photo we going to add to album. Not the photo we _not_ going to add.

### The OS that Immich Server is running on

TrueNAS

### Version of Immich Server

v1.106.3

### Version of Immich Mobile App

v1.106.4

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not matter
```

### Your .env content

```Shell
not matter
```

### Reproduction steps

```bash
1. go to "Utilities"
2. then "review duplicates"
3. if more than 1 duplicate photos you will see highlighted photo to keep
4. click "trash" button which will delete every thing which is not highlighted (and with tag "trash")
```

### Additional information

![image](https://github.com/immich-app/immich/assets/81762967/8f84eaa0-0b11-4f15-9a2a-ae4023d17e45)

**Comment by danieldietzler** [comment]
It is not only highlighted, but it also literally says "keep" on it, right? If anything this sounds to me more like a feature request than an issue
