### ISSUE TITLE
[BUG] Manual backup stops when changing apps and the screen turns off

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#1051]
**Describe the bug**
When I manually start a backup and I switch apps, the backup stops.
The backup also stops when I turn off my phone or the screen automatically goes dark due to battery saving.
I have turned off the automatic background backup service, because I only want files to be uploaded when I trigger it manually.
I don't know if this is intended behavior, but I find it annoying that the backup stops upon switching apps when I manually trigger it.

I checked the logcat info through ADB, and this was shown:
```
flutter : [APP STATE] inactive
flutter : Attempting to disconnect from websocket
flutter : Disconnect to Websocket Connection
flutter : Backup was cancelled by the user
flutter : [APP STATE] paused
```
The above lines appear when turning off the phone and when switching apps.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Go to the backup page.
2. Click on 'Start backup'
3. Switch apps and/or turn off the phone
4. See the backup being interrupted and stopped.

**Expected behavior**
I expect the backup to continue running in the background until all the files are uploaded. 

**Screenshots**
![image](https://user-images.githubusercontent.com/47184046/205446440-cdb01c53-81aa-4dd8-a1a5-d758db608b2d.png)

The section with info about the current item being uploaded still contains the normal date and filename. It just doesn't show any progress, and the backup button is blue instead of red when switching back to Immich.

**System**
- Phone OS [iOS, Android]: `Android 12`
- Server Version: `v1.37.0`
- Mobile App Version: `v1.37.0 build 58`

**Comment by alextran1502** [comment]
This is working as intended because the manual backup is the foreground process, so when you switched app? It is put into the background, hence stopping all operations

**Comment by JVT038** [comment]
Ah OK, good to know.
Can this be changed? Or is that not possible?

**Comment by alextran1502** [comment]
Unfortunately, it cannot be. Background backup is now only triggered when you take a photo.
