### ISSUE TITLE
[Feature]: Forgot password option

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#1052]
### Feature detail

If I forget my password, I would like to be able to do the following to reset it:

1. Click on 'Forgot Password' at the login screen
2. Enter my e-mail address in a new screen
3. If an user with that email address exists, an email should be sent to the user's email address, containing a link that allows the user to reset their password. This link expires in 10 minutes or something like that and this can be managed by storing JWT tokens in a database.

The admin can optionally configure an SMTP server with environment variables. If no valid SMTP server is configured, the email functionalities shouldn't be available.

I would like to have this for both web and mobile. Additionally, server-side changes are necessary for this.

### Platform

Web

**Comment by alextran1502** [comment]
We are not planning on supporting email reset password

**Comment by ahanel13** [comment]
@alextran1502 I don't want to open a new issue so I figured I ask here. 

Could we revisit this feature request? I think if immich wants to support multiple users, e.i. families, not allowing users to reset their own passwords it a big pain point. I already have my SMTP server setup with immich, it's just lacking this feature now.

Would this be accepted if someone wanted to make a PR?
