### ISSUE TITLE
[BUG] [OIDC] Apps logs out when closed

### ISSUE THREAD

**Issue by christiaangoossens** [immich-app/immich#1054]
**Describe the bug**
The mobile app, on Android, logs out whenever the app is closed when using OIDC login. This is independent of token lifetimes.

**Task List**

Other steps seem not relevant, if necessary let me know 😅

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**

1. Configure OIDC
2. Use it to login to the mobile app
3. Close the mobile app (either force close or swipe up from the task manager)
4. App is logged out

**Expected behavior**
App should remain logged in.

**Screenshots**
Not relevant.

**System**
- Phone OS [iOS, Android]: `Android`
- Server Version: `1.36.1`
- Mobile App Version: `1.37.1`

**Additional context**
Using Authentik as IdP. Writing this issue on mobile, can add additional info on pc if wanted.

**Comment by alextran1502** [comment]
Confirmed

**Comment by akoyaxd** [comment]
I can not reproduce with the steps in OP. I use Immich with Authentik as well.
I had the same issue after my phone ran out of battery for a few days, though.

Server Version: 1.37.0
Mobile Version: 1.37.1 (Android)
Authentik: 2022.10.1

**Comment by Morethanevil** [comment]
Sometimes I get logged out and I don't know why. This is annoying 🙁

Android app with standard login (mail / password)

Maybe this is related? 🤔

**Comment by bt90** [comment]
Force closing does not trigger a logout for me. But the last app updates via Google Play have always forced me to log in again.

**Comment by alextran1502** [comment]
> Force closing does not trigger a logout for me. But the last app updates via Google Play have always forced me to log in again.
> 
> Standard user/password auth Mobile Version `1.40.0 build.63`

Hello, do you mind providing a screen capture of the behavior?

**Comment by bt90** [comment]
In both cases I was greeted with a message that a new server version was available. The username and password fields were both blank, but my server URL was pre-filled.

I tried to trigger this by installing an older version and upgrading. Since this is not so easy with the Playstore version, I uninstalled it and installed an older F-droid version instead. However, installing the update did not cause a logout. Unfortunately, I stumbled across another bug, it seems. I now have a few duplicates on my server :confused:

**Comment by christiaangoossens** [comment]
To note, I have not encountered this with password signin, only with SSO.

**Comment by akoyaxd** [comment]
I could reproduce the issue of OP after updating my Authentik to ~2022.12.1
To fix this I extended the Access Token validity. Does Immich use the refresh token or do you need re login every time it expires?

![image](https://user-images.githubusercontent.com/22196236/211017320-404a4121-d9d3-44b6-9765-eec4586b4993.png)

**Comment by jrasm91** [comment]
@akoyaxd We don't use the refresh token and we only the use `accessToken` once, during login, so I would be surprised if extending the lifetime of the token in Authentik fixes the issue. At the end of the OAuth flow the mobile app gets an Immich issued JWT which (should be) saevd for future requests. No request are made to the OAuth service after that.

**Comment by akoyaxd** [comment]
You are right. After testing again, this setting did not change anything. I fear, I just forgot to set the "stay logged in". :S

#1261

**Comment by akoyaxd** [comment]
@christiaangoossens Do you have to reenter the Server URL again? Did you set the "stay logged in" checkbox?

**Comment by bt90** [comment]
Hmm. Did we completely rule out the server yet? An invalid token would also trigger a relogin?

**Comment by jrasm91** [comment]
> Hmm. Did we completely rule out the server yet? An invalid token would also trigger a relogin?

The token lifespan was 7 days up until a recent change (30 days now), but if this was the root cause then this issue would not be unique to OIDC, but apply to password logins as well.

I use OAuth and have no had any problems personally. I did just log back in without checking the `Stay logged in` checkbox and can confirm that when I did so I had to login again next time I opened the app. 

I agree we should remove the `Stay logged in` box, always save the server endpoint, and make `/api` optional.

Can anybody confirm that they still have a problem, even when checking the `Stay logged in` button?

**Comment by jrasm91** [comment]
> Well it happens for me as well and i only use the password login

Can you send a recording of this happening?

**Comment by bt90** [comment]
Sadly, i've not been able to reproduce it as mentioned above.

**Comment by jrasm91** [comment]
> Sadly, i've not been able to reproduce it as mentioned above.

It sounds like your are just experiencing session expression, which used to be 7 days.

**Comment by bt90** [comment]
Interesting. Has this changed recently?

**Comment by jrasm91** [comment]
https://github.com/immich-app/immich/releases/tag/v1.40.0_63-dev

#1187

**Comment by bt90** [comment]
So i get logged out of the app after a fixed time period?

**Comment by jrasm91** [comment]
Yes. We're working on changing this to be indefinite with the ability to revoke device access remotely.

**Comment by jrasm91** [comment]
I believe this has been fixed. Anyone still feeling this issue?

**Comment by dugite-code** [comment]
I tried yesterday with my Authentik server and was logged out when I closed the app

**Comment by jrasm91** [comment]
What version of the app/server are you running @dugite-code?

**Comment by dugite-code** [comment]
@jrasm91 I pulled the container with the release tag so it would have been 1.52.0 as I was testing just a few hour before the 1.52.1 release was announced.

I'll give the newer release a go in a bit and report back

**Comment by christiaangoossens** [comment]
I believe the issue is fixed too, I have not encountered it anymore with the newer versions.
