### ISSUE TITLE
‘Load original image’ not working on mobile

### ISSUE THREAD

**Issue by jaisinghdhaliwal** [immich-app/immich#10556]
### The bug

I think one of the new updates must have broken this. Opening an image always shows the large thumbnail even with ‘load original image’ enabled. This used to work before but appears to have been broken. Tested on iPhone 15 Pro Max and iPad Pro. 

### The OS that Immich Server is running on

Linux Mint

### Version of Immich Server

1.106.2

### Version of Immich Mobile App

1.106.3 build.160

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Enable Settings>AssetViewer>LoadOriginalImage
2. Restart app (optional)
3. Open image and zoom in to see extremely heavy compression
4. Can download original image and see that the quality is much better
...
```

### Additional information

This is a feature that I know for certain was working in a previous version but one of the iOS app updates much have broken it.

**Comment by bo0tzz** [comment]
When you reproduce this, what do the app's logs say?

**Comment by jaisinghdhaliwal** [comment]
> When you reproduce this, what do the app's logs say?

I have app logging set to finest and turned on troubleshooting. I open the app and the logs seem to bring up “Local album XXXXXX has not changed. Skipping sync” and other clean ups and socket opens. I clear the log and tap on multiple images. Nothing gets added to the log.

**Comment by fabianbees** [comment]
This bug is NOT specific to iOS, it is also reproducable on Android 14.

**Comment by alextran1502** [comment]
Looks like this functionality was removed in #7016

**Comment by jaisinghdhaliwal** [comment]
> Looks like this functionality was removed in #7016

Could functionality be restored? For now, 'Load original image' seems to be a toggle that doesn't serve any purpose. Could toggling 'Load Original Image' use the 'original_image_loader' that was removed in that commit?

**Comment by omeryagmurlu** [comment]
This is probably also the reason behind https://github.com/immich-app/immich/issues/9628

**Comment by Danilado** [comment]
And behind #10297 , I suppose

**Comment by wlamers** [comment]
Same here [#11048](https://github.com/immich-app/immich/issues/11048)

**Comment by MK73DS** [comment]
I have the opposite issue for local images. I *don't* want the original to be displayed but the medium one from the server (because some are 100 to 200MPx and make the whole app lag and freeze). But no matter how I change the settings in the Asset Viewer section and clear cache, it stays the same.
If this is a separate issue I will open a new issue but I think it's related to this one and the setting doesn't work as expected?

**Comment by Danilado** [comment]
> I have the opposite issue for local images. I _don't_ want the original to be displayed but the medium one from the server (because some are 100 to 200MPx and make the whole app lag and freeze). But no matter how I change the settings in the Asset Viewer section and clear cache, it stays the same. If this is a separate issue I will open a new issue but I think it's related to this one and the setting doesn't work as expected?

I had a talk in discord about that. Apparently the load original image functionality was removed to prevent the lag/freeze issue
But I guess it still occurs if you have the original photos on your device

**Comment by jaisinghdhaliwal** [comment]
> I have the opposite issue for local images. I _don't_ want the original to be displayed but the medium one from the server (because some are 100 to 200MPx and make the whole app lag and freeze). But no matter how I change the settings in the Asset Viewer section and clear cache, it stays the same. If this is a separate issue I will open a new issue but I think it's related to this one and the setting doesn't work as expected?

This is also very confusing because for local images. Local images appears to have a lower resolution than the same local image when viewed in the iOS photos app. I’ve attached 2 screenshots to show my point - one screenshot is an image zoomed in on the native photos app, the other is the same photo zoomed into the same level on Immich (the same local file). 
![IMG_5017](https://github.com/user-attachments/assets/9d094f8c-faae-4471-9d7f-6ba81bf0d4d4)
![IMG_5018](https://github.com/user-attachments/assets/1acd8608-bdec-40e4-a26f-f739211e06ec)

**Comment by jaisinghdhaliwal** [comment]
> I have the opposite issue for local images. I _don't_ want the original to be displayed but the medium one from the server (because some are 100 to 200MPx and make the whole app lag and freeze). But no matter how I change the settings in the Asset Viewer section and clear cache, it stays the same. If this is a separate issue I will open a new issue but I think it's related to this one and the setting doesn't work as expected?

Also for this option, you can go to advanced and select prefer remote images, that way it always loads the thumbnail from the server.

**Comment by MK73DS** [comment]
> Also for this option, you can go to advanced and select prefer remote images, that way it always loads the thumbnail from the server.

The thumbnail is fine. The issue is when I view the photo. It loads the local image (which can be arbitrarily large) instead of the medium sized one from the server as I selected in the settings.
It's not really a deal breaker sure, but the app freezes for 5 to 10 seconds when loading very large images even if they're locally stored.

> This is also very confusing because for local images. Local images appears to have a lower resolution than the same local image when viewed in the iOS photos app. I’ve attached 2 screenshots to show my point - one screenshot is an image zoomed in on the native photos app, the other is the same photo zoomed into the same level on Immich (the same local file).

I don't think I noticed a quality drop when zooming on local image. Are you sure the image you are seeing in Immich isn't the medium one from the server?
Also I should have noticed I'm using the Android app, if this matters.


> I had a talk in discord about that. Apparently the load original image functionality was removed to prevent the lag/freeze issue But I guess it still occurs if you have the original photos on your device

Did you get an answer? Is that a separate issue from this one? If it is, I would like to open a new issue instead of polluting this one.

**Comment by jaisinghdhaliwal** [comment]
> The thumbnail is fine. The issue is when I view the photo. It loads the local image (which can be arbitrarily large) instead of the medium sized one from the server as I selected in the settings. It's not really a deal breaker sure, but the app freezes for 5 to 10 seconds when loading very large images even if they're locally stored.

By selecting that option, it is supposed to load the large thumbnail image when you open the image regardless of whether the file is also saved locally, for me it is working as intended. 

> I don't think I noticed a quality drop when zooming on local image. Are you sure the image you are seeing in Immich isn't the medium one from the server? Also I should have noticed I'm using the Android app, if this matters. 

Yes I am sure it is the local file as the quality of the large thumbnail preview is much worse than what I showed - I can see this when I have prefer remote images enabled. The local image in the Immich app appears to be a lower resolution version of the local image whereas the remote image is lower resolution AND heavily compressed.

**Comment by MK73DS** [comment]
> By selecting that option, it is supposed to load the large thumbnail image when you open the image regardless of whether the file is also saved locally, for me it is working as intended.

Yes, but it also loads every thumbnail from the server as well. Since my Immich library is 100% photos from my phone, I think this is unnecessary. It's a workaround for this issue, but it doesn't solve it. 

> Yes I am sure it is the local file as the quality of the large thumbnail preview is much worse than what I showed - I can see this when I have prefer remote images enabled. The local image in the Immich app appears to be a lower resolution version of the local image whereas the remote image is lower resolution AND heavily compressed.
> 
> Edit: Below is the remote version of the image that I used before (with prefer remote image enabled), showing that the local image that it is showing is not the remote one and that the quality of local images just displayed worse than the native app.

Maybe this is iOS specific? I am not familiar at all with Apple devices I'm sorry. I definitely don't get this behavior on my device.

**Comment by omeryagmurlu** [comment]
Is the team aware of this bug? I don’t understand how this bug is not one of the top priority bugs right now?

Not being able to show the images uploaded to it is a bad spot to be in as an image management application in my opinion.

**Comment by bo0tzz** [comment]
@omeryagmurlu I'm not sure what you mean, the image is still displayed, just not the full-size original.

Trying to decide priorities for a team you're not a part of is generally considered bad form.
