### ISSUE TITLE
Searching for text in documents, memes, etc does not work currently

### ISSUE THREAD

**Issue by big-chungus69420** [immich-app/immich#10574]
### The bug

Due to OCR functionality not being present in immich, searching for any pics of documents, memes etc does not work properly at all.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.3 build.143

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1.Going to Immich
2. Clicking on the Search bar
3. Searching for a document by writing part of it for eg (Inpatient Hospital)
```

### Relevant log output

```shell
It shows completely irrelevant results, unrelated to the query typed.
```

### Additional information

The image I'm looking for: 
![20240606_120642](https://github.com/immich-app/immich/assets/87696847/061ffe47-924e-43df-b364-dd3d3c2d2535)
The results I get: 
![Screenshot_240623_00001](https://github.com/immich-app/immich/assets/87696847/e5e03b02-4f49-4bb1-bebc-e07c95ccb5ee)

**Comment by bo0tzz** [comment]
I'm not sure what you're trying to say - Immich indeed doesn't support OCR, so searching by text not working isn't a bug, it's just obvious?
