### ISSUE TITLE
Documentation suggestion:  Backup and Restore page needs restart in YML

### ISSUE THREAD

**Issue by bcsteeve** [immich-app/immich#10578]
### The bug

I've had several times over the years where I notice my backup isn't working.  I mean the backup described on this page: https://immich.app/docs/administration/backup-and-restore/

I followed the instructions and copy/pasted as appropriate, and each time it would work fine... for awhile.  Then it wouldn't.

I think the problem is simple:  When I restart the machine, Immich is restarting but the backup isn't.  It eventually dawned on me that there's no restart logic.  I haven't tested, but I expect simply adding:

    restart: always

to the backup section of docker-compose.yml will resolve this.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
As described
```

### Relevant log output

```shell
n/a
```

**Comment by mmomjian** [comment]
thanks!
