### ISSUE TITLE
Scrolling initiates a "tap" from the OS

### ISSUE THREAD

**Issue by Fmstrat** [immich-app/immich#10608]
### The bug

When scrolling up or down, many of the scroll actions register a tap in the OS (Android). This means if you have haptic feedback turned on, your phone constantly vibrates when scrolling in Immich.

### The OS that Immich Server is running on

Android

### Version of Immich Server

n/a

### Version of Immich Mobile App

1.106.4

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. Unlock Android device
2. Go to Settings
3. Go to Accessibility
4. Turn on Haptics and Touch Feedback
5. Open Immich
6. Scroll your timeline
7. Vibrate.. Vibrate.. Vibrate..
...
```

### Relevant log output

```shell
n/a
```

### Additional information

n/a

**Comment by alextran1502** [comment]
You can turn off haptic feedback in the app by going to app Settings > Preference > Disable haptic feedback
