### ISSUE TITLE
Immich CLI add to album broken on windows

### ISSUE THREAD

**Issue by waqasali101** [immich-app/immich#10617]
### The bug

NOTE: I am awaring a recent fix went in to fix recursive behavior on windows, this test is including that fix

Add to album is broken when using CLI on windows.
Reason for this is that filePath in assests.ts is probably being unifixied somewhere and following line in method getAlbumName resolves to undefined

const folderName = os$1.platform() === "win32" ? filepath.split("\\").at(-2) : filepath.split("/").at(-2);

filePath 

### The OS that Immich Server is running on

Windows 11

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. On windows, latest version including changes to fix recursive bug on windows
2. 
3.
...
```

**Comment by bo0tzz** [comment]
@fky2015 is this a regression from your PR #10430?

**Comment by waqasali101** [comment]
looking at code it does not seem like a regression

**Comment by waqasali101** [comment]
@bo0tzz you were right, this is caused by #10430
this is because convertPathToPattern changes slashes.
I believe this is intended behavior of convertPathtoPattern from fast-glob.
does that mean we should only split on / ?

**Comment by fky2015** [comment]
Never mind the above question. I'll make a PR ASAP.

**Comment by fky2015** [comment]
> does that mean we should only split on / ?

For compatibility (maybe future this function will be called with both `/` and `\`), I use `path` to substitute the manually-written parsing code.
