### ISSUE TITLE
[Feature]: Multiple Image Download

### ISSUE THREAD

**Issue by ajoshuasmith** [immich-app/immich#1064]
### Feature detail

Ability to select multiple photos and the option to download all of those selected photos. 

Currently you would need to individually select each image and hit the download option.
(Unless I am missing something)

### Platform

Web

**Comment by alextran1502** [comment]
You are not missing anything, we haven't implemented this on the main timeline yet 🥲

**Comment by jalin2** [comment]
It would be great to have this feature within albums and shared albums.

**Comment by ameyp** [comment]
Was this actually fixed by #1266? I still don't see an ability to select multiple photos on my timeline/in an album and download them, or download an entire album.

**Comment by alextran1502** [comment]
Can you show us what you see? Is the album your own album or is shared with you?

**Comment by ameyp** [comment]
It's my own album, not shared with anyone. Which screen would you like to see? On the list of albums, long-pressing (on Android or iOS) does nothing. After opening an album and selecting a few photos by long-pressing, this is what I see:

![Screenshot_20230618_164200_Gallery](https://github.com/immich-app/immich/assets/83116/dbddd770-82e9-4e96-aedd-2d4d4cef6c2f)

**Comment by alextran1502** [comment]
@ameyp we haven't implemented this feature on the mobile device yet 😁

**Comment by ameyp** [comment]
Cool, ty. I'm gonna delete my screenshot now because I'm kinda paranoid about privacy 😅

**Comment by Cheekie25** [comment]
> @ameyp we haven't implemented this feature on the mobile device yet 😁

Hello,
Is this feature planned to be implemented for mobile ?

**Comment by loxoron218** [comment]
Shouldn't be this issue open, since this feature hasn't been implemented? :)
> > @ameyp we haven't implemented this feature on the mobile device yet 😁
> 
> Hello, Is this feature planned to be implemented for mobile ?

**Comment by DrieWielRr** [comment]
I see the same issue, requests like this keeps getting closed without actually providing the option..
I've seen many pushbacks with statements like "Immich was meant as a backup not a gallery replacement", but imho it has all the bells and whistles to be exactly that..
Not only that but most of us run this at home to backup pictures from our phone and remove them locally to save space but not being able to recall pictures back to the phone for use with other apps is just painfull...
The worst part is even that there is a "share with app" function within the app when I multiselect where it downloads my selection and hands them over to another app (so the immich-app already has the multiple-download functionality in it, there is just no "download to phone" function yet)..
The problem we face is that many apps dont directly support all the functions with the "share-to-app", Instagram for example will not allow you create a regular post this way only stories and reels..
