### ISSUE TITLE
Cant add photos to album from Search window

### ISSUE THREAD

**Issue by picarica** [immich-app/immich#10651]
### The bug

cant add photos from search to album, it can be easily added from default photo page

### The OS that Immich Server is running on

truenas-Dragonfish-24.04.1.1

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.4

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. open mobile app
2. search some string
3. try to select two or more images
4. try to add to album
4. window suddenly closes
```

### Relevant log output

```shell
not relevant
```

### Additional information

uploading video with demostration
https://github.com/immich-app/immich/assets/45492894/20067d55-73f3-478a-bdd7-4345509e1267

**Comment by bo0tzz** [comment]
Dupe: #8635
