### ISSUE TITLE
[BUG] Immich machine learning not working with objects

### ISSUE THREAD

**Issue by big1tasty** [immich-app/immich#1078]
**Describe the bug**
Things recognition is not working.
"no object info.... Avaliable"
![image](https://user-images.githubusercontent.com/64231135/206705808-cc45ff9e-b4f4-4921-958c-44c95738374b.png)

[docker-compose.yml.txt](https://github.com/immich-app/immich/files/10194920/docker-compose.yml.txt)
[env.txt](https://github.com/immich-app/immich/files/10194924/env.txt)

the Docker host is installed on a ubuntu server 20.04, backup working fine!

The Logs from Immich Machine learning docker:
`Illegal instruction (core dumped)`

**Comment by alextran1502** [comment]
Please take a look at Known Issue in the readme file for more information about this error
