### ISSUE TITLE
immich_server container makes request to registry.npmjs.org every 30 seconds

### ISSUE THREAD

**Issue by justinhorton** [immich-app/immich#10796]
### The bug

This may be working as designed, but I'm not familiar enough with NodeJS apps to say. I noticed in my pi-hole logs that registry.npmjs.org had become a top hit and traced it back to the `immich_server` container. When I first set up immich and its firewall rules earlier this year, I wasn't seeing any traffic to the public internet after the models were downloaded, which is consistent with what Alex said here:

["Everything should work offline after the models get downloaded and the reverse geocoding files get downloaded"](https://www.reddit.com/r/immich/comments/179ay90/comment/k554lfe)

Can you confirm whether this frequency of requests to the NPM registry is intended?

### The OS that Immich Server is running on

debian 12 bookworm

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
same as the release docker-compose.yml
```

### Your .env content

```Shell
standard
```

### Reproduction steps

```bash
Start the immich stack and see DNS requests to registry.npmjs.org every 30 seconds, accompanied by HTTPS connections to one of the registry.npmjs.org IPs.
```

**Comment by mertalev** [comment]
I'm not aware of a reason it should be making requests to npmjs.org, let alone every 30 seconds. Others can chime in if this is a known / expected behavior.

**Comment by mmomjian** [comment]
Can you please add the following to the immich_server docker compose container?

```
healthcheck:
  disable: true
```
