### ISSUE TITLE
Transcoded videos don’t play any more in Mac Safari

### ISSUE THREAD

**Issue by Str1atum** [immich-app/immich#10814]
### The bug

Since 1.107 the recoded videos don’t play in Mac Safari 17.5 any more.
File itself is loaded and can be downloaded, but it is not playable. Chrome on same machine works fine.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

1.107.2

### Version of Immich Mobile App

1.107.2

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Standard
```

### Your .env content

```Shell
Standard
```

### Reproduction steps

```bash
1. Open a video in Mac Safari
2.
3.
...
```

**Comment by alextran1502** [comment]
Do you use iOS 18? Do older videos work, or just newly updated ones?

**Comment by mmomjian** [comment]
How are you connecting? Using any proxy?

**Comment by Str1atum** [comment]
> Do you use iOS 18? Do older videos work, or just newly updated ones?

Just on Mac, iOS works fine. All videos affected.

**Comment by Str1atum** [comment]
> How are you connecting? Using any proxy?

Traefik 3.0.4 with let’s encrypt certificate

**Comment by mmomjian** [comment]
Please connect directly to :2283

**Comment by Str1atum** [comment]
> Please connect directly to ipaddress:2283

tried that and disabled Traefik - direct connect with only HTTP - still the same error, just a spinning wheel and the video doesn't play.

**Comment by elisiariocouto** [comment]
I'm having the same issue. Safari 18.0 on macOS 15 Developer Beta 2. Cloudflare Proxy + Caddy. If I copy the video URL and open it in a new tab, it works. In Safari's developer tools, I can see some 206 but with an error color:
<img width="365" alt="Screenshot 2024-07-04 at 19 55 36" src="https://github.com/immich-app/immich/assets/818914/f45954d4-eb55-4258-96fc-83e29157a601">

Seems like the same behaviour as https://github.com/immich-app/immich/issues/1197

**Comment by EliasMarine** [comment]
I am having the same issue, running immich v1.107.2 and safari Version 17.5 (19618.2.12.11.6). No issues using Brave/chrome browsers.

**Comment by rmohns** [comment]
Same experience here, but it's ANY WebKit-based Mac browser. Thumbnails play, but the viewer/detail view hangs up with a spinner. If I click it the poster image is replaced with a black screen. I get the same behavior on Safari, Orion and iCab.

- Immich v1.111.0
- MacOS version 14.5 (23F79)
- Browsers affected:
  - Safari version 17.5 (19618.2.12.11.6)
  - Orion version 0.99.128.1-beta (WebKit 619.1.11.111.2)
  - iCab version 6.2.3
- Browsers _not_ affected:
  - Arc version 1.53.1 (52180) (Chromium Engine Version 127.0.6533.73)
  - Firefox 128.0.3

I do NOT see this behavior in iOS browsers, including Safari and iCab Mobile; video plays fine. I'm running iOS 17.5.1. Mac M2 Pro. So it sure does look like a Mac WebKit problem.

**Comment by rmohns** [comment]
Problem still exists in v1.112

**Comment by rllynch** [comment]
I'm experiencing the same issue - thumbnails play but I get the spinner trying to view any videos with:

- Immich v1.112.1
- MacOS version 14.5
- Safari 17.5 (19618.2.12.11.6)

The following browsers on the same Mac can successfully play the video:

- Firefox 129.0.1
- Chrome 125.0.6422.77

It also plays successfully on iOS 17.5.1 Safari and the iOS Immich app (1.112.1 build.169).

**Comment by peremenov** [comment]
Also confirming on Immich v1.115.0

**Comment by 3zero2** [comment]
Following as this is happening to me as well on v1.117.0

**Comment by rmohns** [comment]
Thank you for fixing this! 🎉
