### ISSUE TITLE
Mismatching german translation for facial recognition

### ISSUE THREAD

**Issue by jpaffrath** [immich-app/immich#10848]
### The bug

If you select German as the web frontend language, the job description for _face detection_ and _facial recognition_ is the same (both gets translated to "Gesichtserkennung").

When I look into the language mappings, I can see that there is a separate translation for facial recognition:
`"machine_learning_facial_recognition": "Gesichtszuordnung",` 
Which german translation makes much more sense compared to the current implementation. Yet, it does not seem to be used in the frontend.

Also, the sentence describing the _face_detection_description_ is kinda misleading:
`werden nach Abschluss der Gesichtserkennung in eine Warteschlange für die Gesichtserkennung gestellt`.
In my opinion it should translate to:
`werden nach Abschluss der Gesichtserkennung in eine Warteschlange für die Gesichtszuordnung gestellt`.

### The OS that Immich Server is running on

Debian Docker

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not needed
```

### Your .env content

```Shell
Not needed
```

### Reproduction steps

```bash
1. Login into immich as admin
2. Change language to "German"
3. Visit Admin->Jobs
4. Scroll down to "Face Detection" Job
```

**Comment by michelheusschen** [comment]
This is already resolved on main. You can contribute to translations using Weblate: https://hosted.weblate.org/projects/immich/immich/de/

![image](https://github.com/immich-app/immich/assets/59014050/ff123ca3-54df-4b52-b12a-f352deb5575e)
