### ISSUE TITLE
[Feature]: Save image with upload date to avoid put many images in 1970 when not detects correct date

### ISSUE THREAD

**Issue by nando2301** [immich-app/immich#1087]
### Feature detail

I have many photos within 1970 year received by whatsapp, messenger, etc

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/32605309/206873987-085a0cde-162d-46ed-bfa7-5df719661d24.png">

Please consider save images with upload date and then with discovery they will be moved to correct date.

### Platform

Server

**Comment by florihupf** [comment]
I tried to dig around in the code a bit for this startingwith the CLI tool.  And even through the upload seems to read the exif and passes it as a json, the server ignores it.

Happy to provide patches if you guys have some pointers.

**Comment by jrasm91** [comment]
Is this still an issue?

**Comment by florihupf** [comment]
For me it isn’t anymore due to the fact that we can use file dates when uploading via CLI when mega data is absent.
