### ISSUE TITLE
Foreground backup should keep the screen on

### ISSUE THREAD

**Issue by bt90** [immich-app/immich#10914]
### The bug

Just tried to backup 3k photos from a Google Pixel 7a and the backup stops each time the screen turns off. An ongoing backup should keep the screen awake.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. start a foreground backup
2. wait for the screen to go off
3. the backup job is aborted
```

**Comment by bo0tzz** [comment]
Dupe: #8217

This is not a bug, please use the discussions for feature requests.

**Comment by bt90** [comment]
> Dupe: #8217

Is it? That issue seems to be iOS specific?

**Comment by bo0tzz** [comment]
Not anymore :stuck_out_tongue:
