### ISSUE TITLE
Immich CLI not deleting duplicates

### ISSUE THREAD

**Issue by andreybavt** [immich-app/immich#10940]
### The bug

Issue is also reported [here](https://www.reddit.com/r/immich/comments/1dhtjo2/immich_cli_not_deleting_duplicates_anymore/)

After running `immich upload --delete --recursive <directory>` on the directory that was already uploaded I'm getting
```
Found 0 new files and 780 duplicates
```

However despite `--delete` the duplicates aren't deleted

Older version of CLI also deleted the existing duplicates and it was convenient

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

1.107.2

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
TrueNas scale installation 

https://github.com/truecharts/charts/tree/master/charts/stable/immich
```

### Your .env content

```Shell
TrueNas scale installation 

https://github.com/truecharts/charts/tree/master/charts/stable/immich
```

### Reproduction steps

```bash
1. Run `immich upload --recursive <directory>`
2. Run `immich upload --recursive --delete <directory>`
3. Check that the duplicates aren't removed after the second execution (with `--delete`)
```

### Additional information

immich cli version - `2.2.7`

**Comment by aviv926** [comment]
At the end of the process, do you only have the duplicate files left in the folder?

**Comment by darkroom2** [comment]
same issue, I need a way to delete duplicated local files, not only those that were uploaded, but also those already existing in library

**Comment by danieldietzler** [comment]
> > At the end of the process, do you only have the duplicate files left in the folder?
> 
> yes

Then just delete the folder, no?

**Comment by aviv926** [comment]
> > > At the end of the process, do you only have the duplicate files left in the folder?
> > 
> > 
> > yes
> 
> Then just delete the folder, no?

Yes actually
