### ISSUE TITLE
Photos/videos that was previously uploaded started to re-upload after I restored my iPhone.

### ISSUE THREAD

**Issue by dsync89** [immich-app/immich#10943]
### The bug

Backstory: Due to a mysterious Apple infamous apple logo boot freeze on my Iphone 14, I have no choice but to restore it using my 2023/04 iCloud backup. Yes it's not typo as I haven't back up for 1 year+ because my iCloud storage ran out at that time and I didn't resubscribe, poor decision :/). After re-install Immich iOS app again and selected the `Recent` album, it somehow attempted to reupload all the media again. I have a total of ~68k media and uploaded ~20k of it before the restore, but after restore it started all over again from the ~68k media. 

The app should have received the same hash value from the server and skip the upload, but it doesn't seem to be the case here, as I can still see the file upload progress bar...

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.1 build.162

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Omitted because it is irrelevant
```

### Your .env content

```Shell
Omitted because it is irrelevant
```

### Reproduction steps

```bash
Selected `Recents (All)` album in Backup Albums, then Start Backup.
```

### Relevant log output

```shell
Omitted because it is irrelevant
```

**Comment by bo0tzz** [comment]
This is mostly working as expected - the mobile app doesn't hash before uploading yet.
