### ISSUE TITLE
[Feature]: Switch for local network (auto)

### ISSUE THREAD

**Issue by PeterBasista** [immich-app/immich#1097]
### Feature detail

Settings for the home network.

**Description:**
The specified url (http://immich.example.com) will be accessed if no local network is available (192.168.x.x:2283; e.g. based on the wifi name). If a home network is available, the application will connect via the local network.

**Benefits:**
Faster data transfer (internet transfer is dependent on the program from isp)

**Why?**
My current library is 2Tb. The files are hosted on a home server, moving this data and the subsequent fees would be costly.

### Platform

Mobile App

**Comment by bo0tzz** [comment]
Duplicate of #308

**Comment by Betoniara** [comment]
This should be natively supported
