### ISSUE TITLE
portrait mode

### ISSUE THREAD

**Issue by soapmancn** [immich-app/immich#10970]
### The bug

Photos taken using portrait mode on ios18 iphone15promax cannot be synchronized successfully
![1720513463951](https://github.com/immich-app/immich/assets/33997593/804ef159-ff18-4c12-aee1-04808b08c024)
![1720513488062](https://github.com/immich-app/immich/assets/33997593/8abe047b-e909-436a-8af0-1c5b530cbc9b)

### The OS that Immich Server is running on

Ubuntu2204

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.2

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
...
```

### Your .env content

```Shell
...
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by alextran1502** [comment]
#10464
