### ISSUE TITLE
[BUG] Album zip file content

### ISSUE THREAD

**Issue by PeterBasista** [immich-app/immich#1102]
**Describe the bug**
When downloading an album in the form of a zip, the media has a creation date as the date of uploading to the server.

**Task List**

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Create album and add some photos
2. Click on download album as zip (web)
3. Unzip the files and look on creation date
4. Creation date is based on upload date

**Expected behavior**
The date of creation of the files will be the same as the date indicated in the EXIF (table)

**System**
- Phone OS [iOS, Android]: `IOS`
- Server Version: `1.38.2`
- Mobile App Version: `1.38.0 build.75`

**Additional context**
it's not bad for regular backups, but when the library is copied later, it can create a good confusion in the photos, especially when you need to orient yourself "in time" as the events followed. It would be great if these downloaded files also contained full EXIF data as before uploading to immich.

**Comment by alextran1502** [comment]
Can you check the EXIF value instead of the creation date on the file browser, the file downloaded is the original file, so the EXIF value of the creation date should be intact.

**Comment by PeterBasista** [comment]
I don't understand how it can be, if I open the information about the file using information (macos) it doesn't show me any, but when I use the ExifTool all of them run nicely. The problem seems to be on my side as it ignores these Exif, although I don't understand why. Sorry.
