### ISSUE TITLE
[Feature] [WEB]: Using shift to bulk select

### ISSUE THREAD

**Issue by akoyaxd** [immich-app/immich#1103]
### Feature detail

Being able to use Shift to mark all Assets as selected between two manual selected Assets. Similar how it works on the local file browser.

Example usecase: I want to add all assets from a year abroad to an album. Selecting all of them is really annoying.  
This does also apply at smaller scale to Vacations.

### Platform

Web

**Comment by bo0tzz** [comment]
Duplicate of #709
