### ISSUE TITLE
Other user can't share photos from shared album

### ISSUE THREAD

**Issue by jwefers** [immich-app/immich#11046]
### The bug

My partner is added as user to a shared album. She'd like to multi-select and share several photos as public link from that album - containg only photos i uploaded.
Error:
```
ApiException 400:
{"message":"Not found or no asset.share access",
"error":"Bad Request","statusCode":400,"correlationId":"pdw1dz7r"}
```

While i imagine that this might be somewhat desired ("don't forward the pictures i gave you!!"), i'd like to at least make this a configurable option on an album, i.e. "Allow others to share photos from this album".

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

v1.180.0 build.148

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
--
```

### Your .env content

```Shell
--
```

### Reproduction steps

```bash
1. Create shared album
2. stuff it with photos
3. add other user
4. let other user try to create share link for multiple photos from album
5. error
...
```

**Comment by TopherMayor** [comment]
![image](https://github.com/user-attachments/assets/4eddcdf4-8d84-43b6-b4f7-19e25664cded)
Think it's related to this only checking for owner access and not including partner access in the returned id sets.
Seems like users users added to shared albums are not given access to the assets within the album if it wasn't added by them.

**Comment by Tronix117** [comment]
Permission management on shared album is quite light, until there is better permission support, a user which can add photos should also be able to share album imho

**Comment by MPavleski** [comment]
> ![image](https://private-user-images.githubusercontent.com/100199391/348444343-4eddcdf4-8d84-43b6-b4f7-19e25664cded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NzU1MjMsIm5iZiI6MTcyNTc3NTIyMywicGF0aCI6Ii8xMDAxOTkzOTEvMzQ4NDQ0MzQzLTRlZGRjZGY0LThkODQtNDNiNi1iNGY3LTE5ZTI1NjY0Y2RlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwNjAwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTlhMDVkOTM5NDBlNmM2MjMzMmY5MmI0ZWU0NWZmZTQ0Y2RjMTBmZDVkYjRkOTBlNjdkODBkM2EzM2M1ZWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yVM_AFZH2mdjFskktcH8FoC4DTyoFiLu3nSzmpgENFU) Think it's related to this only checking for owner access and not including partner access in the returned id sets. Seems like users users added to shared albums are not given access to the assets within the album if it wasn't added by them.

Wouldn't it be better default to allow share if there is read access already. I mean, the user read the asset, they can read it and can share it by other means anyway. Like this:

![image](https://github.com/user-attachments/assets/71622f87-2929-403f-88f2-e73c9719d9ed)

**Comment by jrasm91** [comment]
Closing in favor of #12614
