### ISSUE TITLE
[BUG] Can't login on both Android and iOS

### ISSUE THREAD

**Issue by missuo** [immich-app/immich#1105]
**Describe the bug**

Can't login on both Android and iOS. "Error logging you in, check server URL, email and password"

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Open App enter email and password
2. Enter server URL: http://192.168.36.222:10323/api
3. Click on Login button
4. See error: "Error logging you in, check server URL, email and password"

**Expected behavior**
Login successful

**Screenshots**
![5948e2e2152d228cb87aa](https://missuo.ru/file/5948e2e2152d228cb87aa.jpg)

**System**
- Phone OS [iOS, Android]: `iOS 16.2 and Android 12`
- Server Version: `v1.29.5`
- Mobile App Version: `iOS 1.38.0 and Android 1.38.2`

**Additional context**

iOS does not have this problem on the latest TF version, but on Android, both the Beta and official versions of Google Play Store cannot be logged in.

**Comment by alextran1502** [comment]
Please update the server to the latest version
