### ISSUE TITLE
[BUG] <android open album error>

### ISSUE THREAD

**Issue by chen3stones** [immich-app/immich#1106]
**Describe the bug**
when I run android app in debug mode open the album, an error occurred。

> Error [getAlbumDetail] 'package:openapi/model/asset_response_dto.dart': Failed assertion: line 193 pos 18: 'json.containsKey(key)': Required key "AssetResponseDto[tags]" is missing from JSON.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Start the idea, connect phone  to computer and run the main.dart
2. Go to 'library', create an album and add  some photos into album
2. Open the album that we created before, then will always loading, the ide will see the error `rror [getAlbumDetail] 'package:openapi/model/asset_response_dto.dart': Failed assertion: line 193 pos 18: 'json.containsKey(key)': Required key "AssetResponseDto[tags]" is missing from JSON.`

**Expected behavior**
When I open the album, it opens.

**Screenshots**

**System**
- Phone OS [Android]: `<Android11（MIUI12.5.6.0）>`
- Server Version: `<1.38.0 build 60>`
- Mobile App Version: `<1.38.0>`

**Additional context**
docker-compose and .env include in the zip
[config.zip](https://github.com/immich-app/immich/files/10235599/default.zip)

**Comment by alextran1502** [comment]
This is development related issue.  Since you are running the app in dev mode, you can go into the problem file and commented out the  `assert` lines
