### ISSUE TITLE
Changing upload_location results error when trying to call up administration

### ISSUE THREAD

**Issue by DeltaTango69** [immich-app/immich#11068]
![image](https://github.com/user-attachments/assets/e35be4fa-642e-4139-a66e-a64f735b1a12)

http://192.168.178.5:2283/admin/user-management

![image](https://github.com/user-attachments/assets/7873f852-8842-46c5-bd9b-00815dfa3c25)

_Originally posted by @DeltaTango69 in https://github.com/immich-app/immich/discussions/11049_

**Comment by bo0tzz** [comment]
This is not a bug, it's just some sort of issue with your setup.
