### ISSUE TITLE
The install script fails on MacOS

### ISSUE THREAD

**Issue by jadenquinn** [immich-app/immich#11120]
### The bug

The install script doesn't work on MacOS:

jaden@UltraPuckExtreme ~ % curl -o- https://raw.githubusercontent.com/immich-app/immich/main/install.sh | bash

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2890  100  2890    0     0  13289      0 --:--:-- --:--:-- --:--:-- 13317
Starting Immich installation...
Creating Immich directory...
Downloading docker-compose.yml...
Downloading .env file...
Generate random password for .env file...
bash: line 28: sha256sum: command not found
Starting Immich's docker containers
failed to find 'docker compose'
error starting Docker
There was an error installing Immich. Exit code: 13. Please provide these logs when asking for assistance.
jaden@UltraPuckExtreme ~ % 

### The OS that Immich Server is running on

MacOS 14.5

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Get an Apple Silicon Mac
2. Try to install Immich.
```

### Relevant log output

```shell
jaden@UltraPuckExtreme ~ % curl -o- https://raw.githubusercontent.com/immich-app/immich/main/install.sh | bash

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2890  100  2890    0     0  13289      0 --:--:-- --:--:-- --:--:-- 13317
Starting Immich installation...
Creating Immich directory...
Downloading docker-compose.yml...
Downloading .env file...
Generate random password for .env file...
bash: line 28: sha256sum: command not found
Starting Immich's docker containers
failed to find 'docker compose'
error starting Docker
There was an error installing Immich. Exit code: 13. Please provide these logs when asking for assistance.
```

**Comment by bo0tzz** [comment]
The install script is meant as just a quick way to try stuff out. It looks like you're missing a few of the prerequisites, including a (recent) docker installation.

**Comment by jadenquinn** [comment]
> The install script is meant as just a quick way to try stuff out. It looks like you're missing a few of the prerequisites, including a (recent) docker installation.

That should be in the documentation if it isn’t grabbing it. I expected it to download what it needs, especially since I did find a standalone executable it could have grabbed to use for Docker stuff.

This is coming from a user perspective, I have almost no dev experience.
