### ISSUE TITLE
504 Gateway Timeout - api/reports

### ISSUE THREAD

**Issue by krypton9208** [immich-app/immich#11134]
### The bug

On web page, i just want to open page "repair" as a admin. but i gut 504 in response...

### The OS that Immich Server is running on

helm

### Version of Immich Server

v.1.108.0

### Version of Immich Mobile App

v.1.108.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
standard
```

### Your .env content

```Shell
standard
```

### Reproduction steps

```bash
1. login as a admin
2. Enter in admin panel
3. Click on "repair" section
...
```

### Relevant log output

```shell
no logs from "immich-server"
```

**Comment by mmomjian** [comment]
Are you using a reverse proxy? How are you connected to Immich.

**Comment by anyshpm** [comment]
Same error with a nginx reverse proxy. Only `admin/repair` page get 504.

Configuration:
```
...
    location / {
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        proxy_redirect off;
        proxy_pass http://immich-server:2283/;
        client_max_body_size 2048m;
        proxy_read_timeout 300;
    }
...
````

**Comment by bo0tzz** [comment]
#4510
