### ISSUE TITLE
Previews overwriting thumbnails

### ISSUE THREAD

**Issue by ajpanton** [immich-app/immich#11152]
### The bug

I was asked on Discord to post this here.

I started using Immich in the beginning of June, or at the very end of May. I also don't remember what version it was, but whatever was the newest TrueNAS Scale app back then. I'm sorry for the lack of exactness.

I'm exclusively using an external library with 19k images. Nothing has ever been uploaded to Immich directly.

Going by the database column "fileModifiedAt", all images until the 1st of June (13k images) will be referred to as "old", and everything starting from the 2nd of June (6k images) are "new". Something probably happened here, but I'm not sure what. It's possible that that's when I started using Immich, but it's also possible that I installed it a few days earlier and that's when I upgraded it to a newer version.

All old images (with a very few exceptions, not sure why) have had their previews stored with the -thumbnail suffix, overwriting any potential thumbnail that might've been created first. The database column "previewPath" has the -thumbnail suffix, and this also means that when the webUI tries to serve me a thumbnail, it instead serves me the higher-res preview. All new images correctly have thumbnails with the -thumbnail suffix and previews with the -preview suffix.

I'm sorry for being so vague, but I'm really not sure about a lot of things here. I only noticed this now many versions later and can't even tell if this has already been fixed or not. Could be the initial scan thing, or it could be an older version thing, or maybe something with the TrueNAS version.

### The OS that Immich Server is running on

TrueNAS Scale

### Version of Immich Server

Not sure

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

**Comment by alextran1502** [comment]
If you run `generate thumbnail` for all, does it help fix the issue? I think this might be the mismatch when we moved to the new file format a few versions back.

**Comment by ajpanton** [comment]
Yes, I rerun the thumbnail generation in admin/jobs and it's all good now.

**Comment by jrasm91** [comment]
This has been resolved.
