### ISSUE TITLE
Remove offline files doesn't remove from trash

### ISSUE THREAD

**Issue by ajpanton** [immich-app/immich#11159]
### The bug

Removing offline files from an external library doesn't remove offline files that are in trash.

### The OS that Immich Server is running on

TrueNAS Scale

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

Browser

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
Have photos on an external library. Move some of them to trash in the Immich UI. Then delete the source files. They will now be offline in Immich. Now go to Administration -> External Libraries -> Remove Offline Files. The offline files that were in timeline will be removed, but not the ones in trash.
```

**Comment by pjft** [comment]
Thank you!
