### ISSUE TITLE
[Feature]: Allow Bitwarden to autofill login screen (Android)

### ISSUE THREAD

**Issue by colin715** [immich-app/immich#1116]
### Feature detail

Bitwarden is currently not able to autofill the login details when opening the Android app.  It appears that the login fields will need to be marked as autofill-able.  

### Platform

Mobile App

**Comment by martabal** [comment]
Neither on IOS

**Comment by spiralham** [comment]
Fwiw It's not just Bitwarden.  This issue should probably be renamed to a generic "Support autofill on login screen"
