### ISSUE TITLE
Server is not response from android app

### ISSUE THREAD

**Issue by johnaiii** [immich-app/immich#11191]
### The bug

Server not response

Log:

#0      new _Uri.notSimple (dart:core/uri.dart:1616)
#1      Uri.parse (dart:core/uri.dart:1138)
#2      ApiService._isEndpointAvailable (package:immich_mobile/services/api.service.dart:107)
#3      ApiService._resolveEndpoint (package:immich_mobile/services/api.service.dart:85)
#4      ApiService.resolveAndSetEndpoint (package:immich_mobile/services/api.service.dart:67)
#5      LoginForm.build.getServerLoginCredential (package:immich_mobile/widgets/forms/login/login_form.dart:99)
#6      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1171)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242)
#11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:696)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425)
#20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420)
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299)
#24     _invoke1 (dart:ui/hooks.dart:328)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)

### The OS that Immich Server is running on

Windows 11

### Version of Immich Server

Lastest

### Version of Immich Mobile App

Lastest

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I haven't touched
```

### Your .env content

```Shell
I haven't touched
```

### Reproduction steps

```bash
1. I have disabled Windows firewall.
2. I have double-checked the URL for sign in.
3. Postman from windows works 200 response, but not server response from android.
4. I installed immitch by downloading the raw files and execute the docker.
5. Also, problem with other open source app not reaching from android to windows.
6. Loading properly the URL in windows.
7. I have tried to add the port 2283 in Windows firewall inbound/outbound.
```

### Additional information

I have tried with

**Comment by bo0tzz** [comment]
#11189

**Comment by johnaiii** [comment]
But mine is server not response, not sure if is the same issue.
