### ISSUE TITLE
Error deleting photo - see console

### ISSUE THREAD

**Issue by droidus** [immich-app/immich#1121]
Upon attempting to delete a photo from the web desktop, I get this error message: Error deleting this asset, check console for more details.  I am running server version v1.38.2.  I deployed the non-production method.  Where is the Console located?

**Comment by alextran1502** [comment]
Non production method meaning running directly from the main branch, correct?

Console here is the web console. You can access it by pressing F12 and click on the console tab

**Comment by droidus** [comment]
Any idea what went wrong here?:
`Object { message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…}, stack: "" }
​
code: "ERR_BAD_RESPONSE"
​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​
message: "Request failed with status code 500"
​
name: "AxiosError"
​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​
response: Object { data: {…}, status: 500, statusText: "Internal Server Error", … }
​
stack: ""
​
<prototype>: Object { constructor: N(r, e, t, a, s), toJSON: toJSON(), stack: "", … }`

**Comment by jrasm91** [comment]
Can you expand the collapsed properties? Or just copy the response from the network tab?

**Comment by droidus** [comment]
Nevermind; I ran out of storage room on the server.  I expanded the HD.  Now I can delete images.

**Comment by jakub-antos** [comment]
I uploaded 163228 photos and 5657 videos. It took 2 days (without transcoding) the photos I have on an external drive, now I find out that I can't delete unnecessary photos from immich web😒.
The function mentioned here is even basic, I hope it will appear soon in the project, I don't want to leave it, it's a really good application 👍 Thank you.
