### ISSUE TITLE
When using remote microservices container with different GPU one fails.

### ISSUE THREAD

**Issue by ronbruins** [immich-app/immich#11223]
### The bug

In the HW transcode settings a dropdown selects with HW transcoding to use. But when one server is NVIDIA and the other is ARM then either one of them fails. Can't this be set as an ENV for the respective microservice container so both can use the HW at their disposal?

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

v1.108.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1.spin up second microservices 
2.start transcoding
```

### Relevant log output

```shell
[Nest] 7  - 07/16/2024, 11:16:04 AM   ERROR [Microservices:MediaService] Error occurred during transcoding. Retrying with NVENC acceleration disabled.
```

### Additional information

<img width="823" alt="image" src="https://github.com/user-attachments/assets/c3d217e1-c744-4212-98a0-5f103782f10a">

**Comment by bo0tzz** [comment]
You can set a different config file with hwaccel settings for each of the instances. I think that should work fine, though we haven't accounted for people doing something like that, so if it causes any weirdness please let us know!

**Comment by ronbruins** [comment]
you mean add the vaapi options under the nvenc section?

**Comment by bo0tzz** [comment]
I mean using https://immich.app/docs/install/config-file
