### ISSUE TITLE
[BUG] EntityNotFoundError: Could not find any entity of type "AssetEntity" matching

### ISSUE THREAD

**Issue by xxyzz** [immich-app/immich#1122]
**Describe the bug**
I use the IOS app to backup photo but the app stuck at 154 assets, then I check the "immich-app_immich-server_1" container log and find many "EntityNotFoundError":

```
EntityNotFoundError: Could not find any entity of type "AssetEntity" matching:
    "where": {
        "userId": "x",
        "checksum": {
            "type": "Buffer",
             "data": [
                235,
                5,
                134,
                1,              
                233,
                113,            
                9,              
                187,            
                112,
                101,
                218,            
                118,            
                219,         
                120,
                148,
                110,
                80,
                62,
                10,
                59
            ]
        }
    },
    "relations": [
        "exifInfo"
    ]
}
    at /usr/src/app/node_modules/typeorm/entity-manager/EntityManager.js:590:39
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AssetService.handleUploadedAsset (/usr/src/app/dist/apps/immich/apps/immich/src/api-v1/asset/asset.service.js:95:38)
```

And the "immich_postgres" container log has many duplicate key errors:

```
2022-12-19 07:09:31.441 UTC [66] ERROR:  duplicate key value violates unique constraint "UQ_userid_checksum"
2022-12-19 07:09:31.441 UTC [66] DETAIL:  Key ("userId", checksum)=(543e65cc-5df3-47f6-80bc-0110c0c195c8, \xebd2cfb5386e7cfca3016e6ef6ebf6851fa57544) already exists.
2022-12-19 07:09:31.441 UTC [66] STATEMENT:  INSERT INTO "assets"("id", "deviceAssetId", "userId", "deviceId", "type", "originalPath", "resizePath", "webpPath", "encodedVideoPath", "createdAt", "modifiedAt", "isFavorite", "mimeType", "checksum", "duration", "isVisible", "livePhotoVideoId") VALUES (DEFAULT, $1, $2, $3, $4, $5, DEFAULT, DEFAULT, DEFAULT, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING "id", "webpPath", "encodedVideoPath", "isFavorite", "isVisible"
```

I didn't changed the `docker-compose`  file and I only change the `UPLOAD_LOCATION` and `JWT_SECRET` variables in `.env` file. Before backup file on my phone, I used the cli to upload some files and one file got 504 error then I rerun the command it was uploaded successfully.

Server OS: Arch Linux
Podman version: 4.3.1

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Use immich cli to upload some files.
2. Backup photos from phone.

**Expected behavior**
Backup all photos.

**Screenshots**

**System**
- Phone OS [iOS]: `16.2`
- Server Version: `v1.38.2`
- Mobile App Version: `v1.38.0`

**Additional context**

**Comment by xxyzz** [comment]
Oh I type the wrong version number... I'm using the latest version.

**Comment by xxyzz** [comment]
The remainder assets number is always 154 and the uploading file info stops at the same file. I have some photos backed up by Nextcloud before, but Nextcloud breaks the HEIC file to jpeg and mov file. I add those Nextcloud photos via the immch cli command before using the app, maybe the server think they are the same but not the app?

**Comment by alextran1502** [comment]
@xxyzz Hmm, Immich handles LivePhotos by uploading the HEIC and the MOV portion to the server. I think this *might* conflict with the MOV files you are backing up from NextCloud.

Can you help me test the hypothesis by creating a new instance, then uploading the photos from your mobile phone before running the CLI?

**Comment by xxyzz** [comment]
I delete those jpeg and mov files from immich's web page and the app uploads all the photos successfully. I'm pretty sure the Nextcloud's mov files cause the error. I'll consider the issue resolved since it's caused by previous backup files from Nextcloud.

**Comment by xxyzz** [comment]
I find another bug in the app. Click a thumbnail then swift to the right from the left of the screen to return to the grid view. The app will turn to a black screen when I repeat this the third time.

**Comment by JustAmply** [comment]
I've got the same issue after importing (around 150.000) images from my nextcloud library via the cli tool.
Already imported images are stuck in the upload queue of the iOS app. 
They are repeatedly being uploaded, as they don't get marked as a duplicate when the error is thrown.

**Comment by SMAW** [comment]
Having the same issue also, cannot even delete pictures anymore on webpage. Also the pictures that aren't uploaded yet, because of the error are not visable...
