### ISSUE TITLE
Can't set image description to blank

### ISSUE THREAD

**Issue by ajpanton** [immich-app/immich#11238]
### The bug

When trying to set the image description to blank, it defaults to what's stored in the photo's exif tag. There doesn't seem to be a way to clear this without going and editing the image file itself.

Also somewhat related I guess, I have a camera that produces image descriptions of just 31 blank spaces. Would it be possible to treat whitespace-only descriptions as non-existant? It bugs be when browsing photos and some have the "Add a description" text (because they are empty) and some are just missing it (because they are full of spaces).

### The OS that Immich Server is running on

TrueNAS Scale

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

**Comment by orrd** [comment]
This seems to be an issue again in the current version (v1.134.0).  @jrasm91
