### ISSUE TITLE
[Feature]: iOS client login page `Email` saved password

### ISSUE THREAD

**Issue by bigbeka** [immich-app/immich#1124]
### Feature detail

As this project is fast developing and iOS client logs out of the account very often due to client app auto update and server legs behind.

Login screen of iOS `Email` filed could offer saved email to be filled in without typing it in manually.

`Password` field offers to lookup the password in the iOS Keychain/Password list, `Email` field does not.

In addition, iOS Keychain/Password list recognises that I am looking for a domain name/URL that relates to immich, that saved password could be suggested right above the keyboard instead of "🔑Password"

<img width="1255" alt="Screenshot 2022-12-19 at 15 03 55" src="https://user-images.githubusercontent.com/53529055/208443734-24595c4f-119c-4acc-9d76-ba0eaff6068b.png">

### Platform

Mobile App

**Comment by alextran1502** [comment]
This is implemented
