### ISSUE TITLE
App crashing on iPad 8th gen

### ISSUE THREAD

**Issue by Saschl** [immich-app/immich#11258]
### The bug

Hi all, I noticed the Immich app is crashing for me very frequently when scrolling through pictures. 

Briefly before the crash, no more thumbnails are being loaded and an exclamation mark appears on top of the blurred image.

I’ve attached an error log which I assume is part of the crash, but not 100% sure. 

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.109.2

### Version of Immich Mobile App

v1.109.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not relevant here
```

### Your .env content

```Shell
Not relevant here
```

### Reproduction steps

```bash
1.opening the app, scrolling through timeline, crash will happen at some point
```

### Relevant log output

`Instance of 'FlutterErrorDetails'
Exception: Exception: Could not create Impeller texture.
Library: image resource service
Context: Instance of 'ErrorDescription' `

[iOS crash file](https://github.com/user-attachments/files/16323923/Crash.json)

### Additional information

8. Gen iPad, iOS 17.5.1

**Comment by quchwe** [comment]
my

**Comment by Saschl** [comment]
It seems like that after regenerating thumbnails again and waiting for a while, the app does not crash anymore. It also feels much more fluid and previews/thumbnails do load much quicker. Not really sure what might have caused the issue

**Comment by alextran1502** [comment]
I think when the thumbnails weren't finished generating, the original format were request, cause increase in ram usage or ran into unsupported format so it crashes the app
