### ISSUE TITLE
Calling the donations "Licenses" is probably legally problematic

### ISSUE THREAD

**Issue by basdp** [immich-app/immich#11288]
### The bug

Apart from the whole discussion about ethics in OSS and putting a big buy buttons on every page (I'm not going into that), I believe the usage of the term "license" for paid users is incorrect and might suggest a legal issue as the license for Immich is AGPL-3.0. By buying a 'license', nothing about that changes, so you don't actually buy a _license_. It's basically a donation button that allows you to hide the buy button for a "licensed" banner. That banner is thus incorrect, as everyone is already implicitly 'licensed' by the AGPL.

I would propose renaming 'license' to 'donate', 'pay for support', or something else that doesn't imply a legal license to use the software. My personal suggestion would be to remove the 'feature' altogether, given the backlash that is happening at the moment, but that is not the scope of this issue.

**Comment by bo0tzz** [comment]
In our latest/followup announcement (#11226) we indicated that we are taking the feedback under consideration. We'll have more on that sometime this week.
