### ISSUE TITLE
[Feature]: Trash area to store removed photos for some time before permanent deletion

### ISSUE THREAD

**Issue by rohanssrao** [immich-app/immich#1129]
### Feature detail

Similar to Google Photos, there should be an area under the Library header on the sidebar for Trash, where removed images are sent by default.

- Images in the trash are permanently deleted after 60 days.
  - The ability to change this duration in settings would be good.
- Images can be recovered from the trash.

I can only choose one platform for this request but the feature would also be for mobile.

### Platform

Web

**Comment by bo0tzz** [comment]
Duplicate of #833
