### ISSUE TITLE
XMP files behavior - can't revert, watch for changes, seconds missing

### ISSUE THREAD

**Issue by ajpanton** [immich-app/immich#11319]
### The bug

When editing image metadata (timestamp, location) through Immich, there doesn't seem to be a way to revert the changes, even though the changes are done to a separate xmp file that preserve the originals.

Immich doesn't even seem to react to changes to this file (creation, deletion, edits) even though it does react to image files being created or edited. This is all on an external library, with "watch for file changes" enabled. So even if I delete the file, Immich still keeps the changes made.

Finally, editing the timestamp doesn't support editing the seconds, so they always get stored as 00.000, which can mess up the order of the images. Even when all you want to edit is the time zone, the timestamp is in the same dialogue box so the seconds always get set to zero.

### The OS that Immich Server is running on

Truenas SCALE app

### Version of Immich Server

v1.109.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

**Comment by bo0tzz** [comment]
This is a handful of feature requests, which should go in https://github.com/immich-app/immich/discussions/categories/feature-request as separate posts.
