### ISSUE TITLE
[Feature]: Create album on upload - mobile app

### ISSUE THREAD

**Issue by d-sko** [immich-app/immich#1132]
### Feature detail

Hello,

it would be nice if it would be possible to define an album to which all backed up images are added automatically. Example: all images backed up from my phone would be automatically added to a album "phone" (or however I name it) and all from my tablet would be added to another album like "tablet".
This would make it easier to browse images by backup source.

### Platform

Mobile App

**Comment by bo0tzz** [comment]
Maybe not quite the same, but closely related to #537

**Comment by d-sko** [comment]
Yes, you're right, definitely related but not the same.

**Comment by jrasm91** [comment]
I'd say more generally what you are wanting is to easily be able to search for your photos by device. The ability to say "show me all the photos from "phone"". Are you also asking for any specific "album" features? Like, sharing, etc. If all you need is the search/find by device type this can probably be achieved/implemented as part of search. There are quite a few requests for custom albums that I think might be achievable with a decent search implementation combined with automatic tagging.

**Comment by d-sko** [comment]
@jrasm91 yes you are right
> The ability to say "show me all the photos from "phone"".

This is exactly what I'd like to do. The only reason I proposed to do it with an album was because I thought as the album functionality is already there it should be relatively easy to implement. But every other way to achieve this is is fine too.

**Comment by bo0tzz** [comment]
Good thinking, this could be covered by the search-based smart albums concept. Closing in favour of #570
