### ISSUE TITLE
Change language related to 'support license' to 'support payment' or 'donation'. 

### ISSUE THREAD

**Issue by lightweight** [immich-app/immich#11325]
### The bug

I will happily support the Immich project with a payment, but *not* if it is being sold as a 'license', because doing that is incompatible (infringes on) the AGPL under which the project is licensed. It is far more appropriate to call financial support for the project a 'payment' or 'donation' or perhaps 'support payment' rather than (very confusingly) a  'license'. 

The use of the term 'license' to describe this payment is counter to the terms of the Affero General Public License under which the project is *already licensed*, undermining the project's Copyleft (and open source) status, which I do not believe is the intention of the project coordinator, Alex Tran. 

Specifically, (although I'm not a lawyer), it seems that the final paragraph of Section 10 of the [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html) is relevant: "You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License. For example, you may not impose a license fee, royalty, or other charge for exercise of rights granted under this License, and you may not initiate litigation (including a cross-claim or counterclaim in a lawsuit) alleging that any patent claim is infringed by making, using, selling, offering for sale, or importing the Program or any portion of it."

I strongly encourage Alex to reconsider the language being used to describe this (otherwise quite understandable) initiative to, presumably, make the project financially sustainable. I will be first in line to make a support payment when that language is changed! 

Please note, too, that I'm not keen to be using Github to make this request, as I prefer not to use closed/proprietary tools (I won't use Discord at all as a matter of principle, which I describe in greater detail here: https://davelane.nz/notslack) to interact with open/Copyleft projects. It would be great if this project (like all open projects) recognised that it undermines the openness of the community to require participants to use (and accept the onerous terms of) closed tools.   

Also , to be clear, I'm a strong proponent of the AGPL for this project (and Copyleft in general) and would be discouraged from using it if the license was changed. 

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.109.2

### Version of Immich Mobile App

v1.107.2 build.147

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
My docker-compose.yml works fine.
```

### Your .env content

```Shell
So does my .env
```

### Reproduction steps

```bash
I just viewed this post: https://immich.app/blog/2024/immich-licensing/
```

### Additional information

This is a great *open* project. I'd love to be able to support it financially, to make it a sustainable project for its authors and community!

**Comment by alextran1502** [comment]
Please read the plan update to the wording here https://github.com/immich-app/immich/discussions/11313

**Comment by lightweight** [comment]
Thanks for that pointer, Alex. Pleased to see I'm not alone in my concern.
