### ISSUE TITLE
[Feature] Download from the timeline with a keyboard shortcut (SHIFT+D)

### ISSUE THREAD

**Issue by JordyEGNL** [immich-app/immich#11375]
### The bug

When you are on the homepage and selecting multiple images the shortcut to download (SHIFT + D) does not work. I can confirm that the delete shortcut (DEL) does work as expected.

### The OS that Immich Server is running on

Ubuntu Server 22.04 LTS

### Version of Immich Server

v1.110.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Select 1 or multiple items from the homepage
2. Press SHIFT + D on your keyboard
3. Nothing happens
4. When pressing DEL on your keyboard the items do get deleted as expected
```

**Comment by michelheusschen** [comment]
Has this worked before? Ctrl+D also seems a strange shortcut because it's used by browsers to bookmark/favorite a page.

**Comment by JordyEGNL** [comment]
My bad, I meant SHIFT + D... Also no this has never worked on the homepage. App-Which-Must-Not-Be-Named has this on the homepage as well
