### ISSUE TITLE
Oauth not working (No Oauth Button on Website)

### ISSUE THREAD

**Issue by Bleala** [immich-app/immich#1137]
**Describe the bug**
Hello there!

I added the new Oauth function to my Immich instance with the following config:
```
OAUTH_ENABLED=true
OAUTH_ISSUER_URL=<redacted>/application/o/immich-oauth/.well-known/openid-configuration
OAUTH_CLIENT_ID=<redacted>
OAUTH_CLIENT_SECRET=<redacted>
OAUTH_BUTTON_TEXT="Anmelden mit Authentik"
OAUTH_AUTO_REGISTER=true
OAUTH_SCOPE="openid profile email"
```

I'm using Authentik as my Oauth provider and as you can see there is no "Anmelden mit Authentik" button on the website.

![Login Screen](https://user-images.githubusercontent.com/51357182/208708389-bef26291-b4ae-4616-bfeb-6182dc4ed450.png)

Does anyone know what's the problem here?

The .env file is working fine for all other configs.

Greetings

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Add Oauth
2. Go to Immich website

**Expected behavior**
An existing Oauth button

**Screenshots**
Added in the description.

**System**
- Server Version: `v1.39.0`

**Additional context**
-

**Comment by jrasm91** [comment]
https://github.com/immich-app/immich/releases/tag/v1.38.0_60-dev

**Comment by alextran1502** [comment]
OAuth setting is moved to the admin setting page. 

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/27055614/208709010-65d5fc90-22ff-4862-bcce-80af1b995bc5.png">

**Comment by alextran1502** [comment]
Updated `.env.example`
