### ISSUE TITLE
Some videos are rotated 180° (upside down) in the Android app

### ISSUE THREAD

**Issue by NuSuey** [immich-app/immich#11400]
### The bug

Hello,
I've had many of my videos be rotated 180° in the android app. Seems it is happening for non-vertical videos (videos recorder from the phone are correct, videos recorded via my Insta360 GO 3 are not) 

Watching them via the  iOS app or on the web they are normally watchable.  
The issue was happening also in the iOS app some versions earlier (seems to have been fixed in the recent versions).

I have tried to lower the  resolution from 720p to also 480p (and deleting the encoded videos folder), but  it didn't help, tried relogging, deleting data in the app and relog back if it's not just  some problem with the app, but that didn't work either.
Tried setting the  Acceleration API to vaapi/disabled, hw decoding is off

I have seen that various posts about  similar issues are closed, but this issue still occurs for me:
https://github.com/immich-app/immich/issues/9252
https://github.com/immich-app/immich/issues/10498

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.110.0

### Version of Immich Mobile App

v1.110.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
See above
```

### Relevant log output

```shell
[Nest] 7  - 07/26/2024, 7:15:53 PM     LOG [Microservices:MediaService] Started encoding video aa58f7d7-edfb-41fc-9052-e436a70ee955 {"inputOptions":[],"outputOptions":["-c:v h264","-c:a aac","-movflags faststart","-fps_mode passthrough","-map 0:0","-map 0:1","-v verbose","-vf scale=480:-2,format=yuv420p","-preset ultrafast","-crf 23"],"twoPass":false
```

**Comment by BjGoCraft** [comment]
I experience the same. I recorded a video with the GoPro Max and the camera was mounted upside down. If I watch the videos directly from the SD card they are fine. I uploaded them to Immich via the web app and in the web app they are also fine, but when I look at the video from within the Android app, it is flipped 180°. This is a sample video where it is happening:
https://github.com/user-attachments/assets/3eb368ed-2828-470a-aa05-bd1d0afa02f0
I'm also on version v1.110.0.

**Comment by NuSuey** [comment]
Well I am also on 1.111.0 but the videos are still broken as posted before, I tried to login, logout back, also re-encode them all (deleting the encoding video folder), nothing helped

**Comment by bram-pkg** [comment]
This is still happening for me. Let me know if I should provide any data.

**Comment by danieldietzler** [comment]
An example image would certainly be much appreciated, yes please! Ideally in a zip archive :)

**Comment by NuSuey** [comment]
Seems the issue was fixed in the recent versions of immich, or at least I am not encountering that issue anymore. Gonna leave it open if some other folks still don't have the issue
