### ISSUE TITLE
[Feature]: Delete button

### ISSUE THREAD

**Issue by athornfam2** [immich-app/immich#1143]
### Feature detail

Not much delete here but would be nice to have a delete button/trash an icon when viewing the picture not just at the library view.

### Platform

Mobile App

**Comment by Acidiphilium** [comment]
I tried to search but couldn't find any similar request. It's it possible to have a delete button when viewing pictures from an album. Right now there is only a button to remove the picture from the album but no button to simply delete the picture once and for all (by the way on my device the delete button from album isn't well described, as it's written only "Remove fro..."). Yes we can go back to the album global view and select the desired picture but that's kind of very slow when you have many albums to look for pictures cleaning. Moreover that when you go back from a picture, you're lost at top of the album even if the last viewed picture is at the bottom (also kind of unpractical).
