### ISSUE TITLE
[BUG] Filename of assets is not converted to UTF-8

### ISSUE THREAD

**Issue by EnricoBilla** [immich-app/immich#1146]
**Describe the bug**
The original filename of assets isn't converted to UTF-8 correctly, see below.
Issue has been found both on web frontend and mobile, I guess it's a bug of the server.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

**The bug has been found on the demo, so nothing I had to setup.**

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Go to the gallery
2. Open the Génie de la Liberté photo
3. See the wrongly formatted filename

The actual filename is: GÃ©nie_de_la_LibertÃ©_971.jpg
Should be: Génie_de_la_Liberté_971.jpg

**Expected behavior**
The filename should be converted to UTF-8

**Screenshots**
Web
![Screenshot_20221220_221753](https://user-images.githubusercontent.com/25234601/208769410-ea50f6b7-c566-4923-b178-1df85ba7353e.png)

Mobile
![photo_2022-12-20_22-27-22](https://user-images.githubusercontent.com/25234601/208770301-d03eae34-2642-4ba7-9915-e4b8fe911457.jpg)

**System**
- Phone OS [iOS, Android]: `Android 12`
- Server Version: `1.39.0`
- Mobile App Version: `1.39.0`

**Comment by jrasm91** [comment]
Related to multer -> busboy handling it as latin1.

https://github.com/mscdex/busboy/issues/20

**Comment by EnricoBilla** [comment]
You beat me on time, I was trying to debug it. So the workaround is to convert manually it afterwards?

Actually duplicate to #951 but I haven't found it before by searching `UTF-8` and `filename`.

**Comment by jrasm91** [comment]
I think the actual issue is something related to an RFC for file uploads. Adhering to that spec means that busboy assumes it is latin1. Browser doesn't send it as utf8 and I can't figure out how to change that. So it looks like the easy thing to do is convert from latin1 (default assigned encoding) to utf8 (actual encoding) on the server.

**Comment by EnricoBilla** [comment]
Yup got it! Thanks
