### ISSUE TITLE
Add a warning or error message to Server Settings -> External domain

### ISSUE THREAD

**Issue by martyfuhry** [immich-app/immich#11492]
### The bug

You can enter non-valid URLs to the External domain text box

![image](https://github.com/user-attachments/assets/112d988d-a356-4ee5-ad2b-0cbeb47fbd0e)

We should get an error message, because this is obviously not a valid entry. In particular, we could try `URL.canParse()` validate the text.

I would also like to not be *required* to enter the `http://` or `https://` prefix, and just have the application conditionally look that up for me. But maybe that would be best as a follow-up issue.

### The OS that Immich Server is running on

NA

### Version of Immich Server

1.111

### Version of Immich Mobile App

NA

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
Go to Server Settings -> External domain
```

**Comment by bo0tzz** [comment]
Should just need @IsUrl tacked on at https://github.com/immich-app/immich/blob/main/server/src/dtos/system-config.dto.ts#L380.

**Comment by Ghosty01** [comment]
when url contains "_" makes trouble :/
