### ISSUE TITLE
[BUG] Connection error after setup via Portainer

### ISSUE THREAD

**Issue by Marcus-Schubert** [immich-app/immich#1151]
**Describe the bug**
Immich services seem to start I can connect, although logs are looking fine. 

I have tried the following:

- access via `http://192.168.178.210:2283` (server) --> no connection possible
- access via `http://192.168.178.213:2283` (web) --> no connection possible

After looking at the logs, I saw that the web component is listening on port 3000, so I tried accessing it via `http://192.168.178.213:3000`. I get to the start screen, but when I click on "Getting Started" I run into "Error code 500". When looking at the logs of web, I can see an error (see attachment), but I'm not sure whether this is a false positive due to me using another port to access the web URL.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Deploy immich via Portainer 
2. Try opening ip:2283
3. See connection error

**Expected behavior**
Immich is being accessed correctly

**Screenshots**
Error message that is being shown after accessing the webIP:3000.
![grafik](https://user-images.githubusercontent.com/73036442/208932820-2cb95882-1de1-4e52-80eb-bb3066c03e08.png)

**System**
- Phone OS [iOS, Android]: n/a
- Server Version: 1.39.0
- Mobile App Version: n/a

**Additional context**
Next to docker-compose and stack.env I also added the logs of server and web.
[stack.txt](https://github.com/immich-app/immich/files/10278524/stack.txt)
[compose.txt](https://github.com/immich-app/immich/files/10278506/compose.txt)
[_immich-immich-server-1_logs(1).txt](https://github.com/immich-app/immich/files/10278598/_immich-immich-server-1_logs.1.txt)
[_immich-immich-web-1_logs.txt](https://github.com/immich-app/immich/files/10278618/_immich-immich-web-1_logs.txt)

**Comment by alextran1502** [comment]
You should use `192.168.178.216:2283`

**Comment by alextran1502** [comment]
I highly recommended to use the default network setup though.

**Comment by Marcus-Schubert** [comment]
@alextran1502 
Thank you for the quick response. I appended the port and used http://192.168.178.216:2283 to access immich, but I still got the connection error.

I tried to use it in bridge mode instead of macvlan and it worked without an issue. 

@jrasm91 Good point, I will change the configuration to only one IP and port.
