### ISSUE TITLE
Android mobile app fails to log in with oauth

### ISSUE THREAD

**Issue by ITestInProd** [immich-app/immich#11518]
### The bug

The Android app, starting with v1.111.0, fails to log in via OAuth. Downgrading to v1.110.0 or earlier resolves the bug.

### The OS that Immich Server is running on

K8s deployment

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Log out of the mobile app
2. Upgrade to v1.111.0
3. Attempt to log in via OAuth
4. Authenticate to your provider
5. The provider will redirect back to Immich
6. The Immich mobile app will throw an error that the user is unknown
7. The OAuth user is not logged in
```

**Comment by aendes** [comment]
I found today the same issue with Version v1.111.0 of apk on Server with Version v1.109.2
This also fails with users with static passwords not OAuth.
Downgraded apk to Version 109 and login works.

**Comment by krisavi** [comment]
v1.110.0 seemed to log in as well without problems. 

v1.111.0 just fails to log in, gives message like server URL, email or password is wrong.

**Comment by alextran1502** [comment]
I will take a look at this. Probably a bug with from the recent fix of random logout

**Comment by sheepman4267** [comment]
FYI, this is also happening on iOS. When my GF updated the app to 1.111.0, she got signed out for some reason and can no longer sign back in with oAuth.

**Comment by alextran1502** [comment]
Will make this a priority this coming week

**Comment by alextran1502** [comment]
So I will need your help on this. I cannot reproduce the issue to identify the bug.

I am using Authentik as an OAuth provider, on a local connection, and can perform the logging. What provider do you guys use? Can you please share the log after the login fails?

**Comment by jrasm91** [comment]
Both mobile logs and server logs would be useful.

**Comment by sheepman4267** [comment]
> So I will need your help on this. I cannot reproduce the issue to identify the bug.
> 
> I am using Authentik as an OAuth provider, on a local connection, and can perform the logging. What provider do you guys use? Can you please share the log after the login fails?

I'm using Keycloak, and the issue is still present on my android device running app version 1.111.0. I'm attaching the mobile log, but I see no log events in a `docker-compose logs --follow` attached to my immich server container when I try a login.
[Immich_log_2024-08-05T11:31:11.813138.log](https://github.com/user-attachments/files/16499840/Immich_log_2024-08-05T11.31.11.813138.log)

**Comment by alextran1502** [comment]
@sheepman4267 Looks like your server is not on the latest version

**Comment by sheepman4267** [comment]
> @sheepman4267 Looks like your server is not on the latest version

WHOOPS.

Ugh, I feel like a total moron now- apparently on my last upgrade step, I only changed the version for the machine learning container and not the main container in my docker-compose. I'm so sorry to waste your time... and it's all working now!
