### ISSUE TITLE
Removed duplicates re-appear with next backup

### ISSUE THREAD

**Issue by dwillemsen** [immich-app/immich#11515]
### The bug

When you use the option to remove duplicates, the next time you have a backup running on your iphone, it restores all the duplicates

### The OS that Immich Server is running on

True NAS

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
don't know is on TrueNAS
```

### Your .env content

```Shell
don't know is on TrueNAS
```

### Reproduction steps

```bash
1. Remove duplicates on server
2. backup with app on phone
3. Duplicates re-appear on server
...
```

**Comment by schuhbacca** [comment]
This is currently the expected functionality (Your auto backup has no blacklist concept currently). Discussions are happening around how to address this, more to come.
