### ISSUE TITLE
iOS autofill not working

### ISSUE THREAD

**Issue by TorranceYang** [immich-app/immich#11536]
### The bug

Autofill has stopped working. It was working as recently as a ~few months ago, but has since stopped working. I personally use Bitwarden, though it seems iCloud Keychain is also not working. 

If I begin typing my email, it does seem like my device can autofill in the rest of my email, but it's specifically unable to autofill an email/password combo.

I'm guessing this is related to #5177, but I didn't see a separate issue for iOS!

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.110.0

### Version of Immich Mobile App

v1.111.0 build.167

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open Immich app
2. Attempt to autofill with password manager
3. Keyboard closes but input fields remain empty
...
```

**Comment by mmomjian** [comment]
Was this ever supported..? I opened a FR at #9024 some time ago. Can someone share what autofill URL they are using?

**Comment by alextran1502** [comment]
Yes it was supported, I used 1password and iOS native key something

**Comment by bo0tzz** [comment]
#3618
