### ISSUE TITLE
Unable to enter Slideshow on iOS Web

### ISSUE THREAD

**Issue by TechGeekGamer** [immich-app/immich#11547]
### The bug

When trying to enable Slideshow in Immich when viewing Immich on the web on iOS, an error is displayed indicating that it failed to enter full screen. 

Error displayed in the frontend:
![IMG_2150](https://github.com/user-attachments/assets/47f24ceb-06ff-4a33-800f-f1b6e102cc3c)

Error displayed in the console:
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/7c4dbd8a-4a9a-409b-9a03-4e7f7e7a81c6">

**Potential Solution**
When looking at the source code and testing locally, from what I can tell the errors originated from [this line](<https://github.com/immich-app/immich/blob/55b31d1ce2a16d21dd5248034ca8fb3ce182a091/web/src/lib/components/asset-viewer/asset-viewer.svelte#L333>). The fix that worked for me was only trying to run the function if it was defined, ex.
```js
 assetViewerHtmlElement.requestFullscreen?.();
```
How you handle it is up to you (the maintainers) of course, but this is an idea of what you *could* do.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

1.111.0 build.167

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A - client side issue
```

### Your .env content

```Shell
N/A - client side issue
```

### Reproduction steps

```bash
1. Setup / Use an existing Immich instance
2. If not already, add images to the library
3. Reload the page
4. Select and open an image 
5. Select the three dots menu
6. Select Slideshow option
7. Observe the error
```

### Relevant log output

```js
[Error] [handleError]: Unable to enter fullscreen (2)
TypeError: $t.requestFullscreen is not a function. (In '$t.requestFullscreen()', '$t.requestFullscreen' is undefined) — asset-viewer.D3Rtni5T.js:3:147292
"@http://192.168.1.143:2283/_app/immutable/chunks/asset-viewer.D3Rtni5T.js:3:147291
tr@http://192.168.1.143:2283/_app/immutable/chunks/asset-viewer.D3Rtni5T.js:3:147376
@http://192.168.1.143:2283/_app/immutable/chunks/asset-viewer.D3Rtni5T.js:3:144534
u@http://192.168.1.143:2283/_app/immutable/chunks/index.uGfSEuUk.js:1:304
Lt@http://192.168.1.143:2283/_app/immutable/chunks/scheduler.agOdOFRt.js:1:1980
@http://192.168.1.143:2283/_app/immutable/chunks/scheduler.agOdOFRt.js:1:9606
forEach@[native code]
@http://192.168.1.143:2283/_app/immutable/chunks/scheduler.agOdOFRt.js:1:9595
S@http://192.168.1.143:2283/_app/immutable/chunks/asset-viewer.D3Rtni5T.js:3:36630
f@http://192.168.1.143:2283/_app/immutable/chunks/menu-option.DekS3JjK.js:1:2380"
	E (handle-error.NiqSoenH.js:1:626)
	(anonymous function) (asset-viewer.D3Rtni5T.js:3:147306)
	tr (asset-viewer.D3Rtni5T.js:3:147377)
	(anonymous function) (asset-viewer.D3Rtni5T.js:3:144535)
	u (index.uGfSEuUk.js:1:305)
	Lt (scheduler.agOdOFRt.js:1:1981)
	(anonymous function) (scheduler.agOdOFRt.js:1:9607)
	forEach
	(anonymous function) (scheduler.agOdOFRt.js:1:9596)
	S (asset-viewer.D3Rtni5T.js:3:36631)
	f (menu-option.DekS3JjK.js:1:2381)
```

**Comment by alextran1502** [comment]
Is this on Safari?

**Comment by TechGeekGamer** [comment]
Yes
