### ISSUE TITLE
edited file isn't picking up original filename

### ISSUE THREAD

**Issue by dkerlee** [immich-app/immich#11545]
### The bug

after editing a pic on iOS the renamed file is called "_edited.jpg" but it looks like it's supposed to be <original filename>_edited.jpg

### The OS that Immich Server is running on

unraid 6.12.9

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
ghcr.io/imagegenius/immich
```

### Your .env content

```Shell
ghcr.io/imagegenius/immich
```

### Reproduction steps

```bash
1.edit pic on iOS
2.backup to server
3.look at new file names on the same day
...
```

**Comment by bo0tzz** [comment]
#11503
