### ISSUE TITLE
Map is missing details

### ISSUE THREAD

**Issue by jenda69** [immich-app/immich#11553]
### The bug

In a recent version, there was a change in the map hosting. But now the map is really bad. This screenshot shows quite zoomed out part of my region and it doesn't contain any details. Major roads missing, even region capitals missing. There are tiles where it shows more villages and roads, but it still not detailed enough to tell forest paths etc. where the photos were taken on... 

![image](https://github.com/user-attachments/assets/2c2a86c2-5a11-4de3-aec9-2c33f5dfa272)

On the side (or bottom in app) panel with details the map is by default zoomed so far beyond map details, it's usually just a pin on grey or green background, or maybe border between them if you get lucky.

![image](https://github.com/user-attachments/assets/024f7c84-339e-403f-9f35-6c0a181dba22)

### The OS that Immich Server is running on

Raspbian Bookworm

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open photo with GPS coordinates
Or
1. Open <server>/map
2. Zoom in
```

**Comment by alextran1502** [comment]
Do you have the lat/lon of the location where it shows just the gray area? We just switched the map style, so optimization will likely needed. Knowing the coordinates would help

**Comment by jenda69** [comment]
It seems it got better now. The grey area from the screenshot was on coordinates 50.3728, 13.1467. Details are there now. 

Paths are really thin and almost invisible unless really zoomed in but they are there now at least. I also find it weird that fields are often bluer and darker than forests (like here 50.1138, 12.6289) but other than that, the map looks serviceable now.

**Comment by zackpollard** [comment]
Hey, we had a bug in the deployed code of the map provider on Friday and fixed it over the weekend. We deployed a full fix today and cleared the CDN cache, so there should no longer be any weirdness on the maps. Please let us know if you experience any other problems :slightly_smiling_face:
