### ISSUE TITLE
Edited Image on new date

### ISSUE THREAD

**Issue by moritzbindewald** [immich-app/immich#11602]
### The bug

Hey, thx so much for the editor! I just tried it and noticed, that edited images are treated as new files and have the date of the edit and not when the photo was taken. This is not intended - I think? It messes quite a bit with the timeline and is quite confusing in the long run.

### The OS that Immich Server is running on

*

### Version of Immich Server

*

### Version of Immich Mobile App

*

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
*
```

### Your .env content

```Shell
*
```

### Reproduction steps

```bash
*
```

**Comment by bo0tzz** [comment]
There's an open feature request for preserving metadata

**Comment by moritzbindewald** [comment]
> There's an open feature request for preserving metadata
> 
> 

Oh sry thx!
