### ISSUE TITLE
Video playback is broken when using MTLS

### ISSUE THREAD

**Issue by piotrszlenk** [immich-app/immich#11627]
### The bug

It seems that video playback is broken when using mTLS with Cloudflare. Apparently ExoPlayer on Android mobile app does not perform mTLS with Cloudflare, hence Cloudflare blocks such request.

### The OS that Immich Server is running on

Ubuntu 22

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. Setup mTLS on Cloudflare and issue a certificate
2. Download certificate and import to the mobile app during and perform login process
3. Enable custom rule on Cloudflare and reject calls without mTLS
4. Try to play a video via immich mobile app
```

**Comment by bo0tzz** [comment]
#5553
