### ISSUE TITLE
[BUG] Android 13 notification problem

### ISSUE THREAD

**Issue by AlexZorzi** [immich-app/immich#1167]
**Describe the bug**
On my pixel 7 pro Android 13 i can't enable notifications for immich, such as upload status.
I even enabled the notifications in immich settings, but are locked on Android settings

As suggested from @alextran1502 the problem might be correlated to https://developer.android.com/develop/ui/views/notifications/notification-permission and the introduction of new permissions on Android 13

I'm available for future testing

**Task List**
- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Go to 'Android notification settings for immich'
2. Click on 'enable notifications'
3. See error

**Expected behavior**
Immich should update the asset uploads though the notifications

**Screenshots**
![Screenshot_20221223-000929](https://user-images.githubusercontent.com/47613715/209241305-590dcc24-03ac-45d2-bd58-d819b40a31c6.png)

**System**
- Phone OS [Android]: `13`
- Server Version: `1.39.0`
- Mobile App Version: `1.39.0 build 62`

**Comment by akoyaxd** [comment]
Can confirm. Same on my Pixel 6 with CalyxOS and Android 13.

**Comment by Backslashh** [comment]
Can confirm on my Pixel 7Pro, Android 13.

**Comment by TokugawaHeavyIndustries** [comment]
Confirmed, Galaxy S22 Ultra, Android 13
