### ISSUE TITLE
immich app implementation of "remove from album" differs from web (for album assets with archived flag)

### ISSUE THREAD

**Issue by lakemike** [immich-app/immich#11703]
### The bug

This affects assets that are at the same time in an album and have archived status (i.e. not visible on timeline, only in album).
When clicking "remove from album" on such an asset
- app will move asset into trash (seems incorrect, hence I tag this as an issue with app version)
- web will simply "remove from album", but not touch archived status (seems correct)

### The OS that Immich Server is running on

QNAP Linux (docker)

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
1. go to album and archive two test assets
2. use "remove from album" in app -> asset will be trashed (seems inconsistent)
3. use "remove from album" in web -> asset will be removed from album, but archive flag remains untouched (seems correct)
```

**Comment by bo0tzz** [comment]
Fixed in #11671
