### ISSUE TITLE
Mapping data soruce lacks granularity

### ISSUE THREAD

**Issue by ScaredyCat** [immich-app/immich#11715]
### The bug

Imported images which have gps data embedded are shown on maps at the correct location however because the data isn't fine grained enough or lacks location names so the text shows the photos as being taken in a different place.

Ironically, mine show up as being in a town 1/10 the size of the one I live in, which isn't even listed in the locations search box.

### The OS that Immich Server is running on

Proxmox -> Docker -> Linux 506c1393a36b 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 GNU/Linux

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0 build 152

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Irrelevant
```

### Your .env content

```Shell
Irrelevant
```

### Reproduction steps

```bash
Import an image with gps location data - shows wrong town name

Search for correct town name - not available
```

### Additional information

Map data source lacks detail when searching. Some locations don't appear in the list.

![badmap](https://github.com/user-attachments/assets/2d34b9ae-4a65-4a69-91c8-db7cbf36f8c9)

**Comment by bo0tzz** [comment]
#10850

**Comment by zackpollard** [comment]
Sorry, was looking at this, on the map it looks like this is in the centre of Eye but is incorrectly identified which I wouldn't expect. Could you send the exact coordinates for this photo to me and I will check with my local data what this should return?

**Comment by zackpollard** [comment]
Turns out I was looking at Eye in Peterborough. The problem is that the dataset we use, geonames, doesn't have a population number for Eye, but it does for Occold. We only include places that have a population > 500 to reduce the amount of data we ingest. You can go and fix this yourself by getting a source of information for the population (probably wikipedia) and adding that into geonames for eye. Here are links to the records for Occold and Eye. Once you've done this, it will be shipped with the next version of immich :slightly_smiling_face: 

https://www.geonames.org/2641102/occold.html
https://www.geonames.org/2649789/eye.html

**Comment by ScaredyCat** [comment]
52.3210234
1.1457729

**Comment by ScaredyCat** [comment]
Updated info on Geonames. Waiting for next release :)

**Comment by ScaredyCat** [comment]
Updated info on Geonames. Waiting for next release :)

**Comment by kvalev** [comment]
I will (ab)use this issue, as I have a very similar problem with another place. Thankfully it has more than 500 population, so I have updated it in Geonames in good conscience. I understand that Geonames does a new "release" about once per day, but I dont know how and how often the `cities500.txt` makes it to immich. Does it get pulled automatically or does every immich release include the latest version at the time?

**Comment by zackpollard** [comment]
> I will (ab)use this issue, as I have a very similar problem with another place. Thankfully it has more than 500 population, so I have updated it in Geonames in good conscience. I understand that Geonames does a new "release" about once per day, but I dont know how and how often the `cities500.txt` makes it to immich. Does it get pulled automatically or does every immich release include the latest version at the time?

We pull new data before each release and it is bundled with the deployment 🙂
