### ISSUE TITLE
[BUG] 502 Bad Gateway

### ISSUE THREAD

**Issue by CodebySven** [immich-app/immich#1172]
**Describe the bug**
When i do for the first time the setup of Immich it gives a nginx error bad gateway - 502

**To Reproduce**
1. Go to http://server:2283
2. See error

**Expected behavior**

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/96389299/209434444-adbdef72-cc7b-404d-82f1-4c4852bb1c86.png)

**System**
- Phone OS [iOS, Android]: `nvt`
- Server Version: `latest`
- Mobile App Version: `nvt`

**.env file**
https://paste.helpch.at/izedododub.makefile

**docker compose**
https://paste.helpch.at/iqeluwuvus.yaml

**Server OS** 
Distro: Ubuntu Server
Version: 22.04 LTS

**Installation Guide**
[x] I have read the installation guide.

**Comment by CodebySven** [comment]
This is a local server :smile:

**Comment by bo0tzz** [comment]
I see you set these env vars
```
IMMICH_WEB_URL=http://server:4000
IMMICH_SERVER_URL=http://server:4001
IMMICH_MACHINE_LEARNING_URL=http://server:4003
```

They're meant to use only if you have a specific need for them. I see no indication in your `docker-compose.yml` that you have the services running on those ports, so please remove these env vars. If that doesn't fix the issue, please post your full server logs (`docker-compose logs`)

**Comment by CodebySven** [comment]
> 

Where can i find the server logs?

**Comment by alextran1502** [comment]
@CodebySven Can you remove the three lines that @bo0tzz mentioned and restart the stack? Then let us know if it helps.

You can see the log follow this guide

https://immich.app/docs/guides/docker-help

**Comment by alextran1502** [comment]
the issue is resolved on Discord

**Comment by pythonmkl** [comment]
This also shows up when you forget to boot up redis and postgres docker images before immich.

**Comment by vorboyvo** [comment]
For if anyone has the same issue: I just upgraded from an older version and had the issue. While updating, I didn't change the docker-compose.yml, thinking it would stay the same. I fixed it by downloading docker-compose.yml from the release tag and running `docker compose down` and `docker compose up -d` again
