### ISSUE TITLE
[BUG] Firefox crashes when opening file type dropdown on upload

### ISSUE THREAD

**Issue by IrwenXYZ** [immich-app/immich#1173]
**Describe the bug**
When using Firefox, the entire browser crashes when selecting the file type dropdown when uploading

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Go to immich web interface while on Windows using Firefox
2. Click on Upload
3. Click on the button as attached below
5. Entire browser hangs and crashes

**Expected behavior**
Browser should allow me to see the file types available to choose

**Screenshots**
![image](https://user-images.githubusercontent.com/34356541/209472063-9b23961b-e575-4cb7-b36f-2fd1bd731275.png)

**System**
- Server Version: `v1.39.0_61-dev`, running using Docker on Ubuntu 22.04

**Additional context**
On Windows 11 Pro. Only occurs on Firefox, working fine on Chrome

**Comment by bo0tzz** [comment]
That's a native prompt, so that seems like a Firefox issue unrelated to Immich.
