### ISSUE TITLE
Download returns image AND video for images with embedded motion video

### ISSUE THREAD

**Issue by C-Otto** [immich-app/immich#11742]
### The bug

I have a few JPGs that contain motion videos as created by certain Samsung phones. These short videos show up as part of the image when viewed in immich. When downloading such an image, this results in two downloaded files: the actual image (which still includes the video), and the (extracted) video. When downloading several images, this issue also exists in the resulting ZIP file.

This wastes disk space, causes longer downloads and also causes duplicates when re-importing using the data from the downloads.

I suggest to NOT add the video to the download file, just adding the photo should be enough.

### The OS that Immich Server is running on

Debian Stable

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

none

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

defaults

### Your .env content

defaults

### Reproduction steps

1. Have image asset with embedded video (motion video, Samsung phones)
2. Download image

**Comment by C-Otto** [comment]
This seems to be on purpose. Introduced in #3032, see https://github.com/immich-app/immich/blob/54b276c984cf8329dec144ecb7039c160fdb5bb0/server/src/services/download.service.spec.ts#L182

**Comment by Cheekie25** [comment]
I agree. Or the behavior should be  customizable with an option
