### ISSUE TITLE
[BUG]: Support Google OAuth

### ISSUE THREAD

**Issue by TokugawaHeavyIndustries** [immich-app/immich#1174]
### Feature detail

Immich currently requires `app.immich:/` in the Redirect URIs for mobile application OAuth.

Google requires https for the Redirect URI scheme, per: https://developers.google.com/identity/protocols/oauth2/web-server#uri-validation

Screenshot of Google Cloud console:

![image](https://user-images.githubusercontent.com/18420782/209497846-3401fb8d-c6aa-4664-a191-ff38e7200a15.png)

(note http is not supported for production applications, so disregard that part of the error message in the above screenshot).

### Platform

Server

**Comment by alextran1502** [comment]
Hmm is your username the mix of Borderland 3 and Ieyasu? 😛

**Comment by jrasm91** [comment]
You can register the mobile app redirect URI if you change the client to a mobile app.

https://developers.google.com/identity/protocols/oauth2/native-app

The problem with immich/Google oauth is that Google doesn't allow you to mix redirect URIs between web/mobile. Either the client is a web app with https redirects or a mobile app with custom scheme. You can't mix them.

We'll either have to have separate oauth config for mobile vs web or update the mobile flow to somehow use https and then add a mechanism to the web to automatically redirect to the mobile app afterwards.

I think the later might be possible, but will require some more research.

**Comment by EnricoBilla** [comment]
It should be possible to link a HTTP URL to the app (see https://stackoverflow.com/questions/16762357/oauth2-redirect-uri-for-android-application and https://stackoverflow.com/questions/2958701/launch-custom-android-application-from-android-browser). If this is correct it would be possible to keep the web flow and use it on mobile too

**Comment by jrasm91** [comment]
True, it would just be a little tricky to get the right redirect URI. Right now it's not kept in immich anywhere. It comes from the web via window.location, which could be an IP or hostname, Http or https. And it might change depending on what network you access it from. Basically it depends on a lot of things and I'm not sure how to know which one to reflect back to when the flow starts from the mobile app.

**Comment by EnricoBilla** [comment]
And also I just forgot that URL must be set at compile time. With Immich everyone has a different URL to use, so it isn't possible

**Comment by jrasm91** [comment]
I think I have this fixed now. It's possible using a redirect like you originally suggested. It's just the URL needs to come from the user, so I added a setting/field for just that:

![image](https://user-images.githubusercontent.com/4334196/209977986-2719b333-3b1b-4497-8c10-dbdeeec08343.png)

**Comment by TokugawaHeavyIndustries** [comment]
This is awesome @jrasm91 . Thank you so much for the amazingly fast turnaround on this.

**Comment by TokugawaHeavyIndustries** [comment]
@alextran1502 haha nah, username is from Metal Gear Solid :P

**Comment by jrasm91** [comment]
> This is awesome @jrasm91 . Thank you so much for the amazingly fast turnaround on this. 

There is a docker tag with the PR number of you want to test it BTW.

**Comment by waclaw66** [comment]
Hello @TokugawaHeavyIndustries, could you please provide Immich OAuth configuration for Google? I don't know what's ISSUER URL in this case. Thanks.

**Comment by jrasm91** [comment]
> Hello @TokugawaHeavyIndustries, could you please provide Immich OAuth configuration for Google? I don't know what's ISSUER URL in this case. Thanks.

https://accounts.google.com/.well-known/openid-configuration

**Comment by waclaw66** [comment]
@jrasm91 Thanks, I was able to setup Google OAuth. The ISSUER URL for Google is just `https://accounts.google.com/`. I would suggest to add more examples to docs.

**Comment by jrasm91** [comment]
Feel free to open a PR. Also the Google issuer url is already listed on the oauth docs page.
