### ISSUE TITLE
Android app stuck at app launch when server is down

### ISSUE THREAD

**Issue by vinyasns** [immich-app/immich#11805]
### The bug

When the immich server is offline, the android app takes upto 5 minutes before launching. This makes it difficult to use the app when server is offline.
![Screenshot_20240815-131900](https://github.com/user-attachments/assets/9b65d50b-21aa-4432-88b6-413d3c117fc7)
This is the error seen in logs after app launches after around 5 minutes.

### The OS that Immich Server is running on

Raspberry Pi OS

### Version of Immich Server

v1.112.0

### Version of Immich Mobile App

v1.112.1 and v1.112.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Keep immich server offline.
2. Open immich app on the android phone.
3. App keeps frozen on the splash screen. It opens after 5 minutes.
```

**Comment by binse03** [comment]
I got this issue too. I annoying to turn on VPN to my server to open my photos. Please implement that we can open the app and at least see my local photos. Thanks

**Comment by mmomjian** [comment]
Thank you. Duplicate of #11769

**Comment by binse03** [comment]
> Are you guys using vpn or reverse proxy?

When I want to use it when I am not at home I use udp vpn. Without using VPN the android app loads like hours

**Comment by vinyasns** [comment]
@alextran1502 I'm using tailscale.

**Comment by popy2k14** [comment]
Same issue here, using a NGINX proxy manager in between.
If I close the app (swipe it away) it opens instantly after that.
