### ISSUE TITLE
Search results are not sorted, should be newest first

### ISSUE THREAD

**Issue by JordyEGNL** [immich-app/immich#11819]
### The bug

The search results are not sorted. In my opinion they should be sorted by newest first.

### The OS that Immich Server is running on

NA

### Version of Immich Server

v1.112.0

### Version of Immich Mobile App

v1.112.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. Have different images with the same subject (for example a cat) but with different dates
2. Make sure that the search task has finished for those images
3. Search for the subject
4. Images are not sorted by date and this cannot be changed
```

**Comment by bo0tzz** [comment]
The search results are sorted by relevance.

**Comment by JordyEGNL** [comment]
> The search results are sorted by relevance.

Could make it an option? To search by relevance or date?

**Comment by schuhbacca** [comment]
> > The search results are sorted by relevance.
> 
> Could make it an option? To search by relevance or date?

How would you see that working out of curiosity? When you search for "cat" it brings up the most relevant results in that order. How would you also sort by date then?

You would need an arbitrary "relevance" cutoff that could then be sorted, but that is a number that would be very hard to define more than likely.

**Comment by JordyEGNL** [comment]
You're right, there should be a relevance cutoff in order to only show the relevant assets.

**Comment by dvelayosmd** [comment]
i get the "relevance" argument, but when you have a lot of "relevant" images, the search result seems a chaos.

it would be great to have a way to sort the results by date as an option on the result page

**Comment by Theprim0** [comment]
Bump this feature. I would like to see the most recent images when i search for "sky" for example. It shows pictures with no order, ones made years ago and others a days ago, in the same row.

**Comment by jamesob** [comment]
Yeah agree, search is pretty useless IMO right now without an "order-by" function. E.g. I'll often have written something down, take a picture, and look for it later. Without search ordering, this is useless. Google Photos also offers this functionality.

**Comment by bdm1010** [comment]
here a year later having the same problem.  I'm searching for a picture of an old car i used to won maybe 10 years ago.  i search vehicle or jeep and i get an un-scrolable amount of results.  i know the exact year range i owned the vehicle but i cant sort those results by date.  very frustrating.

**Comment by dronf** [comment]
This is almost singlehandedly making me look for an alternative to immich.

**Comment by MoHamza1** [comment]
I was about to raise a feature request. It would be great if there was an option to groupby year.. it doesn't have to be the default since there's already a manual filters tab.

**Comment by alanmilinovic** [comment]
This is unfortunately a deal breaker for me. An option to sort result should be a default feature, I cannot believe that this is marked as not planned. Wow

**Comment by MoHamza1** [comment]
> This is unfortunately a deal breaker for me. An option to sort result should be a default feature, I cannot believe that this is marked as not planned. Wow

I've got one of my agents performing search and bucketting client side, the api doesn't exactly return a confidence score, but the results are always sorted by relevance, organising by date is trivial. 

There's also the cold start problem of the search model not always being in GPU memory.. so yeah, for me having an agent deal with all my search problems has been a game changer.

**Comment by bram-pkg** [comment]
I do believe this is useful when searching for a filename or by media type.

**Comment by alanmilinovic** [comment]
For me this is super usefull!

**Comment by jkcdarunday** [comment]
I keep going back to using Google Photos search because of this. Often times I have to find the most recent prescription photo or whatever and I search for "prescription" and it shows me stuff from 5 years ago lol.

If not planned and never will be, then maybe it's time to fork

**Comment by TZeys** [comment]
please implement a feature like this. This has been the single-most useful feature in google photos.
