### ISSUE TITLE
immich refuses to import images from the folder I set

### ISSUE THREAD

**Issue by D0nnieD4rk0** [immich-app/immich#11822]
### The bug

ive set the .env but it still doesnt pull anything and makes me upload images one by one. your documentation mentions nothing about how to import besides the mobile app. i just want to pull 

### The OS that Immich Server is running on

WSL

### Version of Immich Server

latest -- 112.1

### Version of Immich Mobile App

none

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default, nothing changed
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/USER/Screenshots
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/Lis># TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1.docker compose up -d
2. gui only takes one file at a time
3. confusion
...
```

**Comment by schuhbacca** [comment]
Please thoroughly go through the documentation. You are not setting things up correctly. Immich has a concept of an internal library that immich manages the backing file system for, and external library where you manage the file system photos. 
For upload you can either do through the web, mobile, or cli. These will be placed in the upload location. The uplaod location should be a blank folder to start.

For external libraries you can see here: https://immich.app/docs/guides/external-library/

For general explanation of libraries see here: https://immich.app/docs/features/libraries/
