### ISSUE TITLE
Trash is sorted differently on web and mobile

### ISSUE THREAD

**Issue by JordyEGNL** [immich-app/immich#11820]
### The bug

On the web version of Immich the trash items are sorted by newest first.
On the mobile version of Immich (Android in my case) this is the reverse, the oldest assets are shown on top.

Expected behavior: the trash items are also sorted by newest first like the web version

| Mobile | Web |
| ------- | ------ |
| ![Screenshot_20240815-162322_Immich.png](https://github.com/user-attachments/assets/1676990c-6cd2-457a-95cc-27d10c6c137c) | ![markup_1000020720.png](https://github.com/user-attachments/assets/d6f22701-a6c0-4373-8225-2773ab290943) |
| The oldest assets are shown at the top | The oldest assets are shown at the bottom |

### The OS that Immich Server is running on

Ubuntu 22.04 LTS

### Version of Immich Server

v1.112.0

### Version of Immich Mobile App

v1.112.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. Trash items with different dates
2. View the trash on web -> newest on top
3. View the trash on mobile -> oldest on top
```

**Comment by yashrajjain726** [comment]
Hey @JordyEGNL , I can start working on this. So, should I make it as same as web sort ?

**Comment by JordyEGNL** [comment]
> Hey @JordyEGNL , I can start working on this. So, should I make it as same as web sort ?

In my opinion, yes, the most recently deleted items should be shown at the top

**Comment by yashrajjain726** [comment]
Added changes as required.
