### ISSUE TITLE
Mobile: Missing Translation Emptied Trash / Asset trashed

### ISSUE THREAD

**Issue by MickLesk** [immich-app/immich#11844]
### The bug

1. If you have Assets in trash, you delete all. You get "emptied trash"  (Translation in localizly missing)
![Screenshot_20240816-112150](https://github.com/user-attachments/assets/c090dd9e-33e4-4578-8f24-8308fa5ed9ed)

2. if you delete an photo or asset, you get "asset trashed" (Translation in localizly missing)
![Screenshot_20240816-112103](https://github.com/user-attachments/assets/8b1bbf2b-aebc-4639-9af3-7a92523fe5b4)

### The OS that Immich Server is running on

Debian 12 (Docker)

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v1.112.1 Build 154

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Irrelevant, just missing app translation
```

### Your .env content

```Shell
Irrelevant, just missing app translation
```

### Reproduction steps

```bash
1. see description above
```

**Comment by bo0tzz** [comment]
Dupe: #11762
