### ISSUE TITLE
No key available for value id - 9

### ISSUE THREAD

**Issue by leepfrog-ger** [immich-app/immich#11860]
### The bug

Log shows `No key available for value id - 9` from `Store`.
No (known) impact on functionality

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v1.112.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
/
```

### Your .env content

```Shell
/
```

### Reproduction steps

```bash
1. Open the Immich app
2. Check the logs
```

### Relevant log output

```shell
2024-08-17 00:38:45.898948 | WARNING  | Store                | No key available for value id - 9 |
```

### Additional information

Error has been present in the log since many versions back - without any apparent impact.
Even if raising the log level to the highest level there are no supporting/surrounding log entries around that error.

**Comment by mike12806** [comment]
I see the same thing.

**Comment by alextran1502** [comment]
This can be ignored
