### ISSUE TITLE
Assets shared though an album cannot be shared with a link

### ISSUE THREAD

**Issue by agross** [immich-app/immich#11877]
### The bug

1. Create an album and share it with another user
2. Let the other user add e.g. an image
3. Open the image
4. Click the share icon and create a link
5. "Not found or no asset.share access" error shows up

### The OS that Immich Server is running on

docker

### Version of Immich Server

1.112.1

### Version of Immich Mobile App

unrelated

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
unrelated
```

### Your .env content

```Shell
unrelated
```

### Reproduction steps

```bash
1. See above
```

**Comment by parkjaeil0x01** [comment]
Same problem here.

**Comment by jrasm91** [comment]
This is working as designed, but we can probably change the access rules to allow re-sharing photos that have been shared with you.

**Comment by parkjaeil0x01** [comment]
> This is working as designed, but we can probably change the access rules to allow re-sharing photos that have been shared with you.

Is there anyway to do it myself? or need you edit some codes in Immich?

**Comment by jrasm91** [comment]
Closing in favor of #12614
