### ISSUE TITLE
Shared album assets not searchable

### ISSUE THREAD

**Issue by agross** [immich-app/immich#11875]
### The bug

1. Create an album and share it with another user
2. Let the other user add e.g. a recently-recorded video
3. Search your assets for videos limiting the time to "recent"
4. The asset shared by the other user does not show up in the search results despite you having access to the asset through your album

### The OS that Immich Server is running on

docker

### Version of Immich Server

1.112.1

### Version of Immich Mobile App

unrelated

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
unrelated
```

### Your .env content

```Shell
unrelated
```

### Reproduction steps

```bash
1. See above
```

### Additional information

I consider this to be a usability issue. I was searching for a specific video that I knew existed but I was not able to find it. So I asked the other person to perform the same search on his Immich account and the video showed up immediately. Searching my assets took me at least 3 hours also using manual search (through hundreds of assets).

**Comment by bo0tzz** [comment]
Other users' assets are currently not part of the search.

**Comment by agross** [comment]
> Other users' assets are currently not part of the search.

That's somewhat obvious from my problem description.

It's still a usability issue making shared albums almost useless to me.

I'm in favor of reopening the issue.

**Comment by bo0tzz** [comment]
It's not a bug, as there currently is no functionality intended to enable this, and there's already an open feature request for it.

**Comment by agross** [comment]
How can I find the open feature request?

**Comment by agross** [comment]
Interesting, feature requests are discussions. I've searched issues.
