### ISSUE TITLE
Unable to scroll mobile app on iPhone Mirroring

### ISSUE THREAD

**Issue by TechGeekGamer** [immich-app/immich#11914]
### The bug

When using the new [iPhone Mirroring](https://www.apple.com/macos/macos-sequoia-preview/) that is in the macOS Sequoia beta and iOS 18 beta, I am unable to scroll in any of the views. I can otherwise interact with the application (menus, view people, etc.) where scrolling isn't required. 

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

1.112.1 build.169

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A - Client side issue
```

### Your .env content

```Shell
N/A - Client side issue
```

### Reproduction steps

```bash
1. Download and install the beta software versions of macOS and iOS (https://beta.apple.com/)
2. Setup the iPhone Mirroring app
3. After connecting to the phone, navigate to the Immich app
4. Attempt to scroll on any of the views
Expected Behavior: Being able to scroll using the iPhone Mirroring feature
Actual Behavior: Being unable to scroll using the iPhone Mirroring feature
```

### Additional information

I know I am using beta software that Immich may not have been tested on, but scrolling works on many other third party apps (but not all), so this seems to be an issue with immich's client rather than the iPhone Mirroring feature itself.

**Comment by mmomjian** [comment]
This doesn't seem like an Immich issue IMO, likely either an Apple beta issue or a upstream Flutter issue, but I'll leave it open for now until someone else weighs in.

**Comment by TechGeekGamer** [comment]
Oh yeah maybe it's a Flutter issue, didn't think of that. Might open an issue there if it ends up not being an Immich issue.

**Comment by alextran1502** [comment]
yeah looks like this is Flutter issue, they will need to handle the new interaction type from the mirroring software I assume
