### ISSUE TITLE
problem with two or more live photos (i.e. heic) that have same livePhotoCID and same owner

### ISSUE THREAD

**Issue by rossanode** [immich-app/immich#11947]
### The bug

STEPS: I uploaded an live photo from an iphone. The image is composed by an heic file and a mov file. the heic file contains a livePhotoCID and immich correlates correctly the main foto with the video, the livePhotoVideoId metadata of the heic assets conteins the id of the asset of mov file.

The problem occurs when i decide to copy the same live photo in my external library. after job processing i found that the heic asset uploaded in my ext-library was linked to the .mov uploaded in the backup library. sometimes happend also that the heic files swap their links; the .heic asset in backup library is linked to the .mov in the ext-library and the heic in the external library is linked to the .mov in the buckup library. 

I suspect that the issue can be related to the "handleLivePhotoLinking" method, the server searchs for the linked video of an heic asset search by livephotocid and ownerId only, but it does not check if the assets are from the same original path.

    const match = await this.assetRepository.findLivePhotoMatch({
      livePhotoCID: asset.exifInfo.livePhotoCID,
      ownerId: asset.ownerId,
      otherAssetId: asset.id,
      type: otherType,
    }); 

### The OS that Immich Server is running on

TrueNas Core

### Version of Immich Server

v1.110.0

### Version of Immich Mobile App

v1.110.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. upload an heic+mov photo through the backup of the iphone
2. upload tha same heic+mov in an external libray
3. check the video linked in livePhotoVideoId. the heic uploaded in external library is linked to the mov of the assets upload during the iphone buckup
```

**Comment by jrasm91** [comment]
Thanks for the detailed write up. I believe we should only be linking photos within the same library.
