### ISSUE TITLE
Immich Android App - Horizontal Layout

### ISSUE THREAD

**Issue by SteadyStatus21** [immich-app/immich#11950]
### The bug

![Screenshot_20240820-151111](https://github.com/user-attachments/assets/569d8316-21af-47ca-9ab7-685a049ffedc)
Mobile layout for horizontal devices on Android app looks strange and out of place. (Is this intentional design, if so, please do let me know, as I do not mean to be rude to anyone's design.)

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

v1.112.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
Change layout from vertical to horizontal on a mobile device.
```

### Additional information

Device used for screenshot: **Google Pixel 8 Pro**

**Comment by alextran1502** [comment]
yes, it is intentional to have the sidebar to the left for horizontal view
