### ISSUE TITLE
Web Camera Model Not Being Populated in Advanced Search

### ISSUE THREAD

**Issue by schuhbacca** [immich-app/immich#11961]
### The bug

When using the advanced search I see the Camera Make as populated. It always shows "No Results" in the Model Dropdown. In the network panel I see results coming back for the query, but seems like they are not getting bound to the dropodown.

### The OS that Immich Server is running on

Debian 10

### Version of Immich Server

1.112.1

### Version of Immich Mobile App

1.112.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Default
```

### Your .env content

```Shell
Default
```

### Reproduction steps

```bash
1. Open advanced search on web
2. Open Camera Model Dropdown on web
3. Empty
...
```

![image](https://github.com/user-attachments/assets/0c202344-7a5f-4d45-a7c8-32c45a9c402d)

**Comment by bo0tzz** [comment]
#11883
