### ISSUE TITLE
Purchase in JPY shows wrong amount

### ISSUE THREAD

**Issue by Disctanger** [immich-app/immich#11986]
### The bug

If i choose JPY on purchase page the purchase cost is 40 JPY instead of equivalent of $25.
It supposed to be somewhere around 3700 JPY. Would be great if you could fix this display issue. Thank you.

![Uploading Futo Screenshot 2024-08-23 at 11-13-21 Payment Portal.png…]()

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v1.112.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Go to Account
2. Scroll down to Purchase section
3. Select Individual purchase option ($25) 
4. Get redirected do Futo purchase page (external)
```

**Comment by zackpollard** [comment]
Hey, sounds like there is a bug in the payment logic that assumes two decimal places, but currencies like JPY don't have decimals so it's caused this display issue. A fix will be deployed on Monday probably, thanks for raising! :slightly_smiling_face:

**Comment by zackpollard** [comment]
Hey, this should now be resolved, thanks for reporting it!

**Comment by Disctanger** [comment]
I can confirm the issue was fixed. Thanks for the fix, that was quick!
