### ISSUE TITLE
Web: Shared links back navigation button navigates to wrong page

### ISSUE THREAD

**Issue by Snowknight26** [immich-app/immich#11985]
### The bug

The back/close button on the Shared links page seems to be hard-coded to always go back to `/sharing` instead of where you previously were.

### The OS that Immich Server is running on

Windows 10 22H2 (19045.4780)

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Go to Photos
2. Click on a photo
3. Click the triple dots on the top navigation bar
4. Click `Add to album`
5. Click `New Album`
6. Click `View Album` in the toast, or click the album in the Info bar
7. Click `Share` in the top nav bar
8. Click `Create link`
9. Click `Create link`
10. Close the modal
11. Click `Share` in the top nav bar
12. Click `View links`
13. Click the `Close` button (back icon) in the top nav bar

You should be back on the album, not back on Sharing

**Comment by Pranay-Pandey** [comment]
@jrasm91 Can you please suggest if this is the correct way to handle this? I see your comment 

```js
  // The GalleryViewer pushes it's own history state, which causes weird
  // behavior for history.back(). To prevent that we store the previous page
  // manually and navigate back to that.
```

Would using history.back() in `albums/album-id` be bad?

Or is this redirect hardcoded in `sharing/sharedlinks` for some reason?

**Comment by maromcik** [comment]
I am on the latest Immich version but this problem persists for me. I think it was fixed before but now it reappeared.
