### ISSUE TITLE
android 14 app issue 

### ISSUE THREAD

**Issue by TheodorDumitru** [immich-app/immich#12005]
### The bug

If i upload elements, then i delete permanently some of them only from my server, then all the rest, this creates a difference between the number of photos he sees in the section where you select the folders to upload and the actual number he's going to upload. 

So my WhatsApp images has 14 elements: 

![Screenshot_20240823_213156](https://github.com/user-attachments/assets/31569c31-a19e-48dd-9393-a2eca8b92a42)

I uploaded them correctly, I deleted in 2 phases all the items only from the server ( i took out 3 of them first and then the rest)

Then, when I scan my photos for upload, it only sees 11. I can confirm upload for all of them and then do it manually for the rest of them. The folder selecter will continue to see 14 photos but after I manually upload the 3 elements, it looks like this:  

![Screenshot_20240823_213159](https://github.com/user-attachments/assets/2495b1ab-0a4d-4672-8d2b-2fb29354375d)

### The OS that Immich Server is running on

omv7 via docker compose 27.1.2

### Version of Immich Server

1.112.1

### Version of Immich Mobile App

1.112.1 build.154

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Still testing so I took the yml file as is, didn't change anything
```

### Your .env content

```Shell
Same for environment file
```

### Reproduction steps

```bash
See description
```

### Additional information

As a temporary fix, if I delete and reinstall the app, this solves the issue but I'm hoping for a more permanent fix

**Comment by alextran1502** [comment]
> Then I delete permanently some of them only from my server

Can you describe how you delete them permanently from the server?

**Comment by TheodorDumitru** [comment]
https://github.com/user-attachments/assets/1fdab964-6655-494a-a493-702d072ab339

**Comment by bo0tzz** [comment]
This is just a visual bug, it'll be fixed when we refactor the backup mechanism.

**Comment by TheodorDumitru** [comment]
It's not, I tried deleting everything and then backing up again, and despite immich seeing all the selected folders in "photos" tab, it just won't back up the difference. I have to back them up manually, at which point the total number of backed up assets ends up bigger than the number of unique elements he says he can find in the selected album(s). If at any point in this process I try to see how many elements does he see in the folder selection window, he'll see my WhatsApp folder with all its 14 elements shown correctly. 

I know you have a lot on your plate and most of the app behavior is really good, expectable and familiar, especially for someone transitioning from google photos but it really doesn't take into account the difference so please look into it when releasing updates. Luckily, there's a workaround until then. 

If I delete and reinstall the app, it works fine again, so I'm thinking it's got something to do with the cached information within the app

**Comment by alextran1502** [comment]
> Screen_Recording_20240823_232753.mp4

The video doesn't play

**Comment by TheodorDumitru** [comment]
> > Screen_Recording_20240823_232753.mp4
> 
> The video doesn't play

:(( it does for me. So anyway, I hold down a photo I want to delete from the server only (or multiple assets in my case). This selects it, and then I press on the crossed cloud sign, indicating i want it removed only from the server, not my phone, and confirm. Afterwards, i navigate to trash within the library tab and empty it instead of waiting for the conventional 30 days to pass.

**Comment by alextran1502** [comment]
Thanks, closing this to track in mobile app upload tech-debt #2567
