### ISSUE TITLE
People page is reporting inaccurate numbers of people

### ISSUE THREAD

**Issue by NotJag** [immich-app/immich#12037]
### The bug

![image](https://github.com/user-attachments/assets/aa574915-8575-4acb-82f8-1fdfa0794c75)
On the main screen we can see that it is reporting there are five people when in reality there a three (well six including hidden - so still wrong)

![image](https://github.com/user-attachments/assets/1f159be1-edff-406b-9f92-755d4d0f075e)
In this image we can see that it is reporting that there are eight people (this is when I've selected the Show & hide people button) however there are only six people on my screen - 3 unhidden and 3 hidden.

### The OS that Immich Server is running on

24.04

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

Inapplicable

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not sure it's really relavent
```

### Your .env content

```Shell
Again not relavent
```

### Reproduction steps

```bash
Not sure I did anything
```

**Comment by pyccl** [comment]
me too，#12013。
i have 97，but display 113。

**Comment by bo0tzz** [comment]
Closing as dupe
