### ISSUE TITLE
wrong storage space on side bar

### ISSUE THREAD

**Issue by NoPinky** [immich-app/immich#12047]
<img width="978" alt="image" src="https://github.com/user-attachments/assets/0aecd1f1-781f-480e-8301-d0e887b485d0">
on the left hand side bar, immich shows the wrong occupied space. But the Server Stats reports the correct one. 

### The OS that Immich Server is running on

TrueNAS SCALE Dragonfish-24.04.2

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

not relevant here

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
no idea, generated by TrueNAS
```

### Your .env content

```Shell
no idea, generated by TrueNAS
```

### Reproduction steps

```bash
1. have some fotos in immich, probably more than 100MByte altogeter
2. go to the web interface and see space occupation report on the left bottom corner. Compare with the Server Report.
```

### Additional information

Probably a minor error to be fixed since the Server Report knows the correct space occupied by all the images.

**Comment by bo0tzz** [comment]
The sidebar displays the used space in the media root. Since the default truenas setup mounts separate volumes, there's never any space used there.
