### ISSUE TITLE
automatic background backup not working with mTLS client certificate and Android Immich App

### ISSUE THREAD

**Issue by neothematrix** [immich-app/immich#12067]
### The bug

hello!
I've recently configured Immich and exposed it via cloudflare + nginx reverse proxy. I've enabled mTLS authentication on Cloudflare using client certificate.
Immich is working properly after importing the p12 client certificate in the Android app, photos are correctly shown (except video playback as already reported by #5553) and backed up using foreground backup, but it seems the background backup is ignoring the p12 client certificate, I can see the connections blocked on Cloudflare WAF for not having a mTLS certificate.
Is it possible that p12 client certificate isn't correctly loaded in for the background backup process?
I've already tried re-installing and re-configuring Immich app, but the same behavior is shown.

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v1.112.1 build.154

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

1. enable mTLS for immich public host on Cloudflare
2. block any request to the public host without mTLS valid certificate on cloudflare WAF
3. configure Immich App on Android importing p12 client certificate
4. enable background backup and take a new picture
5. check that backup fails and requests are blocked on Cloudflare WAF events
![Screenshot 2024-08-27 113058](https://github.com/user-attachments/assets/a7092d08-d858-4f93-b0c0-334d5804d936)

**Comment by bo0tzz** [comment]
Dupe: #11870
