### ISSUE TITLE
Android App: Map feature doesn't run with much data

### ISSUE THREAD

**Issue by jojo-gfx** [immich-app/immich#12114]
### The bug

Have 75.000+ photos in my immich and was try out the map function today.
Had no chance ro use it, because every time when much content should be shown the app is frozen long time any every small move or zoom after long waiting time leads also to a new frozen period.

### The OS that Immich Server is running on

Android 14

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v1.112.1 build 154

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
...
```

### Your .env content

```Shell
...
```

### Reproduction steps

1. try to use the map with heavy ammount of content on Android App
2.
3.
...

**Comment by bo0tzz** [comment]
Dupe #4174
