### ISSUE TITLE
[BUG] No albums displayed to backup in iOS app

### ISSUE THREAD

**Issue by dsippel** [immich-app/immich#1214]
Hi there,

I just installed immich on my server and access the server locally at the moment. I can log in with the created user on iOS and I can also view photos that were upload through the web interface. However I cannot backup photos from the iOS app itself.

When I want to select the albums to backup no albums are shown (see screenshot). This seems similar to this bug report:
[https://github.com/immich-app/immich/issues/410](https://github.com/hydazz/docker-immich)

 However I don't use iCloud and only have locally stored files. Full access to all photos is granted in settings. I have 4663 photos and 273 videos on my iPhone at the moment. Interestingly, Immich seems to detect that there are 19 albums on my phone (see screenshot of log in iOS app) but doesn't display them.

I use the new all in one docker container from @hydazz [https://github.com/hydazz/docker-immich](https://github.com/hydazz/docker-immich) if that is of importance.

**To Reproduce**
1. Go to 'Backup'
2. Click on 'Select' (to select albums)
3. Nothing appears under 'albums on device'

**Expected behavior**
See a list of albums on device to select from for backup.

**Screenshots**
See attached screenshots!

**System**
- iPhone 13 Pro, iOS 16.2
- Server Version: `v1.40.0`
- Mobile App Version: `v1.40.0 build.77`

![IMG_2212](https://user-images.githubusercontent.com/103022385/209998100-159fe62a-ee4b-4d3e-8fa0-11f3be9ad289.PNG)
![IMG_2211](https://user-images.githubusercontent.com/103022385/209998119-112aef34-ca87-4926-a839-414036624cb3.PNG)
![IMG_2210](https://user-images.githubusercontent.com/103022385/209998124-2b56d392-54f6-4b7a-9c05-dd738c962de2.PNG)
![IMG_2213](https://user-images.githubusercontent.com/103022385/209998694-aedab328-0b17-4cb9-95f8-500de377d513.PNG)
![IMG_2209](https://user-images.githubusercontent.com/103022385/209998130-9d6990e1-d9be-433f-bc0c-0127d6a43af1.PNG)

**Comment by alextran1502** [comment]
Can you try one or the official method of installation Immich to see if the problem persists?

**Comment by hydazz** [comment]
I can't reproduce, my albums show up and I can do a backup. I'm running the same environment except for an iPhone 14 Pro on iOS 16.3:
Server Version: v1.40.0 (My container)
Mobile App Version: v1.40.0 build.77

> Can you try one or the official method of installation Immich to see if the problem persists?

The app is independent from the container - It should be able to find albums anyway

**Comment by dsippel** [comment]
@alextran1502 : I set up a Ubuntu VM and installed immich the "official" way using docker compose. I uninstalled the iOS app again and started completely fresh. However I get the same error.

So I guess it must be a problem on the phone / with the iOS app in connection with my photo library there.

Any suggestions what I could test?

**Comment by dsippel** [comment]
@hydazz : Your comment about iCloud make me think again about that. I briefly enabled iCloud Photos and then disabled it again. AND voilà: it works now! Don't really understand it but hey, it works now 😉...

Thanks @alextran1502 and @hydazz for your quick feedback and awesome work 🙂 

Best

Daniel
![IMG_2216](https://user-images.githubusercontent.com/103022385/210020102-4f2137df-2f5b-485b-bd19-b86d68ba6fd1.PNG)
![IMG_2217](https://user-images.githubusercontent.com/103022385/210020114-bcfe4839-e2b6-48cf-b85d-1960042c1ea4.PNG)
![IMG_2218](https://user-images.githubusercontent.com/103022385/210020122-440c5e51-4cb8-41cc-a5ce-c7de2bbf428c.PNG)

**Comment by alextran1502** [comment]
Hmm this is strange. Can you double check the settings for iCloud photos?

**Comment by alextran1502** [comment]
No problem, enjoy!

**Comment by dsippel** [comment]
> Hmm this is strange. Can you double check the settings for iCloud photos?

I checked it again: enabled iCloud Photos, un- and reinstalled the iOS app. Now it still just works. No idea what the problem was... thanks again for this awesome app/server. Really enjoying it 🙂!

**Comment by jasongwq** [comment]
same problem

![16745262795662596352182838501570](https://user-images.githubusercontent.com/7529184/214198771-a2cfe667-4e7a-48e7-b85d-2603cf2bbb4a.jpg)

**Comment by jasongwq** [comment]
same problem
![mmexport1674527035388](https://user-images.githubusercontent.com/7529184/214200030-eff0cc7e-5375-431f-aa64-fb6535ab8a89.jpg)

**Comment by alextran1502** [comment]
@jasongwq Can you try to enable and then disable iCloud photos like the post mentioned above and see if that helped with the issue?

**Comment by jasongwq** [comment]
I tried to disable iCloud, but ios prompts that I can't re-enable iCloud, because my local album capacity is 60G, but iCloud space is only 5G.

**Comment by jasongwq** [comment]
I disabled iCloud yesterday, then restarted immich, but still no albums display.
But today I started immich and found that everything is normal😂
![IMG_20230125_084641](https://user-images.githubusercontent.com/7529184/214456930-ff6d5f87-6870-42ab-9e2d-1a879e64ec2e.jpg)
restarted the iOS app. Now it still just works.
