### ISSUE TITLE
Unable to display jobs status page

### ISSUE THREAD

**Issue by jacekjaros** [immich-app/immich#12145]
### The bug

when try to open http://{my immich ip}:3001/admin/jobs-status i get empty page

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
cluster is set up on portainer
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

this part is hard - i'm unable to provide this steps

### Additional information

i setup my gallery few days ago (no upgrade / migration for that time). in some point of time job status page simply stop working. i aready try to restart all containers and clean up redis keys - this was not help. this is also not seems to be performance issue - library have less then 8k items.

**Comment by alextran1502** [comment]
Can you view other pages? have you tried incognito?

**Comment by jacekjaros** [comment]
hi @alextran1502 - everything beside of job status page work perfectly fine (smooth and fast). i try incognito, i try to use other browsers (test on safari, chrome, firefox).

**Comment by alextran1502** [comment]
Can you check the console of browser (F12) when you browse the page to see if there is any error?

**Comment by jacekjaros** [comment]
![Screenshot 2024-08-30 at 19 04 41](https://github.com/user-attachments/assets/311b9bf4-f5f5-40cd-aedc-54a4b7a2d337)

**Comment by jacekjaros** [comment]
there are no errors in console tab

**Comment by bo0tzz** [comment]
Please post the container logs

**Comment by jacekjaros** [comment]
After migration dockers to dedicated network everything starting work fine.

**Comment by TPerformance** [comment]
I have the same issue. But it works with a new browser until i restart the immich stack, while being on the jobs page. After that, the browser is "wasted" and i have to use another one. After a few days it works again. I suspect it could be the browser cache or a missing header in my reverse proxy.
