### ISSUE TITLE
Bad Url in memories link

### ISSUE THREAD

**Issue by InventorB** [immich-app/immich#12171]
### The bug

When I go to the memories, and click on the icon in the bottom right of the photo, I click on it and get a 404 error.
<img width="130" alt="image" src="https://github.com/user-attachments/assets/897a05c7-b6dd-4779-88c4-461081a1a5e1">
Here is the 404 error:
<img width="525" alt="image" src="https://github.com/user-attachments/assets/05e0e9e7-618d-4cd2-89b6-29401f2de79e">
When I looked into it, the url had some weird attributes. For this sake of example I will use demo.immich.app as your URL.

It takes me to https://demo.immich.app/$/photos?at=$778be5f8-5872-4004-9cff-b2b89f7ea310
https://demo.immich.app/photos?at=$778be5f8-5872-4004-9cff-b2b89f7ea310  takes me to the equivalent of demo.immich.app/photos.
However, https://demo.immich.app/photos/778be5f8-5872-4004-9cff-b2b89f7ea310 (notice the missing $ before the ID) loads the entire photo, as I wonder if you were trying to do. Or are you trying to do something with **photos?at=** that wasn't built into the server yet?

Thanks.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v113.0

### Version of Immich Mobile App

Irrelevant

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Irrelevant, everything else works fine
```

### Your .env content

```Shell
Irrelevant, everything else works fine
```

### Reproduction steps

See above

**Comment by alextran1502** [comment]
Fixed in #12158
