### ISSUE TITLE
Bugs and Suggestions After Upgrading to Version 1.113.0:

### ISSUE THREAD

**Issue by pyccl** [immich-app/immich#12170]
### The bug

1.	On the "Tags" page, there is no "Back" button, only a "To root" button.
2.	In the "root" directory of "Tags", there is still an "Edit tag" button (which is meaningless and can be removed).
 
![image](https://github.com/user-attachments/assets/bba8bf80-339b-4617-b77a-af4b0163bd4a)

3.	In the "Edit tag" section, there is only an option to edit the color, but no option to edit the tag name. Additionally, the color cannot be deleted (after deleting the color code, clicking "Save" has no effect).
 
![image](https://github.com/user-attachments/assets/574113c3-4289-4bac-a4c7-a338647fbb28)

4.	On the "Album" page, if you click "Create album" and proceed to click the "Add photos" button in the top right corner without first entering an album name, then click "Close" in the top left corner, and repeat this sequence of actions (clicking "Add photos" and then "Close" again), an error message "No Found or No album.read access" will appear. This error does not occur in the demo.immich.app environment. Additionally, after encountering this error and attempting to close the page by clicking the "Close" button in the top left corner, the application may become unresponsive. This unresponsive behavior has also been observed in the demo.immich.app.
 
![image](https://github.com/user-attachments/assets/4f2e0ad1-f154-4cfa-8eca-ceef32710d83)

5.	In the "Folders" and "Tags" pages, within the "Explorer" section on the left, if a name (either a tag name or a folder name) at the same level fully contains the name of the one above it (for example, "test" and "test1", "test11", "test111"), clicking on it may result in the display of two or more icons for the current directory (i.e., both the current directory and any directories above it with names that are contained within the current directory's name are shown as the current directory). However, this issue does not occur if a color has been set for the tag.
    
![image](https://github.com/user-attachments/assets/2225ce22-d4c8-44ac-a76a-d2fd0e1fa166)
![image](https://github.com/user-attachments/assets/fb5c71fc-d8d3-42b5-999a-e551e4f8a6e5)

6.	In the "Folders" and "Tags" pages, when the length of a directory name is too long, it may extend beyond the rounded rectangular area that serves as the background for the current directory.
   
![image](https://github.com/user-attachments/assets/170a73fd-5db3-4126-85e9-97d316f29076)
![image](https://github.com/user-attachments/assets/057b97d6-7a2a-48ca-a245-00097cd9638e)

7.	Translation display issue with date selection: Only "dd" is translated to "day" (or "日" in the context of your language), while "yyyy" and "mm" remain untranslated. Additionally, no translation options could be found for these elements on hosted.weblate.org.
 
![image](https://github.com/user-attachments/assets/29a5391f-bc62-4955-9309-6301db854fcc)

### The OS that Immich Server is running on

windows 11 docker desktop v 4.33.1

### Version of Immich Server

v1.113.0

### Version of Immich Mobile App

-

### Platform with the issue

- [x] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I don't think it's involved.
```

### Your .env content

```Shell
I don't think it's involved.
```

### Reproduction steps

Check the details above

**Comment by thomasss02** [comment]
If i can add a note about the mobile app: the memory display is broken as shown in the screenshot. the one on the right side is smaller than the others
![FotoGrid_20240831_111438300.jpg](https://github.com/user-attachments/assets/baeccba4-18b9-4168-b566-4b9591283c1b)

**Comment by deafmute1** [comment]
Some things observed from folder view:
- thumbnails fail on load on most videos for me, until I mouse over 
<img src="https://github.com/user-attachments/assets/b1e4090b-eb3d-43e5-a9b1-d1b7243b1e33" width=25% height=25%>

- Folder gallery view has a hardcoded max length for no reason
<img="https://github.com/user-attachments/assets/ba5c2f71-b486-4eed-bb23-8462231fe194" width=50% height=50%>

- Theres a L-R scroll on the sidebar that comes up due to the length of autogeneraterated folder name (upload/library/<autogen name>). No easy way to solve this but a resizable sidebar and just cutting the name off would probably be optimal. Right now it sways side to side as you scroll with mouse wheel.  
- No select on act on multiple files despite it being in the timeline; I'd expect to see it here.
- the use of monospace font everywhere and solid grey bands feels crude and incongruous compared to the rest of the ui. Everything uses monospace here, except the folder names when in gallery view, which is weirdly inconsistent.

**Comment by ingria** [comment]
Also, there's a small bug in folder sorting:

![tags](https://github.com/user-attachments/assets/196038f3-6b9a-4e79-a7b0-8529012174bd)

198x should be on the top, 2001.08_test should come after 2001, etc.

**Comment by SpookyUSAF** [comment]
Seems like thumbnails are failing to generate to anything uploaded. I just converted to a storage template (default settings) so not sure if this is version related to storage template conversion related. Logs are indicating that the "upload/" folder is being added to the path where it shouldn't be.

Also, in the information button in Immich web, the file location is shown as "upload/library/admin/2006/2006-09-04/BABY_A.AVI" when it's actually "library/admin/2006/2006-09-04/BABY_A.AVI"

Here's logs showing this:
* [Nest] 31  - 08/31/2024, 11:42:13 AM   ERROR [Api:LoggerRepository~84krif5q] Unable to send file: Error
* Error: ENOENT: no such file or directory, access 'upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
* [Nest] 31  - 08/31/2024, 11:42:13 AM    WARN [Api:ExpressAdapter~84krif5q] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
* [Nest] 31  - 08/31/2024, 11:42:13 AM   ERROR [Api:ExceptionsHandler~84krif5q] ENOENT: no such file or directory, access 'upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg'
* Error: ENOENT: no such file or directory, access 'upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
* [Nest] 7  - 08/31/2024, 11:47:38 AM   ERROR [Microservices:MediaRepository] ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
*   built with gcc 12 (Debian 12.2.0-14)
*   configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc

**Comment by pyccl** [comment]
Continuing above:
1.	In Time-based memories , the "View in Timeline" button for the photo was clicked but the link was incorrect.
 
 
![image](https://github.com/user-attachments/assets/c728386b-e3ec-4513-9381-e552b88e8e3a)
![image](https://github.com/user-attachments/assets/77f64e53-e456-49ce-af6c-30841baad5ea)

2.	2. On the "Folder" page, when viewing images of various files, click on other folders to enter. The scrollbar on the right is not located on top, but in the same position as the previous folder.
3.	In the "Folder" page, there is no photo selection function, and photo management such as deletion cannot be performed.
4.	In the "Tags" page, there is a photo selection function, but there is no pop-up menu and it cannot be managed, such as deletion.
5.	In the screening, the country and province are correct, but the city is displayed as a township (in China, China>provinces/municipalities/special administrative regions/Taiwan>prefecture level cities>districts/counties/county-level cities>townships).
 
![image](https://github.com/user-attachments/assets/44e322df-857c-463a-8a75-cefd05d46afb)

6.	It is recommended to add a new feature: uploading images can be done to a folder in an external gallery. You can add an upload button on the "Folder" page to upload images to this folder. You can also add the function of selecting the upload location in the homepage upload.
7.	Suggest adding new features: Change the "Photos" in the left list to "Medias" (all media files are together), then add separate "Photos" (here are individual photos, no videos, live photos, etc.), add "Live Photos" (Motion Photos), "Videos" (here are all videos, no photos)
 
![image](https://github.com/user-attachments/assets/9a5b5f2a-412f-4002-8434-c7e565f9a985)

8. It is recommended to add a new feature: search results also support timelines (or have a timeline switch).

**Comment by alextran1502** [comment]
Thanks @pyccl  for the feedback, but let's not use one bug report to report all bugs and make feature requests simultaneously because it will not get appropriately tracked. Most of the feature requests you made here are mostly requested

**Comment by pyccl** [comment]
> simultaneously

thanks,I know.

**Comment by alextran1502** [comment]
Some have been addressed. Closing this as we cannot track multiple things in one issue and the suggestions have also been opened
