### ISSUE TITLE
Immich Android App the timeline scroll button can disappear behind "Library" button

### ISSUE THREAD

**Issue by elversoee** [immich-app/immich#12188]
### The bug

Immich Android App the timeline scroll button can disappear behind "Library" button
today after the update to 1.113.0 but not sure it is from this version.
But when scrolling all the way to the bottom i the timeline on the Immich android app and still holding on the scroll button past the "Library" it keeps scrolling but the Button disappears and if you release the button then it is hidden and can only reappear if you scroll a lot manually in the reverse direction    

### The OS that Immich Server is running on

Proxmox/debian

### Version of Immich Server

1.113.0

### Version of Immich Mobile App

1.113.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not Relevant
```

### Your .env content

```Shell
Not Relevant
```

### Reproduction steps

1. But when scrolling all the way to the bottom i the timeline on the Immich android app and still holding on the scroll button past the "Library" it keeps scrolling     
2. But the Button disappears and if you release the button then it is hidden and can only reappear 
3. if you scroll a lot manually in the reverse direction
...

**Comment by bo0tzz** [comment]
Confirmed, I can reproduce this.

**Comment by fenty17** [comment]
Not just on Android actually, happens on iOS too.

**Comment by samolego** [comment]
https://github.com/user-attachments/assets/9ef14d2b-19e5-4dc3-a1f9-badc210891fa

here's demo
