### ISSUE TITLE
Android "back" gesture closes app when watching video

### ISSUE THREAD

**Issue by Danilado** [immich-app/immich#12186]
### The bug

When watching videos in android app, the "back" gesture closes (or rather minimizes) the app instead of closing the video view.

This doesn't happen with pictures and gif files

### The OS that Immich Server is running on

Opensuse Tumbleweed

### Version of Immich Server

v1.113.0

### Version of Immich Mobile App

 1.113.0 build.156 

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I don't think it's relevant
```

### Your .env content

```Shell
I don't think it's relevant
```

### Reproduction steps

1. Open video in the android app
2. Perform "back" gesture
Expected behavior: video view closes, I return to timeline
Real behaviour: app minimizee, I return to the desktop

### Additional information

I tried turning different view settings, such as load original image
The behaviour didn't change

The down swipe performs the desired action

**Comment by bo0tzz** [comment]
I can't reproduce this, it behaves as expected for me.

**Comment by Danilado** [comment]
Weird just tried reinstalling the app both from google play and the releases page
It still closes the app for me

Im using Vivo IQOO Neo 8 phone running Origin OS 4 based on Android 14
I tried changing to navigation buttons in the OS
Pressing the "back" button performs as expected - I return to  the timeline from the video

The problem only happens with the gesture. 
Guess I have to suffer from using a cheap chineese device

**Comment by alextran1502** [comment]
I can reproduce on Samsung S23

**Comment by ryanwinter** [comment]
I have the same issue on pixel 6. Swipe back always closes the app.

**Comment by NicholasFlamy** [comment]
This might no longer be an issue with #12104. I just enabled predictive back in a debug build and could not reproduce on my Galaxy S22 Android 14.

**Comment by Danilado** [comment]
@NicholasFlamy 
The problem was fixed in September 2024...

**Comment by NicholasFlamy** [comment]
> [@NicholasFlamy](https://github.com/NicholasFlamy) The problem was fixed in September 2024...

This issue was fixed with PR #12221, but that fix disables predictive back gestyres entirely. I re-enabled predictive back gestures in a debug build and I did not have this issue.

**Comment by Danilado** [comment]
Makes sense

You should either create a new issue and mention this one or just reopen this one

**Comment by NicholasFlamy** [comment]
> Makes sense
> 
> You should either create a new issue and mention this one or just reopen this one

Yep, I demoed it and posted in the Discord and may open a PR for predictive back gestures soon.
