### ISSUE TITLE
Unable to login when IOS app is updated to the latest version but server has not been updated

### ISSUE THREAD

**Issue by Microices** [immich-app/immich#1224]
**Describe the bug**

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [ * ] I have read thoroughly the README setup and installation instructions.
- [ * ] I have included my `docker-compose` file.
- [ * ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. IOS app auto updates
2. Start Immich app
3. User is logged out
4. Enter login credentials
5. Click Login
6. Nothing happens

**Expected behavior**
after opening app timeline should be show.

**Screenshots**

**System**
- Phone OS [iOS, Android]: `IOS 16.2`
- Server Version: `1.38.0`
- Mobile App Version: `1.40.0 build.77`

**Additional context**
Once i updated the server the I am able to login to the app

**Comment by alextran1502** [comment]
Please update the server to the latest version. With the fast development cycle, we only support compatibility among the same version of the server and the mobile app.
