### ISSUE TITLE
[BUG] Demo instance announces HTTP3 but doesn't use it

### ISSUE THREAD

**Issue by bt90** [immich-app/immich#1227]
It's just nitpicking, but Caddy now ships with HTTP/3 enabled by default. It would be nice if you could open port 443/udp to make it work :wink:

![image](https://user-images.githubusercontent.com/1926175/210051274-4c5b0a6e-35ff-45b7-8340-86e0992a3a3d.png)

**Comment by bt90** [comment]
In case you're using docker:

`-p 80:80 -p 443:443 -p 443:443/udp`

docker-compose:

```yml
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
```

**Comment by bo0tzz** [comment]
I've opened the ports, but I'm not sure how to test this. Can you verify it for me?

**Comment by bt90** [comment]
The developer consoles of Chrome/Firefox should report HTTP/3. I'm on mobile right now so that's not an option but this test indicates that it's working:

https://www.http3check.net/?host=demo.immich.app

(don't get confused by the QUIC warning: https://github.com/caddyserver/caddy/issues/5122#issuecomment-1268978760)

**Comment by bo0tzz** [comment]
Great, thanks!
