### ISSUE TITLE
[BUG] Thumbnail endpoint should set proper content-type

### ISSUE THREAD

**Issue by bt90** [immich-app/immich#1230]
The endpoint should set the content-type depending on the specified `format`. For `format=WEBP` the type `image/webp` should be used.

This allows to examine the thumbnails in a different tab without triggering a download.

![image](https://user-images.githubusercontent.com/1926175/210052250-aab622e1-272b-469f-af96-2ca59fd70899.png)

**Comment by uhthomas** [comment]
Ah, #3018
