### ISSUE TITLE
Asset thumbnails do not show focus outlines

### ISSUE THREAD

**Issue by ben-basten** [immich-app/immich#12329]
### The bug

Thumbnails in the asset grid should show an outline when they are focused and focus is visible. Previously, there was a dark blue outline.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.113.1

### Version of Immich Mobile App

v1.113.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Reproducible in demo instance
```

### Your .env content

```Shell
Reproducible in demo instance
```

### Reproduction steps

1. Press the `Tab` key until focus is inside of the "Photos" asset grid
2. Tab through the photo thumbnails
3. Observe that the thumbnails are focused, but there is no outline showing focus

**Comment by bo0tzz** [comment]
cc @midzelis did this maybe get lost during the refactor?
