### ISSUE TITLE
[BUG] Unable to upload HEIC photos

### ISSUE THREAD

**Issue by IrwenXYZ** [immich-app/immich#1235]
**Describe the bug**
Unable to upload HEIC photos. When photo is attempted to be uploaded, the bottom right upload GUI does not appear, and immich provides no response in GUI or in logs

**To Reproduce**
1. Go to immich web UI
2. Attempt to upload HEIC file
3. Upload does not occur

**Expected behavior**
The bottom right upload UI should show up indicating progress, and when finished, immich should prompt user to refresh

**System**
- Server Version: `v1.40.1_63-dev`

**Additional context**
Tested on Firefox and Chrome

**Comment by alextran1502** [comment]
The initial observation is the `HEIC` file when uploaded from the web doesn't have the `type` specified as `image/<type-name>` but as a blank string, thus the web excluded the file from being uploaded

**Comment by lameslime** [comment]
Same seems to be also happening with app (android) uploads, only jpgs are appearing. Videos (.mp4) aren't appearing, also no logs in gui or app.
Version: latest stable (v1.40.0), app is play store version.

**Comment by alextran1502** [comment]
> Same seems to be also happening with app (android) uploads, only jpgs are appearing. Videos (.mp4) aren't appearing, also no logs in gui or app. The progress bar is showing upload progress and my proxy reports traffic, but it seems to be discarded by the server.
> 
> Version: latest stable (v1.40.0), app is play store version.

Hmm, can you share a file from your Android phone? Heic is standard on iPhone so I am not sure why uploading from Android not working?

**Comment by lameslime** [comment]
Alright, I think it was taken with Proshot. [Picture](https://photos.app.goo.gl/2uTrm27vqP2FYZyWA)

**Comment by Hukuma1** [comment]
Just doing a catch-all comment. Tested with latest version. Uploaded `gif`, `jpg`, `jpeg`, `png`, `webp`, `heif`, `heic`, `avif` from web upload.

HEIF/HEIC/AVIF do not work/upload with standard example files downloaded from websites. AVIF does show a file upload dialog box, but nothing shows up once I refresh.
