### ISSUE TITLE
The associated person opens a blank page

### ISSUE THREAD

**Issue by pyccl** [immich-app/immich#12379]
### The bug

On the "People" page, open any character and click on other characters on the right, and a blank page will appear. Click back to return to the 'People' page. But the same link (a link on a blank page) can be opened normally by pressing enter again.

![image](https://github.com/user-attachments/assets/70a6b1a7-1dac-45a5-97f8-fb74ad9e0e36)

### The OS that Immich Server is running on

Windows 11 Docker Desktop v4.34.0

### Version of Immich Server

V1.113.1

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

1.
2.
3.
...

**Comment by bo0tzz** [comment]
Dupe: #12348
