### ISSUE TITLE
New face extraction from XMP feature is missing face thumbnails, when ML face detection is turned off

### ISSUE THREAD

**Issue by ajgon** [immich-app/immich#12391]
### The bug

I'm testing it extensively new "extract face metadata from xmp" feature, and it works great! However I think I noticed an edge-case. With metadata extraction enabled, and face detection disabled, face thumbnails are missing:

Missing people section in explore (despite faces being added via metadata extraction):
![2024-09-05-223349_1842x1844_scrot](https://github.com/user-attachments/assets/c24ddcb1-bd67-4846-8cae-b474f36c6b85)

Missing thumbnails of faces in photo details (yet, name of the person is extracted correctly):
![2024-09-05-223549_1838x1850_scrot](https://github.com/user-attachments/assets/d0119be4-286d-4068-bb90-c71e47a38f90)

Not sure if it matters, but I have face detection disabled in `config.json`, and it was set before any external library was added.

### The OS that Immich Server is running on

Kubernetes, talos linux

### Version of Immich Server

main@sha256:19948acea54ecf537a411ddd90e79a79a2a17ed2f53360395a311f1d4168b247

### Version of Immich Mobile App

doesn't apply

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

Using k8s with app-template/common-library: https://github.com/deedee-ops/home-ops/blob/1a9c9be9844ba190b061e87b9b4cfbc082d70be1/kubernetes/apps/default/immich/values.yaml#L73

### Your .env content

https://github.com/deedee-ops/home-ops/blob/1a9c9be9844ba190b061e87b9b4cfbc082d70be1/kubernetes/apps/default/immich/values.yaml#L3

### Reproduction steps

1. Fresh install of immich
2. Before starting the server, set up following `config.json` file: https://github.com/deedee-ops/home-ops/blob/1a9c9be9844ba190b061e87b9b4cfbc082d70be1/kubernetes/apps/default/immich/files/config.json (with face detection disabled)
3. Add an external library and scan it
4. There will be no faces in "explore" section (I assume because ML faces are disabled?) and also missing thumbnails for faces extracted from metadata.

**Comment by ajgon** [comment]
I have more info regarding this issue - today I checked my immich instance, and all the thumbnails are there. There is also a people list on the "explore" section - so my bet is, some job ran in a meantime and reindexed it? I'll investigate further later, but this may not be a bug after all...

**Comment by ajgon** [comment]
Ok, after manually running "Generate Thumbnails" job, everything appeared. So I assume the only "bug" here may be an order of jobs? I.e. first running extract metadata, and then generate thumbnails? (I'm not sure how immich handles that). 

I'll leave the issue open, because I'm not sure if it's intended behavior, or minor quirk :)

**Comment by alextran1502** [comment]
The behavior is expected, the facial data will show up once all the facial recognition and clustering jobs are finished

**Comment by ajgon** [comment]
Ok, so it's me didn't understanding it. Thank you for the clarification!

**Comment by mertalev** [comment]
I think it depends on thumbnail generation in this case. Metadata extraction runs before that and creates the face, but the Explore page hides people that don't have a person thumbnail. Person thumbnails are added to the end of the thumbnail queue, so it can take time for it to get through the rest of the assets.
