### ISSUE TITLE
Photo selection behaviour incorrect on web interface

### ISSUE THREAD

**Issue by kikendo** [immich-app/immich#12406]
### The bug

Clicking a picture on the web interface then shift clicking on another does not select a range from the first one to the second.
This seems to only happen on search results. It works on the Library view.

### The OS that Immich Server is running on

Debian Bullseye

### Version of Immich Server

v1.114.0

### Version of Immich Mobile App

/

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

Described above

**Comment by bo0tzz** [comment]
This is not a bug, range selection hasn't been implemented yet for the search view: #9159
