### ISSUE TITLE
[BUG] iOS app version 1.40.0 stalls at login. 

### ISSUE THREAD

**Issue by florihupf** [immich-app/immich#1240]
See title. 

Tried erasing app and reinstalling to no avail.  It does recognize credentials though. Giving it bad ones pops up red text that email/password are wrong.  

This is on iOS 16.1 on an iPhone X. 

HTH.

**Comment by SteliosPapamichail** [comment]
Can confirm! Same case for Android from my testing. It seems to connect just fine in the background but no navigation transaction happens.

**Comment by bo0tzz** [comment]
What is the version of your server?

**Comment by SteliosPapamichail** [comment]
> What is the version of your server? 

For me it's on the latest version.

**Comment by alextran1502** [comment]
Can you guys double check your server version and make sure it is on 1.40?

**Comment by florihupf** [comment]
I double checked right now and it is on v1.39.0.   Will report back if upgrade fixes it. :-)

**Comment by florihupf** [comment]
Can confirm everything works with v1.40.0. :- Thanks for the (obvious) pointer :-) Closing out.

**Comment by srwareham** [comment]
I'm having the same issue running iOS version 1.40.0 and the same server version. Although I'm not sure if it distinguishes between valid and invalid credentials. After clicking login I get the spinning animation and nothing happens. It will eventually timeout and then the login button returns, but doesn't seem to trigger anything when I click on it.
