### ISSUE TITLE
Wrong rotation HEIC / iPhone 15

### ISSUE THREAD

**Issue by Str1atum** [immich-app/immich#12405]
### The bug

I have some photos where I cannot really see a pattern, that are displayed in the wrong rotation in Immich after upload. I attach an example photo here.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

V.114

### Version of Immich Mobile App

113

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Standard
```

### Your .env content

```Shell
Standard
```

### Reproduction steps

1.upload the image via web from iPhone 
[IMG_6004.zip](https://github.com/user-attachments/files/16912073/IMG_6004.zip)

2.
3.
...

**Comment by alextran1502** [comment]
Interesting, I am guessing the IMU is messed up while you are on the plane so that it does not have the accurate information for the thumbnail generation to rotate correctly

**Comment by Str1atum** [comment]
Might be - but it's displayed correctly on the photos app on iOS and I have two other photos taken minutes apart which are correctly displayed.

**Comment by bo0tzz** [comment]
#8355
