### ISSUE TITLE
The Android mobile app prompts "Error occurred" when adding or modifying character names.

### ISSUE THREAD

**Issue by pyccl** [immich-app/immich#12421]
### The bug

When adding or modifying a character's name in a mobile app, an error message "Error occurred" appears. However, in reality, it can be seen in the web page that the modification has been successful (both Chinese and English have been tried with the same error).

![image](https://github.com/user-attachments/assets/8233c132-07f4-4fe6-9dc9-d6017b3abc49)
![image](https://github.com/user-attachments/assets/4f20ec32-c020-47c5-ae69-9044a3f982bb)

### The OS that Immich Server is running on

Windows 11 Docker Desktop V4.43.0

### Version of Immich Server

V1.114.0

### Version of Immich Mobile App

V1.113.1 build.2157

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

1.
2.
3.
...

**Comment by pyccl** [comment]
v1.114.0 the same error

**Comment by Acidiphilium** [comment]
Same here and yes even if there is this error, the change is applied.

**Comment by theoforger** [comment]
Could be a server side issue?

I tried to change the name and the server responded with:
```json
{
  "id":"7a3c1d8f-442a-417b-9ec1-00820383c02a",
  "name":"test",
  "birthDate":null,
  "updatedAt":"2024-09-09T17:54:01.430Z"
}
```
According to the logs, the error happened at line 94 here:
https://github.com/immich-app/immich/blob/7b2f98a433351bd8f02e86324c2c3b9ba51730fc/mobile/openapi/lib/model/person_response_dto.dart#L84-L101

My assumption is that the server response was missing two fields (`isHidden` and `thumbnailPath`), and the error happened when the client tried to deserialize that.

**Comment by AlexKalopsia** [comment]
Experiencing the same
