### ISSUE TITLE
Scrollbar iOS can't go all the way down.

### ISSUE THREAD

**Issue by gcarrarom** [immich-app/immich#12453]
### The bug

When scrolling on iOS, I'm trying to go all the way down to the last photo. But the scroll bar disappears much earlier than the end of my feed. Here's what I mean:

https://github.com/user-attachments/assets/acd98c41-0399-4b0e-a658-53f864ee8426

### The OS that Immich Server is running on

openSUSE MicroOS - k8s - docker.

### Version of Immich Server

v1.114.0

### Version of Immich Mobile App

v1.114.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Open immich with a bunch of assets on iOS.
2. Scroll and select the scrollbar to navigate.
3. Pull the scrollbar all the way to the bottom.
4. It won't go all the way to the end.

**Comment by bo0tzz** [comment]
Dupe: #12188
