### ISSUE TITLE
[BUG] Image grid is sometimes messed up

### ISSUE THREAD

**Issue by bt90** [immich-app/immich#1246]
**Describe the bug**

When scrolling quickly through the demo, sometimes the following glitch occurs:

![image](https://user-images.githubusercontent.com/1926175/210207958-522b9a27-f3a3-4367-91cb-586aa5704080.png)

Inspecting the HTML indicates that the timebucket divs are overlapping:

![image](https://user-images.githubusercontent.com/1926175/210208758-ffe52233-1613-47c0-9fef-47b6e949de95.png)

Tested with Firefox 108

**To Reproduce**
1. Open https://demo.immich.app/
2. Quickly scroll down
3. Wait for the glitch to appear

**System**
- Server Version: `1.40.0` (Demo installation visited on 2023-01-02)

**Comment by alextran1502** [comment]
Confirm this has been the issue I want to track down since implementing the smart grid system but haven't been able to fine where the state not updating yet. Will look into it in detail in the near future.

**Comment by nicolopozzato** [comment]
![image](https://user-images.githubusercontent.com/22364782/222924565-fd16ed54-035c-405c-a54f-5fc72c989bc8.png)

Doesn't need to scroll, some times I just open the page and i get this galley.
Immich server 1.50.1 with Chrome browser.
A reload (ctrl+r) doesn't fix the issue, also (ctrl+shift+r) doesn't do anything to the grid...
But reload a couple of times fix the issue...

**Comment by bt90** [comment]
Scrolling from bottom to top is almost impossible without causing severe distortion.

**Comment by alextran1502** [comment]
I notice you tested on Firefox, does Chrome do this on your side?

**Comment by bt90** [comment]
I still need to test it with Chrome, but at least the problem is reproducible. It always occurs in the same places in my timeline.

**Comment by alextran1502** [comment]
@bt90 I found the source of the current behavior on `main` it was due to a recent change of determine the viewport width to set the thumbnail size for mobile view. It cause the rerender of the timeline calculated bucket height

**Comment by alextran1502** [comment]
Resolved in #2666
