### ISSUE TITLE
[Feature]: Use Immich in one docker container.

### ISSUE THREAD

**Issue by CodebySven** [immich-app/immich#1247]
### Feature detail

When u use something like Portainer or Yacht you get 5 containers when your running Immich.
Is it possible to just use one container?

### Platform

Server

**Comment by bo0tzz** [comment]
There is a community-made single image at https://github.com/hydazz/docker-immich, but it's not supported by us. I strongly recommend just using the official setup - is there a particular reason you don't want to run multiple containers?
