### ISSUE TITLE
Export to ONNX failed

### ISSUE THREAD

**Issue by sushilkhadkaanon** [immich-app/immich#12496]
### The bug

When I try to run the script to export models to onnx, it fails 
I'm particularly interested in apple/DFN2B-CLIP-ViT-L-14 model. So I removed everthing in run.py file except "ViT-L-14-quickgelu::dfn2b",.
Please help me regarding conversion.

The error I get is :
`UnsupportedOperatorError: Exporting the operator 'aten::_native_multi_head_attention' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
`__

### The OS that Immich Server is running on

Ubuntu 20.04

### Version of Immich Server

.

### Version of Immich Mobile App

.

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
..
```

### Your .env content

```Shell
..
```

### Reproduction steps

1. Running the run.py script
2.
3.
...

### Relevant log output

```shell
UnsupportedOperatorError: Exporting the operator 'aten::_native_multi_head_attention' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues
```

### Additional information

ubuntu 20.04
python == 3.12.5
torch == 2.4.1
open_clip_torch == 2.26.1
onnxruntime-gpu == 1.19.2
onnx == 1.16.2

**Comment by mertalev** [comment]
Hmm, the line `torch.backends.mha.set_fastpath_enabled(False)` should avoid this error. Also, make sure you’re using the Conda/Mamba environment in that folder to have the right dependency versions.

**Comment by HarshUnadkat** [comment]
Use a different opset version:

torch.onnx.export(model, input_tensor, "model.onnx", opset_version=16)

**Comment by sushilkhadkaanon** [comment]
Hi @mertalev , Yes it workedddd!!! Thanks a lot  What does this line do cause I coudn't find any reference to this function. And why do you beleive it should avoid the problem. Thank you for your response!

@HarshUnadkat already tried all the opset versions.

**Comment by sushilkhadkaanon** [comment]
@mertalev I saw the implementation, it say it disables C++ Kernel for nn.Functional.MHA and nn.TransformerEncoder.
Would you please help me understand how did this help?

**Comment by mertalev** [comment]
Glad to hear it worked! The fast path is used in eval mode when gradients are disabled. This path isn't supported by PyTorch's ONNX exporter, so it needs to be disabled for the model to export in this case.
