### ISSUE TITLE
[BUG] Information pop-up is hidden behind webUI User Settings bar

### ISSUE THREAD

**Issue by Chipwingg** [immich-app/immich#1249]
**Describe the bug**
On the webUI at the address `<immich-address>/user-settings` the information pop-up for `Photos` on the sidebar is behind the title bar `User Settings`. 

**To Reproduce**
1. Go to `<immich-address>/user-settings`. I have only tested this on the admin account, which is my only account. 
2. On the side bar on the left, hover your mouse over the `🛈` symbol next to `Photos`.

**Expected behavior**
A small pop-up will appear, but it would be mostly hidden behind the title `User Settings`. 

**Screenshot**
![Screenshot_20230102_111403](https://user-images.githubusercontent.com/102692588/210259816-ae418ee0-bded-4bd3-990f-e89cd6594d0c.png)

**System**
- Phone OS `N/A`
- Server Version: `v1.40.0`
- Mobile App Version: `N/A`
- Browsers this happens in: `Brave (Chromium based) and Firefox`

**Note**
This is relatively a minor issue, and it doesn't impact the day-to-day usage of this app. It is simply a cosmetic problem as far as I can tell.

**Comment by jrasm91** [comment]
Confirmed.
