### ISSUE TITLE
v114.0 - All tags has become just one long string (tag)

### ISSUE THREAD

**Issue by GD-Dal** [immich-app/immich#12516]
### The bug

First, thanks for adding tags (metadata) into v1.113.
And it was a rather good implementation, too
All my IPTC keywords that I had added to the pictures (from external folders) in Lightroom were parsed in a separate tags.

This is what it should look like, and it's taken from a picture that lies in an external folder
![image](https://github.com/user-attachments/assets/4dca144c-28db-42dd-b1bd-29aacb2afaea)

But then I uploaded pictures from my Android phone, and I discovered that those pictures had not many tags, but all tags in one long.. tag (string?)
This is the tags from the same picture when uploaded from my phone:
![image](https://github.com/user-attachments/assets/eec3d2ff-6091-4a0d-9cb7-76b2ce987449)

It seems to have similar problems when uploading from my PC as well.

Anyone else experienced this?

Thanks

### The OS that Immich Server is running on

Unraid docker

### Version of Immich Server

v1.114

### Version of Immich Mobile App

v.114

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. Uploading pictures from phone or web

**Comment by jrasm91** [comment]
Fixed in https://github.com/immich-app/immich/pull/12509

**Comment by karl007** [comment]
Does not work in v1.115 🙁 
Images has multiple tags separated by `,` in the iptc metadata `keywords`.
I scanned this images with v1.112 or v1.113 and after updating to v1.114, I do a job `extract metadata` for all and an `SIDECAR METADATA` sync.

Now I'm on v1.115.0 and the tags are still a single long strin. Did I miss something?

**Comment by jrasm91** [comment]
I think that is a separate issue. This fixed something related to HierarchalSubjects. Can you open another request and upload the file that isn't working (as a zip)?

**Comment by karl007** [comment]
> I think that is a separate issue. This fixed something related to HierarchalSubjects. Can you open another request and upload the file that isn't working (as a zip)?

No, this issue is for multiple tags (spearated by ,) not Hierarchal tags (separated by >). But the FIX #12509 only describes Hierarchal, so maybe this is the error?

Also #12542 seems like multiple tags, not Hierarchal.

But while looking for an image for example, I recognize that my images are now all OK, but the old long tags are still there 🙁
I redo the both jobs this night and it seems this do the job, so issue closed for me, Thanks.

**Comment by jrasm91** [comment]
Sounds like your issue was fixed then. Correcting old, empty tags is being worked on in #12654.
