### ISSUE TITLE
Mobile App Scrolling Bug

### ISSUE THREAD

**Issue by datt-daniel** [immich-app/immich#12532]
### The bug

I have noticed that when I scroll down with the immich mobile app using the scroll bar on the right, it goes all the way down under the bottom bar that contains library, sharing, search, and photos buttons. Instead of doing this it should end at that bottom bar like google photos does. 

### The OS that Immich Server is running on

TrueNAS SCALE 24.10

### Version of Immich Server

1.113.1

### Version of Immich Mobile App

1.114.0 build.158

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Open mobile app
2. scroll with scroll bar provided on right hand side all the way down and the issue reveals itself

**Comment by radh21301** [comment]
It is a known bug. Should be fixed by this:

https://github.com/immich-app/immich/pull/12512
