### ISSUE TITLE
"Error occured" when Add a name for People in Android app

### ISSUE THREAD

**Issue by voitekhovich** [immich-app/immich#12567]
### The bug

When you add a name to a recognized face and click save, the error "Error occured" appears.
The "Add name" window closes with an error via the Cancel button.
If you restart the application, the added name appears.

The name is displayed immediately via the Web.

![Screenshot_20240911_141836](https://github.com/user-attachments/assets/5f8ef3ce-e061-401e-a507-39267ae7d1b7)

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.114.0

### Version of Immich Mobile App

1.114.0 build.158

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

1. Open People card
2. Add a name for people
3. Click Save

### Relevant log output

```shell
MESSAGE:
Error while updating person name

DETAILS:
Null check operator used on a null value

FROM:
PersonService

STACK TRACE:
#0      PersonResponseDto.fromJson (package:openapi/model/person_response_dto.dart:94)
#1      ApiClient.fromJson (package:openapi/api_client.dart:423)
#2      ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#3      PeopleApi.updatePerson (package:openapi/api/people_api.dart:541)
<asynchronous suspension>
#4      PersonService.updateName (package:immich_mobile/services/person.service.dart:72)
<asynchronous suspension>
#5      updatePersonName (package:immich_mobile/providers/search/people.provider.dart:39)
<asynchronous suspension>
#6      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>
```

**Comment by alextran1502** [comment]
Fixed and will be available in the next release
