### ISSUE TITLE
[BUG] App freezes and is sluggish when having a lot of photos

### ISSUE THREAD

**Issue by Fenisu** [immich-app/immich#1257]
**Describe the bug**
When opening the app and when scrolling, the app freezes for around 5-10 seconds. It worked fine until I filled up it with all my photos, around 50k photos in 15y

My hunch is that the app expects to read from the phone's / app cache the thumbnails instantly. But when there are 50k thumbnails it doesn't. 

The app is version 1.40.0. Running on Pixel 4a 5g.

Running the server from docker on a Xeon E31260L and 8gb. But I doubt the server has anything to do with it since there seems to not be any traffic when it happens. 

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [ x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x ] I have included information on my machine, and environment.

**To Reproduce**
1. Open app
2. Splash screen freezes halfway 
3. App unfreeze and show photogrid
4. Scroll down towards middle of timeline
5. App scrolls, shows gray empty pictures and freezes.
6. App unfreeze and updates the view. 

**Expected behavior**
The app should load instantly. Either empty gray photos and load and update in the background. Try not to block main UI thread with IO. 

**Screenshots**
-

**System**
- Pixel 4a 5G A12: `Android 12`
- Server Version: `1.40.0`
- Mobile App Version: `1.40.0`

**Additional context**
I belive this is a performance issue related to the phone's HW.

**Comment by alextran1502** [comment]
Thank you for the info we are working on improving the performance in #1176 by doing exactly what you described, updating the cache in another thread to avoid blocking UI thread

**Comment by Fenisu** [comment]
Good to know! Thanks!
