### ISSUE TITLE
GENERATE THUMBNAILS job not prioritizing new uploads during an all-files run in large libraries

### ISSUE THREAD

**Issue by coltenkrauter** [immich-app/immich#12578]
### The bug

I encountered an issue with the `GENERATE THUMBNAILS` job when running it against `ALL` files in a large library (~500k images/videos, 5TB). While running this job, thumbnails for newly uploaded images and videos were not generated, leading to missing thumbnails on the main `/photos` page.

![missing-thumbnails](https://github.com/user-attachments/assets/ea97025b-1909-4256-9e42-f92a3f8f8034)

After canceling the job and then running the job against missing thumbnails, the issue was resolved and I see thumbails for recent uploads., but I will now need to restart the `GENERATE THUMBNAILS/ALL` job, which is time-consuming.. And now is re-runninging against thousands of files.

## Proposed Solution
Could there be an option to prioritize thumbnails for new uploads, even when the `ALL` job is running?

[This is the reason that I am running this job against ALL files.](https://github.com/immich-app/immich/discussions/9547#discussioncomment-10548329)

### The OS that Immich Server is running on

TrueNas Scale Immich App

### Version of Immich Server

v1.113.1

### Version of Immich Mobile App

1.114.0 build.173

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
TrueNas Scale Immich App
```

### Your .env content

```Shell
TrueNas Scale Immich App
```

### Reproduction steps

1. Run the "GENERATE THUMBNAILS" job for all files in a massively large library.
1. Upload new images/videos while the job is still running.
1. Check the /photos page to see missing thumbnails for newly uploaded files.

### Additional information

This issue affects large libraries and may not impact smaller setups.

**Comment by zackpollard** [comment]
When running large imports like this, the queue will be saturated. We don't have any prioritisation or even ordering for these queues, though things added first do tend to get processed first. We don't have any plans to add prioritisation for this, so this is working as intended right now.

**Comment by coltenkrauter** [comment]
Do you have any flexibility on this?

I think that this warrants consideration, or some kind of workaround perhaps. (please let me know if this doesn't make sense.)

It's my intention to run Immich servers for my family, but if running a job like the thumbnail generation job against all assets (which could take to a large library) means that folks won't see image thumbnail, that creates a pretty poor user experience. 

I completely understand that perhaps the system isn't designed to help with this kind of issue right now. But, since this is a legit situation, isn't it worth considering the user experience here?

**Comment by coltenkrauter** [comment]
Another idea, I have for a way to solve this would be to create a secondary thumbnail generation job. So the first job could be dedicated to recent uploads, you could potentially even be hidden or something. Then the second thumbnail generation job could be run against a bunch of files without impacting the user experience.

**Comment by zackpollard** [comment]
This is only a problem when you're running imports for those users initially, that should be a very infrequent task. After those are done the system will work as intended. This is the nature of queuing systems in general.

**Comment by coltenkrauter** [comment]
At very minimum, it might be useful to add a note somewhere on the jobs page that indicates that running these jobs against a lot of assets could lead to a poor user experience as newly uploaded assets may not get processed in a timely manner.

**Comment by coltenkrauter** [comment]
Feature request – https://github.com/immich-app/immich/discussions/15776
