### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by utkarsh030201** [immich-app/immich#1258]
**Describe the bug**
Unable to install the app after multiple tries, consistently getting the same 
`bash: line 8: syntax error near unexpected token `newline'` error.

**To Reproduce**
1. run `curl -o- https://raw.githubusercontent.com/immich-app/immich/main/install.sh | bash`
this gets no result and the request times out

2. copy the URL from github and running manually 
**Expected behavior**
Script works

**Screenshots**

**System**
- Ubuntu Server

**Additional context**
<img width="791" alt="image" src="https://user-images.githubusercontent.com/53508181/210849435-5949bd69-be4c-4f0b-b692-3abdfa21e844.png">

**Comment by bo0tzz** [comment]
The command in your screenshot is different (and wrong) from the one you posted in the text

**Comment by utkarsh030201** [comment]
my bad, here's with the correct command
<img width="624" alt="image" src="https://user-images.githubusercontent.com/53508181/210852509-1269bfe6-0587-4945-8a94-b1b433e79fc4.png">

**Comment by bo0tzz** [comment]
Your system can't reach the github servers, you probably have an issue in your networking somewhere.

**Comment by utkarsh030201** [comment]
i can go to GitHub and get a link and download the script using `wget`, and run it manually. still the same issue though.
<img width="591" alt="image" src="https://user-images.githubusercontent.com/53508181/210853723-6dbc527d-c3e1-4881-a291-d69d031a97bd.png">

**Comment by bo0tzz** [comment]
Now you're using the wrong URL again ;)

**Comment by utkarsh030201** [comment]
man! i'm beat, i got this URL directly by copying it from the GitHub. and the one that's on the tutorial isn't working. Even though the server is pinging Github normally. 

Any suggestions on what to do?

**Comment by alextran1502** [comment]
My guess is your networking. 

You can try running the command without `sudo`

**Comment by alextran1502** [comment]
Also please compare the content of the file you download using `wget` with this file https://raw.githubusercontent.com/immich-app/immich/main/install.sh
