### ISSUE TITLE
Create Album - Done Button is grayed out

### ISSUE THREAD

**Issue by chriswa81** [immich-app/immich#12645]
### The bug

There is a small unsightly error:
When I go to “Create Album”, then “Select Photos” and then drag'n drop photos in and the upload is complete, the “Done” button is grayed out.

![00_immich](https://github.com/user-attachments/assets/b0a7f1c5-0372-4ea0-9792-077cee0eec13)
![01_immich](https://github.com/user-attachments/assets/9ba75240-751d-42bf-8e41-1c0d65aed907)
The illustration is only an example, the Immich demo does not allow photo uploads. After uploading the photos via drag'n drop, the “Done” button stays grayed out.
![02_immich](https://github.com/user-attachments/assets/1ead44ab-932c-4ffb-9540-7fc0b46c2ed7)

### The OS that Immich Server is running on

Debain 12

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. Create Album
2. Select Photos
3. Drag'n drop photos in and the upload is complete

Result: The “Done” button is grayed out.

**Comment by Mraedis** [comment]
I cannot reproduce this, could you share the compose file/env and perhaps what system you are running this on?

**Comment by chriswa81** [comment]
I'll pass on the information later. Immich Server runs via Docker Container.
What is also important for reproducing the error is that after new photos have been dragged in via drag'n drop, no existing photos are selected. Then the Done button remains grayed out. The button only becomes active if I also select existing photos that are already on the server.

**Comment by Mraedis** [comment]
Looks like you're mixing two things here, you can always upload new images on any page, even on the "create album" page. 🙂
