### ISSUE TITLE
iOS App - Scrolling Bug in search

### ISSUE THREAD

**Issue by interunivers** [immich-app/immich#12655]
### The bug

When searching in the iOS App for picture with a date range set. You can scroll to the bottom of the of the page because it keeps jumping back to the top once you scrolled a tiny bit past the last picture. 

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not available
```

### Your .env content

```Shell
Not available
```

### Reproduction steps

Go to search page, select date range  for pictures to be shown (more obvious when searching in a larger range)scroll to the bottom till the limit.

**Comment by m4v** [comment]
This also happens in android, immich mobile 1.114.
Is not only when you scroll to the bottom of the search results, but will also happen if you try to add a picture (a picture in the search results, not in the timeline screen) to an album and scroll to the bottom of the album list.
I don't see errors in the logs.

**Comment by bo0tzz** [comment]
#8635
