### ISSUE TITLE
bug(mobile): Scrolling to the bottom of a searchpage reloads the search screen.

### ISSUE THREAD

**Issue by hermesespinola** [immich-app/immich#12685]
### The bug

Whenever you do a search (not sure if this happens in other screens, at least it doesn't happen in the main timeline), and scroll to the bottom, Immich will crash and reload all the photos, making it so it goes back to the top of the search page. Happens in both Android and iOS, and has been an issue for a couple of releases now.

### The OS that Immich Server is running on

Linux raspberrypi 6.1.0-rpi7-rpi-2712

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

1. Search something
2. Scroll to the bottom using the scroll thingy at the right edge of the screen.
3. Reload happens.

### Relevant log output

```shell
App doesn't show any logs after reproducing the bug.
```

**Comment by bo0tzz** [comment]
#8635
