### ISSUE TITLE
Docker Compose not reading .env file as well full other errors while running it on Win 10 with docker.

### ISSUE THREAD

**Issue by Gur15** [immich-app/immich#1268]
I am using Windows 10 machine with docker installed on it.

I have noticed that when I run docker compose up -d, it wont read .env file.
Both compose file and env are in same folder.
Upload location is also set correctly in env file, for the test sake i tried using backslash and forward slash in upload location but it still wont read it and gives the error that Empty Section Between Colons ( screenshot below ). also its setting up variables to blank string.

<img width="730" alt="Error" src="https://user-images.githubusercontent.com/122171619/211162612-a2c3aafe-4ba1-4717-94a0-1d029c36c2d2.png">

In docker compose when i removed $ sign in front of upload location then it seems to go past that error but then it gives different error. 
<img width="720" alt="Error 2" src="https://user-images.githubusercontent.com/122171619/211162825-e1b7cee5-0c82-45d0-a45b-bf89aef842d2.png">

Let me know if am doing something wrong or if this is an issue.
if you need more information please let me know.

thank for your help again.

**Comment by alextran1502** [comment]
1. Can you post your `.env` and `docker-compose.yml` file?
2. From the `immich` directory can you run `ls` and take the screenshot of the output?

**Comment by Gur15** [comment]
as soon i ran the ls command, i see that .env file was saved as .env.txt, so i installed notepad++ and it saved the .env file and now docker compose is running. I was able to set it up on windows machine. thank you so much for help. you can close the case
