### ISSUE TITLE
Immich Mobile app privacy policy on Google Play outdated

### ISSUE THREAD

**Issue by Zoobdude** [immich-app/immich#12700]
### The bug

The privacy policy link on Google Play underneath the "App support" section:
![image](https://github.com/user-attachments/assets/818dfe0e-3837-4914-bc56-66ca481961a2)

Seems to take you here - https://pages.flycricket.io/immich/privacy.html

Now that https://immich.app/privacy-policy/ exists and is used on the Apple App Store, I would assume it should take you there instead?

### The OS that Immich Server is running on

n/a

### Version of Immich Server

n/a

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

1. Navigate to Immich App on Google Play
2. Pop-out the app support section
3. Select 'Privacy Policy' from the menu

**Comment by alextran1502** [comment]
Indeed, thanks for the reminder

**Comment by alextran1502** [comment]
Done, sent for review
