### ISSUE TITLE
Photo rotation of embeded previews wrong

### ISSUE THREAD

**Issue by timothyfrn** [immich-app/immich#12720]
### The bug

When I upload raw pictures into Immich and create thumbnails with the "Use embedded preview" feature enabled, Immich rotates vertical pictures 90 degrees. When I turn off the "Use embedded preview" feature, the pictures are rotated correctly, but the colors are displayed incorrectly.

### The OS that Immich Server is running on

Unraid 7.0.0-beta.2

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0 build.159

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

1.Turn on "Use embedded preview" for thumbnail and preview images
2.Upload vertical Sony compressed RAW files

### Additional information

Embedded preview:
![Immich Test picture embedded preview](https://github.com/user-attachments/assets/dba818a3-bdcb-4ee9-92e7-30d4a121a2cf)

Embedded preview off:
![Immich Test picture no embedded preview](https://github.com/user-attachments/assets/17e876b8-e7f6-4d59-9882-1217300e34ad)

Raw File:
https://drive.google.com/file/d/1vZvrNVNe3mjakngBEM52I6JpdLPtZtX9/view?usp=drivesdk

**Comment by bo0tzz** [comment]
Can you share a zip with a file that this happens on?

**Comment by karl007** [comment]
Same error here - Image is .NEF and has a TIFF Header orientation = 8 (I think it is , is only shown in german)
Image is too large to upload: https://www.file2send.eu/de/download/d7F6OAVq2TiWUqv1lTL3YjO69KC5kYcboXW2vPir0BqWYw1TXsu2FveUWUehyl2w

**Comment by zynexiz** [comment]
Have the same issue with "Use embedded preview", but I needed to enable it to get any thumbnails with good quality. Without it the thumbs looked like 64x64 jpeg with extreme compression rate (for NEF's).

**Comment by Seany70363** [comment]
I also have this issue using v1.117.0 with embedded preview enabled.
Raw files taken using a Sony camera (.ARW) held portrait.
The ratio of the thumbnail is portrait - but the picture itself is landscape, rotated 90 degrees.
Hoping this is fixed soon!
