### ISSUE TITLE
Face Selection Page Resets to Top After Navigating Back

### ISSUE THREAD

**Issue by Mansour-J** [immich-app/immich#12771]
### Description:
When a user selects a face and navigates back to the previous screen, the page automatically scrolls back to the top instead of retaining the user's previous scroll position. This forces users to scroll down and find where they left off, causing a poor user experience.

I have 782 faces(people) in my instance and makes me to scroll down all the time when I navigate back.

**Expected behavior:**
The page should retain the scroll position and return the user to where they left off.

**Actual behavior:**
The page resets to the top, causing the user to lose their place. 

### The OS that Immich Server is running on

Windows

### Version of Immich Server

v1.115.0 (Latest)

### Version of Immich Mobile App

N/A (I don't use the mobile app)

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
The default
```

### Your .env content

```Shell
The default
```

### Reproduction steps

1. Navigate to the face selection page.
2. Scroll down and select any face.
3. Use the back button to return to the face selection page.

### Relevant log output

```shell
N/A
```

### Additional information

N/A

**Comment by bo0tzz** [comment]
3114
