### ISSUE TITLE
[BUG] Images not added to shared album from guest upload

### ISSUE THREAD

**Issue by klejejs** [immich-app/immich#1278]
**Describe the bug**
I tried uploading some photos as guest from mobile, they were uploaded the first time, but not added to the album. If I try to upload them again, nothing happens and they are still not added to the album.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Upload images to the Immich instance
2. Try unloading them again as a guest to a shared album

**Expected behavior**
Images are added to shared albums.

**System**
- Phone OS: `Android 11`
- Server Version: `v1.41.0`

**Comment by bo0tzz** [comment]
Looks like there is some code to handle the case of an asset already existing and still add it to the album (https://github.com/immich-app/immich/blob/main/web/src/lib/utils/file-uploader.ts#L132-L140), but it doesn't pass the `sharedKey`. The `addAssetsToAlbum` key call after successful upload does: https://github.com/immich-app/immich/blob/main/web/src/lib/utils/file-uploader.ts#L162.
