### ISSUE TITLE
[Feature]: Combined shared album

### ISSUE THREAD

**Issue by aksdb** [immich-app/immich#1280]
### Feature detail

Use case: on vacation, my wife and me take photos with our devices. We upload them to immich each. Now it would be nice, if we could have one album of that vacation which combines both our photo collections. That album in turn can then also be shared with other users or "published" (for viewing).

### Platform

Server

**Comment by jrasm91** [comment]
You can already create an album and share it with someone, and now you can also generate a public share link.

Is there something specific you are asking for that is different from what's already possible?

**Comment by aksdb** [comment]
@jrasm91 I can share the album, but it can only include my photos. My wife can't add her photos to my album.
I basically want an album that shows my and my wife's vacation photos. Here's are in her account, mine in my account.

**Comment by jrasm91** [comment]
This is already possible, both on mobile and on the web. Two people can contribute to a single album. Is it unclear how that can be achieved?

**Comment by jrasm91** [comment]
![Screenshot_20230110-091321.png](https://user-images.githubusercontent.com/4334196/211574336-edd42b70-a70a-4c92-a73f-28d6115c0a3e.png)

**Comment by aksdb** [comment]
Hmm, I need to try this again. When I tried it seemed to be "read only" for the other user. Maybe I f*cked this up somehow.

**Comment by aksdb** [comment]
:man_facepalming: It worked now. I was probably just blind the first time and overlooked the "add" button on the other phone. Sorry about that.

**Comment by jrasm91** [comment]
No worries!
