### ISSUE TITLE
[BUG] Notification shows 'backup_background_service_default_notification' instead of translated string

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#1281]
**Describe the bug**
When Immich starts checking for new items, a notification appears.
However, doesn't show the translation string. It instead shows 'backup_background_service_default_notification'. 
See screenshot below

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Set system language to Dutch
2. Enable background backup
3. Take a picture to trigger detect mechanism

**Expected behavior**
I expected the notification to have a proper translated string instead of this.
It is kind of weird, because the string is translated in Dutch [here](https://github.com/immich-app/immich/blob/0164171cad2441f0630fde4d602981dac55dea47/mobile/assets/i18n/nl-NL.json#L19).
All the other notifications show the translated string properly, except this one.

**Screenshots**
![image](https://user-images.githubusercontent.com/47184046/211565664-d3194ef1-5521-46f3-9438-919635713af6.png)

**System**
- Phone OS [iOS, Android]: `Android 12`
- Server Version: `1.41.0`
- Mobile App Version: `1.40.0`

**Additional context**

**Comment by RealFascinated** [comment]
I have also had this happen a few times, and yeah the rest work for me.

**Comment by JVT038** [comment]
> Hello, are the rest of the text are translated correctly?

Yes.

**Comment by alextran1502** [comment]
Hello has this issue been fixed?

**Comment by JVT038** [comment]
Nope

**Comment by fyfrey** [comment]
I've also randomly (very infrequently!) encountered this issue. Does it occur for you every time?

**Comment by fyfrey** [comment]
Closed due to inactivity; could not reproduce this in the last few months.

**Comment by fyfrey** [comment]
Closed due to inactivity; could not reproduce this in the last few months.
