### ISSUE TITLE
Videos do not show on iOS app (and not backed up)

### ISSUE THREAD

**Issue by pablopunk** [immich-app/immich#12811]
### The bug

Hi! I had immich before and this wasn't an issue. Now I installed it on another server (via TrueNAS scale apps) and iOS photos are backing up just fine but the immich app on iOS doesn't show my latest videos and it's not backing them up either.

### 👇🏻 Left: iOS gallery with photos/videos. 👇🏻 Right: iOS immich with photos only

<img width="40%" src="https://github.com/user-attachments/assets/7c2f4966-4492-40fc-b99c-1eee2d76c3f7" />
<img width="40%" src="https://github.com/user-attachments/assets/b7c90b7e-4480-449c-baf9-c1e6555582bb" />

### The OS that Immich Server is running on

TrueNAS Scale

### Version of Immich Server

1.115.0

### Version of Immich Mobile App

1.115.0 build.175

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
# done through the TrueNAS UI
```

### Your .env content

```Shell
# done through the TrueNAS UI
```

### Reproduction steps

Honestly I don't know, it used to work. And yes, I have the "Videos" folder enabled in the iOS app settings.

### Additional information

I'm using a Cloudflare Tunnel. I've tried directly using my local IP (which was what I did on my previous server) but that didn't seem to solve it.

**Comment by alextran1502** [comment]
I am seeing the spinner at the bottom of the app bar, meaning the app is still hashing, depends on how much photos and videos do you have ok the device, it might take sometimes. Just let it be and it will show up once the hashing process is done. Just to clarify, can you take a screenshot of the albums you select for backup?

**Comment by bo0tzz** [comment]
As an extra note, any files >100MB will not be able to upload through clouflare tunnel.

**Comment by pablopunk** [comment]
> I am seeing the spinner at the bottom of the app bar, meaning the app is still hashing, depends on how much photos and videos do you have ok the device, it might take sometimes. Just let it be and it will show up once the hashing process is done. Just to clarify, can you take a screenshot of the albums you select for backup?

@alextran1502 good to know! I have around 32k pictures and 7k videos, so what you said makes a lot of sense. The albums I'm selecting to backup are basically all of them, including one that says "videos"

> As an extra note, any files >100MB will not be able to upload through clouflare tunnel.

@bo0tzz ah I forgot about that, I'll keep the local IP then, since videos can get quite heavy

**Comment by pablopunk** [comment]
Is there a way to know how the hashing process is going?

**Comment by pablopunk** [comment]
There was definitely something wrong with Immich. I waited and waited, but nothing changed. I ended up removing everything, installing a brand new Immich image, and starting the backup from my iPhone all over again (I still had the pictures in iCloud). Now the videos are working, even though it has only backed up one-third of the total items so far.
