### ISSUE TITLE
Unable to favorite a picture from a partner share

### ISSUE THREAD

**Issue by yurividal** [immich-app/immich#12958]
### The bug

I have partner sharring enabled, and I have set the partner photos to show in my gallery.
When i try to add a picture owned by my partner as a favorite (pressing the heart icon) i get a popup message which says "Added 0 to favorites".
The picture is not added to the favorites. 

### The OS that Immich Server is running on

Ubuntu 22.04 - Docker

### Version of Immich Server

v1.116.0

### Version of Immich Mobile App

v1.116.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
same as example docker-compose
```

### Your .env content

```Shell
same as example .env file
```

### Reproduction steps

1. Enable partner sharing
2. Enable "Show in timeline"
3. From the timeline, select a picture that is owned by the partner
4. Click the heart icon to add to favorites
5. See the info popup
6. check favorites folder. photo is not there.
...

**Comment by bo0tzz** [comment]
This is not supported yet

**Comment by yurividal** [comment]
@bo0tzz if its not planned, maybe the button should be hidden, or the info message should be a bit more user-friendly.
