### ISSUE TITLE
[BUG] Web interface can create empty albums

### ISSUE THREAD

**Issue by EnochPrime** [immich-app/immich#1296]
**Describe the bug**
The create album page from the web interface allows creating an empty album.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. From web browser to albums
2. Click 'Create album'
3. Give the album a name, but don't add any pictures
4. Click the back arrow
5. A new album with the given name is created with no pictures

**Expected behavior**
The creation should be canceled and no album should be created.

**Screenshots**

**System**
- Phone OS [iOS, Android]: `N/A`
- Server Version: `v1.41.0_64-dev`
- Mobile App Version: `N/A`

**Additional context**
Personally, I like the idea of being able to create an empty album because of the public sharing feature. However, if is forbidden in the mobile app to create any album without any pictures.

**Comment by alextran1502** [comment]
This is the intended behavior on the web

**Comment by alextran1502** [comment]
on the mobile, we can take a look at the empty album in your other opened issue.
