### ISSUE TITLE
Quick selection with CTRL+SHIFT not possible in search selection

### ISSUE THREAD

**Issue by DaanHend** [immich-app/immich#13001]
### The bug

When searching for items, I am unable to select a range of items using CTRL+SHIFT, which is the normal behavior in the overview. This makes it difficult to select and add multiple items to an album. Furthermore, this limitation is inconsistent with the functionality available in other views, such as the normal overview. For example, adding 800 pictures with a certain criteria to an album requires manually selecting each item individually, which is time-consuming and inefficient.

### The OS that Immich Server is running on

DMS 7

### Version of Immich Server

1.116.2

### Version of Immich Mobile App

1.116.2

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Default
```

### Your .env content

```Shell
Default
```

### Reproduction steps

1. Open the application and navigate to the search results view.
2. Perform a search for a specific item or group of items.
3. Attempt to select a range of items using CTRL+SHIFT while in the search results view. The selection should not be possible, and individual items can only be selected one at a time.

**Comment by bo0tzz** [comment]
#9159
