### ISSUE TITLE
[BUG] No file name in info when there is no EXIF data

### ISSUE THREAD

**Issue by adamaze** [immich-app/immich#1307]
**Describe the bug**
When viewing a file in immich that has no EXIF data, the "info" section simply says "NO EXIF INFO AVAILABLE", when it should likely at least include the file name.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. upload picture with no EXIF 
2. Click on uploaded picutre
3. click on info
4. See the distinct lack of "info" in the "info" section

**Expected behavior**
Even though there is no EXIF data, i expect to see what little info we have, like the file name

**Screenshots**

**System**
- Phone OS [iOS, Android]: `<version>`
- Server Version: `<version>`
- Mobile App Version: `<version>`

**Additional context**

**Comment by alextran1502** [comment]
Fixed in #1326
