### ISSUE TITLE
Live Photos from iOS18 show up as broken 

### ISSUE THREAD

**Issue by mikaelj** [immich-app/immich#13109]
### The bug

Images show up as broken in shared photos. See "how to reproduce".

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.116.2

### Version of Immich Mobile App

v1.116.1 build 177

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Latest from github.
```

### Your .env content

```Shell
Latest from github.
```

### Reproduction steps

1. User A on iOS 17 creates a photo album and uploads photos.
2. User A shares it with User B.
3. User B on iOS 18 uploads Live Photos to the shared album
4. Media shows up as broken images, but with correct size and file information:

![Skärmavbild 2024-10-02 kl  09 49 53](https://github.com/user-attachments/assets/3ff52ce4-932f-41a8-9684-fec3c6ac42b3)

![Skärmavbild 2024-10-02 kl  09 50 19](https://github.com/user-attachments/assets/5a6f0502-8a2a-43f8-82f8-cec74f50dd42)

**Comment by alextran1502** [comment]
I cannot reproduce this issue :thinking

**Comment by mikaelj** [comment]
@alextran1502 me neither, because today the media (thumbs and fullsize) is shown correctly. o_O

Maybe related to slow disk storage on a slow CPU and thumbs not created properly? But you should still be able to display the full-size image, something not possible yesterday.
