### ISSUE TITLE
The backup is stuck due to unsupport file type

### ISSUE THREAD

**Issue by onstring** [immich-app/immich#13107]
### The bug

I met with the issue several time that the backup is stuck due to some pictures upload is failed. The Failed backup gives me the logs as:

Unsupported file type 16998.pic

I don't know why I got the file with this format, but think it will be better that Immich can skip the failed upload and continue its backup.

### The OS that Immich Server is running on

MacOS

### Version of Immich Server

v1.116.2

### Version of Immich Mobile App

v1.116.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Using default one from release page
```

### Your .env content

```Shell
Using default one from release page
```

### Reproduction steps

1. Start backup from Iphone app.
2. Backup is going on well until it is stuck by some unsupported format
3. Only if I deleted the file, the backup can continue
...

**Comment by bo0tzz** [comment]
Dupe: #2892
