### ISSUE TITLE
[BUG] Portrait images uploaded from iPhone are not intact when downloaded from web UI

### ISSUE THREAD

**Issue by zkhan93** [immich-app/immich#1315]
**Describe the bug**
a portrait image initially uploaded from iPhone, when downloaded via web UI is not intact 

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. download a portrait image from web 
2. compare hash of original and downloaded file 
3. they should be same, but you will see a difference

**Expected behavior**
hash should match/ image should be valid
web UI should that the uploaded portrait image is a .jpg.
The issue seems to be on the uploading side

**Screenshots**

**System**
- Phone OS [iOS, Android]: `iOS`
- Server Version: `1.40`
- Mobile App Version: `1.40`

**Additional context**

**Comment by jrasm91** [comment]
This bug report is quite old, is this still a current issue?

**Comment by jrasm91** [comment]
Closing stale issue, can be reopened if still a problem.

**Comment by marcelschmidtdev** [comment]
Can we re-open this? This is still an issue with v1.118.2 and I almost noticed too late losing all the data for portraits.
Repo steps are:
1. Backup a portrait with the iOS App
2. Delete the portrait from device
3. Either re-download the portrait from the app or download via webinterface
4. Import asset into Photos app
You will see, the downloaded portrait will no longer have the correct portrait data. If you try edit it you can no longer change its aperture
