### ISSUE TITLE
[BUG] Screenshots appear to be taken in the future in timeline

### ISSUE THREAD

**Issue by sagniKdas53** [immich-app/immich#1320]
**Describe the bug**

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

`.env` and `docker-compose` in this zip file below:
[immich_info.zip](https://github.com/immich-app/immich/files/10413472/immich_info.zip)

**To Reproduce**
1. Take screenshot
2. Wait for it to be uploaded to immich
3. Open web-UI or android app

**Expected behavior**
Screenshots should appear in the timeline on the day they are taken. 

**Screenshots**
Screenshots appear in the future, they are in order of taking.
![Screenshot_2023-01-13_21:44:31:715](https://user-images.githubusercontent.com/40667155/212370202-2adc18d9-5c70-4c5a-b03f-6b8d12db05ee.png)

Photos appear correctly:
![Screenshot_2023-01-13_21:45:24:242](https://user-images.githubusercontent.com/40667155/212370310-853b0f17-b907-42d7-840c-22885972a2b7.png)

The Storage Template saves the files in correct location:
![Screenshot_2023-01-13_21:44:43:667](https://user-images.githubusercontent.com/40667155/212370540-1033052f-8d54-4aa3-abc5-803e451e1b4c.png)

The EXIF data of the Screenshots are correct:
![Screenshot_20230113_210628](https://user-images.githubusercontent.com/40667155/212370721-fe411bba-8bac-4011-87cb-20cf4953ddb1.jpg)

**System**
- Phone OS [iOS, Android]: `Android 11`
- Server Version: `v1.41.1`
- Mobile App Version: `v1.41.0 build.64`

**Additional context**
I exported the pgdata volume as a .tar file as I had to uninstall docker so I made a backup.
After reinstalling I extracted it in another location which I mounted as a volume to where pgdata was mounted.

**Comment by alextran1502** [comment]
Can you help show the exif data of the correct photo on Jan 13?

**Comment by alextran1502** [comment]
This might be the timezone issue (we are aware of it) so since it is 8pm something, due to the unknown timezone when converting to utc, it pushes the image to the next day

**Comment by sagniKdas53** [comment]
Yeah sure, this is the EXIF data of the 4th image in the second Screenshot.
![Screenshot_20230113_225118](https://user-images.githubusercontent.com/40667155/212381135-ae0738a8-cc09-4fd5-89c7-f199dc7460a2.jpg)
