### ISSUE TITLE
Timeline buckets show unordered days (1-3-2 instead of 1-2-3)

### ISSUE THREAD

**Issue by C-Otto** [immich-app/immich#13258]
### The bug

See https://github.com/immich-app/immich/discussions/12650#discussioncomment-10871022 and related comments (https://github.com/immich-app/immich/discussions/12650#discussioncomment-10860542). As seen on the screenshot, the days in the timeline are:

1) Sep 30
2) Sep 28
3) Sep 29

![374271370-2378fa6f-bfb3-4d9c-b643-ed19989e1b36](https://github.com/user-attachments/assets/a7c17c1e-42f0-4686-b688-3d2d22b525f0)

### Version of Immich Server

v1.117.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

**Comment by C-Otto** [comment]
@igor47 Please provide further about the bug details here, if you have them.

**Comment by jrasm91** [comment]
Fixed in #13262
