### ISSUE TITLE
[Feature]: Recreate Album in Immich When Syncing From Mobile

### ISSUE THREAD

**Issue by Zindswini** [immich-app/immich#1331]
### Feature Detail:
As it is, I have spent quite a bit of time sorting my photos into apple photos albums. While Immich conveniently provides the option to sync specific albums, I do not see an option to keep those albums when the photos are brought into Immich.

Ideally there would be an option, perhaps a checkbox under the album name in the upload/sync menu, which would bring not only the images themselves but also create a new album in Immich for them to be attached to.

Loving Immich, I'm looking forward to seeing its continued development. Thanks!

### Platform

Mobile App

**Comment by alextran1502** [comment]
Thank you. I will close this issue as it is duplicated with #537. Please follow that issue for more information. Thank you
