### ISSUE TITLE
[Feature]: Regonize people from pictures using machine learning

### ISSUE THREAD

**Issue by samip5** [immich-app/immich#1333]
### Feature detail

I would love to see a way for me to say who someone in a picture is, and it would find that person from all of the pictures and organize them under that person's name/picture.

Similar to how photoprism does it.

### Platform

Server

**Comment by bo0tzz** [comment]
Duplicate of #294

**Comment by samip5** [comment]
Ah sorry, tried to search for it but did not find that.
