### ISSUE TITLE
Map Doesn't Load in Microsoft Edge

### ISSUE THREAD

**Issue by SoulGit** [immich-app/immich#13358]
### The bug

Map link on web results in a blank page on Microsoft Edge (running latest 129.0.2792.89).  Error in console follows.  Issue exists on local install as well as Demo Immich Instance.

Uncaught (in promise) Error: {"requestedAttributes":{"alpha":true,"stencil":true,"depth":true,"failIfMajorPerformanceCaveat":false,"preserveDrawingBuffer":false,"antialias":false},"statusMessage":"Could not create a WebGL context, VENDOR = 0xffff, DEVICE = 0xffff, GL_VENDOR = Google Inc. (Google), GL_RENDERER = ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (LLVM 10.0.0) (0x0000C0DE)), SwiftShader driver-5.0.0), GL_VERSION = 5.0.0, Sandboxed = yes, Optimus = no, AMD switchable = no, Reset notification strategy = 0x8252, ErrorMessage = BindToCurrentSequence failed: .","type":"webglcontextcreationerror","message":"Failed to initialize WebGL"}
    at v.Map._setupPainter (map.CwsACdXL.js:580:202737)
    at new v.Map (map.CwsACdXL.js:580:185658)
    at qt (map.CwsACdXL.js:580:243406)
    at Object.m (map.CwsACdXL.js:580:241747)
    at _t (index.DoTFCMjV.js:4:3024)
    at Object.m (map.CwsACdXL.js:583:526)
    at c (await_block.BDR3ixd6.js:1:439)
    at await_block.BDR3ixd6.js:1:550

### The OS that Immich Server is running on

Demo Instance

### Version of Immich Server

v1.117.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Issue exists in https://demo.immich.app/map
```

### Your .env content

```Shell
Issue exists in https://demo.immich.app/map
```

### Reproduction steps

1. Navigate to Immich instance with Microsoft Edge
2. Click on map
3. Error
...

**Comment by bo0tzz** [comment]
Are you using any anti-fingerprinting settings or such?

**Comment by SoulGit** [comment]
I am not, at least to my knowledge, just a standard install on OS X.  Works on the same machine in Safari, so it doesn't seem to be firewall or network related.

**Comment by alextran1502** [comment]
Seem like an issue with Brave's browser that they are not supporting WebGL at the moment https://community.brave.com/t/webgl-will-not-work-in-brave-browser-but-it-will-work-in-chrome/539127

**Comment by SoulGit** [comment]
Is Edge based on the Brave code base?  I thought it was Chromium?

**Comment by alextran1502** [comment]
Edge and Brave based on Chromium
