### ISSUE TITLE
Immich web cannot use browser language for international display. Immich web 不能使用浏览器正在使用的中文展示

### ISSUE THREAD

**Issue by fa1seut0pia** [immich-app/immich#13401]
### The bug

我在浏览器控制台输入 `navigator.languages`,打印出 `['zh-CN']`
My browser `navigator.languages` console log

![image](https://github.com/user-attachments/assets/1577ee56-4767-4b0f-9018-94eaf6a8d704)

`zh-CN` 与 [web/src/lib/constants.ts#L323](https://github.com/immich-app/immich/blob/main/web/src/lib/constants.ts#L323) 中的 `code: 'zh-Hans'` 不匹配
This does not match the `zh-CN` in [web/src/lib/constants.ts#L323](https://github.com/immich-app/immich/blob/main/web/src/lib/constants.ts#L323) `zh-Hans`

应该要把 [web/src/lib/constants.ts#L323](https://github.com/immich-app/immich/blob/main/web/src/lib/constants.ts#L323) 中的`zh-Hans`修改为`zh-CN`?
Should I change the 'zh-Hans' in [web/src/lib/constants.ts#L323](https://github.com/immich-app/immich/blob/main/web/src/lib/constants.ts#L323) to `zh-CN`?

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.117.0

### Version of Immich Mobile App

v1.117.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml

与Github仓库一致
Consistent with GitHub repository
```

### Your .env content

```Shell
https://github.com/immich-app/immich/releases/latest/download/example.env

与Github仓库一致
Consistent with GitHub repository
```

### Reproduction steps

1. Chrome 浏览器中(其他浏览器类似)，打开 chrome://settings/languages 添加并置顶中文
In Chrome browser (similar to other browsers), open chrome://settings/languages to add and set the top Chinese
Like this:

![image](https://github.com/user-attachments/assets/f342c04d-fd0b-4088-9da8-b38c656c3856)

3. 打开 Open [https://demo.immich.app](https://demo.immich.app/auth/login)

![image](https://github.com/user-attachments/assets/a6c4f837-ff5f-4373-a7aa-eec3035739fe)

### Relevant log output

```shell
-
```

### Additional information

注意，当我在浏览器控制台输入 `localStorage.setItem("lang","zh-Hans");` 后刷新网页，它可以正常显示中文
Note that when I type `localStorage.setItem("lang","zh-Hans");` in the browser console and refresh the web page, it can display Chinese normally

![image](https://github.com/user-attachments/assets/06212f9e-70ae-4b83-92a7-dffa6487247f)

**Comment by fa1seut0pia** [comment]
我想修改它，只是不知道作者当初为什么要用 `zh-Hans`，不知道把 `zh-Hans 换成 `zh-CN` 之后有没有其他影响。
I want to modify it, but I just don't know why the author used 'zh-Hans' in the first place, and I don't know if there will be other side effects after replacing 'zh-Hans with' zh-CN '.

**Comment by m0eak** [comment]
居然有中文了，我都不知道

**Comment by fa1seut0pia** [comment]
> 居然有中文了，我都不知道
有bug，不然安装好打开就会自动识别中文

**Comment by fa1seut0pia** [comment]
@michelheusschen 

我现在想把 `zh-Hans` 换成 `zh-CN`，对你有影响吗？
diff https://github.com/immich-app/immich/commit/79705dc58d3a6210f8d1ceb09a7f273f0c51b081#diff-962a6f42c6e15c7537933f7dc7b15b198937c33f7d10e285f76e9dcdf7a30666R281
你的意思是，你的浏览器 `navigator.languages`,打印内容包含 `['zh-Hans']`?

Now I want to change `zh-Hans` to `zh-CN`. Does it affect you?
diff https://github.com/immich-app/immich/commit/79705dc58d3a6210f8d1ceb09a7f273f0c51b081#diff-962a6f42c6e15c7537933f7dc7b15b198937c33f7d10e285f76e9dcdf7a30666R281
Do you mean that your browser's `navigator.languages` prints contain `['zh-Hans']`?

**Comment by danieldietzler** [comment]
We understood that you consider this a bug. However, there is no need to ping people here or DM them on Discord, *especially* if you know they're on vacation. You don't have any right to expect people immediately paying all their attention to you. I think this issue has all the information it needs. If you continue pinging people here or DM'ing them on Discord it will have consequences.

**Comment by fa1seut0pia** [comment]
> We understood that you consider this a bug. However, there is no need to ping people here or DM them on Discord, _especially_ if you know they're on vacation. You don't have any right to expect people immediately paying all their attention to you. I think this issue has all the information it needs. If you continue pinging people here or DM'ing them on Discord it will have consequences.

Sorry to bother you, thank you very much for developing Immich. Regarding Discord, I am not familiar with it. I am learning how to use Discord, and now I am trying to find a way to fix this "bug(maybe)"

**Comment by pyccl** [comment]
原来可以自动变成中文的的啊，我一直以为只能手动，每次换浏览器、换电脑登录就改一下语言😄😄😄😄

**Comment by danieldietzler** [comment]
Please stick to english here on Github so that it's easier for everyone to follow (and for us to figure out if it's bad)

**Comment by fa1seut0pia** [comment]
是吧，这个小改动还是可以帮到很多人的，使用中文的人十多亿人呢，意义很大 😁
Yes, this small change can still help many people. More than a billion people use Chinese, which is of great significance
