### ISSUE TITLE
[Feature]: Android app unable to log in when app updates automatically and server version is mismatched

### ISSUE THREAD

**Issue by gh3597** [immich-app/immich#1345]
### Feature detail

This is a bit of a feature request that stems from a possible bug making this feature become more important.

Seems there is no official/simple method for updating Immich that I can find. Only way I have found is to go into the editor in Portainer and then click ````Update the stack```` and make sure ````Re-pull image and redeploy```` is selected. This doesn't feel like the correct way of doing it though?

The reason this has become an issue relating to a bug is it seems that while the Android app is automatically updated it then will not connect due to a mismatched server version. It has done this the last 2 times it has updated, and only when I've updated the server has the app been able to log in again. 

### Platform

Server

**Comment by bo0tzz** [comment]
I'm pretty sure the server update method you describe is correct. Why do you think it isn't?

Compatability between different versions of server and app is not planned for now, while Immich is still under heavy development.

**Comment by gh3597** [comment]
> I'm pretty sure the server update method you describe is correct. Why do you think it isn't?

Because I don't see it mentioned in any Immich documentation anywhere, and it just seems like a workaround. This is more a Portainer issue I think but would have thought there would be an "update stack" button somewhere higher up than sort of buried in the editor and then behind another button press.

If that's the official way of doing it then it might be useful adding this to the documentation.
 
> Compatability between different versions of server and app is not planned for now, while Immich is still under heavy development.

I did think this may be the case, hence why I'd not raised that as its own bug.
