### ISSUE TITLE
iOS app Oauth not working with latest update

### ISSUE THREAD

**Issue by chaosclarity84** [immich-app/immich#13467]
### The bug

I updated to latest Immich today, as well as the iOS app. I have setup the Google OAuth configuration, which is working fine for desktop browser login, and was previously working great on the iOS app. But after today's update, I can no longer login using the iOS app with Google OAuth. Just so happens my wife wanted to sign up and use it today, that's how I discovered it was broken.

The error I receive after tapping the OAuth login within the app is:
custom scheme uris are not allowed for 'web' client type

### The OS that Immich Server is running on

Unraid Docker

### Version of Immich Server

latest

### Version of Immich Mobile App

latest

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not sure how to pull that in Unraid, for me it's just a gui with text fields, but nothing is configured out of the ordinary I would say.
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Log out of Immich ios app
2. Attempt to log back in using Google OAuth

**Comment by alextran1502** [comment]
If you revert to 1.117.0 on the server, does it work?

**Comment by bo0tzz** [comment]
What are the redirect URIs you've configured on your oauth server?

**Comment by chaosclarity84** [comment]
> What are the redirect URIs you've configured on your oauth server?

![image](https://github.com/user-attachments/assets/00e68b46-875f-4c85-91f2-0dca383b240a)

**Comment by nicokaiser** [comment]
Does adding `app.immich:///oauth-callback` as additional Redirect URI help? I think [v0.113.0](https://github.com/immich-app/immich/releases/tag/v1.113.0) added this.

**Comment by chaosclarity84** [comment]
> Does adding `app.immich:///oauth-callback` as additional Redirect URI help? I think [v0.113.0](https://github.com/immich-app/immich/releases/tag/v1.113.0) added this.

Unfortunately google doesn't allow you to add that, it shows as invalid.

**Comment by bo0tzz** [comment]
Can you share your complete oauth config on both Immich and Google? Of course, redact client secrets and such ;)

**Comment by bo0tzz** [comment]
@Harguer you have a completely unrelated issue, and it's caused by not reading the release notes.

**Comment by chaosclarity84** [comment]
> Can you share your complete oauth config on both Immich and Google? Of course, redact client secrets and such ;)

Sure, here you go:
![image](https://github.com/user-attachments/assets/0e6821da-6e4b-40a4-b831-1e18b289af5a)
![image](https://github.com/user-attachments/assets/422e7703-3b76-412a-ad4b-c0e29f773529)

**Comment by chaosclarity84** [comment]
Sorry if this is a silly question, but when will we see the fix? Is it in
an iOS app update, or is it in Immich itself? Thanks!

**Comment by alextran1502** [comment]
@chaosclarity84 update the server to 1.118.1 will fix it

**Comment by sgbangale** [comment]
![image](https://github.com/user-attachments/assets/b01acc24-a3e2-4e97-aa4b-cd533804a268)
I have configured google oauth and getting error when I use iOS app v1.118.0 and server version is as per below screenshot 
![image](https://github.com/user-attachments/assets/d3824272-afd4-4cea-a5a7-bc7b64285cb3)

I can use google oauth from web browser, also changed redirect uri 'https://photos.xxx.xxx/app/oauth/mobile-redirect'

**Comment by bo0tzz** [comment]
That should be /api/ not /app/
