### ISSUE TITLE
Mobile UI showing many English texts instead of translation

### ISSUE THREAD

**Issue by Sherlock1979** [immich-app/immich#13477]
### The bug

Looking at the new UI changes in 1.118 in a different language I noticed that half of the UI is now in English. My app language is set to Hungarian which is 100% translated. (I am one of the translators and reviewed and improved the whole translation to make it consistent and fix up glitches and typos.)

Anyways, couple of examples in the attached screenshots.

![Screenshot_20241016-070107](https://github.com/user-attachments/assets/7dd5eece-aad7-4869-9bb3-12040565b5ff)
![Screenshot_20241016-070036](https://github.com/user-attachments/assets/8c42f4a4-6128-4f95-b6b1-6fd82c89c336)
![Screenshot_20241016-065938](https://github.com/user-attachments/assets/55a38b5d-23ba-4a77-8035-c2d27b9f6c16)
![Screenshot_20241016-065900](https://github.com/user-attachments/assets/5eea91ea-6503-4744-961a-0c0d6b7e1b6f)
![Screenshot_20241016-065805](https://github.com/user-attachments/assets/e79a3a76-35bf-4f57-b874-4109e618f8db)
![Screenshot_20241016-065731](https://github.com/user-attachments/assets/af3d98b4-d02b-4a5c-acca-e162b545d920)
![Screenshot_20241016-065528](https://github.com/user-attachments/assets/b966e77f-7f05-44d9-8098-70a4df371796)

Thanks for looking into it.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

1.118.0

### Version of Immich Mobile App

1.118.0 build.163

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Irrelevant
```

### Your .env content

```Shell
Irrelevant
```

### Reproduction steps

1. Open Immich android app.
2. Change language (e.g., to Hungarian)
3. Optional: force stop and start the app again
4. Observe the lack of translated texts.

**Comment by bo0tzz** [comment]
#12582 added new translation keys when updating those pages, which I think is what you're seeing here. Are you sure those were translated before we started this release?

**Comment by alextran1502** [comment]
The keys were changed so they need to be updated from Localizely as well

**Comment by Sherlock1979** [comment]
> #12582 added new translation keys when updating those pages, which I think is what you're seeing here. Are you sure those were translated before we started this release?

Yes, the Hungarian translation was always very up-to-date and I spent this weekend reviewing the whole translation. It was fully translated by Sunday, including any new translation keys. 

Also note that many of those missing texts are not new translation keys. 

Thanks.

**Comment by bo0tzz** [comment]
The mobile app is still on localizely :sweat_smile:

**Comment by Sherlock1979** [comment]
> The mobile app is still on localizely 😅

Oh no, that's terrible. I mean I can definitely look into it but it's a lot of duplicated effort to keep both translations up-to-date as well as consistent. 

Do you have any plans to move all translations over to a single repository?

Also note that the dates/times are in English as well. I think that's not a translation issue but the app would need to apply the relevant locale to date formatting functions.

Cheers

**Comment by Sherlock1979** [comment]
Done, I have reviewed and updated the Hungarian localizely translation, and added all missing keys. @alextran1502, can you please include the changes in the next release? Thanks.
