### ISSUE TITLE
[BUG] iOS app log to CSV not working

### ISSUE THREAD

**Issue by marleyjaffe** [immich-app/immich#1351]
**Describe the bug**
After viewing the logs in the iOS app, I attempted to export/share them to include in another bug report. I was unsuccessful in airdropping, slacking, or saving the csv to my local storage, and simply copy. Airdropping results in a `Failed` status, `Save to Files` does not do anything, and `Copy` does not seem to load anything to the clipboard. The share screen does show the file name, that it is a csv format, and that it is 18KB.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Click on top left profile icon
2. Click on Logs
3. Click Share icon top right
4. Attempt to share using any of the iOS share options

**Expected behavior**
Ability to export/"share" the logs to another source for easy attachment to GitHub issues etc. 

**Screenshots**
Showing filename, file type and file size
![IMG_0518F6FDDDE1-1](https://user-images.githubusercontent.com/3719336/213071454-764cc5b1-3a65-4aea-8cbc-f892edb6f4dd.jpeg)

**System**
- Phone OS [iOS]: `iOS 16.1.1`
- Server Version: `1.41.1`
- Mobile App Version: `v1.41.0 build.78`

**Additional context**
Docker configs don't seem relevant and are uploaded to another #[submitted bug](https://github.com/immich-app/immich/issues/1349). I can copy them here if helpful.

**Comment by sypion** [comment]
For additional context:

Using the share button to pull up the system’s share sheet, on the header, the `.csv` file has a few bytes of data, but as soon as I try to save it elsewhere, the file exhibits 0 bytes of data. Attached is a screen recording that shows this.

https://user-images.githubusercontent.com/8906653/218836223-ddc63b2c-eb80-43d8-99c7-39a8153ecf61.MOV
