### ISSUE TITLE
[Feature]: Import Library & Keep Library Files Separate

### ISSUE THREAD

**Issue by threehappypenguins** [immich-app/immich#1357]
### Feature detail

So, I think I was expecting something totally different when I had installed Immich. I have Immich installed on my home NAS (Odroid HC2). I thought that it would be able to scan my library, like Plex and Emby and other media organizers do, and display them. But I can't find any way to scan my library or import it or anything. I found one discussion where someone mentioned that import can be done from CLI, so I installed immich cli via npm. But I can't find the command to do so, and I also don't know my "key" and kept getting "Error: Cannot find module 'fs/promises'" so I gave that up. Then I tried to upload files that already existed within the upload location, and nothing happened. So then I uploaded a picture right from my laptop, and it worked. I went into my upload location, and see some randomly generated folder (_3587e07e-9515-4d55-90b6-aae23057a7b8_), and then within that, a _2023_ folder, a folder called _original_, and a folder called _thumb_.

What I am hoping for, is to have all the library files in a separate location from the media folder of my choosing, as well as the ability to scan for already existent media.

I don't think I will be able to use Immich unless this is done, as my OCD would go absolutely crazy having all these extra webp files and folders and whatnot all mixed in my very carefully organized library!

I do really like Immich in that it seems like it has potential to be a perfect replacement for Google Photos, and it is **very** fast!

I hope all that made sense. :)

### Platform

Server

**Comment by alextran1502** [comment]
Please see #1006 for more information 

And my answer for the question why we have the approach we have today

https://www.reddit.com/r/selfhosted/comments/100g899/why_does_immich_create_a_new_file_structure/j2hr4w9/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3

I hope this helps!
