### ISSUE TITLE
[Feature]: ETA for jobs

### ISSUE THREAD

**Issue by jacob-seiler** [immich-app/immich#1358]
### Feature detail

ETA column for jobs tab would be really nice to have. Included a mock-up.

![image](https://user-images.githubusercontent.com/42191997/213365096-17c12e26-73d0-420d-8f8c-7784f37b082f.png)

### Platform

Web

**Comment by alextran1502** [comment]
it is heavily depends on the processor speed and we don't have a good way to properly telling how long the queue would take to run :)
