### ISSUE TITLE
[Mobile][Android][OIDC] Login not possible

### ISSUE THREAD

**Issue by xundeenergie** [immich-app/immich#13590]
### The bug

I've configured keycloak to authenticate to immich.
It works in Browser but not with android app.

I get redirected to jeycloak, where i authenticate normally. (A webview overlay to the app on grapheneos)
Redirecting back to the app the immich website opens in the overlay webview, where i authenticated on keycloak. I'm authenticated in it.

Closing this browser i get an error in immich app.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.118.2

### Version of Immich Mobile App

v1.118.2

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Standard file, downloaded from install-advisory
```

### Your .env content

```Shell
Later on my computer
```

### Reproduction steps

1. Press Login with oidc
2. Authenticae on keycloak
3. Consent
4. 
![IMG_20241018_211143](https://github.com/user-attachments/assets/13925c55-9fc5-4e23-a885-85e4e95fa30f)

5. Back to app (still in authentication browser window)
![IMG_20241018_211206](https://github.com/user-attachments/assets/83f1486c-6874-4181-a54e-0aa533d845bc)
6. Clicking on the X left above to close the browser
7. Error
![IMG_20241018_211228](https://github.com/user-attachments/assets/25bec2cc-4942-49ac-b1f8-a6dab0112e0e)

### Relevant log output

```shell
Starting OAuth flow with redirect URI: app.immich:///oauth-callback
```

Message
```
Error logging in with OAuth: PlatformException(CANCELED, User canceled login, null, null)
```
Details
```
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>
#2      FlutterWebAuth.authenticate (package:flutter_web_auth/flutter_web_auth.dart:41)
<asynchronous suspension>
#3      OAuthService.oAuthLogin (package:immich_mobile/services/oauth.service.dart:35)
<asynchronous suspension>
#4      LoginForm.build.oAuthLogin (package:immich_mobile/widgets/forms/login/login_form.dart:255)
<asynchronous suspension>
```

From LoginForm
```


### Additional information

I don't know, if immich app works with keycloak....

It's a fresh installation

**Comment by bo0tzz** [comment]
#12246
