### ISSUE TITLE
Upload against settings

### ISSUE THREAD

**Issue by xundeenergie** [immich-app/immich#13667]
### The bug

I had some problems with not uploading images.
Seemed a combination of dns and a remote reverse-proxy.

For testing purpose i logged out  from app and in with another account.

Now i'm back with the original account.

My app should upload only, when the phone is plugged in to power

![IMG_20241022_073419](https://github.com/user-attachments/assets/0a65ef7a-8c11-4a74-8881-0e0615bde228)

But it backups all the time...
And more than i have images on my phone

![IMG_20241022_073452](https://github.com/user-attachments/assets/b18a4978-b2aa-4194-9f1e-2de9e1d5cfa9)

On the first run, it could upload only the haf of the fozrthousandsomething images... now it's on more the 5000 backed up images (and even movies).

### The OS that Immich Server is running on

Debian bookworm

### Version of Immich Server

v2.118.2

### Version of Immich Mobile App

v1.118.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Can not reach from my mobile
```

### Your .env content

```Shell
Can not reach from my mobile
```

### Reproduction steps

1. Login an start upload/backup your local images
2. Logout while backup is in progress
3. Login with another account
4. Logout
5. Login with the first account again.
...

### Relevant log output

```shell
No errors
```

**Comment by xundeenergie** [comment]
Still uploading.
Im on my way now, without wifi... and i activated now "wifi only upload".

Still uploading

![IMG_20241022_081608](https://github.com/user-attachments/assets/d79760ed-ddea-45a5-863c-204d279d070a)

**Comment by bo0tzz** [comment]
The charging setting only applies to the background backup. You also have the foreground backup enabled, which is what you're seeing on the backup progress screen in the app.
