### ISSUE TITLE
Mobile app does not retain selection after assets added to album

### ISSUE THREAD

**Issue by Sherlock1979** [immich-app/immich#13746]
### The bug

Using the mobile app (on Android) I select a few assets and add them to an album. The assets are successfully added to the album, however, the assets become un-selected. When I do the same on the web, the assets are still selected after they are added to the album.

Use case: I always need to add the assets to 3-5 different albums at the same time. Re-applying the selection over and over is very painful.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.118.2

### Version of Immich Mobile App

v1.118.0 build.163

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

1. Select some assets in the mobile app
2. Add them to an album
3. Observe how the assets are no longer selected (optionally observe how they remain selected on the web)

**Comment by bo0tzz** [comment]
This is an existing feature request: #2686
