### ISSUE TITLE
[APP]Unable to set server address！

### ISSUE THREAD

**Issue by qcks** [immich-app/immich#13761]
### The bug

Click “Next” to report errors directly without an eye-visible delay
Just my iphone！Only my iphone, I borrowed a few iphones all normal only my iphone, can't even get into the configure service address page!
Look for problems in your app code!!!
![IMG_0165](https://github.com/user-attachments/assets/e2ddb540-6810-4795-9994-b9471e9be6b9)
![IMG_0166](https://github.com/user-attachments/assets/02ead923-b53d-4608-8a15-ccbf4ea335d8)

### The OS that Immich Server is running on

having nothing do (with sth else)

### Version of Immich Server

having nothing do (with sth else)

### Version of Immich Mobile App

v1.118.0  iphone15Pro 

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
having nothing do (with sth else)
```

### Your .env content

```Shell
having nothing do (with sth else)
```

### Reproduction steps

having nothing do (with sth else)

### Relevant log output

```shell
having nothing do (with sth else)
```

### Additional information

ios:17.6.1(having nothing do (with sth else));

If you can't solve it, ask me again.

**Comment by bo0tzz** [comment]
You've been asked a few times now to stop creating issues, and told that this is not an immich bug. If you can provide clear information showing that it is then we can create an issue to track it, but for now please keep it to your existing discussion threads. 

If you continue creating new issues for the same thing we'll need to block you from the project for spamming, consider this a warning.

**Comment by alextran1502** [comment]
Reinstall the app, when it asks for access to local network, allow it.
