### ISSUE TITLE
External libraries size doesn't count toward user

### ISSUE THREAD

**Issue by fliespl** [immich-app/immich#13767]
### The bug

External libraries size doesn't count toward user.

As in title - I am adding icloud sync as external library and size is zero for specific user.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.118.2

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

1. Setup external library
2. Check per user usage

**Comment by danieldietzler** [comment]
That is intentional. There's no way (from immich) to prevent someone from putting more images into a local folder.
