### ISSUE TITLE
UI issue in iPad mini 

### ISSUE THREAD

**Issue by drmcachr** [immich-app/immich#13804]
### The bug

I use 6th iPad mini

1. Memory too small for tablets 
2. Blank between photos in album view and timeline view

![IMG_0130](https://github.com/user-attachments/assets/229f424f-2f22-4ee6-8d04-fdb3397bcd98)
![IMG_0129](https://github.com/user-attachments/assets/bfdd1d83-0e25-43fa-91fb-770b92916aa0)
![IMG_0128](https://github.com/user-attachments/assets/f4c48665-a1b2-47e5-bf1b-c0702cf6367d)

### The OS that Immich Server is running on

Asustor 4.3

### Version of Immich Server

119

### Version of Immich Mobile App

119

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not related
```

### Your .env content

```Shell
Not related
```

### Reproduction steps

1.
2.
3.
...

**Comment by alextran1502** [comment]
How do they look in vertical view?

**Comment by alextran1502** [comment]
Ah I can see it now. If you go to App Settings > Photo Grid > Increase the number of assets per row to (4) it will temporarily fix it
