### ISSUE TITLE
Strip external library path

### ISSUE THREAD

**Issue by mfbehrens** [immich-app/immich#13819]
### The bug

When entering a path with a trailing or leading whitespace it should just be stripped / trimmed away, since it is obvious and very hard to see

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.119.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

1. Open Administrations Settings
2. Goto External libraries
3. Create a library
4. Add a valid library and add a whitespace at the end
5. "Path invalid"

**Comment by bo0tzz** [comment]
This seems risky - people use the weirdest folder names, and I bet this change would find someone who deliberately has trailing whitespace in a path :sweat:
