### ISSUE TITLE
Feature: similar photo deletion suggestions

### ISSUE THREAD

**Issue by klejejs** [immich-app/immich#1387]
### Feature detail

When I take pictures, I often capture at least 2 or 3 of the same subject just to be sure that I get the perfect one. Unfortunately it takes up a lot of space and is cumbersome to go through all of them afterwards and delete them the redundant ones manually. It would be nice if there was a feature that detected similar photos and suggested deleting them.

### Platform

Web

**Comment by bo0tzz** [comment]
Duplicate of #644

**Comment by klejejs** [comment]
@bo0tzz Hello! I do not think this is a duplicate of the ticket you referenced as I am thinking more of a feature where deduplication works on similarly looking photos, not the same photo. Sorry if my description was incorrect.

**Comment by bo0tzz** [comment]
The current hash-based duplication mechanism works on files that are identical. The issue I linked covers that, but is still open because it also covers other deduplication mechanisms, including visual similarity.
