### ISSUE TITLE
Android app can not logout after the server IP is changed.

### ISSUE THREAD

**Issue by zl6977** [immich-app/immich#13886]
### The bug

Dear maintainers,

I think I found a bug.

### The OS that Immich Server is running on

windows

### Version of Immich Server

1.119.1

### Version of Immich Mobile App

1.119.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
The default one.
```

### Your .env content

```Shell
Not important.
```

### Reproduction steps

1. Run the server on a host computer using IP-1, suppose it is 192.168.1.100. And set up the Android app with this IP. Everything can work fine.
2. Change the host's IP to 192.168.1.101 (call it IP-2), and restart immich server in docker. This is quite common if the server's IP is assigned by DHCP service. 
3. Click "Sign out" on the Android app. I expect it should go to the "endpoint input UI", but it does not. After many times "sign out" and clear APP cache, I finally see the "endpoint input UI", but I do not know how I did it.

### Additional information

I guess the "Sign out" process has to interact with the server, but the server is not reachable if the host IP is changed. 
I think this process can be optimized so that the "Sign out" can still work even if the server is not reachable. Otherwise, is there a good way to change the endpoint URL?

Thank you in advance.
```[tasklist]
### Tasks
- [ ] https://github.com/immich-app/immich/pull/14104
```

**Comment by zl6977** [comment]
> I had the same issue if the IP changed / was unreachable. Sign out did nothing at first, no feedback - but after 1-2 minutes the app logged me out. Was some time ago.

Good to know I am not alone :)

**Comment by Eambo** [comment]
Just wanted to +1, I've recently moved my server and I couldn't log out of the app to log in to the new server. On Android I had to clear all data (essentially wipe the app) to get it to work.

**Comment by johnstef99** [comment]
I just open a PR to fix this issue, seems that the logout request didn't have a timeout.

**Comment by zl6977** [comment]
> I just open a PR to fix this issue, seems that the logout request didn't have a timeout.

Thank you for trying to fix it. Looking forward to the new version.
Should I close this issue now or when the new version is released?
