### ISSUE TITLE
[BUG] Albums section opens slowly on PC via browser

### ISSUE THREAD

**Issue by pig-cop** [immich-app/immich#1389]
When using the web-ui from a browser on PC (both Firefox or Chronium) loading the Albums section is very slow.
I get the purple progress bar on top upon entering the Albums and no matter what it loads for a couple of seconds every time.

Installed via docker on my NAS at home but checked on the mobile app too, no hangs there.
On the mobile app it's fast and butter smooth.

EDIT:
just noticed I can't reproduce it know and it loads as expected, I will investigate further when it happens and why,

**Comment by alextran1502** [comment]
The first time it loads it could be slower because of server side rendering. Then it will always load fast
