### ISSUE TITLE
Shared video still can be downloaded even if not marked

### ISSUE THREAD

**Issue by Karmalakas** [immich-app/immich#13910]
### The bug

Shared video still can be downloaded even if marked to not allow downloads

### The OS that Immich Server is running on

TrueNAS Scale

### Version of Immich Server

1.119.1

### Platform with the issue

- [X] Web

### Reproduction steps

1. Open video
2. Click to share it
3. Unchect "Show Metadata" ("Allow download" gets un-checked automatically)
4. Create link
5. Copy link
6. Open in incognito
7. Play video
8. Click 3 dots on the bottom right of the player
9. Click "Download"
10. Full resolution video gets downloaded

**Comment by bo0tzz** [comment]
This is working as expected. The video file that's served is the transcoded video (unless you've disabled transcoding). The user needs to be served some file for them to look at, and they necessarily are able to save that as well, just like they could right click and save a photo on which you've disabled downloading.

**Comment by bo0tzz** [comment]
Hiding the controls would prevent people from seeking etc, that doesn't seem like a viable option to me. In general, trying to prevent people from downloading this video is just theater. If you don't trust someone to that level, don't share the video with them at all.

**Comment by Karmalakas** [comment]
```
<video controls controlsList="nodownload" ...
```
This does NOT hide the controls. It only hides the download option from the 3-dot menu

**Comment by bo0tzz** [comment]
Even with nodownload set, right-clicking the image still gives you a "save video as" option, so it's pretty pointless.

**Comment by Karmalakas** [comment]
That's why there's
```
oncontextmenu="return false;">
```
