### ISSUE TITLE
[BUG] Selection toolbar and photo grid out of sync

### ISSUE THREAD

**Issue by EnochPrime** [immich-app/immich#1396]
**Describe the bug**
When navigating back to photos page where photos were once selected the page will display the toolbar, but the photos are not indicated as selected. The buttons on the control will operate on the photos that were selected.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [X] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Go to Photos page
2. Select one or multiple photos
3. Navigate to another pages, such as Sharing
4. Return to Photos page

**Expected behavior**
Either the selection should be cleared when navigating away from the page or the photos should be reselected in the grid view upon return.

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/1175190/214113021-52d3a6dc-6a86-4e9e-9f89-e14ce43633d1.png)

After
![image](https://user-images.githubusercontent.com/1175190/214113179-a7a28830-a273-48d7-b590-652b7746dff7.png)

**System**
- Phone OS [iOS, Android]: `N/A`
- Server Version: `v1.42.0`
- Mobile App Version: `N/A`

**Additional context**

**Comment by michelheusschen** [comment]
Has been resolved in v1.56.0
