### ISSUE TITLE
Stacks created on web appear broken on mobile

### ISSUE THREAD

**Issue by Danilado** [immich-app/immich#13962]
### The bug

After creating a bunch of stacks of photos in the web app, they all appear as broken images on android client

### The OS that Immich Server is running on

Opensuse Tumbleweed

### Version of Immich Server

1.119.1

### Version of Immich Mobile App

1.119.0 build 164

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I don't think it's relevant
```

### Your .env content

```Shell
I don't think it's relevant
```

### Reproduction steps

1. Load pictures to the server through the android mobile app
2. Stack them trough web app
3. Reload mobile app

### Relevant log output

```shell
doesn't show much on "finest" setting
```

### Additional information

using Google Pixel 8 pro

**Comment by alextran1502** [comment]
can you try sign out and sign back in 🤔?

**Comment by Danilado** [comment]
That worked
guess you can close this
