### ISSUE TITLE
Backup without database root access

### ISSUE THREAD

**Issue by dotlambda** [immich-app/immich#13971]
### The bug

The backup can fail with
```
pg_dumpall: error: query failed: ERROR:  permission denied for table pg_authid
```
That can be fixed using `--no-role-passwords` but I suspect that the backup can still fail if there are other databases on the server that the immich user doesn't have access to.
Why isn't `pg_dump` used instead or at least used if `pg_dumpall` fails?

### The OS that Immich Server is running on

NixOS

### Version of Immich Server

1.120.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
DB_URL=postgresql:///immich?host=/run/postgresql
```
```
```

### Reproduction steps

Have a PostgreSQL user `immich` that only has access to the `immich` database.

**Comment by mmomjian** [comment]
The built-in database backup is not designed for use with an external database. We use `pg_dumpall` because not all of the schema information is properly captured when using `pg_dump`. I would recommend you disable the built-in dump and continue making your own backups.

**Comment by dotlambda** [comment]
> Why isn't `pg_dump` used instead or at least used if `pg_dumpall` fails?

The latter is not an option?

**Comment by bo0tzz** [comment]
> The latter is not an option?

Like mentioned, it would result in an incomplete backup. I prefer outright failure over that.

**Comment by zackpollard** [comment]
Yea, I don't think this is something we are currently looking to support. If you have a custom setup, you should probably be running custom backups. Maybe we improve in the future to support this, but not right now.
