### ISSUE TITLE
Backup does not respect the postgres port

### ISSUE THREAD

**Issue by martabal** [immich-app/immich#13980]
### The bug

As the title says.

https://github.com/immich-app/immich/blob/be2b76be8c9201d1ef3d2ea6b3cb52b8aaeb5251/server/src/services/backup.service.ts#L88

And if the service fails, an empty temp file is created `immich-db-backup-1730941200145.sql.gz.tmp`

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.120.0

### Version of Immich Mobile App

v1.120.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Use a different port the postgres db
2. Run the backup job
3. Should throw an error in the docker logs
...

### Relevant log output

```shell
pg_dumpall: error: connection to server at "postgres_immich", port 5432 failed: FATAL:  password authentication failed for user "immich"
```

(I have a different postgres server running on port 5432)

**Comment by zackpollard** [comment]
Resolved by #13970

**Comment by bo0tzz** [comment]
Only if using a DB_URL, but not with DB_PORT right @zackpollard ?

**Comment by martabal** [comment]
> Only if using a DB_URL, but not with DB_PORT right @zackpollard ?

Yeah, it does not fix that issue
