### ISSUE TITLE
Delete not working in cli upload

### ISSUE THREAD

**Issue by masterwishx** [immich-app/immich#13982]
### The bug

when using unraid User script for upload : 

docker exec -i immich immich login-key http://192.168.0.199:8180/api APIKEY
docker exec -i immich immich upload --recursive --delete /import

no delete files in import folder

### The OS that Immich Server is running on

Docker

### Version of Immich Server

lasted version

### Version of Immich Mobile App

lasted

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Using `https://github.com/orgs/imagegenius/packages/container/package/immich`
```

### Your .env content

```Shell
.....
```

### Reproduction steps

1. run script
2. no files was deleted
3.
...

### Relevant log output

```shell
Logging in to http://192.168.0.199:8180/api
Logged in as masterwishx@mymail
Wrote auth info to /root/.config/immich/auth.yml
Crawling for assets...
Found 0 new files and 610 duplicates
All assets were already uploaded, nothing to do.
Deleting assets that have been uploaded...
Script Finished Nov 07, 2024 12:42.43
```
```


### Additional information

This is from container console when : ls -lah

```
drwxrwxrwx 1 abc  users    3 Nov  7 14:23  .
drwxr-xr-x 1 root root   366 Nov  7 08:36  ..
-rw-rw-rw- 1 abc  users 3.9M Oct  8  2022  20221008_220151.jpg
-rw-rw-rw- 1 abc  users  88M Oct  9  2022  20221009_112419.mp4
-rw-rw-rw- 1 abc  users 3.5M Oct  9  2022  20221009_113434.jpg
-rw-rw-rw- 1 abc  users 4.1M Oct  9  2022  20221009_114003.jpg
-rw-rw-rw- 1 abc  users 3.7M Oct  9  2022  20221009_114008.jpg
-rw-rw-rw- 1 abc  users 3.8M Oct  9  2022  20221009_114011.jpg
-rw-rw-rw- 1 abc  users 3.5M Oct  9  2022  20221009_191043.jpg
-rw-rw-rw- 1 abc  users 3.7M Oct 12  2022  20221012_214810.jpg
-rw-rw-rw- 1 abc  users 3.7M Oct 12  2022  20221012_214811.jpg
-rw-rw-rw- 1 abc  users 2.9M Oct 12  2022  20221012_214822.jpg
-rw-rw-rw- 1 abc  users 3.8M Oct 14  2022  20221014_115534.jpg
-rw-rw-rw- 1 abc  users 3.4M Oct 19  2022  20221019_082019.jpg
-rw-rw-rw- 1 abc  users 3.4M Oct 19  2022  20221019_082023.jpg
-rw-rw-rw- 1 abc  users 3.5M Oct 19  2022  20221019_082036.jpg
-rw-rw-rw- 1 abc  users 3.5M Oct 19  2022  20221019_082043.jpg
-rw-rw-rw- 1 abc  users 350M Oct 24  2022  20221024_100309.mp4
-rw-rw-rw- 1 abc  users 4.0M Nov  2  2022  20221102_193111.jpg
-rw-rw-rw- 1 abc  users 4.2M Nov  2  2022  20221102_193116.jpg
-rw-rw-rw- 1 abc  users 3.2M Nov  7  2022  20221107_105234.jpg
-rw-rw-rw- 1 abc  users 4.5M Nov  7  2022  20221107_105242.jpg
-rw-rw-rw- 1 abc  users 6.1M Nov  7  2022  20221107_105255.jpg
-rw-rw-rw- 1 abc  users 126M Nov 17  2022  20221117_170523.mp4
-rw-rw-rw- 1 abc  users 197M Nov 21  2022  20221121_170001.mp4
-rw-rw-rw- 1 abc  users 3.4M Nov 22  2022  20221122_074636.jpg
-rw-rw-rw- 1 abc  users 1.8M Nov 24  2022  20221124_144429.jpg
..
..
etc
```

**Comment by masterwishx** [comment]
> You need to post your compose and env. You must have added something to mount the /import folder

Yes I have it, it was working befor not shure why now not working

**Comment by masterwishx** [comment]
> You need to post your compose and env. You must have added something to mount the /import folder

```
docker run
  -d
  --name='immich'
  --net='proxynet'
  --pids-limit 2048
  -e TZ="Asia/Jerusalem"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Server"
  -e HOST_CONTAINERNAME="immich"
  -e 'DB_HOSTNAME'='192.168.0.199'
  -e 'DB_USERNAME'='postgres'
  -e 'DB_PASSWORD'='postgres password'
  -e 'DB_DATABASE_NAME'='immich'
  -e 'REDIS_HOSTNAME'='192.168.0.199'
  -e 'DB_PORT'='5433'
  -e 'REDIS_PORT'='6379'
  -e 'REDIS_PASSWORD'='Password'
  -e 'MACHINE_LEARNING_GPU_ACCELERATION'='vaapi'
  -e 'MACHINE_LEARNING_WORKERS'='1'
  -e 'MACHINE_LEARNING_WORKER_TIMEOUT'='120'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png'
  -p '8180:8080/tcp'
  -v '/mnt/user/Pictures Immich/':'/photos':'rw'
  -v '/mnt/user/Import Pictures Immich/':'/import':'rw'
  -v '/mnt/user/Pictures/':'/libraries/masterwishx/pictures':'ro'
  -v '/mnt/system_cache_ssd/appdata/immich':'/config':'rw'
  --device='/dev/dri' 'ghcr.io/imagegenius/immich:latest'
```

**Comment by masterwishx** [comment]
> Probably a permissions issue and the user/group does not have permission to delete from your mount point.

by container env 99:100 + umask =022 , by container console abc:users . do you mean i need to change umask to 000 ?

**Comment by masterwishx** [comment]
it seems changing `umask = 000`  fixed the issue, will close for now

**Comment by Binocularbath** [comment]
Im having the same problem
