### ISSUE TITLE
Upload fails when `utime` is not available

### ISSUE THREAD

**Issue by denysvitali** [immich-app/immich#14005]
### The bug

It looks like Immich tries to set the `utime` of the uploaded files, but certain storage implementations such as [geesefs](https://github.com/yandex-cloud/geesefs) do not allow this.  
  
To properly fix the issue, I think it would be convenient to allow users to disable / mock `utime` when a specific environment variable is specified.

https://github.com/immich-app/immich/blob/75340985969b371d73279622343a84adf856a92b/server/src/repositories/storage.repository.ts#L62-L64

```
Error: EPERM: operation not permitted, utime 'upload/upload/e9209f4c-7ad4-437d-a
f25-1c059623c8e1/24/cd/24cd5cc9-a7db-4d4d-86d5-d7d4675f69df.jpeg'
    at async Object.utimes (node:internal/fs/promises:1128:10)
    at async AssetMediaService.create (/usr/src/app/dist/services/asset-media.se
rvice.js:273:9)
    at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-med
ia.service.js:96:27)
    at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/ass
et-media.controller.js:40:29)
```

### The OS that Immich Server is running on

Alpine

### Version of Immich Server

v1.120.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Use [geesefs](https://github.com/yandex-cloud/geesefs) (or any non-POSIX compliant FS) and mount an S3 bucket to the uploads directory
2. Try to upload a file

### Relevant log output

```shell
Error: EPERM: operation not permitted, utime 'upload/upload/e9209f4c-7ad4-437d-a
    at async Object.utimes (node:internal/fs/promises:1128:10)
    at async AssetMediaService.create (/usr/src/app/dist/services/asset-media.se
    at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-med
    at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/ass
```

**Comment by bo0tzz** [comment]
I'm not sure whether we want to support filesystems that aren't POSIX-compliant, that comes with all sorts of issues.

**Comment by denysvitali** [comment]
They can be feature-flagged. I've made a small patch on that method that checks an environment variable - and when that's set, it skips the call.

I'm fine with not having support out-of-the-box, but I think there should be an option somewhere, ideally an environment variable, that allows to skip at least `utime`

**Comment by etnoy** [comment]
We have discussed this internally and decided on not opening up support for non-posix filesystems.
