### ISSUE TITLE
[BUG] Info view of images has text "undefinedundefined" in geolocation

### ISSUE THREAD

**Issue by martyfuhry** [immich-app/immich#1407]
**Description of the bug**
In the detail view of various images near the geolocation data. I'm not sure what is supposed to belong there, but the text "undefinedundefined" certainly suggests a bug. I believe the town, city, state, or region text belongs there, but I'm not positive.

**To Reproduce**
1. Select an image with location metadata.
2. Select the Info button to see the map / associated metadata.
3. You can see text "undefinedundefined" occasionally where geolocation data belongs (e.g., town, city, state).

**Expected behavior**
I believe more geolocation data belongs here or else the text should be suppressed. 

**Screenshots**

**Web**
![image](https://user-images.githubusercontent.com/100457/214351306-29f0c235-902b-4c85-94a9-8527bf432ead.png)

**Mobile**
![image](https://user-images.githubusercontent.com/100457/214351757-7576f2bc-b921-4689-8356-1fd3f7872350.png)

**System**
- Phone OS [iOS, Android]: Either OS (Screenshot is from Android, but behavior is on both)
- Server Version: 1.42.0
- Mobile App Version: 1.42.0 build.65

**Additional information**
You can also see some "null" text in e.g., the camera metadata, which should be cleaned up as well.

**Comment by alextran1502** [comment]
Hello, do you have a test image that we can use for troubleshooting?

**Comment by martyfuhry** [comment]
My guess is that it's an issue with the reverse geocoding done on the server. It looks like the client is receiving the text string "undefinedundefined" from the server as the value of it's `exifInfo.state` member.

Below is an example of an image I imported from Google Photos into my own self-hosted Immich server. Loads of my images have this issue, though, and the lat/lng is appropriately set.

This was a super cool apartment, too.

![20160901_131655](https://user-images.githubusercontent.com/100457/214369303-561b54f1-c55d-449b-ac92-8c4f73e97da1.jpg)

**Comment by alextran1502** [comment]
HMm here is the result from my instance 

![image](https://user-images.githubusercontent.com/27055614/214384098-8a451e89-c643-45df-81b9-c8e1f6687674.png)

The mobile app also shows the same info. I guess this comes down to the `REVERSE_GEOCODING_PRECISION` setting in the `.env` file. I currently have mine set as `0`. What is yours?

**Comment by martyfuhry** [comment]
Well I apologize, I should have included my `.env` file... It was even there in the new issue template, but oh, *I knew better*. 

```
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=***
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/nfs/photos
JWT_SECRET=***
PUBLIC_LOGIN_PAGE_MESSAGE=***
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=2
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

Looks like I've got it set to `2`? I imagine that if I changed it to `0`, I would likely have the same result as you, which is a great workaround for the moment.

If that's the case, then the bug should be triaged to suppress `undefined` reverse geocoding strings when the precision is insufficiently set as they are being emitted to the client.

**Comment by alextran1502** [comment]
> f that's the case, then the bug should be triaged to suppress undefined reverse geocoding strings when the precision is insufficiently set as they are being emitted to the client.

Correct. Just trying to replicate the same settings yours so I can fix that issue :P

**Comment by owmsoton** [comment]
when I saw this problem, I remembered having seen this same undefined information.

I went to look in the `.env` for `REVERSE_GEOCODING_PRECISION=2` and in my case, it is commented and it even shows the geolocation, is that correct?

![image](https://user-images.githubusercontent.com/6722382/214988907-4c87e466-80c5-46b2-b904-39d7a8cee6a7.png)

**Comment by jrasm91** [comment]
I tested with this photo, specifically with REVERSE_GEOCODING_PRECISION=2, and it seems to be working as expected. I believe this issue has been fixed. Can re-open if it is not the case though.
