### ISSUE TITLE
Android app certificate validation invalid

### ISSUE THREAD

**Issue by nodiaque** [immich-app/immich#14099]
### The bug

Hello,

When using a reverse proxy that have a certificate where the subject name doesn't match the domain but have alternate subject name that match, immich won't connect and throw an invalid certificat error

https://pastebin.com/imYAe9b1

As soon as I change the subject name for my wildcard domain (which is in the alternate subject), it work.

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.12.0.1

### Version of Immich Mobile App

1.20.0.1 build 166

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
unraid, no docker compose
```

### Your .env content

```Shell
not using
```

### Reproduction steps

1. Setup a reverse proxy like Swag, Nginx
2. Use a certificate file where the subject name doesn't match the domain (or isn't a wildcard to the immich subdomain) but do add the wildcard in the alternate subject
3. Try to connect with the mobile app
...

### Relevant log output

```shell
ApiException 400: TLS/SSL communication failed: GET /server/ping (Inner exception: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393)))

#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:143)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:920)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1049)
<asynchronous suspension>
```

**Comment by bo0tzz** [comment]
Can you clarify, is this a valid WebPKI certificate or something self signed?

**Comment by nodiaque** [comment]
Let's Encrypt certificate

**Comment by nodiaque** [comment]
Here's what I mean.

This is my server certificat. We can see here that the subject name (Objet, sorry it's in French) is something.duckdns.org. It is not a widcard. For privacy purpose, I blurred and renamed it a.duckdns.org. My immich server reside at immich.b.duckdns.org.

![image](https://github.com/user-attachments/assets/e4804698-213a-4ee7-b8f7-ba4559ebb630)

Here, you can see I have alternate subject set to:
- *.a.duckdns.org
- *.b.duckdns.org
- *.c.duckdns.org
- b.duckdns.org
- c.duckdns.org

![image](https://github.com/user-attachments/assets/f56fe9b8-9066-4c81-8ee4-d4135692416f)

**Comment by mmomjian** [comment]
I am not able to replicate this. My nginx serves a Lets Encrypt cert covered by a Subject Alternative Name and have had no issues on iOS or Android.

**Comment by nodiaque** [comment]
Weirdly when I put back that certificat, it does the error back and it's made from the same software. Maybe when there's multiple alternative name? In my case, it was the third dns alternate name. Be sure that the subject doesn't match the domain nor subdomain.

**Comment by mmomjian** [comment]
My cert has like 20 alternate names , FWIW

**Comment by nodiaque** [comment]
I really don't know what to say. It's the only difference between this certificate and the one I'm using right now.

**Comment by squanbo** [comment]
I encountered the same issue when using a reverse proxy. I am using a self-signed certificate and have enabled the 'Allow self-signed certificates' option in the settings. When opening a video on the Android client, the app crashes.

ApiException 400: TLS/SSL communication failed: GET /partners (Inner exception: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393)))

#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:143)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:920)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1049)
<asynchronous suspension>

**Comment by mmomjian** [comment]
> I encountered the same issue when using a reverse proxy. I am using a self-signed certificate and have enabled the 'Allow self-signed certificates' option in the settings. When opening a video on the Android client, the app crashes.
> 
> ApiException 400: TLS/SSL communication failed: GET /partners (Inner exception: HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393)))
> 
> #0 _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99) #1 _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:143) #2 _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:920) #3 _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1049)

Your issue is not related. Self signed certs currently do not support video playback.

**Comment by mmomjian** [comment]
@nodiaque please share your full domain name for us to be able to test on our end.

**Comment by nodiaque** [comment]
is there a way to send private message in github? Cause I won't disclose my domain name publicy on the internet

**Comment by mmomjian** [comment]
You can join our discord and then ask to DM someone there

**Comment by bo0tzz** [comment]
Is your reverse proxy sending the full certificate chain or only the leaf cert?

**Comment by mmomjian** [comment]
Confirmed misconfigured reverse proxy.

**Comment by nodiaque** [comment]
problem solved. for those that might have this issue, in nginx ssl.conf, normally you have let's encrypt dealing with this without a problem but since I'm importing cert from somewhere else, I had to modify the configuration.

Default nginx/swag configuration

```
ssl_certificate /config/keys/cert.crt;
ssl_certificate_key /config/keys/cert.key;
# verify chain of trust of OCSP response using Root CA and Intermediate certs
ssl_trusted_certificate /config/keys/cert.crt;

```

What's important to note here is:
cert.crt is actually a symlink to fullchain.pem
cert.key is a symlink to privkey.pem

My non working config was like that:

```
ssl_certificate /config/acme/####.duckdns.org.crt;
ssl_certificate_key /config/acme/####..duckdns.org.key;
# verify chain of trust of OCSP response using Root CA and Intermediate certs
ssl_trusted_certificate /config/acme/###.duckdns.org.all.pem;
```

Weirdly enough, one would think that ssl_trusted_certificate  would install the whole chain but no. So I changed the first line to
`ssl_certificate /config/acme/###.duckdns.org.all.pem;`
And voila, it's now resolving the chain properly.

For anyone else needing to check there ssl installation, this little tool work great. There's also an offline version if you don't have access from internet (ssl tools on the same page)

https://www.sslshopper.com/SSL-CHECKER.HTML

I should have followed my own advice, check my ssl installation and not blindly trust my docker ;)
