### ISSUE TITLE
Switch to next photo don't work with stacked photos (web)

### ISSUE THREAD

**Issue by DeltaTango69** [immich-app/immich#14101]
### The bug

If you have stacked photos and switch between, then the next photo in timeline will not be shown. This happens only when you switch between the stacked photos!

### The OS that Immich Server is running on

Ubunto 24.04

### Version of Immich Server

v1.120.1

### Version of Immich Mobile App

v1.120.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

1. Show stacked photo
2. Switch between the stacked photo
3. Push left forward button to next photo
4. Next photo will not be shown!

1. Show stacked photo
2. Switch **not** between the stacked photo
3. Push left forward button to next photo
4. Next photo will be shown!

**Comment by alextran1502** [comment]
@bo0tzz After you click on the stack, the arrow key will navigate between the stack items instead of navigating to the next asset on the timeline
