### ISSUE TITLE
problem with tags when stacking photos

### ISSUE THREAD

**Issue by MD77MD** [immich-app/immich#14179]
### The bug

when stacking multiple pictures,  tags are shown only for the first picture, other pictures tags are not shown but come back when unstacked

### The OS that Immich Server is running on

demo

### Version of Immich Server

demo

### Version of Immich Mobile App

demo

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
demo
```

### Your .env content

```Shell
demo
```

### Reproduction steps

1. stack multiple pictures 
2.open stack view
3.first pictures has its tags but the rest don't 
4. unstack pictures 
5. 5. all tags are back and shown normally 
...

### Additional information

got this in the demo

**Comment by yashrajjain726** [comment]
Please mention in which platform have you faced the issue, and the steps to re-produce it.
