### ISSUE TITLE
Allow Alternative Method of Sponsorship

### ISSUE THREAD

**Issue by atomdmac** [immich-app/immich#1419]
Not sure where else to put this so apologies if this is not the appropriate place to ask...

Now that Microsoft is removing support for Paypal via the GH Sponsorships feature, I'd like to use a different avenue to support this project.  Would it be possible to use LiberaPay or something similar?

**Comment by alextran1502** [comment]
Here you go, thank you for asking. I will update the documentation

https://liberapay.com/alex.tran1502/
