### ISSUE TITLE
[Technical Debt]: Share.shareFiles deprecation

### ISSUE THREAD

**Issue by matthinc** [immich-app/immich#1426]
### Feature detail

Affects:

- lib/shared/services/immich_logger.service.dart
- lib/shared/services/share.service.dart

### Platform

Mobile App

**Comment by alextran1502** [comment]
@matthinc I don't see a deprecation message on my end, I am running on Flutter 3.3.9. Where do you see the message from?

**Comment by matthinc** [comment]
![Screenshot 2023-01-26 at 18 09 21](https://user-images.githubusercontent.com/6898797/214902216-2bbca2ba-aee5-43ef-a55b-9d53b6989d62.png)

Also in `dart analyze`. I added ignore-comments for now to keep CI passing.

**Comment by jrasm91** [comment]
https://github.com/fluttercommunity/plus_plugins/blob/main/packages/share_plus/share_plus/lib/share_plus.dart#L72
https://github.com/fluttercommunity/plus_plugins/blob/main/packages/share_plus/share_plus/CHANGELOG.md#450
