### ISSUE TITLE
People Counter incorrect

### ISSUE THREAD

**Issue by mlinko6** [immich-app/immich#14336]
### The bug

My people counter is not correct, I've named exactly 91 People and the rest is hidden, but the counter shows 3689.

![Screenshot 2024-11-25 105936](https://github.com/user-attachments/assets/4f0941c7-b939-4c3a-bece-5b17d5111b16)

But when I open hidden faces (arround 7k) and try to hide some more.

If I create new people, they are not shown in the People - and can't be found either... I can scroll in the hidden section to hide some more people and save the changes, but when I open the people and hidden faces again there are the same faces still unhidden allthough I've just hidden them...

Example Foto below:

![Screenshot 2024-11-24 144603](https://github.com/user-attachments/assets/f0269915-5f95-4deb-a519-e42a8d1bc326)

These are the people that are shown all the time allthough I've hidden them many times. I've also restarted all the containers but the behaviour didn't change.

### The OS that Immich Server is running on

Synology NAS Docker

### Version of Immich Server

1.120.2

### Version of Immich Mobile App

1.0.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
s
```

### Your .env content

```Shell
s
```

### Reproduction steps

1.
2.
3.
...

**Comment by bo0tzz** [comment]
Dupe: #13245

**Comment by mlinko6** [comment]
Thx @bo0tzz , but there is no solution description in the Case #13245 ... Are you still working on it?

**Comment by mlinko6** [comment]
Thx for the feedback!
