### ISSUE TITLE
Check for corrupt asset backups doesn't recognize unmetered wi-fi correctly

### ISSUE THREAD

**Issue by lukaszwawrzyk** [immich-app/immich#14390]
### The bug

I wanted to try out the  "Check for corrupt asset backup" but it is always rejected with "Make sure to be connected to unmetered Wi-Fi". Needles to say, that I am connected to my home wifi. I tried to disable mobile data, it didn't help either, I tried both 2,4 and 5GHz networks. I am connecting to Immich through Tailscale if this could have any impact.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

v1.121.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

.

**Comment by bo0tzz** [comment]
I'm not sure which option you mean, can you share a screenshot?

**Comment by lukaszwawrzyk** [comment]
![image](https://github.com/user-attachments/assets/d4a9df36-72c3-4129-bf1f-9ebd573cf774)

**Comment by systemtester** [comment]
Is `!` at this line required?
#https://github.com/immich-app/immich/blob/3d61548d7da9a2985964ee2c081eec9aacc387b2/mobile/lib/providers/backup/backup_verification.provider.dart#L38

**Comment by bo0tzz** [comment]
Yes, it was accidentally removed.

**Comment by alextran1502** [comment]
Fixed in $14401
