### ISSUE TITLE
Android: Bottom sheet does not extend beyond navigation bar

### ISSUE THREAD

**Issue by ns130291** [immich-app/immich#14410]
### The bug

Bottom sheet does not extend beyond navigation bar:
![Screenshot_20241130_092647](https://github.com/user-attachments/assets/b3600ade-3fc5-4fa7-9e39-1060e80e97c0)

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.119.1

### Version of Immich Mobile App

1.21.0 build.168

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

Select image by long press

**Comment by alextran1502** [comment]
You can drag the sheet up
