### ISSUE TITLE
Users cannot see timeline, modify albums, see people, or favourite photos for albums they have "Editor" privileges to

### ISSUE THREAD

**Issue by bverkron** [immich-app/immich#14433]
I have created some shared albums and given a user (my wife) Editor privileges to those albums. However, she can't interact with them or see any information from them aside from just viewing the photos or downloading them directly inside the albums themselves.

In the iOS app:

* Cannot see the timeline (stuck at "Building the timeline")
* Cannot modify the albums she has Editor access to
* Cannot like (heart) photos
* Cannot delete photos (button does nothing)
* Cannot see people, place, or "on this device"
* Can download photos

In the web UI:
* Cannot see the timeline ("Click to upload your first photo")
* Cannot modify the albums she has Editor access to
* **_Can_** like (heart) photos, unlike in the iOS app
* Cannot delete photos (no option to delete)
* Cannot see people, place, or "on this device"
* Can download photos

Seems like the timeline issue _could_ be a duplicate of this https://github.com/immich-app/immich/issues/1497. That was closed as fixed but had people continue to experience the issue, it seems?

However, will so many other issues there's likely something else going on. I can't imagine why the user would not be able to add favourites regardless of the state of the timeline. The favourites button isn't even showing.

<img width="448" alt="Screenshot 2024-12-01 at 10 07 16 AM" src="https://github.com/user-attachments/assets/5728c3c2-f2fc-4a6a-94ce-53257b197593">

![IMG_0430](https://github.com/user-attachments/assets/ccca65cc-73c0-47d1-a52d-5e528afb0c44)

![IMG_0432](https://github.com/user-attachments/assets/f51f62b9-3a09-4355-95c4-63987e7daa17)

![IMG_0431](https://github.com/user-attachments/assets/c7225e86-a222-444f-aa69-3b8d60e91230)

**Comment by bverkron** [comment]
After reading [the documentation](https://immich.app/docs/features/shared-albums/) and some other discussions / bugs / reddit posts I am wondering if this does not function the way I think?

If I share an album with a user...
* will their timeline not be populated with photos from those albums?
* will they not be able to see people I've tagged in those albums?
* should they be able to favorite photos in the albums (conflicting behaviour between iOS app and web)
* should they be able to delete photos from the albums?

Right now I'm mostly concerned about the user being able to favorite photos and see people that have already been tagged but I'd like tho know how this is all supposed to work for the future.

**Comment by bo0tzz** [comment]
Sharing an album does exactly what it says on the tin and no more, it just shares the album. What you're looking for is https://immich.app/docs/features/partner-sharing. At the moment that does not yet share people or allow favouriting and such.

**Comment by bverkron** [comment]
@bo0tzz what about the inconsistent behaviour with the favorites between the iOS app and web ui? My wife is unable to favorite in the iOS app (no button appears) but can favorite in the web ui. Comments and likes is enabled as per the screenshot.

Additionally nothing shows up under her favorites after doing it in the web ui, which by the sounds of it might be "by design" currently?
