### ISSUE TITLE
Photos that are moved to trash are not properly deleted when trash is emptied on mobile and get re-uploaded

### ISSUE THREAD

**Issue by urbenlegend** [immich-app/immich#14439]
### The bug

I am having this issue where if I select a photo and use the "Move to Trash" option and then later empty the trash, the photos pop back up in my timeline and get re-uploaded to Immich.

### The OS that Immich Server is running on

Arch Podman-Docker

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

1.121.0 build.168

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Irrelevant
```

### Your .env content

```Shell
Irrelevant
```

### Reproduction steps

1. Long-press a photo and select "Move to Trash"
2. Go to Trash and empty the trash or permanently delete the aforementioned photo
3. Notice that the photo reappears in the timeline as a local photo and later gets re-uploaded
...

**Comment by bo0tzz** [comment]
If you're not deleting the local file from your phone, this is currently working as expected.
