### ISSUE TITLE
Tags and Shared Albums

### ISSUE THREAD

**Issue by alexrtp** [immich-app/immich#14478]
### The bug

When I share an album with other users, the users are not shown any tags for the shared photos. 
All tags are shown in the sidebar under the menu item Tags, but no photos are shown when clicking on the tags.

### The OS that Immich Server is running on

any

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

any

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
any
```

### Your .env content

```Shell
any
```

### Reproduction steps

1.Share Album
2.Open Image in Shared Album
3.Search the Tags
...

**Comment by bo0tzz** [comment]
This is currently working as expected. #12614
