### ISSUE TITLE
[Feature]: Use adaptive icons for Android

### ISSUE THREAD

**Issue by martyfuhry** [immich-app/immich#1447]
### Feature detail

Currently Immich uses a static image for its Android icon. But it could use [Adaptive Icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) to be styled more appropriately by the Android OS.

**Current Immich App Icon on Android 12**
![image](https://user-images.githubusercontent.com/100457/215154741-4bb1e587-75a5-464a-af42-bbfda09d669b.png)

**Adaptive Icon**
![image](https://user-images.githubusercontent.com/100457/215154766-87581b44-58b5-4bcb-a7b6-9d8c249f4b3d.png)

### Platform

Mobile App

**Comment by martyfuhry** [comment]
Adaptive icons will let the system build the icon different kinds of shapes. Here are what the Immich png looks like across the different shapes:

![image](https://user-images.githubusercontent.com/100457/215183040-4e5df61c-e556-49c2-a058-df1140d1045e.png)
![image](https://user-images.githubusercontent.com/100457/215183073-76f3211a-c17e-4e84-aaef-845026ecd048.png)
![image](https://user-images.githubusercontent.com/100457/215183083-4684f220-4c58-4cda-9f54-f9c5f79eab94.png)
![image](https://user-images.githubusercontent.com/100457/215183096-5cb955e9-007e-4ec8-aa26-069e821dc98c.png)

**Comment by martyfuhry** [comment]
It may look more authentic with some added padding:

![image](https://user-images.githubusercontent.com/100457/215184629-6260ab4d-8277-4ff9-88c1-86b7cb10e345.png)
![image](https://user-images.githubusercontent.com/100457/215184668-16942025-4d22-4f9f-a0c2-7f373c424533.png)
![image](https://user-images.githubusercontent.com/100457/215184688-740de41c-7f45-4c57-8f37-16b2fcd58f27.png)
![image](https://user-images.githubusercontent.com/100457/215184711-f7a806ea-038d-4f95-ab90-5048c5c982ea.png)

But maybe you like the colorful boundary more...

**Comment by alextran1502** [comment]
Hmm I like the padding more
