### ISSUE TITLE
[Web] Top bar covers top portion of photos

### ISSUE THREAD

**Issue by SayantanRC** [immich-app/immich#14471]
### The bug

Top bar / title bar / menu bar always covers the top section of the photos with no way to see the full photo on the web.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.120.1

### Version of Immich Mobile App

Not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

1. Upload this image (on web): 
   [2024-12-04_01-35](https://github.com/user-attachments/assets/b57d4373-354f-4880-8046-ff058ed94026)

   Then Immich web shows the thumbnail properly:  

   <img src=https://github.com/user-attachments/assets/d24bb203-8231-41b6-b2bc-970f02c04ca5 width=250/>

2. But on opening the image, the top part is always covered:  
   <img src=https://github.com/user-attachments/assets/b8f546a2-b760-4e08-ba3a-59be40cec1d3 height=400/>

**Comment by bo0tzz** [comment]
What browser are you using? Do you have any extensions like dark reader or such?

**Comment by SayantanRC** [comment]
@bo0tzz I use Firefox. Yes I use the Dark Reader extension.

**Comment by bo0tzz** [comment]
Dark reader messes up the styling of the top bar

**Comment by SayantanRC** [comment]
@bo0tzz I disabled Dark Reader and yes the bar becomes transparent, but it still overlaps. I don't think the issue should be closed. Ideally the image display should start below the bar, or the bar should disappear.

**Comment by mertalev** [comment]
I think it'd be reasonable for it to disappear if you click once on it, but that's more of a feature request.

**Comment by SayantanRC** [comment]
@mertalev Yes even that much would be great!

**Comment by thomas001** [comment]
Did you ever get around to file a new issue? I was looking for one, but couldn't find it.

**Comment by SayantanRC** [comment]
I guess I just forgot..
