### ISSUE TITLE
[BUG] connect ECONNREFUSED on fresh install Ubuntu 22.10

### ISSUE THREAD

**Issue by b3valsek** [immich-app/immich#1449]
Immich server can't connect with postgre and postgre can't log in with default pass. 
**Task List**
- [ x ] I have read thoroughly the README setup and installation instructions.
- [ x ] I have included my `docker-compose` file.
- [ x ] I have included my redacted `.env` file.
- [ x ] I have included information on my machine, and environment.

**To Reproduce**
1. Install fresh Ubuntu 22.10
2. Install docker
3. Install Immich by docker compose

Hardware tested: VM.Standard.E2.1.Micro, Lenovo Z510 laptop
OS tested: Ubuntu 22.10

**Expected behavior**
Working connection with postgre. 

**Screenshots**
![Screenshot from 2023-01-27 21-54-39](https://user-images.githubusercontent.com/119067436/215195249-d8f3900b-597c-4df7-a35a-a9e2d2bd5e16.png)

**System**
- Server Version: `release`

**Additional context**
Little changed env file: 
```
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/zdjecia/
JWT_SECRET=YGW5InCfxJTr2ZHQifeNUAnZyjbgi+jZEv+PZJXm5cYkESpgHRnd5XpGhzMrnvy3sw+5z486LrliGfXIEN3XI74Dmw91q9qY467fPOhqZpSfnxZjJeppyb80mhcQtOYiuJDcQiVJGDHPiz/ccDfhIQ6BQs3kFG8mLa6xRGLr8Vc=
PUBLIC_LOGIN_PAGE_MESSAGE="something"
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```
any changes in docker compose file

**Comment by alextran1502** [comment]
Please use tag `release` as shown in the docker-compose file.

**Comment by b3valsek** [comment]
> 

*edited

**Comment by jrasm91** [comment]
I'd try shutting the stack down, removing the postgres volume and then start everything up again. And/or show the logs for the immich_server container.

**Comment by b3valsek** [comment]
> I'd try shutting the stack down, removing the postgres volume and then start everything up again. And/or show the logs for the immich_server container.

In docker server log there is only: 
`[Nest] 1  - 01/27/2023, 9:41:48 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
error: password authentication failed for user "postgres" `

and in postgre log there is info about that default 'postgres' role doesn't exist
`
(2023-01-27 21:42:54.970 UTC [91] DETAIL:  Role "postgres" does not exist.
Connection matched pg_hba.conf line 100: "host all all all scram-sha-256")
`

**Comment by jrasm91** [comment]
That error should go away if you re-create the postgres data volume.

**Comment by b3valsek** [comment]
tried many times

**Comment by jrasm91** [comment]
> tried many times

How did you remove the volume? Also, can you share the compose file? You either didn't attach it, or github auto-removed it. Maybe just add the postgres and immich-server sections as those seem to be problematic.

**Comment by b3valsek** [comment]
> 

Everytime I just used docker compose with --force-recreate option. Compose file is untouched.

**Comment by jrasm91** [comment]
`--force-recreate` will re-create the containers, you need to delete the postgres _volume_. Do `docker-compose down -v` Or, if you have it mapped to an actual /data folder somewhere, you need to delete that.

**Comment by b3valsek** [comment]
> `--force-recreate` will re-create the containers, you need to delete the postgres _volume_. Do `docker-compose down -v` Or, if you have it mapped to an actual /data folder somewhere, you need to delete that.

Oh, you are right. I forgot that `--force-recreate` option doesn't remove the volume.
Solution: If whatever goes wrong on first installation, you must remove postgres volume. Reinstallation instruction:
`docker volume ls `
`docker volume rm "postgres_volume_name"`
`docker-compose up -d --force-recreate`

**Comment by sbkg0002** [comment]
With these instructions, I still have this error:
```
[Nest] 1  - 01/28/2023, 10:13:56 AM     LOG [InstanceLoader] BackgroundTaskModule dependencies initialized +1ms
[Nest] 1  - 01/28/2023, 10:13:56 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
```
What I did:
```
docker compose stop
docker compose rm
docker volume rm docker_pgdata
docker-compose up -d --force-recreate
```
Anyone know what am I missing here? This is since the last update; before that everything was fine.

**Comment by alextran1502** [comment]
> With these instructions, I still have this error:
> 
> ```
> 
> [Nest] 1  - 01/28/2023, 10:13:56 AM     LOG [InstanceLoader] BackgroundTaskModule dependencies initialized +1ms
> 
> [Nest] 1  - 01/28/2023, 10:13:56 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
> 
> Error: connect ECONNREFUSED 127.0.0.1:5432
> 
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
> 
> ```
> 
> What I did:
> 
> ```
> 
> docker compose stop
> 
> docker compose rm
> 
> docker volume rm docker_pgdata
> 
> docker-compose up -d --force-recreate
> 
> ```
> 
> Anyone know what am I missing here? This is since the last update; before that everything was fine.
> 
> 
> 
> Edit: database logs:
> 
> ```
> 
> PostgreSQL init process complete; ready for start up.
> 
> 
> 
> 2023-01-28 10:18:55.821 UTC [1] LOG:  starting PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
> 
> 2023-01-28 10:18:55.821 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> 
> 2023-01-28 10:18:55.821 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> 
> 2023-01-28 10:18:55.834 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> 
> 2023-01-28 10:18:55.842 UTC [63] LOG:  database system was shut down at 2023-01-28 10:18:55 UTC
> 
> 2023-01-28 10:18:55.851 UTC [1] LOG:  database system is ready to accept connections
> 
> ```

@sbkg0002  You are probably using the older .env file that doesn't have the value `db_hostname`. Please copy the default value from the .example.env file to your environment and it should fix it

**Comment by sbkg0002** [comment]
Thanks @alextran1502. Will try asap. I noticed the 127/32 but would expect the container name there.

**Comment by sbkg0002** [comment]
Got it up and running, but now all my config and pictures are gone. 
Is there any to reindex the pictures?
