### ISSUE TITLE
[web] Thumbnails fail to load for videos that contain special characters in the filename

### ISSUE THREAD

**Issue by natedawg** [immich-app/immich#14503]
### The bug

With update (v1.122.0) thumbnails for many of my videos fail to load on the web ui. I get the message "error loading image" instead. The filenames for the failed videos contain Korean or Japanese characters. 

`docker logs` show the same error repeated

I have logged out and back in of the web ui and regenerated all thumnails on the server but the issue persists.  
The mobile app shows everything correctly although it has not updated to v1.122 yet.  

### The OS that Immich Server is running on

docker on debian

### Version of Immich Server

v1.122.0

### Version of Immich Mobile App

v1.122.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
na
```

### Your .env content

```Shell
na
```

### Reproduction steps

1. Open the timeline on the web
2. Thumbnails fail to load for videos that contain Korean or Japanese text in the filename. 

### Relevant log output

```shell
[Nest] 17  - 12/05/2024, 12:10:52 PM   ERROR [Api:LoggerRepository~48tzdcmb] Unable to send file: TypeError
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (node:_http_outgoing:702:3)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:794:10)
    at sendFile (/usr/src/app/dist/utils/file.js:48:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:58:9)
[Nest] 17  - 12/05/2024, 12:10:52 PM   ERROR [Api:GlobalExceptionFilter~48tzdcmb] Unknown error: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (node:_http_outgoing:702:3)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:794:10)
    at sendFile (/usr/src/app/dist/utils/file.js:48:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:58:9)
```

**Comment by alextran1502** [comment]
Is there a sample video that you can share here for troubleshooting?

**Comment by natedawg** [comment]
@alextran1502 
I don't have a video to share. However I just repeated the problem by renaming a working video. 

1. Take any video that shows the thumbail and delete it from immich. 
2. rename the video so it includes Korean text. Example: `트test`
3. Upload the video again

**Comment by seanob86** [comment]
+1 here. A lot of my images are no longer loading

image name example `大学４年生 196.jpg `

```
[Nest] 16  - 12/06/2024, 7:53:55 AM   ERROR [Api:GlobalExceptionFilter~wgq3o5lj] Unknown error: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (node:_http_outgoing:702:3)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:794:10)
    at sendFile (/usr/src/app/dist/utils/file.js:48:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:58:9)
```

**Comment by seanob86** [comment]
Rolling back to `v1.121.0` fixes the issue. 

Unlike the original ticket disclosing issues with videos. Images are also impacted. Neither can they be viewed in web or iOS app. Thumbnails also not loading.

**Comment by natedawg** [comment]
I can confim image thumbnails also will not load when Korean text is in the filename. In this case both the small thumb for the timeline and the large thumb for the asset view fail to load. Videos still play on hover and when opened even when they are transcoded.

**Comment by mertalev** [comment]
It's probably due to #14425. Based on [this](https://stackoverflow.com/a/2543744) post, Content-Disposition only supports ASCII by default unless UTF-8 is specifically specified.

**Comment by zhiiwg** [comment]
I can confirm image thumbnails also will not load when Chinese text is in the filename.

**Comment by feixiang-1** [comment]
Yes, I confirmed that after upgrading to v1.122.0, all thumbnails cannot be displayed. The console shows a large number of 500 errors...
I thought it was an nginx reverse proxy error, so I got the same 500 error when requesting a local address on the server.
![image](https://github.com/user-attachments/assets/abaa5995-efed-497b-b271-6f946cca7ca7)
![image](https://github.com/user-attachments/assets/4ac8ba22-3744-4c28-9b48-17830337e625)

**Comment by feixiang-1** [comment]
After I rolled back to v1.121.0, everything returned to normal.

**Comment by shenyan-008** [comment]
I also can't load thumbnails and original images, and I can't load thumbnails and original images even if I roll back to the previous version. It was working fine before the update, but after the update (v1.122.0), all my efforts were in vain.

**Comment by lucius346346** [comment]
Same here with polish diacritics: ą, ć, ę, ł, ń, ó, ś, ź, ż
