### ISSUE TITLE
Photo don`t delete on mobile, if it deleted from web or other device.

### ISSUE THREAD

**Issue by vadim0872** [immich-app/immich#14515]
### The bug

The photo dont delete on the phone after delete it on another device or web client/

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

 v1.122.0

### Version of Immich Mobile App

 v1.122.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
the same as example on site
```

### Your .env content

```Shell
the same as example on site
```

### Reproduction steps

1. Take photo on mobile phone
2. Sync or Upload photo on server
3. Delete this photo from web
4. Delete this photo from trash (not necessary)
5. Open explorer on phone, the photo all the same folder
6. Open immich app, photo display in gallery

**Comment by bo0tzz** [comment]
This is working as expected

**Comment by vadim0872** [comment]
Where it is expected? On google photo when I delete the photo from other device it delete on other too.
It not useful, e.g. I return from vacation and want to clean up photos on big screen (tablet/laptop), and then I need to do same work to delete from mobile. It's very "convenient", isn't it

**Comment by mmomjian** [comment]
#165 will help improve this
