### ISSUE TITLE
Strange black gradient obscuring thumbnails on mobile

### ISSUE THREAD

**Issue by Book-reader** [immich-app/immich#14514]
### The bug

On the v1.122.0 mobile client, there is a strange black gradient that obscures all thumbnails, making it really difficult to see what the image or video is.
This issue is not present in the web client

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.122.0

### Version of Immich Mobile App

v1.122.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
.
```

### Reproduction steps

1. Open mobile client
2. Thumbnails obscured

### Additional information

![Screenshot_2024-12-06-22-41-40-07_d8aea95ef633eb6b7eb1cae13c34b40e](https://github.com/user-attachments/assets/a8a64519-e20c-4632-b8da-145ea878e95a)

**Comment by alextran1502** [comment]
Hmm I can’t reproduce this. Can you try signout and sign back in?

**Comment by Book-reader** [comment]
I have signed out and back in as well as reinstalled the immich mobile client and updated to v1.122.1, and the issue is still there.

I have also noticed that some parts of the mobile ui are now solid green in v1.122.0 and v1.122.1

![Screenshot_2024-12-07-10-11-27-23_d8aea95ef633eb6b7eb1cae13c34b40e](https://github.com/user-attachments/assets/99e4bbda-9e38-4498-8053-caa00e3d5b6d)

https://github.com/user-attachments/assets/cb0737fa-31b8-48c5-a54f-292b9e0f8f42

![Screenshot_2024-12-07-10-17-11-68_d8aea95ef633eb6b7eb1cae13c34b40e](https://github.com/user-attachments/assets/9c2c4356-7017-47a6-917b-e8cd40a25fa4)

**Comment by alextran1502** [comment]
Tracking in #14543

**Comment by alextran1502** [comment]
Can you also try installing the APK from #14543 to see if it fixes the issue
