### ISSUE TITLE
No translation in the application

### ISSUE THREAD

**Issue by OriginalSimon** [immich-app/immich#14526]
### The bug

When viewing in an application, there is no line feed. The error persists in all languages, making the text difficult to understand for users regardless of the interface language.
This problem has persisted over multiple updates.
![зображення](https://github.com/user-attachments/assets/cd6b0a5f-0f71-435d-9b90-8f5f8fec10c1)

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.122.1

### Version of Immich Mobile App

v1.122.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. This is the search page.

### Additional information

Most likely the translation key is missing. I can't find this line in weblate.

**Comment by bo0tzz** [comment]
The text is at https://github.com/immich-app/immich/blob/97c1eb72897c34bd00891d1d336504ddddebb857/mobile/lib/pages/search/search.page.dart#L683
