### ISSUE TITLE
mobile app visual glitches

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#14543]
### The bug

There are visible visual glitches like missing characters (even partially), missing icons, etc. since version 1.122.x on Samsung A51 with Adnroid 13. Version 1.121.0 works fine on that device. E.g. Samsung S23+ is ok with all versions.

|   |   |   |   | 
|---|---|---|---|
|![obrazek](https://github.com/user-attachments/assets/53926c9f-2c08-4963-a5ed-bbdd0bad0fd6)|![Screenshot_20241207_102709](https://github.com/user-attachments/assets/f9dad31d-7ea5-4fb4-b62f-2a85d782391d)|![Screenshot_20241207_102759](https://github.com/user-attachments/assets/6b55f5e8-0e17-47d0-be65-88efd490ac07)|![Screenshot_20241207_103818](https://github.com/user-attachments/assets/b1aeafa1-7bc3-4148-b6fd-411d0d60f42f)|

### The OS that Immich Server is running on

Fedora 41

### Version of Immich Server

v.1.122.1

### Version of Immich Mobile App

v.1.122.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

Install v1.122.x on Android

**Comment by Saneckg** [comment]
This version of the mobile app simply freezes 20 seconds after launch. phone redmi note 10 pro. Cannot be used.

**Comment by alextran1502** [comment]
Is restarting the app help? 🤔 and do you see any related error in the log?

**Comment by schizovivek** [comment]
Im facing weird issues on the S22+ which is on Android version 13 and OneUI version 5.1
I've reset the app, rebooted the phone but the issue still persists. No issues on a LG v30 on Android 9

Before reset
https://github.com/user-attachments/assets/e00348d9-f995-46c3-9342-11411e5d26ad

After Reset
https://github.com/user-attachments/assets/94f406d1-2caa-4e0a-b42e-7e62e5dc267d

**Comment by BernardoGiordano** [comment]
I also confirm the latest app update has issues. The app is completely unresponsive to touches. I tried wiping all data, uninstalling and reinstalling and I'm stuck in the server url screen, unable to tap on the server endpoint url input. No keyboard shows up.

**Comment by alextran1502** [comment]
Can you guys help provide the app log please?

**Comment by schizovivek** [comment]
I'm not sure how to pull out logs from Android apps

**Comment by waclaw66** [comment]
App restart nor reinstallation doesn't help. Logs look normal, no errors there, just expected sync info.
Those glitches are changing while using the app or switching between apps.

**Comment by waclaw66** [comment]
I would expect that those glitches are result of some rendering issue, maybe caused by enabling Impeller rendering engine.

**Comment by alextran1502** [comment]
@waclaw66 I have the same hunch. Can you try this APK with Impeller disabled?

https://drive.google.com/file/d/13A8-970emQfbP8vdtSedrUklFIs6fWKS/view?usp=sharing

**Comment by waclaw66** [comment]
Yes, render works properly with Impeller disabled.

> @waclaw66 I have the same hunch. Can you try this APK with Impeller disabled?

**Comment by schizovivek** [comment]
> @waclaw66 I have the same hunch. Can you try this APK with Impeller disabled?
> 
> https://drive.google.com/file/d/13A8-970emQfbP8vdtSedrUklFIs6fWKS/view?usp=sharing

Tried this version on the s22+ .. Had to un install and re install for it to work

**Comment by Book-reader** [comment]
> @waclaw66 I have the same hunch. Can you try this APK with Impeller disabled?
> 
> https://drive.google.com/file/d/13A8-970emQfbP8vdtSedrUklFIs6fWKS/view?usp=sharing

This fixes the black gradients on the thumbnails and random solid green elements for me
