### ISSUE TITLE
Counting inside Persons not working

### ISSUE THREAD

**Issue by ledahosn** [immich-app/immich#14569]
### The bug

![image](https://github.com/user-attachments/assets/810ec86b-08ef-49b4-93c8-3989c552f715)

It shows 1 Datei (means 1 File) but sometimes it is not counting correctly - I believe it could be not counting Live-Pics or Videos or something like that

### The OS that Immich Server is running on

Alpine Linux

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

not-used

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
```

### Your .env content

```Shell
---
```

### Reproduction steps

1. Go into Faces
2. Click on any with different Media Types

**Comment by bo0tzz** [comment]
This should be fixed in the latest release
