### ISSUE TITLE
[Feature]: Add APK file to release

### ISSUE THREAD

**Issue by EnochPrime** [immich-app/immich#1463]
### Feature detail

Add APK file to release. This was done prior to the new release script (#447).

### Platform

Mobile App

**Comment by alextran1502** [comment]
@bo0tzz Let's aim to have this in the CI in the next release

**Comment by bo0tzz** [comment]
Agree. @matthinc were you working on a workflow to build the apk or not?

**Comment by matthinc** [comment]
@bo0tzz Had this in my personal backlog but I have not yet had the time
