### ISSUE TITLE
Unable to load image with UTF characters

### ISSUE THREAD

**Issue by matejkramny** [immich-app/immich#14642]
### The bug

Hi, not sure how it happened but some of my images have UTF8 characters in the path

I can download the image, but not view it in the browser.

The request to get the image in the web app fails with error 500

![image](https://github.com/user-attachments/assets/322bc881-f6fd-4ec4-a3e1-b0e9f56594df)

See log output for the stack trace

### The OS that Immich Server is running on

docker container

### Version of Immich Server

v1.122.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
file path is `photo-2018-08-23 160104+0000.81.jpg`
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

1. Upload a file with utf characters in name/path
2. Image is not viewable in the browser

### Relevant log output

```shell
[Nest] 17  - 12/11/2024, 11:04:31 AM   ERROR [Api:GlobalExceptionFilter~uefjf2bk] Unknown error: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
at ServerResponse.setHeader (node:_http_outgoing:702:3)
at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:794:10)
at sendFile (/usr/src/app/dist/utils/file.js:48:17)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:58:9)
```

**Comment by mmomjian** [comment]
Please update your server, this is fixed.
