### ISSUE TITLE
[BUG] Android back button exits the app when selecting multiple assets

### ISSUE THREAD

**Issue by martyfuhry** [immich-app/immich#1464]
**Describe the bug**
When in the multiselection view of the main timeline, e.g., tapping the back button in Android (iOS has no such functionality) exits the app. I would expect it to deselect all of your photos and hide the bottom sheet. In other words, I expect it take you back to a non-multiselection state, or just the normal browsing activity.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Open the Android app
2. Hold down to select multiple assets
3. Tap the back button
4. Exit the app

**Expected behavior**
I would expect to remain in the app. My selection should be cleared and the bottom sheet should hide.

**Screenshots**

"Multiselect" view I was referencing above:
![image](https://user-images.githubusercontent.com/100457/215273601-f11c8d81-52b3-48ec-8488-af6aedca4c02.png)

Hitting back exits the app.

**System**
- Phone OS [iOS, Android]: Android
- Server Version: 1.42.0
- Mobile App Version: 1.43.0 build.66

**Additional context**
N/A

**Comment by SitramSoft** [comment]
I can confirm this behavior on my OnePlus 9 Pro running Android 13.

Server version: v1.43.1
Mobile App Version: 1.43.0 build.66
