### ISSUE TITLE
[BUG] Doesn't show DNG file when duplicately-named JPG exists despite both being uploaded

### ISSUE THREAD

**Issue by doblez42** [immich-app/immich#1466]
**Describe the bug**
When you take photos in pro mode on Samsung phones you're unable to avoid a low res .jpg copy of the DNG file. Immich then uploads both files, compares them and then only shows the low res .jpg in both the Immich app and on the web.
Both files have the same name except for the extension. When you take the photo both images are shown in the app, but after uploading only the jpg remains. 

**Expected behavior**
I would expect it to upload both files since they're different filenames (if you include extension)

**System**
- Phone OS [Android]: `<13>`
- Server Version: `<1.43.1>`
- Mobile App Version: `<1.41 build.66>`

**Additional context**
Might be a feature to toggle whether you want both raw and jpg of a file with the same name.

**Comment by alextran1502** [comment]
Can you help me understand how you determine where can you see the two files' versions, i.e low res vs high res on Android?

**Comment by doblez42** [comment]
With low res I just meant "lossy" as in the difference between a raw and jpg. The actual resolution is identical.
 An example is photo "20230128_163255.jpg" and photo "20230128_163255.dng", both are 3000x4000 pixels, but due to the format one is ~23MB and the other is ~3.5MB

**Comment by doblez42** [comment]
Misclicked - sorry!

**Comment by alextran1502** [comment]
Can you actual see two files on the album/folder/file system on the phone?

**Comment by doblez42** [comment]
Yes, I've taken 3 screenshots. One of the files in the folder structure and one of how it looks in Immich before and after upload. I also have the log file exported if needed. 
![SmartSelect_20230128_180713_Solid Explorer](https://user-images.githubusercontent.com/77155786/215279674-169b70d6-9fde-4518-9042-7ae52a6fc1a7.jpg)
![SmartSelect_20230128_180754](https://user-images.githubusercontent.com/77155786/215279676-b7aaf08a-0d1f-4f8c-8742-edd0fe0cb0c4.jpg)
![SmartSelect_20230128_181026](https://user-images.githubusercontent.com/77155786/215279677-3a952b17-3b59-40cb-9238-067b355c25b3.jpg)

**Comment by alextran1502** [comment]
Can you help me check if both files are uploaded to Immich `UPLOAD_LOCATION` directory?

**Comment by doblez42** [comment]
It looks like they are indeed both uploaded and it's the client that doesn't show both files.
Updated the title to reflect that it's uploaded but not shown.
![2023-01-28 21_04_58-Window](https://user-images.githubusercontent.com/77155786/215288514-bb4079a7-7bd6-41da-b3b6-1715709816bd.png)

**Comment by alextran1502** [comment]
Can you help shared a set of files? I can use them to troubleshoot and see what is going on here

**Comment by doblez42** [comment]
Here's an imageset of raw (dng) plus jpg files from a recent Galaxy S series phone.
[Nextcloud imageset](https://nextcloud.hjorthlund.dk/s/TNQyPXJBE9iCCkL)

**Comment by alextran1502** [comment]
So, the problem is the thumbnail generation library cannot handle DNG files, which is strange because Apple also has DNG raw files and the thumbnail can be generated. So only the JPEG file gets thumbnail generated so it is displayed on the app.

Please follow #1414 because that would potentially fix this issue.
