### ISSUE TITLE
Apply Storage Template to moved-into-album- and altered-date-files

### ISSUE THREAD

**Issue by hardysim** [immich-app/immich#14660]
### The bug

I'm using a Storage Template with the album-preset which moves files into folders just fine if the "Storage Template Migration"-job is run. But not automatically.

I know this ["intended" for existing files](https://immich.app/docs/FAQ/#what-happens-to-existing-files-after-i-choose-a-new-storage-template) but it doesn't make sense if I modify a file by moving it to a (different) album or alter its date (so it should move to another new year-folder).

It would be fine if the migration job is run regularly or if I could at least have access to it from the outside to add a cronjob for it. Is this possible? Wouldn't it make sense to add the migration job to the list of regularly jobs (I assume there is one)?

### The OS that Immich Server is running on

TrueNAS 24.10.0.2

### Version of Immich Server

v1.122.2

### Version of Immich Mobile App

v1.122.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I'm using the TrueNAS app for immich (which is using docker).
```

### Your .env content

```Shell
I did not add any "Additional Environment Variables" to the TrueNAS app config for immich (just added the storage folders linked to a host path).
```

### Reproduction steps

1. Install immich as via the TrueNAS app functionality
2. enable Storage Template using the album-preset
4. add images to immich via the web-uploader
5. (files are now automatically moved to the /year/other folder - good)
6. create some albums and add images to them
7. (files are *not* moved to the new album on the filesystem - bad)
8. upload more images via the web-uploader and add them directly to an album
9. (files are *still not* moved to the new album on the filesystem - bad)
10. alter an image's date so it should be sorted into a different year-folder
11. (files are *still not* moved to the new year folder on the filesystem - bad)
12. run the storage template job
13. (files are all correctly sorted now - good)

**Comment by mmomjian** [comment]
How long after making the changes did you check the location of the files on the disk? 

Did you edit the date in the immich web UI or by some other method?
