### ISSUE TITLE
[Mobile] Pinch to zoom broken on latest iOS and Android apps

### ISSUE THREAD

**Issue by mr-bobdobalina** [immich-app/immich#14677]
### The bug

Pinch to zoom not functional. I powered on an iOS device with an older version of Immich app and zoom was fine. Went to the app store and updated it and pinch-to-zoom doesn't work anymore. Android does the same thing with v1.122.2 build 170

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.122.2

### Version of Immich Mobile App

1.122.2 build 184

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

1.Open an image
2.Attempt to pinch to zoom in/out

**Comment by danieldietzler** [comment]
Fixed in #14608, a patch release will come in the next days
