### ISSUE TITLE
Android: Cannot zoom "live photos"

### ISSUE THREAD

**Issue by tsuijten** [immich-app/immich#14682]
### The bug

Pinch zooming works fine with normal photos, but when I click on a "live photo" (with a small video) I cannot pinch-zoom into the photo.

### The OS that Immich Server is running on

Synology NAS

### Version of Immich Server

1.122.1

### Version of Immich Mobile App

1.122.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

1. Open a live photo
2. Try to pinch zoom

**Comment by bo0tzz** [comment]
#14608
