### ISSUE TITLE
[Mobile] Motion Photo or Live Photo playback broken

### ISSUE THREAD

**Issue by NicholasFlamy** [immich-app/immich#14698]
### The bug

Motion playback entirely doesn't work for motion photos on-device only or on-device and remote.

The second part of the bug is that if you click on a photo in the gallery and then swipe to a motion photo and click play for motion playback, it will view the photo you started on. This applies to on-device only, on-device and remote, and remote only.

This seems to have been caused by #14608

<br><br>

Video of on-device and remote:

https://github.com/user-attachments/assets/2e580ec8-28d8-4098-b570-6f4c0aa317fa

<br>

Video of remote only (I used another app to delete the local copy):

https://github.com/user-attachments/assets/fce436d6-0a10-41e8-8b84-88875dcf4a10

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.122.3

### Version of Immich Mobile App

v1.122.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Reproduction steps

Explained above. Also, the video shows my taps.
```[tasklist]
### Tasks
- [ ] https://github.com/immich-app/immich/pull/14731
- [ ] https://github.com/immich-app/immich/issues/14758
```

**Comment by Rihcus** [comment]
Also have this issue

**Comment by NicholasFlamy** [comment]
> Also have this issue

Yep. One of the devs is already working on it. If you discovered some behavior with an edge case that I did not already cover in the post, please share it.

**Comment by mcjak97** [comment]
Me also i have this issue.
Motion photos are completely broken on mobile app.

**Comment by mertalev** [comment]
You're right, the issue impacts most live photos in practice.

For future reference, please thumbs up the issue instead of replying if the issue is relevant to you and there's no new info to add.

**Comment by NicholasFlamy** [comment]
So the first bug was fixed but the second bug (likely created by this new video player as well, but I have not downgraded to check) was not:


> The second part of the bug is that if you click on a photo in the gallery and then swipe to a motion photo and click play for motion playback, it will view the photo you started on. This applies to on-device only, on-device and remote, and remote only.

If you want me to split this into a separate issue rather than having this one reopened, I can do that.

**Comment by alextran1502** [comment]
> If you want me to split this into a separate issue rather than having this one reopened, I can do that.

Yes please

**Comment by NicholasFlamy** [comment]
Alright, new issue #14758 created and new video (demonstrating the remaining issue on app version v1.123.0) uploaded to that issue.
