### ISSUE TITLE
Add ability to create albums

### ISSUE THREAD

**Issue by jbaez** [immich-app/immich#147]
Albums are a great way of organizing photos. This could be implemented like in Google photos:
- when viewing a single photo, add option to "add to album" (can be added to a shared album or "normal" album)
- when viewing a single photo from inside an album, add option to "Remove from album"
- from inside an album, add option to add photos (exactly like in the current "shared album")
- from  inside an album, add option to share album (convert it into shared album)
- from inside an album, add option to remove album

Having photos in albums also makes it easier for a "export albums" feature (that could be implemented in the future) that would export photos using the albums as folders.

**Comment by alextran1502** [comment]
I like this idea. Let me see how to refactor the shared albums feature to implement this one

**Comment by jbaez** [comment]
@alextran1502 I was just looking into the code, if you want I can do the refactor and do a PR. It seems straightforward. The DB looks fine (although the tables could be renamed). Mostly just needs renaming "sharing" into "album" and changing the API.
I think the `/shared/...` API can just become `/album/:id/...`
What do you think?

**Comment by alextran1502** [comment]
Ok the backend it is very straightforward. I was mentioning about the mobile app 🤓

**Comment by jbaez** [comment]
OK cool. I'll do the backend and update the mobile app to use the "new" API first 😃

**Comment by Eidenz** [comment]
Any update on this feature?

It seems to only be missing the UI implementation, and it's the main missing feature preventing me from testing the app more thoroughly.

**Comment by alextran1502** [comment]
@Eidenz Album and shared album is being work on in #342 for the web. Once that is done, I will circle back and implement album only feature on the mobile app

**Comment by alextran1502** [comment]
Implemented in #420
