### ISSUE TITLE
Icons missing from photo toolbar when screen too narrow (web)

### ISSUE THREAD

**Issue by ajpanton** [immich-app/immich#14702]
### The bug

Opening a photo with a web browser when the screen is too narrow will hide the leftmost icons in the toolbar. They become visible when the screen is made wider. Can't find them in the dropdown menu either.

In the app the layout is different and it doesn't have this problem. It's very close though, maybe it would be missing icons if the screen was just a tiny bit narrower than what I have?

Narrow screen:
<img src="https://github.com/user-attachments/assets/22ba98fb-adcc-46fb-92d9-1f451f564bd9" width=50% height=50%>

Wide screen:
<img src="https://github.com/user-attachments/assets/84b1ca3b-0620-4dfb-926c-7746da31081b" width=50% height=50%>

### The OS that Immich Server is running on

Docker

### Version of Immich Server

1.122.3

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

**Comment by aviv926** [comment]
Can confirm that this happens to me too (although the sharing icon is displayed but not the others) tested in the demo site

![995d27ec-6508-497a-8699-06384a6e27be.png](https://github.com/user-attachments/assets/a8c1c9e4-9f70-4800-8803-2f27c7bf044e)
