### ISSUE TITLE
Can't download or upload with Telegram built-in browser

### ISSUE THREAD

**Issue by ajpanton** [immich-app/immich#14701]
### The bug

Telegram, the chat app, has a (sadly opt-out) built-in browser. With it, you can't upload or download any photos to/from Immich. Other sites work fine, and Immich works fine with other browsers. I realize it might be a bit low priority for an uncommon browser, but when posting links in Telegram, many people seem to be using this browser.

I'm running Telegram v11.5.4 (5528) on Android 14.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

1.122.3

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

**Comment by alextran1502** [comment]
Please open this as a feature request

**Comment by aviv926** [comment]
FYI to disable  built-in browser in telegram;
telegram - settings - chat settings - In-App browser - disable

**Comment by ajpanton** [comment]
> FYI to disable built-in browser in telegram; Telegram - Settings - Chat Settings - In-App browser - disable

It's the first thing I would do personally, but I can't expect everyone else to do the same.

**Comment by ajpanton** [comment]
> Please open this as a feature request

I fail to see how it's not a bug, as it works everywhere else. Also it doesn't really indicate what went wrong (I should've maybe mentioned this in the beginning). Well, uploading just brings you back to the album immediately, but even this has been enough to trick multiple people into thinking the upload went through. Downloading does bring up the download progress bar, which does actually display the download as finished, but nothing was downloaded.

But if this is still seen as a feature, I can make a feature request.
