### ISSUE TITLE
Motion photos clearly marked in the browser, but not in the app.

### ISSUE THREAD

**Issue by ajpanton** [immich-app/immich#14703]
### The bug

When browsing the timeline or an album on the web, motion photos are clearly marked with a small icon in the top right corner. In the app this icon is missing.

Web has the icon:
<img src="https://github.com/user-attachments/assets/15a7541e-b8bf-4e98-954d-b8db0a0ff585" width=50% height=50%>

App is missing the icon:
<img src="https://github.com/user-attachments/assets/262cdbbb-b36b-4564-baeb-03829ef99367" width=50% height=50%>

### The OS that Immich Server is running on

Docker

### Version of Immich Server

1.122.3

### Version of Immich Mobile App

1.122.3 build 171

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

**Comment by alextran1502** [comment]
I don't see this as a bug but rather different people platform has different way of interaction with the auto play feature.

On the web you can hover the mouse on top of the play button to auto play the motion part. There is no such hover mechanism on the mobile app.

Also with the smaller screensize, showing more icons on the thumbnail will make it look too crowded

**Comment by ajpanton** [comment]
> I don't see this as a bug but rather different people platform has different way of interaction with the auto play feature.
> 
> On the web you can hover the mouse on top of the play button to auto play the motion part. There is no such hover mechanism on the mobile app.
> 
> Also with the smaller screensize, showing more icons on the thumbnail will make it look too crowded

Both of your arguments fall on the fact that videos do autoplay when you hover over them on the web, and they too "suffer" from the smaller thumbnail in the app. But still they do have a play icon in the app. There's a lack of consistency here. I'd say the options are:
- add the icon for motion photos in the app
- remove the icon for motion photos on the web
- remove the icon for videos in the app

**Comment by alextran1502** [comment]
I guess we can add the LivePhotos icon in the same position if the Video icon

**Comment by mertalev** [comment]
The video icon in the app serves the purpose of differentiating between images and videos, which is more important than differentiating a basic photo from a live photo. The philosophy of a live photo is just that: a photo with a special effect. To mark it with an icon is unnecessary in the same that marking bokeh images or panoramas is unnecessary.

This is different from web, where the button serves an additional purpose by indicating that you can hover over the thumbnail for playback.
