### ISSUE TITLE
[BUG] Selecting an asset or album logs you out after first log in

### ISSUE THREAD

**Issue by martyfuhry** [immich-app/immich#1470]
**Describe the bug**
When you log in for the first time on a clean install on mobile (Android, specifically, haven't tested iOS), the first time you select an album, the app logs you out and returns you to the log in page. After you log in a second time, the second log in seems to stick, however.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Fresh install on Android
2. Log in
3. Navigate to Library
4. Tap an album
5. Sends you to the login page

**Expected behavior**
I am not logged out and I can see my album.

**Screenshots**

https://user-images.githubusercontent.com/100457/215287477-86b71781-bd72-4f9e-b46c-c3c30bec7708.mp4

In the above video, I have just logged in and am looking at the main timeline for the first time on a fresh install (Uninstall / Reinstall) on Android. I then navigate to an album and am returned to the login page.

**System**
- Phone OS [iOS, Android]: Android
- Server Version: 1.42.0
- Mobile App Version: 1.43.0 build.66

**Additional context**
N/A

**Comment by alextran1502** [comment]
Can you update the server to `1.43` and test again? Is it only application to empty album or also populated album?

**Comment by martyfuhry** [comment]
Same behavior on server `1.43`.  Same behavior tapping an empty album as a populated album. I *think* same behavior tapping "Stay logged in" as not, but it's annoying to have to retest because you have to completely reinstall ha.
