### ISSUE TITLE
Tagging a person in an image even when unrecognized

### ISSUE THREAD

**Issue by offbyone** [immich-app/immich#14711]
It would be nice to be able to mark images as containing a person even when they do not appear via facial recognition; I am in the process of putting together a photo album for my late father, and what I'm finding I miss is having him tagged in images where he's there in profile, or walking away; they are still pictures of him, but didn't trigger facial recogntion.

_Originally raised by @shakyr in https://github.com/immich-app/immich/discussions/2472#discussioncomment-6850486_

(the overall issue was closed but I believe this was missed)

**Comment by bo0tzz** [comment]
#7301

**Comment by offbyone** [comment]
Thank you for the link!
