### ISSUE TITLE
[BUG] Server out of date - wrong and showing server version 0.0.0

### ISSUE THREAD

**Issue by deddc23efb** [immich-app/immich#1480]
**Describe the bug**
Android App version 1.42.0.build.65 shows show notification saying "server out of date."  Server version is reported in the app as 0.0.0.  The server is a brand new install using docker.

Docker-compose install with recommended alternate machine-learning docker for systems that don't support the required tensor flow instruction.  Docker vesrion is 1.43.1

System running docker ubuntu 22.04.01
**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [Y ] I have read thoroughly the README setup and installation instructions.
- [ N] I have included my `docker-compose` file.
- [ N I have included my redacted `.env` file.
- [ Y] I have included information on my machine, and environment.

**To Reproduce**
1. Connect to server with FDROID version of the app. 
2. Notice the notification.  
3. observe that the reported server is all zeros. 

**Expected behavior**

**Screenshots**

**System**
- Phone OS Android
- Server Version: Ubuntu 22.04.01 docker-compose version:  1.43.1
- Mobile App Version: 1.42.0.build.65

**Additional context**

**Comment by alextran1502** [comment]
We cannot help without the required info

**Comment by bo0tzz** [comment]
Please update the app to the latest version

**Comment by deddc23efb** [comment]
> 
I'm using the latest version from Fdroid, 1.42.0  - is this an issue with Fdroid lagging the Immich release?



> We cannot help without the required info
What required info is missing?  I'm using the default docker-compose and env.  Only customization is as stated - machine-learning and configuration of my storage path.

I guess what could be missing is my expectation of correct functioning.  Expected behaviour is that the app shows the server version correctly.   The missing server version makes it difficult to know whether the App is wrong about a server version mismatch OR whether the version of the server is indeed out of date.

**Comment by alextran1502** [comment]
> I'm using the latest version from Fdroid, 1.42.0 - is this an issue with Fdroid lagging the Immich release?

Yes, I believe this is the issue. And we did change the way of querying the version on the server in `1.43` so that is why you see the incorrect server version.

> What required info is missing? I'm using the default docker-compose and env. Only customization is as stated - machine-learning and configuration of my storage path.

Apologize, I didn't read the post very carefully.

**Comment by deddc23efb** [comment]
> > I'm using the latest version from Fdroid, 1.42.0 - is this an issue with Fdroid lagging the Immich release?
> 
> Yes, I believe this is the issue. And we did change the way of querying the version on the server in `1.43` so that is why you see the incorrect server version.
> 
> > What required info is missing? I'm using the default docker-compose and env. Only customization is as stated - machine-learning and configuration of my storage path.
> 
> Apologize, I didn't read the post very carefully.

Sound good, thank you for quick response.  I'm not seeing any obvious functionality issues.  I'll monitor Fdroid and update as soon as they provide a new binary.  I'll double check the behaviour and mark this issue resolved if/when it clear up.

**Comment by notarobot63** [comment]
Hi !
I have the exact samedi issue is there a way to get the latest apk without waiting for Fdroid ?
Thanks

**Comment by deddc23efb** [comment]
I have the same version mismatch however my backups are working fine with my docker install.  I'm curious what functionality is broken?  My docker is running 1.43.1.

**Comment by oscarale-camorlinga** [comment]
For me the android app (1.42.0) only shows local files and with incorrect dates, for example a photo from this year is showing up as from 1970. Opening the web app in my browser shows all of my backed up photos with correct dates.

But just like you mentioned the backup is working, I also have foreground turned on and my photos upload fine, but I just can't see photos I've uploaded using other devices/the web app

**Comment by deddc23efb** [comment]
I see - wrt to your question about downgrading, in theory you could install a 1.42.0 docker by specifying that release in the docker-compose.  Think carefully it about though, I have no idea what DB problems might arise as a result of the any schema changes.

Personally if I absolutely couldn't wait and needed to share photos right now, I'd spin up a parallel older version of the docker as a temporary measure with separate storage.  I'm sure a dev would smack me if they could if they read this, so .... be careful with your data.

**Comment by deddc23efb** [comment]
Fdroid finally updated their version of immich.  I've confirmed that the Server version for my docker shows correctly in the Android Application.  This problem is a non-issue.  Thanks!
