### ISSUE TITLE
[BUG] Unable to update through Portainer to v1.43.0/v1.43.1

### ISSUE THREAD

**Issue by pig-cop** [immich-app/immich#1484]
Until now I always updated flawlessly through Portainer simply updating the stack after changing the TAG values in the docker-compose configuration.
Since v1.43.0 I get the attached error.
I can still downgrade without any issues to the release tag or any of the dev tags before v1.43.0.

![immich_update_error](https://user-images.githubusercontent.com/1793444/215502490-4c573c85-fdae-465b-bbbb-8a2045f95e12.jpg)

**Comment by jrasm91** [comment]
I believe there is a max amount of time portainer waits before showing an error and reporting the deployment failed, but that is often unrelated to the actual deployment. I'd just try again, the new images should now be available locally.

**Comment by pig-cop** [comment]
> Can you provide your docker-compose content?

Sure, here you go:

`version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:${TAG}
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:${TAG}
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: altran1502/immich-machine-learning:${TAG}
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:${TAG}
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - stack.env
    environment:
      # Rename these values for svelte public interface
      - PUBLIC_IMMICH_SERVER_URL=${IMMICH_SERVER_URL}
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:${TAG}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
`

I have an environment variable for the tags.

> I believe there is a max amount of time portainer waits before showing an error and reporting the deployment failed, but that is often unrelated to the actual deployment. I'd just try again, the new images should now be available locally.

I don't if that's the issue, I have already tried many times.

**Comment by jrasm91** [comment]
What tag are you using?

**Comment by jrasm91** [comment]
It's worth point out the tag structure changed. It was `v1.42.0_65-dev`, but it's now `v1.43.1`.

**Comment by pig-cop** [comment]
My bad sorry, I double checked the locally available images and found out that I had some images of a previous failed installation.
I think yesterday at some point I closed accidentally the browser tab before the stack was deployed.

Cleared the failed images and updated successfully using tag ```v1.43.1```, thanks for making me realize my mistake!
