### ISSUE TITLE
Immich web portrait videos play upside down on Chrome (although thumbnail is the right side up)

### ISSUE THREAD

**Issue by akshayrvnkr** [immich-app/immich#14853]
### The bug

Some videos in portrait mode display upside down during playback on Chrome Web (these videos seem to play in HDR mode with full brightness). This issue does not occur on Safari Web, although even this plays the video in HDR. 

Non-HDR-like videos play right side up.

### The OS that Immich Server is running on

Debian 12 (TrueNAS App)

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

1.123.0 build.186

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
TrueNAS internal
```

### Your .env content

```Shell
TrueNAS internal
```

### Reproduction steps

Just uploaded a video from my iPhone 15 pro max using the app (1.123.0 build.186) and viewed the uploaded result on the web.

The problem seems to occur with videos playing in HDR.

Original thumbnail (right side up): 
<img width="163" alt="image" src="https://github.com/user-attachments/assets/720df737-a2e8-42f0-af90-95a696e14617" />
Actual preview and playback is a bit funny:
When it is playing back, it plays in HDR with full brightness upside down, but if I try to take a screenshot of that video playing, it shows up right side up. 
<img width="163" alt="image" src="https://github.com/user-attachments/assets/741980ef-8786-4e45-b103-e2c74c0e6a38" />

macOS: Sequoia 15.0
Chrome: 131.0.6778.141

**Comment by alextran1502** [comment]
Did you modify the transcoding settings? If so, how? 

The issue you describe is often because the user choose not to encode the video

**Comment by Zvirovyi** [comment]
Same issue on the Arc browser (Chromium). And yea, all the video transcoding is disabled (can't see any benefits to transcode videos in already efficient HEVC codec). Issue was introduced with the HDR support update.

**Comment by alextran1502** [comment]
Without transcoding, the browser might not interpretation the metadata correctly, thus the issue you are seeing

**Comment by MahmoudAlyuDeen** [comment]
Same issue here. Must we transcode the video in to play in the correct format? Any alternatives / fixes?

**Comment by alextran1502** [comment]
@MahmoudAlyuDeen yes, the video must be transcoded to play correctly since native support for HEVC video is still meh on browsers

**Comment by pampalini0909** [comment]
Additional info:

Maybe this is a browser dependent problem. I have Mac with MacOS 15.1.1 I have rotation (upside-down) problems in Google Chrome with portrait oriented videos shot on Iphone 15. (Presumably caused by HEVC codec.) But when I use Safari, videos are displayed correctly.

**Comment by ThunderFD** [comment]
Can confirm that it's an issue depending on the browser you use:

Same issue here on Arc Browser (chromium based) with videos (.mov) taken on iPhone (the videos I tested are also HDR).
The videos are not transcoded yet.

.mp4 videos that were sent to me via Whatsapp work fine.

In Arc Browser:
- Thumbnails look correct
- hovering over the thumbnails plays the video upside down
- opening the video plays it upside down

In Safari:
- videos work correctly

In iOS App:
- videos work correctly

**Comment by MahmoudAlyuDeen** [comment]
I recently switched to Firefox, and I was surprised to learn that un-encoded iPhone videos do not play at all, in any orientation 😬

Made me more willing to wait for proper orientation support in Chrome.

**Comment by Villains-Crossing** [comment]
@ThunderFD +1 I am experiencing this same issue with Arc, despite transcoding being enabled. It seems to impact some vertical videos, but only on certain videos captured from certain iOS devices.

**Comment by alextran1502** [comment]
@Villains-Crossing You are probably playing the cache version when the video hasn't finished transcoding, so it plays the original file. Try in incognito or clear the cache on the web for Immich instance
