### ISSUE TITLE
[Tech-Debt] Restify Asset Endpoints

### ISSUE THREAD

**Issue by jrasm91** [immich-app/immich#1485]
We should simplify (and restify) the set of API endpoints related to assets.

All endpoints will return a new header,  indicating total item count, which can be used for display totals. A `HEAD` to the endpoint will return the header without the items.

Search:
- [x] `GET` `/search/<metadata|smart>` - get a list of assets with search/sort filters, including `isFavorite`, created before/after/on, albumId, etc.

Single:
- [x] `POST` `/`: - create an asset (with file upload)
- [x] `GET` `/:id` - get asset

Multiple:
- [x] `POST` `/download/archive` - download a list of asset by ids (as an archive)
- [ ] `POST` `/check` - check a list of asset metadata to determine which ones to upload
- [x] `PUT` `/` -update multiple assets by ids
- [x] `DELETE` `/` -delete multiple assets by ids

Serve:
- [ ] `GET` `/media/thumb?assetId=<id>` - get thumbnail
- [ ] `GET` `/media/original?assetId=<id>` - get thumbnail
- [ ] `GET` `/media/resize?assetId=<id>` - get dynamic/resized version

Remove:
- [x] `GET` `/download/:id`
- [x] `GET` `/download-library`
- [ ] `GET` `/:deviceId`
- [x] `GET` `/count-by-time-bucket`
- [x] `GET` `/count-by-user-id`
- [ ] `POST` `/check`
- [ ] `POST` `/exist`
- [x] `POST` `/shared-link` (move to `/shared`)
- [x] `PATCH` `/shared-link` (move to `/shared`)
- [x] `GET` `/assetById/:assetId` (renamed)
- [x] `GET` `/curated-objects`
- [x] `GET` `/curated-locations`
- [x] `GET` `/search-terms`
- [x] `POST` `/search`

**Comment by agross** [comment]
Will there be at some point a new version of `immich-sdk` to reflect these changes for projects using Immich's API? @alextran1502 Context: https://github.com/agross/immich-duplicates/issues/16#issuecomment-1989279506

**Comment by jrasm91** [comment]
I believe all of the asset endpoints are basically fixed, so closing. (at least CRUD seems to be done)
