### ISSUE TITLE
Stuck processing uploads

### ISSUE THREAD

**Issue by sohail579** [immich-app/immich#1486]
I did a bulk upload and it seems to have gotten stuck processing the pictures is there a way to restart this?  I have tried to restart the containers this has not works

![image](https://user-images.githubusercontent.com/57506081/215529043-b50814c8-ebc6-49c6-aaa1-c3b551368516.png)

**Comment by alextran1502** [comment]
I don't think it is stuck, it just takes sometimes.

If you want to reset it though, you can remove the Redis container and bring it backup

**Comment by bo0tzz** [comment]
Check the logs of your microservices container just to be sure

**Comment by sohail579** [comment]
> Check the logs of your microservices container just to be sure

stupid question inbound.. how do i do that.. im running this in Unraid when i click the container and log it loads then closes immediately so dont see anything

**Comment by alextran1502** [comment]
Got it! then it is probably having some issues. Just bring down everything, then remove the Redis container and bring everything backup, it will clear the queue

**Comment by sohail579** [comment]
> Got it! then it is probably having some issues. Just bring down everything, then remove the Redis container and bring everything backup, it will clear the queue

Thanks Alex its done the trick and all back to normal now
