### ISSUE TITLE
EXIF Updates Made in UI Are Ignored During Downloads

### ISSUE THREAD

**Issue by aviv926** [immich-app/immich#14871]
### The bug

When you download a file through the Immich user interface, it ignores the changes made in the UI, I understand that Immich does not change the original file, but perhaps it is worth adding an option for the user to choose whether to download the original file without the changes through the UI or the file that includes the changes made in the UI ?

Originally reported on Discord
https://discord.com/channels/979116623879368755/994044917355663450/1242591486915117207

### The OS that Immich Server is running on

Immich demo v1.123.0

### Version of Immich Server

Immich demo v1.123.0

### Version of Immich Mobile App

Immich demo v1.123.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Immich demo v1.123.0
```

### Your .env content

```Shell
Immich demo v1.123.0
```

### Reproduction steps

1. Choose a random image
2. Change the date and time/location of the photo
3. Download the image
4. The changes made through the UI do not appear in the downloaded image.

**Comment by mmomjian** [comment]
Feature request, no?

**Comment by aviv926** [comment]
> Feature request, no?
> 
> And/or duplicate of #10592 (I know that one says sidecar, but IMO similar enough to be grouped)

In my opinion, this is more of a bug, because if a user changes the time/location of the files, this is not what he will see when he downloads them on another end

**Comment by mmomjian** [comment]
Immich first principle is to not edit the originals, so I don’t view this as a bug. Maybe someone else can chime in though.

**Comment by alextran1502** [comment]
There should be a companion XMP file get downloaded as well, right?

**Comment by aviv926** [comment]
> There should be a companion XMP file get downloaded as well, right?

Yes or "burn" the data from the XMP file to the downloaded file if the user chose to do so

**Comment by alextran1502** [comment]
I don't think that is what we will do. I suggest we move this to the feature request

**Comment by aviv926** [comment]
> I don't think that is what we will do. I suggest we move this to the feature request

So it can be closed because if it is more suitable to be FR then https://github.com/immich-app/immich/discussions/10592 is pretty much the same as this request.

Although it is worth adding a note to the user that when the files are downloaded by another user, the original EXIF ​​will be available to the person who downloaded the file and not what was edited through the UI interface.

I might find time to send a PR for the documentation of this
