### ISSUE TITLE
Typo in timezone name

### ISSUE THREAD

**Issue by troyane** [immich-app/immich#14872]
### The bug

The proper spelling is Kyiv, not Kiev.

<img width="570" alt="image" src="https://github.com/user-attachments/assets/7292b277-cde6-4220-a0fc-44c57678c9e4" />

### The OS that Immich Server is running on

Synology NAS

### Version of Immich Server

v.1.123.0

### Version of Immich Mobile App

v.1.123.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Doesn't relate.
```

### Your .env content

```Shell
Doesn't relate.
```

### Reproduction steps

1. Pick a photo.
2. Go to Details.
3. Edit Date.
4. Observe a problem in the "Timezone" section.

The proper spelling is Kyiv, not Kiev. So the timezone should be: `Europe/Kyiv (+02:00)`.

### Additional information

You can read more about it here: https://stackoverflow.com/questions/71829570/how-and-where-should-i-suggest-a-rename-of-an-existing-timezone-name

**Comment by mmomjian** [comment]
I am not sure where our timezone data comes from, perhaps someone else will chime in who knows. The issue would have to be raised with the upstream repository, as that data is not from Immich.

**Comment by alextran1502** [comment]
The IANA timezone has the name Europe/Kiev https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

We get the timezone from this method https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/supportedValuesOf

If you think this is wrong, please reach out to the web javascript committee, as we haven't curated the data ourselves for the dropdown options.
