### ISSUE TITLE
[BUG] Web application gallery transition flickers in Firefox

### ISSUE THREAD

**Issue by pig-cop** [immich-app/immich#1489]
When watching photos in the gallery the transition dipping to black between one photo and another flickers in Firefox (version109 x64).
No similar issues in Chronium based browsers.

https://user-images.githubusercontent.com/1793444/215622046-25b78717-654f-4689-b409-8653f56c4171.mp4

**Comment by hu-ximing** [comment]
I have the same issue in Firefox. Workaround is to use the mouse to click the left and right arrows instead of using keyboard navigation.

**Comment by pig-cop** [comment]
I tried that but I still get that flicker, especially when I return to photos I already viewed...

**Comment by alextran1502** [comment]
I believe this issue has been fixed as I cannot reproduce it on Firefox anymore

**Comment by pig-cop** [comment]
I further troubleshooted the issue and found out it was caused by the extension "I don't care about cookies".
If anyone has the same issue just whitelist the Immich page to solve it.
