### ISSUE TITLE
Does not load any pictures for person

### ISSUE THREAD

**Issue by Lukasdotcom** [immich-app/immich#14914]
### The bug

No pictures load on person page when navigating from one person to another in the picture details page.

### The OS that Immich Server is running on

NA happens on demo

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

NA

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA reproducible on demo
```

### Your .env content

```Shell
NA reproducible on demo
```

### Reproduction steps

1. Go to any person's page.
<img width="1790" alt="image" src="https://github.com/user-attachments/assets/46593243-f22e-4459-9825-fab1ac2dc539" />

2. Open the detail panel for some picture.
<img width="1796" alt="image" src="https://github.com/user-attachments/assets/fe8f6367-5b1e-4ba7-99a0-b3149d387cf1" />

3. Click on one of the people to view their pictures and the page will fail to load any pictures.
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/0283fada-d608-4a99-83f0-921d7f3cd883" />

### Additional information

I'm using Firefox just in case this is only reproducible for a specific browser. I also used a private window to prevent a browser extension from being the problem.

**Comment by bo0tzz** [comment]
I can reproduce this. I'm not seeing any errors or clear logs anywhere, but I suspect it's trying to fetch the assets for the wrong personId.

**Comment by DeeprajPandey** [comment]
Cannot reproduce this. Hovering on the picture under `People` in the Info tab highlighted multiple faces. I suspected it would try to search for the wrong person but it worked out fine and the page loaded with the expected photo.

Someone should try it on a hosted instance and check.

**Comment by Lukasdotcom** [comment]
@DeeprajPandey Sorry for the low resolution, but here is a screen recording of these steps reproducing the bug in case I didn't explain them well running on the demo instance.
https://github.com/user-attachments/assets/704a41ac-7973-4efc-89af-adacbaff5ad5

**Comment by ffchung** [comment]
It will only happen for the first time new person you never click.
