### ISSUE TITLE
Android, local photos doesn't show

### ISSUE THREAD

**Issue by alex-quiniou** [immich-app/immich#14940]
### The bug

Sony is storing photos like this:
/storage/emulated/0/DCIM/PHOTOGRAPHY_PRO

And i cannot change the output folder.
I have a XQ-DE54.

### The OS that Immich Server is running on

truesnas scale ElectricEel-24.10.1

### Version of Immich Server

1.123.0

### Version of Immich Mobile App

1.123.0 build 172

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. Open app on Android
2. Go to "bibliothèque" where local folder can be access
3. Then tap on "on this device"
4. It's empty
5. 
![Snapchat-789990071](https://github.com/user-attachments/assets/7cf3cb86-a0f1-404d-a374-0c7024e402ae)

### Relevant log output

```shell
-
```

### Additional information

-

**Comment by bo0tzz** [comment]
At the moment "On this device" only shows albums that you've selected in the backup settings.
