### ISSUE TITLE
Android app crashes when scrolling images in search tab

### ISSUE THREAD

**Issue by agrawalsourav98** [immich-app/immich#14973]
### The bug

Android app crashes when scrolling through images in search tab. Image thumbnails load fine initially but after I click an image and go back I don't see any thumbnails (can only see blurred placeholders) and then the app crashes.

### The OS that Immich Server is running on

Truenas Scale Dragonfish 24.04.2.5

### Version of Immich Server

v1.119.1

### Version of Immich Mobile App

v1.123.0.build.172

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Don't have a docker compose file
```

### Your .env content

```Shell
Don't have a .env file
```

### Reproduction steps

1. Search for anything in the android app
2. Click on an image
3. Go back to the previous screen
4. The app crashes after some time

**Comment by alextran1502** [comment]
Can you please update the server to the latest version and see if it helps with the issue?

**Comment by agrawalsourav98** [comment]
> Can you please update the server to the latest version and see if it helps with the issue?

I have to wait for the upstream charts to update, would test it out

**Comment by bo0tzz** [comment]
Closing this for now, let's reopen if it still happens after updating.
