### ISSUE TITLE
DJI photos can't be synced

### ISSUE THREAD

**Issue by EscolarProgramming** [immich-app/immich#14988]
### The bug

Images created via my DJI drone cannot be synchronized. I have already found the note in the two reports #3351 and #2719 that files without a file extension cannot be synchronized, but the image has an extension. When I look at it with the app "FileBrowser", it ends in .jpeg, but in the Immich app itself it is displayed without an extension. I have decided to open a new bug report as the other two are already closed

### The OS that Immich Server is running on

Alpine Linux v3.20.3

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

1.123.0 build.186

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Installed via https://github.com/alexbelgium/hassio-addons/tree/master/immich
```

### Your .env content

```Shell
Installed via https://github.com/alexbelgium/hassio-addons/tree/master/immich
```

### Reproduction steps

1. Take a picture with the DJI drone
2. Sync the picture with the DJI app to you phone
3. Try to upload the picture via Immich

### Relevant log output

```shell
[Nest] 1149  - 12/30/2024, 12:38:54 PM   ERROR [Api:AssetMediaService~hp9252gn] Unsupported file type dji_fly_20230508_190218_228_1683565387805_photo_optimized
```

**Comment by bo0tzz** [comment]
Please share more detail, like what the file/filename looks like on your phone and ideally the actual file in a .zip.

**Comment by mmomjian** [comment]
@bo0tzz this looks like an exact duplicate of #2719 (closed) , some apps seem to infer or guess an extension but if it appears in Immich with no ext the decision was this was unsupported.

**Comment by bo0tzz** [comment]
Yes indeed, I'd forgotten about the part where apps make up a file extension. Thanks!

**Comment by EscolarProgramming** [comment]
Here's the screenshot of the photos app:
![IMG_7177](https://github.com/user-attachments/assets/bde1a840-526e-4382-9965-619aac3653c9)

And here's the screenshot of the FileBrowser app:
![IMG_7178](https://github.com/user-attachments/assets/e7723098-2937-408f-accd-9f1e13300150)

And here's the link to the file itself: 
[dji_fly_20230508_190218_228_1683565387805_photo_optimized.zip](https://github.com/user-attachments/files/18274521/dji_fly_20230508_190218_228_1683565387805_photo_optimized.zip)

**Comment by EscolarProgramming** [comment]
If you don't want to implement file type detection, could you implement something so that such files are simply skipped during the backup? This file is currently blocking my backup because it always gets stuck between 4% and 25% and does not process the rest of the batch

**Comment by mmomjian** [comment]
#13107 , @bo0tzz that one might not be a dupe of #2892 if it’s actually freezing/blocking on future uploads. Probably is an issue vs the FR in 2892

**Comment by nesha14586** [comment]
Is there any solution to this? I too have dji drone photos that are breaking the upload.

**Comment by adjmcwadge** [comment]
i am having the same issue with my dji photos and its blocking the last 2000 from completing.

**Comment by alexlambson** [comment]
This bug prevents backups from finishing. I'll just keep getting notifications about "immich is backing up your files" over and over. 

https://github.com/immich-app/immich/discussions/13798
