### ISSUE TITLE
[Feature]: iOS support for earlier versions of Apple devices pre-iOS13

### ISSUE THREAD

**Issue by deddc23efb** [immich-app/immich#1509]
### Feature detail

This is probably a long shot, but I'd like to use immich on an old iPhone 6.  It can't be upgraded past iOS12 and immich apparently requires iOS 13 or greater.  Would be nice if there could be a legacy build for those of us that don't upgrade our hardware.

### Platform

Mobile App

**Comment by zackpollard** [comment]
Hey, I'm sure this isn't what you want to hear but it's very unlikely we do this. A lot of our dependencies likely won't work properly with the older iOS version, if anything we are likely to move our target to a newer version of iOS. iOS 13, 14 and 15 support hardware all the way down to the iPhone 6S which is 7 years old at this point.

**Comment by deddc23efb** [comment]
Thanks, totally understand.

**Comment by BackMountainDevil** [comment]
iPhone se ios12.4 not work, too. And I understand now
