### ISSUE TITLE
[QUESTION] Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Atemu** [immich-app/immich#151]
**Describe the bug**

```
docker-immich_microservices-1  | 
docker-immich_microservices-1  | > nest_microservices@0.0.1 prebuild
docker-immich_microservices-1  | > rimraf dist
docker-immich_microservices-1  | 
docker-immich_microservices-1  | 
docker-immich_microservices-1  | > nest_microservices@0.0.1 build
docker-immich_microservices-1  | > nest build
docker-immich_microservices-1  | 
docker-immich_microservices-1  | 
docker-immich_microservices-1  | > nest_microservices@0.0.1 start:prod
docker-immich_microservices-1  | > node dist/main
docker-immich_microservices-1  | 
docker-immich_microservices-1  | Illegal instruction (core dumped)
docker-immich_microservices-1 exited with code 132
```

I am running this on a machine with a low-power Celeron CPU that does not have AVX instruction support, so that seems like a likely cause.  
I assume this is the ML stuff? Is it possible to disable AVX instructions for these? Could I pass through the intel iGPU to do this on instead?

**Comment by Atemu** [comment]
Ah, should've read the README to the end...

It'd be nice if immich-microservices could be run on non-AVX CPUs and/or iGPUs instead though.

**Comment by alextran1502** [comment]
Hi, unfortunately, it is TensorFlow that uses the AVX instruction. The only workaround is to build it from the source and disable it, the distributed node.js library that comes with Immich has it enabled. :/

**Comment by Atemu** [comment]
I see.

Can TF be made to use the iGPU? Perhaps it doesn't use AVX when using a GPU.

**Comment by alextran1502** [comment]
I have an experimental dockerfile that uses GPU but haven't actually gotten a chance to fully work on that to incorporate into the code. I will keep this issue opened and updated when I have more info

**Comment by sbkg0002** [comment]
@alextran1502 if there is a way I can help build or test, pm me.

**Comment by sbkg0002** [comment]
Which nodejs package has the AVX dependency? Is there a non-avx version of the pkg?
Im looking into building a iGPU multi-stage dockerfile to get this going!

**Comment by dorianim** [comment]
This might help to build tfjs-node without avx:
https://peterbabic.dev/blog/install-tfjs-node-from-source/

**Comment by JVT038** [comment]
Is there any update on this? I have a NAS with Intel Celeron J3455 that gives the same error, and now I can't run the machine learning container, causing more errors.

**Comment by bertmelis** [comment]
See #300 
I run ML on a j4105

**Comment by alextran1502** [comment]
Closing as this issue is now an information thread.
