### ISSUE TITLE
[BUG] Images in landscape orientation have poor resolution in web view

### ISSUE THREAD

**Issue by rainerwein** [immich-app/immich#1510]
**Describe the bug**
Generated images in landscape orientation have poor resolution compared to images in portrait orientation

**To Reproduce**
1. Upload image once in landscape and once in portrait resolution (original resolution in my case 4205x2803, resp. 2803x4205)
2. Click on image to see large view
3. The landscape version looks pixelated and only has a resolution of 1440x960
4. The portrait version looks sharper and has a resolution of 1440x2160

**Expected behavior**
Images should have decent resolution for screen regardless of their orientation

**Screenshots**
![grafik](https://user-images.githubusercontent.com/31047131/216174361-9f60bf8d-08c0-45e0-91f1-d64bd49ead03.png)
Image on the left looks worse and pixelated even though the uploaded image had the same resolution
![grafik](https://user-images.githubusercontent.com/31047131/216175312-8e41ef07-51f1-408f-a320-9a2db5d86e1f.png)
![grafik](https://user-images.githubusercontent.com/31047131/216175337-e11afab8-2fdf-44d4-9638-221bc678702c.png)

**System**
- Browser: Firefox
- Server Version: `v1.43.1`

**Additional Information**
I only chose the same image for demonstration purposes. Resolution is worse for all landscape images compared to portrait images. This also isn't just an effect of the landscape image taking up more screen real estate as seen by the different resolution of the generated "preview" image

**Comment by alextran1502** [comment]
The landscape version resolution is `1440x960` while the portrait version is `1440x2160`. The total pixel is more, so that is probably why

**Comment by rainerwein** [comment]
Yes, that's the bug I'm reporting. The original images have the same number of pixels but the preview that Immich generates produces different resolutions.

**Comment by rainerwein** [comment]
This is also noticeable on the demo page, where all landscape images seem to have a low resolution, but when downloaded look totally fine. Of course the effect is less severe for screen resolutions of 1080p or less, but at 1440p it's very apparent.
