### ISSUE TITLE
[BUG] closing the image selection window accidentally opens up an image to full screen

### ISSUE THREAD

**Issue by Shlokp** [immich-app/immich#1518]
When closing the "select images" window, window closes but also opens up into the image selected. 

https://cdn.discordapp.com/attachments/994044917355663450/1070650293664096256/screen-20230202-1001463.mp4

**System**
- Phone OS: Pixel 7 Pro - Android 13
- Server Version: 1.44 (latest)
- Mobile App Version: 1.43 build 66 (latest)

**Comment by bo0tzz** [comment]
I could reproduce this on the latest app release (1.44.0_67). It seems to happen with local-only assets, with a local asset being opened when backing out of any selection. 
Interestingly, after deleting the local asset that was being opened (but still having other local-only assets), I cannot reproduce it anymore.
