### ISSUE TITLE
[Feature]: Multiselect add to favorite

### ISSUE THREAD

**Issue by martyfuhry** [immich-app/immich#1549]
### Feature detail

While selecting multiple assets in the timeline grid, you should be able to add all of them to favorites from the bottom panel:

![image](https://user-images.githubusercontent.com/100457/216781732-306d429e-4a32-4145-9a93-2bb0a1c161dd.png)

### Platform

Mobile App

**Comment by alextran1502** [comment]
Implemented in #1558
