### ISSUE TITLE
[Feature]: Dynamically generated collections, e.g., "one year ago today" to view in the mobile apps / web

### ISSUE THREAD

**Issue by martyfuhry** [immich-app/immich#1559]
### Feature detail

Other photo apps have several suggestions of generated image collections you may be interested in viewing. For example, one collection my wife and I really enjoy from other photo apps is images taken one year ago today. These typically appear as a card at the top of the timeline, and could be dismissable or user-configurable to disable.

### Platform

Mobile App

**Comment by bo0tzz** [comment]
If feasible, it would probably be best to implement this as a server endpoint so any client can do this consistently without duplicating the code that picks the assets.

**Comment by EnochPrime** [comment]
Duplicate of #1316?

**Comment by martyfuhry** [comment]
> Duplicate of #1316?

Woops! Sure looks similar. The only thing I can think of is that I would like to see other dynamic collections, as well as the "X years ago" collections, but that can be brought up separately. Thank you @EnochPrime!
