### ISSUE TITLE
[BUG] Missing thumbnails (even jobs has run multiple times)

### ISSUE THREAD

**Issue by MichaelBui** [immich-app/immich#1565]
I've just bulk-uploaded my photos via the CLI but I don't see them on the clients (web, mobile) even though the files are created on the server side

**Describe the bug**
After doing some checks, I realized that there are no thumbnails for those files even though I've tried to run the `GENERATE THUMBNAILS` job multiple times (wait until it is completed). Only those 6 files that have thumbnails can appear in the client UI:
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/1146708/216889752-6a9371e6-a732-4e81-89f6-1b18df93d6f4.png">

Not sure what was missing and caused that issue, is there any cli or logs to debug?

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
- Phone OS [iOS, Android]: `<version>`
- Server Version: `1.42.0`
- Mobile App Version: `<version>`

**Additional context**

**Comment by alextran1502** [comment]
Those are I believe is LivePhotos motion part, please confirm those files have column `isVisible` as `false.

**Comment by MichaelBui** [comment]
All files are Visible:
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/1146708/216891095-f3c74998-840d-435c-9c9f-f22410b17f48.png">

Upload happened at 12:16pm (SGT):
![image](https://user-images.githubusercontent.com/1146708/216891738-8ead153c-d57c-4a5e-93cc-79deec076eb5.png)

Logs from the pod around that time (seems not related to the uploaded files, the ones in `2014/03-10` are from previous run):
<img width="720" alt="image" src="https://user-images.githubusercontent.com/1146708/216892002-9f10e2ce-dfd7-4277-86c6-3f85337d7224.png">

In the pod, `/var/logs/` is empty. Not sure where else I can check...

**Comment by alextran1502** [comment]
Can you check the log of `microservice` container? it handles thumbnail generation

**Comment by MichaelBui** [comment]
It has this error message at the upload time & repeated every time with the job: `Error: Input file is missing`
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1146708/216894419-e074013a-757b-452a-833f-303d0ac1bb3c.png">

**Comment by alextran1502** [comment]
Hmm interesting, I suspect the mount has a problem. What happens if you drop that file to upload from the web?

**Comment by MichaelBui** [comment]
@alextran1502 you’re right! I’ve just found out that for some reason the Helm chart for TrueNAS (TrueCharts) support additional host mount only for the main container (`immich`), not `microservices` so it can’t access the original files to generate the thumbnails. After I re-organize the structure with no additional mount, the thumbnail generator job has run fine & I can see the photos on the client UI.
However, should the UI should the assets with blank thumbnails instead of not showing the assets at all?

**Comment by alextran1502** [comment]
Not showing at all would probably better user experience imo 😀
