### ISSUE TITLE
[Feature]: ability to multiselect via shift key

### ISSUE THREAD

**Issue by bbieberle** [immich-app/immich#1580]
### Feature detail

Hi all, 

huge thanks for developing this application! Appreciate it and i am looking into supporting it myself!

Feature request:
It would be very useful to be able to seletc multiple photos by holding down the shift-key. Similar to how it works in any file browser. It should select every image in between the last time selected and the clicked image. 

Kind regards!
Benedikt

### Platform

Web

**Comment by bo0tzz** [comment]
Duplicate of #709

**Comment by bbieberle** [comment]
Sorry, i searched for this issue but did not find it

**Comment by SGEthan** [comment]
Hi, I just found that in a specific people page, this doesn't work. Do you have any ideas of fixing that? It does help a lot when I want to share all photos of someone with themselves
