### ISSUE TITLE
[Feature]: Support IPv6

### ISSUE THREAD

**Issue by alextran1502** [immich-app/immich#1703]
### Discussed in https://github.com/immich-app/immich/discussions/1610

<div type='discussions-op-text'>

<sup>Originally posted by **pr0ton11** February  7, 2023</sup>
### Feature detail

Hi

I am using the Immich Helm Chart in my IPv6 only Kubernetes cluster. Unfortunatly, Immich does not seem to listen to IPv6 at all, making it currently unusable for me.

Is there a parameter where I could tell Immich to bind / listen to an IPv6 address instead?

Thanks you

### Platform

Server</div>

**Comment by samip5** [comment]
I don't think this is complete as the mobile app more than likely has issues if it's IPv6-only.

My fix is only part of the whole thing.

**Comment by pr0ton11** [comment]
My ingress controller terminates IPv4 and IPv6. Only the pod addresses are IPv6, so this might already be enough.

**Comment by pr0ton11** [comment]
Still doesn't work:
```
kubectl -n ms logs immich-pic-web-6b74db4679-2bfbh
Listening on 0.0.0.0:3000
```

**Comment by pr0ton11** [comment]
@alextran1502 can we reopen this?

**Comment by samip5** [comment]
@pr0ton11 Can you please check `netstat -tulpn` inside the container?
