### ISSUE TITLE
[BUG] harden the exif extraction process more

### ISSUE THREAD

**Issue by Snuupy** [immich-app/immich#1705]
### The bug

https://discord.com/channels/979116623879368755/994044917355663450/1073126252417912843

> parse any integer so that if this case happen it will default to 0 so other info can still be inserted

symptom: file contains EXIF data (possibly invalid), no EXIF data at all is displayed within immich

fix should:
- display exif data even if other fields are not valid
- add better logs there to make it more obvious why it failed

### Version of Immich Server

v1.45

### Version of Immich Mobile App

v1.45

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Reproduction steps

1. grab file on discord
2. import into immich
3. see that no exif data is shown
4. open same file in irfanview, press `e`, see that exif data is shown

**Comment by uhthomas** [comment]
Will be resolved by #2908.

**Comment by bo0tzz** [comment]
Fixed by #2908
