### ISSUE TITLE
[BUG] Can't run immich reverse proxy with IPv6 disabled

### ISSUE THREAD

**Issue by zackpollard** [immich-app/immich#1723]
### The bug

The reverse proxy nginx container will not run if the host has IPv6 disabled. We can solve this by either having an environment variable to disable IPv6 support, or just try to run with IPv6 and if that fails, try IPv4.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

1.46

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Disable IPv6 on host machine
2. Try to run immich 1.46
3. Nginx container will fail
```

**Comment by pr0ton11** [comment]
This is a regression from #1703

We need a way to configure this without interfering with no IPv6 setups. Also the bug is still present.
I would argue for a way to change the listen parameter to use either 0.0.0.0 (default) or [::] depending on an environment variable.

**Comment by alextran1502** [comment]
@lhhel9l3 this is part or experimentation and development as we don't have any data of how many people explicit disable IPv6 in their environment. And we want to make IPv6 works for people that need it as well 😀. Now we figure that we have more cases that disable the use of IPv6 so it is time to fix that. I hope it is not too much of a hassle to stay on 1.45 right now

**Comment by samip5** [comment]
@lhhel9l3 You're deploying in a docker-compose setup with the default docker-compose network config, right? If so, yes that has IPv6 disabled as does Docker daemon's default config.

**Comment by samip5** [comment]
> I assume this is because ipv6 is disabled via kernel boot options.

Why do people do that?
