### ISSUE TITLE
[BUG] Compile error: 'Badge' imported twice

### ISSUE THREAD

**Issue by tbleiker** [immich-app/immich#1729]
### The bug

When debugging the mobile app with VSCode, the following error occurs:

```
ERROR: lib/modules/home/ui/home_page_app_bar.dart:119:21: Error: 'Badge' is imported from both 'package:badges/src/badge.dart' and 'package:flutter/src/material/badge.dart'.
home_page_app_bar.dart:119
ERROR:                   : Badge(
ERROR:                     ^^^^^
ERROR: Target kernel_snapshot failed: Exception
Exception: Build process failed
```

I solved it by adding `hide Badge` to the third line of `lib/modules/home/ui/home_page_app_bar.dart`:

```
import 'package:flutter/material.dart' hide Badge;
```

### The OS that Immich Server is running on

Linux, Arch (build environment)

### Version of Immich Server

-

### Version of Immich Mobile App

ad93733 (newest commit)

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Pull repo
2. Open folder "mobile" in VSCode
3. Run debug
```

**Comment by alextran1502** [comment]
We are still on version 3.3.10 of Flutter. I assume you are using Flutter 3.7? I am working on a PR to move to 3.7, it might be merged today

**Comment by tbleiker** [comment]
I see. Yes, I am using 3.7.1.

**Comment by tbleiker** [comment]
Fixed with the commit 09ab06a. @alextran1502 thx for all your work!

**Comment by kiyasser** [comment]
thank you

**Comment by MohamedWageh1** [comment]
i face the same problem but i hadn't import any package of them . what should i do?
