### ISSUE TITLE
[Feature]: (mobile) Display explanation on favorites page if there are no favorited assets yet

### ISSUE THREAD

**Issue by matthinc** [immich-app/immich#1802]
![Screenshot 2023-02-20 at 08 56 28](https://user-images.githubusercontent.com/6898797/220045960-4874b232-0e54-4879-854a-886f4db0497d.png)

Like on web

**Comment by miikkuu** [comment]
@matthinc what explanation particularly?

**Comment by matthinc** [comment]
> @matthinc what explanation particularly?

Similar to how it's done in web (see screenshot). Does not have to be exactly the same. Just something so that users understand why they see an empty page.

**Comment by jrasm91** [comment]
Maybe another way of saying it - display a placeholder when there are no empty images. In the web there are placeholders for no albums, no favorites, etc. The placeholder should make it clear that there are "no items here".
