### ISSUE TITLE
[BUG] iOS background backup does not immediately pick up foreground process after app exit

### ISSUE THREAD

**Issue by klejejs** [immich-app/immich#1824]
### The bug

iOS app cancels foreground upload if app is exited even for a few seconds and does not do it in background.
This is annoying, especially if trying to upload on mobile data.

### The OS that Immich Server is running on

Ubuntu 22

### Version of Immich Server

v1.48.0

### Version of Immich Mobile App

v1.48.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Unrelated, can provide if needed
```

### Your .env content

```Shell
Unrelated, can provide if needed
```

### Reproduction steps

```bash
1. Open iOS app
2. Start foreground upload for e.g. a long video
3. Switch to another app for 3 seconds
4. Open Immich again to see that the video upload has restarted
```

**Comment by alextran1502** [comment]
This is not the intended usage. Foreground backup and background backup operate independently.
