### ISSUE TITLE
[BUG] Uncaught SyntaxError: illegal character U+009E

### ISSUE THREAD

**Issue by zhum** [immich-app/immich#1852]
### The bug

In Firefox I get this error in the console. I cannot open albums, some of pictures are not loaded.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

Demo server

### Version of Immich Mobile App

none

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
none
```

### Your .env content

```Shell
none
```

### Reproduction steps

```bash
1. Use Firefox 110.0, open the demo server.
2. Login using demo credentials
3. Open developer console (Ctrl-Shift-C e.g.)
4. See the error from the bug title.

If you try to open albums or an image, it don't work.
```

**Comment by bo0tzz** [comment]
I can't reproduce this. Can you try clearing all the browser caches etc?

**Comment by zhum** [comment]
That helped!
