### ISSUE TITLE
[BUG] Show Admin name in server stats

### ISSUE THREAD

**Issue by jrasm91** [immich-app/immich#1857]
### The bug

The admin user's name should be displayed in the usage table (instead of the hard coded "Admin").

![image](https://user-images.githubusercontent.com/4334196/221232012-493ef030-f79e-459b-9413-b6cb4969cd9b.png)

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

**Comment by jrasm91** [comment]
That won't show soft deleted users, which I assume it currently shows now. The `isAll` flag is misleading because it's really "get users to show on the admin page", which is actually "get all users including deleted users, but exclude me". We should probably not exclude the user ever IMO and the flag should control the `withDeleted` property.

![image](https://user-images.githubusercontent.com/4334196/221296844-5ec9918e-d22e-4b13-9e33-ed75623388cc.png)

**Comment by martabal** [comment]
Wouldn't it better to have a new `withDeleted` parameter ?

**Comment by jrasm91** [comment]
That'd be fine, but then there is no need for isAll.

**Comment by jrasm91** [comment]
We could add a new one just for deleted.

My personal opinion is that using a query param to exclude your id is not very restful and that should be changed.
