### ISSUE TITLE
Video keeps upload and fail

### ISSUE THREAD

**Issue by NeleB54Gold** [immich-app/immich#1872]
### The bug

A video that is 179MB keeps failing on upload and retry everytime

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.49.0

### Version of Immich Mobile App

v1.49.0

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I have not access to the Server now
```

### Your .env content

```Shell
Same here
```

### Reproduction steps

```bash
1. Try to upload any video over 170MB
2. Enable auto-backup
```

### Additional information

None

**Comment by alextran1502** [comment]
Can you describe the action of
1. Deleting from Immich Server
2. Deleting the media file from the gallery 

I am not clear what are you trying to accomplish

**Comment by NeleB54Gold** [comment]
> Can you describe the action of
> 1. Deleting from Immich Server
> 2. Deleting the media file from the gallery 
> 
> I am not clear what are you trying to accomplish

1. Deleted from the Immich App 
2. Deleted from the Gallery App

Summary: I deleted the video file while it was uploading to Immich Server, and now it keeps backing up the "broken" file, so the app reads until it loads and then fails.

**Comment by alextran1502** [comment]
Delete and reinstall the app doesn't help?

**Comment by NeleB54Gold** [comment]
> Delete and reinstall the app doesn't help?

![Screenshot_2023-02-25-21-23-24-473_app.alextran.immich.jpg](https://user-images.githubusercontent.com/51356760/221378112-4bf4c8b5-2f05-4710-aa2c-13aa93aa692c.jpg)

Nope, it's still there

**Comment by alextran1502** [comment]
Can you scroll down and confirm that the file it is trying is upload is the video?

**Comment by NeleB54Gold** [comment]
> Can you scroll down and confirm that the file it is trying is upload is the video? 

![Screenshot_2023-02-25-23-27-13-138_app.alextran.immich.jpg](https://user-images.githubusercontent.com/51356760/221382389-f1a92413-13c8-4da6-88b0-8a1948970692.jpg)

Yes, it's always the same video, when starts in background I can confirm by the siza, always 170MB

**Comment by alextran1502** [comment]
Can you click on the photo icon logo next to the upload file? It will show you the thumbnail of the video. Can you help confirm that it is not existed in the gallery?

**Comment by NeleB54Gold** [comment]
> Can you click on the photo icon logo next to the upload file? It will show you the thumbnail of the video. Can you help confirm that it is not existed in the gallery?

I'm sorry, you're right, the video is another, but there is a limit on the upload?
This other video is 179MB and keeps failing at less than 10%

**Comment by alextran1502** [comment]
If you are using dns, and maybe cloud flare tunnel there is a known limitation of 100MB upload. Also it could be your reverse proxy too, if you are using Nginx, please check max body size setting

**Comment by NeleB54Gold** [comment]
> If you are using dns, and maybe cloud flare tunnel there is a known limitation of 100MB upload. Also it could be your reverse proxy too, if you are using Nginx, please check max body size setting

I use ArGuard as dns, and cloudflare + nginx on my home server, if I use the same WiFi of the Server the upload is limited anyway by cloudflare?

**Comment by alextran1502** [comment]
If you are using your local ip, there would be no limitation. 

Then this is a bug of upload the last file

**Comment by alextran1502** [comment]
I will close this issue as this is probably related to proxy server setup and configuration.

**Comment by osresearch** [comment]
I ran into this same issue due to a `client_max_body_size 50M;` in the nginx proxy for the server.  This caused the upload of videos larger than this size to fail silently and constantly retry.  Increasing the limit to half a gigabyte allowed the existing videos to sync, but this just pushes the problem off till later --  if a larger video is ever set to be sync'ed then it will fail again and cause the constant retries.
