### ISSUE TITLE
ENOSYS: function not implemented, link

### ISSUE THREAD

**Issue by nicolopozzato** [immich-app/immich#1899]
Hi, i setup immich on a arm vps on oracle, with ocamel fuse google drive, but I have the same error:

immich_server | [Nest] 1  - 03/01/2023, 12:47:57 AM ERROR [StorageService] Error: ENOSYS: function not implemented, link 'upload/85ff3fb7/original/WEB/408963f5-45f7-40e8-960c-79f36116e086.jpeg' -> 'upload/85ff3fb7/2023/2023-02-25/originalName.jpeg'

So in the folder 2023-02-25 the image is not present but it's only in the original/WEB/....

_Originally posted by @nicolopozzato in https://github.com/immich-app/immich/discussions/1683#discussioncomment-5161014_
      

I have to read the code but with this error I think that the original image stay in the original/WEB/ (in this case) and only a softlink is created inside the 2023/.... so if a user change the folder structure the original image aren't inside that structure, but only a slink. 

This create a bug, that if I download that photos from the web interface i get a file with the id and not the original name that I have uploaded.
Second, I see that I'm not the only one that would like to use a "remote" space like in my case a team drive or other mounted directory on the server... It's a thing that we can think about for a fix? (at 2am i'm thinking of making a copy of the file instead of a softlink, but that use a lot of space specially with a video)

**Comment by alextran1502** [comment]
Hello, at the moment the method you are using to mount the storage drive has not been officially tested or supported by the application so we can't help you here
