### ISSUE TITLE
[BUG] Downloading image to mobile device that has been uploaded with CLI results in duplicates.

### ISSUE THREAD

**Issue by florihupf** [immich-app/immich#1946]
### The bug

Hi there,

maybe not the most common workflow, but never the less would be great to fix.

Repro:

a) Fresh install of Immich
b) Upload tons of pictures to the server using CLI tool (works great).
c) Install mobile app (here iOS)
d) Browse photo selection and download one to mobile device (say you want to use it as background image, etc).
e) Observe that mobile app will instantly detect this image and re-uploads it as a duplicate to the server.

Upon closer inspection what I can see if that the filename endings differ:

Orig.: IMG_6502.jpg
Dupe: IMG_6502.jpg.JPG

On the plus: Deleting the duplicate will only delete the duplicate and not both. 👍 

Would be a great fix, if easy.

### The OS that Immich Server is running on

Truenas Scale

### Version of Immich Server

v1.51.0

### Version of Immich Mobile App

v1.51.0

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Stock.
```

### Your .env content

```Shell
Stock.
```

### Reproduction steps

```bash
See above.
```

**Comment by bo0tzz** [comment]
> mobile app will instantly detect this image and re-uploads it as a duplicate to the server.

Does the image actually show up duplicated in the (web) UI after this?

**Comment by florihupf** [comment]
Also, let's say for simplicity, the iOS photo roll is empty when doing c) from the repro steps.

**Comment by florihupf** [comment]
Yes, it also shows duplicated on the web.

**Comment by bo0tzz** [comment]
That's very strange, since we have hash-based deduplication so it should be detected that it's the same file. Is there a chance that it's being picked up by iCloud photos or such and being compressed or otherwise altered?

**Comment by florihupf** [comment]
Don't think so, it happens right away.  Also I have iClouds photos disabled.

**Comment by florihupf** [comment]
Is there maybe a difference between how the hashes are computed for CLI uploads and mobile assets?

**Comment by jrasm91** [comment]
Hashes are computed on the server regardless of what client uploads them.

**Comment by florihupf** [comment]
Does the file name go into the hash? Maybe downloading an image modifies it? On 5. Mar 2023, at 17:35, Jason Rasmussen ***@***.***> wrote:﻿
Hashes are computed on the server regardless of what client uploads them.

**Comment by klejejs** [comment]
I can confirm, I have a similar issue.

Steps to reproduce:
* Download images to PC and upload them to the web with drag-n-drop
* Download the same images from the same source to iOS and add them to the library
* iOS app uploads the images again and there are duplicates in the Immich library
* 
I did notice that GPhotos also has the same issue, so I wonder if the hash or something else about the images actually does change. 🤔 
I also don't use iCloud if that can impact anything.

**Comment by klejejs** [comment]
@Dilanwizzy isn't that the case only if you have iCloud photos enabled? I do not upload photos to iCloud so I don't have that option available, but I still have the the issue.

**Comment by Dilanwizzy** [comment]
@klejejs The uploaded pictures have different sizes. I have just done what you explained and each time the size is different. The size difference is usually by 1 or 2 kb. Here is a file continuously downloaded.

3,292,209
3,291,980
3,291,298
3,292,438

File size each time is different. I have also seen it be the same and the image does not get uploaded.

**Comment by jrasm91** [comment]
Instead of looking at sizes it would be best to do a sha1 hash.

You should be able to verify the hash at each step and it should be the same at each step. Immich should not modify it at all, ever.

- Take a picture, verify sha1 hash
- Upload the picture to immich, verify sha1 of file in upload directory
- Download the picture using "download" feature in immich web, verify sha1 of file is the same
- Download the picture from the mobile app, verify the sha1 of the file is the same
- Upload the picture again, verify it's a duplicate and not processed

If the sha1 changes at any step, that would be a problem. It might be related to iOS cloud stuff though.

**Comment by Dilanwizzy** [comment]
I used sha1 hash to verify and the file each time the hash is different. The different sizes show that maybe IOS is doing something with the files. 

The same issue also happens on Google Photos

**Comment by jrasm91** [comment]
Do you have some files you can upload that I can inspect? Ideally, an original and then a download-and-modified version.

**Comment by Dilanwizzy** [comment]
So, it seems like the way google handles this is by appending the word original to the file. And then treating the file on the server and the one downloaded as 1 file. Currently, immich would treat them as 2 separate images, with one being uploaded on the server and the other showing as not uploaded.

**Comment by florihupf** [comment]
Yeah, also quick note that I have iCloud disabled and thus the option mentioned is not available for me.

**Comment by jrasm91** [comment]
Can somebody share/upload a sample image (before and after) that I can investigate with? Otherwise, it is hard to know what is going on.

**Comment by florihupf** [comment]
Ok, will see to it.

**Comment by florihupf** [comment]
[immich.zip](https://github.com/immich-app/immich/files/11036921/immich.zip)

Here is a zip with a picture uploaded via CLI on Feb/23.  I just downloaded onto my phone on Mar/22 and it got uploaded right away as a duplicate.  I downloaded them both using the web gui.  Note that the zip contains two files with the same name.

HTH and thanks for taking a peek!

**Comment by colin715** [comment]
I'm seeing similar behavior on Android. My wife (also Android) and I share a user account so that we can see each other's pictures. If I download an image to my device that my wife took, then I end up with a duplicate photo. And the original photo still shows up as not on my device.

**Comment by alextran1502** [comment]
Thank you all for the report, we are hoping to address this issue in the next release or so

**Comment by t-shock** [comment]
I set ups Immich couple days ago and I’m facing the same issue with my iPhone

**Comment by florihupf** [comment]
Wohoooooooooooo 💯 🥇

**Comment by uhthomas** [comment]
@florihupf You reported your server and app versions as `v1.61.1`, which isn't a valid release. The current release is `v1.61.0`. Would you mind checking both are up to date?

**Comment by florihupf** [comment]
Yeah, my bad. I am up to date with v1.61.0.  Typo on the last digit.

**Comment by florihupf** [comment]
I can repro with more detail.

How do I enable advanced error reporting? In the iOS Immich app, I see Log Level: Info and a trouble shooting toogle.  What settings should apply?

As for the repro steps:

a) Just click download on any picture that is not downloaded to the phone yet (but uploaded via CLI to the server).
b) Upon completion of the download, there will be two images in the mobile app (identical looks) and the second image will be uploaded to the server, creating a duplicate there as well (after a delay).

HTH

**Comment by fyfrey** [comment]
Enable trouble shooting. Then when clicking the info icon in the full screen view, you see advanced/raw info about an asset.

I bet the checksums are different. But I don't know yet why.

**Comment by paniman** [comment]
One solution for the slightly adjusted image to detect as duplicate could be to use phash instead of a another hash algorithm.
Source: https://www.phash.org

**Comment by florihupf** [comment]
Hi there,

just tried this again and it works now.  Lets close this out.  Thanks!
