### ISSUE TITLE
[BUG] Launching Immich (Android 13) only gets as far as showing the flower

### ISSUE THREAD

**Issue by Linecutterx** [immich-app/immich#2005]
### The bug

Immich never gets as far as trying to reach a server.

VPN based firewall has most things restrained (although totally unblocking Immich makes no difference).
There are no firewall entries for Immich.

### The OS that Immich Server is running on

Android 13 (S23U, latest OS update).

### Version of Immich Server

v1.50.1

### Version of Immich Mobile App

1.50.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Contact with the server is never made. Runs fine via web access
```

### Your .env content

```Shell
Contact with the server is never made. Runs fine via web access
```

### Reproduction steps

```bash
1. Launch Immich on the phone
2.
3.
...
```

### Additional information

No obvious activity after the splash screen.
Clearing data (cache is always empty) doesn't help.
The lack of firewall entries (or progress) suggests that this is an early event in the launching process.
No obvious dependencies that could be missing, as far as I can tell (I've debloated some of the redundant Samsung/google stuff, but nothing I'd expect to be needed to create a UI. Other apps work fine)

**Comment by alextran1502** [comment]
Where did you install the application? Google Playstore or from F-Droid?

**Comment by Linecutterx** [comment]
This is the f-droid version.

**Comment by samip5** [comment]
F-droid is known bug.

**Comment by alextran1502** [comment]
Duplicated of #1815
