### ISSUE TITLE
[BUG] Uploading of videos (.mp4) gets stuck and is unable to finish the backup

### ISSUE THREAD

**Issue by jrhbcn** [immich-app/immich#2010]
### The bug

New user of immich. I have setup everything from scratch using a ubuntu linux as server and a Google Pixel 6 as the android phone with the app. I only select the album "camera" with around 700 photos and videos (some of the videos are up to 1Gb in size). I set the screen on the phone to never sleep so I can test the uploading in the foreground (I do not activate the background download for now just to test). I have setup the connection between mobile and server directly (through the IP with http) and through a cloudflare tunnel (using the DNS name and https). 

When I activate the foreground backup, I was expecting the upload of all the album to happen. However, in both cases uploading of videos get stuck (specially large ones). I have left the phone for minutes on (with the immich app always opened) and nothing happens. In the direct connection, after cancelling the upload and resuming it many times I have managed to re-start the transmission and the upload of all the videos finishes. However, using the cloudflare tunnel this does not happen and I have been unable to finish the entire backup. The videos get stuck and stuck again no matter how many times I cancel/resume the upload. 

I don't see any log in immich_proxy. In immich_microservices I see the "Generating video thumbnail" and "converting success" ones only. I noticed (using docker stats) that the immich_microservices container sometimes do not uses any cpu time and it does not even try to convert the video so it seems as if never finishes the upload.  immich_server reports "new websocket connections" and "client disconnections from websocket" only.

### The OS that Immich Server is running on

Ubuntu 20.04 on an oracle cloud free tier A1 compute

### Version of Immich Server

v1.50.1

### Version of Immich Mobile App

v1.50.0 build.73

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
same as default, haven't changed anything.
```

### Your .env content

```Shell
Same as default, I just added 

TZ=Europe/Madrid    #to see if logs were using correct timeline

and changed UPLOAD_LOCATION to point to a local folder.
```

### Reproduction steps

```bash
1. Start server from scratch (deleting all config)
2. Install app on phone and select Camera album to backup
3. Select foreground backup and keep immich app always open
4. videos get stuck uploading
```

### Additional information

Is there any way to increase the log of the docker containers? I would like to see if uploads of video finishes completely...

**Comment by etnoy** [comment]
Are you using a reverse proxy? Cloudflare?

**Comment by jrhbcn** [comment]
@etnoy I am using both direct connection (no tunnel no reverse proxy) and cloudflare tunnels.

**Comment by samip5** [comment]
> @etnoy I am using both direct connection (no tunnel no reverse proxy) and cloudflare tunnels.

CF tunnels have limits...

**Comment by jrhbcn** [comment]
@samip5 are you sure? I haven't been able to find any bandwith or total limits on cloudflare tunnels anywhere.

Also, as I said, I have used direct connection and videos also get stuck. My guess is that somehow immich server throttles and it is unable to serve/accept any more files?

**Comment by michelheusschen** [comment]
If I'm understanding correctly, you're still using Cloudflare's CDN which has a upload limit of 100MB. Not having any error logs in either the server or microservices container is weird and probably indicates a problem elsewhere. The logs for `immich_proxy` are hidden by default, but error logs can be enabled by removing the logging `driver: none` from the compose file.

But you mention that uploading videos locally does work and you're only having trouble once you connect via your domain which uses Cloudflare, right? You can also try uploading videos larger than 100MB through the web interface, first via the local IP and then try to use your domain with Cloudflare and see if the upload fails.

**Comment by jrhbcn** [comment]
> If I'm understanding correctly, you're still using Cloudflare's CDN which has a upload limit of 100MB. Not having any error logs in either the server or microservices container is weird and probably indicates a problem elsewhere. The logs for `immich_proxy` are hidden by default, but error logs can be enabled by removing the logging `driver: none` from the compose file.

OK, if there is indeed a 100MB limit on upload requests with cloudflare tunnels then I guess videos will always fail yes. I checked and I've got 14 video files greater than 100Mb. I will start from scratch again and see if that is a magic number where upload fails.

> But you mention that uploading videos locally does work and you're only having trouble once you connect via your domain which uses Cloudflare, right? You can also try uploading videos larger than 100MB through the web interface, first via the local IP and then try to use your domain with Cloudflare and see if the upload fails.

Ok, I will try that. However, when connecting directly using the public IP number of the oracle cloud instance, upload also gets stuck as well on some files but cancel/resuming manages to finally upload all files. Also no logs here.


Thanks for all your answers!

**Comment by jrhbcn** [comment]
Confirmed, trying to upload a video with more than 100Mb through web with cloudflare tunnel is no go. 

I will investigate further why upload stucks in the direct connection and report here. Also, I will try to setup a nginx reverse proxy directly to bypass the cloudflare limitation. 

 

Thanks again,

**Comment by derekpurdy** [comment]
I'm actually seeing a similiar issue just behind an nginx reverse proxy (SWAG), no cloudflare tunnel currently enabled here.

**Comment by alextran1502** [comment]
@derekpurdy do you have max body size set on your Nginx reverse proxy?

**Comment by derekpurdy** [comment]
> @derekpurdy do you have max body size set on your Nginx reverse proxy?

hrmm, looks like i have it set as "client_max_body_size 0;"

**Comment by etnoy** [comment]
You need 

  client_max_body_size 0;

and in the proxy def

    proxy_max_temp_file_size 96384m;

We should document this in the FAQ

**Comment by derekpurdy** [comment]
I'm still having issues with mp4 files, i also switched now from the all-in-one container to the docker compose method on unraid. Finding documentation on the proper nginx config for swag has been confusing. Lots of information, but all seem to not use the immich proxy, which is how the docker-compose is written.

**Comment by jrhbcn** [comment]
Sorry for my delayed answer, but I was in the process of changing some hardware of my proxmox server and took a while to set everything up. Just to recap I was unable to upload big files to immich through cloudflare tunnels due to the 100MB limit. It is OK to upload big files directly to local IP address.

So I tried to proxy through my docker swag container (running nginx inside). I have used this configuration file. I wanted to use the internal immich proxy so I did **not** follow the discussion #1275 but only proxy the `/` location. This is my `immich.subdomain.conf` in swag/nginx:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name photos.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;
    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.1.20;
        set $upstream_port 2283;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        #proxy_set_header X-Forwarded-for $remote_addr;
        proxy_max_temp_file_size 96384m;

    }
}
```

Accessing immich through the web is working fine (and I can upload big files). However, I seem to run into a different (maybe related) problem. When I freshly install the immich android app and try to set up the `https://photos.mydomain.com` in the first screen then I get the following screen and I cannot even login. Android app is the latest version (v1.51.0) and it also happens with my local IP address `http://192.168.1.20:2283` so I am not sure know if it is my swag-nginx setup or something else?

![image](https://user-images.githubusercontent.com/22198270/227785427-cad8365f-a19a-47bb-a0a8-df4c89390959.png)
