### ISSUE TITLE
[BUG] Internal server error 500 when clicking "Explore"

### ISSUE THREAD

**Issue by bertmelis** [immich-app/immich#2028]
### The bug

When clicking "Explore" on the web, the server generates an internal error 500.

immich-server shows this log:

```
[Nest] 1  - 03/20/2023, 5:42:08 PM   ERROR [ExceptionsHandler] Request failed with HTTP code 400 | Server said: Error with filter field `exifInfo.state`: Filter value cannot be empty.

RequestMalformed: Request failed with HTTP code 400 | Server said: Error with filter field `exifInfo.state`: Filter value cannot be empty.

    at RequestMalformed.TypesenseError [as constructor] (/usr/src/app/node_modules/typesense/lib/Typesense/Errors/TypesenseError.js:23:28)

    at new RequestMalformed (/usr/src/app/node_modules/typesense/lib/Typesense/Errors/RequestMalformed.js:25:42)

    at ApiCall.customErrorForResponse (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:332:21)

    at /usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:199:98

    at step (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:33:23)

    at Object.next (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)

    at step (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:18:139)

    at Object.next (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)

    at fulfilled (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:5:58)

    at runMicrotasks (<anonymous>)
```

![image](https://user-images.githubusercontent.com/23474336/226424086-c207bb4d-7b6b-4dee-a35c-1666dce32437.png)

### The OS that Immich Server is running on

RHEL9

### Version of Immich Server

v1.51.0

### Version of Immich Mobile App

v1.50.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
standard, like the official
```

### Your .env content

```Shell
standard, like the official
```

### Reproduction steps

```bash
Updated the containers to v1.51.0
Clicked "Explore" in the web interface.
```

**Comment by bo0tzz** [comment]
Did you add the new typesense container as specified in the release notes?

**Comment by bertmelis** [comment]
It might have something to do with the hostname indeed. I'm running the stack with Podman and not Docker. I'll see if I can sort this out.

**Comment by jrasm91** [comment]
BTW - the actual error you originally posted about a malformed request looks to be a immich bug, not a typesense issue or even a communication issue.

**Comment by bertmelis** [comment]
Yes, I'll try to reproduce the original error and post the log again.

**Comment by Nobrac** [comment]
I have the exact same error with a completely new installed Immich server from scratch. My OS is RHEL 8.6.

![immich](https://user-images.githubusercontent.com/22682116/226453120-a5057711-509c-42bd-abe0-ca7c502cd00d.PNG)

**Comment by bertmelis** [comment]
I'm about to completely ruin my system... Can't really reproduce anymore. When defining the hostname (`localhost`) I do get this:

```
Request #1679342542451: Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8108"
```

Typesense isn't reachable.

I added an extra container to the stack to curl into Typesense but the connection was refused...

**Comment by alextran1502** [comment]
Let us take a look at the issue and will advise you

**Comment by alextran1502** [comment]
Confirm that we also experiencing this issue of accessing the Explore page on some of the account. On my production instance, I can access with my account but my wife account has problem accessing it, same 500 error. We are working on identifying the cause for a hot fix

**Comment by jrasm91** [comment]
Pretty sure this is caused by some of the data having spaces or parens in it. Will probably need to escape those in the query to typesense.  Should be easy enough to fix later tonight.

**Comment by alextran1502** [comment]
Let me know if the release 1.51.1 help fix this issue.

**Comment by JosiahBull** [comment]
Upgrading to 1.51.1 has not solved this issue for me.

Please find screenshot attached of errors in the log:
![image](https://user-images.githubusercontent.com/29187591/226522000-13906511-72bb-43d9-bc37-45bff3f65484.png)

![image](https://user-images.githubusercontent.com/29187591/226522703-939ea010-57a0-4bf0-bdb0-606b85c14040.png)

**Comment by bertmelis** [comment]
1.51.1 did solve the issue for me. 👍

**Comment by happyxhw** [comment]
![image](https://user-images.githubusercontent.com/44490504/226571037-1f1ee857-aa9d-40a2-a016-f5b322d5937e.png)


ERROR [ExceptionsHandler] Request failed with HTTP code 404 | Server said: Not Found
