### ISSUE TITLE
[BUG] Internal server error 500 when clicking "Explore"

### ISSUE THREAD

**Issue by zyg117** [immich-app/immich#2035]
### The bug

When clicking "Explore" on the web, the server generates an internal error 500.

immich-server shows this log:

[Nest] 1  - 03/21/2023, 8:36:19 AM   ERROR [ExceptionsHandler] Request failed with HTTP code 404 | Server said: Not Found
ObjectNotFound: Request failed with HTTP code 404 | Server said: Not Found
    at ObjectNotFound.TypesenseError [as constructor] (/usr/src/app/node_modules/typesense/lib/Typesense/Errors/TypesenseError.js:23:28)
    at new ObjectNotFound (/usr/src/app/node_modules/typesense/lib/Typesense/Errors/ObjectNotFound.js:25:42)
    at ApiCall.customErrorForResponse (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:338:21)
    at /usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:199:98
    at step (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:33:23)
    at Object.next (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)
    at step (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:18:139)
    at Object.next (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)
    at fulfilled (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

![image](https://user-images.githubusercontent.com/36789713/226559399-56ab6d3c-ec14-4eda-b644-aa0d96ed9a9c.png)

### The OS that Immich Server is running on

Unraid 6.11.5

### Version of Immich Server

v1.51.1

### Version of Immich Mobile App

v1.50.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
standard, like the official
```

### Your .env content

```Shell
standard, like the official
```

### Reproduction steps

```bash
Updated the containers to v1.51.1
Clicked "Explore" in the web interface.
```

### Additional information

No response

**Comment by JosiahBull** [comment]
May be a duplicate, see #2028

**Comment by alextran1502** [comment]
@zyg117 Can you add LOG_LEVEL=debug in your Immich environment variable file, then restart the containers and try to access the explore page again then help us capture a screenshot of the log

**Comment by florianchevallier** [comment]
I'm not sure if it's exactly the same thing but I get this when doing a search :

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/42930731/226678288-48c1e40e-afd3-46de-a31b-73face24d066.png">

**Comment by kai23** [comment]
Still the same : 
![Capture d’écran 2023-03-21 à 17 52 37](https://user-images.githubusercontent.com/796803/226683553-7f37ba11-0960-4f44-821c-81630d53b22b.png)

Here is the full log of the "start" : 
![Capture d’écran 2023-03-21 à 17 52 52](https://user-images.githubusercontent.com/796803/226683640-7ff1c4aa-87c8-4e50-a9dc-bb6202fc49b8.png)

```logs
21/03/2023 17:50:01
/opt/venv/lib/python3.10/site-packages/transformers/models/convnext/feature_extraction_convnext.py:28: FutureWarning: The class ConvNextFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ConvNextImageProcessor instead.
21/03/2023 17:50:01
  warnings.warn(
21/03/2023 17:50:01
/opt/venv/lib/python3.10/site-packages/transformers/models/yolos/feature_extraction_yolos.py:28: FutureWarning: The class YolosFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use YolosImageProcessor instead.
21/03/2023 17:50:01
  warnings.warn(
21/03/2023 17:50:01
/opt/venv/lib/python3.10/site-packages/transformers/models/yolos/image_processing_yolos.py:704: FutureWarning: The `max_size` parameter is deprecated and will be removed in v4.26. Please specify in `size['longest_edge'] instead`.
21/03/2023 17:50:01
  warnings.warn(
21/03/2023 17:50:02
 * Serving Flask app 'main'
21/03/2023 17:50:02
 * Debug mode: off
21/03/2023 17:50:02
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
21/03/2023 17:50:02
 * Running on all addresses (0.0.0.0)
21/03/2023 17:50:02
 * Running on http://127.0.0.1:3003
21/03/2023 17:50:02
 * Running on http://192.168.89.4:3003
21/03/2023 17:50:02
Press CTRL+C to quit
21/03/2023 17:50:39
/opt/venv/lib/python3.10/site-packages/transformers/models/convnext/feature_extraction_convnext.py:28: FutureWarning: The class ConvNextFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ConvNextImageProcessor instead.
21/03/2023 17:50:39
  warnings.warn(
21/03/2023 17:50:40
/opt/venv/lib/python3.10/site-packages/transformers/models/yolos/feature_extraction_yolos.py:28: FutureWarning: The class YolosFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use YolosImageProcessor instead.
21/03/2023 17:50:40
  warnings.warn(
21/03/2023 17:50:40
/opt/venv/lib/python3.10/site-packages/transformers/models/yolos/image_processing_yolos.py:704: FutureWarning: The `max_size` parameter is deprecated and will be removed in v4.26. Please specify in `size['longest_edge'] instead`.
21/03/2023 17:50:40
  warnings.warn(
21/03/2023 17:50:40
 * Serving Flask app 'main'
21/03/2023 17:50:40
 * Debug mode: off
21/03/2023 17:50:40
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
21/03/2023 17:50:40
 * Running on all addresses (0.0.0.0)
21/03/2023 17:50:40
 * Running on http://127.0.0.1:3003
21/03/2023 17:50:40
 * Running on http://192.168.89.4:3003
21/03/2023 17:50:40
Press CTRL+C to quit
21/03/2023 17:51:17
192.168.89.41 - - [21/Mar/2023 17:51:17] "POST /sentence-transformer/encode-text HTTP/1.1" 404 -
21/03/2023 17:52:26
192.168.89.41 - - [21/Mar/2023 17:52:26] "POST /sentence-transformer/encode-text HTTP/1.1" 404 -
```

**Comment by alextran1502** [comment]
@kai23 I think your container is not up-to-date

**Comment by jrasm91** [comment]
@florianchevallier you should open a separate ticket (or post on discord for faster replies) as you are running into an unrelated issue with your setup.

**Comment by kai23** [comment]
On my side, it was indeed because I was still using the old repository for the docker images, after using the new ones (from ghcr.io), the 404 went away

**Comment by theautomation** [comment]
I have this same issue when using the search bar. 

immich-server log:
```
[Nest] 1  - 03/21/2023, 8:32:56 PM   ERROR [ExceptionsHandler] Request failed with status code 500
Error: Request failed with status code 500
    at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by twitsforbrains** [comment]
@theautomation I had the same error. As you can see it says permission denied on /.cache. I had passed in a uid into this container just cause I'm paranoid. Removing the uid and letting it be root fixes the problem. Unfortunately when I created a folder in the container `/.cache` and set the permissions manually to the same userid for the container I still couldn't get it working so I just reverted back to using the root user

**Comment by zyg117** [comment]
> @zyg117 Can you add LOG_LEVEL=debug in your Immich environment variable file, then restart the containers and try to access the explore page again then help us capture a screenshot of the log



> 

Where should I go to set up? Is it this configuration file ：
![image](https://user-images.githubusercontent.com/36789713/226814140-e43b4192-c00a-4b3c-a9c6-7594d2d0836f.png)
![image](https://user-images.githubusercontent.com/36789713/226814171-649e4609-926f-4411-b57b-923ca901f082.png)
![image](https://user-images.githubusercontent.com/36789713/226814218-a64aeed5-359c-4aa7-9ee2-54f86e63785b.png)

If it's here, I've already added it and restarted as you instructed, but when I accessed that page again, I found that the log output didn't change. Did I set something wrong?

Here is the error log output：

![image](https://user-images.githubusercontent.com/36789713/226814734-ef0aeac3-912a-41fa-9084-eceedd82949c.png)

And the full log output：
![image](https://user-images.githubusercontent.com/36789713/226814873-9cbce53b-c86e-4b10-b840-ca5c0a60dbf5.png)
![image](https://user-images.githubusercontent.com/36789713/226814901-465d85bb-a242-4430-8d1d-65be1dfe3afc.png)
![image](https://user-images.githubusercontent.com/36789713/226814925-05226fa8-287e-4992-ae44-55f66c14cc02.png)
![image](https://user-images.githubusercontent.com/36789713/226814950-988399b0-f64d-4176-9093-a112550530e9.png)

**Comment by w00tlarr** [comment]
Hi - I got these errors but resolved it. Here are the steps for me:
1) Make sure your docker-compose is pulling the image from ghcr.io repo (i.e.: ghcr.io/immich-app/immich-server:release) instead from altran1502.

2) Have to start containers in order - after docker-compose -d up (tho I use Portainer), I manually shutdown all containers and restart one by one in this order, immich-db, redis, typesense, then wait up to 5 mins before immich-machine-learning, immich-server, immich-microservice. The connection between typesense and immich-server is pretty tight (per release notes), so make sure typesense is up before the server is. [I did comment out the _logging: driver: none_ section of typesense docker-compose to monitor in the docker logs.] This part is a lot of trials and errors for me to get all containers run healthily - if someone can suggest a docker-compose method to check for dependencies + health checks (not just container starts), please suggest one. Thanks in advance.

3) Once up, go to the Immich Web UI > Administration > Encode Clip > All (button). Mine ran overnight (~over 100K photos). Trying to search before this is done will give the 500 errors (404 in immich-server logs). At the end, you'll need to have patience for this for large libraries.

4) Note: I am getting these errors still though. But my search works now.
Immich-Microservice logs: 
[Nest] 1  - 03/22/2023, 8:58:30 AM   ERROR [SmartInfoService] Unable run clip encoding pipeline: 795e0760-3aa3-483c-a52b-70dbbe5e1e02
QueryFailedError: numeric field overflow
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async SmartInfoRepository.upsert (/usr/src/app/dist/apps/microservices/libs/infra/src/db/repository/smart-info.repository.js:25:9)
    at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/apps/microservices/libs/domain/src/smart-info/smart-info.service.js:97:13)
    at async ClipEncodingProcessor.onEncodeClip (/usr/src/app/dist/apps/microservices/apps/microservices/src/processors.js:112:9)

Immich-Postgres
2023-03-22 12:58:30.591 UTC [472] ERROR:  numeric field overflow
2023-03-22 12:58:30.591 UTC [472] DETAIL:  A field with precision 20, scale 19 must round to an absolute value less than 10^1.
2023-03-22 12:58:30.591 UTC [472] STATEMENT:  INSERT INTO "smart_info"("assetId", "tags", "objects", "clipEmbedding") VALUES ($1, DEFAULT, DEFAULT, $2) ON CONFLICT ( "assetId" ) DO UPDATE SET "assetId" = EXCLUDED."assetId", "clipEmbedding" = EXCLUDED."clipEmbedding"

**Comment by jrasm91** [comment]
Thanks!

We're working to make the start order/logic between typesense and the other containers more flexible.

The overflow has shown up a few times. If you could grab the thumbnail for that asset, I would be interested to know if it is a valid image. If you could find and upload it, we can troubleshoot that issue. Ultimately it means that one won't show up in clip searches, but everything else should continue to work as expected.

**Comment by jagjordi** [comment]
I am also seeing this error when running encode clip or tag objects:
```
172.25.0.7 - - [24/Mar/2023:15:33:03 +0000] "POST /image-classifier/tag-image HTTP/1.1" 500 265 "-" "axios/0.26.1"
[2023-03-24 15:33:03,567] ERROR in app: Exception on /object-detection/detect-object [POST]
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/src/app/src/main.py", line 37, in object_detection
    return run_engine(model, assetPath), 200
  File "/usr/src/app/src/main.py", line 59, in run_engine
    predictions = engine(path)
  File "/opt/venv/lib/python3.10/site-packages/transformers/pipelines/object_detection.py", line 95, in __call__
    return super().__call__(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1084, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/opt/venv/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1090, in run_single
    model_inputs = self.preprocess(inputs, **preprocess_params)
  File "/opt/venv/lib/python3.10/site-packages/transformers/pipelines/object_detection.py", line 98, in preprocess
    image = load_image(image)
  File "/opt/venv/lib/python3.10/site-packages/transformers/image_utils.py", line 232, in load_image
    raise ValueError(
ValueError: Incorrect path or url, URLs must start with `http://` or `https://`, and upload/a8e843dc-2b16-4175-b247-8ee5539f08ab/thumb/CLI/da09f667-6bd8-41a3-90a8-093b2306b5bc.jpeg is not a valid path
```

**Comment by jrasm91** [comment]
@jagjordi - can you verify that the UPLOAD_LOCATION volume is mounted to  the machine learning container?

**Comment by jagjordi** [comment]
@jrasm91 It looks like it is mounted:
```
root@Tower:~# docker exec -it immich_machine_learning bash
root@3fb4fa0cb6be:/usr/src/app# ls
Dockerfile  README.md  gunicorn.conf.py  src  upload
root@3fb4fa0cb6be:/usr/src/app# cd upload/
root@3fb4fa0cb6be:/usr/src/app/upload# ls
1dd38e30-8f47-4129-bcd0-36e6537dfa54  5001418f-1e48-4a12-81c9-10ff90defb78
21500b77-b342-4707-acf0-b6f1daa55577  9d015ed5-e62c-4dac-b6f6-3f5f25c73e00
root@3fb4fa0cb6be:/usr/src/app/upload# cd 9d015ed5-e62c-4dac-b6f6-3f5f25c73e00/
root@3fb4fa0cb6be:/usr/src/app/upload/9d015ed5-e62c-4dac-b6f6-3f5f25c73e00# ls
1980  2007  2010  2013  2016  2019  2022           original
2003  2008  2011  2014  2017  2020  2023           profile
2004  2009  2012  2015  2018  2021  encoded-video  thumb
root@3fb4fa0cb6be:/usr/src/app/upload/9d015ed5-e62c-4dac-b6f6-3f5f25c73e00# 
```

`docker_compose.yml` (ML section)
```
  immich-machine-learning:                                                                                                                                                                                                      
    container_name: immich_machine_learning                                                                                                                                                                                     
    image: ghcr.io/immich-app/immich-machine-learning:release                                                                                                                                                                   
    volumes:                                                                                                                                                                                                                    
      - ${UPLOAD_LOCATION}:/usr/src/app/upload                                                                                                                                                                                  
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
```
It seems to be correctly mounted into `/usr/src/app/upload`

**Comment by alextran1502** [comment]
This would happen if the system has non-avx CPU and try Typesense search, the workaround is to disable typesense
