### ISSUE TITLE
[BUG] Backup album select search displays incorrect count

### ISSUE THREAD

**Issue by EnochPrime** [immich-app/immich#2050]
### The bug

When performing a search of albums to select for backup the full list asset count is maintained. 

For example of the first album in the list has 100 assets and the second has 50 and the user searched for the second album it will display 100 assets.

### The OS that Immich Server is running on

Various 

### Version of Immich Server

v1.50.1

### Version of Immich Mobile App

v1.50.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Tap the cloud icon
2. Search for album name
```

**Comment by alextran1502** [comment]
Can you update the app and server then check again to see if the bug is still there?

**Comment by alextran1502** [comment]
Confirmed bug. Good find!

**Comment by EnochPrime** [comment]
Confirmed this is fixed.
