### ISSUE TITLE
[BUG] 500 getaddrinfo ENOTFOUND immich-server

### ISSUE THREAD

**Issue by MozPri** [immich-app/immich#2055]
### The bug

Can't access Immich web page since version v1.51.0.
I get 500 getaddrinfo ENOTFOUND immich-server error.

[_immich_server_logs.txt](https://github.com/immich-app/immich/files/11049569/_immich_server_logs.txt)

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v1.51.2

### Version of Immich Mobile App

v1.51.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Latest from the docs
```

### Your .env content

```Shell
Latest from the docs
```

### Reproduction steps

```bash
1. Install Immich with Portainer or docker-compose
2. Go to the Immich web page
```

**Comment by bo0tzz** [comment]
Is the typesense container running? The server can't reach it.

**Comment by MozPri** [comment]
It's running if I add `restart: always`. But it's not running without it.

**Comment by bo0tzz** [comment]
You'll need to enable logging on the typesense container to figure out why it's having trouble starting. Either way this is not a problem in Immich, so I'll close this issue.

**Comment by tinju87** [comment]
Same problem with docker-compose running on portainer.

**Comment by tinju87** [comment]
TYPESENSE_API_KEY is missing in the env file and needed by typesense container.
Adding TYPESENSE_API_KEY to the env with whatever value worked for me.

**Comment by Peda1996** [comment]
I have the same problem, my server wont boot up.

`
getaddrinfo ENOTFOUND immich-server
`
Where can I find log files, that I can attach to that issue? Im using a dell wyse 5070 thin client as my system.

**Comment by MozPri** [comment]
@Peda1996 Try disabling machine learning and typesense.
Add this to env variables:
```
IMMICH_MACHINE_LEARNING_URL=false
TYPESENSE_ENABLED=false
```

Logs:
https://documentation.immich.app/docs/guides/docker-help#logs

**Comment by florihupf** [comment]
Running into the same thing.

Should this be re-opened?

**Comment by florihupf** [comment]
Ah, never mind.  Didn't realize I need to update .env.

**Comment by florihupf** [comment]
Dang it, I got it all working and that search is SO SUPER AWESOME!

TYTYTYTY!

**Comment by Peda1996** [comment]
Oh, sorry forgot to mention that I already fixed it with the help of
discord. Fixed it as followed:

1. add these to .env
TYPESENSE_API_KEY=some-random-text

2. exchange your docker compose for the newest version

Now just update like you would regularly update the service:
1.  docker compose pull
2. docker compose up -d

Florian Sauer ***@***.***> schrieb am So., 26. März 2023,
18:05:

**Comment by Snuupy** [comment]
@bertmelis do you think we can get a non-avx image working here?

**Comment by bertmelis** [comment]
I don't know. I guess I can start a build container: https://github.com/typesense/typesense#build-from-source and see what happens.

**Comment by bertmelis** [comment]
So. I just built Typesense from source, using the script in the typesense repo and pointed the compose file to the locally generated image.

On my J4105 it took a less then 4 hours. Not a big deal to do it yourself. It also doesn't clutter your system with all kind of dependencies because the build process is entirely contained in build containers.

I probably won't publish an image because it actually is just too easy to create one yourself. And then it is built for **your** cpu.

I'm happy to write the instructions if you need help.

**Comment by Snuupy** [comment]
I'll give it a try! Thanks!

**Comment by Snuupy** [comment]
How do you get docker to reference the locally built typesense image in the compose file?

My typesense build worked  after running the command several times due to some checksums not working. Eventually it did build though (not sure how long it took, walked away and got some food, when I came back build was done). It was tagged by default as `typesense/typesense:nightly`, which I re-tagged as `typesense` (in attempts of trying to make it not pull latest from dockerhub).

However, when I run `docker compose pull`, docker will complain that the repo `typesense` does not exist (which rightfully so, it does not on dockerhub). How do I get `pull` to skip typesense and provide a local image to be used instead? `up -d` works in the meantime.

**Comment by bertmelis** [comment]
This should go in your composefile:

image: localhost/typesense/typesense:nightly

**Comment by Snuupy** [comment]
If I paste that in, I get: `Error response from daemon: error unmarshalling content: invalid character '<' looking for beginning of value`

**Comment by bertmelis** [comment]
Sorry, I'm using Podman, not Docker. I'm not familiar with your error.

Can you run the image as-is, outside of the Immich stack?

**Comment by Snuupy** [comment]
Via docker run? I don't see why that wouldn't work. It's when I `pull` that it tries to fetch an image remotely but I want it to use the local one instead.

**Comment by bertmelis** [comment]
Some googling suggests you just shouldn't pull. When the stack is started, docker will find the local image.

https://github.com/docker/compose/issues/3660

**Comment by Snuupy** [comment]
> Some googling suggests you just shouldn't pull. When the stack is started, docker will find the local image.
> 
> [docker/compose#3660](https://github.com/docker/compose/issues/3660)

Wait - but I need to pull to update immich

**Comment by rkononov** [comment]
> I don't know. I guess I can start a build container: https://github.com/typesense/typesense#build-from-source and see what happens.
> 
> Edit: after some minor changes to their Docker build script, it's building. I have no clue about the outcome or the time it takes.
> (changes: replace docker by podman and satisfy SELinux, you might not have to do this)

Could you please share the changes you introduced?

**Comment by bertmelis** [comment]
I'm using postman on a SELinux-enabled machine.

The two changes:
- replaced docker command with podman command
- added :Z flags to volume mounts

**Comment by 55nevets** [comment]
> So. I just built Typesense from source, using the script in the typesense repo and pointed the compose file to the locally generated image.
> 
> On my J4105 it took a less then 4 hours. Not a big deal to do it yourself. It also doesn't clutter your system with all kind of dependencies because the build process is entirely contained in build containers.
> 
> I probably won't publish an image because it actually is just too easy to create one yourself. And then it is built for **your** cpu.
> 
> I'm happy to write the instructions if you need help.

@bertmelis:  I'm interested in compiling typesense for my Intel N5100.  Could you provide your build script?  Are you still running this non-avx version, and has it been sufficient for a personal immich install?

**Comment by bertmelis** [comment]
I'm still running it. For me it is sufficient. It might take a tad longer but it's a background task. It still processes the pictures faster than I shoot them.

I don't know how I built the container but I might find some leftovers on my home server... Stay tuned.

**Comment by bertmelis** [comment]
ah yes. Typesense is on v0.25 but Immich uses v0.24. The instructions to build it yourself are extremely simple: just download/clone the Typesense repo with the correct version and execute the script.

**Comment by 756yang** [comment]
After my inspection, the official archive compiled by typesense supports most x64 platforms. Based on the platform instruction set, it requires at least SSE2, SSSE3, SSE4.1 support, and may require SSE3 and SSE4.2 support.

The AVX instruction set is additional and not necessarily required.
