### ISSUE TITLE
[BUG] Timeline shows photos with the same date in the wrong sort order (web only)

### ISSUE THREAD

**Issue by natedawg** [immich-app/immich#2061]
### The bug

I have a few sets of photos that have the exact same date because they were downloaded from Instagram posts. The timeline shows these photos in one order but if I click on the first photo in the set to open the fullsize photos and then cycle through them the sort order is different. This only happens on the web. I looked at the mobile app and both the timeline and fullscreen view sort order match. 

The sort order of the photos on mobile matches the order of the web fullsize photo view. So it's the web timeline that is not sorting correctly.

### The OS that Immich Server is running on

Docker on debian

### Version of Immich Server

v1.51.2

### Version of Immich Mobile App

v1.51.2

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. Look at the order of a set of photos that have the same date and time on the web timeline
2. View the first photo in the set
3. Cycle through the photos and the sort order does not match the timeline
```

**Comment by uhthomas** [comment]
Fixed by #3092.
