### ISSUE TITLE
[BUG] WEBM uploads from Android APP does not work

### ISSUE THREAD

**Issue by zeyadtamimi** [immich-app/immich#2086]
### The bug

While backing up my Android phone's media I noticed that  `.webm` videos do not get backed up at all with the app showing the error status "Bad request".

When this happens the `immich` server reports:

`[Nest] 1  - 03/25/2023, 11:52:55 PM   ERROR [AssetUploadConfig] Unsupported file type  file MIME type unsupport/unsupport`

This issue does not seem to exist on the WEB UI I as am able to upload the same `.webm`s with no errors.

I think the Android upload logic might not be setting the MIME type correctly.

### The OS that Immich Server is running on

Arch Linux, x86_64, Linux Kernel 6.2.2

### Version of Immich Server

v1.51.2

### Version of Immich Mobile App

v1.51.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Try to trigger a manual backup on the android app with a `.webm` in photos to back up.
```

**Comment by alextran1502** [comment]
I think the issue is the phone cannot decode `webm` for the Mime type as you see it reported the mimetype is as `unsupported/unsupported`

**Comment by printfuck** [comment]
I can confirm that behaviour. It looks like the webm type is missing in the Filehelper class:

https://github.com/immich-app/immich/blob/0164171cad2441f0630fde4d602981dac55dea47/mobile/lib/utils/files_helper.dart#L3-L49

At least that returns by default the `unsupport/unsupport` type.

**Comment by ZeyadTamimi** [comment]
@printfuck thanks for pointing out the snippet. Ill see if I can get get a PR up to add `.webm`s in there.
