### ISSUE TITLE
[BUG] Search seems to be broken after last update

### ISSUE THREAD

**Issue by yurividal** [immich-app/immich#2124]
### The bug

Running latest app and latest server compose.
Whenever I search for anything on my mobile app, I only get a black screen with a forever spinning wheel.

![Screenshot_20230330_080756](https://user-images.githubusercontent.com/8555749/228757325-4c61373c-e742-4ef2-8eb4-2d035259eb14.png)

### The OS that Immich Server is running on

Ubuntu 22.04 docker

### Version of Immich Server

1.52.1

### Version of Immich Mobile App

1.52.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Identical to the one provided by latest version, including machine learning and typesense
```

### Your .env content

```Shell
Identical to release
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by alextran1502** [comment]
Is it still happening? Can you help grab the mobile app log after performing the search?

**Comment by yurividal** [comment]
Just tried again and it seems to be fixed now. I think my server was too busy indexing and processing my revent uploads...

I also noticed that, every time I open the app, it initially thinks I don't uave any backup folders selected, and after a few seconds (5-10), if finally changes and shows that u am syncing the "camera" album.

Probably not related to OP though. Feel free to close this
