### ISSUE TITLE
Duplicate photos on mobile

### ISSUE THREAD

**Issue by dsippel** [immich-app/immich#2129]
### The bug

Since a couple of releases all photos uploaded from my iPhone, that are still on my phone, show up as duplicates in the photos view on my iPhone. See screenshot attached.

It probably is an issue with the recognition of what’s already uploaded and what not. In the web view or on an android tablet no duplicates are shown.

What I tried so far: logging out and back in on the mobile iOS app. Uninstalling and reinstalling the iOS app. Restarting the immich server. All without any luck.

Any suggestions?
![IMG_3616](https://user-images.githubusercontent.com/103022385/228921869-6574a170-24f4-40d0-9cd9-28d1cfaf3498.jpeg)

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v.1.52.1

### Version of Immich Mobile App

v.1.52.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not using docker compose. Using the all in one docker image: https://github.com/imagegenius/docker-immich
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
Open the mobile iOS app with photos that are still on the device and already uploaded.
```

**Comment by alextran1502** [comment]
Thank you, we are also received similar reports. So we will take a look at this. I just want to confirm that all of those shown as duplicated photos have been uploaded, correct? Can you help me navigate to the backup page and take a screenshot of that page as well?

**Comment by dsippel** [comment]
Thanks for the fast reply and this amazing piece of software!

Yes, all of the photos are uploaded correctly. Can view them on the web and on other devices.

Screenshots of my backup page attached.
![IMG_3617](https://user-images.githubusercontent.com/103022385/228925745-9e5a5b6c-f572-4eae-9d0f-a4a28a631050.png)
![IMG_3618](https://user-images.githubusercontent.com/103022385/228925756-5cf78ba1-b18a-4c44-8501-cb8ad47b89d0.png)

**Comment by alextran1502** [comment]
Ok, the current workaround is to choose an album that has 1 or 2 assets, so it won't show the local assets on your timeline.

**Comment by fyfrey** [comment]
@dsippel could you export the logs: profile drawer -> logs -> share (top right) or if this fails take a screenshot of any yellow or red entries in the log (or else simply the topmost logs after logout+login). Thanks!

**Comment by dsippel** [comment]
Exporting the log file didn’t work. Please find the screenshots of the log after a fresh sign in attached. Thanks for helping!

![IMG_3625](https://user-images.githubusercontent.com/103022385/229265724-3fad6f63-ff16-4bfd-9c56-54b4b393c909.png)
![IMG_3626](https://user-images.githubusercontent.com/103022385/229265725-ab522d98-3db0-4cfb-b111-b57917f77ac5.png)
![IMG_3627](https://user-images.githubusercontent.com/103022385/229265727-cbf71b00-3c4d-44fa-b1f5-88cacb857c4e.png)
![IMG_3628](https://user-images.githubusercontent.com/103022385/229265728-66b939f6-4eb5-483c-8d48-51ff326ebda3.png)
![IMG_3629](https://user-images.githubusercontent.com/103022385/229265730-e3125e28-72b5-4cb7-8307-c7fb1985e016.png)
![IMG_3630](https://user-images.githubusercontent.com/103022385/229265731-097fc962-c034-4370-b2dd-4e881a413f2b.png)
![IMG_3631](https://user-images.githubusercontent.com/103022385/229265733-95496d9c-2b6b-4d46-97e0-46f84b380b63.png)
![IMG_3632](https://user-images.githubusercontent.com/103022385/229265734-63b21fba-df23-4ae7-9b0f-08814e45da2e.png)
![IMG_3633](https://user-images.githubusercontent.com/103022385/229265735-4cd69e04-996a-4faf-b9f5-15b8c566cf5a.png)

**Comment by Isti6github** [comment]
Hello,

I have the same issue after the new relase (mobile iOS and server)![image](https://user-images.githubusercontent.com/127151924/230789539-bc87e374-3a9e-4afa-a240-66288c906116.png)![image](https://user-images.githubusercontent.com/127151924/230789542-28b29878-4265-4e19-8522-78a79689d10c.jpeg)

**Comment by alextran1502** [comment]
> Hello,
> 
> I have the same issue after the new relase (mobile iOS and server)![image](https://user-images.githubusercontent.com/127151924/230789539-bc87e374-3a9e-4afa-a240-66288c906116.png)![image](https://user-images.githubusercontent.com/127151924/230789542-28b29878-4265-4e19-8522-78a79689d10c.

Does it happen on all photos?

**Comment by bart268** [comment]
I also got the same issue starting about two weeks ago. I only use the web interface and IOS client on iPhone, all photo's are uploaded using the IOS client.
Sometimes the app seems to think all the photo's are new and tries to upload them (sort of).
My remainder photo's are now on -328. When I see this happening top right in the app I quickly close the app to not have all the photo's as duplicate. The timeline has now 328 (I guess) duplicates where one of the photo is uploaded and one isn't uploaded, the web UI doens't have the duplicate photo's.

I think this happened after the new folder structure was introduced, I migrated from the old to the new structure but not sure if this has anything to do with it.

This is the logging from last time it happened, I noticed the issue at 8:21 on april 11th. Also added logging from the day before, maybe this is related to the issue.
```
created_at,level,context,message,stacktrace
2023-04-11 08:31:35.239391,LogLevel.INFO,"AssetNotifier","state is already up-to-date",""
2023-04-11 08:31:35.236382,LogLevel.INFO,"AssetNotifier","Load assets: 1836ms",""
2023-04-11 08:31:35.236347,LogLevel.INFO,"AlbumService","Syncing completed. Changes: false",""
2023-04-11 08:31:34.704940,LogLevel.INFO,"AlbumService","Found 59 device albums",""
2023-04-11 08:31:33.423056,LogLevel.INFO,"BackupNotifier","Found 65 local albums",""
2023-04-11 08:31:33.401727,LogLevel.INFO,"BackupNotifier","[_resumeBackup] Start back up",""
2023-04-11 08:31:09.891857,LogLevel.INFO,"AssetNotifier","state is already up-to-date",""
2023-04-11 08:31:09.891337,LogLevel.INFO,"AssetNotifier","Load assets: 2065ms",""
2023-04-11 08:31:09.891305,LogLevel.INFO,"AlbumService","Syncing completed. Changes: false",""
2023-04-11 08:31:09.392588,LogLevel.INFO,"AlbumService","Found 59 device albums",""
2023-04-11 08:31:07.846762,LogLevel.INFO,"BackupNotifier","Found 65 local albums",""
2023-04-11 08:31:07.827505,LogLevel.INFO,"BackupNotifier","[_resumeBackup] Start back up",""
2023-04-11 08:22:31.464884,LogLevel.INFO,"AssetNotifier","state is already up-to-date",""
2023-04-11 08:22:31.464297,LogLevel.INFO,"AssetNotifier","Load assets: 1566ms",""
2023-04-11 08:22:31.464270,LogLevel.INFO,"AlbumService","Syncing completed. Changes: false",""
2023-04-11 08:22:31.051190,LogLevel.INFO,"AlbumService","Found 59 device albums",""
2023-04-11 08:22:27.514539,LogLevel.INFO,"BackupNotifier","Found 65 local albums",""
2023-04-11 08:31:09.891857,LogLevel.INFO,"AssetNotifier","state is already up-to-date",""
2023-04-11 08:31:09.891337,LogLevel.INFO,"AssetNotifier","Load assets: 2065ms",""
2023-04-11 08:31:09.891305,LogLevel.INFO,"AlbumService","Syncing completed. Changes: false",""
2023-04-11 08:31:09.392588,LogLevel.INFO,"AlbumService","Found 59 device albums",""
2023-04-11 08:31:07.846762,LogLevel.INFO,"BackupNotifier","Found 65 local albums",""
2023-04-11 08:31:07.827505,LogLevel.INFO,"BackupNotifier","[_resumeBackup] Start back up",""
2023-04-11 08:22:31.464884,LogLevel.INFO,"AssetNotifier","state is already up-to-date",""
2023-04-11 08:22:31.464297,LogLevel.INFO,"AssetNotifier","Load assets: 1566ms",""
2023-04-11 08:22:31.464270,LogLevel.INFO,"AlbumService","Syncing completed. Changes: false",""
2023-04-11 08:22:31.051190,LogLevel.INFO,"AlbumService","Found 59 device albums",""
2023-04-11 08:22:27.514539,LogLevel.INFO,"BackupNotifier","Found 65 local albums",""
2023-04-11 08:22:19.848796,LogLevel.INFO,"AssetNotifier","setting new asset state",""
2023-04-11 08:22:19.819641,LogLevel.INFO,"AssetNotifier","Load assets: 1389ms",""
2023-04-11 08:22:19.819559,LogLevel.INFO,"AlbumService","Syncing completed. Changes: true",""
2023-04-11 08:22:19.675790,LogLevel.INFO,"SyncService","Synced changes of local album AssetPathEntity(id: 7054C870-C326-40DF-933B-35759EC4E3D0/L0/040, name: Recent) to DB",""
2023-04-11 08:22:19.313763,LogLevel.INFO,"AlbumService","refreshDeviceAlbums is already in progress",""
2023-04-11 08:22:18.788620,LogLevel.INFO,"AlbumService","Found 59 device albums",""
2023-04-11 08:22:18.434034,LogLevel.INFO,"BackupNotifier","Found 65 local albums",""
2023-04-11 08:22:18.429840,LogLevel.INFO,"AssetNotifier","Reading assets 14713 from DB: 50ms",""
2023-04-11 08:22:18.367613,LogLevel.INFO,"BackupNotifier","[_resumeBackup] Start back up",""
2023-04-11 08:22:01.138378,LogLevel.SEVERE,"ImmichErrorLogger","PathNotFoundException: Cannot delete file, path = '/private/var/mobile/Containers/Data/Application/E469E05F-4D60-4D32-A94D-2D638B82416E/tmp/.image/1681161904.923239_o_IMG_3107.HEIC' (OS Error: No such file or directory, errno = 2)","#0      _File.throwIfError (dart:io/file_impl.dart:629)
#1      _File._deleteSync (dart:io/file_impl.dart:312)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424)
#3      BackupService.backupAsset (package:immich_mobile/modules/backup/services/backup.service.dart:319)
<asynchronous suspension>
#4      BackupNotifier.startBackupProcess (package:immich_mobile/modules/backup/providers/backup.provider.dart:448)
<asynchronous suspension>
#5      BackupNotifier._resumeBackup (package:immich_mobile/modules/backup/providers/backup.provider.dart:573)
<asynchronous suspension>
"
2023-04-11 08:22:01.069906,LogLevel.INFO,"AssetNotifier","setting new asset state",""
2023-04-11 08:22:01.035569,LogLevel.INFO,"AssetNotifier","Load assets: 3450ms",""
2023-04-11 08:22:01.035508,LogLevel.INFO,"AlbumService","Syncing completed. Changes: true",""
2023-04-11 08:22:00.919719,LogLevel.INFO,"SyncService","Synced changes of local album AssetPathEntity(id: 7054C870-C326-40DF-933B-35759EC4E3D0/L0/040, name: Recent) to DB",""
2023-04-11 08:21:59.727618,LogLevel.INFO,"AlbumService","refreshDeviceAlbums is already in progress",""
2023-04-11 08:21:59.727584,LogLevel.INFO,"SyncService","Upserted 2 assets into the DB",""
2023-04-11 08:21:57.987896,LogLevel.INFO,"AlbumService","Found 59 device albums",""
2023-04-11 08:21:57.825795,LogLevel.INFO,"BackupNotifier","Found 65 local albums",""
2023-04-11 08:21:57.811949,LogLevel.INFO,"BackupNotifier","[_resumeBackup] Start back up",""
2023-04-11 08:21:57.585380,LogLevel.INFO,"AssetNotifier","Reading assets 7554 from DB: 25224ms",""
2023-04-11 08:21:57.521727,LogLevel.INFO,"BackupNotifier","Found 65 local albums",""
2023-04-11 08:21:32.345925,LogLevel.INFO,"BackupNotifier","[_resumeBackup] Start back up",""
2023-04-10 14:20:06.524588,LogLevel.INFO,"BackupNotifier","No Asset On Device - Abort Backup Process",""
2023-04-10 14:20:05.242409,LogLevel.INFO,"AssetNotifier","state is already up-to-date",""
2023-04-10 14:20:05.240362,LogLevel.INFO,"AssetNotifier","Load assets: 828ms",""
2023-04-10 14:20:05.240331,LogLevel.INFO,"AlbumService","Syncing completed. Changes: false",""
2023-04-10 14:20:04.925762,LogLevel.INFO,"AlbumService","Found 59 device albums",""
2023-04-10 14:20:04.465390,LogLevel.INFO,"BackupNotifier","Found 65 local albums",""
2023-04-10 14:20:04.464453,LogLevel.SEVERE,"AssetService","Error while getting remote assets","#0      ApiClient.invokeAPI (package:openapi/api_client.dart:105)
<asynchronous suspension>
#1      WithETag.getAllAssetsWithETag (package:immich_mobile/utils/openapi_extensions.dart:20)
<asynchronous suspension>
#2      AssetService._getRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:64)
<asynchronous suspension>
#3      AssetService.refreshRemoteAssets.<anonymous closure> (package:immich_mobile/shared/services/asset.service.dart:49)
<asynchronous suspension>
#4      SyncService._syncRemoteAssetsToDb (package:immich_mobile/shared/services/sync.service.dart:154)
<asynchronous suspension>
#5      AssetService.refreshRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:48)
<asynchronous suspension>
#6      AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:113)
<asynchronous suspension>
"
2023-04-10 14:20:04.414635,LogLevel.INFO,"BackupNotifier","[_resumeBackup] Start back up",""
2023-04-10 05:27:00.008112,LogLevel.INFO,"BackupNotifier","No Asset On Device - Abort Backup Process",""
2023-04-10 05:26:46.969242,LogLevel.INFO,"BackupNotifier","Found 65 local albums",""
2023-04-10 05:26:46.929239,LogLevel.INFO,"AssetNotifier","state is already up-to-date",""
2023-04-10 05:26:46.928843,LogLevel.INFO,"BackupNotifier","[_resumeBackup] Start back up",""
2023-04-10 05:26:46.753153,LogLevel.INFO,"AssetNotifier","Load assets: 3489ms",""
2023-04-10 05:26:46.752894,LogLevel.INFO,"AlbumService","Syncing completed. Changes: false",""
2023-04-10 05:26:44.814657,LogLevel.INFO,"AlbumService","Found 59 device albums",""
2023-04-10 05:26:43.319299,LogLevel.INFO,"AlbumService","refreshDeviceAlbums is already in progress",""
2023-04-10 05:26:43.319011,LogLevel.SEVERE,"AssetService","Error while getting remote assets","#0      ApiClient.invokeAPI (package:openapi/api_client.dart:105)
<asynchronous suspension>
#1      WithETag.getAllAssetsWithETag (package:immich_mobile/utils/openapi_extensions.dart:20)
<asynchronous suspension>
#2      AssetService._getRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:64)
<asynchronous suspension>
#3      AssetService.refreshRemoteAssets.<anonymous closure> (package:immich_mobile/shared/services/asset.service.dart:49)
<asynchronous suspension>
#4      SyncService._syncRemoteAssetsToDb (package:immich_mobile/shared/services/sync.service.dart:154)
<asynchronous suspension>
#5      AssetService.refreshRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:48)
<asynchronous suspension>
#6      AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:113)
<asynchronous suspension>
"
2023-04-10 05:26:43.264046,LogLevel.INFO,"AssetNotifier","Reading assets 7554 from DB: 212ms",""
2023-04-10 05:26:43.211549,LogLevel.SEVERE,"ImmichErrorLogger","ApiException 400: Socket operation failed: GET /album (Inner exception: SocketException: Failed host lookup: '<dns name>' (OS Error: nodename nor servname provided, or not known, errno = 8))

#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:694)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1855)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:297)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:77)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2462)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2906)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2911)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2766)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2604)
#10     IOClient.send (package:http/src/io_client.dart:35)
#11     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
#12     BaseClient.get (package:http/src/base_client.dart:27)
#13     ApiClient.invokeAPI (package:openapi/api_client.dart:102)
<asynchronous suspension>
#14     AlbumApi.getAllAlbums (package:openapi/api/album_api.dart:514)
<asynchronous suspension>
#15     AlbumService.refreshRemoteAlbums (package:immich_mobile/modules/album/services/album.service.dart:149)
<asynchronous suspension>
#16     SharedAlbumNotifier.getAllSharedAlbums (package:immich_mobile/modules/album/providers/shared_album.provider.dart:48)
<asynchronous suspension>
","#0      ApiClient.invokeAPI (package:openapi/api_client.dart:105)
<asynchronous suspension>
#1      AlbumApi.getAllAlbums (package:openapi/api/album_api.dart:514)
<asynchronous suspension>
#2      AlbumService.refreshRemoteAlbums (package:immich_mobile/modules/album/services/album.service.dart:149)
<asynchronous suspension>
#3      SharedAlbumNotifier.getAllSharedAlbums (package:immich_mobile/modules/album/providers/shared_album.provider.dart:48)
<asynchronous suspension>
```

**Comment by dsippel** [comment]
The problem still persists for me with the newest server and iOS version (1.53.0). I tried uninstalling and reinstalling the iOS app and restarting the server. With the newest iOS app, the log export works now. Please find it attached. If you need any more information, let me know.

A
[Immich_log_2023-04-11T09:18:45.942815.csv](https://github.com/immich-app/immich/files/11197730/Immich_log_2023-04-11T09.18.45.942815.csv)
nd as always: thanks again for this great piece of software! Amazing work!

**Comment by dsippel** [comment]
[Immich_log_2023-04-11T09:18:45.942815.csv](https://github.com/immich-app/immich/files/11197746/Immich_log_2023-04-11T09.18.45.942815.csv)

**Comment by alextran1502** [comment]
> The problem still persists for me with the newest server and iOS version (1.53.0). I tried uninstalling and reinstalling the iOS app and restarting the server. With the newest iOS app, the log export works now. Please find it attached. If you need any more information, let me know.
> 
> 
> 
> And as always: thanks again for this great piece of software! Amazing work!
> 
> 

Thank you for the log, we still haven't found the root cause yet and in the process of building more debug info to help find the bug

**Comment by fyfrey** [comment]
@dsippel thank you for providing the log. Do the duplicates also show in the album view? Scroll down on the library page to "Albums on Device" and open the local/device albums. I'd would be very interesting to know whether the duplicates from the main timeline are also shown as duplicates here!

**Comment by Isti6github** [comment]
> @dsippel thank you for providing the log. Do the duplicates also show in the album view? Scroll down on the library page to "Albums on Device" and open the local/device albums. I'd would be very interesting to know whether the duplicates from the main timeline are also shown as duplicates here!

Hi, 
I see the duplicates pictures in the "Recents" folder view too.

**Comment by dsippel** [comment]
> @dsippel thank you for providing the log. Do the duplicates also show in the album view? Scroll down on the library page to "Albums on Device" and open the local/device albums. I'd would be very interesting to know whether the duplicates from the main timeline are also shown as duplicates here!

Nope, I don't see the duplicates there.

**Comment by fyfrey** [comment]
Thank you both! That is certainly an ambivalent picture; maybe these are two separate issues.
The next release will allow to get more debug info. Hopefully this will help us to resolve this issue.

**Comment by dsippel** [comment]
Hey immich team,

great new release 1.54.0. I updated my server and the mobile app. The issue with duplicates shown still persists. Please see attached screenshot and log file. Finest logging level selected. Hope this helps track down the issue.

Best

Daniel

![IMG_3724](https://user-images.githubusercontent.com/103022385/233126710-4edf774d-a84a-4d4e-9656-f70b80cd24c0.png)
[Immich_log_2023-04-19T17:31:46.925624.csv](https://github.com/immich-app/immich/files/11274873/Immich_log_2023-04-19T17.31.46.925624.csv)

**Comment by alextran1502** [comment]
@dsippel Thank you for the follow-up, and we didn't have a fix to this issue because we didn't know what to fix. Can you turn on the Advanced troubleshooting in the setting, go to a set of duplicate photos, open the info panel, take a screenshot, or add the info here?

Thanks!

**Comment by dsippel** [comment]
Please find attached the two screenshots. The first one is from the already uploaded file (cloud with check mark). The second from the local file (cloud struck through). Hope this helps.
![IMG_3725](https://user-images.githubusercontent.com/103022385/233172973-10492117-3a60-41ad-9ad2-7a2b0cf8ae00.png)
![IMG_3726](https://user-images.githubusercontent.com/103022385/233172979-d91e84a1-b193-4654-9ea7-4b198bbec52b.png)

**Comment by alextran1502** [comment]
@dsippel As you can see the `localId` of the two files are different as well as the `fileModifiedAt` property is different. The width and height of the two files are also different, which indicates two different files. Do you know if they ever get modified, or download from different sources? What is the album are you selecting for update?

@fyfrey FYI

**Comment by dsippel** [comment]
This is very strange. The photos were taken on my iPhone and were uploaded through the immich app. I did not modify them in any way before or after upload! I didn't change the resolution and they don't get downloaded from different sources. iCloud Photos is disabled (photostream is on, but I don't think that's a problem). I selected the "Recents (All)" album als backup album.

**Comment by alextran1502** [comment]
Do you use the Share Album feature of Apple Photos app?

**Comment by alextran1502** [comment]
Can you help take a screenshot of your photos app settings?

**Comment by dsippel** [comment]
here are my settings:

![IMG_3727](https://user-images.githubusercontent.com/103022385/233183970-273e73f6-594b-4d9a-bd31-ce43bc3573e5.png)
![IMG_3728](https://user-images.githubusercontent.com/103022385/233183975-0c41586a-d5a2-4057-8e34-62c8c93c597d.png)

I have one shared Album I was invited to. I disabled it now in settings, logged out of immich in the app and back in. No change. Still duplicates.

**Comment by alextran1502** [comment]
hmm very very strange. What is your iPhone model and iOS version?

**Comment by dsippel** [comment]
OK, I think I found the problem! Disabling the PhotoStream made the duplicates disappear! 🙂 Thanks for all the help and effort! If you need any more information from me, let me know!

**Comment by alextran1502** [comment]
OHHHH very good data point. Thank you!!!

**Comment by alextran1502** [comment]
Do you know if those duplicated photos can be uploaded to Immich?

**Comment by dsippel** [comment]
They were not uploaded. Somehow the photostream was the reason that the local photos were displayed as duplicates. None of these with the lower resolution were uploaded. Or what do you mean?

**Comment by alextran1502** [comment]
I mean can they be uploaded at all?

**Comment by dsippel** [comment]
Nope

**Comment by yoyotueur** [comment]
I have the same issue. But I don't have the photostream setting in Setting>Photos

**Comment by jeff15110168** [comment]
> I have the same issue. But I don't have the photostream setting in Setting>Photos

I also have the same issue. I don't have photostream option but i do use shared photo libraries a lot so turning it off is not an option.

I currently have every single "local" folder selected for backup. Is that a bad idea and should i just select "recent" for backup that then captures all the files on my local iphone (i don't want to backup any shared albums)

**Comment by czar** [comment]
Hi, my phone is having the same issues as the original poster (seeing a local and the backed up copy.)  I just set up Immich yesterday and installed the Android app from F-Droid. How was this issue resolved? Thank you.

**Comment by christopherarter** [comment]
I'm still having this issue on a Pixel 8a actually, immich running [v1.126.1](https://github.com/immich-app/immich/releases/tag/v1.126.1)

**Comment by alextran1502** [comment]
@christopherarter there is a known issue of the Pixel phone can potentially wrangle the local ID causing weirdness happen. The only work around right now is to reinstall the qpp so it can reindex

**Comment by christopherarter** [comment]
Thank you @alextran1502 ! I'll give that a shot.

**Comment by konradwalsh** [comment]
I'm having this issue and I've reinstalled the asp after clearing the storage. 
Samsung S22 ultra


Happy to test any suggestions

**Comment by vtosevski** [comment]
Hi everyone,
Apologies for opening the old thread but I have the same/similar issue and don't quite get the solution. I have Xiaomi 14 phone and see duplicate images on my mobile, similar as above, with 2 different status icons, ticked cloud and empty cloud. However, I also see those images as exact duplicates on my timeline through my web browser - based on image information, they're identical. Is there anything I can do about this?
Thanks!

**Comment by PubBow** [comment]
Hi,

I'm having the same issue:

![Image](https://github.com/user-attachments/assets/c26557d0-f140-4990-b49b-e9a4e3f0bd24)

I'm currently on 1.132.3.  The upload directory is mounted to an external library if that makes any difference.

**Comment by Ralith** [comment]
Reinstalling the app seems to have fixed this on my Pixel 9, after backing up from a Pixel 6 triggered it on both devices.

**Comment by pawjwp** [comment]
I've tried reinstalling a few times with no luck. It seems to affect two months of my photos, but nothing newer, so it's something I can live with, especially since the photos aren't being uploaded twice. Still, I'd love a fix.

**Comment by schontho** [comment]
I have the same problem here. It looks like whe indexed or where the meta data has extracted already and the original file does not match. I don't have it on new files but on all older files I Uploaded from the app (current android version).

**Comment by PubBow** [comment]
I deleted and reinstalled the app and the issue is still there (iOS).

This issue is showing as closed, I wonder if admin are aware we are commenting on it!

**Comment by konradwalsh** [comment]
good point!!!

> I deleted and reinstalled the app and the issue is still there (iOS).
> 
> This issue is showing as closed, I wonder if admin are aware we are commenting on it!

**Comment by rizkyarlin** [comment]
In my case I use [icloudpd](https://github.com/icloud-photos-downloader/icloud_photos_downloader) to download all my photos from icloud to my server to save time, because most of my original photos not on my phone. 

I then use [immich-go](https://github.com/simulot/immich-go) to upload the photos to immich. 

Now when I tried to enable the album backups on the iOS app, I ran into the same problem of duplicate photos.


OP said:
> OK, I think I found the problem! Disabling the PhotoStream made the duplicates disappear! 🙂 Thanks for all the help and effort! If you need any more information from me, let me know!

@alextran1502 can you reopen this issue since PhotoStream setting is not in the iOS Photos settings anymore?

**Comment by rizkyarlin** [comment]
ths immich_server log my have some clue why the uploads / file consolidations failed.
```bash
immich_server            | [Nest] 23  - 10/18/2025, 2:54:27 PM   ERROR [Api:Error: EIO: i/o error, close~03ozr0gm] Unknown error: Error: EIO: i/o error, close
immich_server            | [Nest] 23  - 10/18/2025, 2:54:28 PM   ERROR [Api:ErrorInterceptor~ztyq94c6] Unknown error: Error: ENOENT: no such file or directory, mkdir '/data/upload/c9d11eb6-5698-40fa-b7ac-31dbf45b2e54/93/09'
immich_server            | Error: ENOENT: no such file or directory, mkdir '/data/upload/c9d11eb6-5698-40fa-b7ac-31dbf45b2e54/93/09'
immich_server            |     at mkdirSync (node:fs:1363:26)
immich_server            |     at StorageRepository.mkdirSync (/usr/src/app/server/dist/repositories/storage.repository.js:130:37)
immich_server            |     at AssetMediaService.getUploadFolder (/usr/src/app/server/dist/services/asset-media.service.js:80:32)
immich_server            |     at /usr/src/app/server/dist/middleware/file-upload.interceptor.js:131:52
immich_server            |     at callbackify (/usr/src/app/server/dist/middleware/file-upload.interceptor.js:72:31)
immich_server            |     at FileUploadInterceptor.destination (/usr/src/app/server/dist/middleware/file-upload.interceptor.js:131:16)
immich_server            |     at DiskStorage._handleFile (/usr/src/app/server/node_modules/.pnpm/multer@2.0.2/node_modules/multer/storage/disk.js:31:8)
immich_server            |     at FileUploadInterceptor.handleFile (/usr/src/app/server/dist/middleware/file-upload.interceptor.js:145:29)
immich_server            |     at /usr/src/app/server/node_modules/.pnpm/multer@2.0.2/node_modules/multer/lib/make-middleware.js:158:17
immich_server            |     at callbackify (/usr/src/app/server/dist/middleware/file-upload.interceptor.js:72:16)
immich_server            | [Nest] 23  - 10/18/2025, 2:54:28 PM   ERROR [Api:ErrorInterceptor~zwm2f1g8] Unknown error: Error: ENOENT: no such file or directory, mkdir '/data/upload/c9d11eb6-5698-40fa-b7ac-31dbf45b2e54/98/aa'
immich_server            | Error: ENOENT: no such file or directory, mkdir '/data/upload/c9d11eb6-5698-40fa-b7ac-31dbf45b2e54/98/aa'
immich_server            |     at mkdirSync (node:fs:1363:26)
immich_server            |     at StorageRepository.mkdirSync (/usr/src/app/server/dist/repositories/storage.repository.js:130:37)
immich_server            |     at AssetMediaService.getUploadFolder (/usr/src/app/server/dist/services/asset-media.service.js:80:32)
immich_server            |     at /usr/src/app/server/dist/middleware/file-upload.interceptor.js:131:52
immich_server            |     at callbackify (/usr/src/app/server/dist/middleware/file-upload.interceptor.js:72:31)
immich_server            |     at FileUploadInterceptor.destination (/usr/src/app/server/dist/middleware/file-upload.interceptor.js:131:16)
immich_server            |     at DiskStorage._handleFile (/usr/src/app/server/node_modules/.pnpm/multer@2.0.2/node_modules/multer/storage/disk.js:31:8)
immich_server            |     at FileUploadInterceptor.handleFile (/usr/src/app/server/dist/middleware/file-upload.interceptor.js:145:29)
immich_server            |     at /usr/src/app/server/node_modules/.pnpm/multer@2.0.2/node_modules/multer/lib/make-middleware.js:158:17
immich_server            |     at callbackify (/usr/src/app/server/dist/middleware/file-upload.interceptor.js:72:16)
immich_server            | [Nest] 23  - 10/18/2025, 2:54:40 PM     LOG [Api:EventRepository] Websocket Connect:    3aJvjyAlPu168mA5AABB
```
