### ISSUE TITLE
[BUG] Sony RAW (.ARW) unsupported

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2156]
### The bug

I found https://github.com/immich-app/immich/issues/1109, but do not believe the resolution is fair. The Sony RAW format is very popular and is a major blocker for adoption.

The linked [libvips issue](https://github.com/libvips/libvips/issues/1304) suggests there is support for the file format, but `magickload` must be used instead.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.52.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

### Additional information

N/A

**Comment by samip5** [comment]
Could I have an example file to test with?

**Comment by andrewgdunn** [comment]
Here is a link to an example JPG and RAW file: https://photos.app.goo.gl/fxjPFHKZ274LR6c17

**Comment by samip5** [comment]
> Here is a link to an example JPG and RAW file: https://photos.app.goo.gl/fxjPFHKZ274LR6c17

Unfortunately, Google Photos will not let me download the .ARW file. Those both come downloaded as JPEG.

**Comment by uhthomas** [comment]
@samip5 Please see this ARW image: https://github.com/uhthomas/immich2156/blob/main/_DSC2642.ARW.

**Comment by uhthomas** [comment]
So I've been looking into this and I think it should actually be a really small change, though I did come across a major caveat. Image Magick on Alpine is compiled for ufraw, which is not a valid package on Alpine. The base image may need to use debian instead, at least until the upstream issue is fixed.

See https://gitlab.alpinelinux.org/alpine/aports/-/issues/14957.

**Comment by jrasm91** [comment]
Just FYI - On my backlog is to finish #2198, which is trying to integrate darktable-cli which has general support for many different raw formats.

**Comment by uhthomas** [comment]
> Just FYI - On my backlog is to finish #2198, which is trying to integrate darktable-cli which has general support for many different raw formats.

I wouldn't worry about it. It looks like the alpine authors have already recompiled imagemagick with libraw support. The change for Immich is then just including that package. I think this is preferable to relying on multiple cli tools and keeps the code cleaner. The change should also be less risky.

**Comment by jrasm91** [comment]
What does this imply? Will this change add general support for RAW files? If so, I agree that would be preferable.

**Comment by uhthomas** [comment]
I believe it does, yes. It should support: https://www.libraw.org/supported-cameras.

**Comment by jrasm91** [comment]
Great, I'll keep putting it off then :laughing: and maybe it will resolve itself.
