### ISSUE TITLE
[BUG] Photo upload fails from last f-droid app on current server

### ISSUE THREAD

**Issue by johannesk** [immich-app/immich#2178]
### The bug

The last app version on F-Droid which can be started is 1.43.0 (due to https://github.com/immich-app/immich/issues/1815).

This version can not upload onto a current server (1.52.1).

It seems as the upload metadata properties have changes names: (createdAt -> fileCreatedAt, modifiedAt -> fileModifiedAt).

Here is an excerpt from a tcpdump of the failing HTTP request:

    POST /asset/upload HTTP/1.1
    [...]
    --dart-http-boundary-OqL7eazkbRVmdYZyIX1GTAJbifnAJqok6s9_fyo+mHL1K1aDn0-
    content-disposition: form-data; name="createdAt"
    
    2023-03-24T18:33:35.000
    --dart-http-boundary-OqL7eazkbRVmdYZyIX1GTAJbifnAJqok6s9_fyo+mHL1K1aDn0-
    content-disposition: form-data; name="modifiedAt"
    
    2023-03-24T18:33:35.000
    --dart-http-boundary-OqL7eazkbRVmdYZyIX1GTAJbifnAJqok6s9_fyo+mHL1K1aDn0-
    [...]
    HTTP/1.1 400 Bad Request
    X-Powered-By: Express
    Content-Type: application/json; charset=utf-8
    Content-Length: 125
    ETag: "7d-r5hxlec+PkfZaLnqCA5zKJCKY5U"
    Date: Wed, 05 Apr 2023 14:58:59 GMT
    Connection: close
    
    {"statusCode":400,"message":["fileCreatedAt should not be empty","fileModifiedAt should not be empty"],"error":"Bad Request"}

This bug is especially problematic, because no Immich app version available on FDroid can upload to a current server.

Better compatibility between already released app and server versions could be achieved by accepting both "createdAt" and "fileCreatedAt" as well as "modifiedAt" and "fileModifiedAt". Such problems can be mitigated in the future by refraining from such insignificant API changes.

### The OS that Immich Server is running on

Debian Bullseye

### Version of Immich Server

1.52.1

### Version of Immich Mobile App

1.43.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
*
```

### Your .env content

```Shell
*
```

### Reproduction steps

```bash
*
```

**Comment by bo0tzz** [comment]
As Immich is still under heavy development, API changes are expected and we're not intending to maintain significant backwards compatibility at this time.
