### ISSUE TITLE
[BUG] Fresh mobile client showing a popup of server update before logging-in to any server

### ISSUE THREAD

**Issue by samip5** [immich-app/immich#2183]
### The bug

Fresh mobile client shows an popup about server version before logging-in to any server

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

v1.53.0

### Version of Immich Mobile App

v1.52.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Download Immich Android app from Play Store
2. Start it up
3. See popup before able to login
```

### Additional information

I don't think this should happen before logging-in.

https://photos.skylab.fi/share/f2e26844e3f8c9b9affb0dfe3f8f2415af30c1255b6088a05ae0db5b5b8f1a0da8a14983cb7749b7000e1d2ed5d779cadfc0 (expires after 30d)

**Comment by DX37** [comment]
Confirmed on 1.57.0

**Comment by alextran1502** [comment]
I believe this is fixed, let me know if it isnt
