### ISSUE TITLE
[BUG] immich-machine-learning doesn't start on Pi4/aarch64

### ISSUE THREAD

**Issue by arminus** [immich-app/immich#2226]
### The bug

Withe the default docker-compose.yml, immich-machine-learning doesn't start on a Pi4/64 (or rather restarts continuously without any docker logs).

Starting the container manually like this:

```
docker run --env-file .env --volume ${UPLOAD_LOCATION}:/usr/src/app/upload --volume $(pwd)/modelcache:/cache ghcr.io/immich-app/immich-machine-learning:release /bin/sh -c "while true; do sleep 2; done"
```
I managed to exec into it and try to start the entrypoint which reveals this:

root@e78f93eee886:/usr/src/app# gunicorn src.main:server
Illegal instruction (core dumped)

Narrowing this down further (inside the container):

root@cbf4faadf806:/usr/src/app# python3
Python 3.10.11 (main, Apr  6 2023, 00:10:13) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from flask import Flask, request
>>> from transformers import pipeline
Illegal instruction (core dumped)

This ran ok with images from a couple of weeks ago on the same Pi4.

### The OS that Immich Server is running on

RaspberryPi4/aarch64

### Version of Immich Server

1.53.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
https://github.com/immich-app/immich/blob/main/docker/docker-compose.yml
```

### Your .env content

```Shell
https://github.com/immich-app/immich/blob/main/docker/example.env
```

### Reproduction steps

```bash
1. see above
2.
3.
...
```

**Comment by alextran1502** [comment]
Duplicated of #2221

**Comment by arminus** [comment]
#2221 seems to be about 32bit? I'm observing this on a 64bit Pi4 ...

**Comment by Lyokovic** [comment]
I have the same issue on rpi4 with arm64 OS.
This issue has nothing to do with #2221 where there is no docker image available for armv7. Here the docker image is pulled but crashes on startup, as detailed in the initial post.

**Comment by arminus** [comment]
> There may be an issue with arm64 on upstream python projects (pytorch/transformers/...) introduced after 2023-03-22.

right, as shown in my original post, python crashes when it tries to import transformers.

**Comment by jon-f-novastor** [comment]
I had the opposite on my Raspberry Pi 4b running Ubuntu 22.10 x64, in 1.53 the machine learning container was able to load and run but in 1.54 it just shows constantly restarting the container, when checking with 'docker ps', and doing a docker logs tail on that container doesn't show any status, but docker logs tail on immich_server keeps showing ml is not in a valid state. I had to disable ml from the .yml and the .env file detailed in the FAQ about ml probably needs to be disabled on Rpi4.
