### ISSUE TITLE
[BUG] RAF not uploading via CLI

### ISSUE THREAD

**Issue by Thoroslives** [immich-app/immich#2259]
### The bug

Its a known issue that RAF files do not get imported via the CLI but the issue was closed, its still an issue.

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.53.0

### Version of Immich Mobile App

1.53.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. try to upload a RAF file with Bulk upload CLI
2. It says complete however files are not imported
```

**Comment by samip5** [comment]
CLI doesn't support RAF at the moment, web does.

**Comment by Thoroslives** [comment]
So will this get moved to be fixed?

**Comment by samip5** [comment]
Please create an issue about CLI at: https://github.com/immich-app/cli

**Comment by Thoroslives** [comment]
Done, thank you
