### ISSUE TITLE
[BUG] Live Photos broken in shared albums

### ISSUE THREAD

**Issue by tinju87** [immich-app/immich#2318]
### The bug

Live Photos are not working in the ios app or the website when someone uploaded (added) it in a shared album. Neither my personal pictures nor pictures added by a friend work. The live photo button is there however if you click it manually a red exclamation mark will appear exclamation ❗️
However for the same picture the Live photo feature will work (only) in the main timeline.

### The OS that Immich Server is running on

Docker-compose on Portainer on Ubuntu LCX on Proxmox

### Version of Immich Server

v1.54.1

### Version of Immich Mobile App

v154.0 build 94

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Same as repo
```

### Your .env content

```Shell
Same as repo
```

### Reproduction steps

```bash
1. Create shared album with some Live Photos.
2. allow others to add/upload additional photos 
3. Upload additional Live Photos via the generated link.
4. Live Photo feature is broken im shared albums.
```

### Additional information

Everything is up to date so far.

**Comment by koiralasandesh** [comment]
I am facing the same issue. Attaching a few images for convenience.

When loading the image, the screen gets stuck on loading animation.
<img width="1475" alt="Screenshot 2023-06-20 at 3 51 44 PM" src="https://github.com/immich-app/immich/assets/29060857/f4a9b482-0e24-4e6a-b17b-d1d73fd331e4">

It seems that the server is returning 403 when fetching the video for live photo in a shared album.

<img width="749" alt="Screenshot 2023-06-20 at 4 08 38 PM" src="https://github.com/immich-app/immich/assets/29060857/6f3fafa3-0b0d-47a7-aa04-39812516ba7e">

<img width="1512" alt="Screenshot 2023-06-20 at 4 25 16 PM" src="https://github.com/immich-app/immich/assets/29060857/4f47470d-528e-4aa2-9774-6bf77ad90951">

<img width="538" alt="Screenshot 2023-06-20 at 4 28 45 PM" src="https://github.com/immich-app/immich/assets/29060857/c2195392-d7a8-445f-a9dd-df5f7b9eca43">
