### ISSUE TITLE
[BUG] MOV type videos not playing in Android after Transcode Video (h264) in both Web and Mobile app

### ISSUE THREAD

**Issue by w00tlarr** [immich-app/immich#2334]
### The bug

After uploading a video (HEVC from an iPhone) via Immich web - video loads fine in Android Web and Mobile app.

After Transcode Video job, somehow some of my MOV videos, not all of them cannot be played via the Web and Mobile app only in Android. Though Windows MS Edge browser is fine. And VLC mobile android app is fine after a long press - save as locally (not the via the download feature).

### The OS that Immich Server is running on

Docker (Alpine Linux in Windows Hyper-V)

### Version of Immich Server

1.54.1

### Version of Immich Mobile App

1.54.1

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
same as default
```

### Your .env content

```Shell
same as default
```

### Reproduction steps

```bash
1. Upload a new MOV video (HEVC h265 from iPhone).
2. Paused the Transcode Job b4 it transcoded it.
3. Verified that MOV is able to be played in Android Web and Mobile App as-is
4. Unpause, let Transcode Job convert it with default Immich FFMpeg settings (h264)
5. Video is now not able to be played via Android Web and Mobile App.
```

**Comment by w00tlarr** [comment]
https://user-images.githubusercontent.com/126688857/234463172-293a6128-77ab-41e3-9ec7-ae8b48b113be.mp4

**Comment by w00tlarr** [comment]
sample encoded video uploaded

**Comment by jrasm91** [comment]
In recent months several bugs have been fixed related to transcoding. Closing as this is most likely resolved. Feel free to open it if it is still an issue.
