### ISSUE TITLE
[TECH-DEBT] scroll performance in view other than timeline

### ISSUE THREAD

**Issue by alextran1502** [immich-app/immich#2337]
We query all assets belonging to the albums and archives in their respective views with only lazy loading. There is no virtual scroll on these views which affects performance when there are more than thousands of assets in an album. We will need a better way to handle these cases

**Comment by jrasm91** [comment]
We can take the main timeline approach or Google's approach of loading the next page on scroll (no virtual scroll). I think (1) better, but (2) would be easier to implement as it's just pagination.

**Comment by SitramSoft** [comment]
I would like to see this performance issue addressed as soon as possible. It affects especially large albums.

**Comment by jrasm91** [comment]
Started working on this in #2464. Got it working well in archive and favorites, but albums have some extra complexity that needs to be refactored before it can be added there.
