### ISSUE TITLE
[BUG] OpenAPI Immich Server Spec - Client generation is not usable 

### ISSUE THREAD

**Issue by ckocyigit** [immich-app/immich#2341]
### The bug

I have generated a python client from the immich server openapi spec and noticed some flaws which I will list here:

- Content Types for AuthenticationApi.Login.login cannot handle response from server with 'charset=utf-8'
- Configuration is not generating 'access_token' attribute correctly
- e.g. Asset.downloadFile content type for generated client is expected to be "application/octet-stream" but "image/jpeg" is incoming
- TBD..

### The OS that Immich Server is running on

Unraid 6.12.0-rc2

### Version of Immich Server

1.54.1

### Version of Immich Mobile App

1.54.0 build.77

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
skip
```

### Your .env content

```Shell
skip
```

### Reproduction steps

```bash
1. Generate a client I would assume of any kind or for python
2. Try utilizing the client
3. Fail :()
```

**Comment by michelheusschen** [comment]
> * Content Types for AuthenticationApi.Login.login cannot handle response from server with 'charset=utf-8'

Are you saying the OpenAPI docs have the media type listed as `application/json`, but you're seeing a `Content-Type` header with the value `application/json; charset=utf-8` in the response? Having the charset explicitly defined shouldn't lead to issues with UTF-8 also being the default for JSON responses.

> * Configuration is not generating 'access_token' attribute correctly

I'm guessing you're trying to use the Python snippet generated by the API docs on the [website](https://immich.app/docs/api), right? It doesn't seem to include the cookie header, but it is defined in our [OpenAPI spec](https://github.com/immich-app/immich/blob/main/server/immich-openapi-specs.json#L3459-L3463). It looks like a limitation in the package that is being used for generating these docs, if you select bearer auth the correct header is added.

> * e.g. Asset.downloadFile content type for generated client is expected to be "application/octet-stream" but "image/jpeg" is incoming

`application/octet-stream` is the default content type for indicating a binary file and is often used for unknown file types. It could be further specified with something like `image/*` and `video/*` but I don't think it's a huge issue.

Below an example in Python that showcases a few different ways for authentication:

```python
import requests

url = "http://localhost:2283/api/album"

payload={}
headers = {
	'Accept': 'application/json',

	# Choose one of these headers
	'Authorization': 'Bearer *access token*',
	'Cookie': 'immich_access_token=*access token*',
	'x-api-key': '*api key*'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)
```

**Comment by alextran1502** [comment]
Add api key in #2362 to potentially fix this issue
