### ISSUE TITLE
Bug: Mobile app's video playback progress bar is conflicting with a button

### ISSUE THREAD

**Issue by samip5** [immich-app/immich#2389]
### The bug

There seems to be a little Fullscreen kind of a button very close to the progress bar preventing you from pressing it.

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

V1.54.1

### Version of Immich Mobile App

1.54.0 build.77

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
1. Open any video on Android
2. Start playback
3. See issue
```

### Additional information

![Screenshot_20230507-045154](https://user-images.githubusercontent.com/1703002/236653626-7cdd5b9d-6636-4fcc-a366-09fc4f65e4b8.png)

**Comment by oblivioncth** [comment]
I'm not sure if that button is the actual cause but I have the same problem. The track bar is not able to be interacted with in anyway and it's been like this for a while now, though wasn't on a previous version a number of releases back.

Not sure if it's related but the buttons that fade away when a video is playing can still be pressed even though they're hidden. For example, it's very easy to accidentally archive a video without even realizing it when trying to click the track bar if the press is slightly too low.
