### ISSUE TITLE
[BUG] Incorrect photo placement on map view

### ISSUE THREAD

**Issue by truppelito** [immich-app/immich#2410]
### The bug

Just updated Immich today to 1.55 and started playing around with the Map view (was a feature I was looking for, thank you!) and noticed the following:

<img width="1613" alt="Screenshot 2023-05-09 at 11 10 56" src="https://github.com/immich-app/immich/assets/1059798/142d6a38-41cd-4067-a1fd-9d54b75fe265">
<img width="1607" alt="Screenshot 2023-05-09 at 11 11 06" src="https://github.com/immich-app/immich/assets/1059798/7f1e0db1-139d-42ab-ab13-29cd5c43da02">

So there's two issues with these screenshots:
1. The items on the right (some are suspiciously close to the Latitude = 0 line) do not belong to those locations. I know where they were taken and they shouldn't be there. This could be a problem with the metadata in the photo/video files, but that seems unlikely. There are currently no metadata extraction jobs running, but 14 jobs failed, so maybe that's why.
2. The items on the right are in the "second copy" of the world to the right. I assume all items should be shown on the "main copy" of the world (where all other items are shown).

Let me know if I can help with anything else regarding these bugs.

### The OS that Immich Server is running on

Raspberry Pi 4, NAME="Debian GNU/Linux", VERSION="11 (bullseye)"

### Version of Immich Server

v1.55.0

### Version of Immich Mobile App

v1.54.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I'm using the https://immich.app/docs/install/all-in-one compose file.
```

### Your .env content

```Shell
What the all-in-one file has, with the necessary changes for IPs/ports, databases
```

### Reproduction steps

```bash
See above.
```

**Comment by Zegorax** [comment]
I tested it on my side and have the same issue as well

**Comment by michelheusschen** [comment]
Are you still having this issue? If you do, can you the coordinates for some of these pictures?

**Comment by Pheggas** [comment]
It **should** be solved by [this commit](https://github.com/immich-app/immich/pull/2648/commits). Just update to latest version and see. Maybe re-upload those assets to remap coordinates.

**Comment by michelheusschen** [comment]
Yes I've also added a bounds check, so this should be solved. Re-upload isn't needed, running the extract metadata job in `All` mode will correct the coordinates.

**Comment by Pheggas** [comment]
I'm glad the issue is resolved!
