### ISSUE TITLE
[BUG] Wrong file name shown on mobile

### ISSUE THREAD

**Issue by Sherlock1979** [immich-app/immich#2461]
### The bug

Ehn you click the 'Information' button in the mobile app, the internal (uuid) filename is shown. The same functionality on the web shows the correct, original filename.

### The OS that Immich Server is running on

Debian 

### Version of Immich Server

1.55.1

### Version of Immich Mobile App

1.55

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Irrelevant
```

### Your .env content

```Shell
Irrelevant
```

### Reproduction steps

```bash
1. Open any image in the mobile app.
2. Click on the Information icon.
3. Observe the file name.
```

**Comment by alextran1502** [comment]
Is there a specific photo with that issue you can share for debugging purposes?

**Comment by Sherlock1979** [comment]
It only happens while the photos are in the 'upload' folder. Once they are moved to the 'library', everything is fine.

Still, the behaviour is inconsistent but it's a very rare case. Do you want to fix it or just close this issue? Either way is fine for me.

Thank you!

**Comment by raisinbear** [comment]
As far as I can determine, it always happens with freshly uploaded images. Also, location information and so on are missing. A force close and reopen fixed it for me when testing but usually I don’t pay attention and it’s corrected anyways after a couple of close / open cycles.

**Comment by alextran1502** [comment]
stale, please reopen if still applicable
