### ISSUE TITLE
[BUG] Docker Secrets are not supported for all sensitive environment variables

### ISSUE THREAD

**Issue by mark-monteiro** [immich-app/immich#2465]
### The bug

Docker secret support (https://github.com/immich-app/immich/issues/14) was partially implemented in https://github.com/immich-app/immich/pull/1254, but only for PostgreSQL environment variables. There are a few other sensitive environment variables that would benefit from docker secret support that were missed in the original implementation:

- TYPESENSE_API_KEY
- REDIS_USERNAME
- REDIS_PASSWORD
- others?

### The OS that Immich Server is running on

Docker (Ubuntu host)

### Version of Immich Server

v1.55.1

### Version of Immich Mobile App

v1.55.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by mark-monteiro** [comment]
After a bit more investigation, neither Typesense nor Redis support Docker secrets in the compose file for the environment variables mentioned. Which makes supporting them in Immich a bit useless since they'll need to be exposed as environment variables for the other services anyways. I will close this issue.

**Comment by abhi-chakrab** [comment]
@mark-monteiro - Is there a possibility to at least add the REDIS_USERNAME && REDIS_PASSWORD as a secret. It is possible to use a workaround as per the below suggestion from the official repo:
https://github.com/docker-library/redis/issues/46#issuecomment-335326234

I have also created a PR for the basic script changes - https://github.com/immich-app/immich/pull/3282
