### ISSUE TITLE
[BUG] Search order when searching for objects seems random

### ISSUE THREAD

**Issue by Quadrubo** [immich-app/immich#2493]
### The bug

When searching for objects such as "Rollercoaster" or "Pizza" the order of the objects seems to be completely random. When I click on any preexisting category in the UI as it is the case with "Pizza" the search is ordered by date as I'd expect.

Example for the **search** of Pizza: August 2021 -> July 2021 -> November 2021 -> September 2021 -> November 2022 -> May 2022 -> September 2021 -> ...
Example for the **category** of Pizza: March 2023 -> February 2023 -> January 2023 -> ...

This happens on both the web and the mobile app.

### The OS that Immich Server is running on

Unraid 

### Version of Immich Server

v1.56.2

### Version of Immich Mobile App

v1.56.0 build.79

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Using the Unraid image and shouldn't matter.
```

### Your .env content

```Shell
Using the Unraid image and shouldn't matter.
```

### Reproduction steps

```bash
1. Open the Immich app or the web interface.
2. Click on the category of a random "Thing" in the UI and check the dates of the images.
3. Search for that exact "Thing" in the search bar instead and check the dates of the images.
```

**Comment by bo0tzz** [comment]
The search is ordered by relevance. More sort options are planned to be added later.

**Comment by Quadrubo** [comment]
Ah okay thanks :) any feature or issue where this is tracked?
