### ISSUE TITLE
[BUG] Running the face recognization job results in "Failed 1" after a minute or so.

### ISSUE THREAD

**Issue by florihupf** [immich-app/immich#2505]
### The bug

Nothing in the logs as I can see.

Retrying results in the same thing.

### The OS that Immich Server is running on

Truenas Scale

### Version of Immich Server

v1.56.2

### Version of Immich Mobile App

v1.56.0 (96)

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Stock
```

### Your .env content

```Shell
Stock
```

### Reproduction steps

```bash
- After upgrading from v1.55.0 kick of a Face Recognition Job from the Admin panel.
- Wait for a minute or so.
- Now it says "Failed 1".
```

Note that there also was just a single job queued, not any more.  Pointing out, because the other job types usually queue more jobs at once.

### Additional information

<img width="836" alt="Screenshot 2023-05-21 at 15 51 26" src="https://github.com/immich-app/immich/assets/4993621/2908c5c3-305d-4895-8fb1-1d7ec323ddef">

**Comment by alextran1502** [comment]
Can you help check your microservices log and machine learning container log?

**Comment by florihupf** [comment]
Right now I see 

```
INFO:     Waiting for application startup.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
The `max_size` parameter is deprecated and will be removed in v4.26. Please specify in `size['longest_edge'] instead`.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
/opt/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:54: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'
  warnings.warn(
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: /cache/models/buffalo_l/1k3d68.onnx landmark_3d_68
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: /cache/models/buffalo_l/2d106det.onnx landmark_2d_106
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /cache/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: /cache/models/buffalo_l/genderage.onnx genderage
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /cache/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3003 (Press CTRL+C to quit)
```

In the machine learning container.  Will see if anything gets added.

**Comment by florihupf** [comment]
The micro services container says:

```
[Nest] 1  - 05/21/2023, 4:45:11 PM     LOG [MetadataExtractionProcessor] Reverse Geocoding Initialized

<--- Last few GCs --->

[1:0x7f406a599300]   201293 ms: Mark-sweep 4045.5 (4132.9) -> 4030.9 (4134.2) MB, 4208.1 / 0.0 ms  (average mu = 0.083, current mu = 0.008) allocation failure; scavenge might not succeed
[1:0x7f406a599300]   205588 ms: Mark-sweep 4046.8 (4134.2) -> 4032.2 (4135.4) MB, 4243.3 / 0.0 ms  (average mu = 0.048, current mu = 0.012) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

Having 8GB allocated for the docker environment.  Maybe I need more?

**Comment by alextran1502** [comment]
Hmm @jrasm91 any idea? Are you running docker-compose file or all-in-one image on your Truenas?

**Comment by florihupf** [comment]
I am running in a docker container from TrueCharts that provides a docker compose environment, ie. docker inside docker.

I could try the all-in-one image.  Let me find it.

**Comment by florihupf** [comment]
> Right now I see
> 
> ```
> INFO:     Waiting for application startup.
> Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
> The `max_size` parameter is deprecated and will be removed in v4.26. Please specify in `size['longest_edge'] instead`.
> Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
> /opt/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:54: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'
>   warnings.warn(
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> model ignore: /cache/models/buffalo_l/1k3d68.onnx landmark_3d_68
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> model ignore: /cache/models/buffalo_l/2d106det.onnx landmark_2d_106
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /cache/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> model ignore: /cache/models/buffalo_l/genderage.onnx genderage
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /cache/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
> set det-size: (640, 640)
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://0.0.0.0:3003 (Press CTRL+C to quit)
> ```
> 
> In the machine learning container. Will see if anything gets added.

After a while these logs resulted in "Failed 2" on the admin panel.

**Comment by alextran1502** [comment]
I suggest you run the `docker-compose` route since it is the official support installation method. Truechart and the all-in-one image is community image.

**Comment by florihupf** [comment]
Yeah, for docker-compose to work on Truenas Scale, you need the docker-compose image provided by TrueCharts, because Truenas Scale doesn't support docker-compose :(

**Comment by jrasm91** [comment]
Right now the way the "all" jobs work it needs to load every single asset into memory and then queue them. It looks like it runs out of memory doing that. How big is your library (number of assets)?

I think allocating more RAM would eventually fix it. We have a backlog todo to redo how this works so that we can load and process chunks at a time, which would reduce the need for so much ram. Other than allocating more RAM I'm not sure what else you can do in the short term.

**Comment by florihupf** [comment]
Right, my library is pretty large. I think more than 300GB and 10.000 assets.

**Comment by florihupf** [comment]
Error: Just checked 112k assets.

**Comment by jrasm91** [comment]
Yeah, unfortunately this is a limitation right now. If you have the ram for it you can temporarily increase it to queue the job and then reduce it again afterwards

**Comment by SiriusBlue5120** [comment]
I had this issue - see my comment at [#2468](https://github.com/immich-app/immich/discussions/2468#discussioncomment-5944529)

I eventually got over this limitation by allocating more RAM than I used to - 16 GB did the trick for me.

Also see my comment [here](https://github.com/immich-app/immich/discussions/2468#discussioncomment-5950462). I don't know too much about it to confirm or verify, but immich_microservices doesn't seem to be using more than 20-25% of the memory available to the Docker container.

**Comment by MattPhilpot** [comment]
> > 
> I eventually got it working by allocating more RAM than I used to - 16 GB did the trick for me.
> 

I will confirm increasing memory is the solution as well. Not the same configuration as @florihupf - using k3s  - but similar'ish library size of 80k assets and ~1.1TB of storage. 

Struggles with 8GB, running fine when I reserve 12GB. After the face recognition job is done, I'll probably up that reservation to 16-20GB.

**Comment by jrasm91** [comment]
Looks like @michelheusschen is implementing pagination for these "all" jobs, which should significantly reduce the memory consumption, at least for the all jobs. I believe it is will high in some situations (like full mobile sync)

**Comment by florihupf** [comment]
Super thanks for the quick fix, works great!
