### ISSUE TITLE
[BUG] Notification of successful upload despite error

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2531]
### The bug

The error is expected and fine, I'm still setting things up. Though, Immich should not claim the upload succeeded when it actually didn't.

![image](https://github.com/immich-app/immich/assets/9749173/f380f482-6619-44ca-927b-e0dfdf793099)

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

1.57.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
Upload a file and have the server return a 500.
```

### Additional information

```
[Nest] 1  - 05/23/2023, 11:01:02 AM   ERROR [ExceptionsHandler] ERR Error running script (call to 8f55ae4a3be429c6d38c5d5db3e80edf89197b64): @user_script:56: script tried accessing undeclared key
ReplyError: ERR Error running script (call to 8f55ae4a3be429c6d38c5d5db3e80edf89197b64): @user_script:56: script tried accessing undeclared key
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)
[Nest] 1  - 05/23/2023, 11:01:36 AM   ERROR [ExceptionsHandler] ERR Error running script (call to 8f55ae4a3be429c6d38c5d5db3e80edf89197b64): @user_script:56: script tried accessing undeclared key
ReplyError: ERR Error running script (call to 8f55ae4a3be429c6d38c5d5db3e80edf89197b64): @user_script:56: script tried accessing undeclared key
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)
```

**Comment by bo0tzz** [comment]
When uploading multiple assets with some successes we'd probably still want a message like this. Maybe changing the wording to "Upload complete" is sufficient?
