### ISSUE TITLE
[BUG] Data inconsistencies with failed uploads

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2532]
### The bug

Following from #2531, I noticed that the number of photos is > 0, even though the upload failed.

![image](https://github.com/immich-app/immich/assets/9749173/1dbbd80b-aa8d-49fe-bf5b-b042dadf2320)

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

1.57.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
Upload a file where the upload fails.
```

### Additional information

```
[Nest] 1  - 05/23/2023, 11:01:02 AM   ERROR [ExceptionsHandler] ERR Error running script (call to 8f55ae4a3be429c6d38c5d5db3e80edf89197b64): @user_script:56: script tried accessing undeclared key
ReplyError: ERR Error running script (call to 8f55ae4a3be429c6d38c5d5db3e80edf89197b64): @user_script:56: script tried accessing undeclared key
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)
[Nest] 1  - 05/23/2023, 11:01:36 AM   ERROR [ExceptionsHandler] ERR Error running script (call to 8f55ae4a3be429c6d38c5d5db3e80edf89197b64): @user_script:56: script tried accessing undeclared key
ReplyError: ERR Error running script (call to 8f55ae4a3be429c6d38c5d5db3e80edf89197b64): @user_script:56: script tried accessing undeclared key
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)
```

**Comment by samip5** [comment]
I think this is the result of your broken redis config.

**Comment by uhthomas** [comment]
> I think this is the result of your broken redis config.

Possibly? Though the issue still remains that immich then had inconsistent data. Nothing had been uploaded, and yet 2 photos were reported to be uploaded.

**Comment by samip5** [comment]
Yeah, but error handling around those edge cases is not the greatest to begin with.

**Comment by uhthomas** [comment]
Makes sense, how can we improve error handling? 

At this point in time I don't believe immich-server was even connected to redis, I could be wrong. I think I had TypeSense disabled and so immich started fine.

I think it's fair to suggest an upload should be rolled back if it fails to then push jobs into redis.

**Comment by jrasm91** [comment]
If the admin screens shows two images, there are two asset records in the database. Not sure what else to say here. We can track incorrect notification in the other bug. Unless there are not two records in the database this is functioning as designed.

If you don't see any photos on the website, it's because they don't have thumbnails yet, which you won't have until you fix your redis connection. Again, working as designed here.

**Comment by uhthomas** [comment]
> If the admin screens shows two images, there are two asset records in the database. Not sure what else to say here. We can track incorrect notification in the other bug. Unless there are not two records in the database this is functioning as designed.
> 
> If you don't see any photos on the website, it's because they don't have thumbnails yet, which you won't have until you fix your redis connection. Again, working as designed here.

Per https://github.com/immich-app/immich/issues/2531, I believe the uploads failed? Is that actually untrue? I'm feeling a bit confused now.

**Comment by bo0tzz** [comment]
It seems like that upload succeeded insofar as getting the asset into immich, but then returned an error when queueing the job to process it. The details of how to handle that can be covered in the other issue.
