### ISSUE TITLE
[BUG] "Unable to connect to the database" with the latest update 1.58

### ISSUE THREAD

**Issue by Thormir84** [immich-app/immich#2590]
### The bug

After the installation of the latest update (v1.58.0), my server is stuck in a bootloop.

I had updated my compose with the new strings, but nothing works.

The problem consists in two containers ("immich-database" and "immich-server"):

immich-database:

```
2023-05-28 06:47:19.908 UTC [35] ERROR:  column "checksum" of relation "assets" contains null values
2023-05-28 06:47:19.908 UTC [35] STATEMENT:  ALTER TABLE "assets" ALTER COLUMN "checksum" SET NOT NULL
```

immich-server:

```
[Nest] 1  - 05/28/2023, 6:48:17 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
QueryFailedError: column "checksum" of relation "assets" contains null values
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RequireChecksumNotNull1684328185099.up (/usr/src/app/dist/apps/immich/libs/infra/src/migrations/1684328185099-RequireChecksumNotNull.js:10:9)
    at async MigrationExecutor.executePendingMigrations 
```(/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)

### The OS that Immich Server is running on

Docker 5:24.0.2-1~debian.11~bullseye

### Version of Immich Server

v1.58.0

### Version of Immich Mobile App

NULL

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NULL
```

### Your .env content

```Shell
NULL
```

### Reproduction steps

```bash
NULL
```

### Additional information

NULL

**Comment by BEBU88** [comment]
I'm faced with the same error as well. I compared the compose file with the one here at github and they're the same.

**Comment by spupuz** [comment]
same error also for me unable to connect to database

**Comment by alextran1502** [comment]
You guys are the OG users of Immich with an older database that  contains some bad legacy data. Let me work on a procedure to help you all fix this issue

**Comment by alextran1502** [comment]
Ok, here is the fix

1. Leave everything running
2. Attach to the Postgres database container with the following command
```bash
docker exec -it immich_postgres bash
```
3. Connect to the immich's database
```bash
psql -U postgres -d immich
```
4. Check for files that has null checksum 
```bash
select a."originalPath" from assets a where a.checksum is null;
```
5. Here, you can go find those files and pull them aside so we can reupload them after removing them from the database.
6. Now we will delete the bad database entry
```bash
delete from assets a where a.checksum is null;
```
7. Now, can you restart the Immich stack, and it should work.
8. Reupload those files

**Comment by amnesiacsardine** [comment]
@alextran1502 I can confirm that fixed the issue for me

**Comment by Thormir84** [comment]
```
root@nas-casa:~# docker exec -it immich-database bash
root@d9cebe3d8739:/# psql -U postgres -d immich
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "postgres" does not existroot@d9cebe3d8739:/#
```

**Comment by FrankelJb** [comment]
> Ok, here is the fix
> 
>     1. Leave everything running
> 
>     2. Attach to the Postgres database container with the following command (assuming you are using the stock `.env` values for the database)
> 
> 
> ```shell
> docker exec -it immich_postgres bash
> ```
> 
>     3. Connect to the immich's database
> 
> 
> ```shell
> psql -U postgres -d immich
> ```
> 
>     4. Check for files that has null checksum
> 
> 
> ```shell
> select a."originalPath" from assets a where a.checksum is null;
> ```
> 
>     5. Here, you can go find those files and pull them aside so we can reupload them after removing them from the database.
> 
>     6. Now we will delete the bad database entry
> 
> 
> ```shell
> delete from assets a where a.checksum is null;
> ```
> 
>     7. Now, can you restart the Immich stack, and it should work.
> 
>     8. Reupload those files

Is there a step missing between 6 and 7. "Put the moved files back?"

**Comment by Thormir84** [comment]
Ok, the fix worked for me!

Now all run fine!

Thanks!

**Comment by BEBU88** [comment]
Thank you very much @alextran1502 fixed worked!

**Comment by paulmorabito** [comment]
Thanks, works for me now!

**Comment by etnoy** [comment]
Thanks team for fixing this so quickly. I really thought I'd made sure that all OG users had checksums on all assets but obviously I was wrong

**Comment by aruhier** [comment]
I've also hit the problem because I guess my Immich install was a bit old.

@alextran1502: as it requires a manual intervention with the migration, and it happens when migrating from 1.57.1 to 1.58.0, what do you think about adding a short warning in the releases notes of 1.58.0 about this bug and your solution from comment https://github.com/immich-app/immich/issues/2590#issuecomment-1566104816 so it is more obvious?

Thanks!

**Comment by alextran1502** [comment]
@Sophtli The files without checksum are most likely duplicated (that's why they didn't have the checksum when we implemented the checksum mechanism), so re-uploading those assets is precautionary advice. You can proceed to the delete query.

**Comment by Sophtli** [comment]
> @Sophtli The files without checksum are most likely duplicated (that's why they didn't have the checksum when we implemented the checksum mechanism), so re-uploading those assets is precautionary advice. You can proceed to the delete query.

Okay, that makes sense, thank you! Will immich automatically delete the removed database entries from the disk or will the files just stay there unused?
