### ISSUE TITLE
[BUG] Mobile shows cloud-sync error icon, despite cloud-sync being fine.

### ISSUE THREAD

**Issue by yurividal** [immich-app/immich#2591]
### The bug

Every time I open immich, the app shows the cloud icon with the error symbol on top, (on the top right corner).
When I go into the settings, it "realizes" the camera folder is set to sync, and realizes it's fully synced. Takes about 1 or 2 seconds for it to "realize". When I go back to the home screen, the cloud icon is normal.

See attached video for demonstration 

![Screenshot_20230528_075343](https://github.com/immich-app/immich/assets/8555749/e0beed17-4241-4c56-b55d-c49723a065b5)

https://github.com/immich-app/immich/assets/8555749/4d727ee4-de80-47dc-809e-0c243a5a9e0f

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

1.58.0

### Version of Immich Mobile App

1.58.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Same as github. Works fine.
```

### Your .env content

```Shell
Same as instructed by github. Works fine.
```

### Reproduction steps

```bash
1. Kill mobile app (not needed, but just to make sure you open the app fresh)
2. Look at cloud icon on top right 
3. Go into settings
4. GO back to main window
...
```

### Additional information

/

**Comment by alextran1502** [comment]
Ah, the cloud icon to indicate if you have the auto backup on or not, it doesn't relate to the folders being fully synced. But this is a bug that it doesn't show until you get to the backup screen.

**Comment by yurividal** [comment]
Yes, that's what I meant. Sorry if I didn't express exactly what the icon was supposed to mean.
So, is this a known bug? Is there a duplicate bug report? I'm happy to close this issue if so.

**Comment by alextran1502** [comment]
Hello is this issue still relevance? if not, can you help me close it?

**Comment by yurividal** [comment]
@alextran1502 no, this has not been fixed yet. The behaviour you describe in the quote bellow is still happening. 

> Ah, the cloud icon to indicate if you have the auto backup on or not, it doesn't relate to the folders being fully synced. But this is a bug that it doesn't show until you get to the backup screen.
