### ISSUE TITLE
[BUG] Two-pass encoding `ffmpeg` log files persist

### ISSUE THREAD

**Issue by raisinbear** [immich-app/immich#2600]
### The bug

Thanks for all the great updates in the past few weeks! This thing is really taking off 😀

This issue is nothing serious, but should be noted. I just messed with the two pass video encoding feature (I'm using h264, but suppose it is the same for other codecs) and found a `ffmpeg` 1st pass log file in the `encoded-video` folder after successful encoding. This file is not needed anymore and persists even when deleting the uploaded video.

![grafik](https://github.com/immich-app/immich/assets/68740188/3893cf78-c5f1-4ab4-8d1b-1b0cd0dbd4fc)

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v.1.58.0

### Version of Immich Mobile App

v.1.58.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Enable two-pass encoding for videos.
2. Check `encoded-video` folder in server fs and find a second file with suffix `.mbtree` that is not needed anymore nor deleted when deleting the uploaded video.
```

**Comment by alextran1502** [comment]
@mertalev hi Mert, are you aware of this issue?

**Comment by mertalev** [comment]
Yes, I've noticed it as well. There can be one log file left for some reason. I'll look into why it doesn't get deleted.

**Comment by brighteyed** [comment]
> Yes, I've noticed it as well. There can be one log file left for some reason. I'll look into why it doesn't get deleted.

I've just investigated this issue. The following settings result in the creation of the `mbtree` files by `ffmpeg`
  * h264 video codec
  * 2-pass transcoding
  * constrained quality (i.e. max bitrate != 0)
  * `veryfast` or slower preset

That file remains on the disk after the video encoding is completed. I see 2 possible solutions: add `--no-mbtree` option or delete this file explicitly

**Comment by mertalev** [comment]
Thanks for investigating it @brighteyed ! It would be fine to just delete that file too since it apparently helps with compression.
