### ISSUE TITLE
[BUG] Can't delete empty album

### ISSUE THREAD

**Issue by clearminds** [immich-app/immich#2603]
### The bug

There is no way to delete an album that is emtpy, no buttons show up in the header.

### The OS that Immich Server is running on

RedHat

### Version of Immich Server

1.58.0

### Version of Immich Mobile App

1.58.0 build.81

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Unrelated
```

### Your .env content

```Shell
Unrelated
```

### Reproduction steps

```bash
1. Create an album
2. Add photos
3. Delete photos
4. Try and delete album
```

### Additional information

Works on mobile

**Comment by jrasm91** [comment]
I believe you can delete it from the albums page. There are three little dots that show up on hover in the top right corner of the album card.
