### ISSUE TITLE
[BUG] email validation is too strict

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2667]
### The bug

Emails are notoriously difficult to validate. It should simply check whether an `@` is present, rather than trying to be too smart. The email `admin@localhost` is absolutely valid, and yet Immich will reject it.

```
{"statusCode":400,"message":["email must be an email"],"error":"Bad Request"}
```

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.59.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

### Additional information

N/A

**Comment by samip5** [comment]
While I agree with that, there may be an issue with oauth if it's not strict.

**Comment by alextran1502** [comment]
I agree with @samip5. I think your email example is not valid. If you have something like `user@localhost.com` it would be valid

![image](https://github.com/immich-app/immich/assets/27055614/97e67930-1a22-49f5-8dc1-b6beeb080c43)

**Comment by uhthomas** [comment]
Yep, would be happy to do so. Would you mind reopening the issue for tracking?

**Comment by uhthomas** [comment]
FWIW, it looks like the package `class-validators` depends on https://www.npmjs.com/package/validator for validation. 

The relevant section suggests `require_tld` should be set to false.

isEmail(str [, options]) | check if the string is an email.options is an object which defaults to { allow_display_name: false, require_display_name: false, allow_utf8_local_part: true, require_tld: true, allow_ip_domain: false, domain_specific_validation: false, blacklisted_chars: '', host_blacklist: [] }. If allow_display_name is set to true, the validator will also match Display Name <email-address>. If require_display_name is set to true, the validator will reject strings without the format Display Name <email-address>. If allow_utf8_local_part is set to false, the validator will not allow any non-English UTF8 character in email address' local part. If require_tld is set to false, email addresses without a TLD in their domain will also be matched. If ignore_max_length is set to true, the validator will not check for the standard max length of an email. If allow_ip_domain is set to true, the validator will allow IP addresses in the host part. If domain_specific_validation is true, some additional validation will be enabled, e.g. disallowing certain syntactically valid email addresses that are rejected by Gmail. If blacklisted_chars receives a string, then the validator will reject emails that include any of the characters in the string, in the name part. If host_blacklist is set to an array of strings and the part of the email after the @ symbol matches one of the strings defined in it, the validation fails. If host_whitelist is set to an array of strings and the part of the email after the @ symbol matches none of the strings defined in it, the validation fails.
-- | --
