### ISSUE TITLE
[Help]  High CPU Usage During Development Testing

### ISSUE THREAD

**Issue by neozhu** [immich-app/immich#2712]
### The bug

During my development testing, I have noticed that the CPU usage remains consistently high even when I am not performing any actions. I am unsure of the root cause of this issue and would appreciate any guidance on how to identify the process or application responsible for the high CPU usage in the web client project.

<img width="1138" alt="image" src="https://github.com/immich-app/immich/assets/1549611/bdd10047-f225-4af2-a22a-c534d47dc44d">

### The OS that Immich Server is running on

widnow docker desktop

### Version of Immich Server

1.6

### Version of Immich Mobile App

v1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
dev
```

### Your .env content

```Shell
for windows
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by alextran1502** [comment]
So you are using `make dev` to start up all containers, correct? Do you see any log in the immich-web container?

**Comment by neozhu** [comment]
Thank you for your prompt response, As I am developing on a Windows platform, I am not using the "make dev" command. Instead, I am starting up all containers using the command "docker-compose -f ./docker/docker-compose.dev.yml up --remove-orphans" for debugging purposes. I have checked the logs for the immich-web container and have not found any abnormalities. I am also puzzled as to why the CPU usage remains high even when I am not performing any actions.

**Comment by neozhu** [comment]
I found that running containers under Windows Docker Desktop has this problem, but it seems to work fine on Linux/Ubuntu. Does anyone else have the same issue as me?

**Comment by alextran1502** [comment]
> I found that running containers under Windows Docker Desktop has this problem, but it seems to work fine on Linux/Ubuntu. Does anyone else have the same issue as me?

This is very interesting, I've only performed development tasks on Linux so I don't have much experience troubleshooting this
