### ISSUE TITLE
[BUG] Delete dialog hangs when deleting many items from web client.

### ISSUE THREAD

**Issue by wittymap** [immich-app/immich#2718]
### The bug

When deleting many items, the delete dialog never closes and there is no apparent feedback to the user that the delete button has been pressed. If it is pressed again, an error is thrown.

Possible expected behaviors (any would be acceptable):
- Close dialog immediately and delete photos in background.
- Leave dialog up, gray out the button after clicked or something so that the user knows not to click it again. once the completion is complete, close the dialog.
- Show a progress bar showing progress towards deletion.

## Reproduction steps:

Browser: Firefox

Refresh `/photos` page to start from scratch.

Select a full date's worth of photos by clicking on the date header on the timeline (in this case ~2000 photos)
![firefox_qWWsYtBs6j](https://github.com/immich-app/immich/assets/119261743/1cd02069-397e-4339-ad73-6de9c151c350)

Click the delete button on the toolbar:
![image](https://github.com/immich-app/immich/assets/119261743/d1a636c3-6b76-491f-880f-483dc6795631)

Click the red delete button on the dialog that pops up. There is no response and the dialog does not close.
![firefox_BE6veVdSKv](https://github.com/immich-app/immich/assets/119261743/0c3bc936-e1b2-438b-a02f-6ce3346cb3c5)

If the button is clicked again, an error is thrown to the client:
![firefox_ssxl32oZV2](https://github.com/immich-app/immich/assets/119261743/3684002d-2954-4d19-8632-9790c8a7925d)

The dialog never disappears and the page just hangs here forever. However, if the page is manually refreshed, the photos were successfully deleted.

### The OS that Immich Server is running on

Windows 10

### Version of Immich Server

v1.60.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

**Comment by jrasm91** [comment]
While still not the fastest, the confirm button is now disabled after being clicked.
