### ISSUE TITLE
[BUG]: ImageViewerPage UX and Exif Panel strange interaction

### ISSUE THREAD

**Issue by xpwmaosldk** [immich-app/immich#274]
### Feature detail

RemotePhotoView in ImageViewerPage is interacting with Touch Events strangely.

Swipe events interact with both the image viewer and the Exif details panel. This causes strange behaviour when swiping around the screen as can be seen below in the attached videos.

### Platform

Mobile App

**Comment by zackpollard** [comment]
I'm not entirely sure what the issue is that your describing here is. Would you be able to provide a video of the issue you're describing?

**Comment by zackpollard** [comment]
Alright I understand the issue now. I'm going to change this to a bug ticket and will add more detail to the original message

**Comment by alextran1502** [comment]
I would say it is more prominent on the emulator, it is less noticeable like the first video you showed on a real device, have you had a chance to try it on a real device?

Regardless, I like how Google Photos UX on this page but my first try didn't go well so the current resolution is for functionality only, my hope is to get the same bottom sheet dragging  sometimes in the future

**Comment by xpwmaosldk** [comment]
I had a similar feeling on the device as well.
It becomes more prominent when dragged to the corner of the device.

If possible, I will try to change it by referring to Google Photos. :)

**Comment by spupuz** [comment]
I had this behavior too, slide from image to next wold be also cool

**Comment by alextran1502** [comment]
Solved
