### ISSUE TITLE
[BUG] no support for JPEG XL

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2743]
### The bug

[JPEG XL](https://jpeg.org/jpegxl/) seems to be coming more popular, with [Apple adding support](https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes) in the near future. It would be nice if Immich could support this format.

It looks like it _should_ be as simple as installing the [vips-jxl](https://pkgs.alpinelinux.org/package/edge/community/x86/vips-jxl) package. I'll take a look at doing this as I'm already working on #2156.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by clearminds** [comment]
Chrome is removing support though https://bugs.chromium.org/p/chromium/issues/detail?id=1178058#c406
