### ISSUE TITLE
[BUG] machine-learning and nginx should use alpine

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2752]
### The bug

Given everything else in Immich uses alpine, the machine-learning and nginx images should remain consistent. 

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by uhthomas** [comment]
With the nginx image, switching to alpine reduces the image size dramatically from 142.545772 MB to 46.124232 MB.

**Comment by mertalev** [comment]
Alpine for ML is a solid no since Python wheels depend on glibc while Alpine uses musl. This change would mean compiling every Python dependency, including very large ones like PyTorch.

**Comment by uhthomas** [comment]
Makes sense, I think that's all the reason I needed. I'll leave this open for #2754 but will de-scope ml.
