### ISSUE TITLE
[BUG] App does not playback vp9 encoded Video Thumbnails

### ISSUE THREAD

**Issue by akoyaxd** [immich-app/immich#2757]
### The bug

If I transcode my Video Thumbnails to vp9 they do not play back. I only head audio.

### The OS that Immich Server is running on

Debian with Docker

### Version of Immich Server

v.1.60.0

### Version of Immich Mobile App

v.1.60.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not applicable
```

### Your .env content

```Shell
not applicable
```

### Reproduction steps

```bash
1. Configure vp9 as the codec for Video Thumbnails
2. Upload a video
3. Try to playback the Video on an iPhone (Tested on Xs with iOS 16)
```

**Comment by bo0tzz** [comment]
The default codec is h264 for compatibility with the widest range of devices. Changing it is at your own risk as not all your devices might support the new codec.

@alextran1502 @jrasm91 thoughts on adding a warning like this to the settings page?

**Comment by jrasm91** [comment]
I think a warning or even just a link to the documentation site where we have more information about the feature and pros/cons of different options would possibly be even better.

**Comment by patrontheo** [comment]
I still have the same issue. 
Does anyone know if iOS is supposed to support VP9 ?
Thanks :)
