### ISSUE TITLE
[BUG] should use ESM instead of CJS

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2770]
### The bug

Immich currently uses Common JS, which causes some subtle issues. The general recommendation is to use ES modules where possible.

[This guide](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) looks helpful.

Specifically this would allow using import statements consistently, rather than the strange `import()` function like was required for #2649.

```ts
import { rgbaToThumbHash } from 'thumbhash';

// versus

const thumbhash = await import('thumbhash');
```

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by jrasm91** [comment]
This is a technical implementation detail with a lot of caveats. At the moment there is no plan to run the server as ESM.
