### ISSUE TITLE
[BUG] memories shouldn't be limited to 30 years and should use more efficient query

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2774]
### The bug

Per [my comment](https://github.com/immich-app/immich/pull/2759#discussion_r1230226011) on the initial memories PR, memories shouldn't be limited to just 30 years and should use a more efficient query, rather than 30 queries.

@jrasm91 Wrote an initial implementation of the query which seems to work.

```ts
return this.repository.find({
  where: {
    ownerId,
    isVisible: true,
    isArchived: false,
    fileCreatedAt: Raw(
      (alias) =>
        `EXTRACT(MONTH FROM ${alias} AT TIME ZONE :timeZone) = :month AND EXTRACT(DAY FROM ${alias} AT TIME ZONE :timeZone) = :day`,
      {
        day: date.getDate(),
        month: date.getMonth() + 1,
        timeZone: date.getHours(),
      },
    ),
  },
  relations: {
    exifInfo: true,
  },
  order: {
    fileCreatedAt: 'DESC',
  },
});
```

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by alextran1502** [comment]
Fixed
