### ISSUE TITLE
[BUG] Video Download Progress Icon on iOS App Appears in Corner

### ISSUE THREAD

**Issue by wittymap** [immich-app/immich#2828]
### The bug

If a video (that is only present on the server, not on the phone) is downloaded to the phone, a download progress icon with a spinning circle progress bar appears in the top left corner of the screen. Expected behavior: progress bar should appear centered on screen.

Steps to reproduce (see image below):
- View a video large enough that it'll take a few seconds to download.
- Click the download icon (as annotated in image below)
- Purple progress icon appears in top left corner (as annotated in image below)

![ApplicationFrameHost_warULTnlQC](https://github.com/immich-app/immich/assets/119261743/ae641f9a-cf9d-4d84-8008-2806bc5bb95d)

### The OS that Immich Server is running on

Windows 10

### Version of Immich Server

v1.61.0

### Version of Immich Mobile App

v1.61.0 build.101

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

**Comment by forecaster-cyber** [comment]
Is this good?

**Comment by forresthopkinsa** [comment]
Should we expect to see any kind of download progress indicator on Android? Just double checking before opening a feature request for that

**Comment by scrampker** [comment]
> Should we expect to see any kind of download progress indicator on Android? Just double checking before opening a feature request for that

Ditto, I never have any idea when downloads complete. I randomly find them in my file browser later. Zero confirmation or progress.
