### ISSUE TITLE
chore: remove redundant fields from create asset API

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2853]
### The bug

The fields `assetType` and `fileExtension` aren't really necessary, and should be inferred server-side.

Related: #2824

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.62.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by jrasm91** [comment]
Fixed in #3200
