### ISSUE TITLE
[BUG] GPS data "GPS Altitude" info cannot be decoded from EXIF info

### ISSUE THREAD

**Issue by ElhananWeizman** [immich-app/immich#2859]
### The bug

when uploading from WEB, MOV\MP4 files with meta data that has the next GPS Coordinates(for example) 
-GPSCoordinates"32.0000,35.0000,500.0" 
the GPS location of the file is not available in map section on the immich web,

and with  GPS Coordinates -GPSCoordinates"32.0000,35.0000,50.0"
the Coordinates on the web is showing as 35.0000000,50.0000000

it seams thet the  "EXTRACT METADATA" JOB don't know how to handle -GPSCoordinates that have "GPS Altitude"

becose when i remove the Altitude Tag from the meta data the location is working as it should

### The OS that Immich Server is running on

windows 11

### Version of Immich Server

v1.61.0

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1.upload MOV file with -GPSCoordinates"32.0000,35.0000,500.0" from the web upload button
2.check on map section in the web for that file 
3.remove the GPS Altitude (500.0) from the -GPSCoordinates and check again 
...
```

**Comment by klejejs** [comment]
I just noticed a similar issue. I have a video file with the following EXIF data, in this case, the parsing does not fail, but the location is incorrectly mapped to somewhere totally different:
```
GPS Coordinates                 : 58 deg 29' 34.80" N, 4 deg 25' 36.84" W, 6.74 m Below Sea Level
GPS Altitude                    : 6.74 m
GPS Altitude Ref                : Below Sea Level
GPS Latitude                    : 58 deg 29' 34.80" N
GPS Longitude                   : 4 deg 25' 36.84" W
Rotation                        : 0
GPS Position                    : 58 deg 29' 34.80" N, 4 deg 25' 36.84" W
```

**Comment by ElhananWeizman** [comment]
Hi klejejs,

i think its the same issue, if you look at the GPSCoordinates on the map of the exemple you gave i think you will see 36.84 on latitude and 6.74 on the longitude or something like that,
it becouse it takes the Altitude(6.74 at your case) and think that its the longitude
