### ISSUE TITLE
[BUG] Immich uses legacy OSM tile URL

### ISSUE THREAD

**Issue by otbutz** [immich-app/immich#2874]
### The bug

see https://github.com/openstreetmap/operations/issues/737

https://github.com/immich-app/immich/blob/81e2b185313bc9d9258bb99c0681cd306ea9b05c/web/src/lib/components/asset-viewer/detail-panel.svelte#L249

https://github.com/immich-app/immich/blob/81e2b185313bc9d9258bb99c0681cd306ea9b05c/web/src/routes/(user)/map/%2Bpage.svelte#L121

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.62.1

### Version of Immich Mobile App

v1.62.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not applicable
```

### Your .env content

```Shell
not applicable
```

### Reproduction steps

```bash
not applicable
```

**Comment by KeszeiTheOne** [comment]
I would like to work on this issue. Please assign this issue to me.

This is my first contribute a issue. I wanna try it. :D

**Comment by otbutz** [comment]
I think you're free to craft a PR :wink:

**Comment by KeszeiTheOne** [comment]
Okay, thanks! :D
