### ISSUE TITLE
[BUG] Missing jobs should run on unprocessed assets instead of "missing"

### ISSUE THREAD

**Issue by klejejs** [immich-app/immich#2888]
### The bug

Just an opinion here, but I have always assumed that the "missing" button in the jobs page runs the job on the assets that have not been processed successfully, not on all assets that have been processed, but there was no data found.
I think the current implementation makes sense in some cases, but generally, I would like to be able to recheck if all assets have been processed, not rerun the same process with the same model on the same pictures, to once again find that nothing can be found in them.
Maybe, if there is a benefit of the current "missing" process that I am not aware of, the additional button can be implemented to check "missing=unprocessed" images?

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.62.1

### Version of Immich Mobile App

v1.62.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
-
```

**Comment by alextran1502** [comment]
fixed in #2993
