### ISSUE TITLE
[BUG] Email normalization doesn't handle subaddresses, dots, etc.

### ISSUE THREAD

**Issue by mertalev** [immich-app/immich#2904]
### The bug

I was looking through [validator](https://www.npmjs.com/package/validator) and noticed they have a `normalizeEmail` function that does more thorough sanitation beyond converting to lowercase. For instance, Gmail ignores dots so it handles removing them for Gmail accounts. I imagine this would be good to prevent duplicate emails from being registered. At the same time, I'm not sure if there's a good way to apply this to emails in the database so existing accounts still work. Thoughts?

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.62.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by jrasm91** [comment]
I don't think there is much benefit to adding this. I'd say we leave it as is for now.
