### ISSUE TITLE
[BUG] photos should have a permanent url

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2906]
### The bug

Photos don't have a permanent link when viewed, which means Immich will reset back to the main photos page when the page is refreshed. It also means the link can't be copied or opened in a new tab for whatever reason.

![image](https://github.com/immich-app/immich/assets/9749173/6bdef429-f198-4e0a-8185-1b025f63eff6)

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.62.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by uhthomas** [comment]
Even though albums generate a full URL like `/albums/:id/photos/:id`, a refresh forces the user back to `/albums/:id`. Seems a bit pointless and should also be fixed.

**Comment by alextran1502** [comment]
This is a more complicated behavior that we haven't gotten around to implementing. By navigating to the specific URL, the asset will need to be determined which time bucket it is in to allow proper navigation.

**Comment by uhthomas** [comment]
@alextran1502 I don't think it really matters? I don't think even Google Photos handles that. I would be happy if a direct link just handed the user back to the top of the page.

**Comment by jrasm91** [comment]
Google does handle direct links to assets, and the previous/next arrows work within the context too.

**Comment by uhthomas** [comment]
How does Google handle exiting from the asset?

**Comment by jrasm91** [comment]
It goes back to the album/context as you would expect

**Comment by jrasm91** [comment]
With some of the recent changes in the asset grid implementation, I think it should be easier to add this now. For views that use the asset grid, we should be able to add this feature.

**Comment by alextran1502** [comment]
Implemented #8532
