### ISSUE TITLE
[BUG] Fujifilm RAF files are unsupported

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2909]
### The bug

Immich allows `.raf` to be uploaded, but they aren't supported. This is strange as they should be supported by [libraw](https://www.libraw.org/).

```sh
immich_microservices     | [Nest] 2075  - 06/22/2023, 2:04:58 AM   ERROR [JobService] Unable to run job handler: Error: Input file contains unsupported image format
immich_microservices     | [Nest] 2075  - 06/22/2023, 2:04:58 AM   ERROR [JobService] Error: Input file contains unsupported image format
immich_microservices     | [Nest] 2075  - 06/22/2023, 2:04:58 AM   ERROR [JobService] Object:
immich_microservices     | {
immich_microservices     |   "id": "4ec8c8fb-764c-4201-a5d7-6b659a9585ce",
immich_microservices     |   "source": "upload"
immich_microservices     | }
```

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.61.1 (at HEAD)

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by uhthomas** [comment]
Likely the same issue as https://github.com/libvips/libvips/pull/3546.

**Comment by mertalev** [comment]
It's worth testing this again since we use much newer versions of libvips and Imagemagick now.

**Comment by haak** [comment]
I am running v1.74.0 now, and still see the issue with .RAF files, no thumbnails and images show as missing picture

**Comment by torphexi** [comment]
The issue seems to still persist on 1.81.1 any workarounds?

**Comment by haak** [comment]
> The issue seems to still persist on 1.81.1 any workarounds?

i have been using [Adobe DNG converter](https://helpx.adobe.com/camera-raw/using/adobe-dng-converter.html) to convert to DNG then upload.

**Comment by cole21771** [comment]
Same issues with `1.83.0`. Disappointment to see this not working as an external library viewing of my RAWs is my primary use case for immich

**Comment by cole21771** [comment]
@jrasm91 Is there an issue I can follow on the upstream library? 

This (same?) issue seems to suggest it's an immich issue since libraw can identify RAF files just fine
https://github.com/immich-app/immich/issues/3697#issuecomment-1732522870

And I just verified it for myself with an X-H2 which isn't even on the supported cameras list for libraw because it's so new 
![image](https://github.com/immich-app/immich/assets/14830521/aa17f080-db53-44be-a706-513bfb307f8a)

**Comment by jrasm91** [comment]
I think it is related to this:

https://github.com/libvips/libvips/discussions/3734

**Comment by haak** [comment]
Hi has there been any update on this. I am running Server version v1.88.2 and uploading Fuji RAF files still results in no thumbnail or image.

**Comment by jrasm91** [comment]
Looks like vips 8.15 is out. We can try using it and see if it is fixed there.

**Comment by haak** [comment]
i would be happy to test out any beta builds, just let me know if you can update to the new vips version and ill test it out.

**Comment by Eliaxie** [comment]
Hey, is anyone able to see RAF raws in Immich? I still unable to see them. Version 2.7.4

**Comment by BigCheeZ** [comment]
> Hey, is anyone able to see RAF raws in Immich? I still unable to see them. Version 2.7.4

@Eliaxie I have no issue seeing RAF raws from my Fuji x100 vi work in immich. I am also using version 2.7.4

**Comment by Eliaxie** [comment]
That's quite weird.

Do you mind testing on this one to double check it's not a picture problem?

![DSCF7787.zip](https://github.com/user-attachments/files/26662249/DSCF7787.zip)

**Comment by BigCheeZ** [comment]
> That's quite weird.
> 
> Do you mind testing on this one to double check it's not a picture problem?
> 
> ![DSCF7787.zip](https://github.com/user-attachments/files/26662249/DSCF7787.zip)

Yep, works.

![Image](https://github.com/user-attachments/assets/0605cdec-5e0d-497d-bf91-c871247551c7)
