### ISSUE TITLE
[BUG] Bugged animation when closing image on mobile app

### ISSUE THREAD

**Issue by Shlokp** [immich-app/immich#2915]
### The bug

Opening and closing an image quickly causes the animation to bug. See video below

https://github.com/immich-app/immich/assets/35976544/7a357c57-b088-4d6c-91a9-461cbd0b4769

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.62.1 build.85

### Version of Immich Mobile App

1.62.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
As per build release
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
1. Open an image in full screen
2. Press back (quickly)
3. The closing animation appears on multiple images

```

**Comment by alextran1502** [comment]
Fixed
