### ISSUE TITLE
Warning header on immich.app cuts off drawer on mobile

### ISSUE THREAD

**Issue by cmintey** [immich-app/immich#2924]
### The bug

The immich.app documentation site has the “active development” warning at the top. On mobile, when you click the hamburger menu, the top of the drawer is cut off by that warning. 
![IMG_5861](https://github.com/immich-app/immich/assets/35710697/a6314b37-a015-4c44-aa14-87cc1dfd5fd4)
![IMG_5862](https://github.com/immich-app/immich/assets/35710697/3ffb573e-5bc4-4b1e-9bdb-45a430e7ae70)

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Go to immich.app on mobile phone
2. Click hamburger menu and observe the warning overlapping the drawer
```

### Additional information

Issue occurs on Safari iOS 16.5.1

**Comment by jrasm91** [comment]
This has been resolved.
