### ISSUE TITLE
[BUG] DNG's from iPhone not uploading on latest version 1.63.0

### ISSUE THREAD

**Issue by Cotywio** [immich-app/immich#2939]
### The bug

If I take a RAW photo from my iPhone 14 Pro, it's failing to upload on the latest version. 

Mobile App: Showing "Bad Request"

Web Interface:
![image](https://github.com/immich-app/immich/assets/17916912/0cc7fbde-95e4-4d2c-b4c9-42c54ea57a9f)

Server Logs:
```
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:399:5)
    at onclose (node:internal/streams/end-of-stream:154:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[Nest] 1  - 06/25/2023, 2:19:55 AM   ERROR [AssetUploadConfig] Unsupported file type .DNG file MIME type image/dng
[Nest] 1  - 06/25/2023, 2:19:56 AM   ERROR [AssetUploadConfig] Unsupported file type .DNG file MIME type image/dng
[Nest] 1  - 06/25/2023, 2:19:56 AM   ERROR [ExpressAdapter] Premature close
``` 

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.63.0

### Version of Immich Mobile App

v1.63.0 build.103

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
```

### Your .env content

```Shell
https://github.com/immich-app/immich/releases/latest/download/example.env
```

### Reproduction steps

```bash
1. Set up a new server from scratch
2. Backup DNG photo taken from phone; fails
3. Export from iCloud as DNG & try to upload to web; fails.
```

### Additional information

This seemed to work fine on previous releases, likely something to do with the latest RAW changes.

**Comment by uhthomas** [comment]
Thanks for fixing @alextran1502, and sorry for the regression.
