### ISSUE TITLE
[BUG] Mobile app's video progress bar conflicts with android's navigation bar

### ISSUE THREAD

**Issue by taha-yassine** [immich-app/immich#2958]
### The bug

When playing a video on the mobile app, the progress bar conflicts with android's navigation bar. Seeking does not work and instead triggers gesture control. See video bellow.

https://github.com/immich-app/immich/assets/40228615/c8e5a49c-a56c-4d89-a9cb-0546973755d1

Similar to https://github.com/immich-app/immich/issues/2389

A solution could be raising the bar a little bit.

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.63.2

### Version of Immich Mobile App

v1.63 build.86

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I'm using Unraid.
```

### Your .env content

```Shell
Same.
```

### Reproduction steps

```bash
1. Play video on mobile app
2. Try seeking
```

**Comment by Pheggas** [comment]
Same here. They're not yet working on progress bar to be working element. When they will, i'm pretty sure they will start to work on all the similar issues.
