### ISSUE TITLE
[BUG] "Copy to Clipboard" buttons throw unexampled error

### ISSUE THREAD

**Issue by ddshd** [immich-app/immich#2981]
### The bug

"Copy to clipboard" buttons on the front-end only work if the front-end is being served over HTTPS. Currently when the button is used over HTTP it throws a notification with an error message that doesn't explain why the error occurred.

Info: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

My proposed solutions:
- Hide "Copy to clipboard" button if the site is being served over HTTP, or
- Update the error message to be more informative

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.63.2

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default docker-compose
```

### Your .env content

```Shell
default .env file
```

### Reproduction steps

```bash
1. Access front-end over HTTP
2. Click "copy to clipboard" style button when copying API key or links
...
```

**Comment by ddshd** [comment]
Seems to have been fixed by PR. Thanks Alex.

**Comment by jansohn** [comment]
The same problem still appears on the system settings page.
