### ISSUE TITLE
web: select all search results

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2989]
### The bug

It's not currently possible to select multiple items at once in search results. This is possible with the timeline to a limited degree where days can be selected. Would need #2862 to be truly complete.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.64.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by tranquanghuy0801** [comment]
@uhthomas, I can see that we currently have a button to `Select All` photos in the home page and also in the search results and it is working now. However, pressing the button again to `Deselect All` is not working as I expected.

<img width="389" alt="Screen Shot 2023-07-15 at 2 19 30 pm" src="https://github.com/immich-app/immich/assets/29462498/c482613c-93b1-4d5b-86a6-248e6bd02dc1">

**Comment by uhthomas** [comment]
I could be wrong, but I think another problem is that search results have an arbitrary limit of something like 250 which makes the feature a little less useful.

**Comment by veloxy** [comment]
Somewhat related: https://github.com/immich-app/immich/pull/2464#issuecomment-1677535539

Was hoping search was included in that PR but was not yet the case.

**Comment by alextran1502** [comment]
Implemented
