### ISSUE TITLE
[BUG] Immich Mobile App Shows same photo

### ISSUE THREAD

**Issue by Thoroslives** [immich-app/immich#2994]
### The bug

When navigating in the most recent immich mobile app works fin on timeline but when i navigate to the faces section choose a photo and try to swipe to the next it just shows the same photo again and again. Also if i back out tap on another photo it shows that same photo. Also now that photo shows when i tap on any other photo on another face. 

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.64

### Version of Immich Mobile App

1.64 build 87

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Run through community apps template
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
1. Tap on a face in the app
2. Now try swipe to another photo
3. It should just show the same photo over and over
```

**Comment by yakov-k** [comment]
Reproduction steps:
0. Set option: "Settings/Image viewer quality/Load original image"

**Comment by alextran1502** [comment]
Hello is this issue still relevance? if not, can you help me close it?

**Comment by Thoroslives** [comment]
Its still happening now

**Comment by alextran1502** [comment]
Should be fixed
