### ISSUE TITLE
assets should not be viewable by other users

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#3015]
### The bug

@jrasm91 mentioned it may be possible for any other user on the Immich instance to view any file or thumbnail regardless of the owner. This obviously may be intentional for some cases like shared albums, but maybe not desirable otherwise.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.64.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by jrasm91** [comment]
Both the serve file and serve thumbnail endpoints for have `await this.access.requirePermission` checks now, so this should be resolved.
