### ISSUE TITLE
[BUG] 2-Pass encoding fails for some videos

### ISSUE THREAD

**Issue by akoyaxd** [immich-app/immich#3049]
### The bug

If I enable 2-pass encoding with h264, the encoding crashes for some of my assets.

I get this error in the microservice:
```
[Nest] 8  - 06/30/2023, 1:23:21 PM     LOG [MediaService] Start encoding video c72b957b-9fe4-4bad-8326-f905e57ee5a0 -vcodec h264,-acodec opus,-movflags faststart,-vf scale=720:-2,-preset fast,-threads 3,-x264-params "pools=none",-x264-params "frame-threads=3",-b:v 2483k,-minrate 1241.5k,-maxrate 3600k

[Nest] 8  - 06/30/2023, 1:23:22 PM   ERROR [JobService] Unable to run job handler: Error: ffmpeg was killed with signal SIGSEGV

[Nest] 8  - 06/30/2023, 1:23:22 PM   ERROR [JobService] Error: ffmpeg was killed with signal SIGSEGV

    at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/processor.js:180:22)

    at ChildProcess.emit (node:events:513:28)

    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

[Nest] 8  - 06/30/2023, 1:23:22 PM   ERROR [JobService] Object
```

### The OS that Immich Server is running on

Debian 11 with Docker

### Version of Immich Server

v1.65.0

### Version of Immich Mobile App

v1.65.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
on demand
```

### Your .env content

```Shell
on demand
```

### Reproduction steps

```bash
1. Set encoding settings similar to the settings in the screenshot below
2. Upload the test video from below
3. See the encoding failing in the microservice
```

### Additional information

Screenshot of ffmpeg settings

![grafik](https://github.com/immich-app/immich/assets/22196236/062b2cac-057a-4061-bd01-afc091bbc687)

Sample File, that failed:

https://cloud.koyax.org/s/7KJp6FAmWDs4pgA

**Comment by mertalev** [comment]
This happens in the 2nd pass due to the error `2nd pass has more frames than 1st pass`. This error is in turn caused by the default `fps_mode` setting a constant frame rate and duplicating some frames in the first pass. Setting `-fps_mode passthrough` makes ffmpeg accept frames as they are without duplicating or dropping any, fixing the error. Notably, this error only occurs with `h264`; `hevc` and `vp9` are unaffected.
