### ISSUE TITLE
[BUG] Max bitrate is not enforced

### ISSUE THREAD

**Issue by akoyaxd** [immich-app/immich#3050]
### The bug

When I set a max bitrate value, the video preview is still significantly larger than the specified value. An 4k60 test Video from my Phone had a bitrate of about 5100k with peaks to 8k instead of the specified 3600k I defined.

### The OS that Immich Server is running on

Debian 11 with Docker

### Version of Immich Server

v1.65.0

### Version of Immich Mobile App

v1.65.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
on demand
```

### Your .env content

```Shell
on demand
```

### Reproduction steps

```bash
1. Set the encoder settings of immich accordingly to the settings from the screenshot below.
2. Record a video with a high fidelity and upload it to immich
3. Download the preview video and check its bitrate.
...
```

### Additional information

Screenshot of ffmpeg settings:

![grafik](https://github.com/immich-app/immich/assets/22196236/4f535ffd-a3de-4ade-ad23-e9caa07c3185)

**Comment by mertalev** [comment]
I can confirm this. The reason is because x264 and x265 ignore `-maxrate` unless `-bufsize` is also specified, so this needs to be added to the command.
