### ISSUE TITLE
thumbnails don't load sometimes

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#3073]
### The bug

There's no obvious cause, but it seems that thumbnails won't load occasionally. I found I can make it happen more often by using the scrollbar. Seems like a race condition somewhere?

![image](https://github.com/immich-app/immich/assets/9749173/21920a0a-9bcd-4d8a-9936-0d1e858d4b96)

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.65.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by uhthomas** [comment]
I don't really get this. The element is rendered, but the script is not executed. I put a log in the` <script />` tag and it just never showed up.

![image](https://github.com/immich-app/immich/assets/9749173/cad44833-469d-4f68-9108-b435aae4a550)

**Comment by jrasm91** [comment]
Closing this as fixed with #3902.
