### ISSUE TITLE
should support svg files

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#3084]
### The bug

Immich does not currently allow svg files.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.65.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by declan8010** [comment]
Fix #7960

**Comment by declan8010** [comment]
Merged into main.
