### ISSUE TITLE
[Tech-Debt] Analyze Database Query Performance

### ISSUE THREAD

**Issue by jrasm91** [immich-app/immich#3105]
We should hook up a query analyzer to the database and get some performance information about the queries immich is using to access assets and albums.

**Comment by alextran1502** [comment]
Implemented in OpenTelemetry

**Comment by bo0tzz** [comment]
I don't know if OTEL quite covers this, it's not as fine grained as things like pg_stat_statements and EXPLAIN ANALYZE
