### ISSUE TITLE
[web] A new Immich instance should have some kind of placeholder for assets

### ISSUE THREAD

**Issue by etnoy** [immich-app/immich#3110]
### The bug

With a fresh immich install, there is just a giant blank screen in the middle.

![image](https://github.com/immich-app/immich/assets/135728/4577e4ed-578b-4555-8ac4-4b2191bf67ba)

 It would be nice if there could be a placeholder like "Welcome! Start by uploading some assets" in the middle of the screen

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by jrasm91** [comment]
We have this for other less important screens like albums, favorites, archived, etc. Makes sense to add a placeholder or button here as well.

**Comment by uhthomas** [comment]
Fixed by #3155.
