### ISSUE TITLE
AdobeRGB images are dull

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#3136]
### The bug

It seems like images within the AdobeRGB colour space have dull thumbnails.

See this side-by-side comparison of the same image rendered by Geeqie and Immich.

![image](https://github.com/immich-app/immich/assets/9749173/ace600b8-bd7b-4e1e-ac50-afc8ec9876e5)

https://github.com/lovell/sharp/issues/1114 seems related, maybe it's as simple as asking sharp to use the inbuilt profile?

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.65.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by AngelaDMerkel** [comment]
This is likely caused by Immich converting proxy/thumbnails to sRGB and us the same as my feature request #3623
