### ISSUE TITLE
[BUG] "Download Error" when attempting to download a photo to iOS

### ISSUE THREAD

**Issue by ameyp** [immich-app/immich#3140]
### The bug

I have photos that I uploaded to Immich from my Android phone. On my iPad, when I view one and click on the Download icon, I instead get a red message at the bottom saying "Download Error". Downloading works if I do it from Safari.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.66.1

### Version of Immich Mobile App

1.63.0 build.103

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
This is deployed on Kubernetes, but the setup is virtually identical to the sample docker-compose.yml in the repo.
```

### Your .env content

```Shell
NODE_ENV=production
TYPESENSE_ENABLED=false
IMMICH_MACHINE_LEARNING_URL=false
```

Other values are database and redis-related.
```


### Reproduction steps

```bash
1. Upload a photo from Android
2. Open the photo on iOS
3. Attempt to download the photo
```

### Additional information
There's nothing useful in the app's logs either, I see a bunch of errors with no `Message` or `Stack Traces` and FROM `ImmichErrorLogger`

**Comment by alextran1502** [comment]
Can you update the app on iPad and try downloading again?

**Comment by ameyp** [comment]
Ah, that fixed it, sorry!

**Comment by AndyXheli** [comment]
Hello, I'm having this issue my iPhone works but my iPad does not and I shared some albums with my wife and she's also not able to download on iPhone. Any ideas :)

**Comment by almogtzabari** [comment]
Hi,
I also use iPhone and get this "Download Error" when I try to download some files (some files are downloaded fine).

Looking at the logs of the iOS app I see this (might not be relevant, but I'll add it here anyway):
![image](https://github.com/immich-app/immich/assets/37792505/ecb37158-24e9-412b-8b16-c2ae074384f4)
![image](https://github.com/immich-app/immich/assets/37792505/3751ced1-098c-43bd-a240-ffcbcf2fe602)

**Comment by maxdd** [comment]
I'm having the same issue on Android.
Currently hosting over docker and cannot download anything.
The video/image im trying to download is working fine via web ui though

**Comment by alextran1502** [comment]
@samluxh do you know if the video is uploaded from an iOS device, or from other devices?

**Comment by alextran1502** [comment]
@samluxh can you the app log after the download failed to run?
