### ISSUE TITLE
cannot scroll to top of timeline

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#3163]
### The bug

It's impossible to scroll to the top of the timeline with thousands of assets. The mouse just can't get to a position which is at the top. Either the page has to be refreshed, or the scroll wheel must be used (which takes ages).

![image](https://github.com/immich-app/immich/assets/9749173/6c419867-d8e7-44db-88a6-5c9192024c20)

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.65.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by KailashGanesh** [comment]
I would like to start contributing to this project, I would like to work on this bug. Please assign it to me.

For the solution, I'm thinking the min map bar expands when going to the top?

where can I reach out if I need help?

**Comment by jrasm91** [comment]
Feel free to go to discord to get help. I don't think we want a minimap, just an adjustment to the virtual scrolling.

**Comment by KailashGanesh** [comment]
> Feel free to go to discord to get help. I don't think we want a minimap, just an adjustment to the virtual scrolling.

yes, I called the virtual scrolling as minimap. Thanks I'll ask help on discord.

**Comment by KailashGanesh** [comment]
@uhthomas  @jrasm91 I have made a PR to fix this issue, please check https://github.com/immich-app/immich/pull/3302
