### ISSUE TITLE
web UI becomes unresponsive when uploading files

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#3166]
### The bug

Uploading multiple files via the web brings the entire UI to a crawl and becomes unusable until the uploads complete.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

73e82303e7db6f4192eb74ae0aa60ac7255c93e0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by lifeart** [comment]
We could have upload progress outside of modal window and call resolve before upload here: https://github.com/immich-app/immich/blob/main/web/src/lib/utils/file-uploader.ts#L72

**Comment by uhthomas** [comment]
I believe this has something to do with how thumbnails of uploading assets are rendered? I can see they never fully load and I'm not sure how they're generated. If the entire image is used, then that would cause problems as these files are 6336 x 9504.

**Comment by uhthomas** [comment]
Yeah... We should change this.

https://github.com/immich-app/immich/blob/c8f1a15f21e11d9eda0af652d7c5dca947b962f3/web/src/lib/components/shared-components/upload-asset-preview.svelte#L12C1-L12C1

**Comment by bo0tzz** [comment]
Fixed in #4219
