### ISSUE TITLE
sharing a large album causes the web UI to hang

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#3177]
### The bug

I tried to share an album with ~7000 assets and found the web UI would become unresponsive and never recover. The album would be successfully shared however.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.66.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by lifeart** [comment]
Some of virtual scroll svelte libs may help here: https://github.com/v1ack/svelte-virtual-scroll-list

**Comment by kanazaca** [comment]
+1 also it happens to me when creating a album from a lot of photos.

Not sure if same issue, but the symptom is quite similar.
