### ISSUE TITLE
[BUG] Video Playback not 120hz on mobile

### ISSUE THREAD

**Issue by icodesdeveloper** [immich-app/immich#3180]
### The bug

Videos filmed with my iPhone 13 Pro Max are not smooth in the Immich app, they look so 60 hz compared to when viewed on the Photos app itself.

On the PC they look way smoother too! (Watching with a 240 Hz monitor)

### The OS that Immich Server is running on

iPhone 13 Pro Max

### Version of Immich Server

v1.66.1

### Version of Immich Mobile App

v1.66.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Using Unraid Docker CT

CUDA_ACCELERATIOn = false
```

### Your .env content

```Shell
Using Unraid Docker CT
```

### Reproduction steps

```bash
1. Upload a vid with a high refresh rate
2. Watch it using an IOS device, possibily android too
```

### Additional information

/

**Comment by alextran1502** [comment]
Limitation of the current player
