### ISSUE TITLE
[BUG] CLI upload has wrong count if some images are already on server

### ISSUE THREAD

**Issue by osresearch** [immich-app/immich#3219]
### The bug

After unpacking a second takeout zip file and re-running the upload command, the already uploaded files are correctly detected, but the bargraph and progress estimate uses the total number not the new file count:
```
 ./node_modules/.bin/immich  upload -k XXXX -s https://photos.example.com/api -r ./dir/
Checking connectivity with Immich instance...
Server status: OK
Checking credentials...
Login status: OK
Successful authentication for user user@example.com
Indexing local assets...
Indexing complete, found 3319 local assets
Comparing local assets with those on the Immich instance...
A total of 1259 assets will be uploaded to the server
Do you want to start upload now? (y/n) y
Start uploading...
Upload Progress | ███████████████░░░░░░░░░░░░░░░░░░░░░░░░░ | 37% || 1259/3319
```

### The OS that Immich Server is running on

Ubuntu 20.04

### Version of Immich Server

v1.66.1

### Version of Immich Mobile App

none

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
defaul
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
1. `npm install immich`
2. `immich upload` as above
3. Progress bar stops midway
...
```

**Comment by alextran1502** [comment]
This is the issue with the progress bar display incorrectly - which will be resolved in the new CLI tool being rewritten.
