### ISSUE TITLE
[Bug] Mobile: clicking on upload icon takes some time

### ISSUE THREAD

**Issue by klejejs** [immich-app/immich#3233]
### The bug

Sometimes, when clicking on upload icon during upload, it takes 5-10 seconds for the view to open.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

1.61.0

### Version of Immich Mobile App

1.61.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open app
2. Start uploading
3. Click on upload icon on top right corner
4. Sometimes it will take time for the view to open
```

**Comment by klejejs** [comment]
@alextran1502 top right, the cloud icon

**Comment by alextran1502** [comment]
Hello is this issue still relevance? if not, can you help me close it?

**Comment by klejejs** [comment]
Haven't observed it recently so I assume this has been fixed now. Thanks for the work!
