### ISSUE TITLE
[BUG] Uploaded image do not get upload instantly 

### ISSUE THREAD

**Issue by Avas77** [immich-app/immich#3237]
### The bug

When we upload a picture and the upload is successfully. The uploaded image is not shown only when we reload the page the uploaded image is shown

 

### The OS that Immich Server is running on

Mac OS

### Version of Immich Server

v1.61.0

### Version of Immich Mobile App

v1.61.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open the app
2. Click on upload icon
3. Upload Image
```

**Comment by alextran1502** [comment]
Not a bug, there is a popup message say that refresh to see changes :)
