### ISSUE TITLE
[BUG] reinstalling Android app doesn't recognize previously uploaded photos

### ISSUE THREAD

**Issue by noneabove1182** [immich-app/immich#3263]
### The bug

After reinstalling the app, all my photos appear with the icon indicating they've been backed up, however on the back up screen it says all 3000 assets need to be backed up and attempts to do so.. how can I fix this?

### The OS that Immich Server is running on

Docker ubuntu 22.04

### Version of Immich Server

v1.67.1

### Version of Immich Mobile App

v1.67.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Default
```

### Your .env content

```Shell
Default
```

### Reproduction steps

```bash
1. Have Android app installed and all photos backed up
2. Reinstall all
3. Login and note the bug
```

**Comment by alextran1502** [comment]
Did you change the installation source? For example, going from install from the apk to using google play store?

**Comment by noneabove1182** [comment]
As per @alextran1502 comment, reinstalled from the same source (Google Play) and it resolved itself, thanks!
