### ISSUE TITLE
[BUG] Restarting container in Unraid results in re-downloading all the libraries

### ISSUE THREAD

**Issue by madhusudhanarya** [immich-app/immich#3264]
### The bug

When the Immich container is restarted in Unraid server, all the libraries gets re-downloaded. This happens every time Immich container is restarted which is not the expected behavior.

### The OS that Immich Server is running on

Unraid 6.11.5

### Version of Immich Server

v1.67.1

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Downloaded from Unraid Community Applications
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. Search "Immich" in Unraid Community Applications, click on "Install"
2. Fill the Immich installation template and click on "Apply"
3. Wait for the container to spin up. Take ~5-10 mins to download the libraries and start the server
4. Stop/start or Restart the Immich container
5. During the restart, all libraries gets re-downloaded again. This happens every time Immich container is restarted.
```

**Comment by alextran1502** [comment]
Hello, please raise this issue with the maintainer of the Unraid Community Application.
