### ISSUE TITLE
[BUG] Web Close modal of creating link to share clears the selected photos

### ISSUE THREAD

**Issue by tranquanghuy0801** [immich-app/immich#3280]
### The bug

Description:
- Closing the modal of creating link to share the photos cleared the selected photos, which I think this is not correct behavior. The selected photos should be persisted so the user can continue with other actions such as Download or Archive.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.67.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. On the home page, select some photos
2. At the top, click Share button
3. Close the modal. This action will clear all the selected photos.
```

**Comment by jrasm91** [comment]
Google photos does leave them selected after going through the create shared link process.

**Comment by tranquanghuy0801** [comment]
@jrasm91 Yeah I understand this. What I meant is it closed the modal when I did not select any photos. Your PR fixed this issue.
