### ISSUE TITLE
Add support for OAuth login 

### ISSUE THREAD

**Issue by vins345** [immich-app/immich#33]
Only login and password is to weak secure for 2022 year :)

**Comment by nchristopher** [comment]
Security keys would also be great, if it's not too much of a hassle.

**Comment by adyanth** [comment]
I would say instead of rolling your own, it is better to add OAuth2.0/OIDC support and let the identity providers/auth servers like Authelia or KeyCloak do that job of handling users/rules/2FA/security keys etc.

Username and password is indeed weak for 2022 :)

**Comment by alextran1502** [comment]
@adyanth Thank man, I like this approach. I will look into incorporating them into the application.

**Comment by erikthegamer1242** [comment]
> I would say instead of rolling your own, it is better to add OAuth2.0/OIDC support and let the identity providers/auth servers like Authelia or KeyCloak do that job of handling users/rules/2FA/security keys etc.
> 
> Username and password is indeed weak for 2022 :)

Please implement Authelia and KeyCloack they are the kings when it comes to self-hosted 2FA

**Comment by adyanth** [comment]
With OIDC in place, it should work with both of them and many many more :)

**Comment by ippocratis** [comment]
I just finished seeing up [caddy-security](https://authp.github.io) plugin
It does not require any integtagration in the immich side
You just reverse proxy to the imich port on localhost and authorise it with mfa

Reference [config](https://t.me/s/ippossackofhacks/591)

**Comment by alextran1502** [comment]
The work is being carried on in #207 - Closing this issue

**Comment by jrasm91** [comment]
Implemented in #884, #990.
