### ISSUE TITLE
regression(web): mts files unsupported and uncaught error for unsupported file extensions

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#3300]
### The bug

Attempting to upload a `.mts` video via the web on v1.67.2 does nothing and shows errors in the console.

![image](https://github.com/immich-app/immich/assets/9749173/82d449b1-652f-44ab-a8d7-847a62a211cb)

![image](https://github.com/immich-app/immich/assets/9749173/f0ff12c2-d2a8-452b-a202-f787e237a263)

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.67.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by Pheggas** [comment]
Same issue with m2ts files.

**Comment by jrasm91** [comment]
The "no elements in sequence" issue has been fixed, but the following file extensions are still missing server-side:
- jxl
- m2ts
- mpg
- mts
