### ISSUE TITLE
[BUG] <title>No Facial Recognition with Immich on TrueNAS Scale

### ISSUE THREAD

**Issue by ederidder** [immich-app/immich#3304]
### The bug

I am a user of TrueNAS Scale, installed the Immich App and enabled Machine Learning for Facial recognition. Running the jobs, i see it's telling me its doing the FR but when finished there is no FR in Explore. No "Things" as well, just Places

### The OS that Immich Server is running on

TrueNAS Scale 22.12

### Version of Immich Server

1.67.2

### Version of Immich Mobile App

1.67.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
n/a
```

### Additional information

If you could try it on TrueNAS Scale

**Comment by bo0tzz** [comment]
Can you include logs etc? Is your machine-learning container running?

**Comment by ederidder** [comment]
Thank you for very very quick answer !!! As i am new to all of this , how can i include logs? I have a lot of containers for this app and i see the immich - machine learning is running. I just added a bit more RAM, from 8 to 12 and testing now

**Comment by alextran1502** [comment]
Things is empty because we removed Object Detection since it has poor result and CLIP search is better at detecting object for search.

How is the facial recognition job doing? are you seeing faces now?

**Comment by loadedmodg** [comment]
I also ran into this issue.  I ended up fighting with it, and reinstalling a few times, then set up my own Ubuntu box, used the docker instructions, and boom, facial recognition now works.  

In addition to the original problem ederidder mentioned, typing anything in the search bar (when using the app in TrueNAS Scale) would give me an error message.  App issues aside, kudos to the team, you have made an amazingly useful platform here and I applaud all the work.

**Comment by ederidder** [comment]
Thank you for the help. So Things i forget. So i added more RAM but still the same. So it looks like an App issue just in TrueNAS Scale? And thats the only NAS i have. But same as "loadedmodg" , it's an amazing app, if i could just get FR working :s

**Comment by ederidder** [comment]
Just an update, with latest version of the immich server on Truenas scale it works now. Just one question, "things" got removed while Synology just added this back. Would deepstack api work for this so we have scenerie detection, object detection and much more

**Comment by alextran1502** [comment]
@ederidder we are now use CLIP-SBERT for contextual search which is more powerful and more accurate than traditional object detection so we remove the Things section due to its poor result
