### ISSUE TITLE
[BUG] Mobile - No filename show weird empty spacing

### ISSUE THREAD

**Issue by ddshd** [immich-app/immich#3305]
### The bug

When there is no/empty filename there is this weird spacing in the bottom sheet..

![image](https://github.com/immich-app/immich/assets/17243132/3143e650-0292-4147-85ab-879c9472e206)

My suggestion is to add a placeholder text if the `fileName` is empty...

https://github.com/immich-app/immich/blob/c8f1a15f21e11d9eda0af652d7c5dca947b962f3/mobile/lib/modules/asset_viewer/ui/exif_bottom_sheet.dart#L205

```
              asset.fileName.isEmpty ? "-" : asset.fileName,
```

### The OS that Immich Server is running on

iOS

### Version of Immich Server

v1.57.0

### Version of Immich Mobile App

v1.67.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
- Open an image on the mobile device where it is unable to obtain the filename, usually a local image. The default images on the iOS simulator are good examples.
- Tap the info button and see the spacing issue in the filename
```

**Comment by alextran1502** [comment]
Fixed
