### ISSUE TITLE
[Feature] Sort shared albums

### ISSUE THREAD

**Issue by alextran1502** [immich-app/immich#3308]
### Discussed in https://github.com/immich-app/immich/discussions/3307

<div type='discussions-op-text'>

<sup>Originally posted by **vulcanjedi** July 16, 2023</sup>
### The feature

Currently the timeline is defaulted and only sortable by descending order (new to old) but shared albums seem to be ascending (old to new)
I think this should be uniformly defaulted to descending (newest first ) across Immich or configurable via user settings?
Right now a shared album means user has to scroll down 40 yrs of pics for the newest ones!?

Past few releases have been massive steps and huge performance improvements....thank you!

### Platform

- [X] Server
- [X] Web
- [X] Mobile</div>

**Comment by alceil** [comment]
Can I take a dab at this issue? @alextran1502

**Comment by alextran1502** [comment]
@alceil yes please go ahead

**Comment by alceil** [comment]
Thanks @alextran1502

**Comment by cfitzw** [comment]
Taking a stab here that it might be related to line 39 in:
server/src/immich/api-v1/album/album-repository.ts

fileCreatedAt: 'ASC' --> fileCreatedAt: 'DESC'

Hopefully I am pointing you in the right direction?

**Comment by magicedy** [comment]
It seems this only works effectively on the web version, but there's no effect in the app version(Android v1.71.0)

**Comment by magicedy** [comment]
neither iOS, please help confirm this issue @cfitzw @alextran1502

**Comment by alextran1502** [comment]
@magicedy yep, the mobile app use the local database to query so we need to fix the order of the local database as well

**Comment by cfitzw** [comment]
@magicedy The updated sorting looks to work as expected for albums made with Immich (whether on web or mobile).

The OS-based albums, at least for iOS, appear to still use oldest to newest (sound like the same is true for Android). We will have to see if mobile devices allow sorting their albums.

I also plan to make some further improvements to address updating the thumbnails to be the most resent photo (to mimic iOS behavior), except in cases where the album thumbnail was manually set.

I’m just getting into this awesome project, so getting my feet wet with these improvements. Very well done @alextran1502 , I’ve tried many projects and this one takes the cake, and I’ll do what I can to contribute further.

**Comment by alextran1502** [comment]
will be fixed in https://github.com/immich-app/immich/pull/3469

**Comment by jbalcao** [comment]
Sorting in shared albums(public link) still uses the oldest to newest. Would it also be possible to change it?

**Comment by jrasm91** [comment]
We can open a separate issue for shared links if those are still inconsistent. Albums are sorted newest to oldest now though.
