### ISSUE TITLE
[BUG] Cannot open file, path

### ISSUE THREAD

**Issue by Pro100x3mal** [immich-app/immich#3313]
### The bug

Permanent bug in iOS app. Occurs very often. The Immich server is running with an nginx reverse proxy (without using the immich-proxy container). Upload directory mounted as nfs share

Message
PathNotFoundException: Cannot open file, path = '/private/var/mobile/Containers/Data/Application/EEC3F688-3507-41A4-AEBE-7BA9099CA519/tmp/.image/1636156303.686423_o_FullSizeRender.jpg' (OS Error: No such file or directory, errno = 2)

From
ImmichErrorLogger

Stack traces
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
<asynchronous suspension>
#2      _FileStream._start.onOpenFile (dart:io/file_impl.dart:153)
<asynchronous suspension>

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.67.2

### Version of Immich Mobile App

v1.67.0

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Standart
```

### Your .env content

```Shell
Standart
```

### Reproduction steps

```bash
1.Open mobile app
2.Open error log
3.
...
```

**Comment by alextran1502** [comment]
You are using Shared Album feature on iOS, correct?

**Comment by alextran1502** [comment]
The reported issue you are seeing is related to Shared Album, which we are not fully supported (yet).

Nginx should not interfere at all with the log message you are seeing on the mobile app

**Comment by kloknibor** [comment]
I have the same error, my immich is running behind a reverse apache proxy. Immich will not continue to upload pictures and only killing it manually and restarting helps.

**Comment by ViktorBarzin** [comment]
+1 affected here. Similar setup - behind nginx proxy. No photos being uploaded at all. I am just using the bare minimum, no shared albums as such. v1.79

**Comment by alextran1502** [comment]
@ViktorBarzin Can you update to 1.86?

**Comment by ViktorBarzin** [comment]
My bad, already on 1.86

**Comment by alextran1502** [comment]
@ViktorBarzin can you check mobile app logs as well as the server log?

**Comment by ViktorBarzin** [comment]
Nothing suspicious - client logs suggest syncying succeeds with `changes: False`. However not all images are uploaded. I see some of the images in the immich gallery in the client with the icon saying they are not uploaded. Manually clicking on the upload button doesn't make any difference - nothing shows up neither on client nor server logs (I can see the websocket connections when backup begins).

It's a vanilla installation in k8s behind an nginx ingress. I tried syncing a smaller album before going on the main gallery. I don't know if that makes any difference.

**Comment by alextran1502** [comment]
@ViktorBarzin Try access the instance over local IP to remove the proxy variable

**Comment by ViktorBarzin** [comment]
Yep the proxy was the issue, great catch :) The nginx ingress had the logs:
`2023/11/16 15:23:08 [error] 1396#1396: *4700611 client intended to send too large chunked body: 1033951+65536 bytes,`
Disabling the proxy was not an option as it's running as a k8s service so the ingress proxies all inbound traffic. Adding the following annotation to the ingress solved the issue:

`"nginx.ingress.kubernetes.io/proxy-body-size" : "5000m"`

**Comment by noppe91** [comment]
> I have the same error, my immich is running behind a reverse apache proxy. Immich will not continue to upload pictures and only killing it manually and restarting helps.

i tried to set it up behind a reverse proxy, and failed. could you share your config plz?

**Comment by pattisonmichael** [comment]
I had the same issue and solved it by adding `client_max_body_size 5000M;` in the http section of nginx.conf.
This was on android app but the client seems to have issues with chunked transfer in general.
