### ISSUE TITLE
[Feature] remove the username/password login, when this is disabled in web, on mobile.

### ISSUE THREAD

**Issue by alextran1502** [immich-app/immich#3337]
### Discussed in https://github.com/immich-app/immich/discussions/2206

<div type='discussions-op-text'>

<sup>Originally posted by **Quafley** April  7, 2023</sup>
### The feature

Good evening,

I would like to request a feature to remove the "normal" login, being the username and password when this has been disabled in the web app. (Administration > Setttings > Password Authentication > disable login with email and password)

In the web interface it looks like this:
![image](https://user-images.githubusercontent.com/44779473/230658018-6057fa43-7782-44e2-b2d9-42df41fbae89.png)

While the interface on mobile looks like this: 
![image](https://user-images.githubusercontent.com/44779473/230658054-c99236ca-f0a7-48ca-96db-5014cb92aa1a.png)

NOTE: It is not possible to login with username/password, as this has been disabled and generates an error.

### Platform

- [ ] Server
- [ ] Web
- [X] Mobile</div>

**Comment by sweepies** [comment]
Small nitpick: is this a feature or a bug?

Otherwise +1, I had just assumed someone had submitted this issue already
