### ISSUE TITLE
[BUG] Hiding faces not applying to all

### ISSUE THREAD

**Issue by abrondijk** [immich-app/immich#3349]
### The bug

Hiding faces does not apply to all the faces. Faces that are all the way at the bottom of the list, don't seem to "save" whether its set to hidden or not. Once set to be hidden, they will still show up after clicking "Done". They are also still set to "not hidden" when trying again.

Not sure whether this is related or just a coincidence, but when I scroll to a certain point, the top header starts showing again:
![image](https://github.com/immich-app/immich/assets/73667900/88dadaf5-5cc7-46af-8b1c-c472159427ab)
It seems as though only faces below this point are not saving. Again, not sure if related or just a coincidence.

I checked the logs of all the pods running and the browser console, but no errors were logged.

Happy to provide more information if requested.

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.68.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
DB_HOSTNAME=immich-database
DB_PORT=5432
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_WEB_URL=http://immich-web:3000
TYPESENSE_HOST=immich-typesense
TZ=Europe/Amsterdam
```

### Reproduction steps

```bash
1. Scroll far down when hiding faces
2. Hide most bottom faces
3. Click "Done"
```

**Comment by martabal** [comment]
Can your reproduce this bug everytime ?

**Comment by abrondijk** [comment]
I should have mentioned this, I can indeed reproduce the issue everytime. Reloading or force reloading does not change the behaviour.

**Comment by martabal** [comment]
And when you click on `Done`, is the notification showing up ?

**Comment by abrondijk** [comment]
Upon checking whether that notification shows up or not, I believe I have found the cause. I was simply refreshing the page too fast.
If I wait for that notification to show up, it works as expected, if I don't and instead refresh the page before the notification comes up, not everything seems to apply.

Looking at the network requests made upon clicking "Done" confirms this, as its making separate requests for each face to be hidden.

Not sure if that's desirable?

**Comment by martabal** [comment]
Yep, that's not really great, I'm working on it to fix this 😁

**Comment by martabal** [comment]
I think it's a part of the problem. But I get 2* better performance with a single API call (I tested with 50 faces).
