### ISSUE TITLE
[BUG] Unable to upload .jpg image from Android app

### ISSUE THREAD

**Issue by someonewating** [immich-app/immich#3362]
### The bug

Unable to upload .jpg image from Android. Uploading from Android was working well initially.
Error message on the service side: `ERROR [AssetUploadConfig] Unsupported file type .jpg file MIME type application/octet-stream`.
Error message on the Android application side: `Bad request`.
Upload the jpg image from the webpage is OK.

### The OS that Immich Server is running on

Azure Container App, ghcr.io/imagegenius/baseimage-ubuntu:lunar

### Version of Immich Server

v1.66.1

### Version of Immich Mobile App

v1.68.0 build.91

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
All in one version from `https://github.com/immich-app/immich`, no docker-compose.yml
```

### Your .env content

```Shell
Only one `DB_URL`.
```

### Reproduction steps

```bash
1. Run immich Android application
2. Select backup albums
3. Press `Start Backup`
4. Error
```

### Additional information

I haven't changed any existing code, configuration, or infrastructure. Tried to reinstall the Android app, still got same error.

**Comment by bo0tzz** [comment]
Your server is out of date.

**Comment by someonewating** [comment]
Yes, everything is fine after upgraded the server.
