### ISSUE TITLE
[BUG] all the images taken vertically are rotated left by 90 degrees in webui in docker.

### ISSUE THREAD

**Issue by MayurAgarkar** [immich-app/immich#3367]
### The bug

Hi,

Since last update, all the images I have taken and uploaded from my mobile device and directly in my NAS, are rotated left by 90 degrees.
Its super weird. in the Android Mobile app, on the phone which took the images, I am able to see images properly.
But on another phone app and on docker webui, all the vertically taken images are rotated.

Plus, there is no way currently in webui to edit the image to rotate it back and make correct orientation.
Can you pl help !
I have around 28000 images and more than 10k are rotated like this ! Not just latest but old images too.

Attached a screenshot.

### The OS that Immich Server is running on

UNRAID Version: 6.12.2 

### Version of Immich Server

v1.68.0

### Version of Immich Mobile App

v1.68.0 build.91

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
unraid docker so dont know how to get this
```

### Your .env content

```Shell
unraid docker so dont know how to get this
```

### Reproduction steps

```bash
1. Upload images taken vertically
2. All the uploaded images on Server (webUI plus mobile app(mobile other than the one which took images)) are seen rotated left by 90 degrees.
```

**Comment by alextran1502** [comment]
This is a bug from the web UI. You can track the process here #3227
