### ISSUE TITLE
[BUG] Photos of hidden faces still appear in the "merge faces" window

### ISSUE THREAD

**Issue by Majestic7979** [immich-app/immich#3398]
### The bug

I take lots of street photos, invariable they have lots of strangers.

I used "hide faces" to hide lots of strangers faces from my library.

Then I went to the faces that I wanted to see, and saw there were some duplicates, so I picked "merge faces" option from one of the faces that I opened. Shockingly, the hidden faces are all showing up meaning I have to scroll through hundreds of different people I don't care about, to find the face that I need. I expected that if I say "hide" then it doesn't show anywhere that is supposed to show the faces for selection like it's happening now in the merging tool.

### The OS that Immich Server is running on

Docker on Debian 12

### Version of Immich Server

v1.68.0

### Version of Immich Mobile App

Not applicable

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not applicable
```

### Your .env content

```Shell
Not applicable
```

### Reproduction steps

```bash
As explained above
```

**Comment by alextran1502** [comment]
Fixed and will be available in the next release
