### ISSUE TITLE
[BUG] SSO 503 is not handled

### ISSUE THREAD

**Issue by samip5** [immich-app/immich#3410]
### The bug

It seems that if the IdP provider returns something else than 200, it's not handled properly on server nor app.

Results in wierd behavior like: 

![image](https://github.com/immich-app/immich/assets/1703002/99b6d74e-2ccf-4df4-92ad-a6fb26c11807)
![image](https://github.com/immich-app/immich/assets/1703002/cc0c234c-fbc6-4059-ad71-f43266d9c11f)

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

v1.69.0

### Version of Immich Mobile App

v1.69.0

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Setup Immich with password auth disabled
2. See an error if IdP is unreacheable
3. Notice how poorly it handles it in app
```

### Additional information

App doesn't seem to be logging anything in mobile.

Server log snippet:
```
[Nest] 8  - 07/24/2023, 9:04:38 AM   ERROR [ExceptionsHandler] expected 200 OK, got: 503 Service Unavailable
OPError: expected 200 OK, got: 503 Service Unavailable
    at processResponse (/usr/src/app/node_modules/openid-client/lib/helpers/process_response.js:41:11)
    at Issuer.discover (/usr/src/app/node_modules/openid-client/lib/issuer.js:179:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AuthService.getOAuthClient (/usr/src/app/dist/domain/auth/auth.service.js:231:24)
    at async AuthService.generateConfig (/usr/src/app/dist/domain/auth/auth.service.js:151:22)
    at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by alextran1502** [comment]
Hello is this issue still relevance? if not, can you help me close it?

**Comment by samip5** [comment]
I think it should be handled.
