### ISSUE TITLE
[BUG] Motion photos with <1s length re-encoded wrong

### ISSUE THREAD

**Issue by ishioni** [immich-app/immich#3413]
### The bug

I have a lot of motion photos which are short, sometimes less than 1s. It appears that those get extracted correctly, but when passed through ffmpeg, come out badly for some reason. My ffmpeg settings are unchanged from the default

I will include an example

The original image with MP embedded
![The original image](https://github.com/immich-app/immich/assets/50323052/8bca8732-6396-40c7-8c9e-c60da9590115)

The extracted video
https://github.com/immich-app/immich/assets/50323052/ff26d06a-b694-433f-94e4-ec582377152c

What immich actually tries to display
https://github.com/immich-app/immich/assets/50323052/269d6840-7f85-439c-b6f1-891f3b23a39c

### The OS that Immich Server is running on

Talos 1.4.6

### Version of Immich Server

1.69.0

### Version of Immich Mobile App

1.69.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Upload a short motion photo
2. The resulting motion video is borked both on web and mobile
```

**Comment by alextran1502** [comment]
Dup of #3421
