### ISSUE TITLE
[BUG] Incorrect photo upload in ios

### ISSUE THREAD

**Issue by Pro100x3mal** [immich-app/immich#3419]
### The bug

The bug appears when the "storage optimization" option is enabled in the ios settings and the original photos are uploaded to icloud. At the same time, the immich mobile application uploads non-original photos to the server. I noticed that most of the photos that are on ios in heif format are uploaded to immich in jpeg format. I expected a different behavior - only the original photos and videos need to be uploaded, not their compressed copies

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.69.0

### Version of Immich Mobile App

v1.69.0

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Standart
```

### Your .env content

```Shell
Standart
```

### Reproduction steps

```bash
1. Enable "storage optimization" in the Photos app on ios (with uploading originals to icloud)
2. Open immich app and start backup
3. Most of the photos will not be uploaded in original quality.
...
```

**Comment by alextran1502** [comment]
Hello, this is a known limitation. When you have storage optimization enabled, the photos will be on iCloud. Right now, Immich can only read assets on the physical device.

**Comment by alextran1502** [comment]
Thank you for the report. I don't use iCloud, so I don't have a device to troubleshoot this. I plan to do this soon to help folks that have all the photos on iCloud and be able to use Immich.

**Comment by alextran1502** [comment]
Closing until live photos is tested
