### ISSUE TITLE
[BUG] Mobile, iOS: Sometimes app tries to upload all pictures

### ISSUE THREAD

**Issue by klejejs** [immich-app/immich#3424]
### The bug

Sometimes, when the app has not been killed and is opened a while later (not sure if hours, or days), it will show that all pictures are uploading again. To fix this, the app must be force closed and reopened, then only the remaining pictures are uploaded. If it is not noticed immediately, and some pictures are uploaded, when all photos successfully upload the negative reminder has increased by those uploaded pictures.
I have noticed this for a while now, this is not something new.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.69.0

### Version of Immich Mobile App

v1.69.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open Immich
2. Start uploading
3. Go to another app
4. Open Immich sometime later (a long time later)
5. Upload counter on the top right will show the count of all pictures on device
```

**Comment by alextran1502** [comment]
This might be a hard to reproduce issue. Do you have auto foreground backup enabled?

**Comment by klejejs** [comment]
Yes, full auto foreground and background are enabled.

**Comment by alextran1502** [comment]
@klejejs Can you try to disable automatic foreground backup and use the app for a few days to see if it is the cause?

**Comment by klejejs** [comment]
@alextran1502 Ok, I will do that, but wouldn't it be 100% that the problem disappears then? If the automatic foreground background is disabled it would not upload anything when the app is opened and there will never be any attempt to upload all those pictures. Or do you think it could appear when "Start" button is manually pressed?

**Comment by alextran1502** [comment]
@klejejs I might be happen when you manually start the back up. I want to pin point of it is state management related issue

**Comment by klejejs** [comment]
@alextran1502 I think it will take some time to test this thoroughly, but I have one theory - with foreground backup disabled, when I open the app and "upload" view, the "Start" button is greyed out for some time, I assume until the app indexes all assets and decided which ones it needs to upload. Could it be that with the foreground backup enabled, sometimes upload starts before this check is done, thus uploading starts for all assets?

**Comment by helio4k** [comment]
I also have the same issue as OP mine shows Reminder -52 Remaining photos and videos to back up from selection.
I will disable the foreground backup and see if that solves the issue.

**Comment by klejejs** [comment]
@alextran1502 Just encountered the issue when I opened the app.
Here it is showing the incorrect number of assets that need to be uploaded.
![image](https://github.com/immich-app/immich/assets/24546950/ef27c179-75f6-40b1-9ff7-dd1e3d139ef4)
Interestingly, though, when I clicked the upload button, nothing happened, and this time I believe no photos were uploaded and the negative reminder count did not increase.
![image](https://github.com/immich-app/immich/assets/24546950/e11aff4a-626f-42e7-affa-f5961092d9af)
After force closing the app and opening it, everything went back to normal and new photos were successfully uploaded.
![image](https://github.com/immich-app/immich/assets/24546950/cb464da8-3d1f-4f7c-a4e7-f2a6170d2e8e)
Interesting fact - even though I snapped some screenshots and the total number of photos increased between the first screenshot and the last one, in the last one the total photo count is lower than the first one. Can't explain that one :(

**Comment by atomdmac** [comment]
I'm experiencing this as well on iOS.  It may be worth noting that this is _not_ occur on Android.

**Comment by Silenoz93** [comment]
Hi, 
this also did occur on my Android phone.
It automatically did try to upload all pictures from the "Recent" album which contains all pictures on the phone.
I disabled all albums except the Camera folder, from there the Automatic foreground backup is working... (until now)

**Comment by alextran1502** [comment]
@fyfrey can you think of an edge case that could cause this?

**Comment by klejejs** [comment]
Haven't seen this with the latest app versions, so I assume it was fixed at some point. Thanks!
