### ISSUE TITLE
[BUG] Accepted file type mismatch between new CLI and server/web

### ISSUE THREAD

**Issue by sethbaird01** [immich-app/immich#3429]
### The bug

Server and web do not support .tif files while new CLI does. This causes it to upload such unsupported files resulting in ERR_BAD_REQUEST. 

Error during upload:
![image1](https://github.com/immich-app/immich/assets/58704551/37f36f43-821f-41ae-a96b-d63c95875efe)
![image2](https://github.com/immich-app/immich/assets/58704551/ccfb1495-e70c-4152-941a-8acc970cdc2f)

Diff between types listed in web/src/lib/utils/file-uploader.ts and server/src/domain/asset/asset.service.spec.ts
![diff](https://github.com/immich-app/immich/assets/58704551/3d2401b3-6852-4352-b66a-0000cb1ef28b)

Could be fixed by changing line 12 in CLI's supported files from `const tiff = ['tif', 'tiff'];` to `const tiff = ['tiff'];` https://github.com/immich-app/immich/blob/1c5926553a7fba7a6eaf24be63181a61e6b763d7/cli/src/cores/constants.ts#L12

I tried this locally and the upload proceeded without issue. Not sure if this would pass tests though, since ".tif" is mentioned in the spec file cli/src/services/crawl.service.spec.ts

### The OS that Immich Server is running on

TrueNAS 22.12.3.2

### Version of Immich Server

1.69.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Login to the server through new CLI
2. Upload a .tif file or a folder containing one
3. Error
```

**Comment by alextran1502** [comment]
Hello, what version of the CLI are you running?

**Comment by etnoy** [comment]
For reference, it's the new cli version in the main repo.

Thanks for a really nice writeup, we should be able to fix this quickly!
