### ISSUE TITLE
[BUG] Uploading live photos directly to an album doesn't hide the video

### ISSUE THREAD

**Issue by pixil98** [immich-app/immich#3430]
### The bug

When uploading live photos directly to an album, either through the web ui or the cli, some photos will have both a live photo and the video file added to the album. After talking to @jrasm91, this appears to be because the video file is being uploaded first and added to the album, then when the associated picture is uploaded, it properly links them and hides the video on the timeline but not in any albums.

Ideally, it would remove the videos from the album automatically after extracting metadata and linking them. Even just a job I could run from the cli or admin page to clean up the albums I've imported would be sufficient for now.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.69.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. The component video and picture for a live photo
2. Create a new album
3. Upload the video to the album, then the photo
...
```

**Comment by jrasm91** [comment]
Uploading a live photo as two parts to an album results in (1) a live photo asset and (2) a video asset. Expected is just a live photo asset with the video auto hidden/removed.
