### ISSUE TITLE
[BUG] Panorama images are rendered as photospheres

### ISSUE THREAD

**Issue by AndreAle94** [immich-app/immich#3465]
### The bug

The panorama feature introduced in the latest release is loading all images with `ProjectionType=equirectangular` EXIF tag as photospheres (360 images). This is working fine for photospheres but not for standard panoramas.

See the example below (taken with GCam):
- Original image:
![PXL_20220830_122740379 PANO](https://github.com/immich-app/immich/assets/15969021/ee8cb50a-36aa-40da-b968-20d34335cae7)

- How it's rendered: 
![immagine](https://github.com/immich-app/immich/assets/15969021/c2d7c611-7862-4c88-be54-0817589558ab)

Not sure the library used is compatible with non-360 images, but maybe it's better to avoid rendering this type of images in 360 mode. In my opinion, a possible approach could be checking if `<XMP-GPano:IsPhotosphere>True</XMP-GPano:IsPhotosphere>` tag is present in metadata.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.71.0

### Version of Immich Mobile App

v1.71.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant to the issue
```

### Your .env content

```Shell
not relevant to the issue
```

### Reproduction steps

```bash
1.take a simple panorama image with Google Camera and upload it via web
2.open the image in the web application, it will be loaded as a 360 image
```

**Comment by alextran1502** [comment]
@dmitry-brazhenko Can you help take a look at this issue? Thank you

**Comment by dmitry-brazhenko** [comment]
I will have a look

**Comment by dmitry-brazhenko** [comment]
Well I understood the problem. Looks like that the viewer that I used is not the best one :( 

Thank you so much for reporting @AndreAle94 

I will explore other panorama viewers and will update it

**Comment by dmitry-brazhenko** [comment]
We can assign this bug to me

**Comment by dominikheinz** [comment]
@dmitry-brazhenko Hey, I was wondering if you had this time to look into this issue yet?
What photosphere library is currently being used? This one seems pretty promising: https://photo-sphere-viewer.js.org/ (Although, I am not sure if it will also work with partial photosphere that are not fully enclosed, as shown in the linked issue above).

**Comment by alex-007** [comment]
> @dmitry-brazhenko Hey, I was wondering if you had this time to look into this issue yet? What photosphere library is currently being used? This one seems pretty promising: https://photo-sphere-viewer.js.org/
> 
> (Although, I am not sure if it will also work with partial photospheres/panormas that are not fully enclosed, as shown in the linked issue above).

Actually it works with partial panoramas. Here is the demo https://photo-sphere-viewer.js.org/demos/basic/cropped-panorama.html

**Comment by dmitry-brazhenko** [comment]
Hi!

Thanks for sharing. 
As far as I see, Photo-Sphere-Viewer is not compatbile with svelte.  I am not very good in frontend technologies. Is it possible to integrate it if there is no svelte package?

**Comment by alex-007** [comment]
@dmitry-brazhenko I know nothing about svelte. But I googled and see an example how to use photo sphere viewer and sveltekit [here](https://www.sanity.io/templates/sanity-template-sveltekit-photo-sphere-viewer)

**Comment by lynrayy** [comment]
+
And some photospheres rendered wrong because they are not fully 360 captured and algorithm stitches existing parts together over black uncaptured areas

**Comment by dmitry-brazhenko** [comment]
Seems I understood how to fix this. I am looking into it

**Comment by dmitry-brazhenko** [comment]
![2024-02-09_12-10-28](https://github.com/immich-app/immich/assets/61410067/fbe4317e-7cd0-486e-86c8-ee164f56959b)

**Comment by dmitry-brazhenko** [comment]
Here is  PR with a fix: https://github.com/immich-app/immich/pull/6992

I was able to utilize  Photo-Sphere-Viewer and it is more flexbile viewer

**Comment by dmitry-brazhenko** [comment]
Hello @nicoKoehler!

I am just contributor to immich, not maintainer. Usually they release every 1-2 weeks, but I just merged the changed 2 days ago. 
Here is a release history: https://github.com/immich-app/immich/releases

**Comment by nicoKoehler** [comment]
@dmitry-brazhenko thank you for the answer. I saw your merge but did not know what the release schedule was. I will keep an eye out for the new version then.
