### ISSUE TITLE
[BUG] Clicking on a person only shows the most recent ~1000 photos of the person

### ISSUE THREAD

**Issue by FrankRodelli** [immich-app/immich#3474]
### The bug

When you click on a person under explore, for example my daughter, it only shows the most recent 1000 photos of the person. I don't remember this being the case before updating as I was able to look at her birth photos. 

To verify that it almost seems to be limiting it to the most recent 1000 photos, I tried my other daughter which also only loads ~1000 photos. I also went into the database, and changed the created date to be more recent for an older photo and it showed up perfectly fine. I'm not sure if I'm missing some sort of configuration issues or if this is intended. 

Same behavior is found in the mobile app. 

### The OS that Immich Server is running on

Unraid/Slackware

### Version of Immich Server

1.71.0

### Version of Immich Mobile App

1.71.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
docker run
  -d
  --name='immich'
  --net='bridge'
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Wattsun"
  -e HOST_CONTAINERNAME="immich"
  -e 'DB_HOSTNAME'='192.168.1.234'
  -e 'DB_USERNAME'=''
  -e 'DB_PASSWORD'=''
  -e 'DB_DATABASE_NAME'='immich'
  -e 'REDIS_HOSTNAME'='192.168.1.234'
  -e 'DISABLE_MACHINE_LEARNING'='false'
  -e 'DISABLE_TYPESENSE'='false'
  -e 'DB_PORT'='5432'
  -e 'REDIS_PORT'='6379'
  -e 'REDIS_PASSWORD'=''
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png'
  -p '8080:8080/tcp'
  -v '/mnt/user/Immich/photos':'/photos':'rw'
  -v '/mnt/user/Immich/config/machine-learning':'/config/machine-learning':'rw'
  -v '/mnt/user/appdata/immich':'/config':'rw' 'ghcr.io/imagegenius/immich'
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Upload more than 1000 photos of a detected person
2. Go to explore and click on the person once the faces have been detected
3. Go to the bottom, and photos older than the first 1000 or so won't be displayed.
```

### Additional information

I'm willing to work with someone to help debug this is if is not intended. I'd actually love to start contributing to the project as I'm using it to replace SynologyPhotos and there are a few features I'd love to see added.

**Comment by alextran1502** [comment]
Hello, here is the current workaround before we implement an optimization for that face view

**Comment by alextran1502** [comment]
You can follow #2464 for update on this optimization

**Comment by FrankRodelli** [comment]
Thank you for the response and I'm sorry if this was a duplicate, I couldn't find anything in my searches. Did you intend to link something for the work around or is it included in that pull?

**Comment by FrankRodelli** [comment]
Disregard, I'm assuming that you meant to say this is the current workaround as in limiting the photos to 1000 is the current implemented workaround until the optimization is completed. Got it, thank you!
