### ISSUE TITLE
[BUG] OpenID login on iOS does not proceed after provider login

### ISSUE THREAD

**Issue by nebulade** [immich-app/immich#3496]
### The bug

The immich instance has OpenID setup and the login via web and Android works fine. However, on iOS it opens the webview redirecting to the OpenID provider (in my case this is Cloudron) and then after login, it just blanks the webview and stays there. I wasn't able to see any error on the immich server side nor the OpenID provider. It looks fine just like it does when using Android.

Unfortunately I have no real clue about iOS development to debug this further, but I hope the app logs give any clue:

```
Error performing oAuthLogin: PlatformException(CANCELED, User canceled login, null, null)
```
```
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
<asynchronous suspension>
#2      FlutterWebAuth.authenticate (package:flutter_web_auth/flutter_web_auth.dart:41)
<asynchronous suspension>
#3      OAuthService.oAuthLogin (package:immich_mobile/modules/login/services/oauth.service.dart:27)
<asynchronous suspension>
#4      LoginForm.build.oAuthLogin (package:immich_mobile/modules/login/ui/login_form.dart:188)
<asynchronous suspension>
```
I don't have always access to an iOS device but maybe any hints on what this may mean in the flow could help me diagnose this more.

### The OS that Immich Server is running on

Cloudron

### Version of Immich Server

v1.71.0

### Version of Immich Mobile App

v1.71.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
does not apply with Cloudron
```

### Your .env content

```Shell
Not exactly the .env file but https://git.cloudron.io/cloudron/immich-app/-/blob/main/start.sh
```

### Reproduction steps

```bash
1. Open App
2. Specify server origin
3. Click OpenID login
4. Perform login at OpenID provider
5. Login webview is blank
```

**Comment by Janhouse** [comment]
Works on iOS for me just fine. Have you installed any specific ad-blockers on iOS? Have you whitelisted `app.immich:/` redirect URL in your OpenID provider?

**Comment by nebulade** [comment]
The `app.immich:/` URL is set in the provider and this works on Android as well. I suspect that on iOS something is off in the redirect after provider login making it think that the user cancelled the login (at least what that PlatformException indicates)

**Comment by nebulade** [comment]
After more debugging, the root cause was a CSP header set by the Cloudron OpenID provider. It was setting `form-action *` causing safari webview to not allow the form submission. It was also not an immich iOS app specific issue, as safari on iOS behaves the same way, safari on macOS worked fine.

The solution is to set this CSP value with explicitly allowing `app.immich:` as the schema. 

This may or may not be related to this note on mdn https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/form-action about the `form-action` behavior with redirects (which is what happens for OpenID here)
