### ISSUE TITLE
[Feature]: Unify create user logic

### ISSUE THREAD

**Issue by jbaez** [immich-app/immich#351]
### Feature detail

Currently there are 2 endpoints that creates users introducing duplicated logic:
 - `POST /auth/admin-sign-up`
 - `POST /user`
 
 They can be both merged into a single endpoint `POST /user` with the following business logic:
- admin can only be created if no admin was created before
- prevent creating a user with the same email
- a user can be created only by the admin user

### Platform

Server / Web / maybe Mobile

**Comment by FelixHaimmerer** [comment]
And it would be cool to add the function to delete users again.
Maybe in the add user screen a third button to delete the user. :)

**Comment by jrasm91** [comment]
Can this be closed? The logic is pretty much unified through user core. I also don't think it makes sense to merge an authenticated route with an unauthenticated one.

**Comment by jbaez** [comment]
Yeah let's close this. I think now we probably only have some duplication in the request DTO validation. And yes you are right, it would make it more complicated to merge the API endpoints
