### ISSUE TITLE
[BUG] Import of large library skips 10.000 pictures

### ISSUE THREAD

**Issue by JarlMorgennebel** [immich-app/immich#3517]
### The bug

Hej,

this is a follow-up to bug https://github.com/immich-app/immich/issues/3416 and I am not sure if I should reopen that one or if it is a separate bug. 

The App on my phone reports 5.038 pictures in selected albums to be backup up to Immich v1.71.0.

In https://github.com/immich-app/immich/issues/3416 I imported 56.587 pictures from an existing collection - therefore I would expect 61.500-ish pictures in total on the server.

However in Server Stats only 53.038 pictures are accounted in my account. In the Timeline I am missing a large number (basically an entire directory) of approx. 12.000 pictures.

Is there maybe a by-one error in the recursion?

Thanks, -MN

### The OS that Immich Server is running on

Devuan base OS, docker-compose for Immich

### Version of Immich Server

v1.71.0

### Version of Immich Mobile App

v1.71.0 build 94

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
See https://github.com/immich-app/immich/issues/3416
```

### Your .env content

```Shell
See https://github.com/immich-app/immich/issues/3416
```

### Reproduction steps

```bash
Import commando (last comment on See https://github.com/immich-app/immich/issues/3416)
```

**Comment by JarlMorgennebel** [comment]
More information:

```
root@memories:~# find /mnt/media/existing-morgennebel -type f | wc -l
58564
root@memories:~# find /mnt/media/immich+existing/library/admin -type f | wc -l
4623
```

I am expecting 63187 pictures in Immich (when logged in as Admin of course).

```
root@memories:~# docker run -it --rm -v /mnt/media/existing-morgennebel:/mnt/media/existing-morgennebel ghcr.io/immich-app/immich-cli:latest upload --key VdSjuin8dGHSpVeSyQHqnTZMmz99C6WPvVvfWAnRN0U --server https://memories.XXXXX.de/api /mnt/media/existing-morgennebel --recursive --import --album
Unable to find image 'ghcr.io/immich-app/immich-cli:latest' locally
latest: Pulling from immich-app/immich-cli
8663204ce13b: Pull complete 
d19b13245430: Pull complete 
e4a0f03ce8f3: Pull complete 
e319ab3d00f8: Pull complete 
c097a9c08664: Pull complete 
596df2728f7e: Pull complete 
7d504dd10ea2: Pull complete 
b1008cfb12ca: Pull complete 
9d3ca1902f6d: Pull complete 
882bbd427e4d: Pull complete 
Digest: sha256:023a97dee605ba41dc61ce132e7814ebcd64843aeb01e844528467ed84802faa
Status: Downloaded newer image for ghcr.io/immich-app/immich-cli:latest
Checking connectivity with Immich instance...
Server status: OK
Checking credentials...
Login status: OK
Successful authentication for user oliver@familie-scha.de
Indexing local assets...
Indexing complete, found 56587 local assets
Comparing local assets with those on the Immich instance...
A total of 1520 assets will be uploaded to the server
A total of 56587 assets will be added to album(s).
NOTE: some assets may already be associated with the album, this will not create duplicates.
Do you want to start upload now? (y/n) 
````

I have used this command few times today and still wants to upload 1520 pictures.
1520 to be uploaded + 56587 = 58.107 pictures, **I am missing  5080 pictures** compared to the file level.

````
Start uploading...
Upload Progress | █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 2% || 1520/56587 || Current file [/mnt/media/existing-morgennebel/Familie-Videos/From Dropbox 20161024/From Dropbox 20161
Creating albums...
Upload Progress | ████████████████████████████████████████ | 100% || 391/391 || Current file [{filepath}]
````

Now:

<img width="816" alt="Bildschirmfoto 2023-08-07 um 18 49 47" src="https://github.com/immich-app/immich/assets/59556758/34657d2c-fd89-435f-9f82-1d7b10535ebd">

reports 53.395 + 608 files imported. **I am missing 9184** pictures/files.

I can confirm that I am missing pictures - from my father as example - which I remember well.

Thanks, MN

**Comment by alextran1502** [comment]
Hello, I apologize for the confusing logs in the current CLI tool.

- `56587` is the total number of files scanned from the directory that are accepted file types out of `58564` you see the directory report on the command line.
- Those `1520` files that keep getting uploaded to the server are most likely duplicated files so that the server rejects those.
- So your account should have `56587 - 1520 = 55067` assets while the server stats reports `53395 + 608 = 54003`. So we are looking at `55067 - 54003 = 1064` missing files.

This prompts the question if you see any logs on the server when you are uploading those `1520` assets and is there XMP SIDE from your gallery.

**Comment by alextran1502** [comment]
Bring in @alex-phillips to see if I assume something incorrectly from the `import` feature that lead to this difference in the statistic

**Comment by JarlMorgennebel** [comment]
Hej,

there is absolutely no reason to apologize, this is an awesome product, you are doing awesome work and as every program there are some bugs. The users help them to locate.

For the XMPs:
````
root@memories:/mnt/media# find existing-morgennebel -type f -name "*.xmp" | wc -l
1028
root@memories:/mnt/media# find existing-morgennebel -type f -name "*.XMP" | wc -l
0
````

I think this is a very good catch, as I may have some .hdr and .pano files in the same library:

````

root@memories:/mnt/media# find existing-morgennebel -type f -name "*.pano" | wc -l
4
root@memories:/mnt/media# find existing-morgennebel -type f -name "*.hdr" | wc -l
66
````

1028 + 4 + 66 = 1098.

So everything **should** be correctly imported.

Thanks so much for your patience and helping locating the mismatch.

Ciao, -MN
