### ISSUE TITLE
App Wrong backup count

### ISSUE THREAD

**Issue by GabrieleV** [immich-app/immich#3520]
### The bug

I have started backup. Before it finishes, I've removed some folders.
Now I have a negative number of photos to be uploaded.

![Screenshot_2023-08-02-20-52-01-688_app alextran immich](https://github.com/immich-app/immich/assets/1001288/e9b346d3-698e-4e2d-9e29-87247d9e2e05)

### The OS that Immich Server is running on

Docker 

### Version of Immich Server

1.7.1

### Version of Immich Mobile App

1.7.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
As described.
```

**Comment by alextran1502** [comment]
Dup of #968, you can clear the app cache or reinstall the app to fix this issue at the moment

**Comment by GabrieleV** [comment]
Clearing cache daoes not resolve.
