### ISSUE TITLE
[BUG] Tapping on album thumbnail box doesn't work until the thumbnail appears

### ISSUE THREAD

**Issue by daniele-athome** [immich-app/immich#3539]
### The bug

While loading album thumbnails on the "Library" tab of the mobile app, if you tap on the empty box of an album nothing happens. Same when tapping outside of the error placeholder that appears after a while. Tapping only works:

* on the error placeholder image (a very small area then)
* on the album title

Tapping should work on the whole area.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.71.0

### Version of Immich Mobile App

v1.71.0 build.94 (on Android)

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
(not a server issue)
```

### Your .env content

```Shell
(not a server issue)
```

### Reproduction steps

```bash
1. open mobile app and go to Library at least one time with network connection working (it will cache the album list)
2. make the connection to the server fail (e.g. airplane mode)
3. open the app again, go to Library
4. try to tap on an album avatar while loading (empty space) or tap outside of the little error placeholder
```

**Comment by alextran1502** [comment]
Hello is this issue still relevance?
