### ISSUE TITLE
[BUG] GPS Coordinates Are Not Correct If Coordinate Direction Is In Separate Field

### ISSUE THREAD

**Issue by thegranddesign** [immich-app/immich#3540]
### The bug

EXIF data has a specific field for the coordinate direction.  When XMP file s contain this information, the coordinate is mapped incorrectly.

```
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.4.0">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""
            xmlns:exif="http://ns.adobe.com/exif/1.0/"
            xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/">
         <exif:GPSSpeedRef>K</exif:GPSSpeedRef>
         <exif:GPSSpeed>0.0</exif:GPSSpeed>
         <exif:GPSTimeStamp>2009-01-01T00:00:00Z</exif:GPSTimeStamp>
         <exif:GPSImgDirection>291.76978416999998</exif:GPSImgDirection>
         <exif:GPSLongitudeRef>W</exif:GPSLongitudeRef>
         <exif:GPSAltitudeRef>0</exif:GPSAltitudeRef>
         <exif:GPSLongitude>68</exif:GPSLongitude>
         <exif:GPSLatitude>60.5</exif:GPSLatitude>
         <exif:GPSLatitudeRef>N</exif:GPSLatitudeRef>
         <exif:GPSImgDirectionRef>T</exif:GPSImgDirectionRef>
         <exif:GPSAltitude>121</exif:GPSAltitude>
         <exif:GPSHPositioningError>0.0</exif:GPSHPositioningError>
      </rdf:Description>
   </rdf:RDF>
</x:xmpmeta>
```

Immich currently displays this as in [Russia](https://duckduckgo.com/?q=60.5%252C+68) because it doesn't take into account the `Ref` fields, however the correct location is [Akpatok Island](https://duckduckgo.com/?q=60.5+N%252C+68+W).

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.69.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Use the CLI to import a photo with a sidecar with the contents listed above.
...
```

**Comment by waclaw66** [comment]
Same here, China instead of US. It doesn't take `GPSLongitudeRef` into account.
```
<x:xmpmeta xmlns:x='adobe:ns:meta/'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'>

 <rdf:Description xmlns:exif='http://ns.adobe.com/exif/1.0/'>
  <exif:ImageWidth>3264</exif:ImageWidth>
  <exif:ImageLength>2448</exif:ImageLength>
  <exif:Make>SAMSUNG</exif:Make>
  <exif:Model>GT-I9300</exif:Model>
  <exif:Orientation>Top-left</exif:Orientation>
  <exif:XResolution>72</exif:XResolution>
  <exif:YResolution>72</exif:YResolution>
  <exif:ResolutionUnit>Inch</exif:ResolutionUnit>
  <exif:Software>I9300XXUGNB6</exif:Software>
  <exif:DateTime>2014:05:30 12:51:53</exif:DateTime>
  <exif:YCbCrPositioning>Centered</exif:YCbCrPositioning>
  <exif:ExposureProgram>Normal program</exif:ExposureProgram>
  <exif:ExifVersion>Exif Version 2.2</exif:ExifVersion>
  <exif:DateTimeOriginal>2014:05:30 12:51:53</exif:DateTimeOriginal>
  <exif:DateTimeDigitized>2014:05:30 12:51:53</exif:DateTimeDigitized>
  <exif:MeteringMode>Center-weighted average</exif:MeteringMode>
  <exif:MakerNote>98 bytes undefined data</exif:MakerNote>
  <exif:FlashPixVersion>FlashPix Version 1.0</exif:FlashPixVersion>
  <exif:ColorSpace>sRGB</exif:ColorSpace>
  <exif:PixelXDimension>3264</exif:PixelXDimension>
  <exif:PixelYDimension>2448</exif:PixelYDimension>
  <exif:ExposureMode>Auto exposure</exif:ExposureMode>
  <exif:WhiteBalance>Auto white balance</exif:WhiteBalance>
  <exif:SceneCaptureType>4</exif:SceneCaptureType>
  <exif:InteroperabilityIndex>N</exif:InteroperabilityIndex>
  <exif:InteroperabilityVersion>37, 37,  7</exif:InteroperabilityVersion>
  <exif:GPSLongitudeRef>W</exif:GPSLongitudeRef>
  <exif:GPSLongitude>112,  9, 38</exif:GPSLongitude>
 </rdf:Description>

</rdf:RDF>
</x:xmpmeta>
```

**Comment by uhthomas** [comment]
Possibly resolved by https://github.com/immich-app/immich/pull/2908

**Comment by waclaw66** [comment]
> Possibly resolved by #2908

Nope, it didn't help.

**Comment by alextran1502** [comment]
@waclaw66 it hasn't been released yet 😅

**Comment by waclaw66** [comment]
> @waclaw66 it hasn't been released yet 😅

However it was merged to main and tested on my server.

**Comment by jrasm91** [comment]
I'm guessing we're getting the values of the tags, not adjusted by this reference. This might be something we need to manually do during extraction.

**Comment by jrasm91** [comment]
What is supposed to happen here? The lat/lng need to be updated based on the gps ref? So like negative the coordinates based on the heading, etc.?

**Comment by jrasm91** [comment]
I can work on this if you can help me understand how the headings work and what should be happening, but I don't have time to research the intricacies of this right now.

**Comment by waclaw66** [comment]
@jrasm91 The main problem is, that Immich takes Latitude and Longitude from `tags.GPSLatitude` and `tags.GPSLongitude` fields only.
https://github.com/immich-app/immich/blob/2370c9ef41722a198f646c31bfa4c842ebe9c219/server/src/domain/metadata/metadata.service.ts#L356

However those fields can be positive with additional fields `GPSLongitudeRef` and `GPSLongitudeRef` that specify NSEW direction. And sometimes (https://github.com/immich-app/immich/issues/4340#issuecomment-1747346735) can be contradictional between `GPSLatitude` and `GPSLatitudeRef` N vs S.

I would propose to extract GPS location from `GPSPosition` field, that seems to be always correct, it's precalculated from exiftool.

A nice lizzard photo example:
original xmp data:
```xml
  <exif:GPSLatitude>18,32.725541N</exif:GPSLatitude>
  <exif:GPSLatitudeRef>S</exif:GPSLatitudeRef>
  <exif:GPSLongitude>70,19.873308E</exif:GPSLongitude>
  <exif:GPSLongitudeRef>W</exif:GPSLongitudeRef>
```
extracted by exiftool within immich:
```
"GPSLatitude": 18.5454256833722,
"GPSLongitude": 70.331221799975,
"GPSLatitudeRef": "North",
"GPSLongitudeRef": "East",
"GPSPosition": "-18.5454256833722 -70.331221799975",
```

`-18.5454256833722 -70.331221799975` are correct coordinates

**Comment by BigCheeZ** [comment]
Has anyone else confirmed this is fixed? I have updated my existing instance to Immich v1.93.3, run the Sidecar Metadata job, and the Extract Metadata jobs. I see no difference from before. My media that uses XMP files with GPSLatitudeRef and GPSLongitudeRef are still incorrect. Am I missing steps to make this work?

**Comment by waclaw66** [comment]
> Has anyone else confirmed this is fixed? I have updated my existing instance to Immich v1.93.3, run the Sidecar Metadata job, and the Extract Metadata jobs. I see no difference from before. My media that uses XMP files with GPSLatitudeRef and GPSLongitudeRef are still incorrect. Am I missing steps to make this work?

Please post example image, I can check it on my instance.

**Comment by BigCheeZ** [comment]
@waclaw66 please see JPG and XMP file in the zip file attached below. The JPG actually has the accurate EXIF data inside the file. The XMP files does too, but when it is parsed by Immich it results in the location being shown as Nepal (see below) instead of Orlando, FL USA because GPSLongitudeRef is not being handled appropriately.

Birendranagar
Surkhet, Karnali Pradesh
Nepal

[immich-xmp-test.zip](https://github.com/immich-app/immich/files/14002230/immich-xmp-test.zip)

**Comment by waclaw66** [comment]
This issue is about embedded xmp file in the jpeg file, your issue seems to be something else. I'm not sure how Immich handles external xmp files.

**Comment by MrColumbo** [comment]
i once opened up  [BUG] Wrong location on map #4340  ....not quite sure if this is one is different as well. At least i did not use a sidecar file. In my case the lizzard is still shown at the wrong place on the map. 
I never was able to see the wrong gps coordintes by using exiftool  .....also every other photo app shows it correctly ...

**Comment by waclaw66** [comment]
I can see that lizzard in Chile as expected...
![obrazek](https://github.com/immich-app/immich/assets/15554561/2730ca40-c658-4af3-822b-52d11834ef21)

**Comment by MrColumbo** [comment]
oh -  i just uploaded it again and this time it shows it correctly as well. Before i just did a refresh on the metadata for this single photo. I will try to do a full read metadata job again (maybe refresh metadata does not mean to read it again???)

**Comment by waclaw66** [comment]
Refresh metadata should be sufficient to reload correct gps position.

**Comment by MrColumbo** [comment]
after i did ran the extract meta job it looks all right - thanks. 
Not quite sure why I did not seem to work when i did click on the 3 dots a refresh metadata. Those pictures are part of an external library.
Anyway ....now it looks fine :)  -thanks

**Comment by thegranddesign** [comment]
For those who come to this issue later, there is an additional issue with Apple Photos exporting (or at least there was when I did it). This is not something that Immich is going to fix but *you* can fix it by running an `exiftool` command against your photo metadata.

```sh
exiftool -P -overwrite_original -ext xmp -XMP-exif:All= -tagsFromFile @ -XMP-exif:All '-XMP-exif:GPSLongitude<${XMP-exif:GPSLongitude#}${XMP-exif:GPSLongitudeRef#}' '-XMP-exif:GPSLatitude<${XMP-exif:GPSLatitude#}${XMP-exif:GPSLatitudeRef#}' .
```

What does this command do?

`-P`: Preserve modification times
`-overwrite_original`: Overwrite the original metadata file
`-ext xmp`: Process files with this extension
`-XMP-exif:All=`: Specify which XMP data to read and write
`-tagsFromFile @`: Read tags from the source file being processed
`-XMP-exif:GPSLongitude<${XMP-exif:GPSLongitude#}${XMP-exif:GPSLongitudeRef#}`: Write the longitude by taking the longitude from the source file and follow it by the longitude ref from the source file. Effectively combining them.
`-XMP-exif:GPSLatitude<${XMP-exif:GPSLatitude#}${XMP-exif:GPSLatitudeRef#}`: Write the latitude by taking the latitude from the source file and follow it by the latitude ref from the source file. Effectively combining them.
`.`: Process all files in the current directory
