### ISSUE TITLE
Shift selection doesn't work in some views

### ISSUE THREAD

**Issue by PandaDriver156** [immich-app/immich#3550]
### The bug

When trying to select a range of images by pressing the `Shift` key while selecting an item, it doesn't work and only one image is selected. 

From a quick test, this behavior seems to affect the following places:

- ~Person's photos~
- Place's photos on the explore tab
- Recently added, Videos and Motion Photos (under Your Activity and Categories on explore tab)
- ~Favorites~
- ~Albums~
- ~Archive~
- Search

`Shift` selection on timeline view works fine.

### The OS that Immich Server is running on

Ubuntu 22.04 (Docker)

### Version of Immich Server

v1.71.0

### Version of Immich Mobile App

Not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
1. Go to one of the views mentioned above
2. Select a single image
3. Select another image further away from the first one while holding the `Shift` key
```

**Comment by uhthomas** [comment]
Would be fixed by https://github.com/immich-app/immich/pull/2464

**Comment by joestump** [comment]
Another case where Shift+Click fails is in the photo timeline when you attempt to select photos spanning multiple days. You can only shift+click _within_ a given day on the timeline.

**Comment by uhthomas** [comment]
> Another case where Shift+Click fails is in the photo timeline when you attempt to select photos spanning multiple days. You can only shift+click _within_ a given day on the timeline.

Could you please give an example? I do not see this behaviour. 

![Screenshot from 2023-12-07 16-57-07](https://github.com/immich-app/immich/assets/9749173/a20dba20-6db4-42f1-b42d-7d055f43649e)

**Comment by hugoduraes** [comment]
@uhthomas @alextran1502 @jrasm91 this still doesn't work on the search view!

**Comment by perry-mitchell** [comment]
It's not working for me now on the main page.. 1.22.2, Firefox. It _was_ working for me on the search page though.
