### ISSUE TITLE
[BUG] Broken link in install doc

### ISSUE THREAD

**Issue by tobiasb** [immich-app/immich#3553]
### The bug

https://immich.app/docs/install/docker-compose

> (Optional) Get hwaccel.yml file

> wget https://github.com/immich-app/immich/releases/latest/download/hwaccel.yml

Results in 404 Not Found.

### The OS that Immich Server is running on

Any

### Version of Immich Server

NA

### Version of Immich Mobile App

NA

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. Go to https://immich.app/docs/install/docker-compose
2. (Optional) Get hwaccel.yml file
3. wget https://github.com/immich-app/immich/releases/latest/download/hwaccel.yml
```

**Comment by alextran1502** [comment]
Hello, it is not released yet
