### ISSUE TITLE
[BUG] asset dimensions info don't respect orientation

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#3569]
### The bug

- asset details show dimensions always as `H x W`, it should be `W x H`
https://github.com/immich-app/immich/blob/c73832bd9cd81fe9739a463ca624b977b080c822/web/src/lib/components/asset-viewer/detail-panel.svelte#L189
https://github.com/immich-app/immich/blob/c73832bd9cd81fe9739a463ca624b977b080c822/mobile/lib/modules/asset_viewer/ui/exif_bottom_sheet.dart#L88

- asset details don't respect `orientation` column from `exif` table

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

v1.71.0

### Version of Immich Mobile App

v1.71.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
no relevant
```

### Your .env content

```Shell
no relevant
```

### Reproduction steps

```bash
no relevant
```

**Comment by pamnanaimanish169** [comment]
Is this issue still open to work?

**Comment by jrasm91** [comment]
It still exists for the mobile app, yes. Web has been fixed already.
