### ISSUE TITLE
[BUG] Immich-learning continuous restart

### ISSUE THREAD

**Issue by Thormir84** [immich-app/immich#3580]
### The bug

After the latest update, the immich-learning's container is stuck in a continuous restart.
Inside the log i can see this message:

`python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory`

### The OS that Immich Server is running on

docker-ce 5:24.0.5-1~debian.11~bullseye

### Version of Immich Server

v1.72.1

### Version of Immich Mobile App

v1.72.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NULL
```

### Your .env content

```Shell
NULL
```

### Reproduction steps

```bash
NULL
```

**Comment by bo0tzz** [comment]
Your compose file is out of date, you'll need to update it to the latest release.
