### ISSUE TITLE
[Feature] Allow setting thumbnail quality

### ISSUE THREAD

**Issue by alextran1502** [immich-app/immich#3599]
### Discussed in https://github.com/immich-app/immich/discussions/3597

<div type='discussions-op-text'>

<sup>Originally posted by **james58899** August  8, 2023</sup>
### The feature

Currently there is no way to set the thumbnail quality, and there will be some artifacts when viewing pictures on the web.
Since I don't worry about storage space and bandwidth, I hope to increase the thumbnail quality.

Adding an option to adjust the quality of thumbnails allows us to make a trade-off between quality and storage/bandwidth.

### Platform

- [X] Server
- [ ] Web
- [ ] Mobile</div>

**Comment by james58899** [comment]
This feature request has not been fully resolved, currently only the resolution can be adjusted but the encoding quality cannot be adjusted.
