### ISSUE TITLE
[Feature]  Same actions should be available on albums as in the main timeline

### ISSUE THREAD

**Issue by jrasm91** [immich-app/immich#3607]
### Discussed in https://github.com/immich-app/immich/discussions/2997

<div type='discussions-op-text'>

<sup>Originally posted by **bcsteeve** June 27, 2023</sup>
### The feature

When in the main view, I can delete a file (for example).

When in an album, I can remove it from the album, which makes sense, but I can't delete the file.  Or archive, or add to a different album, etc.

I think it would be useful to have the same full access inside an album as I do outside of the album.

Reason/use-case:  Large collections are difficult to manage.  I may know that I put IMG_001.jpg into my "cats" album, but otherwise have no idea where it is.  Maybe I really want to delete that stupid cat from my life.  I can find it in the album, but I can't do anything with it from there.

### Platform

- [X] Server
- [ ] Web
- [ ] Mobile</div>

**Comment by raisinbear** [comment]
This is absolute awesome, have been waiting for this to happen for a while 😀 also linking discussion #1617 here to be closed with this

**Comment by raisinbear** [comment]
@jrasm91 Sorry, not sure where else to ask this, as it is not an issue or discussion 😅: you explicitly mention being able to delete assets from within an album. As far as I could find out, this only works for one image at a time, inside the asset view, that is. There, the trash can symbol will wipe the file. When selecting multiple assets, the trash can symbol removes them from the album but doesn't wipe them and I couldn't find any other delete options. Am I missing something? Just checking - you added a load of great functionality with this PR! 👍

**Comment by jrasm91** [comment]
Yes, it looks like I slightly jumped the gun on this one. The new action bar (while multi-selecting) does brings up all the same actions/icons as the main timeline now, with the exception of deleting an asset as opposed to removing it from the library. All the testing I did was around removing it from the library, even though I used delete and remove interchangeably in the description.

As far as actually deleting an asset from inside an album, I just want to be careful we don't confuse the two "trash" icons - remove from album vs remove from library. FWIW you _can_ remove from the library via the asset viewer. If you click on the image, the trash icon in the viewer will remove the asset from your library and you can get to that from an album. We could also add a overflow action that would let you do it from the main album page.

Thoughts?

**Comment by jrasm91** [comment]
Perhaps we should change the icon for "remove from album" to be some sort of "minus" variant and then add a "Delete assets" menu item.

**Comment by jrasm91** [comment]
Might just copy google on this one. They put both in the menu so you are less likely to get confused

![image](https://github.com/immich-app/immich/assets/4334196/cf78d459-f10e-4ff2-ad92-0395c08657db)

**Comment by raisinbear** [comment]
> Might just copy google on this one. They put both in the menu so you are less likely to get confused
> 
> ![image](https://user-images.githubusercontent.com/4334196/261078145-cf78d459-f10e-4ff2-ad92-0395c08657db.png)

Seems like the safest approach to me and it's not confounding symbol language. But the same goes for the "minus" (as opposed to the "plus" for add) variant and overhang for deletion from the library. The latter might even be more intuitive, actually, as it keeps an obvious album action in the action bar.
Both gread suggestions, I think!
