### ISSUE TITLE
[Bug] Unable to create shared albums or links on mobile app

### ISSUE THREAD

**Issue by samip5** [immich-app/immich#3609]
### The bug

It seems that one cannot create a shared album nor a share link to a picture on the mobile app

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

1.72.1

### Version of Immich Mobile App

1.72.0 build.95

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
1. Go to sharing
2. Tap create shared album
3. Choose a name and some photos for it
4. Get a prompt to share it with someone but not able to proceed if instance has none other users and create shared album is greyed out as result.
```

### Additional information

I believe this should work without anyone to share it with on the instance.

![Screenshot_20230809-035208](https://github.com/immich-app/immich/assets/1703002/ed916b84-6cd2-4dec-840d-fb8e7cbd4e16)

**Comment by marciopamplona** [comment]
On iOS there's no option to create a share link.

**Comment by alextran1502** [comment]
Not a bug, this is not implemented yet

**Comment by tavdog** [comment]
This appears to be implemented on android but the share link does not reflect the external domain set in the Immich server settings.

<img width="428" alt="Image" src="https://github.com/user-attachments/assets/22767b39-ac13-4c05-bfa5-48db2de25220" />
