### ISSUE TITLE
[BUG] Upload Status Incorrectly Reported as 'Success' When Mobile Screen is Locked/Turns Off on Android

### ISSUE THREAD

**Issue by ankit5902** [immich-app/immich#3614]
### The bug

When attempting to upload files on the Android app, if the mobile screen becomes locked or turns off during the upload process, the upload status is incorrectly displayed as 'Success' even though the upload was actually cancelled.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.72.2

### Version of Immich Mobile App

v1.72.0.build.95

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-N/A-
```

### Your .env content

```Shell
-N/A-
```

### Reproduction steps

```bash
1. Open the Android app.
2. Select multiple files for manual upload.
3. Initiate the upload process.
4. While the upload is in progress, lock the mobile screen or allow it to turn off.
5. Unlock the mobile screen and return to the app.
6. Verify the files selected to be uploaded manually, and check the notification.
```

### Additional information

**Expected Result:** The upload process should continue in the background or (due to any of the limitations, pause when the screen locks/turns off and resume when the mobile screen is unlocked). And, all selected files should be uploaded successfully.

**Actual Result:** The upload status is shown as 'Success', even though the upload process was interrupted due to the screen being locked/turned off. Some of the selected files are actually uploaded until the screen is awake.

**Additional Notes:**
1. The issue does not occur when the app remains active without the screen being locked or turned off during the upload process.
2. The problem leads to confusion as users might believe that their uploads were successful when only "some" or "no" files were actually uploaded due to the interrupted process.

**Comment by shalong-tanwen** [comment]
This might be due to the incorrect app state handling in the initial release which cancelled the upload when the app gets paused which happens way too often. The error message was also had only success and failure notifications which resulted in it getting displayed as 'Success' whereas in reality, the actual state of the upload was 'Cancelled'. This has been addressed in the linked PR which should cancel the manual upload automatically only when the app is in detached state

**Comment by shalong-tanwen** [comment]
This is fixed in 
- #3696 

Uploads should now work even when the device is locked unless the app is killed off, in which case, the notification would say 'Cancelled' instead of 'Success'

**Comment by ankit5902** [comment]
I believe this issue has been resolved and therefore, we can proceed to close it.
