### ISSUE TITLE
[BUG] time buckets show image in different day

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#3616]
### The bug

I have an image taken at 18:09 on Friday (Pá) (in local time), but it's shown in Saturdays (So) bucket.
I assume the problem comes from different timezone perspective. My current timezone is +02:00. The photo has exif only, no TimeZoneOffset field or XMP is present, just time and GPS position. Timezone GMT-04:00 shown in details is probably calculated from GPS position.
When I changed the timezone on my computer to -04:00 and reloaded the page, affected image has moved correctly to Fridays bucket as expected. Local timezone shouldn't affect day buckets.

![obrazek](https://github.com/immich-app/immich/assets/15554561/c34d2e8f-c29c-4eec-8daf-26aacc5793ff)
![obrazek](https://github.com/immich-app/immich/assets/15554561/f755108f-3fc1-4335-8b11-e1cdc9e78b47)
![obrazek](https://github.com/immich-app/immich/assets/15554561/5729fc12-a02a-423b-bda4-a4d9b554fbc9)
![obrazek](https://github.com/immich-app/immich/assets/15554561/b711bff7-7b99-43ac-aae9-6c017c60666c)

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

v1.72.2

### Version of Immich Mobile App

v1.72.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
see above
```

**Comment by waclaw66** [comment]
I think the main problem is that `fileCreatedAt` is converted to UTC and doesn't take into account the original timezone and day when a photo was taken. Then the time bucket day and date are affected by the current timezone and when it's different to the original timezone a photo is shown in different day and date to those shown in photo details.

**Comment by jrasm91** [comment]
Date column are always stored in UTC. Your database viewing tool is displaying them in +2. You can configure your viewer to use/display them in different timezones, but storage is always +0 (UTC). 

The issue is grouping assets into date buckets based on UTC date, but then showing them in local client time. This is especially an issue when you take photos on different timezones than you are viewing, especially when the photos are around midnight UTC.
