### ISSUE TITLE
[BUG] inconsistent button layout

### ISSUE THREAD

**Issue by lordkitsuna** [immich-app/immich#3617]
### The bug

The position of the delete image and the archive image buttons will move depending on how you are viewing an image.

If you are on the main timeline view and you select an image delete is the second to last button from the right, and archive is the rightmost button. However if you then view an individual image these swap position and archive becomes the second to last from the right and delete becomes the rightmost button. This can lead to accidental mispresses when you are sorting through a large amount of images.

I don't personally have any opinion on which position is better, I just know that it would be better if they were consistent

### The OS that Immich Server is running on

arch 

### Version of Immich Server

172.2

### Version of Immich Mobile App

172 b95

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1.select an image on the timeline in the app, note position of the archive and delete buttons

2.view a single image from the timeline, note the position of the archive and delete buttons 

3.compare and realize they do not match
```

### Additional information
![Screenshot_2023-08-09-06-38-47-23_d8aea95ef633eb6b7eb1cae13c34b40e](https://github.com/immich-app/immich/assets/3444267/372cd20b-0bc7-4ad0-91f9-30bf7bf56747)

![Screenshot_2023-08-09-06-38-57-62_d8aea95ef633eb6b7eb1cae13c34b40e](https://github.com/immich-app/immich/assets/3444267/3dcfa922-7f88-4ecf-8762-bbcef2c9eeeb)

**Comment by jrasm91** [comment]
Can you add some relevant screenshots to the description?

**Comment by lordkitsuna** [comment]
> Can you add some relevant screenshots to the description?

done, had to crop the album view to just the bar as my timeline isnt very github friendly but it easily still shows the swapped positions of the delete and archive button
