### ISSUE TITLE
[Feature] Ability to disable memories feature

### ISSUE THREAD

**Issue by jrasm91** [immich-app/immich#3627]
### Discussed in https://github.com/immich-app/immich/discussions/3187

<div type='discussions-op-text'>

<sup>Originally posted by **samip5** July  9, 2023</sup>
### The feature

I would like to be able to disable the memories feature, or at least disable showing things in mobile/web.

### Platform

- [X] Server
- [X] Web
- [X] Mobile</div>

**Comment by Peckmore** [comment]
Sorry for adding a comment when this is already closed! 😄 

I like the ability of turning Memories off from the Timeline view, as I want that to be just a pure timeline of my photos, but it seems that with Memories turned off, there is no other way to get to them through the UI? (Unless I've missed it, in which case I apologise!)

Would it be possible, as an extension of this feature, to add them to the Explore view, perhaps after People (this could also apply to the mobile app too)? I'd still like to be able to get to Memories, just not show them on the Timeline.

**Comment by jrasm91** [comment]
You can open a separate feature request to show memories on the explore page, instead of the timeline.
