### ISSUE TITLE
[BUG] People search doesn’t turn up merged faces

### ISSUE THREAD

**Issue by raisinbear** [immich-app/immich#3728]
### The bug

Hi,

I guess the title says it all. After merging (unnamed) faces to a named face, the search for that name turns up only the images the „original“ named face is in.
Sorry if this is a duplicate, couldn’t find anything related..

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.73.0

### Version of Immich Mobile App

v1.73.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
1. Name a face
2. Merge a (unnamed) face into the named one
3. Search for the name
4. Merged-face images don’t show up
```

**Comment by alextran1502** [comment]
Confirmed

**Comment by alextran1502** [comment]
We reindexed faces but didn't reindex assets with new faces for the search to use them.

**Comment by alextran1502** [comment]
Already fixed
