### ISSUE TITLE
[BUG] timeline scrollbar shown over menu

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#3735]
### The bug

album
![obrazek](https://github.com/immich-app/immich/assets/15554561/fcc594b1-3438-410e-8cec-ed9b8e6f6fd0)
![obrazek](https://github.com/immich-app/immich/assets/15554561/ecc2294b-6954-4c58-b17f-dbfe75ec28b4)

face
![obrazek](https://github.com/immich-app/immich/assets/15554561/4416bc42-f45a-462a-9a15-396954782802)
![obrazek](https://github.com/immich-app/immich/assets/15554561/ccf86f02-ed0b-4422-8e13-8ce073182916)

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

1.73.0

### Version of Immich Mobile App

1.73.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
not relevant
```

**Comment by flyotlin** [comment]
Hi, I've tested this on the demo site running [v1.73.0](https://demo.immich.app), and found this phenomenon as well.

However, I don't know if this is a feature or a bug, code related to this button click action is as below:
- [Svelte template](https://github.com/immich-app/immich/blob/78a2a9e6666807fc1e7738798de2790843698ef7/web/src/routes/(user)/albums/%5BalbumId%5D/%2Bpage.svelte#L331)
- [Click action handler](https://github.com/immich-app/immich/blob/78a2a9e6666807fc1e7738798de2790843698ef7/web/src/routes/(user)/albums/%5BalbumId%5D/%2Bpage.svelte#L168)

If this is considered a bug, I think I can help to fix it.

**Comment by flyotlin** [comment]
I've finished a draft to fix this bug (ContextMenu blocks navigation bar).

Also I noticed that double-click on the button doesn't close ContextMenu, which doesn't match with the behavior of `AccountInfoPanel`'s button. So I coded a fix as well.

Besides, I am wondering how to push my code to a feature branch. Seems like I don't have sufficient permission to push them.

**Comment by jrasm91** [comment]
If you fork the repository, it'll create a copy on your own account that you can write and push to. You can open a pull request from a branch in that repository.
