### ISSUE TITLE
Face Recognition for missing assets is running for all photo wihtout faces

### ISSUE THREAD

**Issue by titro** [immich-app/immich#3750]
### The bug

The face recognition job for missing photos currently is running for all photos without a recognized face. From my point of view it should only process photos which were not analyzed yet.

In the current situation if you run the job thousands of thousands of photos are analyzed again and again with the same result of no face found.

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v.1.73

### Version of Immich Mobile App

v.1.73

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. run the face recognition job for missing assets
2. wait until job is finished
3. run the job again for missing faces. it will run over all "no face detected" assets again
```

**Comment by TheRealchr1s** [comment]
Still encountering this issue in 1.82.1, perhaps there should be a flag to discern analyzed photos with no faces detected from those that have not yet been analyzed

**Comment by alextran1502** [comment]
Hello, we currently don't have a mechanism to determine which one has missing face besides the one without faces

**Comment by sushain97** [comment]
👋 This feels like something that should be supported. Would you be open to a PR @alextran1502? I find it useful to recognize faces for missing assets after a service crash and it's pretty unfortunate that it takes so long.

**Comment by sushain97** [comment]
@alextran1502 I went ahead and attempted a fix in https://github.com/immich-app/immich/pull/4854. It is ~untested right now but I'm happy to write unit tests and test as extensively as necessary if you're open to the general idea.
