### ISSUE TITLE
[BUG] SIG TERM and immich-server

### ISSUE THREAD

**Issue by dhenry123** [immich-app/immich#3763]
### The bug

This is not really a bug.

I've deployed immich in my kubernetes cluster, it seems the immich-server doesn't intercept signal SIGTERM.
When i kill the pod. Kubernetes waits for and finally kills the two containers after reaching timeout. For other containers it's instant, signal is received and containers end cleanly.

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.73.0

### Version of Immich Mobile App

v1.73.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
Kill pod on kubernetes
```

**Comment by alextran1502** [comment]
I believe this has been fixed

**Comment by dhenry123** [comment]
i confirm, Pods restart instantly now
