### ISSUE TITLE
Config file support

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#3774]
It would be nice to add support for an optional config file, so that every aspect of Immich can be configured without needing to use the GUI. This could be implemented as follows:

For simplicity, the config file should be in the JSON format and the schema should match [the existing internal configuration interface](https://github.com/immich-app/immich/blob/main/server/src/infra/entities/system-config.entity.ts#L93-L131), with all values being optional. That way, we don't need to do any additional format parsing or transformation.

The config file can be enabled by setting an environment variable, for example `CONFIG_FILE=/config/immich.json`. 

If the config file is set, The [`SystemConfigCore.getConfig()`](https://github.com/immich-app/immich/blob/main/server/src/domain/system-config/system-config.core.ts#L93C16-L102) function should use the contents of this config file instead of the configuration that is in the database. The admin UI should also be greyed out to not allow updating the database config, and display a message that Immich is configured via the config file.

Bonus: Since the config file format/schema is the same as that used by the API, we could add a button in the admin UI that lets you copy the currently active config, so you can easily move that into a config file.

**Comment by danieldietzler** [comment]
Is there a reason why one should not be able to use the UI when a config file is set? Why don't we just mirror all settings between UI and the file, making both editable?

**Comment by bo0tzz** [comment]
Because then one needs to override the other, and users will need to think about which values will actually get used. It's possible, but it's probably easier for everyone to just not allow it.

**Comment by danieldietzler** [comment]
I just think about a use case where a config file would be the best to easily deploy the software (possibly on multiple hosts?), but later on small tweaks are more easily accessible in the UI. Furthermore, I don't think there will be that many instances, where the config file is currently opened and edited, while at the same time someone changes settings in the UI.

**Comment by jrasm91** [comment]
What about using the configuration file as "defaults", which can still be overwritten with UI values? So leave it editable.

**Comment by danieldietzler** [comment]
> Ah, you mean that changes in the UI are written back to the config file? For some deployment approaches it's pretty common for the config file to be mounted read-only from somewhere, or pulled from git and such. Writing back wouldn't be possible there.

Right, that's fair

**Comment by danieldietzler** [comment]
> What about using the configuration file as "defaults", which can still be overwritten with UI values? So leave it editable.

I like this. Maybe a button in the UI to "revert to defaults".

**Comment by bo0tzz** [comment]
We would need some way to indicate in the UI that a value is overridden from the config file, right?

**Comment by danieldietzler** [comment]
That, or we could show all changed values when the revert button is pressed. But I would prefer indicating it right next to the value as well.

**Comment by jrasm91** [comment]
Well, we already have a "revert to defaults", it would just revert to the config file values instead of the actual defaults, but I guess that could be confusing if you didn't know what value was actually default vs from the file

**Comment by danieldietzler** [comment]
I thought the current reset button only resets dirty fields to their previously saved values; not necessarily the default config?

I agree, the term "default" would then become somewhat ambiguous.

**Comment by bo0tzz** [comment]
It might be worth building this without any merging/UI editing as a basic first pass, then we can see how it works for people and collect some feedback on whether more flexibility is needed?

**Comment by danieldietzler** [comment]
Agreed. Then I have one more, probably "noobie", question: For reading the config file a new utility class would be cleaner than just reading and parsing the file in the getConfig method, right? If so, where should I put such a class? :D domain/storage? infra/utils?

**Comment by jrasm91** [comment]
I would add a method to the storage repository (infra/repos/file provider) for reading a json file and use that inside of system config core. Although it will be annoying to add the dependencies everywhere it is used.

**Comment by briandipalma** [comment]
How is the docker instance meant to access the config file? I don't see any reference to `IMMICH_CONFIG_FILE` in the compose file so my local file reference isn't being volume mapped to somewhere the container knows of...

`/mnt/storage/appdata/immich/immich.config` is my server's config file location in this case. I have the latest release docker compose file, I believe... `https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml`?
```
[Nest] 7  - 08/28/2023, 4:48:19 PM   ERROR [SystemConfigCore] Unable to load configuration file: /mnt/storage/appdata/immich/immich.config due to Error: ENOENT: no such file or directory, open '/mnt/storage/appdata/immich/immich.config'
Error: ENOENT: no such file or directory, open '/mnt/storage/appdata/immich/immich.config'
[Nest] 7  - 08/28/2023, 4:48:19 PM   ERROR [ExceptionHandler] Invalid configuration file
Error: Invalid configuration file
    at SystemConfigCore.loadFromFile (/usr/src/app/dist/domain/system-config/system-config.core.js:244:23)
...
```

**Comment by jrasm91** [comment]
We haven't updated the docker compose file to show how to do this yet, so you will need to add a new volume mount yourself to both immich-server and immich-microservices. Something like:

```yaml
- volumes:
  - /mnt/storage/appdata/immich/immich.config:/mnt/storage/appdata/immich/immich.config
```

**Comment by happyTonakai** [comment]
> We haven't updated the docker compose file to show how to do this yet, so you will need to add a new volume mount yourself to both immich-server and immich-microservices. Something like:
> 
> ```yaml
> - volumes:
>   - /mnt/storage/appdata/immich/immich.config:/mnt/storage/appdata/immich/immich.config
> ```

Simply `- ${IMMICH_CONFIG_FILE}:${IMMICH_CONFIG_FILE}` is fine. I think this should be updated to the official docker compose yaml.
