### ISSUE TITLE
People recognition local storage

### ISSUE THREAD

**Issue by gthb96** [immich-app/immich#3782]
### The bug

When navigating to Search - People, selecting a face, it wrongly shows that the images are not locally stored and let me download the pictures from the server (cloud without checkmark).

When opening the same images in "Photos" view they correctly are detected as locally and server stored.

I did not confirm if it really downloads the images again from the server in that case but the indicator is wrong atleast

I see this on Android (Galaxy S21 5G)

### The OS that Immich Server is running on

Ubuntu 22.04 LTS

### Version of Immich Server

1.74.0

### Version of Immich Mobile App

1.74.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not relevant I guess but can attach in the evening if needed.
```

### Your .env content

```Shell
Not relevant I guess but can attach in the evening if needed.
```

### Reproduction steps

```bash
1. find picture with face in "Photos" view that is locally/server stored.
It shows correctly with cloud + checkmark

2. Go to "Search" - "People" and find the same picture.
It shows cloud without checkmark.
```

**Comment by alextran1502** [comment]
This is not a bug and working as intended for now
