### ISSUE TITLE
How can I delete photos from other users in the shared album ?

### ISSUE THREAD

**Issue by insomnia417** [immich-app/immich#3802]
How can I delete photos from other users in the shared album ?

**Comment by olyrius** [comment]
Same question, is this possible ? 
Would enjoy to see such a feature  : i share an album with severals members of my family for a trip, and we do the sort together. 
It is not easy to remove some pictures if only the owner can remove them from the shared album.

**Comment by jrasm91** [comment]
Non owners should be able to remove them as well, on the web at least. Is this question specifically with regards to the mobile app?

**Comment by insomnia417** [comment]
At least, for example, adding a user to delete permissions for shared folders can also be done

**Comment by jrasm91** [comment]
Ah, I misunderstood. Yes, currently you can only remove photos from the album if:
- You are the owner of the asset (you can remove your own photos)
- You are the owner of the album (you can remove any photos)

There is some pending work to do related to groups and group permissions. I imagine implementing a "delete from album" permission would be in line with that work.

**Comment by akoyaxd** [comment]
Yes, that would be great.
My User Story currently is, that I created an Immich album from a trip but I want e.g. some family member, that I shared the album with to sort out bad images.

**Comment by marekStef** [comment]
Has it been implemented in the meantime? I’d need it for the very same reason.

**Comment by foorschtbar** [comment]
> Has it been implemented in the meantime? I’d need it for the very same reason.

Same question. @alextran1502 marked it as completed, but i found no option.

**Comment by superbarney** [comment]
It still doesn't look like other users who have been granted Editor role can delete photos as of v2.3.1

**Comment by laurento** [comment]
Indeed, this issue has been closed but the problem persists.

**Comment by Suya1671** [comment]
Could a maintainer please reopen this issue? It hasn't been resolved (or mark as a wontfix if the feature can't/won't be added) and I'd like to track it/potentially PR it in :3

**Comment by cookire** [comment]
Is this already on the roadmap?
