### ISSUE TITLE
[BUG] Not able to delete faces which have no associated assets anymore

### ISSUE THREAD

**Issue by samip5** [immich-app/immich#3840]
### The bug

Immich may have had assets at some point that these faces are recognized from, but I'm unable to delete them from faces.

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

v1.74.0

### Version of Immich Mobile App

v1.74.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Delete some photo that has faces recognized
2. See that the face is still shown in people.
```

### Additional information

I don't want to keep faces with no assets.

**Comment by jrasm91** [comment]
There have been lots of facial recognition changes recently. Is this still an issue?

**Comment by mertalev** [comment]
I don't think this is an issue anymore. I just tested and permanently deleting an asset deletes the faces associated with it and the nightly person cleanup query works properly in returning people with no faces.
