### ISSUE TITLE
[BUG] App logs out the user on a HTTP 502

### ISSUE THREAD

**Issue by bt90** [immich-app/immich#3874]
### The bug

I quickly opened the app after updating immich today and was promptly logged out of because the server hadn't finished its startup yet.

My proxy answered with a HTTP 502 - Bad gateway and the app killed my existing session.

I don't think there's a point to force a relogin in such a case. Even worse, a restart of Immich could lead to a silent logout of the user while the app is running in background.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.75.0

### Version of Immich Mobile App

v1.74.0 build.97

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not related
```

### Your .env content

```Shell
not related
```

### Reproduction steps

```bash
1. Login to the app
2. Close the app
3. Stop the server but not the reverse proxy
4. Reopen the app
5. You're logged out now
```

**Comment by traktuner** [comment]
I have the same problem
docker server and iOS app

**Comment by uhthomas** [comment]
Related to https://github.com/immich-app/immich/issues/2980

**Comment by ddshd** [comment]
Are you using domain or IP address?
