### ISSUE TITLE
[BUG] Android App Gray Screen - Nothing is visible on Photos and Library Tab - v1.76+

### ISSUE THREAD

**Issue by o10s** [immich-app/immich#3919]
### The bug

So after updating the server to the 1.76.0 and the mobile app to 1.76.0 (as of time of writing the 1.76.1 is not available)

The Photos tab is just gray nothing happens (the icon on the bottom appears as loading)

The library tab is the same as the photos tab nothing is clickable

The search shows some menus but nothing else:
- I can click on some predefined categories like "videos" but it loads forever.
- If I click on a place or a face it bring me back to the "server endpoint url" screen (effectively logging me out I suppose)

The sharing tab shows my album and photos as expected.

The web interface is working great.
I am on a pixel 6 pro
Reverting back the mobile app to 1.75+ fixes the issue

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

v1.76.0

### Version of Immich Mobile App

v1.76.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not applicable as I use kubernetes
```

### Your .env content

```Shell
Nothing out of the extraordinary has been working for months
```

### Reproduction steps

```bash
1. Install v1.76 on the server and the mobile app
2. Login on the mobile app
```

### Additional information

Pixel 6 pro on android 13

**Comment by shalong-tanwen** [comment]
Do you still have the issue? If yes, can you check and share any error messages in the log?

**Comment by jrasm91** [comment]
Please retest on the latest version and report back if this is still a problem.
