### ISSUE TITLE
[Feature]: Accept cryptocurrency donations

### ISSUE THREAD

**Issue by pluja** [immich-app/immich#392]
### Feature detail

I would like to donate, but I am not willing to give my personal details for making a donation (this includes my card number). I would happily donate with Monero (or Bitcoin) if it was possible.

Likewise, I think many other users (and future users) would also be willing to donate if cryptocurrency was an option. Could you set up some wallets to receive donations? I would recommend you to accept Monero (as it is the most private digital currency with a great community that will happily donate), Bitcoin (the most well-known) and any other currency you feel comfortable to accept.

If you want to accept Bitcoin and Monero from a single wallet app, you can use Cake Wallet which supports Monero, Bitcoin and Litecoin, and it is Open Source. There is also Exodus wallet (I'm not a user of this wallet) which has support for many other coins, but it is not Open Source (although it is trusted).

### Platform

Mobile App

**Comment by alextran1502** [comment]
Thank you for your suggestion, I've updated donation info with BTC and ADA addresses. 

https://github.com/immich-app/immich#support

**Comment by pluja** [comment]
Thank you for the update. I will be donating later :)

As a suggestion, I see you are using an old bitcoin address (legacy address) starting with `1`. Currently, the modern addresses have a lot of benefits over legacy ones. The fees are much lower (30-40% lower) when transacting using modern bech32 addresses (starting with `bc1`). 

I encourage you to update your address to benefit from this and so that people donating to you will need to spend less on fees :) (https://en.bitcoin.it/wiki/Bech32). To update your address, you can use any modern wallet (like Cake Wallet or Blue Wallet, both open source) and generate a new address. Or maybe the wallet you are using allow you to generate a new bech32 address.

I also encourage you to accept Monero. It is a private-by-default currency (no one can see your banace or transaction history) with low fees and fast transaction speeds. It's been up since 2014 (one of the oldest) and has the [3rd most active developers' community](https://www.monerooutreach.org/stories/why-monero-attracts-dev-talent.html). Hope you think about it!

**Comment by pluja** [comment]
I made a donation to your ADA address. The donation was made swapping XMR (Monero) to ADA using a privacy-friendly exchange, but the fees on these exchanges are somewhat high. Thank you for your hard work with this beautiful app :)

**Comment by pluja** [comment]
Can you confirm you received it correctly?

**Comment by alextran1502** [comment]
@pluja I've received it. Thank you for your support!

**Comment by pluja** [comment]
Hi. Have cryptocurrency donations gone away?

**Comment by alextran1502** [comment]
Hello, you can find the information here 

Bitcoin: 1FvEp6P6NM8EZEkpGUFAN2LqJ1gxusNxZX

Cardano: addr1qyy567vqhqrr3p7vpszr5p264gw89sqcwts2z8wqy4yek87cdmy79zazyjp7tmwhkluhk3krvslkzfvg0h43tytp3f5q49nycc

**Comment by pluja** [comment]
I see there is a Zcash donation option, but I'd like to donate in Monero if possible, since it is much more widespread and used, I think it would be interesting to have it as an option.
