### ISSUE TITLE
[BUG] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [immich-app/immich#3920]
...as `geolocator-android` depends on proprietary Google libs

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4978806228#L2435

ref: https://github.com/immich-app/immich/pull/3661

ref: https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator_android/android/build.gradle#L44

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/dfab422b0290488732f3eba00fe127d68e401ba8

**Comment by licaon-kter** [comment]
Also for `1.76.1` you didn't bump versionCode? Still `99` https://github.com/immich-app/immich/blob/v1.76.1/mobile/pubspec.yaml#L5 so it would not have been picked up by autoupdate

**Comment by shalong-tanwen** [comment]
- #3957 adds dependency overrides for `geolocator-android`. It is not used during normal build generation, but is to be used only during F-Droid build generation. 

PR to un-comment this during F-Droid build generation is to be added to `f-droid/data` once this gets released

**Comment by licaon-kter** [comment]
@shalong-tanwen can you give instructions on how this should be used so we can test already?

**Comment by shalong-tanwen** [comment]
> @shalong-tanwen can you give instructions on how this should be used so we can test already?

@licaon-kter  The basic idea is to override the dependency in question with a FLOSS fork without the GMS dependency only during F-Droid build generation. We can use the following [two sed](https://gitlab.com/fdroid/fdroiddata/-/blob/ed7ecabb993cc2c83872a16e7b38b82580a328c4/metadata/app.myzel394.locus.yml#L331-332) commands from locus app's meta to un-comment the overrides before building the app

**Comment by licaon-kter** [comment]
thanks https://gitlab.com/fdroid/fdroiddata/-/commit/99833c1cc2a3d1f75891d2ad2d5ae3267cfc8981
