### ISSUE TITLE
[BUG] some videos without GPS coordinates are listed on the map

### ISSUE THREAD

**Issue by monkeyotg** [immich-app/immich#3923]
### The bug

as the title says

I haven't been there, but the map shows that I have taken some media there.

![Snipaste_2023-08-30_17-02-55](https://github.com/immich-app/immich/assets/8792193/b4e40f5a-191a-4f66-b5ca-638c326fa174)

and these media files do not have GPS coordinates. I haven't checked all of these files one by one, but I‘d say that I've found the pattern. They are not the original data, they are modified versions (by which application, I can't remember, perhaps Google Photos).

The following Video is one of them, and it was taken in Amsterdam. You can download this file here: https://nowtransfer.de/8b82d9529c1f
![Snipaste_2023-08-30_16-36-50](https://github.com/immich-app/immich/assets/8792193/d89437b7-135c-46e9-854f-7015315d7c2b)

P.S.
This bug is not introduced by v1.76.1, but by an earlier version. sorry I didn't write it down as I just noticed it.

### The OS that Immich Server is running on

Windows Server 2022 + Docker Desktop

### Version of Immich Server

v1.76.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by bo0tzz** [comment]
Fixed by #2908
