### ISSUE TITLE
[Feature]: Stats in the admin panel

### ISSUE THREAD

**Issue by MalteKiefer** [immich-app/immich#393]
### Feature detail

It would be great if there was a small static area in the admin area:

- Total number of objects
- Total number of photos
- Total number of videos
- Number of videos / photos per user
- Total storage used
- Storage per user

### Platform

Web

**Comment by alextran1502** [comment]
What do you mean by "memory"?

**Comment by MalteKiefer** [comment]
I mean storage, how much storage it used

**Comment by TCVinNYC** [comment]
I mean CPU + Ram Usage for the app on the admin side would be nice imo.

**Comment by bo0tzz** [comment]
This might warrant it's own issue in the future, but it would also be good to have disk usage quotas per user.

**Comment by zkhan93** [comment]
I just shared my instance with few more people so yeah I would love to see storage used per user

**Comment by zkhan93** [comment]
working on this, can you assign this to me?

**Comment by alextran1502** [comment]
Implemented in #843
