### ISSUE TITLE
[BUG] Map shows no photos when assets have integer lat/lon

### ISSUE THREAD

**Issue by daniele-athome** [immich-app/immich#3935]
### The bug

On the mobile app (Android), map shows no photos at all when at least one asset from the server has integer latitude or longitude. Both are expected to be `double` and the Dart code doesn't account for the JSON parser giving `int`.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.76.1

### Version of Immich Mobile App

v1.76.0 build.99

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
(not relevant)
```

### Your .env content

```Shell
(not relevant)
```

### Reproduction steps

```bash
1. open map page in mobile app
2. select "All" as time range
```

**Comment by daniele-athome** [comment]
The issue lies here:

```dart
      return MapMarkerResponseDto(
        id: mapValueOfType<String>(json, r'id')!,
        lat: mapValueOfType<double>(json, r'lat')!,
        lon: mapValueOfType<double>(json, r'lon')!,
      );
```

This is generated code from OpenAPI specs. The problem is this code takes for granted that the data type for lat and lon is always `double`. When lat or lon don't have a decimal part, the number is treated as `int` and mapValueOfType returns `null`. I'll try to find a way to modify the Typescript code in `server/src/domain/asset/response-dto/map-marker-response.dto.ts` to make it generate the right code.

**Comment by daniele-athome** [comment]
And here it is: https://github.com/OpenAPITools/openapi-generator/issues/15393

**Comment by shalong-tanwen** [comment]
This one was indeed tricky. I was in the process of handling it along with other minor fixes / improvements to the map view. Do you want to handle this or shall I handle this in my PR? For now, I'm patching the generated api helper file to handle `double` value separately

**Comment by daniele-athome** [comment]
I ended up patching the mustache file: https://github.com/daniele-athome/immich/commit/05826c8e5ed80675edd0235592d493027a17e655

Sorry I just read your comment, I don't know if you already did the same thing or something similar. Pick the one you like best :-)

**Comment by shalong-tanwen** [comment]
I just handled this similarly but inside the `api_helper.dart` file and the patch was a little bit simpler

```patch
 /// Returns a valid [T] value found at the specified Map [key], null otherwise.
 T? mapValueOfType<T>(dynamic map, String key) {
   final dynamic value = map is Map ? map[key] : null;
+  // numbers without decimal points are treated as int in dart and fails the type check when double is requested
+  // handle double separately to return a double value instead of null when numbers without decimal points are received
+  if (T is double) return value is num ? value.toDouble() as T : null;
   return value is T ? value : null;
 }
```

**Comment by daniele-athome** [comment]
[I reported about what you and I have found upstream](https://github.com/OpenAPITools/openapi-generator/issues/15393#issuecomment-1702502912). I can't spend more time to submit a PR over there so I hope someone more knowledgeable about OpenAPI Generator will take it up.

**Comment by shalong-tanwen** [comment]
I ended up using your changes for this issue since the double values are patched during the client generation instead of during the runtime. Thank you for the patch

**Comment by daniele-athome** [comment]
In the mean time, [it seems like they fixed the bug upstream](https://github.com/OpenAPITools/openapi-generator/issues/15393).
