### ISSUE TITLE
[BUG] Uploading with Mapbox enabled breaks all metadata

### ISSUE THREAD

**Issue by pluja** [immich-app/immich#394]
**Describe the bug**

I was testing to enable Mapbox for reverse geocoding. Once enabled (ENABLE_MAPBOX=true), I noticed that any images that I was uploading after activating Mapbox didn't have any metadata (on the webUI and phone app). Maybe the API key was in the wrong format?

API key format I used:
`MAPBOX_KEY=pk.e*****************************************************************************_D***`

The same happened if the images were either uploaded from the app or from immich-cli

**System**
- Phone OS [iOS, Android]: `Graphene OS (Android 12)`
- Server Version: `v1.19.0`
- Mobile App Version: `v1.19.0 build.29`

**Comment by alextran1502** [comment]
When you first upload, the metadata extraction job will run at a later time as they are put into a queue system. If you upload 4000 images, you will have to wait for a while because all the background jobs will take turns running so the server won't be choked by heavy CPU usage. Can you please check again?

**Comment by alextran1502** [comment]
If possible, can you try to upload a small set of images first? Also, did you restart the containers after you added in the Mapbox key?

**Comment by pluja** [comment]
@alextran1502 thank you for helping. Yes, I  was restarting all my containers.

I just turned on mapbox again and added my key. I made a single photo (making sure it had location metadata) and uploaded it via Android App (automatic backup). After waiting for at least 15 minutes, the result was "No exif metadata available".

![](https://i.bcow.xyz/bjnvQPh.png)

I turned all containers down, disabled Mapbox form the .env and turned up again. I took the same photo again, and uploaded it. With Mapbox disabled I am getting this:

![](https://rimgo.bus-hit.me/Rzh4SEk.png)

My Mapbox configuration in the `.env`:

```
# ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=true
MAPBOX_KEY=pk.ey**********************************************************************************************A
```

**Comment by alextran1502** [comment]
So I guess your Mapbox key is invalid? Can you try generate a new key and use the new one instead?

**Comment by pluja** [comment]
The key I am using is a valid key.

I meant that I tested making the key wrong on purpose to see if Immich was using the key at all. But when I put a wrong key on purpose it says "Error: Invalid token", which is OK because it means that Immich is in fact detecting that I am using a wrong key.

My key, otherwise, does not output any errors, but still the metadata of the uploaded media is not shown for some reason.

**Comment by alextran1502** [comment]
Is there is a file that you are comfortable sharing that I can use to test it?

**Comment by pluja** [comment]
You mean an image file? It happens with all files on my library. When I enable Mapbox they all loose the EXIF information tab, when I re-enable it, they all get it again. I will try to make a screenshot video later.

**Comment by alextran1502** [comment]
One possibility I can think of is there is a white space after the key in
the .env file. Can you help check if it terminate correctly?

**Comment by pluja** [comment]
Ok. I found what was causing this issue:

When I set up Mapbox, I created a new token specifically for Immich. It seems that this token is not working. If I use the "Default public token" it works perfectly. I checked and the allowed scopes are exactly the same on both tokens, also NO restricted URLs are set up.

It's weird, but I think this is the solution; use the default public token instead of creating one specifically for immich... :/

**Comment by alextran1502** [comment]
Hmm interesting, probably scoping issue when creating the token. We inly use the reverse geocoding or searching by Mapbox's definition, so maybe there is an option for that when creating the token.

**Comment by akoyaxd** [comment]
Hey, I have the exact same problem. The default public token from Mapbox works but a separate token did not work.
I'm happy to share further details if needed.

Btw. Immich is a super awesome app. I was looking for something like (Basicly Google Photos alternative) this for years!! It's a real game changer for me.
Keep going the good work!

**Comment by alextran1502** [comment]
@akoyaxd I think it has to do with the permission of the separated token. I haven't tested which permission does the token need to work.

Also, thank you for the kind words! I and the team appreciate it
