### ISSUE TITLE
[BUG] map api fail connect

### ISSUE THREAD

**Issue by Luis-Lourenco** [immich-app/immich#3971]
### The bug

Map is not opening. 

It opens well on web, not on mobile. 

I’m using iPhone. 

Attached the logs with error. 
This instance is being Cloudflare Tunnel.  

### The OS that Immich Server is running on

Docker on Debian 10

### Version of Immich Server

1.76

### Version of Immich Mobile App

1.76

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
o
```

### Your .env content

```Shell
o
```

### Reproduction steps

```bash
1.update to latest version
2. Click button map, show map empty
3.
...
```

### Additional information

The logs

#0 Cannot get asset for marker ApiException
400: Socket operation failed: GET /asset / assetBvId/ f877ddd2 -
def4-4bbb-9a60-4789a52b105 (Inner exception: Failed host lookup:
'im.phydottenc.uk')
#9
IOClient. send (package:http / src/
io_client. dart: 88)
<asynchronous suspension>
#1
BaseClient._sendUnstreamed
(package: http/src/base_client. dart: 93)
<asynchronous suspension>
#2
ApiClient. invokeAPI
(package: openapi /api_client. dart: 101)
<asynchronous suspension>
# 3
AssetApi. getAssetById
(package: openapi/api/asset_api. dart: 488)
<asynchronous suspension>
#4
MapSerivce. getAssetForMarkerId
(package: immich_mobile /modules /map/services / map. service. dart: 48)
<asynchronous suspension>
#5
mapMarkersProvider. <anonymous
closure>. <anonymous closure> (package: immich_mobile/modules/map/ providers/map_marker.provider. dart: 30)
<asynchronous suspension>
#6
Future. wait. <anonymous closure>
(dart: async/ future. dart: 525)
<asynchronous suspension>
#7
mapMarkersProvider. <anonymous
closure> (package: immich_mobile /modules /map/ providers/map_marker. provider. dart: 28)
<asynchronous suspension>
#8
FutureHandlerProviderElementMixin.ha
ndleFuture. <anonymous closure>. <anonymous closure> (package: riverpod/src/ async_notifier/base. dart: 337)

**Comment by jrasm91** [comment]
Most likely fixed in the latest release. Please retest on 1.77+ when it is available.
