### ISSUE TITLE
[BUG] `oauth.buttonText` is not taken into account

### ISSUE THREAD

**Issue by nebulade** [immich-app/immich#3994]
### The bug

In the log-in screen, the OAuth button text setting is not taken into account anymore.
The settings UI allows to change it, but its not reflected in the login screen. Previous versions worked as expected.

### The OS that Immich Server is running on

Cloudron

### Version of Immich Server

v1.77.0

### Version of Immich Mobile App

does not apply

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
does not apply
```

### Your .env content

```Shell
does not apply
```

### Reproduction steps

```bash
1. Setup OAuth
2. Change button text
3. Open Login view
```

**Comment by bo0tzz** [comment]
I think this got removed in PR #3928. @jrasm91 what was the reason for that?

**Comment by jrasm91** [comment]
When I changed it to use feature flags it became much simpler to implement when I got rid of the custom text. I ask for flags (boolean) and then the authorize url on button click. No easy place to send custom text. It just uses the text "Login" if password login is disabled. Or "Login with OAuth" if both are available.

I am debating dropping the custom text option. If we want to keep it we will need another endpoint just for the text.

**Comment by nebulade** [comment]
Generally it would be nice to add custom text to the button, but if not, then I guess the input field for it and the settings value should be removed to be consistent?

**Comment by jrasm91** [comment]
Agreed that we should either use it or remove the option. 

A few things to consider:
- are there any other places in the web where we might want custom labels/text? If there are a few places we could have a strategy for all of them. I guess the welcome message is currently a variable but that could be moved to an admin config setting as well.
- In the future I think we will eventually translate the UI similar to how the mobile app has been translated into multiple languages. If we have translations and custom text the custom text would only be in a single language.
