### ISSUE TITLE
[BUG] Video audio continues playing after being swiped

### ISSUE THREAD

**Issue by Roy416** [immich-app/immich#4004]
### The bug

When you're watching a video and swipe to go to the next asset, it continues to play for just a little bit on the next asset. For example, I watch a video, swipe to the next asset which can be a video, and for a few seconds both audios are overlapping. 

I think the audio keeps playing until the swiping animation of the next asset has finished. This doesn't occur on the web. I presume because the animation isn't on the web. 

### The OS that Immich Server is running on

Unraid 6.12.4

### Version of Immich Server

v1.76.1

### Version of Immich Mobile App

v1.76.0 build.116

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Same as example
```

### Your .env content

```Shell
Same as example
```

### Reproduction steps

```bash
1. Select a video
2. Swipe to next asset
3.Previous video will continue play (for a second or two) until the animation of the new asset has been completed
```

**Comment by alextran1502** [comment]
Fixed
