### ISSUE TITLE
[BUG] iOS background backup not working

### ISSUE THREAD

**Issue by alextran1502** [immich-app/immich#4020]
### The bug

For the past couple of releases, iOS background backup stopped working.

Diving into the issue, we discovered that the background thread cannot obtain/read the file with the following error messages.

![image](https://github.com/immich-app/immich/assets/27055614/abbf5847-04d3-49f1-a24b-63c11d1b5545)

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v.177.0

### Version of Immich Mobile App

v.177.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Enable background backup on iOS
2. Wait for the background task triggered
3. Receive error notification
```

**Comment by jermanoid** [comment]
Also experiencing this

**Comment by alextran1502** [comment]
Downgrade to flutter 3.10 solved the issue. It appears that flutter 3.13 changes some behavior with background tasks and causes the issue

**Comment by jermanoid** [comment]
I'm using docker for deployment meaning I'd have to downgrade the components to 1.65.0 or something. Would downgrading the server be safe for the database?

**Comment by alextran1502** [comment]
@jermanoid As far as I understand, you don't have a way to select a specific version of the mobile app to install if you are using iOS. But I am not recommending downgrading the server. The latest known version of background task working is on 1.73

**Comment by Pray4Tre** [comment]
How can we select which version of the server to use for a docker container?

**Comment by alextran1502** [comment]
@Pray4Tre Usually, the matching version number is recommended. I found the cause for this issue and it will be fixed in the next release

**Comment by Pray4Tre** [comment]
Was this fix brought into 1.78?

**Comment by alextran1502** [comment]
@Pray4Tre yes, can you help test with your device?

**Comment by Pray4Tre** [comment]
Working on that now, updated everything, took some pics, waiting for background process to run. Will update.

**Comment by Pray4Tre** [comment]
I've been waiting since 9 hours ago for the background job to run... still hasn't.
I only have about 10 apps on background refresh. 
Any reason why google photos background sync is practically instantaneous all day long but this one doesn't run for hours sometimes days?

**Comment by alextran1502** [comment]
@Pray4Tre I am not sure, this is a good question for Google and Apple. It depends on app usage behavior as well afaik, the more you use the app, the more priority it gets to have a background time slice. My background process of Immich runs every 10 minutes or so

**Comment by Pray4Tre** [comment]
I disabled everything but immich and it ran in about 10-20 minutes. It picked up the pics and imported no problem. Thank you for looking into/fixing this bug! Now if only IOS would allow you to rank backround app refresh priority lol

**Comment by alextran1502** [comment]
@Pray4Tre Good to know the issue get resolved, thank you for being consistent and follow up with the issue, without your report, I would have missed the bug. Enjoy

**Comment by f-x1-1** [comment]
Hi, I think the bug is still there. I have been trying to upload my gallery all day, but it doesn't upload unless I open the app.

**Comment by luk6173** [comment]
same bug here, hope to see a fix soon

**Comment by CosticaPuntaru** [comment]
same bug here :)

**Comment by alainvalain** [comment]
Same bug here. Background upload not working makes the whoke Immich idea basically useless for ios users.

**Comment by alextran1502** [comment]
@alainvalain @luk6173 @f-x1-1 

iOS background upload is based on a few things below

1. Usage behavior of the app
2. How many apps are you enabling the "Background App Refresh?"

We have no control over either of those. And the iOS background scheduler is the one making the decision. For context, my wife and I have been using background upload, and it has been working out well for us because we use the app a lot and turn off Background App Refresh of other apps to reduce the completion of the background task time slice.

Background upload is meant for everyday backup (10-20 media), not initial bulk upload. If you use background upload for the initial bulk upload, it will turn out poorly. I would suggest that you turn off the lock screen and let the foreground backup run.

FYI, we are still looking into ways to improve this mechanism,

**Comment by DaeDroug** [comment]
Running into flaky background uploader today as I'm dipping my toes into Immich, I doubt this is helpful but just in case there's a way for you to rip it apart and see how they did it: Synology Photos app for IOS works flawlessly for background uploads, even massive ones manage to get taken care of on their own without me ever even needing to open the app.

**Comment by mccarverone** [comment]
> Running into flaky background uploader today as I'm dipping my toes into Immich, I doubt this is helpful but just in case there's a way for you to rip it apart and see how they did it: Synology Photos app for IOS works flawlessly for background uploads, even massive backlogs manage to get taken care of on their own without me ever even needing to open the app.

I second this, Synology Photos is 100% reliable. Another notable difference is that Synology uploads in parallel and this massively improves transfer times.

**Comment by kenchilada** [comment]
Could you treat large uploads as chunks and upload them as a batch?  I'm not familiar with the API but it seems after you have the iCloud download complete this would be easy enough if you have the ability to read X bytes from offset Y on the downloaded file.
