### ISSUE TITLE
[BUG] EXIF image size data has higher priority than the real image size

### ISSUE THREAD

**Issue by wolfpld** [immich-app/immich#4033]
### The bug

Certain images may contain invalid image size data. For example:

```
% exiftool test.jpg | grep Exif\ Image
Exif Image Width                : 825437749
Exif Image Height               : 256
% identify test.jpg
test.jpg JPEG 800x480 800x480+0+0 8-bit sRGB 181446B 0.000u 0:00.004
```

An example of such image is provided below.

![test](https://github.com/immich-app/immich/assets/600573/3c6eac2e-ff1c-4982-8355-4d2aa26fd26d)

The EXIF image size is used by Immich to display the image size in the UI (one could say that #4017 is thus invalid).

![obraz](https://github.com/immich-app/immich/assets/600573/b0abd2b7-8904-4a2d-9386-db41164a1a8f)

While the image is displayed correctly in the web service when viewing the full image, the thumbnail is displayed as a long bar:

![obraz](https://github.com/immich-app/immich/assets/600573/211359ec-2bb6-4ac5-9b83-c8f29820654a)

The Android app displays both the full image and the thumbnails correctly.

### The OS that Immich Server is running on

-

### Version of Immich Server

v1.77.0

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
-
```

**Comment by alextran1502** [comment]
Hello is this issue still relevance?

**Comment by wolfpld** [comment]
I tested the photo uploaded above with 1.83.0 and the issue seems to be gone.

(I have workarounded this earlier by removing the broken tags from the affected photos.)
