### ISSUE TITLE
[BUG] Upload of webp images failed from web

### ISSUE THREAD

**Issue by basings** [immich-app/immich#405]
I can't upload a webp file although it's among the supported file types defined by the webuploader. The usual popup which appears when uploading jpegs **does not** appear. No error message.

Example images can be found on https://developers.google.com/speed/webp/gallery1

**Comment by basings** [comment]
When uploading a webp photo alongside another "supported file format" e.g. tif, the usual (jpeg) popup for a successful upload appears for all files. The popup message for webp appears but is blank without the thumbnail.

**Comment by alextran1502** [comment]
Note: Need to investigate why `webp` format is failing when uploading to the server although it is a supported file format 

![image](https://user-images.githubusercontent.com/27055614/181959699-8d1ddb02-812c-4589-80e7-adfe68ee4565.png)

**Comment by alextran1502** [comment]
The console showed unknown file format when trying to extract EXIF info therefore exited 

![image](https://user-images.githubusercontent.com/27055614/181961559-c3cc39c8-4189-4d5a-8d3e-db34e5de7ddf.png)

TODO: Work on handling EXIF extraction gracefully for unsupported formats on the web.
