### ISSUE TITLE
[FEATURE] Support Upload of tif(f) files

### ISSUE THREAD

**Issue by basings** [immich-app/immich#406]
I can't upload a tif or tiff file although it's among the supported file types defined by the webuploader. The usual popup which appears when uploading jpegs **does** appear. No error message, image is not uploaded.

Example images can be found on https://filesamples.com/formats/tiff

**Comment by basings** [comment]
Why isn't this a bug? The uploader shows that tif is among the supported file types while it isn't.

**Comment by basings** [comment]
I see, it's not officially among the supported file types. Strange that it's still displayed as one.

![181959699-8d1ddb02-812c-4589-80e7-adfe68ee4565](https://user-images.githubusercontent.com/92867705/182010990-c49d4f3d-a584-49bb-9cac-c862bf702cb8.png)

**Comment by panoti** [comment]
@basings TIFF may be so large in some case, you should take care your memory as well.
