### ISSUE TITLE
Clicking on the ‘map’ in the info section on mobile does not work if apple maps not installed (ios)

### ISSUE THREAD

**Issue by radh21301** [immich-app/immich#4075]
### The bug

When you click on the map in the info section, it shows a pop up to install Apple maps. I would think that this needs be be customizable. Maybe ask me the first time which app to use - I use google maps all the time. I think this could be similar in android as well where google maps could be default ( i am just guessing)

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.76.1

### Version of Immich Mobile App

1.76.0 build.116

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
As in the description
```

**Comment by alextran1502** [comment]
Closing, considering this is the expected dependency to work on iOS
