### ISSUE TITLE
[Feature]: Support for (Sub)Directory Upload

### ISSUE THREAD

**Issue by basings** [immich-app/immich#409]
### Feature detail

Old folks have all their files sorted within folders and subfolders. When uploading images to immich from desktop, you need to go into each dir and select all the images and separate the folders which is inconvenient.

### Platform

Web

**Comment by bo0tzz** [comment]
You'd probably be better off using the cli for this.

**Comment by alextran1502** [comment]
Closing with the alternative of using CLI for such operation.
