### ISSUE TITLE
Logo design proposal and concept

### ISSUE THREAD

**Issue by pluja** [immich-app/immich#411]
I am enjoying a lot using immich, and I just worked on a concept for a new logo design. If you like it, I can send you all the files as PSD and other formats (SVG, PNG, JPG, WEBP)...

The design I chose is inspired on a variation of the shape commonly used in many Gallery apps. I made this choice as the logo would be familiar to any person at a glance; You see this logo and you think of a gallery. Also, the shapes resemble petals from a flower or leaves (or even a butterfly); it is in honor of nature and the thousands of photos we take of it.

The colored logo has the most common colors in nature: green (plants and trees), blue (oceans and sky), yellow (sunlight) and red (dirt, rocks, sunset sky...)

The typography is pixelated to refer to the digital image, since it is a software to backup digital images.

Feel free to say no if you don't like it. I just made it because I enjoy doing this things and I thought that the current logo is a bit too much for my taste as I like simple things. Also you can share any variation ideas or anything that you feel it could improve the design. Here you can see the concepts:

### App logo concept:
![](https://i.imgur.com/2Ps3dgb.png)

### Banner concept:
![](https://i.imgur.com/LVL6oA2.png)

### Logo variations:
![](https://i.imgur.com/gpcPPRh.png)

### Platform

Mobile App

**Comment by spreakfark** [comment]
I personally like the current logo very much. For me it has just more personality and stands out of all the flat and corporate like logos. Also it is just super easy to explain my parents that they have to open the app with the "flower" icon. It is silly but it just works :)

**Comment by pluja** [comment]
@spreakfark  The current logo is not bad, it is just a matter of personal taste. I like the minimalism and, for me, the current logo does not remind me of a "photo-related" app. But as I said, this is just a proposal! :smile:

**Comment by alextran1502** [comment]
Hey, @pluja thank you for the proposal. The current logo has a personal meaning to me. 

I really like Japanese culture, especially books, history, and food. The current logo is a spin-off of [the Oda clan's symbol](https://en.wikipedia.org/wiki/Oda_clan). 

![Oda_emblem](https://user-images.githubusercontent.com/27055614/182044504-a5ed33a8-5640-42de-b359-18fdbee9fb90.svg)

Why Oda, you asked. One of my favorite books is [Taiko](https://www.goodreads.com/book/show/336228.Taiko), about a prominent figure in the history of Japan, [Hideyoshi](https://en.wikipedia.org/wiki/Toyotomi_Hideyoshi). He came from nothing, and through resilient and his wonderful mind, he has become one of the most powerful men in Japan's history. I enjoy his personality and the way he moved through life.

It is a reminder to me to develop this project to the end :)

The color is an adaptation of Google Photos' color scheme, with an extra color (pink) to complete the flower's fifth petals. The petal layers are the same color scheme as the main layer rotating back and forth to "bring the flower to life."

I appreciate you taking the time to develop the new design, but I will keep the current design for the reasons above.

**Comment by pluja** [comment]
Hey @alextran1502! That's very nice to know! Now I can see the logo very differently knowing what it means. You should write this somewhere! I am closing this issue :)

PS: I take note of Taiko to put it on my reading queue :)

**Comment by Tirarex** [comment]
Can you post png images ? that logo is fire !
