### ISSUE TITLE
[BUG] Map in detail view should respect dark mode setting.

### ISSUE THREAD

**Issue by ayykamp** [immich-app/immich#4116]
### The bug

When setting dark mode in the app map view it should apply to the detail map view as well

### The OS that Immich Server is running on

Na

### Version of Immich Server

1.78.1

### Version of Immich Mobile App

1.78.1

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Na
```

### Your .env content

```Shell
Na
```

### Reproduction steps

```bash
1. Open Search/Your Map
2. Open Detail view of any asset with location data
```

### Additional information

<img src="https://github.com/immich-app/immich/assets/32194363/3d00dc02-9bb2-4bcb-aa55-762b18173eb7" width="400">
<img src="https://github.com/immich-app/immich/assets/32194363/45221438-eaf2-4b91-8fd7-9cb9f0fd472b" width="400">

**Comment by shalong-tanwen** [comment]
Using the map theme setting might result in the map getting displayed in dark theme while the app is in light mode or vice verse. Instead, the map can be made dark if the app is in dark mode. This is the behavior in the search page and somehow got missed in the exif info bottom sheet.

**Comment by ayykamp** [comment]
Same thing applies to web btw, forgot to mention that

**Comment by ayykamp** [comment]
Has been fixed on web and mobile.
