### ISSUE TITLE
[BUG] Logging out doesn't redirect to login

### ISSUE THREAD

**Issue by bertmelis** [immich-app/immich#412]
**Describe the bug**
When I click "Log out", my browser doesn't redirect to the login page.

**System**
- Edge browser on Win 11
- v1.19.0 (latest pull from Docker)

The inspection panel does show a 200 response code with 'OK' statustext from the response after logging out. PING continue to run (with response code 304). I'm effectively logged out. Manually refreshing the page returns me to login.

I'm not familiar with debugging this app (the code is minified = too advanced for me).

**Comment by bertmelis** [comment]
Same thing happens when changing the password after first login. It stays on the "change password" page but manually refreshing solves it.

**Comment by alextran1502** [comment]
This perhaps relates to the change to using cookie authentication recently and conflict with previous authentication method.

If you open your browser in an incognito session and try again, does it also have the same issue?

**Comment by bertmelis** [comment]
Same thing. Mind that the logging out works. It's the (automatic) redirect that doesn't.

This condition should evaluate to true though: https://github.com/immich-app/immich/blob/1ba998aa68ad91aa3951c81fdf3f0570b7e2b704/web/src/lib/components/shared-components/navigation-bar.svelte#L48. When I inspect the requests/responses, I do get a 200 with statustext "ok".

**Comment by bertmelis** [comment]
The condition is a bit excessive as I read here though: https://developer.mozilla.org/en-US/docs/Web/API/Response. A `status` of `200` means `statusText` to be `OK`.

**Comment by bertmelis** [comment]
I don't know if it's important to know, but I'm accessing Immich via a reverse proxy (Traefik) that also does TLS termination.

**Comment by alextran1502** [comment]
Can confirm this also happen on my  reverse proxy instance. Logout wirk but redirect doesn't. I will take a look at this issue later

**Comment by bertmelis** [comment]
I'm somewhat happy I'm not the only one. I'll dive into the code as well although I'm not familiar with Svelte.

**Comment by alextran1502** [comment]
Yeah, the annoying part is that it works fine when you accessing the instance locally.

**Comment by alextran1502** [comment]
Fixed in #414
