### ISSUE TITLE
[BUG] <Immich app don't show albums for backup>

### ISSUE THREAD

**Issue by nekior** [immich-app/immich#4130]
### The bug

I created an immich server about 3 weeks ago and both via web interface and app everything worked fine.
Unfortunately, for a few days now I have no longer been able to find the albums locally on my andriod smartphone; when I enter the "backup" section all the information relating to the server is not available and if I go to select the albums for backup only the loading icon appears but even if I wait 30 minutes they can't find any files or albums.
There are around 50/60 files in total locally on the smartphone, while on the server there are around 30K for 140Gb of occupied space.
Furthermore, I have already made sure that the app has permission to access the files and while from the web interface everything works correctly.

Thank you

### The OS that Immich Server is running on

Truenas Scale 22.12.3.3

### Version of Immich Server

1.78

### Version of Immich Mobile App

1.78

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
container environment running in kubernetes
```

### Your .env content

```Shell
{
  "ffmpeg": {
    "accel": "nvenc",
    "crf": 23,
    "threads": 0,
    "preset": "ultrafast",
    "targetVideoCodec": "h264",
    "targetAudioCodec": "aac",
    "targetResolution": "720",
    "maxBitrate": "0",
    "bframes": -1,
    "refs": 0,
    "gopSize": 0,
    "npl": 0,
    "temporalAQ": false,
    "cqMode": "auto",
    "twoPass": false,
    "transcode": "required",
    "tonemap": "hable"
  },
  "job": {
    "backgroundTask": {
      "concurrency": 5
    },
    "clipEncoding": {
      "concurrency": 2
    },
    "metadataExtraction": {
      "concurrency": 5
    },
    "objectTagging": {
      "concurrency": 2
    },
    "recognizeFaces": {
      "concurrency": 2
    },
    "search": {
      "concurrency": 5
    },
    "sidecar": {
      "concurrency": 5
    },
    "storageTemplateMigration": {
      "concurrency": 5
    },
    "thumbnailGeneration": {
      "concurrency": 5
    },
    "videoConversion": {
      "concurrency": 1
    }
  },
  "machineLearning": {
    "enabled": true,
    "url": "http://immich-machinelearning:32002",
    "classification": {
      "enabled": true,
      "modelName": "microsoft/resnet-50",
      "minScore": 0.9
    },
    "clip": {
      "enabled": true,
      "modelName": "ViT-B-32::openai"
    },
    "facialRecognition": {
      "enabled": true,
      "modelName": "buffalo_l",
      "minScore": 0.7,
      "maxDistance": 0.6
    }
  },
  "map": {
    "enabled": true,
    "tileUrl": "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
  },
  "oauth": {
    "enabled": false,
    "issuerUrl": "",
    "clientId": "",
    "clientSecret": "",
    "mobileOverrideEnabled": false,
    "mobileRedirectUri": "",
    "scope": "openid email profile",
    "storageLabelClaim": "preferred_username",
    "buttonText": "Login with OAuth",
    "autoRegister": true,
    "autoLaunch": false
  },
  "passwordLogin": {
    "enabled": true
  },
  "storageTemplate": {
    "template": "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
  },
  "thumbnail": {
    "webpSize": 250,
    "jpegSize": 1440,
    "quality": 80,
    "colorspace": "p3"
  }
}
```

### Reproduction steps

```bash
1. Open app
2. Go to backup 
3. Try to select an album
```

**Comment by nekior** [comment]
I add these two screenshots with the app logs
![1695042468686](https://github.com/immich-app/immich/assets/145349090/f1216560-6da0-4404-8701-8f5ddcb9a394)
![1695042468691](https://github.com/immich-app/immich/assets/145349090/b5ceac81-4aa9-40dc-ab85-3295113525e4)

**Comment by simonl169** [comment]
I have the same error on my girlfriends phone
We are running Immich 1.78.1 on both phone and server
She has an Android phone

**Comment by ot73r** [comment]
Same on a freshly set up Android Phone. Both Versions are on 1.78.1. 

`#0      List.first (dart:core-patch/growable_array.dart:343)
#1      BackupNotifier._getBackupAlbumsInfo (package:immich_mobile/modules/backup/providers/backup.provider.dart:221)
<asynchronous suspension>
#2      BackupNotifier.getBackupInfo (package:immich_mobile/modules/backup/providers/backup.provider.dart:385)
<asynchronous suspension>
`

**Comment by simonl169** [comment]
If I see the release notes correct, this should be fixed by #4139 right?
Will test this

**Comment by nekior** [comment]
Today I updated both the server and the client to version 1.79 but the problem remains

**Comment by nekior** [comment]
Update: I have currently solved the problem by manually installing (via apk) the app version 1.77.
I noticed that on my (slightly old) Xiaomi Redminote7 smartphone the problem occurs while on my girlfriend's smartphone which is much more recent it does not.
