### ISSUE TITLE
[BUG] Clicking on numbered "cluster" in maps view opens a photo instead of the smaller numbered clusters

### ISSUE THREAD

**Issue by mynamewastaken** [immich-app/immich#4136]
### The bug

I have some number of photos clustered together by location on the map. I click on the number, and instead of a few different clusters popping up, one of the photos in that cluster opens directly. This seems like it only happens with higher numbers of photos. If i zoom in a bit, it will finally split apart the cluster and clicking those has the expected effect of popping up a few photo icons to click on.
(Let me know if the above is confusing and I'll attempt to do a screen recording)

I've tested this on Firefox 114.0 and Chromium `Version 116.0.5845.96 (Official Build) Fedora Project (64-bit)` with the same results.

### The OS that Immich Server is running on

Kubernetes k3s: v1.27.1+k3s1

### Version of Immich Server

1.78.1

### Version of Immich Mobile App

xxx

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Running in k8s with official helm chart (immich-0.1.2) and traefik (2.9.9) as ingress - not docker compose. I'm using a basically stock values.yaml file with all the services enabled and persistence enabled on most components.

The only real non-stock thing I have is a kustomize patch to add an additional volume mount to the immich-server component as the helm-chart supports adding an additional volume mount on other components but not immich-server.
```

### Your .env content

```Shell
env:
  TZ: America/Chicago
  LOG_LEVEL: verbose
  PUBLIC_IMMICH_SERVER_URL: "https://domain"
  PUID: 9999
  PGID: 9999
```

### Reproduction steps

```bash
1. Open Maps view
2. Click on a numbered cluster
3. A photo opens
3.1 I would expect to see either multiple smaller clusters or a list of photos popup here instead
```

### Additional information

This has happened for a few version upgrades prior to today.

**Comment by magicedy** [comment]
https://github.com/immich-app/immich/blob/e050121dbf02d362caedb89f3cc3ef28239cec9f/web/src/lib/components/shared-components/leaflet/marker-cluster/asset-marker-cluster.svelte#L22
https://github.com/immich-app/immich/blob/e050121dbf02d362caedb89f3cc3ef28239cec9f/web/src/lib/components/shared-components/leaflet/marker-cluster/asset-marker-cluster.svelte#L52-L62


It seems only clusters with 10 or fewer markers will spiderfy.

**Comment by jrasm91** [comment]
This isn't a bug, it is working as designed, even if you that isn't what you expect 😛.

Right now you just have to zoom in more
