### ISSUE TITLE
[BUG] microservices crash while image upload

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#4141]
### The bug

Microservices crash with following error while uploading attached image...
```
zář 19 13:04:14 server immich-microservices[373855]: [Nest] 373855  - 19. 09. 2023 13:04:14   ERROR [JobService] Unable to run job handler: QueryFailedError: invalid input syntax for type timestamp with time zone: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN"
zář 19 13:04:14 server immich-microservices[373855]: [Nest] 373855  - 19. 09. 2023 13:04:14   ERROR [JobService] QueryFailedError: invalid input syntax for type timestamp with time zone: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN"
zář 19 13:04:14 server immich-microservices[373855]:     at PostgresQueryRunner.query (/opt/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
zář 19 13:04:14 server immich-microservices[373855]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
zář 19 13:04:14 server immich-microservices[373855]:     at async InsertQueryBuilder.execute (/opt/immich/server/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
zář 19 13:04:14 server immich-microservices[373855]:     at async AssetRepository.upsertExif (/opt/immich/server/dist/infra/repositories/asset.repository.js:37:9)
zář 19 13:04:14 server immich-microservices[373855]:     at async MetadataExtractionProcessor.handleMetadataExtraction (/opt/immich/server/dist/microservices/processors/metadata-extraction.processor.js:154:9)
zář 19 13:04:14 server immich-microservices[373855]:     at async /opt/immich/server/dist/domain/job/job.service.js:105:37
zář 19 13:04:14 server immich-microservices[373855]:     at async Worker.processJob (/opt/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)
zář 19 13:04:14 server immich-microservices[373855]:     at async Worker.retryIfFailed (/opt/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)
zář 19 13:04:14 server immich-microservices[373855]: [Nest] 373855  - 19. 09. 2023 13:04:14   ERROR [JobService] Object:
zář 19 13:04:14 server immich-microservices[373855]: {
zář 19 13:04:14 server immich-microservices[373855]:   "id": "ce433da8-1e62-43c6-9cf4-7df8aa6394c6",
zář 19 13:04:14 server immich-microservices[373855]:   "source": "upload"
zář 19 13:04:14 server immich-microservices[373855]: }
```
As a result there is no thumbnail of image, just empty placeholder. ~~While viewing the image, there is infinite loop of requests to `GET https://server/api/asset/assetById/ce433da8-1e62-43c6-9cf4-7df8aa6394c6`~~ another buggy PR https://github.com/immich-app/immich/pull/4125

![obrazek](https://github.com/immich-app/immich/assets/15554561/77dbe7bf-a030-4a6a-b928-8467525cbb85)

[20120613_170405_IMG](https://github.com/immich-app/immich/assets/15554561/caf9a4fe-916f-4c2d-8a39-384f243628c8)

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

1a633f3

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
no docker
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
just try to upload image in web browser
```

**Comment by kevin-king** [comment]
I just ran into this as well. I checked `exiftool -time:all <path>` on every image with the issue (113/13600). I've tried setting various exif datetime fields like createdate, filemodifydate, etc. Also tried deleting the records from `immich.assets` database and regenerating. Tried going a regeneration through the UI itself. No luck.

I did a full import on v1.78.0 and everything was fine. Upgraded to 1.79.0 and did a full reimport when I had this issue.
