### ISSUE TITLE
[BUG] CLIP failed to download in immich_machine_learning

### ISSUE THREAD

**Issue by nick008a** [immich-app/immich#4157]
### The bug

RuntimeError: Failed to download https://clip-as-service.s3.us-east-2.amazonaws.com/models-436c69702d61732d53657276696365/onnx/ViT-B-32/textual.onnx within retry limit 3

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.78.1

### Version of Immich Mobile App

latest

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default file
```

### Your .env content

```Shell
default file
```

### Reproduction steps

```bash
1.default file
2.
3.
...
```

### Additional information

Is it possible to host the file in the docker image directly?

**Comment by mertalev** [comment]
This is being tracked in #4117
