### ISSUE TITLE
[BUG] Time buckets should use exif date/time if available

### ISSUE THREAD

**Issue by daniele-athome** [immich-app/immich#4165]
### The bug

The time buckets feature currently uses `assets.fileCreatedAt` which is the file creation date. If EXIF date/time information is available for an asset, taht should be used instead.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.79.0

### Version of Immich Mobile App

(not applicable)

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
(not applicable)
```

### Your .env content

```Shell
(not applicable)
```

### Reproduction steps

```bash
1. Import some pictures with file timestamp different from exif timestamp using an external library
2. Wait for the jobs to finish and open the timeline
```

**Comment by daniele-athome** [comment]
Sorry I was too rush. I saw that the metadata extraction job updates fileCreatedAt after extracting the tags:

```
    await this.assetRepository.save({
      id: asset.id,
      duration: tags.Duration ? Duration.fromObject({ seconds: tags.Duration }).toFormat('hh:mm:ss.SSS') : null,
      fileCreatedAt: exifData.dateTimeOriginal ?? undefined,
    });
```

It seems like a hack though, especially with new libraries feature which can now handle file system assets. Or maybe I'm overthinking it :-)

**Comment by jrasm91** [comment]
That column has always represented when a photo was taken. Working as intended.
