### ISSUE TITLE
[BUG] Massive Web Request when visiting People Page

### ISSUE THREAD

**Issue by Cebrain** [immich-app/immich#4194]
### The bug

Hey,

i dont know if it is a bug or maybe a optimization, bug i have a Problem when i use Immich on the People Page (https://immich.home/people) with my default Rate Limiting Settings in my Proxy (average=100 / burst=50)

I have about 11000 pictures in my library and when i visit the people page, 550 thumbnails will be loaded in an instant.

When i check the amount of requests when i visit the people page, i think all thumbnails and pictures are being loaded in ones.
So the Rate Limiting Setting kicks in. Maybe it would be better to load the thumbnails in bulks.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

1.7.9.1

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Open the Developer Tools in Browser
2. Open the people page and check if all pictures are loaded
3. Check the log in developer tools how many thumbnails are loaded
```

**Comment by martabal** [comment]
Hello,
It's not really a bug, it's a known limitation which should be solved in the future (see 4.a [here](https://github.com/immich-app/immich/discussions/2472))
