### ISSUE TITLE
[BUG] Search not showing all results

### ISSUE THREAD

**Issue by danny91** [immich-app/immich#4199]
### The bug

I'm trying to find all images taken with an iPhone 4S. All the images are tagged and I can confirm this by clicking on random ones that don't show in the search results.

When I search for:

m:4s 

The results seems to be limited or not showing all results.

### The OS that Immich Server is running on

Unraid Docker

### Version of Immich Server

v1.197.1

### Version of Immich Mobile App

not used

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
docker run
  -d
  --name='immich'
  --net='br0'
  --ip='...........'
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="tower"
  -e HOST_CONTAINERNAME="immich"
  -e 'TCP_PORT_8080'='8080'
  -e 'DB_HOSTNAME'='.........'
  -e 'DB_USERNAME'='Immich'
  -e 'DB_PASSWORD'='............'
  -e 'DB_DATABASE_NAME'='Immich'
  -e 'REDIS_HOSTNAME'='.........'
  -e 'DISABLE_MACHINE_LEARNING'='false'
  -e 'DISABLE_TYPESENSE'='false'
  -e 'DB_PORT'='5432'
  -e 'REDIS_PORT'='6379'
  -e 'REDIS_PASSWORD'='........'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png'
  -v '/mnt/user/appdata/immich/photos':'/photos':'rw'
  -v '/mnt/user/appdata/immich/ml':'/config/machine-learning':'rw'
  -v '/mnt/cache/appdata/immichl':'/config':'rw' 'ghcr.io/imagegenius/immich'
```

### Your .env content

```Shell
I don't think I have one on unraid? Cant find one in the directory.
```

### Reproduction steps

```bash
1. Loads lots of pictures with Camera metadata
2. Attempt to search it
3. Results are mising all results even though I have confirmed ones that don't show are tagged.
```

**Comment by alextran1502** [comment]
Hello, this is our current limitation until we build a more efficient view for displaying the search result. the results cannot be group as the timeline as the moment because they are sorted by relevant score.

**Comment by Moelf** [comment]
can we not at least do some sort of pagination as a temporary solution?

**Comment by alextran1502** [comment]
@Moelf yes this is what we wanted to do, just not having a chance to get to it yet. If you have time and ability, please feel free to help open a PR to help us on this one
