### ISSUE TITLE
[BUG] Manual backup continues when it's canceled during the startup

### ISSUE THREAD

**Issue by bee395** [immich-app/immich#4202]
### The bug

When a manual backup is started it takes some time before the actual files are uploaded
When the backup is canceled ( by clicking the "cancel backup button" or by moving the app to the background) while the backup is still starting up
The cancel event is send, but ignored by the backup service

This confuses the app about the actual state of the backup
It's possible to start multiple backups at the same time, or have the manual backup running while the app is in the background

Sometimes this hidden backup can only be stopped by completely closing the app (moving the app to the background is in some cases not enough)

### The OS that Immich Server is running on

Android 

### Version of Immich Server

v1.76.1

### Version of Immich Mobile App

v1.77

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. Start a manual backup
2. Click on the "cancel" button while the "file info" tile is still empty

Result:
The app will now show that no backup is running
The amount of uploaded files will however still increase, and it's possible to start an additional backup. Backups can also be stacked this way
```

### Additional information

This bug is mainly possible due to 'BackupNotifier.getBackupInfo' taking a very long time (30+ seconds in my case)

Ideally the backup should be canceled independent of the current state of the backup within "BackupNotifier.startBackupProcess"

**Comment by alextran1502** [comment]
I believe this has been fixed
