### ISSUE TITLE
[BUG] immich shows photos at wrong dates

### ISSUE THREAD

**Issue by basings** [immich-app/immich#422]
**Describe the bug**

I just uploaded a couple of images to immich to create albums. Some images are sorted with the wrong date stamp. Exif data under (i) is still correct and the file in immichs source folder shows the correct exif as well.  Photos were uploaded via android app 1.19.0 under A12.

**To Reproduce**
Can't reproduce it. Random images.

**Comment by alextran1502** [comment]
Can you please provide
1. Expected date
2. Incorrect date is being shown
3. If possible, is there a photo that you can share with me for debugging? Preferably put it in a zip file, so all the metadata is preserved

**Comment by alextran1502** [comment]
Another question: Is the problem solved if you try to log out and log back in?

**Comment by basings** [comment]
1. expected date for most incorrect files: 20191224
2. incorrect date: 20220626

I'm still trying to delete the folder to try another upload. I'll report as soon as I have new info.

Neither logging out and back in, nor restarting the server solves it.

**Comment by basings** [comment]
Could this error message be related?

````
[Nest] 7  - 08/02/2022, 3:43:57 PM   ERROR [ExceptionsHandler] invalid input syntax for type uuid: "null"
QueryFailedError: invalid input syntax for type uuid: "null"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2028:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1888:26)
    at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:638:29)
    at async SelectQueryBuilder.getOne (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:665:25)
    at async AssetService.getAssetThumbnail (/usr/src/app/dist/apps/immich/apps/immich/src/api-v1/asset/asset.service.js:153:23)
    at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
````

Moreover, while I'm scrolling through the albums on device to find the right album, another album repeatedly appears among the selected albums. If I click on `x` it just appears again after a while - although it's a duplicate album that's already selected.

**Comment by basings** [comment]
What I did on A12

1. I created a short term local backup for the album for restoration because immich will delete them in a later step
2. unselected the album for backup
3. search for all photos in immich of that album and deleted them manually, otherwise I can't reupload the photos
4. I just searched 15 minutes for the deleted album ....
5. I saw that another album also has the wrong date. But this time it's for the full album not only for a couple of images. Expected date 20210626. Realized date 20220802 (today) but exif in (i) is still correct.

**Comment by basings** [comment]
In the meanwhile I created three test users. For two, I uploaded the album which had for all (but one) image the wrong date assigned, I used the other user to upload from the web client.

The android uploads consistently had the wrong dates. The web client had no problem. I could remove geo location and redact people from the images if you'd like?

**Comment by alextran1502** [comment]
> Could this error message be related?
> 
> ```
> [Nest] 7  - 08/02/2022, 3:43:57 PM   ERROR [ExceptionsHandler] invalid input syntax for type uuid: "null"
> QueryFailedError: invalid input syntax for type uuid: "null"
>     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2028:25)
>     at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1888:26)
>     at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:638:29)
>     at async SelectQueryBuilder.getOne (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:665:25)
>     at async AssetService.getAssetThumbnail (/usr/src/app/dist/apps/immich/apps/immich/src/api-v1/asset/asset.service.js:153:23)
>     at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
>     at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
> ```
> 
> Moreover, while I'm scrolling through the albums on device to find the right album, another album repeatedly appears among the selected albums. If I click on `x` it just appears again after a while - although it's a duplicate album that's already selected.

Would this issue be related to this? https://github.com/immich-app/immich/issues/415#issuecomment-1200645226

Can you perform a screen recording to show the behavior, I am not getting this straight in my head.

**Comment by alextran1502** [comment]
> In the meanwhile I created three test users. For two, I uploaded the album which had for all (but one) image the wrong date assigned, I used the other user to upload from the web client.
> 
> The android uploads consistently had the wrong dates. The web client had no problem. I could remove geo location and redact people from the images if you'd like?

Yes, please, having a reproducible file is very helpful

**Comment by basings** [comment]
> > Could this error message be related?
> > ```
> > [Nest] 7  - 08/02/2022, 3:43:57 PM   ERROR [ExceptionsHandler] invalid input syntax for type uuid: "null"
> > QueryFailedError: invalid input syntax for type uuid: "null"
> >     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> >     at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2028:25)
> >     at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1888:26)
> >     at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:638:29)
> >     at async SelectQueryBuilder.getOne (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:665:25)
> >     at async AssetService.getAssetThumbnail (/usr/src/app/dist/apps/immich/apps/immich/src/api-v1/asset/asset.service.js:153:23)
> >     at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
> >     at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Moreover, while I'm scrolling through the albums on device to find the right album, another album repeatedly appears among the selected albums. If I click on `x` it just appears again after a while - although it's a duplicate album that's already selected.
> 
> Would this issue be related to this? [#415 (comment)](https://github.com/immich-app/immich/issues/415#issuecomment-1200645226)
> 
> Can you perform a screen recording to show the behavior, I am not getting this straight in my head.

I removed all folders for the test users and now it doesn't happen anymore.

**Comment by basings** [comment]
> > In the meanwhile I created three test users. For two, I uploaded the album which had for all (but one) image the wrong date assigned, I used the other user to upload from the web client.
> > The android uploads consistently had the wrong dates. The web client had no problem. I could remove geo location and redact people from the images if you'd like?
> 
> Yes, please, having a reproducible file is very helpful

Later, I got to go now.

**Comment by alextran1502** [comment]
> What I did on A12
> 
> 1. I created a short term local backup for the album for restoration because immich will delete them in a later step

I don't understand exactly the operations you described. When you talk about an album, do you mean an album created by the Photos app on the device? So in the Android world, I assume it is treated as a folder. 

I am not sure Immich can delete an album natively.

**Comment by alextran1502** [comment]
> > > Could this error message be related?
> > > ```
> > > [Nest] 7  - 08/02/2022, 3:43:57 PM   ERROR [ExceptionsHandler] invalid input syntax for type uuid: "null"
> > > QueryFailedError: invalid input syntax for type uuid: "null"
> > >     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
> > >     at runMicrotasks (<anonymous>)
> > >     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > >     at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2028:25)
> > >     at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1888:26)
> > >     at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:638:29)
> > >     at async SelectQueryBuilder.getOne (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:665:25)
> > >     at async AssetService.getAssetThumbnail (/usr/src/app/dist/apps/immich/apps/immich/src/api-v1/asset/asset.service.js:153:23)
> > >     at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
> > >     at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Moreover, while I'm scrolling through the albums on device to find the right album, another album repeatedly appears among the selected albums. If I click on `x` it just appears again after a while - although it's a duplicate album that's already selected.
> > 
> > 
> > Would this issue be related to this? [#415 (comment)](https://github.com/immich-app/immich/issues/415#issuecomment-1200645226)
> > Can you perform a screen recording to show the behavior, I am not getting this straight in my head.
> 
> I removed all folders for the test users and now it doesn't happen anymore. The album text just appears over and over again among the selected albums when removing them. As if I would've selected it again. But I was not even close to the album when scrolling through all albums

I want to clarify that this is the album selection screen, and you are trying to operate the "Include" , "Exclude" operation, correct?

**Comment by basings** [comment]
> > > In the meanwhile I created three test users. For two, I uploaded the album which had for all (but one) image the wrong date assigned, I used the other user to upload from the web client.
> > > The android uploads consistently had the wrong dates. The web client had no problem. I could remove geo location and redact people from the images if you'd like?
> > 
> > 
> > Yes, please, having a reproducible file is very helpful
> 
> Later, I got to go now.

Following is one of the images that showed a wrong date. I did not yet test if it still fails after I removed the geolocation and cut it with gimp. modified date obviously changed to today. The original modified date of the image was not modified today. I can't test it now if it still produces the same bug. I could do it in the course of the week though.

![image](https://user-images.githubusercontent.com/92867705/182453812-dd07273a-21db-4134-91a8-f36b66d568a5.jpg)

**Comment by basings** [comment]
> > What I did on A12
> > 
> > 1. I created a short term local backup for the album for restoration because immich will delete them in a later step
> 
> I don't understand exactly the operations you described. When you talk about an album, do you mean an album created by the Photos app on the device? So in the Android world, I assume it is treated as a folder.
> 
> I am not sure Immich can delete an album natively.

Yes, I was speaking about creating a local folder backup on android. When I delete images on immich on android, it deletes the local image as well, if it is in a current backup folder. I had to delete the images, otherwise I couldn't upload them again for the reproducible test. But then I just created another user because scrolling horizontally through hundreds of folder which are unordered is a real pain.


> I want to clarify that this is the album selection screen, and you are trying to operate the "Include" , "Exclude" operation, correct?

Yes, it is the album selection screen. No, I was not trying to do an "include" "exclude" operation. I was simply searching for the other folder for "including" it. While I scrolled through the folders, an other folder appeared above (shown with the name "XY". behind it is a blue box with an "x" for excluding it) This folder just got included without any reason. Moreover, it was a duplicate.

**Comment by basings** [comment]
> > What I did on A12
> > 
> > 1. I created a short term local backup for the album for restoration because immich will delete them in a later step
> 
> I don't understand exactly the operations you described. When you talk about an album, do you mean an album created by the Photos app on the device? So in the Android world, I assume it is treated as a folder.
> 
> I am not sure Immich can delete an album natively.

Yes, I was speaking about creating a local folder backup on android. When I delete images on immich on android, it deletes the local image as well, if it is in a current backup folder. I had to delete the images, otherwise I couldn't upload them again for the reproducible test. But then I just created another user because scrolling horizontally through hundreds of folder which are unordered is a real pain.


> I want to clarify that this is the album selection screen, and you are trying to operate the "Include" , "Exclude" operation, correct?

Yes, it is the album selection screen. No, I was not trying to do an "include" "exclude" operation. I was simply searching for the other folder for "including" it. While I scrolled through the folders, an other folder appeared above (shown with the name "XY". behind it is a blue box with an "x" for excluding it) This folder just got included without any reason. Moreover, it was a duplicate.

**Comment by basings** [comment]
![image](https://user-images.githubusercontent.com/92867705/182456878-7ae5667e-a999-4b8b-8496-d2c700c9beb2.jpg)

**Comment by FrankelJb** [comment]
Sorry for the necrobump.  I noticed that new photos were upload with tomorrow's date. I went back and confirmed that this has been happening for months. The photos have the correct date on my phone. Is there a setting I need to update? Is it possible to repair my library?

**Comment by alextran1502** [comment]
> Sorry for the necrobump.  I noticed that new photos were upload with tomorrow's date. I went back and confirmed that this has been happening for months. The photos have the correct date on my phone. Is there a setting I need to update? Is it possible to repair my library?

There is an opened PR to resolve this issue
