### ISSUE TITLE
[BUG] Not all photos on map on mobile view

### ISSUE THREAD

**Issue by titro** [immich-app/immich#4223]
### The bug

#3957 does not fix it complete.

I have still hundreds of photos which are not visible on the mobile map view.

Browser:

![image](https://github.com/immich-app/immich/assets/4005090/22d047b8-a039-4f33-b3ca-4dbb92243d22)

Android app:
![image](https://github.com/immich-app/immich/assets/4005090/e5d9a2f2-dbbf-4a72-ae54-a2aee0841699)

But the photos have a geo location and are shown unter locations, not on the map.

Any hints or what i can give you for information to fix?

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v.1.79.1

### Version of Immich Mobile App

v.1.79.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. Open mobile App
2. Open Search --> Map
3. No photos visible on the desired location on the mobile app
```

**Comment by klaus1k** [comment]
Same for me on Android - but I actually don't see any photos at all on mobile.
Date range "all" is selected.

**Comment by titro** [comment]
Any news on this?

**Comment by shenlong-tanwen** [comment]
> Any news on this?
 
Do you still face this issue? If so, Can you open one such asset in the web app and share its coordinates?

**Comment by titro** [comment]
I started from scratch with 1.91.X and photos are now visible on the mobile app. Don't know if that was a fix in the latest releases or the rescan of the library did it.
