### ISSUE TITLE
[BUG] selected albums are kept for different user sessions on android

### ISSUE THREAD

**Issue by basings** [immich-app/immich#423]
**Describe the bug**

When I sign in with another (test) user on android, the selected albums of the previously logged in account are the same and still there. Creating another test user and logging in with that one reproduces the same behavior.

**System**
- Phone OS [iOS, Android]: Android 12
- Server Version: 1.19.0
- Mobile App Version: `1.19.0 build.29`

**Comment by alextran1502** [comment]
I would like to discuss if we should treat this as a bug. The selected albums are bound by the device's local storage. In the real-world scenario, only you should be accessing and backing up to one account (ideally your account) from your phone, let's say you wouldn't let another user to login into your phone and backup your photos/videos to their account. Is that a fair assumption?

**Comment by basings** [comment]
Yes it is :) unless you want to find a bug, you won't notice it anyway.
