### ISSUE TITLE
[BUG] After naming a face, the search results for images are not correct.

### ISSUE THREAD

**Issue by 564192234** [immich-app/immich#4231]
### The bug

"Is it normal that when I run the demo, name a face, and then search, not all the photos related to him appear? "
![image](https://github.com/immich-app/immich/assets/73697191/fad2c82c-aa91-4814-96ed-cdb84d48450a)
I came across the facial search feature in the readme. Could you please guide me on how to use this feature? I hope I'm not misunderstanding anything.Thank you very much.

### The OS that Immich Server is running on

demo

### Version of Immich Server

1.79.1

### Version of Immich Mobile App

demo

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
demo
```

### Your .env content

```Shell
demo
```

### Reproduction steps

```bash
1.rename face name
2.search your photos
```

**Comment by jrasm91** [comment]
When a rename happens, all the assets for that person need to be re-sent to typesense for re-indexing, so it can take a little bit of time before it'll show up in the search results. We're hoping to improve this user experience in the near future.

**Comment by 564192234** [comment]
Ok, thanks for the reply.

**Comment by 564192234** [comment]
By the way, there is another question, the page about image classification “explore” is not displayed
![image](https://github.com/immich-app/immich/assets/73697191/a96d591b-815c-4378-bc21-c3195046bb3e)
![image](https://github.com/immich-app/immich/assets/73697191/07d892f3-5a98-4439-9cfc-a3a21e26938f)

**Comment by jrasm91** [comment]
Not 100% sure why, but there are currently no assets with any machine learning "tags" right now, so there is nothing to display on that page. The jobs might have just not run, or the min threshold is set too high.

**Comment by 564192234** [comment]
Thanks for the reply.Another question：Once immich is deployed on a local server, are all the functionalities implemented locally? If I don't use the mobile app, can I still use the web-based features without an internet connection?

**Comment by jrasm91** [comment]
More or less, yes. Some of the containers need an internet connection to download some supporting files, but you could always manually put them in the cache I think. Specifically, reverse geocoding downloads some csv files on startup and machine learning downloads the open ai models that we use at runtime. Once they are downloaded though, everything works "offline".

**Comment by ayykamp** [comment]
the map doesnt work offline since it uses the OSM tile server, no? but one could always self host a compatible tile server
