### ISSUE TITLE
[BUG] Randomly starts playing video while backing up for hours overnight

### ISSUE THREAD

**Issue by SteffeyDev** [immich-app/immich#4242]
### The bug

I have thousands of photos, so decided that leaving it running overnight would be fastest way to backup. After a while, my phone started playing a video randomly. I would then exit the video and go back to sleep. This happened again, a few hours later. After the second time this woke us up, I gave up and put the phone to sleep.

This may only happen if the most recent items in the library are videos. I left the screen on the photos view one time, and backup view another time, and both times after a long time it randomly opened and started playing one of the three videos that I have at the top of the library.

Is there any mechanism for automatically playing videos from the library without being tapped that could be malfunctioning to cause this?

### The OS that Immich Server is running on

Ubuntu 22.04.1 LTS

### Version of Immich Server

v1.79.1

### Version of Immich Mobile App

v1.79.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Adjust settings so that device never goes to sleep
2. Leave app open and backing up for several hours
3. Phone will randomly start playing most recent item in library, which is video (woke us up in middle of night)
```

**Comment by alextran1502** [comment]
Hello is this issue still relevance?

**Comment by mertalev** [comment]
Closing since there hasn't been any update in a while.
