### ISSUE TITLE
[BUG] mobile: deleted asset reappears while viewing

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#4272]
### The bug

Deleted asset reappears again after its removal while viewing assets.

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

v1.79.1

### Version of Immich Mobile App

v1.79.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. view asset, make sure there is at least one more asset on the left (previous)
2. delete asset, next asset is shown in the background while system is asking for confirmation of asset removal
3. swipe to right to go to previous asset
4. removed asset is shown again, however with thumbnail resolution (because the original is really deleted)
5. swipe to right again, now the correct asset is shown
6. when viewing is exited, removed asset disappears from the grid
```

**Comment by cvazquezeng** [comment]
I was looking around to see if anyone had the same issue. This happens to me too, oddly only while not on the view all page. If I filter photos, or I’m in the peoples page and I find I photo I do not want and delete ; this same thing happens. I would have to browse through all the gallery by dates and find my photo manually and delete it.

**Comment by alextran1502** [comment]
Hello, is this issue still relevance?

**Comment by waclaw66** [comment]
Hi @alextran1502, yes it's still an issue.

**Comment by waclaw66** [comment]
@shenlong-tanwen Could you please check this and https://github.com/immich-app/immich/issues/2748 issue? I've tried to dig into it, but I have few knowledge of the code. I believe there is just needed to remove deleted asset from some list. It's long standing annoying bug. Thanks.

**Comment by shenlong-tanwen** [comment]
> @shenlong-tanwen Could you please check this and #2748 issue? I've tried to dig into it, but I have few knowledge of the code. I believe there is just needed to remove deleted asset from some list. It's long standing annoying bug. Thanks.

#6966 Should fix it :)

**Comment by waclaw66** [comment]
> #6966 Should fix it :)

Thanks, haven't noticed that. Perfect learning material.

**Comment by waclaw66** [comment]
Fixed by https://github.com/immich-app/immich/pull/10603.
