### ISSUE TITLE
iOS app: backup file upload resets if you open a notification bar or switch to another app

### ISSUE THREAD

**Issue by freak12techno** [immich-app/immich#4292]
### The bug

When the iOS app is opened and is on a "Backup" screen, and if there's a backup going on and a large file is uploaded, the upload is reset if you either open a notification bar, or switch to another app. When focusing back on the app, the upload for this file starts over again. This might be annoying if dealing with uploading large files, like videos.

Sounds like a 100% client issue that's why I'm not providing docker-compose.yml/.env files, but please do let me know if they can help, I have a pretty much standard setup otherwise.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

1.79.1

### Version of Immich Mobile App

1.79.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
The default one
```

### Your .env content

```Shell
The default one
```

### Reproduction steps

```bash
1. Have a big file stored locally but not uploaded to server
2. Open a "Backup" screen
3. Scroll down and press Start backup
4. Wait until it's starting uploading that big file
5. Either swipe from the top of the screen (opening a notifications panel; no need to even open it fully, just swipe it a bit and then release, so the app would get focus), or switch to another app and back while the upload of this file isn't finished yet
6. The upload resets and starts from the beginning (I assume we should expect that it would continue either in the background, or at least continue once the app's focus is resumed)
```

**Comment by turingzz** [comment]
I have encountered this issue as well. When synchronizing videos, it takes too long, and if the iPhone screen goes off or I return to the home screen, the synchronization stops and the progress resets to zero. This frustrates me. I hope there will be two features: the ability to transfer large files when the iPhone screen is turned off, and the implementation of resumable transfers : )

**Comment by alextran1502** [comment]
Hello this is working as intended
