### ISSUE TITLE
[BUG] mobile: photo timestamp is shown with no respect of timezone

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#4298]
### The bug

|mobile|web|
|-|-|
|![obrazek](https://github.com/immich-app/immich/assets/15554561/29a78117-ff2d-41a0-81eb-3b16c3e19dcb)|![Snímek obrazovky 2023-10-02 090309](https://github.com/immich-app/immich/assets/15554561/e4633804-1357-4774-9760-8798eb8906f4)|

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

v1.79.1

### Version of Immich Mobile App

v1.79.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
not relevant
```

**Comment by jrasm91** [comment]
Can you share the relevant exif data and your expected results?

**Comment by waclaw66** [comment]
You can see expected results in picture from web version on right.
[20140525_163901_IMG_0389](https://github.com/immich-app/immich/assets/15554561/2dc204ce-1808-43ab-995f-86fd7cc36f42)
