### ISSUE TITLE
[BUG] Internal network information is disclosed on 500 page

### ISSUE THREAD

**Issue by eygraber** [immich-app/immich#4304]
### The bug

If a 500 error page is shown to the user, the internal IP and port is shown 
![Screenshot_20231002-185631~2](https://github.com/immich-app/immich/assets/1100381/aed84d05-42d7-485d-8f24-f80e2833e50b)

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.80.0

### Version of Immich Mobile App

v1.80.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
Get a 500 error page (see screenshot)
```

**Comment by alextran1502** [comment]
Please provide the required information and logs of the server container for help with troubleshooting

**Comment by eygraber** [comment]
Will do when I'm back from vacation.

**Comment by jrasm91** [comment]
This is an internal IP, not public ip

**Comment by eygraber** [comment]
If you hit this page you already have the public ip. The issue with providing the internal ip is that it gives an attacker more information than they had before.

**Comment by jrasm91** [comment]
We don't use immich proxy anymore anyways so I don't think this happens either way.
