### ISSUE TITLE
[BUG] Migrate thumbnails - Job successfully except for 2 assets

### ISSUE THREAD

**Issue by titro** [immich-app/immich#4305]
### The bug

The new Migration job moved all thumbnails in the new folder structure except for 2 assets (faces).

![image](https://github.com/immich-app/immich/assets/4005090/baf8a0b4-42c3-4ba5-b64e-915fc32a7be2)

![image](https://github.com/immich-app/immich/assets/4005090/fc0b3a0d-1d18-4f0a-bf59-c3e505f780b2)

![image](https://github.com/immich-app/immich/assets/4005090/75e28b40-dbd3-4523-9027-e74ddc8926b2)

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v.1.80.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. update to the latest version 1.80.0
2. run the Migration job. All assets are moved
3. 2 assets (in my installation) stay on the folder...
```

**Comment by waclaw66** [comment]
Probably orphans, check this https://github.com/immich-app/immich/pull/4112#issuecomment-1734135290 answer.

**Comment by jrasm91** [comment]
Yeah, I would recommend locating the asset in the database. You can search by path or asset id. The asset id should be uuid in the filename. If you search by that, that is `resizePath` for the jpeg ones.

https://immich.app/docs/guides/database-queries

**Comment by titro** [comment]
yup. orphaned. both files / UUIDs are not available in assets and assets_faces. double checked that with successfully migrated files. Thanks for the quick response. --> closed
