### ISSUE TITLE
[BUG] Generic Internal error when opening frontend

### ISSUE THREAD

**Issue by klejejs** [immich-app/immich#4308]
### The bug

I am not sure if it is after a release update, or after some time passes, but I get a generic error in the image below. On PC, it is easy to fix with Shift + F5, but on mobile, I cannot do that, so I cannot use the page.
The issue has been there for a long time :(
There is nothing in the logs, the only errors I can see in the console are the following:
<img width="1000" alt="image" src="https://github.com/immich-app/immich/assets/24546950/bd3ee5c7-ec25-4fab-bce2-9c71993ebc9f">

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.80.0

### Version of Immich Mobile App

v1.80.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open UI on base page and observe an error (when logged in)
```

### Additional information

![image](https://github.com/immich-app/immich/assets/24546950/19a593ce-0517-4930-9b71-d18c51a8b0dd)

**Comment by alextran1502** [comment]
Is this through a reverse proxy? Does it also happen if you access the instance locally?

**Comment by klejejs** [comment]
> Is this through a reverse proxy? Does it also happen if you access the instance locally?

Good point! I access Immich only through Traefik reverse proxy and never locally. I haven't had any issues with the same config for other self-hosted services, but it might be breaking something for Immich.
I will investigate further, but please let me know if you have any ideas.

**Comment by alextran1502** [comment]
If you can access the instance locally, somethings might have gone wrong with your Traefik's settings. I don't use Traefik but maybe posting your configuration here will catch some more eyes

**Comment by schuhbacca** [comment]
For reference here's my Traefik setup with Immich.

`  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    dns:
      - 192.168.1.2
    networks:
      - proxy
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    labels:
      - 'traefik.enable=true'
      - "traefik.docker.network=proxy" 
      - 'traefik.http.routers.immich_proxy.entrypoints=https'
      - "traefik.http.routers.immich_proxy.tls.certresolver=cloudflare"  
      - 'traefik.http.routers.immich_proxy.tls.options=default'
      - "traefik.http.routers.immich_proxy.rule=Host(`subdomain.mydomain.com`)"
      - "traefik.http.services.immich_proxy.loadbalancer.server.port=8080"  `

**Comment by jrasm91** [comment]
429 means "too many requests", which is more than likely not coming from anything related to immich.

**Comment by jrasm91** [comment]
This is most likely a setup issue unrelated to immich. Feel free to open a discussion if you need help troubleshooting.
