### ISSUE TITLE
[BUG] new week {{WW}} storage template

### ISSUE THREAD

**Issue by pinionless** [immich-app/immich#4315]
### The bug

after changing storage template to new format using year/week/filename.jpg
6 files with date 01-01-2023 are in folder 2023/52
Should be in folder 2023/01

### The OS that Immich Server is running on

ubuntu 22.10

### Version of Immich Server

1.80.00

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Storage tamplate set as: {{y}}/{{WW}}/{{dd}}-{{MM}}-{{y}} {{HH}}.{{mm}}.{{ss}}
2. video file mp4 made on 1/1/23 uploaded to Immich
3. file ends up in folder 2023/52/filename.jpg
```

### Additional information

Example video name placed in wrong folder: "01-01-2023 00.03.00.mp4"

mp4 file shows in windows properties under Origin/Content Created correct date same as file name
File shows up correctly in Immich timeline in January 2023

Photos with date 2nd January 2023 places correctly in 2023/01

**Comment by jrasm91** [comment]
Does the moved files have a exifInfo.timeZone value?

**Comment by pinionless** [comment]
I don't see a time zone in windows properties window. I don't have other exifinfo tools to check.

Anyway, file shows up correctly in January 2023 in Immich.
From PG Admin:
fileCreatedAt: 2022-12-31 23:03:00
So this puts it in W 52? but it still ends up in correct year folder 2023.

**Comment by jrasm91** [comment]
Right, there is an exif info table with a time zone column. Asset joins to exit info one to one. I'm guessing this is null. When it is null the web defaults to the timezones of the browser, which is why it is "correct". The storage job doesn't fallback to that though. We can probably default to the container timezones if one isn't detected though.
