### ISSUE TITLE
[BUG] External Libraries: Not able to edit the upper one if more than one gallery available

### ISSUE THREAD

**Issue by v3DJG6GL** [immich-app/immich#4327]
### The bug

If there is more than one external library listed under **Settings** --> **Libraries**, you cannot edit the ones above: Opening the **3-dot menu** and selecting **Rename** or **Edit Import Paths** for example, immich opens the settings for the lowest gallery in the list. I can observe the same behavior no matter how many galleries I add.
Also, I can't change the name for the *Default Library** because the same behavior occurs.

### The OS that Immich Server is running on

TrueNAS-SCALE-22.12.2

### Version of Immich Server

v1.80

### Version of Immich Mobile App

v1.80

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Open Settings -> Libraries
2. Try to change the settings for an upper external gallery.
```

**Comment by v3DJG6GL** [comment]
No, I am talking about external libraries. If there is more than one present, you cannot edit the upper ones.

**Comment by alextran1502** [comment]
Ah crap, you are right. Sorry, reopen
