### ISSUE TITLE
[BUG] web: add hover background to image toolbar icons

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#4343]
### The bug

In the same way as the X button on Info panel.

![obrazek](https://github.com/immich-app/immich/assets/15554561/b40c4a8c-6491-40d9-ac16-1745ea00bc76)

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

v.1.81.1

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
not relevant
```

**Comment by vedant-z** [comment]
@waclaw66 I would love to work on this issue. Please allow me.
