### ISSUE TITLE
[Improve] Nav bar can be attractive if we add text beside the logo 

### ISSUE THREAD

**Issue by HridoyHazard** [immich-app/immich#4344]
### The bug

![image](https://github.com/immich-app/immich/assets/71395891/224580d0-69cf-40a6-9808-7b572d6c8070)

current nav bar

![image](https://github.com/immich-app/immich/assets/71395891/400215d0-c708-4a93-8752-45d12870cf6c)
if we can add text beside the logo it will look more attractive

i can work on this issue. plz assign this to me.

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

v.1.81.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
not relevant
```

**Comment by HridoyHazard** [comment]
it was assigned to me then why other taking this issue without even asking ? @alextran1502 i was working on this issue and now someone made pr? @alextran1502

**Comment by alextran1502** [comment]
@HridoyHazard ah crap, I don't have control over other's action. Sorry about that

**Comment by jrasm91** [comment]
Added in #4463.
