### ISSUE TITLE
[BUG] iOS background backup stalls after a few photos, and those few photos don't actually upload

### ISSUE THREAD

**Issue by achusuresh2** [immich-app/immich#4360]
### The bug

I have never been able to keep background uploads working beyond a few photos. Once the upload starts, I see the notification count up for a few photos and then it just remains there. I get no notification of background upload failed, the number just never increases after that. No new backup is initiated after this happens either.  Eventually, when I open the app, I found that the photos remaining number didn't even change by the few photos the background upload claimed to upload. 

### The OS that Immich Server is running on

Application on TrueNAS Scale

### Version of Immich Server

1.80.0

### Version of Immich Mobile App

1.80.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
No docker-compose file, running in TreuNAS scale. 
Config shown in additional information
```

### Your .env content

```Shell
No .env file
```

### Reproduction steps

```bash
1. Turn on background uploads
2. Leave the app and wait for uploads to start
3. Uploads will start and stall after a few photos
4. Photos remaining will be unchanged when app is eventually reopened.
```

### Additional information

TrueNAS Scale Application Config

Immich Configuration

Timezone
'America/Toronto' timezone
Public Login Message

Enable Machine Learning - enabled
Enable Typesense - enabled

Network Configuration

Web Port
[PORT]

Storage Configuration

help_outline
Immich Uploads Storage
ixVolume (Dataset created automatically by the system)

Immich Library Storage
ixVolume (Dataset created automatically by the system)

Immich Thumbs Storage
ixVolume (Dataset created automatically by the system)

Immich Profile Storage
ixVolume (Dataset created automatically by the system)

Immich Video Storage
ixVolume (Dataset created automatically by the system)

Additional Libraries
No items have been added yet.

Immich Postgres Data Storage
ixVolume (Dataset created automatically by the system)

Immich Postgres Backup Storage
ixVolume (Dataset created automatically by the system)

Resources Configuration

Limits
CPU
4000m

Memory
8Gi

**Comment by alextran1502** [comment]
If you don't see the assets get uploaded, then probably the server has issues. Can you upload some assets on the web interface and verify if you can see them?

**Comment by achusuresh2** [comment]
Hey, 

Yes, I can confirm that uploads using the web interface work, and uploads using the CLI tool also work. Also, any items uploaded by the foreground process (except one very large video I have - not sure why this isn't working) seem to upload just fine. 

For me personally, the background upload seems to stall after around 9 items usually.

**Comment by achusuresh2** [comment]
I was reading through the FAQs and noticed that video uploads can have issues when using a Cloudflare tunnel due to the size limit, and that's what I've been using. But I've been having issues with both photos and videos, but could this still be a part of it perhaps?

**Comment by alextran1502** [comment]
The background task can only run about 10-15 seconds for each invocation, and this is the allowable time that iOS allows for short background tasks to run.

**Comment by achusuresh2** [comment]
So could it be that a single large file could result in the same file failing to upload multiple times in the background instead of moving on to other files?

**Comment by alextran1502** [comment]
Potentially, but in foreground context, we purposely upload photos first, then videos. Perhaps it could be a really large raw file? 🤔

**Comment by achusuresh2** [comment]
I was able to get past it by just leaving the app open in the foreground and now the uploads seem to be working now that I don't have as many files to upload in one go. So maybe this issue can be closed for now.
