### ISSUE TITLE
[BUG] application language

### ISSUE THREAD

**Issue by maaxpane** [immich-app/immich#4362]
### The bug

The application does not change to the device's language, in this case my local language would be PT_BR, and the application is in English, I have already tested it on other devices and the problem persists

### The OS that Immich Server is running on

ubuntu 22.04

### Version of Immich Server

v1.79.1

### Version of Immich Mobile App

1.80.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not
```

### Your .env content

```Shell
not
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by traktuner** [comment]
Hello!
I have the same issue on mobile (iOS + Android).
Server 1.81.1, mobile apps 1.80.0
Language should be German (de_AT)
Problem exists on multiple devices

Web app is also in english but I guess there is no translation for web so far.

**Comment by alextran1502** [comment]
Implemented in app language setting
