### ISSUE TITLE
[BUG] Mobile app requires endpoint protocol

### ISSUE THREAD

**Issue by austinvaness** [immich-app/immich#4397]
### The bug

In the mobile app setup screen, the server endpoint requires `http://` or `https://` to be specified otherwise it fails with a generic error message. 

Example: `mydomain.com` fails and `https://mydomain.com` works.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.81.1

### Version of Immich Mobile App

v1.80.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
Enter a domain into the server endpoint field without `https://`
```

**Comment by Rihcus** [comment]
Maybe a menu should be added asking the user if they want http or https like the homeassitant compantion app? This could be helpful for users only using immich on a local network or via wireguard/tailscale where https isn't as essential.

![image](https://github.com/immich-app/immich/assets/30292597/2f2855cc-0ac8-4c68-b9ac-ee206f5843da)

**Comment by waclaw66** [comment]
I would suggest to check `https://` first. If it fails, then show error message like now.

**Comment by etnoy** [comment]
Agreed on using https by default. http should only be used if the user explicitly enters it

**Comment by austinvaness** [comment]
Don't make me learn Dart to fix this
