### ISSUE TITLE
[BUG] Android login fails if no protocol specified

### ISSUE THREAD

**Issue by RDKRACZ** [immich-app/immich#4428]
### The bug

I'm testing immich, after installing I wanted to try the mobile app and couldn't log in. Turned out I forgot to add "http://" before the IP address.
Immich should detect this error and add http(s) automatically or at least tell the user what's missing.

### The OS that Immich Server is running on

Doesn't matter

### Version of Immich Server

1.81.1

### Version of Immich Mobile App

1.80.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Doesn't matter
```

### Your .env content

```Shell
Doesn't matter
```

### Reproduction steps

```bash
Try to log in the your server from the Android app without specifying port in the address
```

**Comment by ddshd** [comment]
Similar to #4397

**Comment by RDKRACZ** [comment]
Yes, I missed it while searching. Mine also proposes solution but it's a duplicate so probably better close it.
