### ISSUE TITLE
[BUG] Transcode videos Android Live Photos issue after DB restore

### ISSUE THREAD

**Issue by phoropter** [immich-app/immich#4444]
### The bug

If an immich install is wiped then the database restored, the transcode videos job does not handle the small video that's a part of an android live photo. When trying to view a live photo an error like this occurs:
`[Nest] 8  - 10/11/2023, 10:16:42 AM   ERROR [ExceptionsHandler] ENOENT: no such file or directory, access 'upload/encoded-video/fa2260ba-ca94-4e91-93d7-f6325125a679/36/10/3610befa-d64e-4c2c-8a04-e3232a30a061.mp4'
Error: ENOENT: no such file or directory, access 'upload/encoded-video/fa2260ba-ca94-4e91-93d7-f6325125a679/36/10/3610befa-d64e-4c2c-8a04-e3232a30a061.mp4'`

### The OS that Immich Server is running on

TrueNAS Scale

### Version of Immich Server

v1.81.1

### Version of Immich Mobile App

v1.81.1 build.2105

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
This is not used in Scale
```

### Your .env content

```Shell
This is not used in Scale
```

### Reproduction steps

```bash
1. Back up DB
2. Delete immich & data
3. Reinstall immich and restore DB
4. Run transcode videos (all) job
5. The server throws an error when trying to view the video of a live photo
```

**Comment by bo0tzz** [comment]
Did you only restore the DB, or also the folder where files are stored?

**Comment by phoropter** [comment]
I only restored the DB. 

[This is the relevant discord help desk thread](https://discord.com/channels/979116623879368755/1161446806484430909).

**Comment by truongsinh** [comment]
could be related to https://github.com/immich-app/immich/issues/5977
