### ISSUE TITLE
[BUG] Web: Click on checkmark crash browser

### ISSUE THREAD

**Issue by MalteKiefer** [immich-app/immich#446]
**Describe the bug**
When I click on a checkmark in the web version to mark an image, the hole browser crashes.
I tried it with different browsers. 
Browser console shows no errors.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [X] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [X] I have included information on my machine, and environment.

**System**
- Server Version: `v1.21.0_31-dev`
- Mobile App Version: `v1.21.0_31-dev`

**Comment by alextran1502** [comment]
Hi @MalteKiefer .
How many assets to do have on this instance?

**Comment by MalteKiefer** [comment]
```
root@server /s/i/docker# ls /opt/photos/1ef8cd67-eabb-479f-95bb-e88622afe553/original/9a41422f-c9fb-51da-a2ed-147325235078/ | wc -l
33937
root@server /s/i/docker# ls /opt/photos/1ef8cd67-eabb-479f-95bb-e88622afe553/original/WEB/ | wc -l
187
root@server /s/i/docker# ls /opt/photos/1ef8cd67-eabb-479f-95bb-e88622afe553/encoded-video/ | wc -l
275
```

**Comment by alextran1502** [comment]
This might be related to performance when it try to toggle the check box on all image group. Let me test it on a large instance of mine and find the fix for this

**Comment by alextran1502** [comment]
Can confirm this is a performance bug on large instance.

**Comment by MalteKiefer** [comment]
@alextran1502 make it like Google, Apple and all the others, max 1000 photos at the same time. it is more then enough
