### ISSUE TITLE
[Feature]: Add APK to release

### ISSUE THREAD

**Issue by MalteKiefer** [immich-app/immich#447]
### Feature detail

Hi, 

can you add an APK to the releases?
So I can add it to my personal fdroid repo.

Thanks

### Platform

Mobile App

**Comment by alextran1502** [comment]
Done!

**Comment by fcaronte** [comment]
Hi all, what about add possibility to have apk signature same as the PlayStore version? Actually if I want to update from apk i Need to uninstall PlayStore One and setup again from scratch all my folder to be synced, I think signature should be the same for all immich apk version

**Comment by alextran1502** [comment]
Yeah, we are working toward fully automatic deployment, which will help with the signature
