### ISSUE TITLE
Duplicates from App Backup and External Library

### ISSUE THREAD

**Issue by lyhnet** [immich-app/immich#4487]
I have a Docker setup with a volume added in the config to access my old photo archive . 

```
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /home/lyhnet/oldphotos:/mnt/media/oldphotos:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
````
The photos in the path are loaded by Immick, Good!

I used to sync my Android phone to `oldphotos`  using Synology Photos.

My Android still has many of the photos in `oldphotos`.

Now when I Backup my Android phone with Immich, Immich does not detect duplicates against the External Library.

I know I could add upload `oldphotos` to Immich and that should resolve the issue. However Immich being beta software I would like to keep my  `oldphotos` read-only and static to protect that. 

Is it a bug? If not, is it planned to make this check perhaps optionally. 

@alextran1502 in below Issue you mentioned that it was the use of External Library that was wrong. Immich being beta makes me worried to import all of my existing photos. And to maintain two separate photo sets seems like a bad idea. Isn't it possible to add the duplication step to include the External Library?

_Originally posted by @toxic0berliner in https://github.com/immich-app/immich/issues/4413#issuecomment-1756019392_

and

_Originally posted by @agross in https://github.com/immich-app/immich/discussions/1968#discussioncomment-7248787_

**Comment by skrobul** [comment]
I have run into the same problem - thought it might be possible to exclude particular folders in the `oldphotos` folder in Scan settings but that does not seem to have any effect for external libraries

**Comment by alextran1502** [comment]
This is the current "working as intended"
