### ISSUE TITLE
[BUG] Android APP need to relogin to get timeline after server and app upgraded

### ISSUE THREAD

**Issue by AlliotTech** [immich-app/immich#4506]
### The bug

After the server and APP are upgraded to [v1.82.0](https://github.com/immich-app/immich/releases),
Android app keeps showing "Timeline loading".

So I have to log back into it and then it will show the photos.

This prompt may be misleading, keeping the user on the loading page instead of logging in again.

### The OS that Immich Server is running on

ubuntu

### Version of Immich Server

v1.82.0

### Version of Immich Mobile App

v1.82.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
1. update server to v1.82.0
2. update APP to v1.82.0
3. open the Android APP
...
```

**Comment by alextran1502** [comment]
I don't think we have a remedy for this besides logging out and login back in

**Comment by AlliotTech** [comment]
I guess if we can modify the prompt or notification or just redirect user to login page.
