### ISSUE TITLE
[BUG] "NO EXIF INFO AVAILABLE" when viewing photo in memory

### ISSUE THREAD

**Issue by chain710** [immich-app/immich#4528]
### The bug

Just like this

![image](https://github.com/immich-app/immich/assets/486539/d5acdd2b-f53f-4ac4-8ea5-791e0ca5daa1)

Every photo in that memory prompts the same error

### The OS that Immich Server is running on

Debian 11.8

### Version of Immich Server

v1.82.0

### Version of Immich Mobile App

v1.82.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Irrelavant
```

### Your .env content

```Shell
Irrelavant
```

### Reproduction steps

```bash
1. Click on the memory cards on top of main page
2. Scroll down, click on any photo
3. Got "NO EXIF INFO AVAILABLE"
```

### Additional information

When scrolling the mouse wheel in the "Info" area, the vertical scrollbar responds, which also triggers the loading of other photos in memory, which should not be the expected behavior.

![image](https://github.com/immich-app/immich/assets/486539/9d6f4013-6219-48a5-874a-da2b7763e85c)

**Comment by alextran1502** [comment]
Just to confirm, if you view this photo from your timeline, there is information shown in the detail panel, correct?

**Comment by nicokaiser** [comment]
Same here, with v1.82.1, but the detail panel says "Metadata not loaded for ..." instead. When viewed from the timeline (or the search results), everything is fine, and like @chain710 said, the metadata JSON seems to be loaded but not used.
Faces are being shown in the detail panel though.

Please let me know if there is any additional info we can provide for reproducing this.
