### ISSUE TITLE
[Feature]: Ability to upload a Google takeout zip file

### ISSUE THREAD

**Issue by gregoryduckworth** [immich-app/immich#455]
### Feature detail

It would be nice if you had the ability to upload a Google takeout zip file with photos as it contains the Album structure and all the json data associated with it, e.g: people, geolocation etc..

### Platform

Web

**Comment by Nonobis** [comment]
very nice idea !

**Comment by Nonobis** [comment]
https://github.com/mattwilson1024/google-photos-exif
https://github.com/andyjohnson0/TakeoutExtractor

Could be used as base to clean/import data correctly.

**Comment by alextran1502** [comment]
Google Takeout Zip file will need to parse metadata first before uploading. CLI tool can be used after the files are parsed
