### ISSUE TITLE
[BUG] [Web-Timeline] Only two "year" labels on a web timeline

### ISSUE THREAD

**Issue by MozPri** [immich-app/immich#4557]
### The bug

I have more than 30k assets from the year 2002 to 2023.
But Immich only displays two labels on a web timeline, 2003 on the bottom and 2023 on top. All empty space with dots in between.

I would expect a more dense label population on the timeline to quickly navigate through the years similar to Google Photos.
Tested on Chrome, FF, and Edge on Windows 10.

Immich
![immich](https://github.com/immich-app/immich/assets/8180464/6ea850a6-cccd-466e-ac16-7e2558ee1f4f)

Google Photos
![gphotos](https://github.com/immich-app/immich/assets/8180464/e8fb8e59-616a-4eed-a571-a5b687392de7)

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.82.1

### Version of Immich Mobile App

v1.82.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by alextran1502** [comment]
fixed!
