### ISSUE TITLE
[BUG] Deleting from Trash isn't deleting the picture file

### ISSUE THREAD

**Issue by briandipalma** [immich-app/immich#4595]
### The bug

Since the Trash feature update Immich has stopped deleting files. I can work around it by getting the files I need to delete from the Repair page and manually deleting them. I'm guessing clearing the Trash can should delete the files? Or is there still a hidden delay in the process?

### The OS that Immich Server is running on

Ubuntu LTS

### Version of Immich Server

1.82.1

### Version of Immich Mobile App

1.82.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by shenlong-tanwen** [comment]
@briandipalma Can you upload a new asset, check the path of it in the uploads folder, trash and subsequently empty it and then re-check the uploaded path and check whether the file is still not deleted?

Also, is this happening to all your assets or the ones that are recently uploaded / uploaded in the past?

**Comment by briandipalma** [comment]
OK it looks like different directories in my library have different file permissions. Not a bug in Immich but it should probably be surfaced better? Immich could create the files but it couldn't delete them which is very weird.

**Comment by dRuEFFECT** [comment]
i'm running the latest version of immich on docker with unraid, confirmed there are no permissions issues on the files or folders, and can confirm that emptying trash does NOT delete the actual files. this should be reopened

**Comment by gdelazzari** [comment]
I can also confirm this. No permission issues (Immich automatic checks pass, and from `/bin/sh` inside the container I can create and delete files), but after deleting ~6GB of pictures and emptying the trash folder, the disk usage where the library is stored only decreased by less than 1GB.

*Administration/Server Stats* instead correctly shows that the library is using 6GB less than before.

Is there a workaround at the time being to make Immich delete the dangling files from the library folder?

**Comment by dRuEFFECT** [comment]
> Is there a workaround at the time being to make Immich delete the dangling files from the library folder?

the only thing i can think of is changing the root folder of the user, or the folder structure, then run migration on the existing assets, and lastly manually delete the files remaining in the original location
