### ISSUE TITLE
[BUG] iOS - Upload progress bar inconsistency

### ISSUE THREAD

**Issue by 20pins** [immich-app/immich#462]
**Describe the bug**
When uploading assets, the progress bar in the "Uploading file info" section of the iOS app jumps back and forth to different values. When swapping up to engage app-switching mode, it settles down. Also, progress for uploaded files will reset to 0% when going into, and then back out of, the app switch motion. When I'm going into app switching, I am not actually leaving the app. My finger remains on the app and I'll pull it back down to make it the active on-screen app again.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
Steps to reproduce the behavior: Not exactly sure. I've only seen it happen with this one file so far.

**Expected behavior**
Progress bar percentage should remain intact and not flicker between different values. Progress percentage should remain intact when switching between other apps.

**Screenshots**
https://imgur.com/a/XQb0x5F

**System**
- Phone OS [iOS]: `<15.6>`
- Server Version: `<1.22.0>`
- Mobile App Version: `<1.22.0 build 42>`

**Additional context**
Running these containers on a Synology 1621+ with DSM7.

**docker-compose.yml**
`version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:80
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  db:`

**.env**
`###################################################################################
#Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

#Optional Database settings:
#DB_PORT=5432

###################################################################################
#Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

#Optional Redis settings:
#REDIS_PORT=6379
#REDIS_DBINDEX=0
#REDIS_PASSWORD=
#REDIS_SOCKET=

###################################################################################
#Upload File Config
###################################################################################

UPLOAD_LOCATION=/volume1/docker/immich/upload

###################################################################################
#JWT SECRET
###################################################################################

JWT_SECRET=a-secret-string

###################################################################################
#MAPBOX
####################################################################################

#ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=true
MAPBOX_KEY=a-map-key-is-here

####################################################################################
#WEB - Optional
####################################################################################

#Custom message on the login page, should be written in HTML form.
#For example VITE_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"

VITE_LOGIN_PAGE_MESSAGE=`

**Comment by alextran1502** [comment]
Nice find! Thank you, I haven't noticed this since I mostly use local upload, which is really fast so I barely notice the issue :P

**Comment by 20pins** [comment]
> Nice find! Thank you, I haven't noticed this since I mostly use local upload, which is really fast so I barely notice the issue :P

Happy to help. I updated the link to the screenshot since it wasn't playing for me.

**Comment by alextran1502** [comment]
Found the issue, it happened when you double tapped the upload button quickly so it enables the backup process twice. I will put in a fix soon

**Comment by 20pins** [comment]
> Found the issue, it happened when you double tapped the upload button quickly so it enables the backup process twice. I will put in a fix soon

Just an FYI on the exact behavior going on in the video. I'm dragging from the bottom of the app, as if to switch apps. I'm not directly click on the upload button. In fact when I go to switch apps, there is no upload button. It switches to an upload button once I've pulled up on the app, and then when I release it appear to treat is as if I've selected that button, even though I didn't. Hopefully this provides more clarity.

**Comment by bo0tzz** [comment]
Is this still happening in the latest version of the app?

**Comment by hmorato** [comment]
> Is this still happening in the latest version of the app?

Yes, just happened a couple of times at v1.129.0 build 187.

**Comment by fivestones** [comment]
@bo0tzz I have v1.134.0 build.208 on iOS and it's still happening for me. Running iOS 18.3.1 (22D72).
