### ISSUE TITLE
[BUG] Custom CSS only works for logged-in admins

### ISSUE THREAD

**Issue by jrasm91** [immich-app/immich#4631]
### The bug

The new cusom css feature only works for admins, who are logged in, so it doesn't impact any unauthenticated routes (login page) or for any secondary users.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Create custom css
2. Go to the login page or Login with a non-admin user
3. Observe in immich-web log
...
```

**Comment by Wingysam** [comment]
I see what's wrong. The API I used requires the admin to be logged in and I didn't know that.

**Comment by jrasm91** [comment]
Yeah, feel free to work on it if you want, other @danieldietzler can probably take a look. I believe we are thinking of solving this by:
- Adding a new route `GET /system-config/custom.css` (public route)
- Adding a new service method `configService.getCustomCss()`
- The service implementation can load and return the css string with the right mime type.
- Update the svelte GET handler to use the public endpoint

**Comment by Wingysam** [comment]
I took a different route and added it to the ServerConfig, I'll make a PR with that now.
