### ISSUE TITLE
[BUG] Errors in CLI when using "immich-admin enable-password-login"

### ISSUE THREAD

**Issue by Tyree** [immich-app/immich#4667]
### The bug

When I attempt to use `immich-admin enable-password-login` or `immich-admin disable-password-login` I get an error:
```
immich-admin enable-password-login
TypeError: Cannot read properties of null (reading 'emit')[Nest] 1179  - 10/27/2023, 8:52:30 AM   ERROR [MetadataService] Unable to initialize reverse geocoding: Error: Connection is closed.
Error: Connection is closed.
    at EventEmitter.sendCommand (/app/immich/server/node_modules/ioredis/built/Redis.js:332:28)
    at Script.execute (/app/immich/server/node_modules/ioredis/built/Script.js:59:26)
    at EventEmitter.pause (/app/immich/server/node_modules/ioredis/built/utils/Commander.js:111:27)
    at Scripts.pause (/app/immich/server/node_modules/bullmq/dist/cjs/classes/scripts.js:103:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Queue.resume (/app/immich/server/node_modules/bullmq/dist/cjs/classes/queue.js:136:9)
    at async MetadataService.init (/app/immich/server/dist/domain/metadata/metadata.service.js:77:13)
```
Even with the error, it does update the enable password login setting.

### The OS that Immich Server is running on

unRAID 6.12.4

### Version of Immich Server

v1.82.1

### Version of Immich Mobile App

v1.82.0 build.106

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
unRAID Package, no compose file
```

### Your .env content

```Shell
unRAID Package, no env file
```

### Reproduction steps

```bash
1. Open terminal for Immich container
2. Enter command: immich-admin enable-password-login
```

### Additional information

This isn't isolated. It happens on two different unRAID servers in two different environments.

**Comment by jrasm91** [comment]
Looks like there is still some situations that cause an `AggregateError` to be logged.

**Comment by Xiticks** [comment]
Running in Truenas Scale, using the Truecharts catalog image, I have the error running the command in any order.
I don't have another system to try it tho, but I could launch the image from Truenas catalog to check if it reports the same, if needed.
<img width="565" alt="image" src="https://github.com/immich-app/immich/assets/56741168/1a0cbf54-b0ce-4fcc-a6cc-13944d55ffc2">

**Comment by jrasm91** [comment]
Can you test this again?

**Comment by Tyree** [comment]
Hey, Jason...
Tried again. Now I get this:
```
root@0d54debb075f:/# immich-admin enable-password-login
Error: connect ECONNREFUSED 127.0.0.1:3001root@0d54debb075f:/# immich-admin disable-password-login
Error: connect ECONNREFUSED 127.0.0.1:3001root@0d54debb075f:/# immich-admin enable-password-login
Error: connect ECONNREFUSED 127.0.0.1:3001root@0d54debb075f:/# 
```

**Comment by Xiticks** [comment]
I waited for TrueCharts to update the app (1.88.2), but I still have the AggregateError, but as Tyree said, the setting is still updated and it still works!

**Comment by jrasm91** [comment]
Looking at this again, I realized that the port `3001` that was being used should have actually been `process.env.SERVER_PORT`, since the TrueNas chart sets this to a different value. However, recent changes to how the config is used, means that extra communication isn't even necessary, which is why everything worked either way. This will be fixed in the next release.
