### ISSUE TITLE
[BUG] Server Status Usage shows different values in different locations.

### ISSUE THREAD

**Issue by yurividal** [immich-app/immich#4668]
### The bug

<img width="1216" alt="image" src="https://github.com/immich-app/immich/assets/8555749/8cb7edd4-1bf0-4599-b8d8-1b3abb886fd6">

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

1.82.1

### Version of Immich Mobile App

1.82.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
same as example
```

### Your .env content

```Shell
same as example
```

### Reproduction steps

```bash
Go to page /admin/server-status and look at the value in the 2 different locations.
```

### Additional information

See screenshot

**Comment by alextran1502** [comment]
The storage is the status of the mount of `UPLOAD_LOCATION`, whereas the Storage in the server status page is how much storage the actual raw files take.

**Comment by yurividal** [comment]
i see. makes sense. Maybe an improvement would be to word it better? it just seems a bit contradictive having 2 diffrent things with the same name on the same page.

**Comment by alextran1502** [comment]
Yes for sure, we were using the node API to crawl the file system for actual usage for each user and that takes a long time. This is a point of improvement if you are willing to help with
