### ISSUE TITLE
[BUG] mobile: action buttons do not work in shared album

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#4670]
### The bug

Action buttons Download and Delete do not work in shared album. Download just exits the viewer and Delete does nothing.
Expected behavior is that Download should download the asset and Delete button shouldn't be visible on foreign asset.

![Screenshot_20231027_200137](https://github.com/immich-app/immich/assets/15554561/112220ae-4749-4a6a-9f11-e8014cdeee6c)

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

1.82.1

### Version of Immich Mobile App

1.81.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
not relevant
```

**Comment by shenlong-tanwen** [comment]
The icon is not for downloading but for archiving the asset, which yes, shouldn't be visible to the shared users. Downloading however is working. The download icon should be available in the top bar of the viewer

**Comment by waclaw66** [comment]
@shenlong-tanwen Your are right, download button is on the top and it is working. So the issue is just about visibility is those below buttons.
