### ISSUE TITLE
[BUG] oauthAutoLaunch can sometimes result in an AggregateError if oauth provider is not reacheable

### ISSUE THREAD

**Issue by samip5** [immich-app/immich#4675]
### The bug

It seems that when the oAuth provider is either unreacheable or it's DNS doesn't solve, it throws multiple errors to the stack, which do get somewhat handled by exceptionsHandler but as it's an AggregateError, it doesn't show anything really useful in logs.

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

v1.82.1

### Version of Immich Mobile App

v1.82.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not really relevant
```

### Reproduction steps

```bash
1. Setup oauth with autoredirect
2. Somehow mess with DNS so it's not available anymore or turn your oauth provider off
3. See the issue
```

**Comment by jrasm91** [comment]
I have no idea what an "aggregate error" is. Can you attach screenshots or logs with more details, and/or the actual http server response?

**Comment by samip5** [comment]
> I have no idea what an "aggregate error" is. Can you attach screenshots or logs with more details, and/or the actual http server response?

Wish I knew as the whole error I get in server logs is: `[Nest] 8  - 10/28/2023, 3:18:39 PM   ERROR [ExceptionsHandler] AggregateError`

**Comment by samip5** [comment]
Okey, my PR doesn't really fix it but it changed it to:
```
{"message":"Error in OAuth discovery: AggregateError","statusCode":500}
```

So it does come from the OAuth Discovery portion.
