### ISSUE TITLE
Support for video metadata

### ISSUE THREAD

**Issue by 20pins** [immich-app/immich#469]
### Feature detail

Similar to EXIF data shown for photos, show supporting metadata for videos. In the case of iOS, several pieces of information are captured under HEVC section. This includes location, video resolution and duration, file size, and phone model. Adding this would provide a more consistent experience for end users who are used to seeing this data for photos already.
![861A99F0-4002-412E-B847-5978CDEA1493](https://user-images.githubusercontent.com/110514032/184735417-2d0750d7-665a-4b52-9e28-ad53af53840f.jpeg)

### Platform

Mobile App

**Comment by alextran1502** [comment]
Implemented in #505
