### ISSUE TITLE
App sync task quantity error

### ISSUE THREAD

**Issue by AlliotTech** [immich-app/immich#4719]
### The bug

In the synchronization task of the app, the remaining quantity has mistakenly become a negative number.

### The OS that Immich Server is running on

ubuntu

### Version of Immich Server

latest

### Version of Immich Mobile App

latesr1.83.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
1. sync in android app
2. put app into background
3.  re open app
...
```

**Comment by alextran1502** [comment]
Known cosmetic issue #3676
