### ISSUE TITLE
[Feature]: Support for redis sentinel

### ISSUE THREAD

**Issue by onedr0p** [immich-app/immich#473]
### Feature detail

Hi 👋🏼 

It would be great if immich could connect to a highly available redis instance.

Here's a couple examples of applications that support this method of redis.

- https://www.authelia.com/configuration/session/redis/
- https://github.com/outline/outline/blob/93bb9d067d0f61a2f5d6f1d302774b128095a4d0/.env.sample#L22L29

Thanks!

### Platform

Server

**Comment by alextran1502** [comment]
Hello,

Thank you for opening the issue. This will be left to the user to implement because it is very specific to a user group

**Comment by onedr0p** [comment]
@alextran1502

To be able to implement sentinel support, there would have to be a switch from node-redis to ioredis, since node-redis doesn't have sentinel support https://github.com/redis/node-redis/issues/302 :/

Would you accept PRs on this change?

**Comment by alextran1502** [comment]
You can try but I think there might be dependencies that depends on node-redis, like the socket-io implementation

**Comment by onedr0p** [comment]
Actually it looks like Bull passes the `RedisOpts` directly to ioredis, not sure why the `redis` lib is in the `packages.json`

https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queue

Since with Redis Sentinel would require multiple hosts passthru to the application, do you think the way Outline made it [configurable](https://github.com/outline/outline/blob/93bb9d067d0f61a2f5d6f1d302774b128095a4d0/.env.sample#L22L29) is a decent decision for implentation?

https://github.com/luin/ioredis#sentinel

**Comment by alextran1502** [comment]
Here is the reason we have Redis in the dependency https://docs.nestjs.com/websockets/adapter

**Comment by samip5** [comment]
@alextran1502 Could you re-open this so it would get closed when the support is implemented from the PR?
