### ISSUE TITLE
[BUG] Truenas Scale Adding External Library can not specify the entry point name

### ISSUE THREAD

**Issue by cristianku** [immich-app/immich#4740]
### The bug

Using Truenas Scale Cobia.

I can not enter the external library mount name, so I dont know how to access the external library from Inside of IMMICH.

App Version: 1.83.0
Chart Version: 1.0.32

![Screenshot 2023-10-31 at 08 30 26](https://github.com/immich-app/immich/assets/25354817/13f05f90-56c4-4aff-b5fd-1c8289131a78)

### The OS that Immich Server is running on

Truenas Scale

### Version of Immich Server

1.83.0

### Version of Immich Mobile App

1.83.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I dont know, its managed by truenas scale
```

### Your .env content

```Shell
I dont know, its managed by truenas scale
```

### Reproduction steps

```bash
1. Create a new app inside Truenas scale
2. Try to specify the External Library 
3. No mount name field is displayed
```

**Comment by bo0tzz** [comment]
This is a truenas issue, please take it up with them.
