### ISSUE TITLE
[BUG] mobile: Favorites are sorted reverse

### ISSUE THREAD

**Issue by nicokaiser** [immich-app/immich#4789]
### The bug

In the mobile app (iOS), Favorites are ordered by date, but ascending rathern than the default descending. On the web Favorites are sorted by date descending (like everything else). Maybe this should be consistent.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.84.0

### Version of Immich Mobile App

v1.84.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
(not applicable here)
```

### Your .env content

```Shell
(not applicable here)
```

### Reproduction steps

```bash
1. Open the App
2. Navigate to Favorites
3. Photos are sorted by date, ascending rather than descending
```

**Comment by natedawg** [comment]
I can confirm I'm seeing the same issue on android.

**Comment by alextran1502** [comment]
Fixed
