### ISSUE TITLE
[BUG] Mobile app crashes sporadically when swiping. 

### ISSUE THREAD

**Issue by alextran1502** [immich-app/immich#480]
**Describe the bug**
The mobile app would crash after sipping continuously for an extended period. Perhaps there is a memory leaked

**Comment by waclaw66** [comment]
I think I'm facing this issue using 1.102.2. App starts with 70% system memory usage with my testing. Swiping photos causes that system used memory raises up to 85%, then system starts to killing other apps and finally Immich app is killed too.

**Comment by waclaw66** [comment]
Seems viewing remote only images causes this isuue too, however consumed memory raises very slowly because of small size of thumbnails.

**Comment by martyfuhry** [comment]
Yes this seems like it's the in memory cache, you are correct. The large images, especially the large local images, are putting too much pressure on the system. Thank you for looking at the memory use over time! We keep a separate image cache for the large images. So tweaking that cache should be straightforward. 

I don't believe that the on disk cache also stores anything in memory, but I will double check there, just in case.
