### ISSUE TITLE
[BUG] [iOS] Toggling auto-backup option breaks album selection

### ISSUE THREAD

**Issue by 20pins** [immich-app/immich#481]
**Describe the bug**
When toggling auto-backup option off and back on, users album selections disappear and the "Start Backup" button becomes un-selectable, presumably because no albums are selected. When trying to reselect the albums, the app shows no local albums to choose from. Relaunching the app fixes this.

**Expected behavior**
* Subjective: Re-enabling backup should use previous album configuration established by the user (selected/excluded.)
* After reenabling auto-back, and choosing Select button to configure album inclusion, user should not have to relaunch app for available albums to populate.
* When "Start Backup" button is not selectable, a note should accompany the button directing the user to take action elsewhere. For example "Select albums to enable"

**Screenshots**
![IMG_0749](https://user-images.githubusercontent.com/110514032/185036254-9d117a1b-b26d-4535-8ac0-87092b930d05.jpg)

**System**
- Phone OS [iOS]: `<15.6>`
- Server Version: `<1.23.0>`
- Mobile App Version: `<1.23.0 build.45>`

**Additional context**
Compose and .env are the same as in #462

**Comment by alextran1502** [comment]
Can you help me check if this issue is fixed? On my phone, it doesn't behave this way, I guess it might be related to an optimized storage setting.

**Comment by 20pins** [comment]
I've tried multiple times now and have not been able to reproduce. Will defer to you whether to close this or not, but I lean towards closing and we could re-open if it happens again.

**Comment by alextran1502** [comment]
Closing - Please reopen if it happens again

**Comment by esmondmissen** [comment]
@20pins how did you resolve this? Mine has been like this for months now. Only seems to affect my device.
