### ISSUE TITLE
[BUG] Allow public User to upload is always "off" (but works)

### ISSUE THREAD

**Issue by Arthur-DTAG** [immich-app/immich#4823]
### The bug

Today, I discovered a visual bug (not sure if it's related to the latest version).

I created a shared album with my wife and also creted a link and enabled the "allow public users to upload" option. Copied the link and saved.

I shared the link and was not sure if i enabled the upload and check it in the shared album -> it was toggled off! 
Toggled it on closed the popup, rechecked and again... toggled off.

If i open the link in an incognito window, i am able to upload - so it seems to work - just a visual thing!

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v0.84.0

### Version of Immich Mobile App

v0.84.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not neccessary
```

### Your .env content

```Shell
not neccessary
```

### Reproduction steps

```bash
1. create shared album with an internal user
2. create a shared link and allow public users to upload
3. copy link and close popup
4. check link permissions -> "allow public users upload" is toggled off
5. paste link in incognito window -> Upload is possible as external user
```

**Comment by alextran1502** [comment]
Fixed
