### ISSUE TITLE
[BUG] Uploaded photos not visible on web timeline/albums

### ISSUE THREAD

**Issue by ValdasK** [immich-app/immich#4849]
### The bug

I have uploaded several photos (using web upload), they are only visible in "recently added". If I look for them on timeline, or add them to albums, they are not visible (but are included into album picture count).

Mobile application displays them, but web does not. Reloading without cache does not help.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

1.84

### Version of Immich Mobile App

1.84

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Default
```

### Your .env content

```Shell
Default
```

### Reproduction steps

```bash
1. Upload photo
2. It's not visible on web
```

**Comment by alextran1502** [comment]
Do you know if they come with bad metadata? If you can see them in the mobile app, look at the date

**Comment by ValdasK** [comment]
Everything seems to be correct, in "recently added" they have all the details as expected.

![image](https://github.com/immich-app/immich/assets/4756408/d5e05130-8a72-4605-80f3-95aafb349593)

**Comment by ValdasK** [comment]
Wait a second, some older photos appeared. I believe issue is that if photo time is in future, they are not displayed correctly.

Currently it's 18:21 local time, but camera says that photos were taken on 19:01. Photos taken hour ago (set with 18:09) previously not visible started to appear. This is probably due to summer time not being adjusted in camera + immich not displaying photos which are "in future" time.

**Comment by alextran1502** [comment]
@ValdasK, this is the correct observation. We had an issue with the way we query the timeline on the web app so that if there are photos with bad metadata and have its time in the future, the web won't be able to render the page, so as a quick fix, we choose not to render this at the time. The future plan is to have a page to display these types of problematic photos to let the user intervene

**Comment by ValdasK** [comment]
Hmm, maybe not rendering in timeline would suffice, but hiding such photos in albums seems to be not necessary?

**Comment by alextran1502** [comment]
Album on the web uses the same time bucket render mechanism as the timeline to ensure that big album can be viewed as smoothly as the timeline

**Comment by ValdasK** [comment]
Alright, seems like it's not something that can be solved right now, and issue auto-fixes once time is past photo time, closing.
