### ISSUE TITLE
[BUG] It is not possible to select items in the category

### ISSUE THREAD

**Issue by aviv926** [immich-app/immich#4911]
### The bug

In the immich application, the latest version (v1.85.0), it is not possible to select any photo/video if you enter them under the categories

### The OS that Immich Server is running on

WIN 10 with Docker

### Version of Immich Server

1.85.0

### Version of Immich Mobile App

1.85.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Default
```

### Your .env content

```Shell
Default
```

### Reproduction steps

```bash
1.enter the search - categories - video
2.try to select a video by long pressing / marking with the V by day 
3.the video will not be selected like this also with regard to the other things under categories
```

**Comment by jrasm91** [comment]
Is this still an issue?
