### ISSUE TITLE
No Label for Share Link expiration in iOS

### ISSUE THREAD

**Issue by moritzbindewald** [immich-app/immich#4912]
![IMG_7415](https://github.com/immich-app/immich/assets/106192865/21ee32f5-0cff-4e34-9592-81bce98048ca)
### The bug

When creating a share-link, it is possible to set an expiration-date for the link. In the iOS-App, this option exists, but u can just choose the time in the dropdown. A label for the dropdown is missing. Screenshot is attached. Maybe easy to fix? 

### The OS that Immich Server is running on

unRaid

### Version of Immich Server

v1.85.0

### Version of Immich Mobile App

v1.85.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. click on share
```

**Comment by shenlong-tanwen** [comment]
Thank you for the notice. Should be fixed in the next release.

**Comment by moritzbindewald** [comment]
> Thank you for the notice. Should be fixed in the next release.

Thx for ur awesome work!!! Is there an option to donate?
