### ISSUE TITLE
[BUG] (solution found) Storage Template: Special characters escaped in album names by HandleBars 

### ISSUE THREAD

**Issue by Hely0n** [immich-app/immich#4917]
### The bug

I found out, that using Symbols like `' &` and some others, the folder name ends up with `&amp;` instead of "&" etc.

After debugging the code, I found out that the replacement happens inside the template() call in Line 276 of storage-template.service.ts. Here HandleBarsDelegate is called and it seems like it's expected behaviour of Handbars, to escape those characters.

As stated in [https://github.com/Handlebars-Net/Handlebars.Net/discussions/463](url), it can be prevented by using triple-stash (`{{{album}}}`). I tried to just insert it like this into the settings in the Web UI and it works.

So the current workaround is to use {{{album}}} instead of {{album}} in your storage template. 

But what do you think? Should this replacement happen internally by string.replace(), or should it just be stated in the manual to use tripple-stash for albumnames?

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.85.0

### Version of Immich Mobile App

doesn't matter

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
doesn't matter
```

### Your .env content

```Shell
doesn't matter
```

### Reproduction steps

```bash
1. create Album with "&" in it
2. insert {{album}} into storage template
3. run storage template migration 
4. look at resulting folder name
5. retry with {{{album}}} to check the workaround
```

**Comment by jrasm91** [comment]
I think this work around is good enough for now

**Comment by jaimetur** [comment]
This workaround does not work when Album name has a dot "." in the name. Most of my Albums name follow the same template: "yyyy.mm - Album Name" i.e: "2003.07 - Summer Vacations".

When I import my Albums with those names it remove dots in Albums names if use the following storage template:

{{#if album}}Albums/{{{album}}}{{else}}No-Albums/{{y}}/{{MM}}{{/if}}/IMG_{{y}}{{MM}}{{dd}}_{{HH}}{{mm}}{{ss}}

I would like this to be fixed or have a workaround to it since I don't want to change my Albums template names since 1992.

**Comment by Hely0n** [comment]
The replacement of the dots is there for safety reasons, but maybe it's not necessary. @jrasm91 what do you think? Could dots introduce problems with how the files are handled currently?

**Comment by jaimetur** [comment]
I don't see any reason for that replacement since all the file systems support that char in folders name and since the Albums are already saved in Immich database with the dots in the Album name. 

Even when I download the albums using API REST it save it correctly with the dots in the downloaded folder. 

Please remove that replacement to the Handlebars template exports.

**Comment by jaimetur** [comment]
Any news on this?

**Comment by jaimetur** [comment]
Is there any news on this? I need this to be addressed before to migrate all my albums to Immich since all my albums since 1995 has dots in their names and I would like to keep them on Immich as well.

**Comment by jaimetur** [comment]
@Hely0n Hi Markus, please take a look into this. It would be very very helpful for me to have my Albums folder properly named into my hard drive. If you remove original dots from the album name then all my Albus are completely unsorted on my hard disk and it is completely a mess. I think we can just remove that limitation with no issue. In all other photo apps that I have tried this is possible. 


Thank you so much for your patient and comprehension.

**Comment by Hely0n** [comment]
Okay, I‘ll look into this today

**Comment by Hely0n** [comment]
@jaimetur done. Hope it will be approved soon 😊.

Sorry that I didn't react earlier. I didn't have much time in the last months and while fixing it is a quick task, setting up the dev environment of immich always gives me some sort of headaches, as I'm an IntelliJ user on Windows 😅. Finally getting a macbook in two months.

**Comment by jaimetur** [comment]
Thank you @Hely0n

**Comment by jaimetur** [comment]
Hi @Hely0n do you have any update on this?

It has not been implemented yet

**Comment by Hely0n** [comment]
Hey, 
well I'm sorry, but I'm not a core developer of this project and I created this PR and it was closed:
https://github.com/immich-app/immich/pull/17893

I commented accordingly but there was no reaction, so I thought they are taking care of it in another commit... Looks like they didn't.

Looking at your GitHub Account, you seem like a very capable programer. Maybe you could try to just create PR yourself, as I already tried it and don't want to annoy them from my side.  😅 Hope you understand.
