### ISSUE TITLE
[BUG] web: trashing asset doen't shift to next asset and browsing does't work anymore

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#4954]
### The bug

When an asset is trashed while browsing and viewing using arrow keys it doen't shift to next asset reliably and browsing by arrow keys stops working. It does in more than ~90% of cases. Next asset is shown and arrow keys are working very rarely.

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

v.1.85.0

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```
1. view an asset
2. trash it using Trash button
3. "Moved to trash" toast appears and trashed asset is still shown
5. arrow keys or left/right buttons doesn't work anymore
6. there is needed to go back and view next asset again to restore browsing
```

**Comment by lyz-code** [comment]
Hi, I'm seeing this issue again on 1.98.2 when archiving images with the `Shift + a` shortcut. @jrasm91 shall I create a new issue? or can we reopen this one
