### ISSUE TITLE
[BUG] iOS app shows a negative remainder

### ISSUE THREAD

**Issue by mirosval** [immich-app/immich#4958]
### The bug

I think this is happening because there is an overlap between my selected albums, I selected Videos and Favorites and there are videos that have also been marked as Favorite. Immich uploads them and then counts them 2x (?) compared to the Total count? This is just my theory.

![Screenshot 2023-11-11 at 23 20 02](https://github.com/immich-app/immich/assets/1315417/7fb77dd8-987c-491f-8523-5484ab251784)

### The OS that Immich Server is running on

NixOS

### Version of Immich Server

v1.84

### Version of Immich Mobile App

v1.85

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
https://github.com/mirosval/dotfiles/blob/master/hosts/butters/services/immich/default.nix
```

### Your .env content

```Shell
https://github.com/mirosval/dotfiles/blob/master/hosts/butters/services/immich/default.nix
```

### Reproduction steps

```bash
1. Select 2 albums to sync (likely such that they contain overlapping items)
2. Eventually the Remainder is negative
```

**Comment by danieldietzler** [comment]
This is a known bug: #3676. 
It would be helpful if you could do a quick search first to check if other's already had the same issues and posted it :)
