### ISSUE TITLE
[Feature]: Public instance/ folders

### ISSUE THREAD

**Issue by jdaviescoates** [immich-app/immich#497]
### Feature detail

I'm looking into using Immich to replace my use of Flickr.

So essentially I want the whole instance and all photos to be publicly accessible without a login.

Alternatively, I guess the same thing could be achieved using publicly accessible folders too.

Some overlap with #265

### Platform

Web

**Comment by zackpollard** [comment]
Hey,

We are not looking at specifically supporting this feature in Immich, however I believe with the completion of a couple of other issues you would be able to get something close to what you want. Issue #265 will allow the sharing of albums externally and we are planning to also implement "smart albums" which will be automatically updated albums based on search criteria.

I'm going to close this issue, but hopefully once we have these features implemented it can do something similar to what you are wanting 😄
