### ISSUE TITLE
[BUG] web: scrollbar is stretching and shinking while scrolling

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#5030]
### The bug

That's caused because heights of buckets are changing while scrolling. Haven't found the root cause so far.

|by default|colored buckets|
|-|-|
|<video src="https://github.com/immich-app/immich/assets/15554561/a729437f-51ce-4f07-8fd4-ea9f2296ac37">|<video src="https://github.com/immich-app/immich/assets/15554561/02b06ca3-c390-43f1-9519-da58c820e06a">|

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

v1.86.0

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
just scroll over timeline with many time buckets
```

**Comment by alextran1502** [comment]
This is how it works: the initial size is estimated and updated when the bucket is loaded. I'd say working as intended

**Comment by waclaw66** [comment]
Sure, one can live with that, but there is space for improvement ;)

**Comment by alextran1502** [comment]
Yeah initially I was planning to implement a local storage to remember those adjusted height, but something got in the way 😅
