### ISSUE TITLE
[BUG] server: Error: ENOENT: no such file or directory, open './assets/style-dark.json'

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#5031]
### The bug

Server assets cannot be found because they are located at `/opt/immich/server/assets` path.
Server is searching for them using relative path
https://github.com/immich-app/immich/blob/dc4e6c4629b0a334021f36ed4f150324e7546908/server/src/domain/system-config/system-config.service.ts#L88
within default working directory `/var/lib/immich`.

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

v1.86.0

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
not relevant
```

**Comment by bo0tzz** [comment]
Are you using the official docker container or some other installation method?

**Comment by waclaw66** [comment]
Not using docker, just standard systemd services.

**Comment by waclaw66** [comment]
I see, I missed this change, my bad...
https://github.com/immich-app/immich/blob/dc4e6c4629b0a334021f36ed4f150324e7546908/server/Dockerfile#L21
