### ISSUE TITLE
[ENHANCEMENT] Limit number of total upload item on the web to avoid crashing the browser.

### ISSUE THREAD

**Issue by piraterx** [immich-app/immich#507]
So I tried uploading multiple images from web app on desktop. Every time I upload multiple picture at same time, browser tab keep crashing.
I am using linux as desktop specifically Pop OS and firefox as browser. Currently my PC has 32GB ram and i was watching it when I was uploading and it crashes when it max out. Is there a way to make browser upload smart when it knows what need to be uploaded but wait and upload two or three images at a time. 

I tried same test with different service provider and it didn't crash. 

I restarted service as well. 

Number of photos I was uploading was 147. They are roughly 4 to 10 MB each.

**Comment by alextran1502** [comment]
For bulk upload, I suggest using the CLI instead. Browser should be used for upload about 50 images or less. I will put a limit on total file to be upload at one time on the browser

**Comment by srlamin19** [comment]
Yesterday, I've tried 2.800 images, but also crash, but when I tested with 1000 Images, it works! it depends on which browser, system and total size..

**Comment by piraterx** [comment]
> For bulk upload, I suggest using the CLI instead. Browser should be used for upload about 50 images or less. I will put a limit on total file to be upload at one time on the browser

Thank you so much.
