### ISSUE TITLE
[BUG] web: thumbnails load fails when Album page is reloaded

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#5077]
### The bug

~~Loading of album list is slower when there is high number of albums. Those are shown as squares with their ids for a while.
It would be nice to load album list with thumbhashes and show them instantly, because album covers are loaded in separate requests afterwards.
The same applies when albums are scrolled down and new thumbnails are loaded, it takes few seconds and empty squares with ids are shown.~~

The real cause is that WEBP thumbnails load fails when Albums page is reloaded by F5.
I'm not sure why the `key` parameter is passed while F5 reload, there is no `key` when page navigation to Albums is used.
Because of that, it takes a while to fetch JPEG thumbnails and album icons are for few seconds without image.

![obrazek](https://github.com/immich-app/immich/assets/15554561/a11e55b5-6bcd-4640-ae2f-e450a18b7943)

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

1.86.0

### Version of Immich Mobile App

not releavant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. hit F5 on Albums page
```

**Comment by jrasm91** [comment]
Hmm, I can't reproduce it. The only time the key is set is on the initial page load. This should only happen if you are on the share/[key] route. Do you have any reproduce steps? Did you navigate to the albums page from somewhere else?

```ts
  if ($page.route.id?.startsWith('/(user)/share/[key]')) {
    api.setKey($page.params.key);
  }
  ```

**Comment by waclaw66** [comment]
I can reproduce it on any account, just hit F5 on Albums page.

**Comment by jrasm91** [comment]
Can you reproduce it on the demo site? In an incognito window (without any additional extensions)

**Comment by waclaw66** [comment]
Will do on Sunday, currently away from home.

**Comment by waclaw66** [comment]
I've noticed that 1.87.0 has been releases, thus I checked it and everything seems to be working fine, `key` parameter is not used anymore. Nothing else has been changed on my side.

**Comment by jrasm91** [comment]
Interesting. Maybe a regression in the prior release. Everything is working as expected now then?

**Comment by waclaw66** [comment]
> Interesting. Maybe a regression in the prior release. Everything is working as expected now then?

Everything works fine so far. Closing for now.
