### ISSUE TITLE
[BUG] Unable to log into server 1.85.0 from apps running 1.86.0

### ISSUE THREAD

**Issue by astjohn** [immich-app/immich#5085]
### The bug

Phones automatically updated to 1.86.0. Server is still running 1.85.0.
Now the mobile apps can't log into the server. 

I have not updated the server yet to see if the version mismatch is the culprit, but from an architecture and user support point of view, it's simply bad form to push mobile app updates out that will create incompatibility with the server versions.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.85.0

### Version of Immich Mobile App

v1.86.0

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not necessary
```

### Your .env content

```Shell
Not necessary
```

### Reproduction steps

```bash
1. Keep server version.
2. Update mobile apps to 1.86.0
3. Attempt to login via mobile app.
```

### Additional information

If the culprit is that both the mobile app and the server need to be at 1.86.0... then please follow semantic versioning in the future so we can all stay sane. Breaking changes need a major version bump so this would technically have to qualify as a 2.x release. As a side note, the platform is awesome and I will contribute however I can in the future. Thank you!

**Comment by bo0tzz** [comment]
As noted in the release notes for 1.86.0, this is expected breakage. As noted everywhere else, Immich is currently in beta and under heavy development, so there will be breaking changes like this occasionally.

**Comment by astjohn** [comment]
Understood. It's still a better practice to use semantic versioning to avoid surprises - even in a beta.
