### ISSUE TITLE
[BUG] Opening the Repair page sometimes causes timeout "Internal Error (undefined)"

### ISSUE THREAD

**Issue by v3DJG6GL** [immich-app/immich#5090]
### The bug

As mentioned in the title, opening the repair page results in `Internal Error (undefined)`
![image](https://github.com/immich-app/immich/assets/72495210/6bed6567-e140-463a-a423-bfb6d2592d94)

Here the corresponding log:
`2023-11-17 00:46:44.952985+01:002023/11/17 00:46:44 [error] 64#64: *2922 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.16.1.26, server: , request: "GET /admin/repair/__data.json?x-sveltekit-invalidated=01 HTTP/1.1", upstream: "http://172.17.197.131:10000/admin/repair/__data.json?x-sveltekit-invalidated=01", host: "immich.DOMAIN.TLD", referrer: "https://immich.DOMAIN.TLD/admin/user-management"`

It usually only occurs the first time, e.g. after a restart or update of immich. immich loads the `Repair` page for approx. 30-60s before the error occurs.
On a second attempt, the timeout no longer seems to occur.
Also, there are many untracked files listed on my `Repair` page, which could be the reason for the timeout.
`UNTRACKS FILES (211)`

### The OS that Immich Server is running on

TrueNAS SCALE 23.10.0.1

### Version of Immich Server

v1.86.0

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. You must have enough files that will be listed on the Repair page (e.g. Untracked Files)
2. Open the Repair page the first time after restarting/updating immich.
3. After loading for approx. 30-60 sec, immich will display the mentioned error.
```

**Comment by rollermy** [comment]
I'm experiencing this too. ~15000 files.

**Comment by aviv926** [comment]
I'm experiencing this too

**Comment by bengelnatz** [comment]
this is a problem since the day the repair page got introduced and is tracked [here](https://github.com/immich-app/immich/issues/5090)

**Comment by v3DJG6GL** [comment]
Oh, you're right! I totally overlooked that. Thanks for the link!
