### ISSUE TITLE
[BUG] iOS app: Picture selection in partner timeline

### ISSUE THREAD

**Issue by Shobba** [immich-app/immich#5162]
### The bug

In the partner timeline on iOS I cannot select multiple photos (eg. for downloading a bunch of photos to my iOS library). It shows the checkmark on the right for every day, and I can long press on photos. But both just trigger a short vibration but nothing happens, no entry will get selected.
It's working fine in a shared album.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.87.0

### Version of Immich Mobile App

v1.87.0 build.127

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
-
```

**Comment by alextran1502** [comment]
Implemented
