### ISSUE TITLE
[BUG] Android 1password Autofill doesn't work

### ISSUE THREAD

**Issue by eygraber** [immich-app/immich#5177]
### The bug

If I try to login to the app using autofill from 1password, the email and password fields aren't filled.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.87.0

### Version of Immich Mobile App

v1.87.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Enter server location
2. Open 1password from keyboard
3. Select immich login
4. Control returns to immich but the email and password fields aren't filled in
```

### Additional information

Android 14
1password: 8.10.22-1.BETA
Keyboard: GBoard

If I select the specific login from the keyboard then it does work. Not sure if this is a 1password bug, or an edge case that Immich needs to handle.

https://github.com/immich-app/immich/assets/1100381/23207ce7-ef92-4eaa-93ab-2f38c5379171

**Comment by etnoy** [comment]
Can confirm this behavior

**Comment by sannidhyaroy** [comment]
Can confirm, I've faced this issue since I started using Immich.

**Comment by deiop** [comment]
Can confirm for Bitwarden as well

**Comment by sannidhyaroy** [comment]
> Can confirm for Bitwarden as well

Bitwarden works for me...

**Comment by muava12** [comment]
bitwarden also not work with me, i'm using Pixel 3

**Comment by nickspacemonkey** [comment]
Same not working on iOS with Bitwarden.

**Comment by bo0tzz** [comment]
dupe: #3618
