### ISSUE TITLE
[BUG] <Immich client 1.87.0 iOS cannot connet to server 1.85.0 on truenas on local network>

### ISSUE THREAD

**Issue by Jagdpanzer42** [immich-app/immich#5181]
### The bug

recently updated immich app on app store to 1.87.0, connect on local network have wrong password / url / email error, another iphone using 1.86.0 does not have the issue

### The OS that Immich Server is running on

Truenas

### Version of Immich Server

1.85.0

### Version of Immich Mobile App

1.87.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not have
```

### Your .env content

```Shell
not have
```

### Reproduction steps

```bash
1.updated app to 1.87.0
2.update immich server on truenas to 1.85.0
3.cannot connect
```

**Comment by bo0tzz** [comment]
Release 1.86.0 was a breaking change as stated in the release notes: https://github.com/immich-app/immich/releases/tag/v1.86.0
