### ISSUE TITLE
[BUG] App shows Favorites from Old to New while Web does it the other way

### ISSUE THREAD

**Issue by Juan-Esc** [immich-app/immich#5184]
### The bug

The app should also show the favorite images ordered from New to Old, as Immich's web does and as Google Photo does. However, the app is currently showing the older pictures first on the Favorites page.

### The OS that Immich Server is running on

-

### Version of Immich Server

v1.87.0

### Version of Immich Mobile App

v1.87.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Go to the Favorites section in the app
```

**Comment by alextran1502** [comment]
Fixed

**Comment by Juan-Esc** [comment]
> Fixed

Awesome! Thank you!
