### ISSUE TITLE
[BUG] 504 when viewing large (shared) albums

### ISSUE THREAD

**Issue by traktuner** [immich-app/immich#5226]
### The bug

Hello,
I have a shared family album with 6k assets in it.
Since 1.88(.1) I can't open this album any more in web. On mobile it's ok.
After some time, the server responds with a 504 gateway timeout.
`Request failed with status code 504 (504 - )`
Restarting the stack brought no success.
Also, there are no log entries in the corresponding containers.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

1.88.1

### Version of Immich Mobile App

1.88.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
imagegenius AIO
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
see issue above
```

**Comment by alextran1502** [comment]
@martabal Do you have any thoughts on this one?

**Comment by martabal** [comment]
Yes, I'm fixing it right now

**Comment by martabal** [comment]
Oh you closed #5224 😲

**Comment by alextran1502** [comment]
@martabal yeah damnit Alex, can you reopen a new PR and rebase main?

**Comment by traktuner** [comment]
Thanks!
To clarify: this affects not the album overview page (click on albums) but albums with many assets in it.
DB goes nuts when clicking on the album, then the server times out.
