### ISSUE TITLE
[Feature]: Support for external authentication methods

### ISSUE THREAD

**Issue by ln-12** [immich-app/immich#523]
### Feature detail

Hey, first of all: thanks for this awesome project!

I was wondering, if there are any plans to support external authentication with for example [LDAP](https://de.wikipedia.org/wiki/Lightweight_Directory_Access_Protocol).

### Platform

Server

**Comment by bo0tzz** [comment]
There are plans and an open PR (#207) to implement oauth support. I believe it should then be possible to use that with an idp which also supports LDAP, such as Authelia.

**Comment by alextran1502** [comment]
Close as duplicated with #33
