### ISSUE TITLE
The backup album page on the mobile end has been loading continuously

### ISSUE THREAD

**Issue by wangl1987** [immich-app/immich#5263]
### The bug

When I have over 10000 photos on my phone, including 2300+videos
The backup album page on the mobile end has been loading continuously
Staying on this page for 30 minutes is still like this

### The OS that Immich Server is running on

Installing through Docker Compose on Mac OS

### Version of Immich Server

1.88.2

### Version of Immich Mobile App

1.88.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
no changes
```

### Your .env content

```Shell
no changes
```

### Reproduction steps

```bash
1.phone systems：ios17.1.1
2.photos:7000+;videos:2300+
3.The backup album page on the mobile end has been loading continuously
Staying on this page for 30 minutes is still like this
```

**Comment by wangl1987** [comment]
like this
![微信图片_20231122204956](https://github.com/immich-app/immich/assets/150538734/d31a9ebf-037c-4261-a719-2e2c48d759fb)

**Comment by alextran1502** [comment]
Hello, what permission did you allow Immich to have when accessing the page?

**Comment by wangl1987** [comment]
> Hello, what permission did you allow Immich to have when accessing the page?

Thank you for your reply
This issue occurs when I set immich to have access permissions for all albums.
It is normal for me to have a small amount of photo access permissions when setting immich.
and this function is also normal on another iPhone with fewer photos
