### ISSUE TITLE
[BUG] PikaPods instance showing incorrect storage info

### ISSUE THREAD

**Issue by stryguardian** [immich-app/immich#5264]
### The bug

I spun up an instance of Immich on Pikapods and the storage bar was showing 9.6TiB of 14.6 TiB used. I hadn't yet uploaded anything. Since uploading images and videos, this information has not changed or updated. Not sure if this is an issue with Pikapods or Immich.

### The OS that Immich Server is running on

Unsure (Pikapods instance)

### Version of Immich Server

v1.87.0

### Version of Immich Mobile App

v1.88.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Unavailable
```

### Your .env content

```Shell
Unavailable
```

### Reproduction steps

```bash
Just spin up an instance on Pikapods it would seem.
```

**Comment by bo0tzz** [comment]
The storage display on the side bar shows the total disk usage of the system. You can see more detail about what Immich is actually using in the admin panel.
