### ISSUE TITLE
[BUG] Android client renders colors of iPhone live images incorrectly

### ISSUE THREAD

**Issue by Esokrates** [immich-app/immich#5279]
### The bug

Live photos taken with an iPhone do not render correctly in the android client (wrong colors, see the video that is linked below).
This issue is only present in the mobile client, in the web browser, the colors are rendered correctly. Additionally only live photos are affected, videos of the same iPhone render correctly in the mobile client.

All files were added via an external library, not uploaded / imported.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

 v1.87.0

### Version of Immich Mobile App

 v1.87.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Everything default as in the official instructions, with exception of whitelisting paths for external libraries, don't have access to my server right now.
```

### Your .env content

```Shell
Everything default as in the official instructions, with exception of whitelisting paths for external libraries, don't have access to my server right now.
```

### Reproduction steps

```bash
1. Add an external library containing an iPhone live photo
2. Use the android client to play back the live photo
3. Observe that the colors are wrong during playback
```

### Additional information

Find a demonstration of the issue as well as sample files here: https://drive.proton.me/urls/3REC1AEZ40#FYY6whQaYdhb

**Comment by jrasm91** [comment]
We will track this here: #5120
