### ISSUE TITLE
[BUG] Ability to clear/reset existing sign-ins

### ISSUE THREAD

**Issue by weitheng** [immich-app/immich#5286]
### The bug

It appears that once logged into a user account, the device/browser will continue to stay signed in unless it is manually logged out. This could potentially be a security vulnerability as there are currently no way to see which device is currently logged in to the user account nor have the ability to remove the device/browser from staying logged in. Additionally, having the ability to set how long till a device/browser needs to re-authenticate would make the security more robust.

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.88.1

### Version of Immich Mobile App

v1.88.1

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1.Log in to a user account
2. Close the webpage
3. Continue to be logged in even after a few days
```

**Comment by bo0tzz** [comment]
You should be able to manage active sessions from your user settings.

**Comment by weitheng** [comment]
Looks like I was blind, you are right
