### ISSUE TITLE
[BUG] Log filling with errors - ECONNRESET and Not Ready or Lagging

### ISSUE THREAD

**Issue by Tyree** [immich-app/immich#5294]
### The bug

For the past week, Immich has been using 15-20% CPU near constantly.
Logs are filling with various errors, but mostly 503 Not Ready or Lagging related to TypeSense.
```
Request #1700840083214: Request to Node 0 failed due to "undefined Request failed with HTTP code 503 | Server said: Not Ready or Lagging"
Request #1700840083214: Sleeping for 4s and then retrying request...
```
With intermittent errors like:
`Request #1700840083214: Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8108"`
`Request #1700568114431: Request to Node 0 failed due to "ECONNRESET socket hang up"`
`Request #1700568324697: Request to Node 0 failed due to "ERR_REQUEST_ABORTED error request aborted"`
`[Nest] 1063  - 11/24/2023, 10:35:47 AM   ERROR [TypesenseRepository] Unable to index documents`

I have stopped the container, deleted the typesense folder, and restarted the container. This stops it for a while, but it comes right back.

My server is running an i7-12700K with 64GB RAM

I am using the unRAID template.
I know this isn't officially supported, but I feel like this is a root Immich issue and not an issue with the template.
@martabal suggested that if the issue persisted after posting on the template's github page (which I did), I should post here.

### The OS that Immich Server is running on

unRAID

### Version of Immich Server

1.88.2

### Version of Immich Mobile App

1.88.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A - unRAID Template
```

### Your .env content

```Shell
N/A - unRAID Template
```

### Reproduction steps

```bash
1. Start container
2. Watch logs for errors
```

**Comment by leozulfiu** [comment]
I do see the same error after updating to the newest version.

**Comment by congnt185** [comment]
Same error for me :(

**Comment by GH-Jay319** [comment]
I just got this issue trying to install just today... my firsrt go at immich. :(

**Comment by alextran1502** [comment]
@GHJJ123 Perhaps your CPU doesn't support typesense?

**Comment by GHJJ123** [comment]
> @GHJJ123 Perhaps your CPU doesn't support typesense?

I think this is the issue, Athlon X3 445, no AVX support. 

I'll try the alpine build without typesense.

**Comment by GHJJ123** [comment]
> @GHJJ123 Perhaps your CPU doesn't support typesense?

and this was the issue... it booted fine with alpine image! Thanks for the quick reply!

**Comment by Tyree** [comment]
> @GHJJ123 Perhaps your CPU doesn't support typesense?

I assume this isn't the issue with the 12700K, correct?

**Comment by GHJJ123** [comment]
> > @GHJJ123 Perhaps your CPU doesn't support typesense?
> 
> I assume this isn't the issue with the 12700K, correct?

correct, my issue was that my CPU was too old but got the same error as OP.
I cant see a 12700K having the same issue as my old CPU issue.

**Comment by dnlldl** [comment]
I have the same issue, CPU is brand new from Intel. Doubt it's a CPU problem. I guess this will be fixed with Typesense going away.

**Comment by jrasm91** [comment]
This is related to typesense, which will be dropped in the next release.

**Comment by AlgorithmArcher** [comment]
Just to add that I tried also to install Immich today on Unraid and got the same error...
