### ISSUE TITLE
[BUG] On the map, places with thousands picrtures aren't correctly  rendered

### ISSUE THREAD

**Issue by simulot** [immich-app/immich#5297]
### The bug

When zooming in too high in my living place, the thumbs aren't correctly rendered, probably because of their number.
![image](https://github.com/immich-app/immich/assets/5980377/2f13029b-2815-4d50-8997-33d5feee26dd)

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.88.2

### Version of Immich Mobile App

1.88.2

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
1. On the map view, go to your home
2. Zoom in
```

**Comment by simulot** [comment]
Impressed! 
11 minutes after the creation of the issue, a PR is announced!
💯

**Comment by danieldietzler** [comment]
> Impressed! 11 minutes after the creation of the issue, a PR is announced! 💯

To be fair it was an easy one :D
