### ISSUE TITLE
[BUG]The mobile backup album page keeps loading

### ISSUE THREAD

**Issue by wangl1987** [immich-app/immich#5302]
### The bug

There are 8000+ photos and 2300+ videos on the phone.
When the mobile backup album page is opened, assign permissions to immich to access all photos. The backup album page will always show Loading,I've been waiting for this page for about 2-3 hours. as shown in the picture below.
![微信图片_20231122204956](https://github.com/immich-app/immich/assets/150538734/c988185b-079d-4eaf-89cf-09b9bdc7a7ec)
Did some tests:
1. On another mobile phone, the number of photos is 1000+, and when connected to the same immich server, the backup album page is displayed normally.
2. On another mobile phone, there are 7000+ photos and 2000+ videos, and the backup album page keeps loading.
3. Set up a mobile phone with a large number of photos, only give immich access to some photos, and the backup album page will display normally.
From the client to the server, they are all within the LAN, and there is no proxy in between.

### The OS that Immich Server is running on

Installing through Docker Compose on Mac OS

### Version of Immich Server

1.88.2

### Version of Immich Mobile App

1.88.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
no changes
```

### Your .env content

```Shell
no changes
```

### Reproduction steps

```bash
1.Open the backup album page on the mobile terminal
2.
3.
...
```

**Comment by spectromas** [comment]
I am getting this as well with 1.90.0 (app) and 1.90.2 (server running on Linux).

**Comment by meehatpa** [comment]
Same, I have been also getting with the above versions.
