### ISSUE TITLE
[BUG] Missing timeline in home screen (web only)

### ISSUE THREAD

**Issue by MichaelBui** [immich-app/immich#5305]
### The bug

![image](https://github.com/immich-app/immich/assets/1146708/7fc509b1-59a5-4667-a74a-33626cb13eea)

After upgrading from 1.65.0 to 1.88.2, the timeline is not showing on the home screen (web platform) anymore while it's showing on mobile for both iOS & Android. 

I'm not sure if it's a bug or a new setting that I need to configure? Thanks 🙏

### The OS that Immich Server is running on

Docker Image

### Version of Immich Server

v1.88.2

### Version of Immich Mobile App

v1.88.0 #128

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A because I'm running inside a k8s cluster
```

### Your .env content

```Shell
IMMICH_SERVER_URL: http://192.168.1.5:10400
  DB_HOSTNAME: "192.168.1.5"
  DB_PORT: "5432"
  DB_USERNAME: immich
  DB_PASSWORD: ************
  DB_DATABASE_NAME: immich
  REDIS_HOSTNAME: "192.168.1.5"
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "0"
  TYPESENSE_HOST: "192.168.1.5"
  TYPESENSE_PORT: "8108"
  TYPESENSE_API_KEY: ************************************
```

### Reproduction steps

```bash
I'm not sure if upgrading is the correct step to product

1.
2.
3.
...
```

**Comment by bo0tzz** [comment]
That's a very big jump, have you read the release notes to see if there's any actions you need to take?

**Comment by MichaelBui** [comment]
I'm only aware of changes with microservices (web & proxy were removed since v1.85.0). 

I'm not aware of any changes in DB structure or file system that may cause this and I guess it's likely caused by them because they usually cause the app fails to load rather than missing some part of the UI.

Also, the timeline is showing fine in both iOS & Android (both latest version)

**Comment by bo0tzz** [comment]
Are there any errors in the container logs or the browser console?

**Comment by jrasm91** [comment]
This issue has been resolved.
