### ISSUE TITLE
[BUG] <After the android client accesses the site network is not reachable, login again need to re-enter the account password>

### ISSUE THREAD

**Issue by YosenFree** [immich-app/immich#5330]
### The bug

When I start the android client, at this time, there may be a problem with the network, or the site address accessed needs to go through additional ip authentication first before it can be accessed normally. At this time the app will stay in the site address input page, when I solve the network problem, logging in again need to manually re-enter the account password to log in, why can't the client directly cache my account password?Only if the server returns a mismatch between the account and password authentication, the user is required to enter the account password again.。

### The OS that Immich Server is running on

centos

### Version of Immich Server

v1.88.0

### Version of Immich Mobile App

v1.88.0 build.112

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
This problem should have nothing to do with yml files
```

### Your .env content

```Shell
This problem should have nothing to do with env files
```

### Reproduction steps

```bash
1.Pre-conditions: at this time there are problems with the network, or access to the site address needs to go through additional ip authentication before you can access normally
2.When the pre-conditions are present, at which point the Android app app is launched, the app stays on the server address input screen, the input box has been auto-populated with the currently used server address, and it prompts an error message such as unable to link or something similar.
3.Waiting for me to solve the network problem so that the application can access the server directly. At this point, confirming the address again to log in, the program page jumps to the user account and password entry screen, requiring a human to enter the account password again.
4.why can't the client directly cache my account password?Only if the server returns a mismatch between the account and password authentication, the user is required to enter the account password again.。
```

**Comment by alex-007** [comment]
You can close the app and reopen it again. In my case it helps with both Android and iOS applications

**Comment by YosenFree** [comment]
> You can close the app and reopen it again. In my case it helps with both Android and iOS applications

Thanks, I tried that, but when the scenario where the network needs to verify the ip first comes up, even if you close the app and take care of the network verification, when you open the app again several times at this point, it still stays on the page that confirms the server address, and after clicking the next button, you still need to enter the account password.

**Comment by jrasm91** [comment]
I believe this connectivity issue has been fixed. Let us know if this is still an issue.
