### ISSUE TITLE
[Bug] Proper error message in cli when token is not authorised 

### ISSUE THREAD

**Issue by PrashantSakre** [immich-app/immich#5357]
### The bug

Have descriptive error message in CLI, Incase if the token failed to authenticate user. Currently it shows very long error message.

### The OS that Immich Server is running on

Linux Mint

### Version of Immich Server

v1.88.2

### Version of Immich Mobile App

v.88.0 build. 112

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
This problem should nothing to do with yml file
```

### Your .env content

```Shell
This problem should nothing to do with yml file
```

### Reproduction steps

```bash
1. CLI login with credentials ( url, API key)
2. Remove the token from admin ( web )
3. Try getting the server-info from CLI
4. Server throws the error
```

**Comment by jrasm91** [comment]
The error messages look a lot better now. This is the one for login failure.

```
immich login-key http://127.0.0.1:2283/api abcdef
Logging in to http://127.0.0.1:2283/api
Failed to connect to server: 401
{
  "message": "Invalid API key",
  "error": "Unauthorized",
  "statusCode": 401
}
```
