### ISSUE TITLE
[BUG] [updateAlbumInfo] RequiredError: Required parameter albumId was null or undefined when calling updateAlbumInfo

### ISSUE THREAD

**Issue by jho1670** [immich-app/immich#538]
**Describe the bug**

docker logs on altran1502/immich-web:release shows

Listening on 0.0.0.0:3000
(node:50) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error [updateAlbumInfo]  RequiredError: Required parameter albumId was null or undefined when calling updateAlbumInfo.
    at assertParamExists (file:///usr/src/app/build/server/immutable/chunks/api-3b5a1fed.js:38:11)
    at Object.updateAlbumInfo (file:///usr/src/app/build/server/
immutable/chunks/api-3b5a1fed.js:264:7)
    at Object.updateAlbumInfo (file:///usr/src/app/build/server/immutable/chunks/api-3b5a1fed.js:324:65)
    at AlbumApi.updateAlbumInfo (file:///usr/src/app/build/server/immutable/chunks/api-3b5a1fed.js:355:43)
    at file:///usr/src/app/build/server/entries/pages/albums/_albumId_/index.svelte.js:164:22
    at Object.$$render (file:///usr/src/app/build/server/immutable/chunks/index-b4270eaf.js:117:18)
    at file:///usr/src/app/build/server/entries/pages/albums/_albumId_/index.svelte.js:280:86
    at Object.$$render (file:///usr/src/app/build/server/immutable/chunks/index-b4270eaf.js:117:18)
    at Object.default (file:///usr/src/app/build/server/index.js:37:92)
    at file:///usr/src/app/build/server/entries/pages/__layout.svelte.js:132:53 {
  field: 'albumId'
}

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

[docker-compose.zip](https://github.com/immich-app/immich/files/9435467/docker-compose.zip)

**To Reproduce**
1. Set up immich. Upload some pictures
2. Upgrade to latest 1.25.0_35-dev
3. Server displays 500 internal server error on web ```500 Request failed with status code 502```

**Expected behavior**
Web UI should load without error after upgrade.

**Screenshots**

**System**
- Phone OS [iOS, Android]: n/a
- Server Version: `1.25.0_35-dev`
- Mobile App Version: n/a

**Additional context**

**Comment by alextran1502** [comment]
How did you perform the update? 

Please bring down all the containers and run `docker-compose pull immich-web immich-server`, then restart and try again.

**Comment by jho1670** [comment]
I upgraded with:
```
docker-compose down
docker-compose -f docker-compose.yml pull
docker-compose -f docker-compose.yml up -d
```

I just did
```
# docker-compose pull immich-web immich-server
Pulling immich-web    ... done
Pulling immich-server ... done
# docker-compose -f docker-compose.yml up -d
```

Looks like it's working :) Thanks!
