### ISSUE TITLE
[Feature]: Use as gallery to show photos and videos directly from server

### ISSUE THREAD

**Issue by Txxicer** [immich-app/immich#541]
### Feature detail

Hello,

this software is a great product to backup and store files from a mobile phone and to view them directly in the app or through the web interface. But I miss a big feature.

It would be nice if you could implement the function, that the software can use pictures and videos from a folder on a server, so that I can view the files in web interface or in the app.

### Platform

Server

**Comment by bo0tzz** [comment]
I think this is a duplicate of #34

**Comment by alextran1502** [comment]
Duplicated of #34
