### ISSUE TITLE
[Feature] Lazy load thumbnails on the albums page

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#5418]
### Discussed in https://github.com/immich-app/immich/discussions/5417

<div type='discussions-op-text'>

<sup>Originally posted by **go-vegan** December  1, 2023</sup>
### The feature

Similar to https://github.com/immich-app/immich/pull/5356, only for albums.

### Platform

- [ ] Server
- [X] Web
- [ ] Mobile</div>

**Comment by flyotlin** [comment]
Hi, I would like to take this issue. Is there anyone working on this?

**Comment by bo0tzz** [comment]
Not that I'm aware, go ahead!

**Comment by PrashantSakre** [comment]
Hey 👋, i would love to work on this can you explain bit more on what to do here.

**Comment by bo0tzz** [comment]
@PrashantSakre this issue has already been picked up by @flyotlin

**Comment by PrashantSakre** [comment]
Oo ok, thanks

**Comment by flyotlin** [comment]
@bo0tzz I just added lazy loading support for album, and found that [search](https://github.com/immich-app/immich/blob/main/web/src/routes/(user)/search/%2Bpage.svelte#L149) and [sharing](https://github.com/immich-app/immich/blob/main/web/src/routes/(user)/sharing/%2Bpage.svelte#L99) page use [`AlbumCard`](https://github.com/immich-app/immich/blob/main/web/src/lib/components/album-page/album-card.svelte#L85) as well.

Maybe we can consider also add lazy loading on these two pages?

**Comment by bo0tzz** [comment]
Sounds good, thank you!
