### ISSUE TITLE
[Feature]: Auto create albums out of folders

### ISSUE THREAD

**Issue by Txxicer** [immich-app/immich#542]
### Feature detail

A function, that albums could be created out of the folder structure, would be great.

For example if I have the following folder structure:

-DCIM
--Photos1 {5 photos}
--Photos2 {3 photos}
---Photos2.2 {1 photo}

the software could create the albums called "Photos1" which includes the 5 photos, "Photos2" which includes the 3 photos and "Photos2.2" which includes the 1 photo.

This feature would be nice and would take much work off.

### Platform

Server

**Comment by alextran1502** [comment]
Duplicated of #537
