### ISSUE TITLE
[BUG] Can't uplodad a file named ".jpg" or ".mp4"

### ISSUE THREAD

**Issue by simulot** [immich-app/immich#5421]
### The bug

Dropping a file named ".jpg" or ".mp4" on the app's page gives an error 400 Bad request.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.89.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
Rename perfectly valide jpg file as ".JPG" and drop it on the app page.

Same behavior when uploading this using immich-go.
```

### Additional information

Problem revealed by Tomato 🍅 on this [discord server thread](https://discord.com/channels/979116623879368755/1179517794606395462)

**Comment by simulot** [comment]
Done a second ago
![image](https://github.com/immich-app/immich/assets/5980377/c9bc9203-1875-4931-92fe-e164e31c927c)

**Comment by jrasm91** [comment]
I looked into this. It's not that hard to change the app to support uploading it. However, it does lead to a lot of weird circumstances. Like a lot of the code relies on the fact that a file has a base name and an extension. The storage template in particular. Allowing the file to be named  just `.jpg` or `.mp4` introduces a lot of edge cases that I don't think are worth supporting. So going to close this as not planned.

**Comment by simulot** [comment]
We can find those weird cases in google takeout files.
It's managed by immich-go by pretending the file name is noname.jpg
