### ISSUE TITLE
[BUG] iphone 11 pro max swipe up to view EXIF meta data displays fine but no way to swipe closed.  

### ISSUE THREAD

**Issue by steve5355** [immich-app/immich#5425]
### The bug

When I swipe up on my iphone 11 pro max, i see the json exif dump but when i scroll up or down in all the right places, it moves up or down, but wont slide away, so it just snaps back into view. So there is no way to exit the exif data view, i have to hard close the app and restart.   I have tried pulling and sliding from all areas, corners, etc.   I think it might be a margin issue for the handle to close it or slide it closed.  

proposed fix:  add a "close" button next to the copy button in the top right or bottom, also made the landing area bigger and easier to see for pulling it back up and out of the way again. 

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.89

### Version of Immich Mobile App

v1.89

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. click image
2. slide up to reveal exif data
3. you're stuck there, no way out.
```

### Additional information

only tested in iphone 11 pro max.

**Comment by shenlong-tanwen** [comment]
Can you try tapping outside the "Advanced Info" sheet? Also, try swiping down starting from the area where the text "Advanced Info" is displayed.

**Comment by steve5355** [comment]
> Can you try tapping outside the "Advanced Info" sheet? Also, try swiping down starting from the area where the text "Advanced Info" is displayed.

I tried that, the page pulls down to reveal the photo under it, but instead of sliding back down, it just snaps back up.  i drag from as high up as i can, to as low bottom edge of the screen and it just snaps up again. 

![image](https://github.com/immich-app/immich/assets/150961333/9c026e4f-822e-48ad-a4e6-059c92dfe818)

**Comment by steve5355** [comment]
I believe this is related to having my font size at "larger" setting, it might be pushing the box bigger and the area to swipe closed is now off the edge of the screen.  

My workaround:  
Rotate the phone sideways after viewing the details, to widescreen, and tap in the space on the side.

**Comment by shenlong-tanwen** [comment]
> I believe this is related to having my font size at "larger" setting, it might be pushing the box bigger and the area to swipe closed is now off the edge of the screen.

That was really helpful, Thank you. I finally managed to reproduce the issue. We will get this addressed in a future build. Meanwhile, I can close the sheet by tapping twice or thrice in the status bar around the clock / battery. Can you please check if that works for you as well?

**Comment by steve5355** [comment]
> That was really helpful, Thank you. I finally managed to reproduce the issue. We will get this addressed in a future build. Meanwhile, I can close the sheet by tapping twice or thrice in the status bar around the clock / battery. Can you please check if that works for you as well?

yes, double clicking does slide it away. thanks for that work around.  I updated #5831 saying that i found the cause of the issue, using "Display Zoom = Larger Text" in Display and Brightness settings on ios.    we can keep this item closed if there is a future fix for this.

**Comment by shenlong-tanwen** [comment]
>  We can keep this item closed if there is a future fix for this.

The current fix was to actually make the bottom sheet do not cover the entire screen but to just below the top status bar. The status bar should be a bit more obvious now indicating that it is outside the bottom sheet and the user can tap there to close the sheet. Do you think that this is still not clear and should be handled in a different way instead?

**Comment by steve5355** [comment]
since I'm using  "Display Zoom = Larger Text" in Display and Brightness settings on ios, i dont see a bottom toolbar.  I have to use the workaround and double click on the top area near the ear speaker.
