### ISSUE TITLE
[BUG] mobile: app crashes while scrolling shared albums

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#5428]
### The bug

App crashes while trying to add an asset to shared album. Worth to mention that scrolling all albums do not cause crash, only shared albums dropdown is affected, shared albums thumbnails are loading very slowly comparing to all albums.

```
I/flutter (16891): ═════════════════════════════════════════════════════════════════
I/flutter (16891):  - A RenderFlex overflowed by 6.0 pixels on the right. - rendering library - during layout - null
I/flutter (16891): [SEVERE] [2023-12-01 19:46:54.311298] Catch all error: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞══════════════════════
I/flutter (16891): The following assertion was thrown during layout:
I/flutter (16891): A RenderFlex overflowed by 31 pixels on the right.
I/flutter (16891): 
I/flutter (16891): The relevant error-causing widget was:
I/flutter (16891):   Row
I/flutter (16891):   Row:file:///D:/src/immich/mobile/lib/modules/album/ui/album_thumbnail_listtile.dart:67:16
I/flutter (16891): 
I/flutter (16891): To inspect this widget in Flutter DevTools, visit:
I/flutter (16891): http://127.0.0.1:9100/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A2386%2Fnf3pGTdxF90%3D%2F&inspectorRef=inspector-422
I/flutter (16891): 
I/flutter (16891): The overflowing RenderFlex has an orientation of Axis.horizontal.
I/flutter (16891): The edge of the RenderFlex that is overflowing has been marked in
I/flutter (16891): the rendering with a yellow and black striped pattern. This is
I/flutter (16891): usually caused by the contents being too big for the RenderFlex.
I/flutter (16891): Consider applying a flex factor (e.g. using an Expanded widget)
I/flutter (16891): to force the children of the RenderFlex to fit within the
I/flutter (16891): available space instead of being sized to their natural size.
I/flutter (16891): This is considered an error condition because it indicates that
I/flutter (16891): there is content that cannot be seen. If the content is
I/flutter (16891): legitimately bigger than the available space, consider clipping
I/flutter (16891): it with a ClipRect widget before putting it in the flex, or using
I/flutter (16891): a scrollable container rather than a Flex, like a ListView.
I/flutter (16891): The specific RenderFlex in question is: RenderFlex#f476e relayoutBoundary=up17 OVERFLOWING:
I/flutter (16891):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (16891):   constraints: BoxConstraints(0.0<=w<=328.0, 0.0<=h<=Infinity)
I/flutter (16891):   size: Size(328.0, 68.0)
I/flutter (16891):   direction: horizontal
I/flutter (16891):   mainAxisAlignment: start
I/flutter (16891):   mainAxisSize: max
I/flutter (16891):   crossAxisAlignment: start
I/flutter (16891):   textDirection: ltr
I/flutter (16891):   verticalDirection: down
I/flutter (16891): ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
I/flutter (16891): ═════════════════════════════════════════════════════════════════
```

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

not relevant

### Version of Immich Mobile App

v1.89.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. select an aset
2. swipe up to see albums 
3. drop down shared albums
4. scroll shared albums
5. app crashes without any message
```

**Comment by waclaw66** [comment]
When I've changed thumbnail format to WEPB, it doesn't crash and loading thumbnails is much faster. Why albums convers need big JPEG cover?
https://github.com/immich-app/immich/blob/387faa13d54308e6390b0c10c01ab45cb005c185/mobile/lib/modules/album/ui/album_thumbnail_listtile.dart#L53

**Comment by shenlong-tanwen** [comment]
I cannot reproduce this in my test environment. However, I have very few shared albums each of them having only a handful assets. 

Can you please let me know how many shared albums you have? Also, Can you reproduce the crash consistently, every time you scroll through the shared albums list? What happens when you scroll through the list of albums in the share page? Do you have a shared album with a very long title?

**Comment by waclaw66** [comment]
About 250 of shared albums. Yes, it crashes every time. I've tried to debug it and catch the exception, but it's not thrown. However the problem is somewhere behind `buildAlbumThumbnail()` function
https://github.com/immich-app/immich/blob/231b89c9c0aa0380947c5b5c2c3b67ecba867cb9/mobile/lib/modules/album/ui/album_thumbnail_listtile.dart#L74
When `buildEmptyThumbnail()` is called for all albums it doesn't crash.

**Comment by shenlong-tanwen** [comment]
> When `buildEmptyThumbnail()` is called for all albums it doesn't crash.

The non-shared albums are lazily loaded properly based on their index, however, if you check the following lines

https://github.com/immich-app/immich/blob/main/mobile/lib/modules/album/ui/add_to_album_sliverlist.dart#L32-L36

We are actually using an `ExpansionTile` for the first index and on toggling it, all the shared albums are rendered as its children, thereby triggering the thumbnail fetch for all the shared albums in the same time. Not sure if this is really the reason for the crash though, but this is something that could use a refactoring to lazily load them.

**Comment by waclaw66** [comment]
> We are actually using an `ExpansionTile` for the first index and on toggling it, all the shared albums are rendered as its children, thereby triggering the thumbnail fetch for all the shared albums in the same time. Not sure if this is really the reason for the crash though, but this is something that could use a refactoring to lazily load them.

I belive that's the case. Expanding, loading and scrolling those 250 children is very laggy and it crashes in few seconds.
Unfortunatelly flutter is completely new thing to me, thus I cannot fix it on my own.

**Comment by shenlong-tanwen** [comment]
> I belive that's the case. Expanding, loading and scrolling those 250 children is very laggy and it crashes in few seconds. Unfortunatelly flutter is completely new thing to me, thus I cannot fix it on my own.

Can you please test if it is still crashing on #5510? I've updated the shared albums list to use a ListView, which should hopefully, load them lazily.

**Comment by waclaw66** [comment]
This is fixing that...
```dart
    final sorted = albums
        .where((a) => a.isRemote)
        //.sortedBy((album) => album.endDate ?? DateTime(1000))
        .sorted((a, b) {
      if (a.endDate != null && b.endDate != null) return a.endDate!.compareTo(b.endDate!);
      if (a.endDate == null) return 1;
      if (b.endDate == null) return -1;
      return 0;
    });
```

**Comment by waclaw66** [comment]
No longer an issue due to #6444 fix.
