### ISSUE TITLE
[BUG] server: EXTRACT METADATA job paused after server restart

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#5437]
### The bug

EXTRACT METADATA job is always paused after server restart.

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

v1.89.0

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
not relevant
```

**Comment by bo0tzz** [comment]
The job gets paused while the server is initializing the geocoding data. Does it stay paused afterwards? What do the logs say?

**Comment by waclaw66** [comment]
It stays paused forever. I have to unpause it manually.

**Comment by martabal** [comment]
You can find your missing files here https://github.com/immich-app/base-images/blob/d71ac47ff8e49f55980c1f1beef6594872f017c0/server/Dockerfile#L61-L66

**Comment by waclaw66** [comment]
> You can find your missing files here https://github.com/immich-app/base-images/blob/d71ac47ff8e49f55980c1f1beef6594872f017c0/server/Dockerfile#L61-L66

Thanks, found already. Not nice to use absolute paths in the code.

**Comment by zackpollard** [comment]
We are aware, this is something that will change with future revisions of the reverse geocoding implementation. We were limiting scope on the first pass.
