### ISSUE TITLE
[BUG] Incorrect Portuguese locale

### ISSUE THREAD

**Issue by andredasilvapinto** [immich-app/immich#5490]
### The bug

Portuguese locale is defined as `Locale('pt', 'PR')` [here](https://github.com/immich-app/immich/blob/main/mobile/lib/constants/locales.dart#L17). Country code "PR" is typically Puerto Rico. Portugal is "PT".

There are also [other Portuguese locales](https://www.localeplanet.com/icu/iso639.html#pt) that might need to be added to that file in case you have translations for them (not sure what the purpose of the file is though).

Finally, not sure how relevant it is but there is an entry for pt_BR (Brazil) here https://github.com/immich-app/immich/blob/main/localizely.yml#L33-L34 but not for pt_PT (Portugal).

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

1.88.2

### Version of Immich Mobile App

1.89.0 build.113

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by bo0tzz** [comment]
Side note: should we be defining these locale codes ourselves at all?
