### ISSUE TITLE
[BUG] no option on multi-select on local album in app (android)

### ISSUE THREAD

**Issue by kaaku3** [immich-app/immich#5494]
### The bug

There is no options when multi-selecting pictures in local albums.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.89.0

### Version of Immich Mobile App

1.89.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Same as example
```

### Your .env content

```Shell
Same as example
```

### Reproduction steps

```bash
1. Click on library at bottom of app
2. Select folder under "Albums on device"
3. Long press on a picture
4. Procede click on other pictures to multi-select.
5. No option to do anything with selected pictures.
```

### Additional information

I would love the ability to multi-delete to cleanup unneeded screenshots
![Screenshot_20231205-110832](https://github.com/immich-app/immich/assets/2504063/38185d7a-53df-4f10-a52f-8cf478680997)

**Comment by shenlong-tanwen** [comment]
Will be added in #5407
