### ISSUE TITLE
[BUG] Share-links are no-longer embedded due to missing meta tags

### ISSUE THREAD

**Issue by samip5** [immich-app/immich#5501]
### The bug

It seems that ever since SSR being removed, the share links are missing meta tags that would let things like Discord show the image you shared directly. I want it back and as it used to work, I'm filing this as a bug.

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

v1.89.0

### Version of Immich Mobile App

Not relevant

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
1. Create a public share url
2. Give it to eg https://www.opengraph.xyz or just paste into a Discord channel.
3. See that there's no image fetched.
```

### Additional information

This really used to work and it's a good feature to have. I know that @bo0tzz knows what I'm talking about.

**Comment by jrasm91** [comment]
Yup, that might be possible, although probably quite complicated. Theoretically we can have a list of urls we send back dynamic html for instead of static.

**Comment by bo0tzz** [comment]
What about having the share url lead to a dynamic page that is just the meta tags and an automatic javascript redirect to the actual gallery? That way we can serve that from immich-server without too much fuss, while being mostly seamless to human users (hopefully).

**Comment by jrasm91** [comment]
This has been fixed.
