### ISSUE TITLE
[BUG] Sidebar - Show people resets 

### ISSUE THREAD

**Issue by deiop** [immich-app/immich#5517]
### The bug

Using firefox. 
If you set the sidebar to diplay people link, it is reset to "do not show" after some time. 
This bug exists since the beginning :-) Maybe a container restart sets it back. 

### The OS that Immich Server is running on

Ubuntu LTS

### Version of Immich Server

1.89

### Version of Immich Mobile App

none

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Set sidebar to display people
2. Logout
3. Restart container / clear browser cache (Firefox) / delete cockies
4. people sidebar no longer set. 

Using Firefox
...
```

**Comment by alextran1502** [comment]
this setting is saved on the client side, so if you are clear browser cache/storage, it will remove this settting

**Comment by deiop** [comment]
Hi @alextran1502 browser cache is cleared by security policy in our company and on the laptops as well. So maybe it is "better" to store the setting in the user profile?
