### ISSUE TITLE
[BUG] There are some errors in facial recognition. How can I remove images that do not belong to this person? thanks

### ISSUE THREAD

**Issue by nodis** [immich-app/immich#5518]
### The bug

There are some errors in facial recognition. How can I remove images that do not belong to this person? thanks
![微信图片编辑_20231206220758](https://github.com/immich-app/immich/assets/23695589/3b8a055b-3e7b-4d5b-bc7b-24d73c907a89)

### The OS that Immich Server is running on

Synology

### Version of Immich Server

1.89

### Version of Immich Mobile App

1.89

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
test
```

### Your .env content

```Shell
test
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by deiop** [comment]
Not possible YET. Wait for https://github.com/immich-app/immich/pull/5511

**Comment by jrasm91** [comment]
You can use the "Fix incorrect match" feature to bulk re-assign images to another person.
