### ISSUE TITLE
[BUG] WebUI Clicking Back on Mouse while photo up doesn't go back

### ISSUE THREAD

**Issue by isaacolsen94** [immich-app/immich#5549]
### The bug

While viewing a photo if you press the Back button on mouse it doesn't Exit or Go back. Similar situation in GPhotos would close image. Not sure if this is an intentional choice?  

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.90.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A (Installed from CA)
```

### Your .env content

```Shell
N/A (Installed from CA)
```

### Reproduction steps

```bash
1. Click on photo to view
2. Press back button on mouse
```

**Comment by martabal** [comment]
Yes, this is a current limitation due to #2906
