### ISSUE TITLE
[BUG] Memories not showing up in iOS app

### ISSUE THREAD

**Issue by raisinbear** [immich-app/immich#5586]
### The bug

Hi,

like the title says, memories aren't showing up in the iOS app for me since updating the app to `1.90` and the server to `1.90.1/2`. In the web interface they do, however, so I know there were pictures taken on this date in the past. I am not entirely sure the updates brought this issue immediately as I think I still saw memories yesterday after updating. However, today none showed up. I tried the following without success:
- force close the app and restart
- log out of my account in the app and back in (thus recreating the timeline)
Edit:
- deleted and reinstalled the mobile app

I cannot find log entries related to fetching "memories" photos - neither in the app nor docker stdout, but no errors either.

As always thank you so much for this project and all the new features with each release! 🙂

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.90.2

### Version of Immich Mobile App

v1.90.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I'll tag this and the .env content as not relevant since they have not changed and I see no errors whatsoever.
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. (Possibly wait for a day after updating both server and mobile app, although I'm not sure this isn't nonsense)
2. Open iOS app, find no memories. Go to web interface and find memories. Of course you need to have photos from previous years and that exact date in your library.
```

**Comment by shenlong-tanwen** [comment]
Will be fixed in the next release. Thank you for the report

**Comment by locqust** [comment]
If it helps, same on the Android app as well.

**Comment by r01k** [comment]
Ok, it's not only me then.
