### ISSUE TITLE
[BUG] ctl+f keyboard shortcut is used to mark a photo as a favorite

### ISSUE THREAD

**Issue by eygraber** [immich-app/immich#5603]
### The bug

ctl+f is a browser shortcut for finding text. Maybe it was used because who would be searching for text in a photo, but I've been using it as a workaround for https://github.com/immich-app/immich/issues/5571. Now I have to go unfavorite all of those photos.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.90.2

### Version of Immich Mobile App

v1.90.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1.Press ctl+f when viewing a photo
```

**Comment by jrasm91** [comment]
Fixed in #7207
