### ISSUE TITLE
[BUG] .ARW support still not working

### ISSUE THREAD

**Issue by quadrupole1988** [immich-app/immich#5605]
### The bug

I'm a newbie, but I'm under the impression that .arw support is working based on the following link:

https://github.com/immich-app/immich/pull/2668#issuecomment-1587943535

but when I uploaded some .arw files, no thumbnails are generated and I can't see the photo (attached screenshot)
![Screenshot 2023-12-10 012041](https://github.com/immich-app/immich/assets/83847151/91b7bf0f-a11f-45e9-bb56-e457157376c8)

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.90.2

### Version of Immich Mobile App

1.9.0.0 build 114

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
docker run
  -d
  --name='immich'
  --net='bridge'
  -e TZ="America/Denver"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Saturn"
  -e HOST_CONTAINERNAME="immich"
  -e 'DB_HOSTNAME'='10.10.20.51'
  -e 'DB_USERNAME'='user'
  -e 'DB_PASSWORD'='password'
  -e 'DB_DATABASE_NAME'='immich'
  -e 'REDIS_HOSTNAME'='10.10.20.50'
  -e 'DISABLE_MACHINE_LEARNING'='false'
  -e 'DISABLE_TYPESENSE'='false'
  -e 'DB_PORT'='5432'
  -e 'REDIS_PORT'='6379'
  -e 'REDIS_PASSWORD'='password'
  -e 'MACHINE_LEARNING_WORKERS'='1'
  -e 'MACHINE_LEARNING_WORKER_TIMEOUT'='120'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png'
  -p '8090:8080/tcp'
  -v '/mnt/user/photogallery/Immich/':'/photos':'rw'
  -v '/mnt/user/temp/':'/config/machine-learning':'rw'
  -v '/mnt/user/photogallery/Import/':'/import':'ro'
  -v '/mnt/user/appdata/immich':'/config':'rw' 'ghcr.io/imagegenius/immich'
cd914a8d289b485ed7dfc7a24e4390cc72ca5da1444b6d9eaf75f41bf796c595
```

### Your .env content

```Shell
unraid
```

### Reproduction steps

```bash
1.upload arw from a7iv
2.
3.
...
```

**Comment by AGJSpiegelenberg** [comment]
I think its the same issue solve in: https://github.com/immich-app/immich/pull/5509

**Comment by jrasm91** [comment]
Yup and hasn't been released yet.

**Comment by quadrupole1988** [comment]
Sorry, I didn't know it wasn't released yet!

Thank you for taking the time to reply and for your efforts to Immich!
