### ISSUE TITLE
[BUG] NEF Thumbnails generating incorrectly 160x120px

### ISSUE THREAD

**Issue by dunezilla** [immich-app/immich#5613]
### The bug

I already posted this bug on discord but thought I would post here for tracking and other users who may be experiencing this bug to know they are not alone. 

I am having a problem with NEF files producing very small thumbnails, both the gallery view and the larger thumbnail that is suppose to be 1440p.  When I checked the file at the source, it is 160x120.. which of course results in a very small blurry image.  Its happening across all my NEF imports. I am currently running thumbnail generation again to see if it fixes the problem, but I can't tell yet as i have a massive library. I've searched a bit and it looks like this was an earlier problem.  I am on 1.90.2. All the JPG and DNG work great.

EDIT: running thumbnails again didn’t fix the issue. 

### The OS that Immich Server is running on

Unraid 

### Version of Immich Server

1.90.2

### Version of Immich Mobile App

1.89.0 build 129

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
1.thumbnail generation on NEF files
2.
3.
...
```

**Comment by dunezilla** [comment]
![DSC_9178](https://github.com/immich-app/immich/assets/129792033/6e610884-4724-4933-b505-0917ab869ec5)

**Comment by EsOsO** [comment]
Facing same issue on Unraid, for DNG too. 
Run yesterday thumbnail generation on all photos.

Immich Server version 1.90.2
Immich App version 1.90.0 build.130

**Comment by alextran1502** [comment]
This is a regression upstream, we are looking into this

**Comment by mertalev** [comment]
This is fixed now with #5705.
