### ISSUE TITLE
[BUG] Official website is down

### ISSUE THREAD

**Issue by vnghia** [immich-app/immich#5639]
### The bug

https://immich.app/ is down

![image](https://github.com/immich-app/immich/assets/17511625/52b72b5b-1843-4c6e-bd9d-aab95032c2e6)

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

### Additional information

/cc @alextran1502

**Comment by alextran1502** [comment]
thank you for reporting, it is now up
