### ISSUE TITLE
[Feature]: OCR

### ISSUE THREAD

**Issue by akoyaxd** [immich-app/immich#565]
### Feature detail

Additionally to object detection it would be awesome to have the images ocr'ed to search for Text inside the images and added to the metadata.

### Platform

Server

**Comment by palitu** [comment]
is this something that can be completed by a webhook into an eco-system of ML containers?

Ie, on upload, a webhook is triggered, which is registered by one or more individual ML containers to do their thing, OCR, face detection, object detection.  Whatever is actually wanted/needed by the individual.

**Comment by alextran1502** [comment]
This is nice but out of scope of the project

**Comment by jasongwq** [comment]
I am using [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/README.md) to implement ocr and support retrieval on the app

**Comment by eagle470** [comment]
> I am using [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/README.md) to implement ocr and support retrieval on the app

How?

**Comment by vb0** [comment]
Approaching this from a different angle: Google Photos android app saves locally<sup>1</sup> a fairly complete (and GB-large<sup>2</sup> for any sizeable number of assets) gphotos0.db which is a sqlite3 db with a lot of metadata for (all the) Google Photos assets from the account. There is a lot of data there, including of course the OCRed strings. If we had an endpoint, or a simple no matter how hackish workflow to ingest this into Immich it'll mean a lot for power users coming from Google Photos.  


<sup>1</sup> albeit you'd generally need root to grab it, or just some Android emulator with enough stuff on it so you can install Google Photos, log in and let it sync the db, and then open the local disk and access it some way    
<sup>2</sup> this is what you see as GBs taken by Google Photos even if you don't have anything locally, but many pictures online

**Comment by kingp0dd** [comment]
+1
Really enjoyed this feature in Google photos

**Comment by banjuer** [comment]
> I am using [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/README.md) to implement ocr and support retrieval on the app

hi, Could you make a tutorial? thanks a lot

**Comment by ragsmaroon** [comment]
I'm really surprised that this isn't in the scope of the product, especially because something like memories are an unnecessary feature but I assume they were implemented to have parity with Google Photos. Meanwhile, searching screenshots for text is a feature has a lot of utility and one that I used quite frequently in gphotos, and its absence here really neuters Immich in comparison.

**Comment by devkamiki** [comment]
ente has ocr that also depends on machine learning, the model runs on the device locally instead of server iirc
