### ISSUE TITLE
[BUG] OpenStreetMap attribution not visible on the image details page

### ISSUE THREAD

**Issue by CaldeiraG** [immich-app/immich#5652]
### The bug

When viewing an image details page, the attribution banner for OpenStreetMap is not visible. It could be collapsing automatically if the embed is too small

Relevant documentation: https://maplibre.org/maplibre-gl-js/docs/API/classes/maplibregl.AttributionControl/

### The OS that Immich Server is running on

Ubuntu 20.04 LTS

### Version of Immich Server

v1.90.2

### Version of Immich Mobile App

v1.90.2

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open an image with geolocation data
2. Click on the details button and the map will appear with the photo location without the attribution banner
```

**Comment by bo0tzz** [comment]
@danieldietzler can you take a look at this?

**Comment by bo0tzz** [comment]
Compact intentionally still leaves the attribution expanded, it just allows it to collapse when interacting with the map. The attribution can be pretty small - from the osm attribution guidelines I understand that just a link with the text "OpenStreetMap" is sufficient.
