### ISSUE TITLE
[BUG] Favicon for Firebox bookmark does not work

### ISSUE THREAD

**Issue by jwefers** [immich-app/immich#5676]
### The bug

In Firefox' bookmark bar, the favicon does not work. It works in the tab. Another webpage prone to this (for me) is https://www.theverge.com/ (where someone here gave a great interview ;)). Chromium works fine.

is it maybe due to favicon only being available as png, instead of svg/ico?

![image](https://github.com/immich-app/immich/assets/851823/ed303b96-1775-498a-8112-33981bd6211a)
![image](https://github.com/immich-app/immich/assets/851823/c74a85c0-d6f0-4663-803c-255890185fee)

### The OS that Immich Server is running on

Debian bookworm

### Version of Immich Server

1.90.1

### Version of Immich Mobile App

---

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
untouched from docs
```

### Your .env content

```Shell
untouched from docs
```

### Reproduction steps

```bash
1. Open immich instance
2. save as bookmark in firefox >= v120
3. see missing favicon on bookmark
...
```

**Comment by bo0tzz** [comment]
I think this happens because the favicon isn't in the plain page source, it only gets added once svelte rendering kicks in.

**Comment by martabal** [comment]
I can't reproduce it with Firefox v120.0.1

**Comment by martabal** [comment]
But I do have the same issue with theverge

**Comment by jwefers** [comment]
> I can't reproduce it with Firefox v120.0.1
huh? maybe a stubborn cache issue from the very first visit to my instance? Though i have this issue on two FF instances (120 ans 121-rc1) times two machines (Arch+KDE, X11/Wayland)

**Comment by martabal** [comment]
Nevermind, I have the same issue with librewolf (browser based on firefox).
