### ISSUE TITLE
[BUG] Error: Unknown keys found: {"reverseGeocoding":{"citiesFileOverride":"cities500"}}

### ISSUE THREAD

**Issue by SlavikCA** [immich-app/immich#5682]
### The bug

I use the Immich with config stored in the file.
When I updated to v1.90, it failed to start:

```
immich_server            | [Nest] 7  - 12/13/2023, 6:39:04 PM   ERROR [SystemConfigCore] Unable to load configuration file: /model-cache/immich-config.json due to Error: Unknown keys found: {"reverseGeocoding":{"citiesFileOverride":"cities500"}}
immich_server            | Error: Unknown keys found: {"reverseGeocoding":{"citiesFileOverride":"cities500"}}
immich_server            |     at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
immich_server            |     at async Promise.all (index 24)
immich_server            | [Nest] 7  - 12/13/2023, 6:39:04 PM   ERROR [ExceptionHandler] Invalid configuration file
immich_server            | Error: Invalid configuration file
immich_server            |     at SystemConfigCore.loadFromFile (/usr/src/app/dist/domain/system-config/system-config.core.js:318:23)
immich_microservices     | [Nest] 7  - 12/13/2023, 6:39:04 PM   ERROR [SystemConfigCore] Unable to load configuration file: /model-cache/immich-config.json due to Error: Unknown keys found: {"reverseGeocoding":{"citiesFileOverride":"cities500"}}
immich_microservices     | Error: Unknown keys found: {"reverseGeocoding":{"citiesFileOverride":"cities500"}}
```

I traced the issue to this PR 
https://github.com/immich-app/immich/pull/5301

which changed 

```
  "reverseGeocoding": {
    "enabled": true,
    "citiesFileOverride": "cities500"
  },
```

to

```
  "reverseGeocoding": {
    "enabled": true
  },
```

There are 2 issues now:

1) It would be great, if config parser can handle that change gracefull, i.e. it would ignore the not-needed-anymore variable, or print the warning instead of failing to start.

2) The documentation still have that value, and is invalid:

https://immich.app/docs/install/config-file

### The OS that Immich Server is running on

Docker

### Version of Immich Server

1.90

### Version of Immich Mobile App

0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
n/a
```

**Comment by jrasm91** [comment]
It throws an error by design to make sure you don't set something only to realize later, that it is not being used.
