### ISSUE TITLE
[BUG] Icon not changing after deleting local images

### ISSUE THREAD

**Issue by r3nor** [immich-app/immich#571]
I am running the latest immich version on server and mobile Android (1.26.0_36). When I delete some already backed up photos from my device, the icon on the bottom right of the image should change from the "stacked photos icon" to the "cloud with a tick) icon to indicate that the photo is no longer on the device, but it does not change.

**Comment by alextran1502** [comment]
This is now resolved with the combination of local and remote assets showing on the app
