### ISSUE TITLE
[BUG] Exif time 24:08:19 is not understood

### ISSUE THREAD

**Issue by Strubbl** [immich-app/immich#5714]
### The bug

Back in the days where i used an LG Nexus 4 for taking some pictures after midnight, these were created with some strange exif dates. Instead of e.g. 2015:08:22 00:08:19, the time was set to 2015:08:22 24:08:19 in the exif data. This is not understood by immich and the photo is sorted to the current time when it was process by immich.

### The OS that Immich Server is running on

docker-compose

### Version of Immich Server

v1.90.2

### Version of Immich Mobile App

not used

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
independent of docker-compose.yml
```

### Your .env content

```Shell
is irrelevant to this issue
```

### Reproduction steps

```bash
1. have a photo with exif creation dates e.g. with 2015:08:22 24:08:19
2. add this to immich
3. it gets sorted to today instead of 2015
```

**Comment by alextran1502** [comment]
Not a bug of Immich I would say, because the date is not valid ISO8601 format. So you should fix those first before uploading to Immich, or fix it later after uploading to Immich
