### ISSUE TITLE
[BUG] Website Down

### ISSUE THREAD

**Issue by littlegraycells** [immich-app/immich#5729]
### The bug

The immich website is down. I've checked this with a few different networks. 

![image](https://github.com/immich-app/immich/assets/15359327/f898dbe7-d051-4057-b6fe-1c75413dae84)

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. Go to `https://immich.app` with any browser.
1. A 404 error from vercel is presented.
...
```

**Comment by bo0tzz** [comment]
You seem to be hitting a very stale DNS cache. We moved the website to cloudflare pages recently, and for me that's all working fine ;)
