### ISSUE TITLE
{BUG]s6-rc-compile: fatal: during dependency resolution for service init-config-end: undefined service name init-test-run<title>

### ISSUE THREAD

**Issue by HeresJonny** [immich-app/immich#5779]
### The bug

Immich doesn't start with the above message since the latest update I got just now.

### The OS that Immich Server is running on

Unraid 6.12.6

### Version of Immich Server

alpine

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
ghcr.io/imagegenius/immich:alpine
https://github.com/orgs/imagegenius/packages/container/package/immich
```

### Your .env content

```Shell
? no such thing
```

### Reproduction steps

```bash
1. Happens all the time when I check the log
2.
3.
...
```

### Additional information

Nothing further

**Comment by bo0tzz** [comment]
This is an issue with the unofficial AIO image, please report it in the appropriate repository.
