### ISSUE TITLE
[Feature]: Managing existing photo folder

### ISSUE THREAD

**Issue by nk950357** [immich-app/immich#578]
### Feature detail

Since immich still in development state, I'm now using Synology Photos to backup photos, but it lacks much of detection function.
Immich installs on my nas, is there anyway to make immich manages the existing backup flloder by Synology Photos?
I've tried if I put photos in upload floder, it won't show up image and details.
![image](https://user-images.githubusercontent.com/51433626/188328620-6cba83b5-e5b7-4bc6-b06a-fae4e3c04f2e.png)

### Platform

Server

**Comment by bo0tzz** [comment]
Duplicate: #7
