### ISSUE TITLE
[BUG] web: cluster of photos cannot be opened for viewing

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#5786]
### The bug

Cluster of photos in the map cannot be opened for viewing while clicking on it.

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

v.1.91.2

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
not relevant
```

**Comment by agross** [comment]
Same as #5784?
