### ISSUE TITLE
[BUG] Can't add 58000 photos to an album (53200 limited)

### ISSUE THREAD

**Issue by guiguid** [immich-app/immich#5788]
### The bug

Hi,
On Web interface, when trying to add 58000 photos to a new album, a server error is raised

```
déc. 17 11:31:14 brix immich-server[2088]: [Nest] 2  - 12/17/2023, 10:31:14 AM   ERROR [ErrorInterceptor] Failed to add assets to album
déc. 17 11:31:14 brix immich-server[2088]: [Nest] 2  - 12/17/2023, 10:31:14 AM   ERROR [ErrorInterceptor] QueryFailedError: bind message has 53200 parameter formats but 0 parameters
déc. 17 11:31:29 brix immich-server[2088]: [Nest] 2  - 12/17/2023, 10:31:29 AM   ERROR [ErrorInterceptor] Failed to add assets to album
déc. 17 11:31:29 brix immich-server[2088]: [Nest] 2  - 12/17/2023, 10:31:29 AM   ERROR [ErrorInterceptor] QueryFailedError: bind message has 53200 parameter formats but 0 parameters
```

### The OS that Immich Server is running on

Nixos 23.11.1697.781e2a9797ec (Tapir)

### Version of Immich Server

v1.91.0

### Version of Immich Mobile App

v1.91.0 build.115

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not related
```

### Your .env content

```Shell
not related
```

### Reproduction steps

```bash
On web interface,
create a new album
select more than 58000 photos, and click "Done"
```

### Additional information

May we realy need album with more than 58000 photos ?
Simply list this limitation in "features", "doc", and error related.
thx for this amazing tool !

**Comment by adamantike** [comment]
@guiguid, do you mind testing this again, either by running the current `main` branch, or when a version newer than `v1.91.4` is released?
