### ISSUE TITLE
[BUG] Response from database for reverse geocoding ... was null

### ISSUE THREAD

**Issue by SlavikCA** [immich-app/immich#5809]
### The bug

In the log, I see quite a few messages about reverse geocoding failing for valid coordinates.
For example:

[Nest] 7  - 12/17/2023, 10:57:37 PM    WARN [MetadataRepository] Response from database for reverse geocoding latitude: 49.0635888888889, longitude: -120.78605 was null
[Nest] 7  - 12/17/2023, 10:57:37 PM    WARN [MetadataRepository] Response from database for reverse geocoding latitude: 49.0639472222222, longitude: -120.786963888889 was null
[Nest] 7  - 12/17/2023, 11:00:53 PM    WARN [MetadataRepository] Response from database for reverse geocoding latitude: 49.0635305555556, longitude: -120.787122222222 was null
[Nest] 7  - 12/17/2023, 11:00:53 PM    WARN [MetadataRepository] Response from database for reverse geocoding latitude: 49.0634777777778, longitude: -120.791644444444 was null
[Nest] 7  - 12/17/2023, 11:00:54 PM    WARN [MetadataRepository] Response from database for reverse geocoding latitude: 49.0620583333333, longitude: -120.836644444444 was null
[Nest] 7  - 12/17/2023, 11:00:54 PM    WARN [MetadataRepository] Response from database for reverse geocoding latitude: 49.06015, longitude: -120.842733333333 was null
[Nest] 7  - 12/17/2023, 11:00:54 PM    WARN [MetadataRepository] Response from database for reverse geocoding latitude: 49.0613361111111, longitude: -120.855058333333 was null
[Nest] 7  - 12/17/2023, 11:00:54 PM    WARN [MetadataRepository] Response from database for reverse geocoding latitude: 49.0621666666667, longitude: -120.864147222222 was null
[Nest] 7  - 12/17/2023, 11:00:54 PM    WARN [MetadataRepository] Response from database for reverse geocoding latitude: 49.0625722222222, longitude: -120.866586111111 was null

### The OS that Immich Server is running on

Docker on Synology

### Version of Immich Server

1.91.3

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Reproduction steps

```bash
1. I installed new instance
2. I added external library
3. I started scan

I would gladly share the photo, so issue can be reproduce,
but unfortunately I can not see the filename of the photo in the log,
so I can't figure out which files has this issue
```

**Comment by zackpollard** [comment]
This is a symptom of the way we do reverse geocoding now within postgres. We limit the results to 25km, so if there is no place within 25km that has a population of > 500 people, we will get no results. We log this out for now due to it being an unexpected but not impossible scenario. This is probably something we will fix in later revisions of the reverse geocoding code, but for now it is expected behaviour.

**Comment by mschiff** [comment]
I am seeing lots of the same messages. But what does it mean? Will those coordinates be used for the map view or not?

Would it be possible to return the area/country/continent/ocean if no "Place" is found? I for example have many shots from ocean crossings which I would love to see at least in a category like "Pacific Ocean" or something.

TIA

**Comment by zackpollard** [comment]
We are currently looking into improvements to the reverse geocoding, there is an open PR to get at least the correct country even if the normal process doesn't find a place. Oceans however are entirely unsupported right now, but might come with some of the other improvements we are currently looking into.
