### ISSUE TITLE
[BUG] Cannot update the feature photo of a person

### ISSUE THREAD

**Issue by FabAlchemy** [immich-app/immich#5820]
### The bug

Changing the feature photo of a person only updates the preview page but the change is not committed.

### The OS that Immich Server is running on

NixOS 23.11

### Version of Immich Server

v1.91.3

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Default docker-compose.yml from the release
```

### Your .env content

```Shell
Default environment from the release
```

### Reproduction steps

```bash
1. In the People page, click on a person, then in the menu "Change the feature photo"
2. Select a different photo, the miniature is updated
3. Refresh the page, or go back to the People page: the feature photo has not changed
```

**Comment by deiop** [comment]
Can confirm bug. 
Nothing in the logs so far.

**Comment by alextran1502** [comment]
When you refresh the `People` page, does it change?

**Comment by FabAlchemy** [comment]
No I still get the previous feature photo.

**Comment by alextran1502** [comment]
Did you use Immich before the feature face mechanism was introduced? If yes, then you will have to run the recognize faces job for all again to get the coordinates of the faces registered in the database

**Comment by alextran1502** [comment]
The face's feature photo changes, but the cache hasn't refreshed. If you open the instance in incognito, you will see it changes. This is a bug regardless

**Comment by deiop** [comment]
Tried it with incognito - you are correct! Thank you!

**Comment by FabAlchemy** [comment]
This was fixed in https://github.com/immich-app/immich/pull/5824 and https://github.com/immich-app/immich/pull/5829, and in the 1.91.4 release. Thanks!
