### ISSUE TITLE
[BUG]Selecting Backup Albums keeps loading

### ISSUE THREAD

**Issue by wangl1987** [immich-app/immich#5826]
Some phones keep loading when you choose to back up your albums.
The images and log files are as follows
![IMG_8075](https://github.com/immich-app/immich/assets/150538734/4a6908bb-966f-441e-83bb-16a1c4534429)
[Immich_log_2023-12-18T213155.266182.csv](https://github.com/immich-app/immich/files/13705311/Immich_log_2023-12-18T21.31.55.266182.csv)

### The OS that Immich Server is running on

Installing through Docker Compose on Mac OS

### Version of Immich Server

1.91.3

### Version of Immich Mobile App

1.91.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
no changes
```

### Your .env content

```Shell
no changes
```

### Reproduction steps

```bash
1. I have two ios phones, both have the same app version and connect to the same server. phone A has 1000+ photos and phone B has 8000+ photos. Only phone B will have this problem.
2. The problem occurs when setting the access permission of immich photos to "all photos" on B phone. So I tried to set the access permission of immich photos to "selected photos", then manually select all photos in the album, then select backup album in the app can be displayed normally!
3. I'm still having this problem whether I choose to turn on the ignore icloud photos feature or not
4. After loading the backup albums via 2. I realized that the list of backup albums in immich doesn't match the list of albums in the phone, but matches the list of Media Types in the phone, and is missing the Screen Recordings.
```

**Comment by alextran1502** [comment]
This is a known issue on some phones, and we haven't found the cause yet. My guess is that on some phone, there are some ablums that prevent loading the list of album because if you change the permission to allow a certain album, then it will show up.

**Comment by wangl1987** [comment]
> 这是某些手机上的已知问题，我们尚未找到原因。我的猜测是，在某些手机上，有一些 ablums 会阻止加载专辑列表，因为如果您更改权限以允许某个专辑，那么它就会显示出来。
@alextran1502 
I have tried migrating photos from phone B to phone C via data migration, and I get the same problem on phone C. I'm guessing this could also be related to existing photos and albums
I can assist with some testing if needed and hopefully assist in locating the problem as soon as possible as he has been bothering me for a long time.
Thanks for the reply

**Comment by alextran1502** [comment]
@wangl1987 Thank you for the offer.

I think we can start with manually allowing individual album to be seen by the app and check if the album get loaded in the page. I think eventually we will pick an album that might cause an issue, then we can dive into which properties of the album that are different from others

**Comment by wangl1987** [comment]
Also, is it possible to align the list of albums selected for backup in immich with the list of albums in the phone, rather than with the media type? I'm not sure if this is a problem with my usage habits or not

**Comment by wangl1987** [comment]
@alextran1502 
I just tried assigning permissions to each album individually, and they all select to the backup album properly

**Comment by alextran1502** [comment]
Do you use Shared Album feature of iCloud?

**Comment by wangl1987** [comment]
@alextran1502 
No, I turned that off.
However, I have noticed that in my albums, there are some photos with a corrupted status, it's not quite clear how these corrupted photos were created, I'm trying to delete them and see what happens, but there are so many photos in the albums, it's not clear if there's anything I can do to filter out these photos

**Comment by wangl1987** [comment]
These corrupted photos will have an exclamation point with a circle in the bottom right corner, and it is not possible to upload these photos in immich when permissions have been assigned to these corrupted photos individually.
It's not clear if these photos are the cause.

**Comment by alextran1502** [comment]
@wangl1987 I believe there are cases of people having corrupted photos, but the albums are still loading. Do you mind taking a screenshot of how the corrupted photos get displayed?

**Comment by wangl1987** [comment]
@alextran1502 
Sorry I didn't respond in time after taking yesterday off.
corrupted photos look like this
Figure 1 is displayed when clicking on the exclamation mark in the lower right corner of the image
Figure 2 is displayed when clicking on the upper right corner to edit
I hope this helps some
![IMG_8096](https://github.com/immich-app/immich/assets/150538734/a05aa666-4ec5-44df-8c3d-a42a6eeb0d48)
![IMG_8097](https://github.com/immich-app/immich/assets/150538734/5bb2e43d-100b-45ca-9629-d7cfb64e51f5)
![IMG_8098](https://github.com/immich-app/immich/assets/150538734/5082c85c-9a40-41e4-8028-39a0020da8ce)

**Comment by wangl1987** [comment]
@alextran1502 
When I deleted all the corrupted photos from my cell phone album.
It's also normal now to assign access to all photos to immich.
It seems to be a problem with these corrupted photos, let me know if you need to provide any more info on this!

**Comment by Zosu** [comment]
I managed to get mine working (though it's still a little buggy. Somehow the backed up number is greater than the total). Ironically, after enabling iCloud Photos it was able to back up everything.

I noticed from experimenting with limited photo access with the app that it never loaded when I had certain slow motion videos selected. Maybe that is a factor?

**Comment by stephencarse** [comment]
I had this issue too, and just managed to resolve it by deleting a bunch of albums. I can't give better information than that unfortunately. I can see in the app logs that it had previously said "Found 52 local albums" and then got stuck after that. After deleting a bunch of albums, it now works. 
For what it's worth, I've had an issue with my iCloud recently, and sync wasn't working correctly, including album sync.

**Comment by ednzylmz** [comment]
A hacky solution, give immich limited access and choose everything in "recents" album. Use swipe action top left to bottom right to start scroll selecting, you can use other hand to scroll faster and select everything.

**Comment by adrian-fuertes** [comment]
I never got it to work... I now use PhotoSync and mount my library as an external library. It's been pretty smooth.

**Comment by keithellis74** [comment]
> A hacky solution, give immich limited access and choose everything in "recents" album. Use swipe action top left to bottom right to start scroll selecting, you can use other hand to scroll faster and select everything.

This worked for me in IOS 17.3.1 Immich; IOS App version 1.98.2 build 144 and Immich 1.98.2.

**Comment by alextran1502** [comment]
@sadorowo how many albums/assets do you have on your device?

**Comment by mradalbert** [comment]
I have seen this issue too many times. Now after android upgrade. This time after trying to reset app many times I'm still stuck. App and server on the latest (1.135)

**Comment by alextran1502** [comment]
@mradalbert can you try go to App Settings > Advanced > scroll to the bottom and enable use alternative album filter? See if the issue is fixed

**Comment by mradalbert** [comment]
@alextran1502 Yes, it fixed the issue. Wow! Thank you!

**Comment by sadorowo** [comment]
> [@mradalbert](https://github.com/mradalbert) can you try go to App Settings > Advanced > scroll to the bottom and enable use alternative album filter? See if the issue is fixed

This doesn't resolve the issue for me. After deleting all backed-up photos from my phone (I hope that we will have Clean space button in the future), the album list just keeps loading indefinitely. I think there should be a message like "No albums found". Additionally, when there are no albums, the Backup option is automatically disabled, which seems quite odd. I've encountered the same issue on my phone as well as on two other devices.
