### ISSUE TITLE
CLI retry failed request and don't cancel entire flow on error

### ISSUE THREAD

**Issue by zackpollard** [immich-app/immich#5839]
Currently the CLI will error and cancel the whole process if one request fails. We should probably instead retry a couple of times and then log an error that the asset failed, but continue on to other assets.

**Comment by masterT** [comment]
This is particularly annoying when uploading a lot of assets. Was there any progress toward this issue?

**Comment by masterT** [comment]
A significant improvement could be using an in-memory queue system (e.g., [fastq](https://www.npmjs.com/package/fastq)) and having the ability to retry not just failed asset uploads but also other parts of the CLI. 

I'm trying to upload an extensive library, and I have all kinds of network errors (I'm hosted with PikaPod, and my instance sometimes restarts, which makes the whole process crash).

I think I will craft a draft for this and open a PR.
