### ISSUE TITLE
[BUG] Selection menu not at correct height

### ISSUE THREAD

**Issue by RenautMestdagh** [immich-app/immich#5865]
### The bug

When selecting 1 or more pictures in the mobile app, the selection menu doesn't show at the correct height. Right now it still shows "Add to album" and the "+ Create new album" button. It shouldn't initially show the red part.

![Screenshot_2023-12-19-14-59-00-565_app alextran immich](https://github.com/immich-app/immich/assets/82072978/f247ab8c-5bcc-4583-a5d4-12ba1bd2370e)

### The OS that Immich Server is running on

demo server

### Version of Immich Server

v1.91.3

### Version of Immich Mobile App

v1.91.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
/
```

### Your .env content

```Shell
/
```

### Reproduction steps

```bash
1. Select a picture in the mobile app
```

**Comment by shenlong-tanwen** [comment]
Showing the add to album portion makes it easier for people to know that there is still content below and that the bottom sheet is draggable. Is there a reason to not show the area marked in red?

**Comment by RenautMestdagh** [comment]
I thought i'd be cleaner without it and didn't know it was intentional. It does indeed make it easier for people to know that there is still content below.
