### ISSUE TITLE
[BUG] pgvecto.rs version is pinned to 0.1.11

### ISSUE THREAD

**Issue by dereulenspiegel** [immich-app/immich#5911]
### The bug

I am trying to run immich with the timescaledb-ha image. This image now includes the pgvecto.rs extension, but unfortunately it only ships with 0.1.13 out of the box. Is there a reason to pin the extension to the patch version of the extension? Or could it make sense to pin to the minor version to avoid breakage?

Thanks in advance for any help and hints :) 

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

latest from Apple App Store

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I am not running in docker compose, but with podman based systemd units. If any details about mounts, environment variables etc. are relevant I am happy to provide these
```

### Your .env content

```Shell
Not using a `.env` since my containers are generated from systemd unit files.
```

### Reproduction steps

```bash
1. Setup a database based on `docker.io/timescale/timescaledb-ha:pg15-all` and start it with `-c shared_preload_libraries=vectors` to load the pgvector.rs extension.
2. Setup your immich database user and database as usual
3. Point immich-server and immich-microservices to the newly created database instance
```

### Additional information

For completeness, this is the error I received in the logs:
```
[Nest] 7  - 12/21/2023, 5:29:32 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: The pgvecto.rs extension version is 0.1.13 instead of the expected version 0.1.11.If you're using the 'latest' tag, please switch to 'tensorchord/pgvecto-rs:pg15-v0.1.11'.
    at assertVectors (/usr/src/app/dist/infra/database.config.js:61:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:11:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
  ```

**Comment by zackpollard** [comment]
Currently pgvecto.rs is in heavy development and is undergoing breaking changes in their releases, much like Immich. 0.1.12 for example will break Immich's usage of pgvecto.rs. They are planning to move to stable sometime in January we believe (0.2.x) and once they do, these breaking changes shouldn't be happening as much, but for now we need to pin to 0.1.11 until that happens and we make the necessary changes to update.

**Comment by acme64** [comment]
FYI 0.1.11 breaks synology support. If theres an easy way to change what version is pinned that'd be great, I can't get immich back up since the recent major changes
