### ISSUE TITLE
[BUG] Mobile: Wrong date sorting on metadata search result

### ISSUE THREAD

**Issue by MohamedFBoussaid** [immich-app/immich#5916]
### The bug

1.Click on the search button 
2.search any metadata using m:you-search-keyword
3.Check the date sorting (attached screenshoot in the additional information)

Results: 
The order is random 

Expected: 
The order should be the same as the other screens on the app. (From the newest to the oldest)

P.S: You can see this behaviour also by opening any place to see the assets. 

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.V

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1.Click on the search button 
2.search any metadata using m:you-search-keyword
3.Check the date sorting (attached screenshoot in the additional information)

Results: 
The order is random 

Expected: 
The order should be the same as the other screens on the app. (From the newest to the oldest)

P.S: You can see this behaviour also by opening any place to see the assets.
```

### Additional information

![WhatsApp Image 2023-12-21 at 23 13 08](https://github.com/immich-app/immich/assets/52571029/8c780886-6b03-4e75-b064-342b0aac381d)

**Comment by aisbergde** [comment]
I have the same issue in the android client.
