### ISSUE TITLE
[BUG] web: asset temporary hidden in the album after editing metadata

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#5948]
### The bug

When location, date or description is set manually in the asset viewer and then viewing is exited to the album, that asset is not visible within current album until album is reloaded.
In addition, it's not possible switch to previous or next asset using arrow keys or screen buttons in the asset viewer.

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

v.1.91.4

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. view an asset
2. set manually a location
3. exit viewer
4. asset not visible until album reload
```

**Comment by alextran1502** [comment]
So from an album, view then edit an asset, then that asset is removed from the view, correct?

**Comment by waclaw66** [comment]
> So from an album, view then edit an asset, then that asset is removed from the view, correct?

Right.

**Comment by waclaw66** [comment]
In addition, is't not possible switch to previous or next asset using arrow keys or screen buttons.

**Comment by waclaw66** [comment]
@YFrendo Can you please check this out? It's annoying bug while modifying assets within a large album. Thanks.

**Comment by YFrendo** [comment]
I will check this but I'm very busy curently!
