### ISSUE TITLE
[BUG] "undefined" in error message when error at uploading

### ISSUE THREAD

**Issue by RenautMestdagh** [immich-app/immich#5972]
### The bug

When trying to upload an image onto the demo server (Where uploading is disabled), the site gives an error notification. At the end of the notification it says "undefined"

![Screenshot 2023-12-25 234931](https://github.com/immich-app/immich/assets/82072978/0f79808a-e0ed-467b-ba32-761a62b3cddd)

### The OS that Immich Server is running on

demo server

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

/

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
/
```

### Your .env content

```Shell
/
```

### Reproduction steps

```bash
1. upload image onto demo server
2. look at error popup
```

**Comment by alextran1502** [comment]
We disable upload on the demo site due to abuse

**Comment by RenautMestdagh** [comment]
The bug is not that i'm not able to upload. The bug is in the error message it displays...
