### ISSUE TITLE
[BUG] Large MP4 Video Fails Repeatedly

### ISSUE THREAD

**Issue by godismyjudge95** [immich-app/immich#598]
**Describe the bug**
Backup keeps trying to upload a 700MB MP4 video recorded using the camera.
Resolution is 1920x1080, recorded on a Pixel 5a.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Record large video in MP4 format
2. Go to Immich app
3. Tap the backup icon in the top right
4. Tap the Select button next to Backup Albums
5. Select the folder where the recorded video is stored
6. Tap the back button
7. Tap the Turn on Backup button
8. Tap the Turn on background service button
9. Tap the Start backup button at the bottom
10. Keep phone await by tapping/scrolling every once in awhile

**Expected behavior**
Video will completely upload and the backup service will move on to the next item.

**Actual behavior**
Video upload will make it to a certain percentage and restart.  This will continue to happen repeatedly unless the backup process is stopped.

**System**
- Phone OS [iOS, Android]: `Android 13`
- Server Version: `1.27.0`
- Mobile App Version: `1.27.0 build.37`

**Additional context**
Using the latest docker compose file.
No .env file or special variables.

Might be unrelated but when I updated to 1.27 it seems that now the whole backup process restarts when the phone goes to sleep.
It might say Total = 106, Backup = 5,, Remainder = 101 and then the phone goes to sleep - after waking the app counters reset to Total = 106, Backup = 0, Remainder = 106.  Let me know if I need to open a new issue for that particular issue if it is unrelated.

**Comment by alextran1502** [comment]
Are you using your own reverse proxy? Please check if it has size limitation

**Comment by godismyjudge95** [comment]
@alextran1502 ah yes, I forgot to mention that I am using nginx in front.

Would nginx only require a change to `client_max_body_size` or is there another config value I should be setting with that?

**Comment by alextran1502** [comment]
Should be that parameter only :)

**Comment by godismyjudge95** [comment]
Ok trying it out now.  Any ideas as to why the backup counter is resetting when the phone goes to sleep?  Atm to keep it uploading I set my phone sleep timer to 30min and it seems to work fine then.

**Comment by alextran1502** [comment]
I am not sure, it might be a bug

**Comment by godismyjudge95** [comment]
Ok, would you rather me submit a separate issue for that in particular.  I think the nginx config was the issue for the large video upload.

I could also submit a pull request to add a note about that in the README docs (under installation?)

**Comment by alextran1502** [comment]
Yes please, can you help me open a new issue with the additional information to reproduce it. 

Your contribution is welcomed for the Nginx setting

Thanks

**Comment by godismyjudge95** [comment]
Closing issue as it was caused by an NGINX reverse proxy misconfiguration - submitted pull request https://github.com/immich-app/immich/pull/599 to clarify this when setting up Immich.
