### ISSUE TITLE
[BUG] Search by `m:filename` returns nothing

### ISSUE THREAD

**Issue by chengguangnan** [immich-app/immich#5982]
### The bug

Search by m:filename returns nothing.

### The OS that Immich Server is running on

ubuntu 22.04

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

irrelevant

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
I could not find any file using the `m:(filename)` syntax. Meanwhile `m:(city)` or `m:(camera)` works fine. 

I could verify this issue on the demo site that query [m:Russet_potato_cultivar_with_sprouts.jpg](m:Russet_potato_cultivar_with_sprouts.jpg) returns no results. The filename that I intend to search are like `IMG_0001.mov`.
```

**Comment by alextran1502** [comment]
This is currently removed with the  removal of Typesense
