### ISSUE TITLE
[BUG] Cannot unhide a face when People library is too big

### ISSUE THREAD

**Issue by diyoyo** [immich-app/immich#6011]
### The bug

Even the named People are not showing up in the Hide/Unhide list when trying to unhide a named Person.
This suggests that in addition to the current limitation of max 500 people displayed (which should be fixed, right?), the sorting is not correct when Hide/Unhide is selected.
In my opinion, and as seen in the other Photo apps, when you are about to unhide people, the sorting should be the following:
- Named People first
- Within each category (named vs. not named), order by pic number DESC

### The OS that Immich Server is running on

Debian (Raspberry OS Full, latest) latest

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.1

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
unchanged
```

### Your .env content

```Shell
unchanged
```

### Reproduction steps

```bash
Currently, with the following specs:
- Visible: 480 named people and 20 unnamed
- Hidden: probably more than 200 named people, many more unnamed

With this config, I cannot unhide anyone except, sometimes, the latest persons that I hid in the last 30 min.
```

### Additional information

Maybe this will be fixed with the 500person limitation issue, but I think it is yet another issue.

**Comment by IIIDPGIII** [comment]
Faces that only appear once should be hidden to remove excess from the UI.

**Comment by BlueWolfProduction** [comment]
> Faces that only appear once should be hidden to remove excess from the UI.

This is already possible! In System Settings -> Machine Learning Settings -> Facial Recognition -> "MIN FACES DETECTED". It lets you set the minimum amount of detected photos a face is in, before it starts showing that face on the people tab.

**Comment by IIIDPGIII** [comment]
Thank you!

**Comment by diyoyo** [comment]
Do we agree this is a different problem?

**Comment by alternativesurfer** [comment]
This is a different problem, yes.

When there are too many faces listed, "Hidden" faces no longer appear if you click the show/hide faces button.
I cannot unhide any faces as a result.

**Comment by diyoyo** [comment]
> This is a different problem, yes.
> 
> When there are too many faces listed, "Hidden" faces no longer appear if you click the show/hide faces button. I cannot unhide any faces as a result.

Thanks for refreshing this topic. I thought I had read the the problem had been solved, but I'm still waiting. I'm also waiting to be able to display more than 500.

**Comment by alternativesurfer** [comment]
Truly. Im old AF. I have TONS of matches faces for people I know.
Way more than 500.

**Comment by acbaldwi** [comment]
I too appear to have this issue, i cannto unhide or see people i hid now

**Comment by shumafuk** [comment]
I have same issue. I have over 3000 faces detected, for sure I will not name all of them, but 500 is not enough. Also, as mentioned above, I cannot show previously hidden faces. I made few mistakes in organization and now recognition for some faces is gone and I cannot set up to recognize them again because they not appear in list of "Show & hide people".

**Comment by chodthewacko** [comment]
> I have same issue. I have over 3000 faces detected, for sure I will not name all of them, but 500 is not enough. Also, as mentioned above, I cannot show previously hidden faces. I made few mistakes in organization and now recognition for some faces is gone and I cannot set up to recognize them again because they not appear in list of "Show & hide people".

This doesn't entirely fix your problem but it's  a slight (but kludgy) workaround.
If you accidentally hide a person and want to find that person, try to think of a picture where they appear together.  In that picture, you can show the people in that picture who are hidden, and then you can click on that person and unhide them.
It's only a minor workaround because sometimes a person is only recognized in a handful of pictures (and you have to merge them)

**Comment by DMcWetty** [comment]
Going to add my hope for a broader face list. I accidentally hid a face that belonged to my son's friend and now I can't recover it. I've hidden thousands of faces...

Perhaps a solution is to a system wide toggle that shows the white boxes on found faces in the photos themselves? Then after faces are labeled and hidden, turn the toggle off?

**Comment by chodthewacko** [comment]
> Going to add my hope for a broader face list. I accidentally hid a face that belonged to my son's friend and now I can't recover it. I've hidden thousands of faces...
> 
> Perhaps a solution is to a system wide toggle that shows the white boxes on found faces in the photos themselves? Then after faces are labeled and hidden, turn the toggle off?

I think you're 90% there - if you have a picture with your son's friend you can 'view hidden faces' and then unhide the person.
I've also opened a request to allow 'search name' optionally show hidden people.   You have to work around the 20 person limit on searches though.

**Comment by DMcWetty** [comment]
> > Going to add my hope for a broader face list. I accidentally hid a face that belonged to my son's friend and now I can't recover it. I've hidden thousands of faces...
> > Perhaps a solution is to a system wide toggle that shows the white boxes on found faces in the photos themselves? Then after faces are labeled and hidden, turn the toggle off?
> 
> I think you're 90% there - if you have a picture with your son's friend you can 'view hidden faces' and then unhide the person. I've also opened a request to allow 'search name' optionally show hidden people. You have to work around the 20 person limit on searches though.

Appreciate the response. I was trying to name the face when I hit hide person instead, so unfortunately I can't search them up either. Hopefully the people search and hiding function get a little love in the next release.

**Comment by alternativesurfer** [comment]
Any progress on this?

**Comment by alextran1502** [comment]
The people page can now load all people, including hidden people

**Comment by chodthewacko** [comment]
> The people page can now load all people, including hidden people

For clarity, what is the step to view hidden people?
Is it going to be the same i.e.  explore -> view all    = show all unhidden people, named people first
          then what, a toggle to include hidden people?
