### ISSUE TITLE
[Feature]: data for server/db saved as file within backup folder for easy secondary backup and redundancy. 

### ISSUE THREAD

**Issue by EnderPicture** [immich-app/immich#602]
### Feature detail

Hi,

It would be great if all files related to the server and its database could be saved as files within the chosen backup folder for easy migration to another server, backup, and replication.

The idea is that, by backing up the backup folder to any other location (another drive, offsite drive, or cloud storage), one can just restore the one folder, point docker to the folder, and everything will be restored, back and running.

Great work as always,
Thanks!

### Platform

Server

**Comment by bo0tzz** [comment]
The database folder is currently mounted to a docker volume, but you are free to mount it to a path instead so you can easily back it up.

**Comment by zackpollard** [comment]
Backup solutions exist to backup postgres as well individual files and folders on a filesystem remotely, as no one part of the immich system has access to all the locations files are stored (db files, data, etc) then this isn't really feasible to do anyway. I would look into implementing an existing backup solution for this, I don't think this is within the scope of Immich itself.
