### ISSUE TITLE
mobile - error on nearly all searches

### ISSUE THREAD

**Issue by aisbergde** [immich-app/immich#6032]
### The bug

The only items I can search for are geo locations. all other searches result in different error messages .

![Screenshot_2023-12-28-05-56-00-737_app alextran immich](https://github.com/immich-app/immich/assets/9020187/041a0b87-829a-4752-97f8-4ecbf679d6fd)
![Screenshot_2023-12-28-05-55-44-559_app alextran immich](https://github.com/immich-app/immich/assets/9020187/3ef7e013-0b18-47ac-bfbd-41e65464d033)
![Screenshot_2023-12-28-05-55-37-000_app alextran immich](https://github.com/immich-app/immich/assets/9020187/a3476765-64ca-47fd-a0b3-a4aa865b4c46)
![Screenshot_2023-12-28-05-55-28-076_app alextran immich](https://github.com/immich-app/immich/assets/9020187/dcd61895-39cb-4f8c-a01d-d0e791bb61d4)
![Screenshot_2023-12-28-05-55-18-523_app alextran immich](https://github.com/immich-app/immich/assets/9020187/88095160-b1d7-416f-b183-c25be33146df)

### The OS that Immich Server is running on

docker in synology containers

### Version of Immich Server

1.91.4

### Version of Immich Mobile App

1.91.4

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I have no access from my smartphone
```

### Your .env content

```Shell
I have no access from my smartphone
```

### Reproduction steps

```bash
1. use different searches, see screenshots
2.
3.
...
```

**Comment by alextran1502** [comment]
duplicated #5783
