### ISSUE TITLE
[BUG] <title> Setup with NGINX Proxy Manager

### ISSUE THREAD

**Issue by PrieserMax** [immich-app/immich#6038]
### The bug

EDIT: Got it working
Normally create a proxy host.
Add the following custom config:
proxy_request_buffering off;
proxy_buffering off; 
client_max_body_size 100000m;

Here you have to enter the config:
![Unbenannt](https://github.com/immich-app/immich/assets/96659068/c6031279-2fdc-4a9e-aeb8-e0164367a25a)

From my understanding it disables buffering to the Nginx Proxy and directly sends it to the corresponding host.
The 100000m is the size limit in megabyte.

### The OS that Immich Server is running on

Ubuntu Server 22.04.3 LTS

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

latest

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Default
```

### Your .env content

```Shell
Default
```

### Reproduction steps

```bash
1.Setup new Proxy host in Nginx Proxy Manager
2.
3.
...
```

**Comment by Nickfost** [comment]
This helped me. 

I think the proxy buffering was preventing my large videos from getting uploaded even when I had the max size very high 


It would be nice to see more detailed doc pages for others to set up the nginxproxymanager config in the future

@alextran1502

**Comment by PrieserMax** [comment]
> This helped me.
> 
> I think the proxy buffering was preventing my large videos from getting uploaded even when I had the max size very high
> 
> It would be nice to see more detailed doc pages for others to set up the nginxproxymanager config in the future
> 
> [@alextran1502](https://github.com/alextran1502)

Glad to hear that.

I changed one thing later and just edited it.

The Max Body Size to 0 equals no limit.
