### ISSUE TITLE
[BUG] Preview Pictures are Black and White

### ISSUE THREAD

**Issue by aschrafl** [immich-app/immich#6046]
### The bug

In both Web and Mobile view (mobile only on very few, web consistently since a couple of versions), preview pictures are black and white. When I zoom into the picture (select and then on the magnifying tool), a normal color variant is shown and then stays in the single picture via. The thumbnail gallery view still stays black and white.
If I download the pictures they are colored too.
This appeared a couple of versions ago (not sure when) and prevails up to the current version.
I've tried with different browsers (Firefox and Chrome) and have toggled light and dark themes. 

### The OS that Immich Server is running on

ArchLinux

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4 build.116

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
using ArchLinux package
```

### Your .env content

```Shell
using ArchLinux package
```

### Reproduction steps

```bash
1. Look at server.domain:port/photos
2. Thumbnails are black and white
3. Click on a picture
4. Picture is black and white
5. Click on magnifying tool (zoom in)
6. Colored picture appears
7. Click on magnifying tool (zoom out)
8. Colored picture stays
```

### Additional information

Tried different browsers (Firefox and Chrome)

**Comment by martabal** [comment]
Sounds like it's an issue with Immich dependencies. What libvips version are you using ?

**Comment by alextran1502** [comment]
Can you try the supported installation method to see if it makes the different. We are not the maintainer of Archlinux package

**Comment by aschrafl** [comment]
> Sounds like it's an issue with Immich dependencies. What libvips version are you using ?
libvips: 8.15.0-1

**Comment by mertalev** [comment]
This isn't an Immich issue, but an issue with bare-metal installation. We can't provide support for issues stemming from dependencies in the system environment. I recommend using a supported installation method.
