### ISSUE TITLE
[BUG] web: search crashes when machine learning disabled

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#6056]
### The bug

When machine learning is disabled Immich shouldn't show message like below.
Instead of that album name search and file name search should still work.
Btw. album search doesn't work even when machine learning is enabled.

![obrazek](https://github.com/immich-app/immich/assets/15554561/41722aba-9e36-4997-a90d-60c3bd6ef963)

```
pro 30 00:53:07 server immich-server-dev[1925230]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)] Error: CLIP is not enabled
pro 30 00:56:58 server immich-server-dev[1925230]: [Nest] 1925230  - 30. 12. 2023 0:56:58   ERROR [Error: CLIP is not enabled
pro 30 00:56:58 server immich-server-dev[1925230]:     at SearchService.search (/opt/immich/server/src/domain/search/search.service.ts:64:13)
pro 30 00:56:58 server immich-server-dev[1925230]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)] Failed to search
```

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. disable machine learning
2. search something
3. crash
```

**Comment by aviv926** [comment]
I think that as of now it is not possible to search for albums or file names after the removal of Typesense,
but this is something that will return in the future.

**Comment by jrasm91** [comment]
This should have been addressed with recent search enhancements.
