### ISSUE TITLE
[BUG] Cannot select multiple photos in search result (mobile app)

### ISSUE THREAD

**Issue by tbleiker** [immich-app/immich#6062]
### The bug

With the mobile app, I cannot select multiple photos in a search result (e.g. to add them to an album). This holds for:
- Searching for a certain term (e.g. "mountains"
- Showing the pictures of a person

### The OS that Immich Server is running on

Docker on Debian

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Search for photos (e.g. "mountains") or show the photos from a person
2. Long press a photo
3. Multi-select gets not activated
```

**Comment by aviv926** [comment]
I don't think this is a bug, more like a feature request.
It's just not possible to do it right now through the app.

**Comment by patienttruth** [comment]
I noticed the same thing today on the web interface. It works great on the main screen, and would be awesome to take that same UX and bring it to search.

**Comment by patienttruth** [comment]
Looks like a similar feature request has been made:
https://github.com/immich-app/immich/issues/1882#issue-1600153674

**Comment by bo0tzz** [comment]
This should work in the app now

**Comment by tbleiker** [comment]
It does! Thx!

**Comment by patienttruth** [comment]
> This should work in the app now

Y'all are awesome. Works great. Thank you!
