### ISSUE TITLE
[BUG] Photos disappear from timeline after date change

### ISSUE THREAD

**Issue by aviv926** [immich-app/immich#6070]
### The bug

When you change the date of a picture to a future date it just disappears until the date arrives

If you change the date to 01.02.2024 the image will not appear until the date arrives

### The OS that Immich Server is running on

Demo

### Version of Immich Server

last

### Version of Immich Mobile App

last

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Demo
```

### Your .env content

```Shell
Demo
```

### Reproduction steps

```bash
Don't do this to your photos, your photos will disappear!
Do it in a development environment.

1.Select an image or multiple images
2.Change their date through the UI to a future date
3.Refresh the page and you will find that the images no longer exist
...
```

**Comment by alextran1502** [comment]
This is the expected behavior on the web, the web currently doesn't show dates in the future.

**Comment by aviv926** [comment]
> This is the expected behavior on the web, the web currently doesn't show dates in the future.

I agree that it is not common, it happened to me because the Bios clock showed a future date and so did the server.
Until I noticed I wasn't on the right date, it didn't show me my photos.
