### ISSUE TITLE
[BUG] search tab crashing android app (Flutter issue)

### ISSUE THREAD

**Issue by Eidenz** [immich-app/immich#608]
**Describe the bug**
As mentioned on the Discord, opening the search tab on both my Pixel 6 And Mi 11 (A13 & A12), instantly crashes the app.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [X] I have read thoroughly the README setup and installation instructions.
- ~~[ ] I have included my `docker-compose` file.~~
- ~~[ ] I have included my redacted `.env` file.~~
- [X] I have included information on my machine, and environment.

**To Reproduce**
1. Open the search tab on specific android version/OS ?

**Expected behavior**
Search tab opens without issue.

**System**
- Phone OS [iOS, Android]: `Android 12 and 13`
- Server Version: `v1.27.0`
- Mobile App Version: `1.26.0 build.36`

**Additional context**
[Flutter issue mentioned on stackoverflow with eventual fix](https://stackoverflow.com/questions/73154833/native-crash-of-my-app-on-google-play-console-pre-launch-report-details)
![immich-crash log](https://user-images.githubusercontent.com/27901016/188861590-88925982-487d-412f-bbfc-c477198b10da.png)

**Comment by akoyaxd** [comment]
Do you already have any assets uploaded?

**Comment by Eidenz** [comment]
Yes, but we've already discussed the problem with Alex, he asked me to open an issue to avoid forgetting about it.
We concluded on a Flutter issue reading the logcat, there will be a fix attempt soon enough.
