### ISSUE TITLE
[BUG] UNTRACKS FILES

### ISSUE THREAD

**Issue by LovelyCatEx** [immich-app/immich#6086]
### The bug

I just uploaded two photos to my new installed immich, but there got 2 untracted files
![20240101134736](https://github.com/immich-app/immich/assets/42237679/bbb388b2-01c8-4e1d-beeb-ef81e2270570)

the file path: `/usr/src/app/upload/encoded-video/admin/2023/12/...`

Are these cache files that are not used after uploading? If I continue to upload images, these files will still exist and use additional storage.

### The OS that Immich Server is running on

truenas23.10

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.0.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
truenas scale community default
```

### Your .env content

```Shell
nop
```

### Reproduction steps

```bash
1. Upload images
```

**Comment by alextran1502** [comment]
Probably fix in #5917

**Comment by LovelyCatEx** [comment]
> Probably fix in #5917
