### ISSUE TITLE
[BUG] Uploading directly to album spams notification feed

### ISSUE THREAD

**Issue by aviv926** [immich-app/immich#6102]
### The bug

When uploading a lot of new photos to an **album** this causes many messages to appear one above the other. We should instead suppress these messages in this scenario, either adding a single notification once uploading is complete or just not having any notification at all.

![image](https://github.com/immich-app/immich/assets/51673860/0c0e12a9-74b3-4920-bf88-9bc667e0685a)

### The OS that Immich Server is running on

Win 10 with Docker

### Version of Immich Server

last

### Version of Immich Mobile App

null

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
1. Create a new album
2. Upload +50 photos
3. Try accessing the upload control panel
```

### Additional information

**Tested on several browsers:**
- Google Chrome
- Edge
- Firefox

**Comment by jrasm91** [comment]
Fixed in #10717
