### ISSUE TITLE
Can’t share the album on iOS 

### ISSUE THREAD

**Issue by NaroisCool** [immich-app/immich#6125]
### The bug

This is the log on mobile![IMG_7662](https://github.com/immich-app/immich/assets/28473070/8d12494b-8a22-46ad-8ad5-109793354ead)
This is the bug screenshot ![IMG_7663](https://github.com/immich-app/immich/assets/28473070/4b86d962-17d0-4bd0-be9a-ec23a6f0106a)

### The OS that Immich Server is running on

Ubuntu22

### Version of Immich Server

1.91.4

### Version of Immich Mobile App

1.87.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
The same as the readme
```

### Your .env content

```Shell
The same as the readme
```

### Reproduction steps

```bash
1.Share menu >
2. Create share album >
3. Share the album >
```

**Comment by alextran1502** [comment]
Your mobile app is out of date. Please make sure to be on the same version with the server
