### ISSUE TITLE
[BUG] incomplete search result, different results for the same search with "m:..."

### ISSUE THREAD

**Issue by aisbergde** [immich-app/immich#6128]
### The bug

using the metadata search, I want to get the same results every time and I want to get a complete result set. Currently, I get different results on every search and the set is never complete. For example, my data has GPS and reverse geocoding also works.

For example, I search
`m:Yaroslavl Oblast`
the map shows a bubble with 644. This looks correct. But the search shows randomly a subset of these assets. Maybe there is a hard coded limit?

### The OS that Immich Server is running on

docker in synology containers

### Version of Immich Server

1.91.4

### Version of Immich Mobile App

1.91.4

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by bo0tzz** [comment]
The search is currently a bit haphazard and incomplete since we recently completed a big refactor of the search backend. It'll get improvements soon.

**Comment by aisbergde** [comment]
But if you close the issue, and people are searching open issues, then how to find, if it is closed? 
Why not to close issues, when they are solved? Otherwise, a next user could open a similar issue.

**Comment by bo0tzz** [comment]
There are already many open issues/discussions for the search improvements.
