### ISSUE TITLE
Automatically clean up removed sidecar files

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#6169]
Immich supports adding and editing .XMP sidecar files in the library folder, and has a few jobs to discover and sync those. However deleting those files externally is currently not supported, as once a sidecar path has been added to the database, it is expected to stay on the filesystem as well. The [sidecar discovery job](https://github.com/immich-app/immich/blob/main/server/src/domain/metadata/metadata.service.ts#L283-L298) should be updated so that when a `sidecarPath` exists in the database but not on disk, the path in the database is nulled out.

**Comment by JW-CH** [comment]
I'd love to take this issue.
