### ISSUE TITLE
[BUG] AndroidApp: German language missing text for interface

### ISSUE THREAD

**Issue by Ettebumms** [immich-app/immich#619]
The Android App (Playstore) is missing important text for buttons sliders and infotext in the settings in the german version. 
Many buttons are empty, settings have no text and appears as huge empty blocks without information with sliders in it, also without text or any indication what they are for.

I can not tell if i can change the language setting because most of the text is missing. Please add the missing localisation text in the german version or just set it to english.

**System**
- Phone OS [Android]: 11
- Mobile App Version: 1.27.0

**Comment by bo0tzz** [comment]
This is a known issue, we are already looking into it.

**Comment by bo0tzz** [comment]
This is solved by #620 and #622. A new app release will be pushed out soon.
