### ISSUE TITLE
[BUG] migration wizard moves only assets, not related sidecar files

### ISSUE THREAD

**Issue by aisbergde** [immich-app/immich#6193]
### The bug

I changed the template and used the migration wizard.
The library contained assets and sidecar files per asset.
the wizard moved only the assets but not the sidecar files. sidecare files (*.xmp) are still in the old folders. Now the assets lost their connection to sidecar files.

=> migration of asset location should also move related sidecar files to the new location

To avoid discussion about bug vs feature:
I think, it is bug, because assets should not lost the connection with their sidecar files, when a software is used for migration. At least a big warning should be in the GUI, that the connection could be lost, if the migration wizard is used. But there is only a Start button.

### The OS that Immich Server is running on

docker in synology

### Version of Immich Server

1.91.4

### Version of Immich Mobile App

1.91.4

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by jrasm91** [comment]
This has been fixed.
