### ISSUE TITLE
[BUG] Live photos from shared albums in Google Takeout not getting grouped

### ISSUE THREAD

**Issue by GameKing505** [immich-app/immich#6201]
### The bug

I make use of live photos, which Google Photos seems to handle OK. I used immich-go to import my Google Photos library, and it seems that live photos get broken up into an individual image file (.HEIC or JPEG) and a video file (.mp4 or .mov).

For photos that I have taken **myself**, Immich is able to group these 2 files together in the interface and I get 1 tile, with a still photo and the ability to click the little play button to view the video component. This is the desired behavior.

For photos that have been **shared with me through shared Google albums**, Immich displays the image file as separate from the video file. Further, many of the video files appear in the wrong place in the timeline. When I run exiftools on these orphaned video files, I can see that the "Media Create Date" is 0000:00:00 00:00:00, and I assume that Immich's logic for grouping live photos with their video component relies on some sort of timestamp, so perhaps that is causing the issue. This is a bit of a pain, as many of my photos have been shared with me by my wife, resulting in scattered video files inserted at incorrect points in my Immich timeline.

Is there any way to manually tell Immich that 2 files (image and video) should be viewed as one live photo? Or alternatively, any way to alter the exif data for the video files to properly reflect the same timestamp as the photo?

[...originally this was a reddit thread](https://www.reddit.com/r/immich/comments/18zf4z2/live_photo_woes_when_importing_from_google_photos/) but I was advised to open a github issue

### The OS that Immich Server is running on

unRAID

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A - using unRAID docker implementation
```

### Your .env content

```Shell
N/A - using unRAID docker implementation
```

### Reproduction steps

```bash
1.Import photos with Immich-Go from google takeout archive
2.Observe that live photos are handled correctly, if I have taken them
3.Observe that live photos are split into separate video/photo files in the Immich timeline, if they happen to have been shared with me via a Google Photos shared album.
...
```

### Additional information

I'm truly sorry I can't provide the yml and env files but I'm using unRAID and not docker-compose.

**Comment by GameKing505** [comment]
If helpful, I've attached an example of a live photo that gets split up into photo/video with different dates in  the immich timeline.

https://github.com/simulot/immich-go/assets/58752730/95500f39-e4f8-4a1c-bab4-bdc7f71663e9

![IMG_2237](https://github.com/simulot/immich-go/assets/58752730/870aa4c2-bbe6-457f-9076-8582d09213de)

**Comment by gtsteffaniak** [comment]
This also happens for me. However the behavior seems to be different since starting fresh and upgrading to 1.93.3. 

> NOTE: I am using external library feature for these files

Previously my video and photos would be separate -- the live photo merge wouldn't work at all and it would just be photo with the video right next to it.

Now, the live photo DOES show up! However, the video still shows up right next to the live photo , making it look like a duplicate.

I think the database is handling the video with two separate operations : 

1. the photo gets handled and the live photo is found and attached.
2. the video file is seen as a standalone video and processed independently.

see two examples.
![image](https://github.com/immich-app/immich/assets/42989099/319029bb-ac6a-416b-9e3d-c6cbda627252)

**Comment by krypton9208** [comment]
I have same issue, not in 100%, but some photos have are sepereate from movie, and i web (and in ios) you can see 5-6 elements instead of 3 live photos...

**Comment by jrasm91** [comment]
immich-go now matches by file name and will automatically link associated assets. Without other metadata there is not much that can be done. In #12514 I have added the option to manually link live photos through the web ui, so I'm going to go ahead and close this as completed.

**Comment by HumperE3** [comment]
> > immich-go now matches by file name and will automatically link associated assets.
> 
> Is this no longer the case? I've opened a separate issue, but it was marked closed, saying it's an issue with Google Takeout or Immich-Go.

Any updates, having the same issue?
