### ISSUE TITLE
[BUG] Android: trash confirmation dialog ignores user choice

### ISSUE THREAD

**Issue by simon-lorenz** [immich-app/immich#6211]
### The bug

When I delete an image in the android app, a dialog asks for confirmation whether immich should really move this asset into the trash. 

However, it does not matter which option I choose. The asset gets trashed every time.

### The OS that Immich Server is running on

Ubuntu 22.04 with k3s

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4 build 116

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Delete an image
2. Try to cancel the deletion when asked for confirmation
3. The asset gets trashed anyway
```

**Comment by rastographics** [comment]
I noticed this same issue on my android

**Comment by shenlong-tanwen** [comment]
I guess the confusion here is that the Trash confirmation dialog displayed is actually the one from the OS and not from Immich. Immich never requests for confirmation before trashing an asset currently. So once you hit the delete button, the asset will be trashed if it is a remote only asset. But if the asset is available locally as well, the OS prompt is displayed to trash the local file as well. Even if you hit deny, the asset in Immich will be moved to trash but the local file will be left as it is
