### ISSUE TITLE
[BUG] Translate "Backup options"

### ISSUE THREAD

**Issue by HarHarLinks** [immich-app/immich#6227]
### The bug

The title of the settings page "Backup options" is not translated
https://github.com/immich-app/immich/blob/8c784defa0a3e92655a6cb728d52099ca09135d6/mobile/lib/modules/backup/views/backup_options_page.dart#L488

### The OS that Immich Server is running on

-

### Version of Immich Server

-

### Version of Immich Mobile App

v1.91.4

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
go to backup options
```

**Comment by jrasm91** [comment]
I believe this has been translated now.
