### ISSUE TITLE
[Bug] Drag&Drop Breaks when opening the asset info

### ISSUE THREAD

**Issue by badbreze** [immich-app/immich#630]
![Screenshot_2022-09-07-20-29-35-05_d8aea95ef633eb6b7eb1cae13c34b40e](https://user-images.githubusercontent.com/4717061/188952641-cbc044ec-a80b-4598-a41a-91a513449ce2.jpg)
as you can see in the screenshot, when you drag the pic to expand the info panel, the dragged image is keeping the last drag position instead of getting back to the center.
i dont have the know how to fix this so i hope someone can fix this!

Device: Oneplus 8t
OS: Android 12
App v: 1.27.0

_Originally posted by @badbreze in https://github.com/immich-app/immich/discussions/617_

**Comment by alextran1502** [comment]
Group together with issue #638
