### ISSUE TITLE
[BUG] Pinch to zoom always zooms to center of photo

### ISSUE THREAD

**Issue by meichthys** [immich-app/immich#636]
**Describe the bug**
On Mobile, pinch to zoom always zooms toward the center of the photo regardless of where the 'pinch' happens.

**Task List**

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Open photo on mobile app
2. Pinch to zoom

**Expected behavior**
Zoom should focus on the part of the photo where the 'pinch' happened.

**Screenshots**
![image](https://user-images.githubusercontent.com/10717998/189110052-c0c4aab8-e361-42f6-80e2-9cbe612a3b47.jpeg)

**System**
- Phone OS [iOS, Android]: `iOS 15`
- Server Version: `1.28.0`
- Mobile App Version: `1.28.0 build55`

**Comment by alextran1502** [comment]
We are aware of the weird touch behavior on mobile app. Thank you for reporting

**Comment by alextran1502** [comment]
Should be fixed. Please feel free to reopen otherwise
