### ISSUE TITLE
[BUG] Merging one unnamed face with one named face should choose the named faces name

### ISSUE THREAD

**Issue by jhbruhn** [immich-app/immich#6382]
### The bug

When merging faces directly from an unnamed faces context menu in the face selection overview, and then choosing to merge with an already existing, named faced, the resulting face is an unnamed face. This is not what I expected, as I would expect the named faces name to be chosen.

### The OS that Immich Server is running on

Docker on Synology NAS

### Version of Immich Server

1.92.1

### Version of Immich Mobile App

?

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default docker compose
```

### Your .env content

```Shell
default env
```

### Reproduction steps

```bash
1. Have a named face
2. Have an unnamed face
3. Go to face overview
4. Click on unnamed faces context menu and choose "Merge face"
5. Chose your previously created unnamed face
6. The resulting face is an unnamed face
```

**Comment by AngelPone** [comment]
Actually, there is a switch you can use to merge the unnamed face to a named face

![CleanShot 2024-01-15 at 12 51 28](https://github.com/immich-app/immich/assets/32930283/845edb82-36e6-465c-a895-788a7698270d)

**Comment by jrasm91** [comment]
The name is now kept on merge.
