### ISSUE TITLE
[BUG] Cannot Archive from Album

### ISSUE THREAD

**Issue by andriykrefer** [immich-app/immich#6389]
### The bug

- Open an Album
- Try to Archive one / multiple photos
- Nothing happens (they are not archived)
- Try to archive the same items from the "timeline" view. It works.

Same behavior for Web and App

### The OS that Immich Server is running on

?

### Version of Immich Server

v1.92.0

### Version of Immich Mobile App

v1.92.0 build 117

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Cant tell, running from a managed service (pikapods.com)
```

### Your .env content

```Shell
Cant tell, running from a managed service (pikapods.com)
```

### Reproduction steps

```bash
In the description
```

**Comment by l0nax** [comment]
The archive operation does work, but elements added to an album are always shown – even when archived.

**Comment by andriykrefer** [comment]
I do not think that is the case, they do not appear in the Archive

**Comment by RavidYael** [comment]
@andriykrefer I've attempted to reproduce the bug reported- but did not encounter any issues. I followed the steps described, but everything worked as expected on my end.

**Comment by figadore** [comment]
> @andriykrefer I've attempted to reproduce the bug reported using immich-server v1.95.0 and did not encounter any issues.

I'm having the same problem. Maybe you can reproduce it under the following circumstances: Assets belong to account-1 and are shared with account-2. Album is created by account-2. Options for items in the album for account-2 are only "share", "select all", "add", "download" and "remove from album". Archiving is attempted from the main album view, not an individual photo (where, btw, the options are inconsistently only "copy" and "download")

@andriykrefer does this match what you're seeing? If not, can you provide more details for reproduction?

**Comment by alextran1502** [comment]
Fixed, the assets can now be archived in Album and will have the archive icon visible
