### ISSUE TITLE
[BUG] Facial Recognition bug with babies / kids

### ISSUE THREAD

**Issue by GregTroar** [immich-app/immich#6441]
### The bug

Hi,

I have two kids close in age (5 years old and 4 years old).
I have a lot of pictures of them as babies and I am facing an issue where both of them are recognized as one.

So in a picture where I have both of them only one of them is recognized and when I do an on mouse over the kid who is recognized I have the small white square around both of my kids.

Clearly both my kids are recognized as one but this should be impossible for Immich to tag 2 persons in a picture as one person only.

The problem is I cannot correct this manually at all. Is there a way to solve this ?

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.92.1

### Version of Immich Mobile App

v1.92.0 build 117

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
the one available from here (no change)
```

### Your .env content

```Shell
env content also same as the example except for password and upload folder.
```

### Reproduction steps

```bash
Difficult to replicate without the pictures but basically when having 2 brothers close in age...
```

**Comment by kartonrad** [comment]
I have this exact issue with me and my brother - how exactly do i do the reclustering?

Do i have to train two other strong profiles with a lot of assets of me, and my brother respectively, then run recluster?
