### ISSUE TITLE
[BUG] Web: bad layout on modal when adding users to album.

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#6446]
When adding users to an album, the `Add` button gets hidden by a scrollbar.

![image](https://github.com/immich-app/immich/assets/11602424/633cb906-f0be-4c84-82b5-4f2b443feb54)

**Comment by waclaw66** [comment]
Same feeling, Add button would be better in the same row as To list on the right side. That would also fix jumping Suggestions, when first user is added.

**Comment by A-wels** [comment]
I would like to tackle this
