### ISSUE TITLE
[BUG] System settings UI toggles

### ISSUE THREAD

**Issue by gianfrancomac** [immich-app/immich#6483]
### The bug

Just pulled 1.93.0 and got all these toggles floating around. The "Enabled" label disappeared everywhere.

It looks like something needs a fix in the theme?

![Screenshot 2024-01-18 at 11 04 38 PM](https://github.com/immich-app/immich/assets/16405199/55a92f69-8269-4f07-b36e-b8d7f5630f66)

### The OS that Immich Server is running on

Demo app

### Version of Immich Server

v1.93.0

### Version of Immich Mobile App

none

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Demo app
```

### Your .env content

```Shell
Demo app
```

### Reproduction steps

```bash
1. Navigate to /admin/system-settings
2. Expand the accordions
```

**Comment by mertalev** [comment]
The smart merge PR (#5796) made some changes to this component. It looks like some of the CSS got borked in the process.

**Comment by alextran1502** [comment]
Look like it is affecting system using the config file

**Comment by engels0n** [comment]
Same at account settings:

<img width="363" alt="image" src="https://github.com/immich-app/immich/assets/60095377/31e666d4-9fd4-496d-b729-67f8aba4e01e">

**Comment by alextran1502** [comment]
Fixed, patch release will be available soon

**Comment by engels0n** [comment]
Thank you @alextran1502 - toggles are working ... except the one for partner sharing:

<img width="603" alt="image" src="https://github.com/immich-app/immich/assets/60095377/91732f03-27bc-4ba1-9b68-c4b026a48642">

You can click it, but it does not work anymore.
Can you fix that, too ? :)

Thx in advance
