### ISSUE TITLE
Shared partner photos not present on the create album page

### ISSUE THREAD

**Issue by Georift** [immich-app/immich#6486]
### The bug

When creating an album, the add photos button only shows photos which belong to your account. I would expect if partner sharing is enabled that this would show the same camera roll as the home screen.

Perhaps this isn't a bug, but a feature request. But my partner found it confusing that she had to first create the album, then navigate to the timeline to add photos that were mine.

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

1.92.0

### Version of Immich Mobile App

1.92.1 build.117

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not applicable
```

### Your .env content

```Shell
not applicable
```

### Reproduction steps

```bash
1. Enable partner sharing
2. On the mobile app or web application create a new album 
3. Click on `Add Photos` expecting to see a similar view to the home screen
  - Only your own photos will be shown.
```

**Comment by jhit** [comment]
I think this is not a bug but more of a feature request. I'm missing the possibility to add partners pictures to my albums, too.

To be able to see the pictures of my wife and children is great, but when preparing a calendar or photobook, I need to collect images from different accounts into one of my albums. When I'm done with the album creation I can export all Images and create the print Job.

**Comment by figadore** [comment]
Just a clarification on the reproduction steps, after enabling partner sharing, the "Show in timeline" toggle is enabled. If this is not enabled, I don't know that I'd expect to be able to see shared photos on the "Add photos" page
