### ISSUE TITLE
Errors appearing only in logcat, not in app log

### ISSUE THREAD

**Issue by rovo89** [immich-app/immich#6490]
### The bug

I'm currently experiencing some issues with uploading from the Android app. The root cause is probably in my server config (EDIT: `client_max_body_size` was missing), but that isn't why I open this issue.

While trying to debug the problem, I obviously looked into the "Logs" in the app and in the various Docker containers, but nothing was mentioned there. Even after incrasing the log level. Also no error message in the app, the photos simply didn't end up on the server and the remaining count stayed at 10.

Finally I set up adb to check logcat, and there I found more information:
```
01-19 11:31:13.362 10831 10866 I flutter : ERROR backupAsset: FormatException: Unexpected character (at character 1)
01-19 11:31:13.362 10831 10866 I flutter : <html>
01-19 11:31:13.362 10831 10866 I flutter : ^
01-19 11:31:13.362 10831 10866 I flutter :
```

Would it be possible to make that error message appear in the app log?

And by the way, there are usually hundreds of messages in the log, so maybe it would be a good idea to show the latest message at the top (or scroll down by default).

### The OS that Immich Server is running on

Debian 12 / Docker

### Version of Immich Server

v1.193.0

### Version of Immich Mobile App

v1.193.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
...
```

### Your .env content

```Shell
...
```

### Reproduction steps

```bash
1. Mess up your Nginx config.
2. Try to upload files.
```

**Comment by jrasm91** [comment]
The mobile in-app logging has been improved. I believe this issue has been fixed.
