### ISSUE TITLE
[BUG] Can not delete pictures or tag them as favorite when the search was used

### ISSUE THREAD

**Issue by engels0n** [immich-app/immich#6498]
### The bug

I cannot delete images or declare them as favorites/archives if more than x images have been marked.
I searched for plant, got images displayed and selected them (more than 4 at a time).
When I click on delete the following error appeared:

Error:
<img width="851" alt="image" src="https://github.com/immich-app/immich/assets/60095377/478a458d-2045-4865-8497-e4c9c3227dac">

This happens with every search, no matter what the keyword is.
Deleting from the timeline works without any problems.

### The OS that Immich Server is running on

Debian 12 in Docker Container

### Version of Immich Server

v1.9.3

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
standard
```

### Your .env content

```Shell
standard
```

### Reproduction steps

```bash
1. search for a keyword
2. tag pictures (more than 4)
3. try to delete them
```

**Comment by alextran1502** [comment]
Are you using a partner-sharing feature and some of the assets shown in the search also belong to the partner?

**Comment by engels0n** [comment]
Thanks @alextran1502 for the quick reply.

Yes I'm using the partner sharing feature, but the photos belong to my account as far as i can see ...

I even can't see any suspicious errors in the container logs ... maybe a bug in 1.9.3. ? in 1.9.2 I didn't have the problem and the pictures of my wife were just skipped and not deleted ...

**Comment by alextran1502** [comment]
it might be a bug then

**Comment by bo0tzz** [comment]
Are you still having this issue?

**Comment by jrasm91** [comment]
I believe this has been resolved.
