### ISSUE TITLE
[Question]: very rough estimate for when this app will be "stable" 

### ISSUE THREAD

**Issue by jagjordi** [immich-app/immich#652]
### Feature detail

In the [README.md](https://github.com/immich-app/immich/blob/main/README.md) we can see a warning stating that the app is not stable and it is not safe to store your assets.

> warning WARNING: NOT READY FOR PRODUCTION! DO NOT USE TO STORE YOUR ASSETS. This project is under heavy development, there will be continuous functions, features and api changes.

My question is what is the very very approximate time that should we expect this app to be more stable so that we can "trust" it to store pictures and such. I know it is hard to estimate but I ask for a very approximate time range. Is it a few months? Few years? Many years?

Thank you for your great work and support!

### Platform

Web

**Comment by alextran1502** [comment]
With the current pace of development, I think the first stable release _might_ be sometimes during Q1 2023.

**Comment by jagjordi** [comment]
Thanks for your answer and keep up the great work ❤️

**Comment by jagjordi** [comment]
A side questions @alextran1502 , do you plan to release the unraid image ( as discussed in #84 ) together with the first stable release? Or will it come before or after?

**Comment by alextran1502** [comment]
The Unraid image will be released as soon as it is implemented. Currently it is being worked by the community so that is TBD for the timeframe 😅
