### ISSUE TITLE
can not download the video from web side

### ISSUE THREAD

**Issue by qdog2012** [immich-app/immich#6522]
### The bug

![download1](https://github.com/immich-app/immich/assets/3591266/e5c82ee6-5471-4798-b3ff-40d928ecab8d)
May the problem be caused by file name capitalization?

### The OS that Immich Server is running on

synology docker

### Version of Immich Server

v1.93.2

### Version of Immich Mobile App

v1.93.2

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
1.select the video file, click download
2.
3.
...
```

**Comment by bo0tzz** [comment]
immich-server should have logged an error. Can you post those logs?

**Comment by qdog2012** [comment]
date | stream | content
-- | -- | --
2024/01/30 19:13:13 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:81:21)] [39m[31mError: write EPIPE[39m
2024/01/30 19:13:13 | stderr | at connectionCorkNT (node:_http_outgoing:955:8)
2024/01/30 19:13:13 | stderr | at Writable.uncork (node:internal/streams/writable:523:7)
2024/01/30 19:13:13 | stderr | at clearBuffer (node:internal/streams/writable:773:7)
2024/01/30 19:13:13 | stderr | at doWrite (node:internal/streams/writable:590:12)
2024/01/30 19:13:13 | stderr | at Socket._write (node:net:964:8)
2024/01/30 19:13:13 | stderr | at Socket._writeGeneric (node:net:952:11)
2024/01/30 19:13:13 | stderr | at writeGeneric (node:internal/stream_base_commons:151:3)
2024/01/30 19:13:13 | stderr | at afterWriteDispatched (node:internal/stream_base_commons:160:15)
2024/01/30 19:13:13 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:13:13 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:13:13 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:81:21)] [39m[31mFailed to download file[39m
2024/01/30 19:13:13 | stderr | at connectionCorkNT (node:_http_outgoing:955:8)
2024/01/30 19:13:13 | stderr | at Writable.uncork (node:internal/streams/writable:523:7)
2024/01/30 19:13:13 | stderr | at clearBuffer (node:internal/streams/writable:773:7)
2024/01/30 19:13:13 | stderr | at doWrite (node:internal/streams/writable:590:12)
2024/01/30 19:13:13 | stderr | at Socket._write (node:net:964:8)
2024/01/30 19:13:13 | stderr | at Socket._writeGeneric (node:net:952:11)
2024/01/30 19:13:13 | stderr | at writeGeneric (node:internal/stream_base_commons:151:3)
2024/01/30 19:13:13 | stderr | at afterWriteDispatched (node:internal/stream_base_commons:160:15)
2024/01/30 19:13:13 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:13:13 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:13:07 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:13:07 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:13:07 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:13:07 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to serve file[39m
2024/01/30 19:13:07 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:13:07 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:13:06 | stdout | [33m[Nest] 7  - [39m01/31/2024, 3:13:06 AM [33m   WARN[39m [38;5;3m[ExpressAdapter] [39m[33mContent-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses[39m
2024/01/30 19:13:06 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:13:06 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:13:06 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:13:06 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to serve file[39m
2024/01/30 19:13:06 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:13:06 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:13:00 | stdout | [33m[Nest] 7  - [39m01/31/2024, 3:13:00 AM [33m   WARN[39m [38;5;3m[ExpressAdapter] [39m[33mContent-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses[39m
2024/01/30 19:13:00 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:81:21)] [39m[31mError: write EPIPE[39m
2024/01/30 19:13:00 | stderr | at connectionCorkNT (node:_http_outgoing:955:8)
2024/01/30 19:13:00 | stderr | at Writable.uncork (node:internal/streams/writable:523:7)
2024/01/30 19:13:00 | stderr | at clearBuffer (node:internal/streams/writable:773:7)
2024/01/30 19:13:00 | stderr | at doWrite (node:internal/streams/writable:590:12)
2024/01/30 19:13:00 | stderr | at Socket._write (node:net:964:8)
2024/01/30 19:13:00 | stderr | at Socket._writeGeneric (node:net:952:11)
2024/01/30 19:13:00 | stderr | at writeGeneric (node:internal/stream_base_commons:151:3)
2024/01/30 19:13:00 | stderr | at afterWriteDispatched (node:internal/stream_base_commons:160:15)
2024/01/30 19:13:00 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:13:00 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:13:00 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:81:21)] [39m[31mFailed to serve file[39m
2024/01/30 19:13:00 | stderr | at connectionCorkNT (node:_http_outgoing:955:8)
2024/01/30 19:13:00 | stderr | at Writable.uncork (node:internal/streams/writable:523:7)
2024/01/30 19:13:00 | stderr | at clearBuffer (node:internal/streams/writable:773:7)
2024/01/30 19:13:00 | stderr | at doWrite (node:internal/streams/writable:590:12)
2024/01/30 19:13:00 | stderr | at Socket._write (node:net:964:8)
2024/01/30 19:13:00 | stderr | at Socket._writeGeneric (node:net:952:11)
2024/01/30 19:13:00 | stderr | at writeGeneric (node:internal/stream_base_commons:151:3)
2024/01/30 19:13:00 | stderr | at afterWriteDispatched (node:internal/stream_base_commons:160:15)
2024/01/30 19:13:00 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:13:00 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:58 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:12:58 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:58 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:58 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to serve file[39m
2024/01/30 19:12:58 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:58 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:50 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:12:50 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:50 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:50 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to serve file[39m
2024/01/30 19:12:50 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:50 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:50 | stdout | [33m[Nest] 7  - [39m01/31/2024, 3:12:50 AM [33m   WARN[39m [38;5;3m[ExpressAdapter] [39m[33mContent-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses[39m
2024/01/30 19:12:47 | stdout | [33m[Nest] 7  - [39m01/31/2024, 3:12:47 AM [33m   WARN[39m [38;5;3m[ExpressAdapter] [39m[33mContent-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses[39m
2024/01/30 19:12:47 | stdout | [33m[Nest] 7  - [39m01/31/2024, 3:12:47 AM [33m   WARN[39m [38;5;3m[ExpressAdapter] [39m[33mContent-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses[39m
2024/01/30 19:12:45 | stdout | [33m[Nest] 7  - [39m01/31/2024, 3:12:45 AM [33m   WARN[39m [38;5;3m[ExpressAdapter] [39m[33mContent-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses[39m
2024/01/30 19:12:44 | stdout | [33m[Nest] 7  - [39m01/31/2024, 3:12:44 AM [33m   WARN[39m [38;5;3m[ExpressAdapter] [39m[33mContent-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses[39m
2024/01/30 19:12:41 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:12:41 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:41 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:41 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to serve file[39m
2024/01/30 19:12:41 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:41 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:41 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:81:21)] [39m[31mError: write EPIPE[39m
2024/01/30 19:12:41 | stderr | at connectionCorkNT (node:_http_outgoing:955:8)
2024/01/30 19:12:41 | stderr | at Writable.uncork (node:internal/streams/writable:523:7)
2024/01/30 19:12:41 | stderr | at clearBuffer (node:internal/streams/writable:773:7)
2024/01/30 19:12:41 | stderr | at doWrite (node:internal/streams/writable:590:12)
2024/01/30 19:12:41 | stderr | at Socket._write (node:net:964:8)
2024/01/30 19:12:41 | stderr | at Socket._writeGeneric (node:net:952:11)
2024/01/30 19:12:41 | stderr | at writeGeneric (node:internal/stream_base_commons:151:3)
2024/01/30 19:12:41 | stderr | at afterWriteDispatched (node:internal/stream_base_commons:160:15)
2024/01/30 19:12:41 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:41 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:41 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:81:21)] [39m[31mFailed to serve file[39m
2024/01/30 19:12:41 | stderr | at connectionCorkNT (node:_http_outgoing:955:8)
2024/01/30 19:12:41 | stderr | at Writable.uncork (node:internal/streams/writable:523:7)
2024/01/30 19:12:41 | stderr | at clearBuffer (node:internal/streams/writable:773:7)
2024/01/30 19:12:41 | stderr | at doWrite (node:internal/streams/writable:590:12)
2024/01/30 19:12:41 | stderr | at Socket._write (node:net:964:8)
2024/01/30 19:12:41 | stderr | at Socket._writeGeneric (node:net:952:11)
2024/01/30 19:12:41 | stderr | at writeGeneric (node:internal/stream_base_commons:151:3)
2024/01/30 19:12:41 | stderr | at afterWriteDispatched (node:internal/stream_base_commons:160:15)
2024/01/30 19:12:41 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:41 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:40 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:12:40 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:40 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:40 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to serve file[39m
2024/01/30 19:12:40 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:40 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:35 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:12:35 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:35 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:35 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to download file[39m
2024/01/30 19:12:35 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:35 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:33 | stdout | [33m[Nest] 7  - [39m01/31/2024, 3:12:33 AM [33m   WARN[39m [38;5;3m[ExpressAdapter] [39m[33mContent-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses[39m
2024/01/30 19:12:27 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:12:27 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:27 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:27 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to serve file[39m
2024/01/30 19:12:27 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:12:27 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:12:26 | stdout | [33m[Nest] 7  - [39m01/31/2024, 3:12:26 AM [33m   WARN[39m [38;5;3m[ExpressAdapter] [39m[33mContent-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses[39m
2024/01/30 19:11:12 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:81:21)] [39m[31mError: write EPIPE[39m
2024/01/30 19:11:12 | stderr | at connectionCorkNT (node:_http_outgoing:955:8)
2024/01/30 19:11:12 | stderr | at Writable.uncork (node:internal/streams/writable:523:7)
2024/01/30 19:11:12 | stderr | at clearBuffer (node:internal/streams/writable:773:7)
2024/01/30 19:11:12 | stderr | at doWrite (node:internal/streams/writable:590:12)
2024/01/30 19:11:12 | stderr | at Socket._write (node:net:964:8)
2024/01/30 19:11:12 | stderr | at Socket._writeGeneric (node:net:952:11)
2024/01/30 19:11:12 | stderr | at writeGeneric (node:internal/stream_base_commons:151:3)
2024/01/30 19:11:12 | stderr | at afterWriteDispatched (node:internal/stream_base_commons:160:15)
2024/01/30 19:11:12 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:11:12 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:11:12 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:81:21)] [39m[31mFailed to download file[39m
2024/01/30 19:11:12 | stderr | at connectionCorkNT (node:_http_outgoing:955:8)
2024/01/30 19:11:12 | stderr | at Writable.uncork (node:internal/streams/writable:523:7)
2024/01/30 19:11:12 | stderr | at clearBuffer (node:internal/streams/writable:773:7)
2024/01/30 19:11:12 | stderr | at doWrite (node:internal/streams/writable:590:12)
2024/01/30 19:11:12 | stderr | at Socket._write (node:net:964:8)
2024/01/30 19:11:12 | stderr | at Socket._writeGeneric (node:net:952:11)
2024/01/30 19:11:12 | stderr | at writeGeneric (node:internal/stream_base_commons:151:3)
2024/01/30 19:11:12 | stderr | at afterWriteDispatched (node:internal/stream_base_commons:160:15)
2024/01/30 19:11:12 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:11:12 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:11:09 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:11:09 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:11:09 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:11:09 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to download file[39m
2024/01/30 19:11:09 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:11:09 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:10:00 | stdout | [32m[Nest] 7  - [39m01/31/2024, 3:10:00 AM [32m    LOG[39m [38;5;3m[AuditService] [39m[32mFound 1142 assets, 2 users, 0 people[39m
2024/01/30 19:09:59 | stdout | [32m[Nest] 7  - [39m01/31/2024, 3:09:59 AM [32m    LOG[39m [38;5;3m[AuditService] [39m[32mFound 1136 original files, 2302 thumbnails, 205 encoded videos, 0 profile files[39m
2024/01/30 19:09:46 | stdout | [32m[Nest] 7  - [39m01/31/2024, 3:09:46 AM [32m    LOG[39m [38;5;3m[AuditService] [39m[32mFound 1142 assets, 2 users, 0 people[39m
2024/01/30 19:09:45 | stdout | [32m[Nest] 7  - [39m01/31/2024, 3:09:45 AM [32m    LOG[39m [38;5;3m[AuditService] [39m[32mFound 1136 original files, 2302 thumbnails, 205 encoded videos, 0 profile files[39m
2024/01/30 19:07:37 | stdout | [33m[Nest] 7  - [39m01/31/2024, 3:07:37 AM [33m   WARN[39m [38;5;3m[ExpressAdapter] [39m[33mContent-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses[39m
2024/01/30 19:07:36 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:07:36 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:07:36 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:07:36 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to serve file[39m
2024/01/30 19:07:36 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:07:36 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:07:28 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:07:28 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:07:28 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:07:28 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to serve file[39m
2024/01/30 19:07:28 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:07:28 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:07:28 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:07:28 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:07:28 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:07:28 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to serve file[39m
2024/01/30 19:07:28 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:07:28 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:07:27 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:07:27 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:07:27 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:07:27 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to serve file[39m
2024/01/30 19:07:27 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:07:27 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:07:14 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mError: write EPIPE[39m
2024/01/30 19:07:14 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:07:14 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:07:14 | stderr | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] [39m[31mFailed to serve file[39m
2024/01/30 19:07:14 | stderr | [31m[Nest] 7  - [39m01/31/2024, 3:07:14 AM [31m  ERROR[39m [38;5;3m[Error: write EPIPE
2024/01/30 19:07:14 | stdout | [33m[Nest] 7  - [39m01/31/2024, 3:07:14 AM [33m   WARN[39m [38;5;3m[ExpressAdapter] [39m[33mContent-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses[39m
2024/01/30 19:07:05 | stdout | [33m[Nest] 7  - [39m01/31/2024, 3:07:05 AM [33m   WARN[39m [38;5;3m[ExpressAdapter] [39m[33mContent-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses[39m
2024/01/30 19:06:55 | stdout | [32m[Nest] 7  - [39m01/31/2024, 3:06:55 AM [32m    LOG[39m [38;5;3m[CommunicationRepository] [39m[32mWebsocket Connect:    pWs6PuiEfH08dk7_AAAl[39m
2024/01/30 19:06:54 | stdout | [32m[Nest] 7  - [39m01/31/2024, 3:06:54 AM [32m    LOG[39m [38;5;3m[CommunicationRepository] [39m[32mWebsocket Disconnect: kiAdQwf5BQqA1_jjAAAj[39m

**Comment by bo0tzz** [comment]
Are you using a reverse proxy, or accessing Immich directly?

**Comment by aviv926** [comment]
Hi, is the problem still relevant?
