### ISSUE TITLE
[BUG] Can't change feature photo of a person anymore

### ISSUE THREAD

**Issue by engels0n** [immich-app/immich#6548]
### The bug

Feature photo change of a person does not work anymore:

Error:

`[Nest] 6  - 01/21/2024, 12:11:54 PM   ERROR [JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: extract_area: bad extract area
[Nest] 6  - 01/21/2024, 12:11:54 PM   ERROR [JobService] Error: extract_area: bad extract area
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:161:17)
    at MediaRepository.crop (/usr/src/app/dist/infra/repositories/media.repository.js:28:14)
    at PersonService.handleGeneratePersonThumbnail (/usr/src/app/dist/domain/person/person.service.js:375:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/domain/job/job.service.js:116:37
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 01/21/2024, 12:11:54 PM   ERROR [JobService] Object:
{
  "id": "57dcdf10-ab2c-4e45-a5c1-2244aece9425"
}
`

### The OS that Immich Server is running on

Debian 12 in Docker Container

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. try to change it
```

**Comment by drifter75** [comment]
Running v1.93.3 on Debian 12/Docker.

It works

**Comment by engels0n** [comment]
Is this perhaps related to facial recognition?

Here are my settings:

<img width="555" alt="image" src="https://github.com/immich-app/immich/assets/60095377/1fca2cc2-a122-41c2-af9b-b0540c5fd223">

**Comment by drifter75** [comment]
or is it with the image itself?

have you tried with other images?

**Comment by engels0n** [comment]
I tried different other pictures and even other persons ... no luck :> ...

I'm running face detection again to see what happens ...

**Comment by martabal** [comment]
I think I already saw that error once. The error comes from the way the image is extracted from the photo.

**Comment by engels0n** [comment]
Problem is gone after re-detecting faces ... seems weird though ...
