### ISSUE TITLE
[Feature]: Use QR code to login on mobile

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#655]
### Feature detail

I have a fairly long password and a pretty long URL, and it annoys me to type it when I have to log in on my phone. Though it's a minor thing, I would like to be able to scan a QR code scanned on some personal user page and to login through that QR code. Ombi has this feature as well.

I'm probably just lazy, but it would still be nice.

### Platform

Mobile App

**Comment by alextran1502** [comment]
The app can save the user login info, so this feature won't be needed

**Comment by paaspaas00** [comment]
Hey just a quick proposal here, what about instead of password, Immich offers an asymmetric key-pair qr-code auth? Same as what the Wireguard app for Android does. It would be much more secure that way and easier for user. In case you guys want to reopen this, worth considering maybe @alextran1502

**Comment by TomK32** [comment]
I'm also someone with super long randomly generated passwords: QR codes would be a great feature to have.
Besides logins, I'd also like to show the album share links as a QR code.

I'll put some time into this feature and report back in March. I'm thinking about using either [qr-creator](https://www.npmjs.com/package/qr-creator) (basic) or [qr-code-styling](https://www.npmjs.com/package/qr-code-styling) (fancy) for generating the QR code and [@paulmillr/qr](https://www.npmjs.com/package/@paulmillr/qr) for decoding in the web client.

Any hints on what I should use for the mobile client? [There's plenty of libraries](https://pub.dev/packages?q=platform%3Aandroid+platform%3Aios+is%3Adart3-compatible+sdk%3Aflutter+qr+decode) and it's my first time programming in Dart.

- [ ] generate QR code for sign in for web and mobile
- [ ] generate QR code for sharing links for web and mobile
- [ ] read/decode QR code in mobile (and web?)
