### ISSUE TITLE
wrong date on time line, but only on mobile client, after moving assets into archive

### ISSUE THREAD

**Issue by aisbergde** [immich-app/immich#6560]
### The bug

assets are shown with the correct date in the web client, but with wrong date in the timline on mobile client.

The issue happened after moving 3 assets, taken today, into the archive. I moved them, using the web client. it looks like the mobile client lost the relation between the numbering of assets and the real assets. mobile client only knows, that today 3 assets have been taken and the first 3 assets are shown "today". 3 assets, taken last week are shown as taken yesterday. And so on.

![Screenshot_2024-01-21-23-48-53-041_app alextran immich-edit](https://github.com/immich-app/immich/assets/9020187/9342abdb-1c86-408a-b8ef-10c6850d69a7)
![Screenshot_2024-01-21-23-49-41-944_com android chrome](https://github.com/immich-app/immich/assets/9020187/f4f202c3-289b-463e-8f95-a8560931edbe)
![Screenshot_2024-01-21-23-49-56-410_com android chrome-edit](https://github.com/immich-app/immich/assets/9020187/e31658da-ba65-4bf9-a224-cfb550f04ead)

desired behavior:

if assets are moved to archive , using the web GUI, the mobile GUI should take this into account. At least there should be a refresh option, when swiping down the app to refresh the view.

The issue can be reproduced.

Closing the mobile client and reopening will solve. it looks like the order of assets is defined, only once when opening the mobile client. 

### The OS that Immich Server is running on

container on synology 

### Version of Immich Server

1.93.2

### Version of Immich Mobile App

1.93 2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by alextran1502** [comment]
Hello, not all of the actions have web socket event. We usually sync the mobile client when the app is reopen/bring up from background. There is also the option to pull to refresh on the Photos page.

**Comment by aisbergde** [comment]
it looks like, the permission to allow notifications needed to be set in settings. Now it works.

Is it possible, that the mobile client doesn't remember some settings? Or are these new settings, not existing a few versions before? I think, I went through settings in the past. But I could just forgot.

**Comment by jrasm91** [comment]
I believe this issue has been fixed. Let me know if that is not the case.
