### ISSUE TITLE
Facial Recognition re-processes lots of assets

### ISSUE THREAD

**Issue by tbleiker** [immich-app/immich#6569]
### The bug

When I click "Missing" on the "Facial Recognition" job, thousands of assets are re-processed. When the job finishes and I click "Missing" again, the same amount of assets are processed again. 

### The OS that Immich Server is running on

Docker on Debian Bookworm

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

v1.93.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Open "Administration" and then "Jobs" 
2. Click "Missing" under Facial Recognition
```

**Comment by mertalev** [comment]
This isn't a bug. "Missing" queues faces with no associated person. It needs to process all of these to see if any are eligible to be grouped into people.

**Comment by tbleiker** [comment]
I see. This is due to "min recognized faces" set to >1?

This is a little unsatisfactory, because every time I take a picture, the server now processes thousands of images (which takes roughly 15min now, avg. 50% cpu for all my 4 cores). And the number of assets to process potentially grows with every image I take...

**Comment by mertalev** [comment]
It's possible to reduce the number of faces processed by only checking the faces of new assets, but this would lower the quality of the clustering algorithm.

If you set min faces to 1, the behavior will resemble the old algorithm: all faces will be associated with a person and the clustering for new assets will be quick. The other side of that is that the quality will also be closer to the old algorithm (but still somewhat better).

**Comment by tbleiker** [comment]
Thx for the fast response.

Maybe, "only checking the faces of new assets" can be provided as option and the user can decide. 

For my assets, I cannot see an overall improvement of the new clustering algorithm. Therefore, I would prefer speed (and less ressources) over quality 😄

**Comment by tbleiker** [comment]
Oh, and I realised that the facial recognition job is triggered for images wiht no detected faces as well.

**Comment by mertalev** [comment]
That's a good point. We can optimize that to only trigger facial recognition is a face is detected.

**Comment by tbleiker** [comment]
What do you think, are there any other optimization options? Should we open a discussion topic for this? Or discuss it in Discord?

E.g.: I would expect, that the facial recognition for a new picture with e.g. two faces (which are already clusterd) is fast - given that their points are right in the middle of their already known cluster.
