### ISSUE TITLE
[BUG] server: metadata refresh

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#6599]
### The bug

Metadata refresh doesn't removes City, State, Country when GPS location is not present anomore, e.g. after xmp sidecar removal.

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. set location to asset without location
2. remove xmp sidecar file
3. refresh metadata
4. location still shown, however no map visible
```

**Comment by jrasm91** [comment]
This has been fixed
