### ISSUE TITLE
Can't share photos from partner

### ISSUE THREAD

**Issue by troyane** [immich-app/immich#6602]
### The bug

Settings -> Sharing -> Partner -> Checkbox "Photos from partner" can't be checked. See attachment:

https://github.com/immich-app/immich/assets/477468/1035db2c-030f-4d3f-b80e-08086b654504

### The OS that Immich Server is running on

Synology NAS

### Version of Immich Server

v1.93.0

### Version of Immich Mobile App

doesn't matter

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
Open Settings -> Sharing -> Partner -> Checkbox "Photos from partner" can't be checked.
```

**Comment by alextran1502** [comment]
it is fixed in the latest version 1.93.3
