### ISSUE TITLE
[Feature]: View more elaborate information about videos

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#661]
### Feature detail

Add more information when clicking on the info button in the right-top corner.
Jellyfin does this really well, by showing video codec, container, resolution, etc.
![image](https://user-images.githubusercontent.com/47184046/189480162-8f144147-feef-425f-90fc-ed7a55ad5eb1.png)

Of course the language doesn't have to be added, but please add more info about codec, resolution, aspect ratio, framerate, bitrate, color / video range (hdr / sdr), audio codec, audio bitrate, sample rate, and the audio channels.

I selected web as platform, but it would be nice to have for mobile as well.

### Platform

Web

**Comment by alextran1502** [comment]
The current information is sufficient. I am not planning to add more information about the video. Trying to keep the information minimal for the sake of the UI
