### ISSUE TITLE
Can't go back to the asset viewer when the description is too long

### ISSUE THREAD

**Issue by martabal** [immich-app/immich#6611]
### The bug

When opening the ExifBottomSheet widget and the description is too long, you can't go back to the asset viewer with a swipe down

## Screenshots

https://github.com/immich-app/immich/assets/74269598/45961f51-ed81-40dc-9d16-d1a10208936b

### The OS that Immich Server is running on

Arch Linux

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

v1.93.2 build 135

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Have an asset with a very long description
2. Go to this asset on your phone
3. Open the exif widget
4. Swipe down does not close the widget
...
```

**Comment by alextran1502** [comment]
Fixed
