### ISSUE TITLE
Android app doesn't show images on Server

### ISSUE THREAD

**Issue by amrit92** [immich-app/immich#6619]
### The bug

Android app doesn't show images on Server. The app is setup not to backup anything but just as a viewer. Server has a lot of photos, but none of them appear on the mobile app.

### The OS that Immich Server is running on

Manjaro

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

v1.93.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=xxxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.docker-compose up
2.Run mobile Android app
3.
...
```

### Additional information
created_at,level,context,message,stacktrace
20.08.7376
20.08.7376
20.08.7376
20.08.7376
20.08.7376

#0      IOClient.send (package:http/src/io_client.dart:90)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      ApiClient.invokeAPI (package:openapi/api_client.dart:101)
<asynchronous suspension>
#3      AssetApi.getAllAssets (package:openapi/api/asset_api.dart:400)
<asynchronous suspension>
#4      AssetService._getRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:72)
<asynchronous suspension>
#5      SyncService._syncRemoteAssetsFull (package:immich_mobile/shared/services/sync.service.dart:209)
<asynchronous suspension>
#6      SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/shared/services/sync.service.dart:53)
<asynchronous suspension>
,#0      ApiClient.invokeAPI (package:openapi/api_client.dart:125)
<asynchronous suspension>
#1      AssetApi.getAllAssets (package:openapi/api/asset_api.dart:400)
<asynchronous suspension>
#2      AssetService._getRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:72)
<asynchronous suspension>
#3      SyncService._syncRemoteAssetsFull (package:immich_mobile/shared/services/sync.service.dart:209)
<asynchronous suspension>
#4      SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/shared/services/sync.service.dart:53)
<asynchronous suspension>
2000302
20.08.7376
20.08.7376
#1      _CastListBase.[] (dart:_internal/cast.dart:99)
#2      MemoryLane.build.<anonymous closure>.<anonymous closure> (package:immich_mobile/modules/memories/ui/memory_lane.dart:55)
#3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:490)
#4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:828)
#5      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:842)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719)
#7      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:834)
#8      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:351)
#9      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2604)
#10     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1059)
#11     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2604)
#12     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:340)
#13     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:426)
#14     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#16     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
#17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534)
#20     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1883)
#21     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1834)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#23     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#26     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#29     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#32     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#35     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#38     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#41     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#46     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1431)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#49     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:279)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#51     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#52     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#54     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#57     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#60     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#61     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:213)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#63     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
#64     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#66     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534)
#67     UnboundedRenderViewport._attemptLayout (package:scrollable_positioned_list/src/viewport.dart:281)
#68     UnboundedRenderViewport.performLayout (package:scrollable_positioned_list/src/viewport.dart:182)
#69     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2332)
#70     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1013)
#71     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494)
#72     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918)
#73     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360)
#74     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297)
#75     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227)
#76     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085)
#77     _invoke (dart:ui/hooks.dart:170)
#78     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401)
#79     _drawFrame (dart:ui/hooks.dart:140)
,#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      _CastListBase.[] (dart:_internal/cast.dart:99)
#2      MemoryLane.build.<anonymous closure>.<anonymous closure> (package:immich_mobile/modules/memories/ui/memory_lane.dart:55)
#3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:490)
#4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:828)
#5      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:842)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719)
#7      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:834)
#8      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:351)
#9      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2604)
#10     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1059)
#11     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2604)
#12     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:340)
#13     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:426)
#14     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#16     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
#17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534)
#20     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1883)
#21     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1834)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#23     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#26     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#29     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#32     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#35     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#38     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#41     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#46     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1431)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#49     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:279)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#51     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#52     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#54     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#57     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#60     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#61     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:213)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#63     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
#64     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#66     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534)
#67     UnboundedRenderViewport._attemptLayout (package:scrollable_positioned_list/src/viewport.dart:281)
#68     UnboundedRenderViewport.performLayout (package:scrollable_positioned_list/src/viewport.dart:182)
#69     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2332)
#70     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1013)
#71     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494)
#72     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918)
#73     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360)
#74     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297)
#75     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227)
#76     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085)
#77     _invoke (dart:ui/hooks.dart:170)
#78     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401)
#79     _drawFrame (dart:ui/hooks.dart:140)
2000302
20.08.7376
20.08.7376
#1      _CastListBase.[] (dart:_internal/cast.dart:99)
#2      MemoryLane.build.<anonymous closure>.<anonymous closure> (package:immich_mobile/modules/memories/ui/memory_lane.dart:55)
#3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:490)
#4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:828)
#5      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:842)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719)
#7      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:834)
#8      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:351)
#9      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2604)
#10     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1059)
#11     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2604)
#12     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:340)
#13     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:426)
#14     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#16     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
#17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534)
#20     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1883)
#21     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1834)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#23     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#26     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#29     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#32     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#35     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#38     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#41     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#46     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1431)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#49     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:279)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#51     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#52     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#54     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#57     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#60     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#61     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:213)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#63     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
#64     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#66     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534)
#67     UnboundedRenderViewport._attemptLayout (package:scrollable_positioned_list/src/viewport.dart:281)
#68     UnboundedRenderViewport.performLayout (package:scrollable_positioned_list/src/viewport.dart:182)
#69     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2332)
#70     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1013)
#71     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494)
#72     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918)
#73     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360)
#74     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297)
#75     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227)
#76     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085)
#77     _invoke (dart:ui/hooks.dart:170)
#78     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401)
#79     _drawFrame (dart:ui/hooks.dart:140)
,#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      _CastListBase.[] (dart:_internal/cast.dart:99)
#2      MemoryLane.build.<anonymous closure>.<anonymous closure> (package:immich_mobile/modules/memories/ui/memory_lane.dart:55)
#3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:490)
#4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:828)
#5      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:842)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719)
#7      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:834)
#8      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:351)
#9      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2604)
#10     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1059)
#11     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2604)
#12     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:340)
#13     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:426)
#14     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#16     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
#17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534)
#20     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1883)
#21     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1834)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#23     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#26     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#29     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#32     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#35     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#38     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#41     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#46     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1431)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#49     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:279)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#51     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#52     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#54     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#57     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#60     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#61     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:213)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#63     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
#64     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#66     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534)
#67     UnboundedRenderViewport._attemptLayout (package:scrollable_positioned_list/src/viewport.dart:281)
#68     UnboundedRenderViewport.performLayout (package:scrollable_positioned_list/src/viewport.dart:182)
#69     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2332)
#70     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1013)
#71     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494)
#72     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918)
#73     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360)
#74     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297)
#75     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227)
#76     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085)
#77     _invoke (dart:ui/hooks.dart:170)
#78     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401)
#79     _drawFrame (dart:ui/hooks.dart:140)

_No response_

**Comment by alextran1502** [comment]
can you help grab the mobile app log?

**Comment by amrit92** [comment]
@alextran1502  Added logs

**Comment by jrasm91** [comment]
I believe this has been fixed.
