### ISSUE TITLE
PERF: switch from `axios` to `fetch`

### ISSUE THREAD

**Issue by benmccann** [immich-app/immich#6647]
### The bug

The typescript-axios generator pulls in an extra dependency on `axios`. The typescript-fetch generator could avoid this by using the browser's built-in `fetch` method.

Note that `fetch` is not supported in Internet Explorer (https://caniuse.com/fetch). I didn't see in the docs which browsers are supported, but I'm guessing IE is not a concern since it's a fairly recent app

### The OS that Immich Server is running on

any

### Version of Immich Server

any

### Version of Immich Mobile App

any

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
https://github.com/immich-app/immich/blob/main/open-api/bin/generate-open-api.sh
https://github.com/immich-app/immich/blob/ca28e1e7a82b4467012e27934c2cddda39ea2c6c/.github/workflows/dispatch_sdk_update.yml#L23
```

**Comment by jrasm91** [comment]
I'd be fine with this, just implies testing and validating the new client. Specifically, the file/attachment upload endpoints have always been tricky with the auto-generated clients.

**Comment by benmccann** [comment]
I took a look at this and overall it's quite nice as it removes the need to do `.data` on every response.

The trickiest thing is figuring out how to re-implement `onUploadProgress` and `onDownloadProgress` from axios. Firefox/Safari don't have full support for the necessary APIs (one only supports upload and the other only supports download):
- https://github.com/axios/axios/issues/1219#issuecomment-1281827059
- https://developer.mozilla.org/en-US/docs/Web/API/Request/body
- https://developer.mozilla.org/en-US/docs/Web/API/Response/body

So the only way to monitor progress of these large file transfers appears to be to be to drop down and use XHR directly for that API call rather than using the `typescript-fetch` API for that specific call.
