### ISSUE TITLE
Insta360 Panoramic Photos not dispayed correctly

### ISSUE THREAD

**Issue by albatrosify** [immich-app/immich#6681]
### The bug

<img width="1386" alt="Bildschirmfoto" src="https://github.com/immich-app/immich/assets/64252708/53b4e6fb-ddbf-4760-9751-680f9da9d542">

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

v1.93.3

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Irrelevant
```

### Your .env content

```Shell
Irrelevant
```

### Reproduction steps

```bash
Upload 360° Image and display in web or mobile
```

### Additional information

Example File:
[IMG_20230514_112100_00_055.insp.zip](https://github.com/immich-app/immich/files/14151205/IMG_20230514_112100_00_055.insp.zip)
[IMG_20230514_112100_00_055.dng.zip](https://github.com/immich-app/immich/files/14151206/IMG_20230514_112100_00_055.dng.zip)

**Comment by aviv926** [comment]
Can you try to zoom in on the image and see if the problem exists?
If the problem still exists, could you upload a similar picture so that the team can check?

**Comment by albatrosify** [comment]
Yeah, the problem is, that the kind this image gets wrapped around the sphere is wrong.
I will see and try to get an example image for us to work on

**Comment by aviv926** [comment]
> Yeah, the problem is, that the kind this image gets wrapped around the sphere is wrong.
> I will see and try to get an example image for us to work on

I just want to let you know that currently there is no 360 image support in the browser interface, but there is support in the app.

**Comment by alex-007** [comment]
the same bug is already mentioned in https://github.com/immich-app/immich/issues/3465 and https://github.com/immich-app/immich/issues/3490

**Comment by albatrosify** [comment]
EDIT: Two example files added to the Bug Description

**Comment by dmitry-brazhenko** [comment]
I would suggest to close this issue, I will resolve the problem in this issue: https://github.com/immich-app/immich/issues/3465

**Comment by dmitry-brazhenko** [comment]
seems that this is another bug. as far as I see, the attached image does not have panorama-related exif tags at all. SO probably there is only one option here: allow manually mark images as panoramas 


For example, once I upload the attached photo to Google Photos, it is not recognized as a  panorama view

**Comment by aviv926** [comment]
Fixed at https://github.com/immich-app/immich/pull/6992

You may find https://github.com/immich-app/immich/issues/7243 related

**Comment by nordic-style** [comment]
Hello @aviv926 ,

this is not fixed at #6992 since that only seems to work for already stitched photos. @albatrosify asks for unstitched raw insta360 images.

<img width="1800" alt="Screenshot 2024-05-26 at 01 59 56" src="https://github.com/immich-app/immich/assets/11313330/8669b712-d0ac-437f-97e5-57b1ed9e225e">
<img width="1798" alt="Screenshot 2024-05-26 at 02 00 15" src="https://github.com/immich-app/immich/assets/11313330/5d9b49ff-32a8-4049-b599-5905231a193c">

**Comment by ZILosoft** [comment]
Hi, any updates?

The Insta360 RAW images are still displaying incorrectly.

**Comment by alextran1502** [comment]
@ZILosoft There is not, as this is not on our priority list at the moment

**Comment by davidnghongkong** [comment]
I have the same problem with the x3 raw files, using the latest docker.

**Comment by dfldylan** [comment]
I have the same problem with the x4 air raw files, using the latest docker.

**Comment by dmitry-brazhenko** [comment]
@dfldylan could you share few files that are not displayed correctly?

**Comment by dfldylan** [comment]
> [@dfldylan](https://github.com/dfldylan) could you share few files that are not displayed correctly?

of courses, sir.

could you download these?

http://ustb-ai3ds.quickconnect.cn/d/s/16Ydhd6xlAHs7zNG9h7QpHDlXUOcTB7A/69KP9nGv8islQCkxDJYSFOQLrUEU0_6Z-Rrygl6044Qw

**Comment by dmitry-brazhenko** [comment]
Hi!

I had a look at this issue (as I originally contributed this panorama viewer) , and the core issue that the viewer that was introduced (https://photo-sphere-viewer.js.org/), does not correctly display these insta360 images sadly. 

Seems it is expected to be [dual fishey format](https://photo-sphere-viewer.js.org/guide/adapters/dual-fisheye.html), but when I insert it, it is not displayed correctly 

I will play more, but probably not that easy to fix as there is not component that can display such images correctly . Even google photos do not display them correctly 

Here is how this panorama is displayed if using the adapter. It is better then now, but still not correct: 

<img width="2588" height="1434" alt="Image" src="https://github.com/user-attachments/assets/95244577-c500-4d3a-a9de-7bf859363ba3" />

**Comment by dmitry-brazhenko** [comment]
Seems that isnta360 has some properietary format that is not maintained by community . And the recommended way is to get exported by insta360 studio to Equirectangular projection

**Comment by dmitry-brazhenko** [comment]
I doubt that there is any easy way to do it, sadly

**Comment by dfldylan** [comment]
> I doubt that there is any easy way to do it, sadly

that's ok, bro.
I wonder is this function work well before? or broken all the time?

**Comment by dmitry-brazhenko** [comment]
This always worked this way. I introduced this panorama viewer 1.5 years ago and there were no changes to that since that. 

There is a workaround that I discovered . Open insta 360 image using insta360 studio and export it to jpg. If this jpg is imported, seems that it works correctly.

**Comment by JasonHK** [comment]
> This always worked this way. I introduced this panorama viewer 1.5 years ago and there were no changes to that since that. 
> 
> There is a workaround that I discovered . Open insta 360 image using insta360 studio and export it to jpg. If this jpg is imported, seems that it works correctly. 

Yes, this will fix the display issue. But they intentionally striped the time and location EXIF metadata, thus creates a new issue instead.

**Comment by dmitry-brazhenko** [comment]
Hi
i explord this issue. If there is an interest in this feature, probably I can try to implement it. At least I prototyped it on my laptop and it somehow works

**Comment by dfldylan** [comment]
> Hi i explord this issue. If there is an interest in this feature, probably I can try to implement it. At least I prototyped it on my laptop and it somehow works

It seems that the current version has fixed this issue?
BTW, the only issue I've encountered with panoramic content is that the Immich iOS app can't properly play 360° panoramic videos.

**Comment by dmitry-brazhenko** [comment]
This issue is regarding insta 360 photos, they are custom format. I tried them and they are not properly rendered. 

Regarding mobile app, I am currently pushing another change to support panorama photos first

**Comment by dfldylan** [comment]
> This issue is regarding insta 360 photos, they are custom format. I tried them and they are not properly rendered.
> 
> Regarding mobile app, I am currently pushing another change to support panorama photos first

Okay, okay, I misunderstood it. I’m currently using an automated script on my Windows server that reads INSP or INSV files, converts them to MP4 or JPG, and then saves them back to my NAS, haha.

**Comment by mistic100** [comment]
Here is a discussion and tests about supporting INSP raw files https://github.com/mistic100/Photo-Sphere-Viewer/issues/1787

The general conclusion is that the file itself does not contains enough data to properly stitch the two hemispheres and some serious reverse engineering of Insta360 desktop app would be necessary.

**Comment by dfldylan** [comment]
> Here is a discussion and tests about supporting INSP raw files [mistic100/Photo-Sphere-Viewer#1787](https://github.com/mistic100/Photo-Sphere-Viewer/issues/1787)
> 
> The general conclusion is that the file itself does not contains enough data to properly stitch the two hemispheres and some serious reverse engineering of Insta360 desktop app would be necessary.

There is an official Media-SDK https://www.insta360.com/cn/sdk , but the current version requires a GPU-equiped
