### ISSUE TITLE
[Web] Storage quota is higher than possible

### ISSUE THREAD

**Issue by aviv926** [immich-app/immich#6691]
Currently, a storage quota can be set for the user that is higher than the system is capable of.

When a new storage quota is set and the quota exceeds the current drive size, show a warning message to the administrator.

**Comment by mertalev** [comment]
The storage on the server can be changed at any time, so I'm not sure we should try to enforce a limit based on that. If you set a quota and remove a drive, should it now try to clamp the quota based on that? If yes, then the admin's quota isn't respected if a drive is re-added later. If not, then we're back to square 1 with a quota that's higher than what the storage allows.

**Comment by aviv926** [comment]
> The storage on the server can be changed at any time, so I'm not sure we should try to enforce a limit based on that. If you set a quota and remove a drive, should it now try to clamp the quota based on that? If yes, then the admin's quota isn't respected if a drive is re-added later. If not, then we're back to square 1 with a quota that's higher than what the storage allows.

That's a good thought, I think that in general the system administrator should choose how much storage space there will be for the Immich only, from that he can divide/allocate/limit the amount between the users.

Another option would be to store the available storage space in the database, every time this space is added it could suggest to the system administrator to allocate new space to users.

**Comment by mertalev** [comment]
Maybe we could validate the quota when it's set and from then on just display either the quota or the available storage, whichever is lower. So if the storage was decreased it would look normal, and if it was later increased it would still respect the original quota since the value in the DB never changed.

**Comment by jrasm91** [comment]
I think this is all a bit confusing, but it involves a hypothetical situation where the admin incorrectly sets a limit above the drive capacity, which is odd. I don't think we should make any server changes for this. I would say show a popup warning in this case, but that's probably the only thing I would change.

**Comment by aviv926** [comment]
I think the warning message would be helpful in this case. 
Although Mart's method can be good too.

**Comment by mertalev** [comment]
The pop-up idea seems like the simplest solution.

**Comment by jrasm91** [comment]
I've updated the title/description to indicate the current status. Seems like an easy issue for a new contributor to work on.

**Comment by etnoy** [comment]
Closed via #6737
