### ISSUE TITLE
Time offset in timeline UTC - local time

### ISSUE THREAD

**Issue by DeltaTango69** [immich-app/immich#6799]
Hello,

pictures from my Sony Camera has an offset to the pictures from the mobiles. The difference is the timezone. The only difference in the exif data are that in the mobil pictures are two entrys more.

![image](https://github.com/immich-app/immich/assets/82575543/f88bb548-6255-4302-8a0e-7273109df82f)

![image](https://github.com/immich-app/immich/assets/82575543/0b52447c-ab59-455c-9b2a-d291d0bf50cb)

The "offset" entrys are not in the Sony pictures. Could this be the reason? Other programms only use the information from the datetimeoriginal as Local - time. Than there is no offset in the timeline. 

Windows - time taken!

![image](https://github.com/immich-app/immich/assets/82575543/a905ca4e-817e-4d3f-8dce-dcc72456ef2c)

Immich - Info - one hour difference !

![image](https://github.com/immich-app/immich/assets/82575543/8fbf21e5-a2f1-4d69-8338-b4e64044da70)

Is it possible to use only the datetimeoriginal withou offset?

_Originally posted by @DeltaTango69 in https://github.com/immich-app/immich/discussions/6674_

**Comment by DeltaTango69** [comment]
https://discord.com/channels/979116623879368755/1201824099115216957

**Comment by etnoy** [comment]
This is an issue for DSLRs in general, and google photos even has the same issue!

Either you need to add a timezone field to the metadata of your DSLR photos, or add a default TZ to immich by setting the TZ env variable.

**Comment by etnoy** [comment]
Did you refresh metadata for the image?

**Comment by DeltaTango69** [comment]
Yes of course, as described for photos is working now with the TZ entry. But for videos is now wrong.

**Comment by DeltaTango69** [comment]
My assumption is right - when I delete this

[XMP-xmp] CreateDate : 2024:01:20 11:26:09
[XMP-xmp] ModifyDate : 2024:01:20 11:26:09

from the metadata, then the correct UTC time from the

[QuickTime] CreateDate : 2024:01:20 10:26:09

is used.

I think the best way is to integrate in your list the 

[ItemList] ContentCreateDate : 2024:01:20 11:26:09+01:00

before the createdate. Because here the TZ information is stored.

**Comment by fwsmit** [comment]
I'm also having the same issue. Pictures taken with my sony A7 (first gen) camera have a wrong time offset in immich. The image is taken at 22:14 GMT+1 (ignore that the computer clock is one minute different). When uploaded to immich via the web interface, it shows a time of 23:14 GMT+1, indicating that it added the time zone offset (+1) to the correct time of the image.

The image is attached below. This should be possible to reproduce by just uploading the image with the web interface.
![DSC03509](https://github.com/immich-app/immich/assets/23078054/8aaf3400-4129-4934-8e17-5afa2b8d634d)

**Comment by aviv926** [comment]
For the full discussion regarding the issue on [Discord](https://discord.com/channels/979116623879368755/1206309678578016277):

**Comment by fwsmit** [comment]
The link doesn't work for me. It takes me to an empty channel

**Comment by aviv926** [comment]
> The link doesn't work for me. It takes me to an empty channel

You need to be a member of the server first
https://discord.com/invite/D8JsnBEuKb

**Comment by Namu-Lee** [comment]
Me too have a same problem, when I upload videos without timezone information, it falls to UTC timezone even though I have set the TZ environment variable.

> I have added this env setting and with photos is working now! But now the problem is with videos. Apparently an offset is added to the UTC time.
> 
> Video was taken at 10:26 UTC - 11:26 +01 GMT. Immich shows 11:26 UTC!!!
> 
> ![image](https://private-user-images.githubusercontent.com/82575543/301582665-60506c18-db0a-49ce-8c9a-9f2e11a20aff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjYzMjYsIm5iZiI6MTcwOTg2NjAyNiwicGF0aCI6Ii84MjU3NTU0My8zMDE1ODI2NjUtNjA1MDZjMTgtZGIwYS00OWNlLThjOWEtOWYyZTExYTIwYWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDAyNDcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZDM0NzBkMGY0NjQyM2FkZDYwMjY5YTEyMDY5MjkyMGY4ZDI4MmQ1MzM1MjhlNTY1Njg4OTI2YTUxOTgxMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xBZCGbrkuCrXyKekVaZUKVPISHITXvA4d3JZytdUdrU)
> 
> Here are all times from the metadata
> 
> ======== 20240120112609.mp4 [System] FileModifyDate : 2024:01:20 20:03:01+01:00 [System] FileAccessDate : 2024:02:01 17:38:31+01:00 [System] FileCreateDate : 2024:01:30 17:02:10+01:00 [QuickTime] CreateDate : 2024:01:20 10:26:09 [QuickTime] ModifyDate : 2024:01:20 10:26:09 [Track1] TrackCreateDate : 2024:01:20 10:26:09 [Track1] TrackModifyDate : 2024:01:20 10:26:09 [Track1] MediaCreateDate : 2024:01:20 10:26:09 [Track1] MediaModifyDate : 2024:01:20 10:26:09 [Track2] TrackCreateDate : 2024:01:20 10:26:09 [Track2] TrackModifyDate : 2024:01:20 10:26:09 [Track2] MediaCreateDate : 2024:01:20 10:26:09 [Track2] MediaModifyDate : 2024:01:20 10:26:09 [ItemList] ContentCreateDate : 2024:01:20 11:26:09+01:00 [XMP-xmp] CreateDate : 2024:01:20 11:26:09 [XMP-xmp] ModifyDate : 2024:01:20 11:26:09 [XMP-xmpMM] DerivedFromLastModifyDate : 2024:01:20 11:26:09 [XMP-xmpMM] IngredientsLastModifyDate : 2024:01:20 11:26:09 [XMP-xmpMM] ManagedFromLastModifyDate : 2024:01:20 11:26:09 [XMP-xmpMM] ManifestReferenceLastModifyDate : 2024:01:20 11:26:09 [XMP-xmpMM] RenditionOfLastModifyDate : 2024:01:20 11:26:09 [XMP-xmpMM] VersionsModifyDate : 2024:01:20 11:26:09
> 
> Match would be the createdate under Quicktime and XMP-xmp. Quicktime is UTC and XMP is local time. Maybe therefore is some confusion? I know that the Quicktime value should be right as UTC. When immich use this time than it would be right! ![image](https://private-user-images.githubusercontent.com/82575543/301582941-a99d5b35-fd8a-425f-bd67-2a1d6d13ca1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjYzMjYsIm5iZiI6MTcwOTg2NjAyNiwicGF0aCI6Ii84MjU3NTU0My8zMDE1ODI5NDEtYTk5ZDViMzUtZmQ4YS00MjVmLWJkNjctMmExZDZkMTNjYTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDAyNDcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjODRkMDIzZWQwMzk1OWJmZjI5YTA4YzI2OThlZTJjODFjNWRjZGM5OWM1MDc3NjZjZjhlMmJjZjc0YmNkZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s7XiClT0Nt-ToBE_Z_kTrMsvch8fYHQ_7FugZpAemLQ)

**Comment by DeltaTango69** [comment]
I think for videos the TZ variable is useless because videos with no TZ information are UTC. 
Normally for videos the quicktime:createdate is written with the UTC time!

**Comment by DeltaTango69** [comment]
Solved by myself

**Comment by fwsmit** [comment]
How did you solve the problem? I'm still experiencing the problem, so I don't think the issue should be closed until it's fixed in Immich

**Comment by DeltaTango69** [comment]
See my post before. The exif data was not clear

**Comment by TransRapid** [comment]
Same issue here, also was entirely user error and not knowing QuickTime tags are all UTC. The EXIF tag does not support timezones in the EXIF:DateTimeOriginal or Exif:CreateDate, and XMP times are expected to have the timezone offset in it, and will override most of those things.
