### ISSUE TITLE
[Tech-Debt] Use luxon for user deletion calculation

### ISSUE THREAD

**Issue by jrasm91** [immich-app/immich#6843]
`user.service.ts#isReadyForDeletion` uses Date millisecond parsing, but should use luxon, for a much cleaner implementation.

```typescript
    // TODO use luxon for date calculation
    const msInDay = 86_400_000;
    const msDeleteWait = msInDay * 7;
    const msSinceDelete = Date.now() - (Date.parse(user.deletedAt.toString()) || 0);

    return msSinceDelete >= msDeleteWait;
```

**Comment by manasadepu** [comment]
Hey, first time contributor here. Can I take this issue?

**Comment by manasadepu** [comment]
`import { DateTime } from 'luxon';
    const msDeleteWait = 7 * 24 * 60 * 60 * 1000;
    const deletedAt  = DateTime.fromJSDate(user.deletedAt || new Date(0));
    const msSinceDelete = DateTime.now().diff(deletedAt).as('milliseconds');

    return msSinceDelete >= msDeleteWait;`

**Comment by manasadepu** [comment]
This is my idea for the solution, but should I strive for conciseness?

**Comment by jrasm91** [comment]
Feel free to open a pull request to discuss it

**Comment by danieldietzler** [comment]
Done in #6958
