### ISSUE TITLE
[BUG] iOS 16 - app won't load images or videos

### ISSUE THREAD

**Issue by Sid-Sun** [immich-app/immich#686]
iOS and iPadOS apps won't load images and videos ever since I did bulk upload of images and videos using CLI

The app is working fine on android  and web

Server details:
i7 7700HQ
16 GB Memory
Data is saved on HDD

iPad 8th Gen
iPhone 13
App version: 1.28.3 build.56
Server version: 1.28.3

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file. 
- [x] I have included my redacted `.env` file. 
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Set up service 
2. Use CLI to bulk upload Google Photos Takeout photos and videos to server
3. iOS App won't load images and videos anymore 

**Expected behavior**
Apps continue to work, showing new images and videos

**Screenshots**
![image](https://user-images.githubusercontent.com/22845347/189972925-ff1b8b29-0b96-4680-9793-94245aadbd34.png)
![image](https://user-images.githubusercontent.com/22845347/189972987-be6d0641-0f29-4471-8172-3b63c3b92552.png)

**System**
- Phone OS [iOS, Android]: iOS 16, Android 12
- Server Version: 1.28.3
- Mobile App Version: 1.28.3

**Additional context**
Since the initial symptom, iOS App also sometimes complains about invalid credentials (might be related to network - connected over Tailscale), re-install does not seem to fix the problem

**Comment by alextran1502** [comment]
Can you try the two things here?
1. Clear the cache in the cache setting in the app.
2. Try using local IP to access the instance.

Let me know how it goes.

**Comment by alextran1502** [comment]
Also, have you tried restart the server? Please include the server log when you are browsing the file if you can. 

Did you change any user permission in your docker-compose file?

**Comment by Sid-Sun** [comment]
Hi!

I've tried to clear the cache as well as reinstall the app, it does not help
Tried using local IP directly

I have restarted the server (did it while upgrading today evening and now, images were uploaded before update) here is what i see on `immich-immich-server-1`:
```
immich-immich-server-1            | [Nest] 7  - 09/13/2022, 8:02:45 PM     LOG [WebsocketConnectionEvent] New websocket connection: PZ_eZKBt3tQxWhgaAAAB
immich-immich-server-1            | [Nest] 7  - 09/13/2022, 8:03:23 PM     LOG [WebsocketConnectionEvent] Client PZ_eZKBt3tQxWhgaAAAB disconnected from Websocket
immich-immich-server-1            | [Nest] 7  - 09/13/2022, 8:03:28 PM     LOG [createDeviceInfo] Device Info Exist
immich-immich-server-1            | [Nest] 7  - 09/13/2022, 8:03:28 PM     LOG [WebsocketConnectionEvent] New websocket connection: N_XxIYYk5ujCWK3pAAAD
```
full logs, docker compose and redacted [.env](https://gist.github.com/Sid-Sun/abf8a6a08564770014e723598687e260)

the docker-compose file is unchanged other than enabling logging for proxy container

**Comment by alextran1502** [comment]
We just got similar report on Discord with iOS16 might be the problem here. I updated to iOS16 as well but didn't see any weirdness along with a few others. This might be a bug in the OS. I will keep my eyes out for the additional info from Apple

**Comment by alextran1502** [comment]
Did you also test on your Android and it is not showing up as well?

**Comment by ExcelsiorEyer** [comment]
Just want to add that this is not a one-off case and I’ve been facing the same issue since upgrading to iOS16. Nothing interesting showing up on the logs. 

However in some cases clicking on the failed thumbnails is a hit or miss. It shows the image  sometimes and the rest of the time takes you back to the login page where it doesn’t accept credentials with error “Error logging you in. Check user/password/url”. 

Wait a bit and then the login works but the thumbnail load is wonky still and the issue still remains with some images loading and some not. 

For good measure I tried clearing cache, restarting the entire stack but no luck so far.

**Comment by alextran1502** [comment]
@ExcelsiorEyer Thank you for the report, iOS16 was just out yesterday so obviously there is something going on.

**Comment by alextran1502** [comment]
AND I JUST GOT PAWNED AS WELL! GOOD!!! TIME TO DEBUG

**Comment by Sid-Sun** [comment]
> Did you also test on your Android and it is not showing up as well?

It is showing up on Android, I guess only iOS and iPads are impacted

**Comment by martabal** [comment]
Same problem with iOS 16

**Comment by alextran1502** [comment]
Update on the matter, I updated XCode 14 and build the new version of the app, when loading an instances with existing asset, there were strange error that the image cannot be decoded and therefore skip displaying that image.

Will keep you guys updated with this issue

**Comment by alextran1502** [comment]
Found the issue, the cache manager somehow cannot open the cache on iOS16 - therefore all the cache images cannot be read/write which lead to the error.

**Comment by ExcelsiorEyer** [comment]
This fix didn’t seem to have worked. Thumbnails show up and then starts to disappear. Cache image count keeps fluctuating up and down. 

Let me know if you need any specific information to triage this further.

**Comment by alextran1502** [comment]
@ExcelsiorEyer the new version is not out yet, it is still being reviewed by Apple 😅

**Comment by ExcelsiorEyer** [comment]
Well isn’t this embarrassing 😳. I didn’t pay attention to the fix to the iOS app and was looking at the server version. Thanks for the quick fix.

**Comment by alextran1502** [comment]
Apple is being a nuisance, they reject the app because the `shared with partner` button is grayed out... It has been grayed out for the last 30 versions or so. I have to resubmit the app version with the explanation so that it might be delayed a bit, it is probably available later today

**Comment by ExcelsiorEyer** [comment]
Tested with the new app. Can confirm that the issue is resolved. Thank you!

**Comment by sergiosolorzano** [comment]
Videos that load on browser don't load on Github's app on iphone pro max 12 ios16.5

**Comment by pcgirl** [comment]
IOS 17.0.1 is having a problem with Local Connection.  Can connect using the app from outside the local connection.  Can connect using a browser on iphone when connected locally.  But the app won't connect when connected locally.  Gives a "Server is not Reachable".  I looked into the Local Network settings under Privacy & Security but immich isn't in there.

**Comment by alextran1502** [comment]
@pcgirl when you first use the app to access local instance with local IP, it will ask for permission to access local network, please make sure to allow that. You can restart the app to make sure accepting that permission

**Comment by pcgirl** [comment]
I did and I Allowed but it still says server is unreachable.  I have tried it both with using the ip address IE:  http://192.168.1.100:2238 and also using my dyndns server address.  http://domain.dyndns.org:2238

**Comment by alextran1502** [comment]
@pcgirl please try `http://192.168.1.100:2238/api`

**Comment by pcgirl** [comment]
I did try it that way as well.  Still says server unreachable.

**Comment by alextran1502** [comment]
@pcgirl are your phone on the correct network?
