### ISSUE TITLE
play video black screen

### ISSUE THREAD

**Issue by ecJon** [immich-app/immich#6874]
### The bug

phone model xiaomi 13 ultra,play video black screen but have sound in apk 1.94.0 and 1.94.1,but 1.93.3 is running good!

### The OS that Immich Server is running on

debian

### Version of Immich Server

v1.94.1

### Version of Immich Mobile App

v1.94.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
apk problem
```

### Your .env content

```Shell
apk problem
```

### Reproduction steps

```bash
1.
2.
3.
...
```

### Additional information

apk problem

**Comment by alextran1502** [comment]
The APK isn't released correctly with the hotfix. Will keep this ticket open to remind me to do that

**Comment by MK73DS** [comment]
You can grab the fixed apk there, it's not yet in the release section but it is in Github Action : https://github.com/immich-app/immich/actions/runs/7761456332

**Comment by mertalev** [comment]
Is this issue still relevant?

**Comment by MisterrrX** [comment]
Fixed for me
