### ISSUE TITLE
iOS app asks for permissions to connect to devices on local network

### ISSUE THREAD

**Issue by samip5** [immich-app/immich#6922]
### The bug

![image](https://github.com/immich-app/immich/assets/1703002/6ea763b7-3740-40e4-9684-7222fc1245a4)

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

1.94.1

### Version of Immich Mobile App

1.94.1 build.137

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Open Immich app
2. See that it asks for the permission for no apparent reason.
```

**Comment by alextran1502** [comment]
Not a bug, since many folks connect to local IP

**Comment by samip5** [comment]
> Not a bug, since many folks connects to their instance using the local IP address

It's a bug when one doesn't use LOCAL IP address and the message should tell the user why it's needed which should be doable according to Apple's docs.
