### ISSUE TITLE
Broken link to default.conf.template in docs

### ISSUE THREAD

**Issue by melvinsh** [immich-app/immich#6932]
### The bug

There is a broken link to default.conf.template in docs. I cannot find the correct path so I am assuming the file got deleted. 

https://github.com/immich-app/immich/blob/ce6dc3b7af5a31f31636d4c2e1160c22f53fd0e8/docs/docs/administration/reverse-proxy.md?plain=1#L13

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by bo0tzz** [comment]
Seems like that's referencing the old config for the nginx instance that used to be included in Immich. I think it can be removed.
