### ISSUE TITLE
Search returns completely random results

### ISSUE THREAD

**Issue by diyoyo** [immich-app/immich#6949]
### The bug

Well, not sure whether it is random, but it is highly inaccurate. I'm typing part of the filename of a picture and never get the right result.

### The OS that Immich Server is running on

Debian (RPiOS Lite, latest)

### Version of Immich Server

v1.94.1

### Version of Immich Mobile App

v1.94.x latest

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Unchanged
```

### Your .env content

```Shell
Unchanged
```

### Reproduction steps

```bash
1. Make sure all the scans are done
2. Type a search in the main search bar, using a filename
3. Check results' relevance
...
```

**Comment by alextran1502** [comment]
file name search right now will need to be used with the `m:` syntax, so `m:IMG_123`

**Comment by diyoyo** [comment]
Indeed, but it doesn't work with partial names though, does it?

**Comment by alextran1502** [comment]
@diyoyo Do, it doesn't work with partial names at the moment. I think we will make it work with partial name at a later time
