### ISSUE TITLE
[Feature]: Admin - Delete Users

### ISSUE THREAD

**Issue by puregreen59** [immich-app/immich#695]
### Feature Details:
- [ ] In user management on the web interface, add option to delete user

### Platform
Server & Web

**Comment by NeleB54Gold** [comment]
Hi, I'm new to this immich app, it's the perfect app, or almost...
Did you find any way to delete the user from the postgresql database on docker?

**Comment by PrivateGER** [comment]
I'll do this one. :)

**Comment by zkhan93** [comment]
Is this stuck for some reason ?

**Comment by alextran1502** [comment]
@zkhan93 PR #788 is opened, and I put in a few comments. I haven't seen any movement from @PrivateGER since

**Comment by zkhan93** [comment]
@alextran1502   I saw your comment and I agree with the soft delete approach.
how should I proceed, raise a new PR or continue on the existing one ? 
Not sure how I can continue on the same PR, perhaps some git magic commands.

**Comment by alextran1502** [comment]
> @alextran1502   I saw your comment and I agree with the soft delete approach.
> 
> how should I proceed, raise a new PR or continue on the existing one ? 
> 
> Not sure how I can continue on the same PR, perhaps some git magic commands.   

@zkhan93 please create a new PR, it will be easier on your side

**Comment by PrivateGER** [comment]
Hey, sorry, stuff got a bit busy, and I had to focus on another project for the time being.
I could help @zkhan93 out along the way, but won't be leading this PR.

**Comment by alextran1502** [comment]
@PrivateGER no worries, completely understand! @zkhan93 can help!

**Comment by zkhan93** [comment]
@alextran1502 what is the command to generate new migrations ? 
been struggling for a while to get the command.
I see `typeorm` command is defined in package.json,
so I figured the command is something like this
`npm run typeorm migration:generate`  and datasource option is `-d ./libs/database/src/config/database.config.ts` but not sure about other parameters.

**Comment by alextran1502** [comment]
@zkhan93 
Here is the guide from another unmerge PR

## How to run database migration

1. Attached to the container shell
2. Run `npm run typeorm -- migration:generate ./libs/database/src/<migration-name> -d libs/database/src/config/database.config.ts`
3. Check if the migration file makes sense
4. Move the migration file to folder `server/libs/database/src/migrations` in your code editor.

**Comment by zkhan93** [comment]
nice! BTW this should go in contributors guide

**Comment by alextran1502** [comment]
> nice! BTW this should go in contributors guide

Agree forgot to put it in T_T
