### ISSUE TITLE
Assets report switched width & height

### ISSUE THREAD

**Issue by martyfuhry** [immich-app/immich#7002]
### The bug

I have a video asset that is being reported as 2160 x 3840 (height x width), but this is clearly reversed.

![image](https://github.com/immich-app/immich/assets/100457/358ce954-8950-44b4-91ff-c26b811f7f2a)

![image](https://github.com/immich-app/immich/assets/100457/7fabfcaf-689b-438b-9d28-8dfb1de2b4c5)

### The OS that Immich Server is running on

ubuntu

### Version of Immich Server

1.94.1

### Version of Immich Mobile App

1.94.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
na
```

### Your .env content

```Shell
na
```

### Reproduction steps

```bash
na
```

**Comment by martyfuhry** [comment]
It's reported as height x width in the code, too.

![image](https://github.com/immich-app/immich/assets/100457/fd7ebc26-3aeb-4131-924f-48ada217466d)

**Comment by martyfuhry** [comment]
Other videos (taken by the same person on the same phone) are fine, but they were taken in landscape mode instead of portrait:

![image](https://github.com/immich-app/immich/assets/100457/8b3a96a2-d450-4b16-a1dd-3e9c5547fef4)
![image](https://github.com/immich-app/immich/assets/100457/ff67b3d8-6f6f-4043-9a3c-12abcc46431c)

**Comment by waclaw66** [comment]
Dup of https://github.com/immich-app/immich/issues/3569
