### ISSUE TITLE
[Feature]: Re-index existing photos with machine learning

### ISSUE THREAD

**Issue by dorianim** [immich-app/immich#702]
### Feature detail

I recently got the machine-learning container to work thanks to the guide over here https://github.com/immich-app/immich/discussions/300
.

Now, I'd like all the pictures I added before getting it work to be indexed. This feature might also be helpful in the future, should there ever be changes to the machine learning which require re-indexing.

### Platform

Server

**Comment by dorianim** [comment]
This works now since https://github.com/immich-app/immich/releases/tag/v1.31.0_49-dev

**Comment by dorianim** [comment]
Oh no, nevermind. This only works for photos which have not yet been indexed...

**Comment by alextran1502** [comment]
> Oh no, nevermind. This only works for photos which have not yet been indexed...

And it should solve this issue, shouldn't it?

**Comment by dorianim** [comment]
It solves the original problem, yes. But it does not re-index all photos (as in the title). It only indexes non-indexed photos.

**Comment by alextran1502** [comment]
Why would we need to re-indexing all the photos for machine learning if it has been indexed? I assume it only apply to the scenario where you change the model?

**Comment by dorianim** [comment]
Yes, a change in the model is the only use case. You may close this issue, if you are sure the model will never change, but if it will, this will be very good to have. It doesn't have to be so complicated, could just delete all machine learning results before starting the currently implemented mechanism.

**Comment by alextran1502** [comment]
@dorianim Got it, this will be helpful for that when it happens then. I will leave this open as we are having a contributor working on facial recognition which will need to reindex the whole library. 

Thank you for making it clear

**Comment by alextran1502** [comment]
Implemented with the Job page
