### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JamieSlome** [immich-app/immich#704]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@vautia) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by zackpollard** [comment]
Hey Jamie,

We will absolutely get that setup, if you want to discuss this faster if you join the discord I can add you to a secure channel where we can discuss this. Discord is in the README.

Cheers!

**Comment by alextran1502** [comment]
Hi @JamieSlome , if you don't use Discord, you can also email me at alex.tran1502@gmail.com and I can relay the message back to the team!

Thank you for helping us looking into this

**Comment by zackpollard** [comment]
SECURITY.md was added
