### ISSUE TITLE
[Feature]: Add to shared album

### ISSUE THREAD

**Issue by PixelJonas** [immich-app/immich#708]
### Feature detail

As a user, I want to add pictures to a shared album quickly
So that I can share photos I've just taken with one or multiple people

When entering the main view of the app, I want to be able to select one or multiple images and quickly add them to one of my albums (ordinary or shared)

### Platform

Mobile App

**Comment by matthinc** [comment]
Implemented in https://github.com/immich-app/immich/pull/901

**Comment by alextran1502** [comment]
@martyfuhry I believe this has not been implemented from the user-is-shared-with side. Please feel free to open a PR.

Thank you for the offer :)

**Comment by martyfuhry** [comment]
Excellent! Would you like me to open a new issue with the specific details of what I purpose? Or would you prefer to reopen this issue? In either case, the main important features to us are:

- Add photo to album (shared or otherwise) from the detail view
- Add photo to shared album while multiselected from the main timeline

**Comment by alextran1502** [comment]
@martyfuhry let me reopen this issue.

**Comment by martyfuhry** [comment]
I'd also like to add the ability to add shared albums while selecting multiple assets from the main timeline. I'm happy to make another contribution with this feature. Here is a screenshot of the existing add to album UX from Immich:

![image](https://user-images.githubusercontent.com/100457/215104512-1ba617cc-43f9-4660-ab82-493eac8d4589.png)

I'm happy to change the below "Add to album" to use the same UI I came up with #1413. Something like this below:

![image](https://user-images.githubusercontent.com/100457/215105489-b10f19b7-db14-42eb-a0f1-f249932d2ec8.png)

Of course, with the proper colors and styling. What do you think?

**Comment by PixelJonas** [comment]
I like it

**Comment by martyfuhry** [comment]
This should be good to close now, right?
