### ISSUE TITLE
[BUG] Redis connection failed - connect ECONNREFUSED

### ISSUE THREAD

**Issue by ttran06** [immich-app/immich#713]
**Describe the bug**
After upgrading to the newest version of Immich, I couldn't connect to my server. After inspecting the logs, I found that there was a connection error to Redis

**Screenshots**
![Screenshot2](https://user-images.githubusercontent.com/37080369/190889065-f9ec9137-91d1-4e94-8475-b67c182a2f50.png)

**Comment by alextran1502** [comment]
Can you provided the requested items for when opening a new issue?

**Comment by alextran1502** [comment]
Also, did you change the port in the `immich-proxy` according to the latest release note? 

https://github.com/immich-app/immich/releases/tag/v1.29.0_42-dev

**Comment by ttran06** [comment]
Sorry about that. I did not. Thanks for the help!
