### ISSUE TITLE
Index existing upload folder 

### ISSUE THREAD

**Issue by FelixHaimmerer** [immich-app/immich#714]
### Feature detail

Hello there,

I really love this project and want to use it for all my photos. 

It would be great if there is a way to move all the pictures to the upload folder of the users. And then start a job to get Immich looking over the existing uploads, figure out whats new and add them to the database. Like a reindex of the uploads.

Thanks!

### Platform

Server

**Comment by bo0tzz** [comment]
Duplicate of #7 and #34
