### ISSUE TITLE
[Feature]: Support uploading selected files

### ISSUE THREAD

**Issue by voidshard** [immich-app/immich#715]
### Feature detail

(I apologise if you can do this and I'm simply blind) but I'd love to be able to select & upload particular files rather than(/in addition to) simply selecting an entire album. I mean, not every photo is worth backing up right? :smiley: 

### Platform

Mobile App

**Comment by alextran1502** [comment]
You can do this by creating a folder or album in the native photos gallery app of your phone and move all the pictures you would like to back up in there. Then select that folder/album to be backup in Immich
