### ISSUE TITLE
Quota Bug after deleting ext-library

### ISSUE THREAD

**Issue by AverTry** [immich-app/immich#7196]
### The bug

If I apply a quota, of 20GB, for example, then delete an external library of 1TB, I now have a quota of 20GB + 1TB in negative numbers.

### The OS that Immich Server is running on

OMV Debian11

### Version of Immich Server

v1.94.1

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Your Compose Examples
```

### Your .env content

```Shell
Your env example.
```

### Reproduction steps

```bash
1. set up a quota
2. delete an external library path
3. See the result in bottom left quota limit after refresh
...
```

### Additional information

Thank you for this App.

**Comment by jrasm91** [comment]
I believe this has been fixed.
