### ISSUE TITLE
[Feature]: Web Demo

### ISSUE THREAD

**Issue by meichthys** [immich-app/immich#720]
### Feature detail

It would be nice to have a web demo that potential users could use to get a quick look and feel of the web app.
If added, we could also update Immich's feature set here: https://github.com/meichthys/foss_photo_libraries

### Platform

Web

**Comment by bo0tzz** [comment]
There is a demo instance at https://demo.immich.app/ (temporarily offline, it will be back today), it's just not linked to from anywhere yet.

**Comment by meichthys** [comment]
Ok thanks! Can I link to it from the foss_photo_libraries repo?

**Comment by bo0tzz** [comment]
That's cool with me. @alextran1502 are you OK with starting to get the demo instance out there?

**Comment by alextran1502** [comment]
@bo0tzz Yes I am ok with that

**Comment by wasacoder** [comment]
can mobile app connect to  https://demo.immich.app with  the demo user? 
I tried, but failed. How could I  set the server endpoint url when connected to https://demo.immich.app ?

**Comment by bo0tzz** [comment]
For the url in the app, you need to add `/api` to the end, so: https://demo.immich.app/api
