### ISSUE TITLE
[BUG] Videos disappeared from the app but still exist on webui with latest update

### ISSUE THREAD

**Issue by Thormir84** [immich-app/immich#722]
**Describe the bug**
After the last update (app + server), all videos disappeared from the android app but still exist on webui.
When the app is open, the backup process start and all videos are in queue for a new upload.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [V] I have read thoroughly the README setup and installation instructions.
- [\] I have included my `docker-compose` file.
- [\] I have included my redacted `.env` file.
- [V] I have included information on my machine, and environment.
![Immagine 2022-09-19 102550](https://user-images.githubusercontent.com/88670732/190978868-90e82410-d59a-4f52-8038-3d542c0021af.jpg)

**To Reproduce**
1. Update the server to 1.29.2 and the app to 1.29.1 build 43.
2. Open the app.
3. All photos are ok but all video disappeared.
4. Go to backup settings and the upload of all the videos will start again.

**Expected behavior**
NULL

**Screenshots**
![Screenshot_20220919-095104](https://user-images.githubusercontent.com/88670732/190978898-d3664884-299c-4d72-a50e-3c65a65d5aae.jpg)
![Screenshot_20220919-095013](https://user-images.githubusercontent.com/88670732/190978904-e09588b8-75e3-42c3-ac29-fbda856b8934.jpg)
![190978909-ffa1a9bc-ef43-4f1e-8cb1-a81bdd7a9c62](https://user-images.githubusercontent.com/88670732/190983377-b26b5ad3-6b1e-409f-8403-fc446c857488.jpg)
![Screenshot_20220919-104913](https://user-images.githubusercontent.com/88670732/190982032-d1c1f7f1-fefe-4c4f-a097-213c9ededd49.jpg)
![Screenshot_20220919-110323](https://user-images.githubusercontent.com/88670732/190984298-04cee081-7f87-4325-a94f-81cb8150b3ac.jpg)

**System**
- Phone OS [iOS, Android]: Android 12 with One UI 4.1 on Samsung Galaxy A53
- Server Version: 1.29.2
- Mobile App Version: 1.29.1 build 43

**Additional context**
NULL

**Comment by alextran1502** [comment]
Fix in #724
