### ISSUE TITLE
In the search filter the order of people changes with each selected person

### ISSUE THREAD

**Issue by joytrekker** [immich-app/immich#7256]
### The bug

If you click `See all people` in the new seach filter and select a person the order changes each time you click a person. 

### The OS that Immich Server is running on

Docker on debian

### Version of Immich Server

v1.95

### Version of Immich Mobile App

NA

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. Expand the search filter.
2. Expand the people section by cliking `See all people`
3. Select a person (People will now be sorted in reverse)
4. Select another person (People will be sorted correctly in descending order)
5. The order changes back and forth with each selected person.
```

**Comment by alextran1502** [comment]
Not a bug but rather a design decision, so all of the people you select will be shown at the start of the list

**Comment by joytrekker** [comment]
Yes I know that is intended. It should be just pop the selected person from the list. However the entire list of people is reversed with every new selection. All unselected people are resorted between ascending and descending with every selection making it hard to find and select new people. I have seven rows of people and if want to select the last three then I click one and it moves to the the top as intended but the entire list is now in reverse and I have to scroll to the top find and select the second. Then the list reorders again and I have to scroll to the bottom to select the third.
