### ISSUE TITLE
default search action (confirm with enter) is not working

### ISSUE THREAD

**Issue by titro** [immich-app/immich#7260]
### The bug

In the new search form the default action for confirming with enter key is not search

### The OS that Immich Server is running on

unraid

### Version of Immich Server

v1.95.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. use the new search form
2. type some input in the context field
3. confirm with enter key
4. you do not see search results but all photos again without any search criteria
```

**Comment by mmomjian** [comment]
I can confirm this. Searching by using the "settings" dropdown, and clicking Enter in the "context" field, returns `No results
Try a synonym or more general keyword`

**Comment by titro** [comment]
> I can confirm this. Searching by using the "settings" dropdown, and clicking Enter in the "context" field, returns `No results Try a synonym or more general keyword`

confirm. But only if the results of the settings dropdown are already loaded/used. if you use a fresh search form and use the settings AND context field, it will show all photos again without any search criteria filtered
