### ISSUE TITLE
[Feature]: Add federation to share albums with users from other immich servers

### ISSUE THREAD

**Issue by anbraten** [immich-app/immich#728]
### Feature detail

As a user I would like to share images. In addition to sharing with users of my instance, public users via link (see #265), I would like to be able to share with a user from another immich instance.

__What's the benefit over "simply" sharing with a link?__

- The other user could be allowed to edit the album
- By sharing with an explicit user from an other instance this user would be able to sync the shared photos to his instance as well

### Platform

Server

**Comment by bo0tzz** [comment]
Thanks for the suggestion! Federation between instances is not something that we currently consider in scope for Immich. As for the specific features you mention, editing shared albums as an external user is something that is already planned in that feature. Syncing photos from a shared album is you could accomplish with a fairly small external script using the Immich API.

**Comment by axgdcode** [comment]
I wanted to ask if discussions like this one [GitHub Issue #728](https://github.com/immich-app/immich/issues/728) are going to be reopened following the merger with FUTO. Zack mentioned this topic during the YouTube conference (you can watch it here: [link to the conference](https://www.youtube.com/live/cwz2iZwYpgg?feature=shared&t=4818)), and I still believe it's a critical point for positioning against giants like Google Photos or iCloud.

Personally, I think adopting ActivityPub would open up incredible possibilities for connecting to other applications.

What do you all think? Is this part of the future plans?

Thanks for your responses!

**Comment by domacikolaci** [comment]
Any chance this could reenter the roadmap?

With FUTO funding and the project coming such a long way, it would be amazing to see this on the roadmap even as a "down the line" consideration.

I would love to have the ability to "connect" my server with my mates server so we can share albums and data between each other and allow our users to share data between each other. For anyone from a corporate Microsoft background, this B2B integrations with SharePoint and Teams as an example.

**Comment by axgdcode** [comment]
I am 100% on board with saying that it's missing from the current roadmap. Google's shared album features are super attractive to users. A similar feature in Immich is more complex because we are in a multi-instance system. One of the Immich members talks about it in this conference: https://www.youtube.com/watch?v=F_2oydlnpCQ, so I remain hopeful. It's the feature I also miss to use Immich on a daily basis.

**Comment by MrModest** [comment]
Just willing to share my vision of the implementation of this feature, if the team ever will have time for this :D

https://github.com/immich-app/immich/discussions/13620
