### ISSUE TITLE
TRANSCODE VIDEOS Stop working 

### ISSUE THREAD

**Issue by mingqlin** [immich-app/immich#7280]
### The bug

Build [v1.95.0] TRANSCODE VIDEOS stop transcode video, it appears that just copy the file directly into the transcoded folder, and treat it as done. 

In previous Immich version, when transcode is working, my server cpu in heavy load, this version v1.95.0, when the transcode running, CPU has no load, and going through my 30000 video very fast, and my storage run out fast. I have downloaded a newly encoded video (get it from "encoded-video" folder), this is Media Info, my setting for encode video is 720p, result video is still in original 1080p 120fps

Video: MPEG4 Video (H264) 1920x1080 119.88fps 98382kbps [V: Video Media Handler (h264 high L5.1, yuv420p, 1920x1080, 98382 kb/s)]
Audio: AAC 48000Hz stereo 128kbps [A: Sound Media Handler (aac lc, 48000 Hz, stereo, 128 kb/s)]

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.95.0

### Version of Immich Mobile App

v1.95.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Unraid
```

### Your .env content

```Shell
Unraid
```

### Reproduction steps

```bash
Transcode any video
```

**Comment by mertalev** [comment]
This was changed in #7106 since some users want only the stream that requires transcoding to be transcoded. You can change the transcode policy to make resolution part of the policy so it transcodes the video stream too.

**Comment by mingqlin** [comment]
I have posted comment in  #7106

**Comment by mertalev** [comment]
Also, could you share your transcoding settings? In particular, did you change the target audio codec? It should only be copying the video stream if it needs to transcode the audio stream, and it shouldn't transcode AAC audio unless you changed the target audio codec.

**Comment by mingqlin** [comment]
the transcoding setting is the default, no change:

![image](https://github.com/immich-app/immich/assets/39827861/71515136-156b-43be-96fd-bd9de673da67)
![image](https://github.com/immich-app/immich/assets/39827861/055f3142-dc94-4f9f-a5bb-8525e58d99ef)
![image](https://github.com/immich-app/immich/assets/39827861/722b2dcb-1965-4028-935d-df5a2e31db2f)
![image](https://github.com/immich-app/immich/assets/39827861/58b7d975-0866-4d59-809f-7347aa36c291)

**Comment by mertalev** [comment]
The default behavior will be changed with #7283 to avoid this situation unless the user chooses not to accept a certain audio codec. The other part of this issue is the fact that these videos shouldn't be transcoded based on your transcoding settings. I'll have to dig more into this to see if there's a gap in the test coverage.
