### ISSUE TITLE
[Feature]: Add a extra security layer

### ISSUE THREAD

**Issue by murmelbahn** [immich-app/immich#729]
### Feature detail

Hi,
immich is really great and I like it but one thing need to be changed.
We should be able to use fail2ban for failed login attempts. Is it possible to write to a logfile outside the container
these attempts with the IP of the "attacker"?

Another nice feature would the implementation of a 2fa provider for an extra layer of security.

Thanks for this wonderfull project!

### Platform

Web

**Comment by pluja** [comment]
I second that it would be a very good "extra security layer" for the login part to have 2FA like a TOTP code.

**Comment by bo0tzz** [comment]
IP logging would be accomplished with #732. 2FA would be covered by the already planned OAuth feature (#33).

**Comment by phuripatwattanakul** [comment]
Guten Tag,
wie schränke ich bitte den Zugang zu meiner "Immich-App" mit der OAuth Funktion ein?
Wenn ich einen Benutzer (es ist meine eigene Entscheidung, wer meine Alben sehen darf) anlege, kann er mit eMail-Adresse+Passwort auf meine Instanz zugreifen. Wie funktioniert es nun, dass auch nur von mir berechtigte Benutzer sich mit OAuth anmelden können?
Funktioniert dies nicht, so würde eine 2FA-Funktion die Sicherheit der eMail-Adresse+Passwort erhöhen.
Nach meinen bisherigen Informationen sind 2FA und OAuth zweierlei Dinge.
Weiter sollte eine Nutzung beider Funktionen für den Betreiber seiner "Immich-App" einfacher lösbar sein, es sind eben nicht alle Nutzer dieser App Fachkräfte in Linux oder Administratoren, sondern Hobby-Fotografen. ;)
