### ISSUE TITLE
BUG(Web): Search allows broken/false place filters

### ISSUE THREAD

**Issue by JW-CH** [immich-app/immich#7297]
### The bug

When a country filter was set, the state filter shows only states in that country. If I set the state filter and change the country afterward, the search will never return a result because the filter allows a broken configuration. This is also possible with the city filter.

The place filter should work like the camera filter and not allow broken searches.

![image](https://github.com/immich-app/immich/assets/17313367/5796937c-4efe-4b62-bfd2-0d16245cf08a)

### The OS that Immich Server is running on

UnRaid

### Version of Immich Server

v1.95.1

### Version of Immich Mobile App

not needed

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not needed
```

### Your .env content

```Shell
not needed
```

### Reproduction steps

```bash
1. Open search page
2. Filter city
3. Filter state (city not in state)
4. Filter country (state not in country)
===============
1. Open search page
2. Filter Country
3. Filter state (State filter shows only states in country)
4. Change country filter, state does not match with country anymore
```

**Comment by aviv926** [comment]
fixed via https://github.com/immich-app/immich/pull/7397
