### ISSUE TITLE
CLI error   Error: Cannot find module '/app/cli/dist/src/index.js'

### ISSUE THREAD

**Issue by ragaimeena** [immich-app/immich#7326]
### The bug

Error: Cannot find module '/app/cli/dist/src/index.js'

when trying to use CLI

node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/app/cli/dist/src/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.11.1

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.95.1

### Version of Immich Mobile App

v1.95.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
unraid
```

### Your .env content

```Shell
unraid
```

### Reproduction steps

```bash
1.
2.
3.
v1.95.1
```

**Comment by martabal** [comment]
That’s an AIO issue https://github.com/imagegenius/docker-immich/issues/307
