### ISSUE TITLE
[BUG] Creates new docker volumes

### ISSUE THREAD

**Issue by piraterx** [immich-app/immich#733]
Every time, I run 

docker compose down 
&
docker compose up -d

it creates new docker volume. - https://imgur.com/ioB46m0

Is it desired process or am I missing something. 

Thanks.

**Comment by zackpollard** [comment]
This is standard docker behaviour. `docker compose down` stops and removes the container. When you run the up command it will create new containers along with new volumes. The postgres volume is a named volume and so will be re-used each time.
