### ISSUE TITLE
[Feature]: Cached albums

### ISSUE THREAD

**Issue by nicopace** [immich-app/immich#735]
### Feature detail

Would be great for the client to cache low resolution version of your album's images, so when you access it you always have information to show, and if you are offline, you have your photos with you even though you might not have access to the full-res one.
It could have a storage cap, so the least used ones are deleted or compressed more...

### Platform

Mobile App

**Comment by akoyaxd** [comment]
Hb

**Comment by lbesnard** [comment]
I think it could be an option also for the shared album, to tick a "cached" box

**Comment by bo0tzz** [comment]
@matthinc would this potentially be covered by #826? Not entirely, since the app currently won't open without an internet connection, but beyond that?

**Comment by matthinc** [comment]
@bo0tzz Not entirely, the app still needs an internet connection for authentication. But now that we have #826, adding offline capabilities would probably be rather easy. I already thought about that.

**Comment by alextran1502** [comment]
The album thumbnail and album's content are now cached in the recent update on the mobile app.
