### ISSUE TITLE
Partial 360 photo / panorama fails to load in web

### ISSUE THREAD

**Issue by OverHash** [immich-app/immich#7364]
### The bug

Specific panoramas that are partial 360 photos will fail to load in the Immich web (note: full 360 photos will succeed). This occurs for about 2 out of 50 or so panorama / 360 photos that I have on my gallery.

### The OS that Immich Server is running on

Synology

### Version of Immich Server

v1.95.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. Import photo provided in Additional Information
2. Attempt to open panorama / partial 360
3. Panorama fails to load with "The panorama can't be loaded" (see Additional Information).
```

### Additional information

Web app after opening the image (note, I believe this is a slightly different image than then the repro. same issue though):
![image](https://github.com/immich-app/immich/assets/46231745/a308f07f-5885-407a-a571-bfdfedd57f7d)

Note that the thumbnail preview before I click to open the Panorama is fine.

Zip containing relevant file: 
[immich-broken-panorama.zip](https://github.com/immich-app/immich/files/14384504/immich-broken-panorama.zip)

When visiting console logs I get two errors:
<details>
  <summary>Console errors</summary>
  
  ```
  PSVError: Unable to detect system capabilities (photo-sphere-viewer-adapter.0VsU8crC.js:3797:25198)
    Immutable 63
    Immutable 60
  
  Uncaught (in promise) PSVError: Unable to detect system capabilities (photo-sphere-viewer-adapter.0VsU8crC.js:3777:5633)
    Immutable 63
      Immutable 6
      map self-hosted:221
      Immutable 27
      InterpretGeneratorResume self-hosted:1465
      AsyncFunctionNext self-hosted:852
      Immutable 4
      forEach self-hosted:203
      Immutable 23
      InterpretGeneratorResume self-hosted:1465
      AsyncFunctionNext self-hosted:852
  ```
</details>

**Comment by Rhyscoch** [comment]
In exif wrong pano type - equirectangular. This photo is not equirectangular. Try remove wrong data.

**Comment by jenda69** [comment]
> In exif wrong pano type - equirectangular. This photo is not equirectangular. Try remove wrong data.

If there's no equirectangular exif tag, panorama viewer won't even start and image gets displayed as a plain 2D image. Also the photo is equirectangular and even if it wasn't, it would just get displayed in a wrong projection.

Does it work in a different web browser? I found there used to be [the same issue](https://github.com/mistic100/Photo-Sphere-Viewer/issues/708) in Brave because of some anti-fingerprinting feature.

**Comment by waclaw66** [comment]
It works for me...

![obrazek](https://github.com/immich-app/immich/assets/15554561/29375a68-bcdb-4bbd-957d-81693d898951)

**Comment by OverHash** [comment]
For clarification I am on Ubuntu 22.04 and using Firefox 124.0.1.

As per @jenda69's comments, I have tried on my phone in the Chrome browser (121.0.6167.180) and it works there. So perhaps this is an issue on Firefox?

> In exif wrong pano type - equirectangular. This photo is not equirectangular. Try remove wrong data.

If this *is* the issue, then perhaps we should enforce this or display some sort of message? But it is confusing that the image loads on some browsers and not others.

**Comment by OverHash** [comment]
I just tried again on my Firefox browser and the image loads fine now. Strange. The only difference I can think of is that I re-ran all jobs manually -- perhaps that fixed it.

Thanks all for your comments and suggestions -- appreciate the time taken!
