### ISSUE TITLE
[BUG] The right-side video player controls are blocked by the next-image button (z-index problem)

### ISSUE THREAD

**Issue by oddlama** [immich-app/immich#740]
**Describe the bug**
The right hand side controls of the video player cannot be clicked in the web interface, as they are overlayed by the "next image" button:

![image](https://user-images.githubusercontent.com/31919558/191875172-d556cfe9-1cfe-4eb3-bd63-ff7dc16d5840.png)

Interestingly, the left hand side is correctly placed such that the video player controls can be used to start/stop/seek the video.

**Task List**
[Not applicable]

**System**
- Server Version: `1.29.4`
- Web browser: `Firefox 104.0.2`

**Comment by alextran1502** [comment]
Damn Firefox and its CSS engine. Fixed though. 😛
