### ISSUE TITLE
Archive items are not migrated with storage template change.

### ISSUE THREAD

**Issue by RavMazurek** [immich-app/immich#7494]
### The bug

As in the title - .96 fixed storage template migration in 95% of the cases but still items that ware in archive AT ANY POINT are not moved (it dosn't help moving them out of archive)

### The OS that Immich Server is running on

Unraid current

### Version of Immich Server

.96

### Version of Immich Mobile App

.96

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
no need
```

### Your .env content

```Shell
no need
```

### Reproduction steps

```bash
1.Have an .95 version of app
2.Have something in archive
3.Change storage template
4.Update to .96
5.Run storage template migration
6.Archive items are left in old structure
7.Don't know if it works for items that ware added to archive after .96
```

**Comment by RavMazurek** [comment]
Seems like having something in trash also blocks it

**Comment by nebb00** [comment]
i might be having the same issue with two users, where 6/12882 and 138/25454 got left behind. I have emptied archive and trash, this didnt help. I downloaded the files from the old folder structure, removed them, tried uploading, and they say they are duplicates. So I restored the folders to ensure they didnt show broken under the repair tab.

**Comment by jrasm91** [comment]
The queries for which assets to migrate have been fixed to include trashed and delete items
