### ISSUE TITLE
[Feature]: USB OTG scan to automatically backup media

### ISSUE THREAD

**Issue by NeleB54Gold** [immich-app/immich#752]
### Feature detail

There are currently no options that allow you to integrate folders on external memories like OTG USB drives...
It would be useful to be able to connect a drive or an external SD adapter to the smartphone and have it instantly on the cloud!
Photographers or all those who film and photograph moments can have an immediate backup simply by inserting the drive or SD into a phone connected to immich (which obviously has already been configured the folder)

I hope it will be a good idea for everyone

### Platform

Mobile App

**Comment by alextran1502** [comment]
Very interesting idea! Can you recommend a drive that you normally use to connect to your phone?

**Comment by NeleB54Gold** [comment]
I use a Kingston Data Traveler 3.0 USB, it's a normal 64GB usb stick, then I use the USB OTG adapter

**Comment by alextran1502** [comment]
Thanks, this is a cool feature but currently out of scope of the project. I will put this as nice to have, once we have tackled all of the core features we will circle back to this.
