### ISSUE TITLE
[Feature]: Don't hardcode nginx's proxy_pass

### ISSUE THREAD

**Issue by stavros-k** [immich-app/immich#756]
### Feature detail

It would be nice if we could change the `immich-server` hostname in the nginx conf.
Maybe with an env var? Making it hardcoded, in deployments like kubernetes/helm, you have to override the whole nginx file to template that value.

### Platform

Web

**Comment by bo0tzz** [comment]
This would be dependent on (or maybe even a duplicate of) #647.

**Comment by stavros-k** [comment]
Yep dupe. Closing this one
