### ISSUE TITLE
[BUG] Web: Scroll bar label is layered behind top bar

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#757]
**Describe the bug**
On the web client, the label that is shown when hovering over the scroll bar on the right hand side of the page falls behind the top bar when they intersect.

![image](https://user-images.githubusercontent.com/11602424/192764386-b65c4b72-1593-482d-96e3-3548b5b641eb.png)

**To Reproduce**
1. Go to the web client.
2. Hover on the scroll bar so the month label appears.
3. Move your mouse up to intersect the label with the top bar.

**Expected behavior**
The label is always clearly visible.

**System**
- Web
- Server Version: `1.29.5`

**Comment by bo0tzz** [comment]
Reopening, as it seems unfortunately this is still (or again?) happening.

**Comment by alextran1502** [comment]
I think there was another PR put in that kinda override the fixed I had

**Comment by alextran1502** [comment]
Fixed in #1018
