### ISSUE TITLE
can see what photos owner of shared album likes

### ISSUE THREAD

**Issue by HarHarLinks** [immich-app/immich#7577]
### The bug

Someone shared an album with me.
I can see their likes.
It is impossible to tell wether the like is mine or theirs, both look the same.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.96

### Version of Immich Mobile App

1.96

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
See above
```

**Comment by martabal** [comment]
Can you be a bit more precise ?
Is it a web or a mobile issue ?
In the activity tab, you can see the names of the people who liked it

**Comment by HarHarLinks** [comment]
The behavior is the same on mobile and web. It might be a Server issue of attributes being visible where they shouldn't.

And no, the activity tab is empty, I'm talking about the "gallery view" within the shared album

**Comment by martabal** [comment]
Oh right, you're talking about favorites.

Indeed, I can reproduce this issue, thanks for the report !
