### ISSUE TITLE
[BUG] `local-reverse-geocoder` creates data in `node_modules`

### ISSUE THREAD

**Issue by nebulade** [immich-app/immich#758]
The newly added dependency `local-reverse-geocoder` tries to create a folder to stash some data within `node_modules/` at `server/node_modules/local-reverse-geocoder/geonames_dump`. This causes problems if `node_modules` is in read-only filesystem if treated like code (in this case for the Cloudron app package).

I am not sure if this should be reported rather with the upstream module to change https://github.com/tomayac/local-reverse-geocoder/blob/main/index.js#L99 to use the process cwd instead of the code file path, or if immich should provide a better folder path at https://github.com/tomayac/local-reverse-geocoder/blob/main/index.js#L618 

I am happy to produce a pull request if the change should be made in immich, otherwise will try to get this into the module itself.

**Comment by alextran1502** [comment]
I am open to see the change in Immich since it will probably be faster and easier to control. Let me know if you have any question.

**Comment by zackpollard** [comment]
I'm happy for us to put this change in immich, we did consider it but didn't think the default path would cause a problem. Feel free to make a PR that corrects this with a sensible default path for storing the data.

**Comment by nebulade** [comment]
The change seems unnecessarily small given that I don't know the codebase conventions, so maybe this works for you? :)
