### ISSUE TITLE
Sharing from a shared album is blocked if one or more assets not owned by user or partner are selected

### ISSUE THREAD

**Issue by samholton** [immich-app/immich#7604]
### The bug

In a shared album, if one or more images that are not owned by current user or partner is selected for share, the share operation results in an error:

![error](https://github.com/immich-app/immich/assets/3507151/a97d2437-597e-462a-b8c8-0d3ab103fa9c)

The same is true for the new single asset sharing. The share button could be hidden for single asset share, but how should we address multi-asset selection and sharing from shared album? Do we create the link but remove those without permission? Somehow alert the user which images they are unable to share?

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.97.0

### Version of Immich Mobile App

v1.97.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
make dev
```

### Your .env content

```Shell
make dev
```

### Reproduction steps

```bash
1. Create shared album
1. Invite user that is not a partner
1. Have each user add images to the shared album
1. Attempt to share from the shared album assets that do not belong to you
```

### Additional information

comment on https://github.com/immich-app/immich/pull/7595

**Comment by jrasm91** [comment]
Hey @samholton is this still an existing issue, or has this been resolved?

**Comment by samholton** [comment]
I'll try to recreate and update tomorrow

**Comment by samholton** [comment]
Yes, reproduction steps still cause an issue. Tested on `v1.114.0`

**Comment by jrasm91** [comment]
Closing in favor of #12614
