### ISSUE TITLE
Missing view permissions when runnig pgvecto.rs and non postgres superadmin

### ISSUE THREAD

**Issue by nebulade** [immich-app/immich#7626]
### The bug

While we are working on changes to enable Immich package upgrades in Cloudron to use the 0.2.* pgvecto.rs extension, we were ruinning in a permission issue for one view only (after the `vectors` schema and upgrade docs are followed): trying to SELECT `pg_vector_index_stat` which by default is not accessible by non superusers.

The fix would be to run `GRANT SELECT ON TABLE pg_vector_index_stat to ${dbuser};` which needs to be run __after__ Immich has started up and ran the db migration scripts to create the extension in the first place. Which makes this not too practical as the users have to start the app, kill it, run the SQL command as superuser, then start the app again.

The code in question here does only exist to check for some required reindexing it seems: https://github.com/immich-app/immich/blob/main/server/src/infra/repositories/database.repository.ts#L135

So I wonder if this is entirely related to how Cloudron isolates app database in postgres or if other users which don't run it with postgres superuser credentials also hit this? Would there be any other way to detect the index freshness? 

The error would be:
```
[Nest] 149  - 03/04/2024, 7:12:29 PM    WARN [DatabaseService] Could not run vector reindexing checks. If the extension was updated, please restart the Postgres instance.
/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219
            throw new QueryFailedError_1.QueryFailedError(query, parameters, err);
                  ^

QueryFailedError: permission denied for view pg_vector_index_stat
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DataSource.query (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:350:20)
    at async DatabaseRepository.shouldReindex (/usr/src/app/dist/infra/repositories/database.repository.js:127:25)
    at async /usr/src/app/dist/domain/database/database.service.js:41:21
    at async /usr/src/app/dist/infra/repositories/database.repository.js:185:23 {
  query: '\n' +
    '          SELECT idx_status\n' +
    '          FROM pg_vector_index_stat\n' +
    '          WHERE indexname = $1',
  parameters: [ 'clip_index' ],
  driverError: error: permission denied for view pg_vector_index_stat
```

### The OS that Immich Server is running on

Cloudron

### Version of Immich Server

v1.97.0

### Version of Immich Mobile App

latest

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
does not apply
```

### Your .env content

```Shell
does not apply
```

### Reproduction steps

```bash
does not apply
```

**Comment by nebulade** [comment]
Oh maybe this should have rather been an entry in the discussion section :/ I don't seem to be able to convert it now though

**Comment by alextran1502** [comment]
@VoVAllen Hello, my apologies for the ping, do you have any insights or suggestions on this issue?

**Comment by mmomjian** [comment]
This is not specific to Cloudron, I had the same on my personal non-SU install of Immich. You can start digging [here](https://github.com/immich-app/immich/discussions/7252#discussioncomment-8534336) for some other caveats.

**Comment by mertalev** [comment]
I believe you can create the `vectors` schema in advance and grant permissions to that schema instead of targeting the view directly.

**Comment by VoVAllen** [comment]
I think this is related to the vector schema permission. Your user doesn't have permission to it. You can do `ALTER SCHEMA vectors OWNER TO <immich username>.` or `GRANT ALL ON SCHEMA vectors TO <immich username>;`

Similar issue I found: https://github.com/immich-app/immich/discussions/7398#discussioncomment-8579931

**Comment by nebulade** [comment]
Thanks for all your input. In our case the schema is created and owned by the immich db user. This happens prior to the Immich migration scripts creating the extension, as otherwise the `vectors` schema would be owned by the superuser, despite `CREATE EXTENSION` getting called by the immich user, but that seems like other postgres extensions also work and all other objects like types and function from the extension within that schema are also owned by the superuser. Only the VIEW object `pg_vector_index_stat` has this issue due to that one SELECT. I don't think it would be accessed by Immich anywhere else.

**Comment by nebulade** [comment]
On further investigation, there are also code paths like https://github.com/immich-app/immich/blob/main/server/src/infra/repositories/database.repository.ts#L160 which will never work as such in an environment where Immich does not run with superuser privileges. So maybe a more wholesome change would be for Immich to be better prepared to run with a less privileged database user. Though as far as I understand also from the changelog entry for such a setup, those code paths should not be hit anyways already, if the admin performs the extension upgrade manually. If anyone could confirm this, we could maybe prepare a patch?

**Comment by nebulade** [comment]
Thanks for the hint. So seems like the main outstanding question then is, if having SELECT permissions for the  `pg_vector_index_stat` view can somehow be circumvented for non superuser setups and if not if there will be more permissions required for extension specific objects. 

I don't know the purpose of that view (like is this some internal object or supposed to be for an app), but given that all objects from the extension seem to be created with the superuser being the owner, despite creating the extension is run by the Immich db user, either it may not be designed to be exposed or the extension should have created it in the first place with the user the extension was created.

**Comment by mertalev** [comment]
It's intended to be viewed, not just an internal view (see [here](https://docs.pgvecto.rs/usage/monitoring.html)). It might be good to make an upstream issue for this since I don't think this behavior is intentional.

**Comment by VoVAllen** [comment]
Sorry, I didn't get what the core issue is here. Is it that the schema permissions are not taking effect on pg_vector_index_stat, or do you expect it to work without requiring additional permissions?

**Comment by mertalev** [comment]
> Sorry, I didn't get what the core issue is here. Is it that the schema permissions are not taking effect on pg_vector_index_stat, or do you expect it to work without requiring additional permissions?

I think the general issue described is that even though everything else in the extension is accessible with a certain set of permissions for the vectors schema, the view itself is not and becomes a special case.

But I'm a little confused as well by these lines since you can't create pgvecto.rs as a non-SU immich user:
> Immich has started up and ran the db migration scripts to create the extension in the first place
> ...This happens prior to the Immich migration scripts creating the extension, as otherwise the vectors schema would be owned by the superuser, despite CREATE EXTENSION getting called by the immich user

I feel like there's some confusion about when the extension is actually being created because it sounds like it's created by a superuser before Immich runs.

**Comment by VoVAllen** [comment]
We'll add `GRANT SELECT ON TABLE pg_vector_index_stat to PUBLIC` in the extension SQL in the next release

**Comment by nebulade** [comment]
@VoVAllen yes we have started to add this in the migration code paths. This mitigates the issue. Thanks for following up here and I guess we can actually close this then, with the fix in the extension. Thanks everyone!
