### ISSUE TITLE
Correcting the Library name to an External Library

### ISSUE THREAD

**Issue by aviv926** [immich-app/immich#7686]
### The bug

On the system administrator page under settings, the library  option appears, it is easy to get confused between the main library and an external library since this option is specifically for external library.

I think changing the name will make the definition clearer for the new user.

Especially when it can be turned on even if there is no external library.

![image](https://github.com/immich-app/immich/assets/51673860/b6b8c549-672f-4dd9-b731-1ecdcc1e1ede)

In addition, it is worth changing Encode CLIP to Smart Search following the new versions

![image](https://github.com/immich-app/immich/assets/51673860/e78b6784-99e1-4f8b-af29-5f7c9800fbab)

### The OS that Immich Server is running on

Main Demo

### Version of Immich Server

Main Demo

### Version of Immich Mobile App

Main Demo

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Main Demo
```

### Your .env content

```Shell
Main Demo
```

### Reproduction steps

```bash
1. Administration -> System Settings -> Library
```

**Comment by declan8010** [comment]
I have submitted a pull request for this item - #7744

**Comment by aviv926** [comment]
fixed via https://github.com/immich-app/immich/pull/7744
