### ISSUE TITLE
Upgrade from 1.97.0 to 1.98.0 failing

### ISSUE THREAD

**Issue by szinn** [immich-app/immich#7727]
### The bug

Migration "AddExtensionToOriginalFileName1709763765506" failed, error: could not read block 55 in file "base/18136/18358": read only 0 of 8192 bytes
/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219
            throw new QueryFailedError_1.QueryFailedError(query, parameters, err);
                  ^

QueryFailedError: could not read block 55 in file "base/18136/18358": read only 0 of 8192 bytes
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddExtensionToOriginalFileName1709763765506.up (/usr/src/app/dist/infra/migrations/1709763765506-AddExtensionToOriginalFileName.js:6:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/infra/repositories/database.repository.js:177:9)
    at async /usr/src/app/dist/domain/database/database.service.js:52:13
    at async /usr/src/app/dist/infra/repositories/database.repository.js:185:23 {
  query: '\n' +
    `      WITH extension AS (WITH cte AS (SELECT a.id, STRING_TO_ARRAY(a."originalPath", '.')::TEXT[] AS arr\n` +
    '      FROM assets a)\n' +
    '      SELECT cte.id, cte.arr[ARRAY_UPPER(cte.arr, 1)] AS "ext"\n' +
    '      FROM cte)\n' +
    '      UPDATE assets\n' +
    `      SET "originalFileName" = assets."originalFileName" || '.' || extension."ext"\n` +
    '      FROM extension\n' +
    '      WHERE assets.id = extension.id;\n' +
    '      ',
  parameters: undefined,

### The OS that Immich Server is running on

Talos/kubernetes

### Version of Immich Server

v1.98.0

### Version of Immich Mobile App

v n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
https://github.com/szinn/k8s-homelab/tree/main/kubernetes/main/apps/media/immich/app
```

### Your .env content

```Shell
https://github.com/szinn/k8s-homelab/tree/main/kubernetes/main/apps/media/immich/app
```

### Reproduction steps

```bash
1. upgrading from 1.97.0 to 1.98.0
2. both microservice and server pods reporting issue
3.
...
```

**Comment by mmomjian** [comment]
The error `error: could not read block 55 in file` indicates that the Postgres database is probably corrupted. You should probably restore from backup and consider assessing the stability of your underlying filesystem using fsck and/or smartctl.

**Comment by jrasm91** [comment]
I think this can also happen because the index is corrupt, so it might be worth rebuilding them.

cc: @mertalev

**Comment by szinn** [comment]
all is running just fine with .97.  My postgres database is running with 2 replicas besides the primary and the underlying storage has multiple replicas as well. Any hints as to what is corrupt and why you think that? How do I rebuild the index in 1.97.0?

**Comment by szinn** [comment]
On 1.97.0 ran repair and the same error is showing up in the log.

is there a postgres way to fix things? I can go back to backups too tomorrow

**Comment by szinn** [comment]
Have to say that the last few updates have been a real pain and did not go smoothly (since introduction of pg vector stuff)

**Comment by mertalev** [comment]
Judging by where the error happened, I think the issue is related to the `assets` table and/or an index on the path column. `VACUUM FULL assets` could possibly fix it.

**Comment by szinn** [comment]
did vacuum on the assets table followed by check all / repair all (6 got corrected), restarted microservices and server, check all and no issues found. Did the upgrade and it proceeded fine and all appears good.

Interesting issue for sure

**Comment by NZPy7h0n** [comment]
Just a note to say I had this too, same fix worked but seems rather strange as DB was fine before upgrade.

**Comment by monotok** [comment]
I had the same issue, going from 1.95.1 to 1.98.1. Just ran the `VACUUM FULL assets;` command on the DB and restarted the containers. All started working. 
I have tried to not update as often recently due to the number of DB changes but after a while the mobile app stops working as it auto updates.
