### ISSUE TITLE
[Feature]: Exclude System Files When Selecting Backup Albums

### ISSUE THREAD

**Issue by oscarale-camorlinga** [immich-app/immich#777]
### Feature detail

When I go to select albums to be backed up automatically, I get a lot of albums that appear to be system file folders labeled "textures", "schematics" etc., some even from immich. It would be great to exclude these folders from the available albums, or provide a way to place a .nomedia file within folders that shouldn't appear here. Seeing as the albums are not listed in any particular order, it's difficult to sift through all of the folders to find just the relevant ones that I would potentially include/exclude for backup, like "DCIM" or "Screenshots".

Otherwise love the server and app so far! I came from LibrePhotos and while Immich has a few less features, it is much faster, cleaner, and was very easy to set up. Thanks!

### Platform

Mobile App

**Comment by alextran1502** [comment]
Hello, the current library that we use doesn't support reading the system file. It returns libraries/folders with photos and videos. I added the feature to search for available albums in #1038
