### ISSUE TITLE
[BUG] Thumbnail file path is constructed incorrectly

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#778]
At https://github.com/immich-app/immich/blob/main/server/apps/microservices/src/processors/thumbnail.processor.ts#L65, the path for a thumbnail file is constructed as follows:
`const jpegThumbnailPath = resizePath + originalFilename + '.jpeg';`
This has two issues: there is no `/` between the folder path and the filename, and it is joining paths using string concatenation. Instead, this path should be constructed using the `join` function like is done a few lines above: https://github.com/immich-app/immich/blob/main/server/apps/microservices/src/processors/thumbnail.processor.ts#L57.

**Comment by deepesh16b** [comment]
Please assign this to me
@bo0tzz

**Comment by EdkoPitonak** [comment]
Hi i would love to work on this if it is possible

**Comment by zackpollard** [comment]
> Please assign this to me @bo0tzz

You have been assigned, thanks for the interest in working on this! 😄

**Comment by alextran1502** [comment]
Resolved in #780
