### ISSUE TITLE
Unable to download / share external librairies from app 1.98.1

### ISSUE THREAD

**Issue by jsapede** [immich-app/immich#7781]
### The bug

Very strange behavour on the app. When i try to download a picture form an external librairies i got errors
![Screenshot_20240309-153552](https://github.com/immich-app/immich/assets/66303110/f083413d-ccbf-467a-a5be-a49e391f69d5)

And when i try to share i got a picture labelled as BIN witch does not show in other apps such as WhatsApp or gmail 

![Screenshot_20240309-153608](https://github.com/immich-app/immich/assets/66303110/82ce08a7-2b69-41a0-af0e-ce4eee69b12f)

When i try from a web browser it works fine: 

![Screenshot_20240309-153642](https://github.com/immich-app/immich/assets/66303110/131cc09d-2b14-4930-9dff-0a2cf1b2bfa5)

It also works if i try to download in app a synced picture issues from thé phone

![Screenshot_20240309-154905](https://github.com/immich-app/immich/assets/66303110/0e7f2e7a-8276-465a-b22b-73849e15f3d5)

Yesterday i installed 1.98.0 and it Worked but sonce 1.98.1 upgrade this morning impossible to share or download assets from external librairies from thé app

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.98.1

### Version of Immich Mobile App

1.98.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```
version: '3.8'

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:

```

### Your .env content

```
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/opt/upload
EXTERNAL_PATH=/opt/photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

```

### Reproduction steps

```bash
1.open the app
2.try to download or share a picture from an external library
3.error
4. Try from a browser and it works 
...
```

### Additional information

External librairies are on a NFS share on a Synology nas with all acces read / write

same behaviour on 2 different phones

app has authorizations do read/write on the phone

got same error even if i use the LAN ip addresse of the immich server instead of domain name / proxy

downgraded to 1.98.0 and no changes

**Comment by mmomjian** [comment]
Please post the logs of immich and immich-microservices

**Comment by jsapede** [comment]
where to get them ? in the docker output ?

**Comment by mmomjian** [comment]
`docker logs immich` and `docker logs immich-microservices` on your host.

**Comment by jsapede** [comment]
Ok i reinstalled from zero, removing all libraries, assets, and thumbs, rebuilding immich from zero in 1.98.1, same behaviour

i added external library, scanned it and asked for two downloads from app at 5:17pm and 5:20 pm


docker logs immich_server : 
`[Nest] 6  - 03/09/2024, 5:11:42 PM     LOG [CommunicationRepository] Websocket Connect:    9XDZByneophJEZriAAAJ
[Nest] 6  - 03/09/2024, 5:12:18 PM     LOG [CommunicationRepository] Websocket Disconnect: 9XDZByneophJEZriAAAJ
[Nest] 6  - 03/09/2024, 5:12:35 PM     LOG [CommunicationRepository] Websocket Connect:    kgTYr0s9XzBaXXRkAAAL
[Nest] 6  - 03/09/2024, 5:13:20 PM     LOG [CommunicationRepository] Websocket Disconnect: kgTYr0s9XzBaXXRkAAAL
[Nest] 6  - 03/09/2024, 5:13:27 PM     LOG [CommunicationRepository] Websocket Connect:    LnNHxMry3C7yRf3yAAAN
[Nest] 6  - 03/09/2024, 5:13:55 PM     LOG [CommunicationRepository] Websocket Disconnect: LnNHxMry3C7yRf3yAAAN
[Nest] 6  - 03/09/2024, 5:17:32 PM     LOG [CommunicationRepository] Websocket Connect:    mqnlrrLQkinddnSfAAAP
[Nest] 6  - 03/09/2024, 5:18:09 PM     LOG [CommunicationRepository] Websocket Disconnect: mqnlrrLQkinddnSfAAAP
[Nest] 6  - 03/09/2024, 5:20:14 PM     LOG [CommunicationRepository] Websocket Connect:    QP2SNULbV2W_xzyYAAAR
[Nest] 6  - 03/09/2024, 5:20:33 PM     LOG [CommunicationRepository] Websocket Disconnect: QP2SNULbV2W_xzyYAAAR`


docker logs immich_microservices : 
`[Nest] 7  - 03/09/2024, 5:09:58 PM     LOG [PersonService] Creating new person for face 03f895d7-a9e8-454a-8ba8-d7f24a8eeaa7
[Nest] 7  - 03/09/2024, 5:10:00 PM     LOG [PersonService] Creating new person for face d07ac01b-68da-47dd-be40-c4cfc9303d2d
[Nest] 7  - 03/09/2024, 5:10:00 PM     LOG [PersonService] Creating new person for face c09aa4a1-e99e-4bc2-8073-a29c2575d66b
[Nest] 7  - 03/09/2024, 5:10:00 PM     LOG [PersonService] Creating new person for face 5375cac2-76b6-44f3-a010-50aa731e25bc
[Nest] 7  - 03/09/2024, 5:10:01 PM     LOG [PersonService] Creating new person for face 9f15fdc7-0c9e-4b01-9317-70537cb7eff5
[Nest] 7  - 03/09/2024, 5:10:01 PM     LOG [PersonService] Creating new person for face 3090e5f4-b047-4ab5-acf6-1244dd103e5a
[Nest] 7  - 03/09/2024, 5:10:01 PM     LOG [PersonService] Creating new person for face 49bcff51-d6e8-49fd-bc9e-f0a89b3f4a13
[Nest] 7  - 03/09/2024, 5:10:01 PM     LOG [PersonService] Creating new person for face d85b65f6-f96e-4099-ace0-5ddee0acab61
[Nest] 7  - 03/09/2024, 5:10:01 PM     LOG [PersonService] Creating new person for face 4dfe001e-cb90-4236-8d3e-74624b340441
[Nest] 7  - 03/09/2024, 5:10:01 PM     LOG [PersonService] Creating new person for face d9cdefa7-2dff-4f92-b114-dc80dddb2fda
[Nest] 7  - 03/09/2024, 5:10:01 PM     LOG [PersonService] Creating new person for face f004d106-7178-4e0c-848c-3fbb011fef39`

**Comment by mmomjian** [comment]
What happens on the web if you try to download the same image?

**Comment by jsapede** [comment]
works perfectly

**Comment by jsapede** [comment]
Recently uploaded photos from the phone correctly exhibit extension

![Screenshot_20240309-200416.png](https://github.com/immich-app/immich/assets/66303110/4156f666-63d3-4838-80b5-c4d4f92a53f3)

**Comment by mmomjian** [comment]
Could this be related to #7679?

**Comment by mmomjian** [comment]
Can you confirm your app version is 1.98.1 in the dropdown menu in-app?

**Comment by jsapede** [comment]
![Screenshot_20240309-203224.png](https://github.com/immich-app/immich/assets/66303110/decad817-909f-4e48-b09f-6d5927e1c710)

**Comment by mmomjian** [comment]
Thanks. We might have to wait for some others to weigh in to see if it's related to the recent changes in the way we store the extension.

**Comment by jsapede** [comment]
On some old files extension IS .JPG instead of .jpg , i tested if the problem was case sensitive and renamed the extension as lowcase on some files but changed nothing. 
Same problem with sime vidéos, impossible to download/share from the app

**Comment by jsapede** [comment]
tried this morning to import from CLI instead of external libraries but errors see https://github.com/immich-app/immich/issues/7779

manages to upload with immich-go, same collections, and this time download and share from app is possible. seems only related to external libraries

**Comment by santi8ago8** [comment]
I{m facing the same issue, I think the problem in the import stage because in the WebUI you can see like this: 
<img width="238" alt="image" src="https://github.com/immich-app/immich/assets/3782445/feb48e25-be20-4ac8-8efe-21e4586c7089">
(without the extension) but when I try to download from the web the extension is correct. So only the app is affected.

**Comment by tiltshiftfocus** [comment]
This issue have been fixed as per opened issue in #8052, however for those who have upgraded and still encountering issues even after refreshing the files/library, please look into my reply in the above mentioned issue to see the fix.

**Comment by tiltshiftfocus** [comment]
This issue have been fixed as per opened issue in #8052.

However for those who have upgraded and still encountering issues even after refreshing the files/library like I did, please look into my reply in the above mentioned issue to see the fix.

**Comment by santi8ago8** [comment]
Thanks @tiltshiftfocus! Fixed with the query in the comment: https://github.com/immich-app/immich/issues/8052#issuecomment-2011235454

**Comment by jrasm91** [comment]
I'm pretty sure this has been fixed. Let me know if that's not the case
