### ISSUE TITLE
Mobile archive displays oldest-newest on iOS

### ISSUE THREAD

**Issue by mmomjian** [immich-app/immich#7793]
### The bug

On mobile, the Archive displays images starting the oldest ones first. On web, it starts with the newest ones. I don't see a way to change this on either platform, which seems to make this a bug.

Expected behavior: Immich displays the archive newest -> oldest, like the timeline.

Favorites is not affected.

### The OS that Immich Server is running on

Debian 12, Docker

### Version of Immich Server

1.98.1

### Version of Immich Mobile App

1.98.1.build.143 and 1.98.0.build.142

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open the app on iOS
2. View the Archive
```

### Additional information

N/A

**Comment by mertalev** [comment]
Fixed via #7822
