### ISSUE TITLE
Discrepancy in Android Mobile Application backup items (total vs backup)

### ISSUE THREAD

**Issue by ashishjullia** [immich-app/immich#7811]
### The bug

I believe the following information is not right:

![Screenshot_20240309-230630](https://github.com/immich-app/immich/assets/11252951/1e4f94d0-80d6-481f-92e7-61967b47a016)

### The OS that Immich Server is running on

Raspbian (2023-12-05 - 6.1.69 - 12.2.4) - Docker 25.0.4

### Version of Immich Server

v1.98.1

### Version of Immich Mobile App

v1.98.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I've used the latest compose from here : https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml

(No changes at all)
```

### Your .env content

```Shell
Same, no changes at all.
```

### Reproduction steps

```bash
1. Set-up compose
2. Install mobile Android application 
3. Map a local library 


These are the only things I've used to setup my env, pretty much stock setup.
```

**Comment by alextran1502** [comment]
Hello, this means there are duplicated assets. You can check the number of duplicated assets in Settings > Local Storage. And yes, we need to consider that in this interface

**Comment by ashishjullia** [comment]
> Hello, this means there are duplicated assets. You can check the number of duplicated assets in Settings > Local Storage. And yes, we need to consider that in this interface

@alextran1502 so backed up are only unique assets but the mobile application shows them as backed up (counting duplicates as well but not uploading them, right?)

**Comment by alextran1502** [comment]
Yes sir

**Comment by ashishjullia** [comment]
> Yes sir

Oh great, thanks for the response and confirming.

I got a little confused.

Will close the issue now.
