### ISSUE TITLE
[Mobile app] Sign-in no longer works

### ISSUE THREAD

**Issue by ported-pw** [immich-app/immich#7816]
### The bug

I can no longer sign in on the mobile app. I'm not sure exactly what has caused the issue, but I assume it to have been the v1.98.0 update.

After entering the login credentials, nothing happens and the following error is logged:

**Message:**
```
PlatformDispatcher - Catch all
```

**Details:**
```
Null check operator used on a null value
``` 

**From:**
```
ImmichErrorLogger
```

**Stack trace:**
```
#0      UserResponseDto.fromJson (package:openapi/model/user_response_dto.dart:176)
#1      ApiClient.fromJson (package:openapi/api_client.dart:508)
#2      ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#3      UserApi.getMyUserInfo (package:openapi/api/user_api.dart:295)
<asynchronous suspension>
#4      AuthenticationNotifier.setSuccessLoginInfo (package:immich_mobile/modules/login/providers/authentication.provider.dart:185)
<asynchronous suspension>
#5      LoginForm.build.login (package:immich_mobile/modules/login/ui/login_form.dart:152)
<asynchronous suspension>
```

I can sign in fine on web on the same server. No additional authentication like client certs etc. are in place.

### The OS that Immich Server is running on

TrueNAS Scale

### Version of Immich Server

v1.98.0

### Version of Immich Mobile App

v1.98.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A, TrueNAS Scale community chart
```

### Your .env content

```Shell
N/A, TrueNAS Scale community chart
```

### Reproduction steps

```bash
1. Enter server URL
2. Enter login details
```

**Comment by ported-pw** [comment]
Apologies, I didn't see the duplicate to my issue. Was in the same boat as #7803 , checked release notes and didn't see anything that looked like it could cause the issue with the version desync between .0 and .1. Thanks!

**Comment by alextran1502** [comment]
Hello, there was a PR that merged right before I push out a hotfix release that cause the incompatibility between 1.98.0 and 1.98.1 on the mobile app. 

I overlooked it when trying to fix other issues. Sorry for the inconvenience 😥
