### ISSUE TITLE
Unable to perform searches and does not show face recognition

### ISSUE THREAD

**Issue by wangl1987** [immich-app/immich#7855]
### The bug

Search is not possible and face recognition is not displayed, but geographic image categorization is normal
![image](https://github.com/immich-app/immich/assets/150538734/c2fa6b89-a51e-4f6f-8997-361d9b15ee51)
![image](https://github.com/immich-app/immich/assets/150538734/2cb17173-9168-4ada-a54b-e1d0b7b2772e)
error log：
![image](https://github.com/immich-app/immich/assets/150538734/04bae38f-cb5d-4988-a870-9c98e301dbe4)

### The OS that Immich Server is running on

Installing through Docker Compose on Mac OS

### Version of Immich Server

1.98.1

### Version of Immich Mobile App

1.98.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
1.Using the search images page keeps loading
2.
3.
...
```

### Additional information

I am in China, there will be some limitations on the network, do I need to network to do some other operations after starting the container.
These functions worked fine before I upgraded to version 1.93.0, is it possible to bypass these functions in the new version there?

**Comment by alextran1502** [comment]
Yeah, searching needs to download the machine learning model and I believe it is blocked in China. There are some proxy server that help you download the model manually. I think you can get some more info by searching with Chinese search engine
