### ISSUE TITLE
service-worker.js not found

### ISSUE THREAD

**Issue by nebulade** [immich-app/immich#786]
I am trying to find out where and how `service-worker.js` is used and from which component or dependency it comes from. A repo search did not reveal any reference to it, however in the server logs I can see something requesting this, when using the the web UI, probably some 3rdparty framework used:
```
13:15:10 - Error: Not found: /service-worker.js
13:15:10 - at resolve (file:///app/code/web/build/server/index.js:2368:18)
13:15:10 - at Object.handle (file:///app/code/web/build/server/hooks.server-E3O5L5GT.js:5:16)
13:15:10 - at respond (file:///app/code/web/build/server/index.js:2389:42)
13:15:10 - 172.18.0.1 - - [05/Oct/2022:11:15:10 +0000] "GET /service-worker.js HTTP/1.1" 404 1060 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
```
Is this something which should be installed by some build step which we might be missing?
The context is the Cloudron app package, which is not using the default upstream docker images.
Any pointer in the direction to allow me to investigate further would be much appreciated. Feel free to close this issue if such a question is out of scope here.

**Comment by bo0tzz** [comment]
Are you using immich at an url that was previously used by another app, which did have a service worker setup? If so, your browser might have that cached and be trying to update it.

**Comment by nebulade** [comment]
Oh wow, now I feel very stupid. This is in fact the case. Thanks for the hint and sorry for the noise.
