### ISSUE TITLE
Mobile login stopped working with no hint for user about app and server version mismatch

### ISSUE THREAD

**Issue by simonsso** [immich-app/immich#7886]
### The bug

Mobile app stopped working, after working for a few days. Reinstalling app or chaining network did not change anything.

```
#0      UserResponseDto.fromJson (package:openapi/model/user_response_dto.dart:176)
#1      ApiClient.fromJson (package:openapi/api_client.dart:508)
#2      ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#3      UserApi.getMyUserInfo (package:openapi/api/user_api.dart:295)
<asynchronous suspension>
#4      AuthenticationNotifier.setSuccessLoginInfo (package:immich_mobile/modules/login/providers/authentication.provider.dart:185)
<asynchronous suspension>
#5      LoginForm.build.login (package:immich_mobile/modules/login/ui/login_form.dart:152)
<asynchronous suspension>
```

### The OS that Immich Server is running on

Android • MP18

### Version of Immich Server
Server Version: v1.97.0

### Version of Immich Mobile App
Mar 11, 2024

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Installed on Truenas with default distru
```

### Your .env content

```Shell
Nothing special
```

### Reproduction steps

```bash
1.open app
2.login with correct username and password
3.nothing happens on user screen.
```

### Additional information
After login the device is visible under `Authorized devices` in WebUI

**Comment by simonsso** [comment]
Root cause identified:
App auto updated from play store before server were upgraded. Upgraded the server image and app was able to login again.

@immich-app team: Could we get an indication from the app about the version mismatch?

**Comment by alextran1502** [comment]
This is my oversight for a patch release; there was a PR that caused incompatibility between the server and the mobile app that got into the update from `1.98.0` to `1.98.1`, which got merged right before the update, and I didn't catch it. My apologies

**Comment by cawis68** [comment]
What is the plan here? It is still not working with older versions.

**Comment by alextran1502** [comment]
@cawis68 The server will need to be updated. Since we are still in really active development, we cannot make guarantee for backward compatibility yet

**Comment by cawis68** [comment]
Alex, I'm a supporter of this project. Could you please at least help somehow deploying the latest server version for Umbrel? https://github.com/getumbrel/umbrel-apps/pull/993

**Comment by cawis68** [comment]
@alextran1502 any update on this?

**Comment by alextran1502** [comment]
@cawis68 we are not the maintainer of Umbrel so unfortunately we cannot do anything here
