### ISSUE TITLE
The experience is a bit bad when opening the shared link on the mobile phone

### ISSUE THREAD

**Issue by EastWoodYang** [immich-app/immich#7941]
### The bug

shared link: https://demo.immich.app/share/HifpECbEGVoRE6Rc8Js_sst15LG9dcwrbRswJuJ8mGufG1EQEST2ljE8FcHx6aFzfbY

on mobile phone web:
<img src="https://github.com/immich-app/immich/assets/9335046/645a6944-35ff-472a-95b4-f315968ede3f" width="200">

on pc web:
<img src="https://github.com/immich-app/immich/assets/9335046/7bb8d2fa-8e0f-4324-b136-d68e17b3408d" width="400">

### The OS that Immich Server is running on

.

### Version of Immich Server

.

### Version of Immich Mobile App

.

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
open it
```

**Comment by jrasm91** [comment]
This is a lot better now, but obviously there is still lots of room for improvement. IMO this isn't a bug, it's just not 100% mobile optimized yet. With time that will improve.
