### ISSUE TITLE
Wrong escaping backslach in directory name

### ISSUE THREAD

**Issue by marcin-github** [immich-app/immich#7945]
### The bug

I noticed that directory contained backslash in the name aren't correctly proccessed:

immich_microservices       | [Nest] 7  - 03/14/2024, 10:02:50 AM   ERROR [JobService] Unable to run job handler (library/library-refresh-asset): BadRequestException: Cannot acce
ss file
immich_microservices       | [Nest] 7  - 03/14/2024, 10:02:50 AM   ERROR [JobService] BadRequestException: Cannot access file
immich_microservices       |     at LibraryService.handleAssetRefresh (/usr/src/app/dist/domain/library/library.service.js:363:23)
immich_microservices       |     at async /usr/src/app/dist/domain/job/job.service.js:137:37
immich_microservices       |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_microservices       |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_microservices       | [Nest] 7  - 03/14/2024, 10:02:50 AM   ERROR [JobService] Object:
immich_microservices       | {
immich_microservices       |   "id": "1cc889e2-9374-4242-b698-cb57449a54de",
immich_microservices       |   "assetPath": "/mnt/media/yyy/Bozena/xxxxxx.jpg",
immich_microservices       |   "ownerId": "5a54fc18-4669-448c-a2d3-0604465d438c",
immich_microservices       |   "force": false
immich_microservices       | }
immich_microservices       |

Real path is 
```
/mnt/media/yyy/Bozena\/xxxxxx.jpg
```

### The OS that Immich Server is running on

docker container

### Version of Immich Server

1.98.2

### Version of Immich Mobile App

---

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
```

### Your .env content

```Shell
---
```

### Reproduction steps

```bash
---
```

**Comment by bo0tzz** [comment]
Do you mean that you have a filename with a backslash in it?

**Comment by marcin-github** [comment]
Directory contains backslash \  in the name

**Comment by mmomjian** [comment]
You post that the "Real path is"

`/mnt/media/yyy/Bozena\/xxxxxx.jpg`

This would be a forward slash (`/`) in the file name, escaped by a backslash (`\`). Forward slash (`/`) is an illegal character in a Linux filename. I recommend renaming the file.

**Comment by marcin-github** [comment]
One thing is if such chars are usefull ;) Second thing is how application deal with it (or maybe there are other chars that are problematic)? Also if app has problem with it could it become some kind of security issue?

**Comment by alextran1502** [comment]
We sanitize such character to avoid path traversing attack
