### ISSUE TITLE
People cannot be removed from a shared album through options

### ISSUE THREAD

**Issue by aviv926** [immich-app/immich#7954]
### The bug

Adding people can be done through the shared album options, but people cannot be removed through these options.

https://github.com/immich-app/immich/assets/51673860/4fc4c5a2-022f-4867-8ad6-c93bc4dc16db

### The OS that Immich Server is running on

Demo

### Version of Immich Server

Demo

### Version of Immich Mobile App

Demo

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Demo
```

### Your .env content

```Shell
Demo
```

### Reproduction steps

```bash
1. Create a shared album
2. Add a person through the album options
3. Try to remove it through album options
```

**Comment by AnimeshKotka** [comment]
Hi, Can I fix this? I am a new comer so it would be easier for me.
cc: @jrasm91

**Comment by aviv926** [comment]
> Hi, Can I fix this? I am a new comer so it would be grate experience for me. cc: @jrasm91

There seems to be a PR open for it
https://github.com/immich-app/immich/pull/12959

**Comment by aviv926** [comment]
The problem was solved with https://github.com/immich-app/immich/pull/12959 partially, because although it is possible to remove a user, it does not allow all the full options as suggested by the workaround:

https://github.com/user-attachments/assets/72332c03-a028-430f-a8c0-6c1c911b57df

cc:
@AnimeshKotka 
@Pranav-8bit

If you want to work on PR for this that would be great :)

**Comment by AnimeshKotka** [comment]
Thanks @aviv926 for the heads up. I am working on it.

**Comment by AnimeshKotka** [comment]
Hi @jrasm91 I have created the Pull request.
PR Link: https://github.com/immich-app/immich/pull/13654

**Comment by aviv926** [comment]
> Hi @jrasm91 I have created the Pull request.
> PR Link: https://github.com/immich-app/immich/pull/13654 

Thanks for fixing the problem, I closed here.
