### ISSUE TITLE
Shared album not saved

### ISSUE THREAD

**Issue by aviv926** [immich-app/immich#7959]
### The bug

If you create a shared album and do not share it, it is simply deleted by itself, no pop-up window appears that states that the album must be shared with someone in order for it to be saved. (This can be very frustrating when working hard on selecting specific images).

I know this is not a common scenario but it is still something to alert the user to.

https://github.com/immich-app/immich/assets/51673860/423114a5-14dd-4f48-8780-d40452a28b28

### The OS that Immich Server is running on

Main Demo (1.98.2)

### Version of Immich Server

Main Demo (1.98.2)

### Version of Immich Mobile App

Main Demo (1.98.2)

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Main Demo (1.98.2)
```

### Your .env content

```Shell
Main Demo (1.98.2)
```

### Reproduction steps

```bash
1. Select Assets
2. Add them to a shared album
3. Exit the album
```

**Comment by alextran1502** [comment]
Since it is not shared with anyone, it is on the Album page.
