### ISSUE TITLE
[Feature]: Add the possibility to add current photo to an album

### ISSUE THREAD

**Issue by hbooo** [immich-app/immich#796]
### Feature detail

As a user I would like to be able to add a photo I'm currently viewing in full page to an existing or a new album.

Current behavior on Google Photos that I'd like to see on Immich:
Navigate to a photo
Display photo details
Menu is available with two options:
Add to an album
Add to a shared album
Both leads to the possibility to select an existing album or create a new one.

### Platform

Mobile App

**Comment by martyfuhry** [comment]
I believe this is complete with #708, right?

**Comment by hbooo** [comment]
Yes it's ok now, thanks !
