### ISSUE TITLE
Menu "Repair" doesn't play well with big libraries

### ISSUE THREAD

**Issue by marcin-github** [immich-app/immich#7965]
### The bug

I've got library with ~500k of images.  I manually removed thumbnails, I run force rescan of all files. Now when I try to get into menu "Repair" I can see Postgresql is burning cpu after some time web browser eats a lots of memory on RES and crahses.
Probably immich sends to browser information about many thousands of missing files.
I think number of displayed broken files should be limited.

### The OS that Immich Server is running on

docker container

### Version of Immich Server

1.98.2

### Version of Immich Mobile App

---

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
```

### Your .env content

```Shell
---
```

### Reproduction steps

```bash
---
```

**Comment by alextran1502** [comment]
Duplicated #4510
