### ISSUE TITLE
[FEATURE] Add indicator for actions that is in progress

### ISSUE THREAD

**Issue by dorianim** [immich-app/immich#797]
### Feature detail

The performance when opening the app is currently less than optimal. I have about 7000 assets on my phone, and it takes very long (>30 seconds) for the app to be fully usable after restarted. Especially the backup settings (e.g. count of "total", "backup", "remainder") stays at zero for a long time without any indication that something happens in the background (a spinner or something similar would be nice :)

It also takes very long to initially load the photo library. When I open the app, the view is empty for several seconds (here, some busy indicator, e.g. a [skeleton](https://mui.com/material-ui/react-skeleton/#variants) would make the UX a lot better:)
![image](https://user-images.githubusercontent.com/30153207/194726593-ea37c99c-d589-4624-a6c7-b9037c234c76.png)

To me, it looks like everything is loaded from zero at every restart of the app, as the performance got worse, the more pictures I uploaded. I think, it would make sense to cache very aggressively here and only download deltas every time.

I'm currently trying immich for me, my dad and my girlfriend and details like this (long waiting times, no indication that something is happening in the background) are things that confuse them and make them dislike the app, which is a shame, as I'd really like to use it :)

### Platform

Mobile App

**Comment by alextran1502** [comment]
Have you try the experimental feature for the new asset grid? it is meant to solve this issue.

**Comment by alextran1502** [comment]
This is also a known issue of slow loading time at the start. The improvement work is in progress.

**Comment by dorianim** [comment]
The experimental photo grid makes it a bit better, but still there are a few seconds with a blank screen. Also, the backup page shows 0 for everything and no selected albums for a long time. This is the bigger problem in my opinion, as it always looks like it "forgot" all the selected albums. My dad has ~60 albums selected for backup, and it looks like this for about 30 seconds:
![image](https://user-images.githubusercontent.com/30153207/194727309-bd1de385-851c-4c11-acec-df4e973cc2c5.png)

It would be nice to at least have some form of busy indicator here, as it is really confusing :)

**Comment by alextran1502** [comment]
> The experimental photo grid makes it a bit better, but still there are a few seconds with a blank screen. Also, the backup page shows 0 for everything and no selected albums for a long time. This is the bigger problem in my opinion, as it always looks like it "forgot" all the selected albums. My dad has ~60 albums selected for backup, and it looks like this for about 30 seconds: ![image](https://user-images.githubusercontent.com/30153207/194727309-bd1de385-851c-4c11-acec-df4e973cc2c5.png)
> 
> It would be nice to at least have some form of busy indicator here, as it is really confusing :)

Got it, thank you for the info. Will put in those indicator.

**Comment by dorianim** [comment]
Do you recheck all the files on every start of the app? Maybe it would make sense to chache the scanning results to avoid the long loading times.

**Comment by alextran1502** [comment]
> Do you recheck all the files on every start of the app? Maybe it would make sense to cache the scanning results to avoid the long loading times.
> 
> But a busy indicator will definetly be a huge improovement already!

You can turn off the auto backup (not background backup), it would prevent the app start to scan for all asset when launched, resumed

**Comment by bo0tzz** [comment]
The long loading time on start should be resolved by #826 (cc: @matthinc?). I've specified the backup screen issue in more detail in #834. That would just leave the loading indicator for this issue.
