### ISSUE TITLE
[BUG] Unable to Backup from iOS if using specific selection photos

### ISSUE THREAD

**Issue by Hukuma1** [immich-app/immich#800]
**Describe the bug**
Files are not backed up if using privacy setting of allowing only certain photos to be accessed by Immich.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [X] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [X] I have included information on my machine, and environment.

**To Reproduce**
1. Open Immich on iOS for the first time.
2. Select which photos you want Immich to have access to at the prompt (if not all)
3. Go to cloud backup icon at the top right in Immich
4. Click `Start Backup`
5. Immich will kick you out to iOS permissions settings and not backup anything.

**Expected behavior**
To be able to backup whatever selected photos/album.

**Screenshots**

https://user-images.githubusercontent.com/54511555/194774491-f20f549c-cdc8-45a1-9840-57a8eb2eb57e.MP4

**System**
- Phone OS [iOS, Android]: iOS `14.8`
- Server Version: `1.31.0`
- Mobile App Version: `1.31.0 build 64`

**Additional context**
Selecting `Turn on Backup` will cause you to bootloop more or less as it continuously tries to get permission and kicks you to settings. Don't enable it unless you hate yourself. :P

**Comment by alextran1502** [comment]
I don't think this is the expected use case as well as the intent use case 😅

**Comment by Hukuma1** [comment]
Tries to exclude certain photos from being backed up, gets told he's using it wrong? 😅

**Comment by alextran1502** [comment]
@Hukuma1 I think the easier way is to create an album on your phone in the Photos app that you want to store all the pictures to be backup. Then, from the Photos app, you can choose which one you would like to be uploaded to put in that album.

The reason is because we don't have the mechanism to select individual photo or video when you want to backup from the app. And since we can select the album to back up, there is no need to implement such mechanism. Sorry for brief respond earlier. I hope this would cover your use case 😄

**Comment by Hukuma1** [comment]
Maybe I'm not understanding it correctly, but let's say for humor's sake I got 10 photos that are private. And the other 3000 are everyday snapshots. 

Ideally I would want to backup my whole photos library, minus the 10 private photos. Unless you want The Selfhosted Fappening of 2022 happening, this is a good security measure I think.

Having said that I just tried to whitelist my entire Selfies folder as allowed in iOS (aka exposed to Immich), set it to be the only Backed up folder in Immich and it still kicked me to settings...

I think the issue is Immich wants full access to everything, no privacy setting/selective image/folder options that iOS provides?

**Comment by alextran1502** [comment]
@Hukuma1 From your example scenario, you can create an album as "No Backup" and put the 10 photos you don't one to backup in it. Then in the album selection page, you can chose to exclude that page by double tapping on the album. Does it solve the scenario you describe?

**Comment by Hukuma1** [comment]
Does the inverse of your example not work? I select a specific folder to backup instead of excluding it? (e.g. Selfies folder)

It does not seem to be doing it. If I only want one folder backed up, it is not working.

**Comment by alextran1502** [comment]
Yep it works as well, you can excluded the rest of the image and only include the selfie album, or just select the selfie album.

Did you allow the "Allow all" permission for the app or still keeping the permission as you stated in the original question?

**Comment by Hukuma1** [comment]
I'm not allowing all for privacy reasons, correct...

**Comment by alextran1502** [comment]
The app will need that to be able to function properly . We don't collect any data from your device and your image will only be backup to your own server. That is the guarantee you get when using the solution.

**Comment by Hukuma1** [comment]
I see. Thank you for clarifying. Any particular reason for this? It's like asking for root and then saying don't worry, it's safe. I mean, maybe. And not saying it's not, just pointing out that not everyone will think that... why take the chance? The app certainly doesn't need 'root' if it only needs to backup 1 folder for example, right?

Isn't there a way to list all the files/folders that get exposed without asking for all permissions? Or is this some iOS limitation?

**Comment by alextran1502** [comment]
It is just the general use cases that would backup most of the photos/videos from your phone, otherwise you will not need a fully backup solution like this, but some type of other usage would work. 

So it helps cut down the work for us and less edge cases to handle with. But most important things, it helps to keep things simple.

**Comment by Hukuma1** [comment]
Alright. Thanks for the time and continued effort! Perhaps it'll be revisited later down the road. Privacy is important now more than ever and will be less of an edge case in the future I think.
