### ISSUE TITLE
The image viewing setting is 4K, jpg is normal, HEIC is blurry, and the original image cannot be displayed.

### ISSUE THREAD

**Issue by paynewangw** [immich-app/immich#8016]
### The bug

On the laptop, the immich image viewing setting is 4K, jpg is normal, HEIC is blurry, and the original image cannot be displayed.

But everything works fine on mobile, our family likes to see photos on the big screen

### The OS that Immich Server is running on

CentOS

### Version of Immich Server

v1.98.2

### Version of Immich Mobile App

v1.98.2 build 144

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
normal
```

### Your .env content

```Shell
normal
```

### Reproduction steps

```bash
1.I use Apple 13promax to upload pictures from my phone
2.Browse photos using a computer browser
3.The jpg is very clear and is the original image.
4.HEIC also has 4K resolution, but it looks blurry
...
```

**Comment by alextran1502** [comment]
Can you elaborate on where do you set this? 

```
The immich image viewing setting is 4K
```

**Comment by paynewangw** [comment]
> 您能详细说明一下您在哪里设置吗？
> 
> ```
> The immich image viewing setting is 4K
> ```

![image](https://github.com/immich-app/immich/assets/88674185/27694112-187b-4f73-afde-976fa5d97aea)

**Comment by mertalev** [comment]
We don't display HEIC images on web due to low compatibility, so this isn't a bug.

**Comment by mertalev** [comment]
If you use macOS, the next Immich release will support displaying HEIF images on Safari.
