### ISSUE TITLE
[BUG] immich-microservices Skipped - Image is already being pulled by immich-server

### ISSUE THREAD

**Issue by stepanov1975** [immich-app/immich#802]
When doing ```docker compose pull``` I am getting:
```immich-microservices Skipped - Image is already being pulled by immich-server```
Is it expected?

**Comment by bo0tzz** [comment]
They currently use the same image, so yes.

**Comment by stepanov1975** [comment]
Thanks! Probably need to be mentioned somewhere because very confusing :)
