### ISSUE TITLE
Problems with navigation when deleting images

### ISSUE THREAD

**Issue by drucki** [immich-app/immich#8025]
### The bug

Hello!

So when I am deleting images from an album or in the main photo libary, there is a bug.
First of all it is somtimes not possible to navigate to the left site after deleting pictures. (when pressing left, it goes right)
Secondly if I am deleting images and navigating to the right site, pictures will be skipped while navigating.

I tested on Android IOS and Windows (web). Bug existing everywhere.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.98.2

### Version of Immich Mobile App

v1.98.2

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
1. go to an album
2. take a picture in the middle
3. delete this picture
4. navigate left (arrow left on the keyboard)
5. see that the navigation isnt working, or it goes right
6. delete some more pictues
7. by going right pictures will be skipped
```

**Comment by aviv926** [comment]
I was unable to reproduce this behavior.

**Comment by drucki** [comment]
Problem solved with v.1.99.
