### ISSUE TITLE
[Feature]: Compiled Docker Image

### ISSUE THREAD

**Issue by micogg** [immich-app/immich#803]
### Feature detail

Thanks in advance for this project! It's exactly what I was looking for.

I'm running TrueNAS Scale for all my storage and docker images.
Scale does not natively support docker-compose, which is the install method I found.
There is a TrueChart app which allows for the  install of a docker image based on a docker-compose.yml file.
I attempted this TrueChart docker-compose install method and copied the ENV variables into the app variables, but I'm thinking this is what caused the issue if Immich is looking for a specific ENV file and I added the variables directly to the TrueChart app.

The issue I'm running into is that the app gets stuck on deploying.  It's not producing any logs so I cannot locate where it is stalling.  I'm hoping someone has had luck installing on Scale.

I did find in dockerhub that there are 4 docker images.  I tried just the server image, but I'm noticing that if I went that route, it looks like the other 3 are dependencies so I would need them running as well.

Any advice or direction on how to achieve Immich on Scale would be greatly appreciated!

### Platform

Server

**Comment by micogg** [comment]
I checked TrueCharts within my install but I didn't even think to check for updated images...  Thanks so much, I'll give this a try!

**Comment by bo0tzz** [comment]
Did this work for you @micogg?

**Comment by bo0tzz** [comment]
Truecharts set the image version in their [values.yaml](https://github.com/truecharts/charts/blob/master/charts/incubator/immich/values.yaml#L3), so you'd need to edit that. (But I have no idea if there is a way to do that, or if it will break anything on truecharts' setup, you'd need to ask them)

**Comment by missuo** [comment]
I am having the same problem. the version of TrueCharts is 1.29.5, which seems to have not been updated for more than two months, and this old version of the mobile app cannot be connected. I tried using TrueCharts `docker-compose`, but he doesn't seem to recognize the `.env` file correctly.
