### ISSUE TITLE
[Feature]: Low Resource App

### ISSUE THREAD

**Issue by athornfam2** [immich-app/immich#804]
### Feature detail

Any time soon when the code will be revamped to require less resources or can we get a "low resource mode"? I ask this because I'm looking for a low cost alternative to iCloud storage with self hosting. Vultr I believe is amongst the cheapest and even that fitting the min CPU requirements is $20. Is it possible to get this software to run on 1c/1gb or 1c/2gb at some point? Maybe have a little compromise of setting up ingestion times to keep the experience smooth... by uploading and storing in cache and then processing that data at a certain time like lets say 8PM to 8AM.

### Platform

Server

**Comment by alextran1502** [comment]
I've heard good things about Oracle cloud with their free tier, it has 24GB of RAM and 4 Arm core CPU. The current demo instance is running on it.

Back to the your question, most of the resource intensive operation is during the upload process. So as long as you recognize that and just let it does its things after a large amount of assets get uploaded, you should not be constraint on any machine. The only constraint here is the time you have to wait until all the assets are processed. 

We will probably not steering the code/operations toward the suggested idea.

**Comment by athornfam2** [comment]
That's a good solution for some maybe. I'm really trying to stick within my parameters of Vultr and a colo. I would self-host at home since I have plenty of the compute and storage to do so. Its more of the upload speed for me. I can't offer that on my current internet circuit. Unless Immich has a low-bandwidth profile in the works?

**Comment by bo0tzz** [comment]
A few things you can do to decrease cpu usage is to turn off the geocoding and the machine learning container. In the future we'll probably also have settings for video encoding etc. that you could tweak.

**Comment by athornfam2** [comment]
Will close the issue. Hope this will help others that may have the same type of idea/request.
