### ISSUE TITLE
bug(mobile): asset description is not shown

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#8042]
### The bug

Asset description is not shown when (i) button is clicked. Info panel has to be closed and opened again to show description.

https://github.com/immich-app/immich/assets/15554561/81dc7fab-a725-4376-ae0a-1e1fcc0673c3

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

v1.98.2

### Version of Immich Mobile App

v1.98.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. add description to an asset on web or mobile and kill the app then
2. view asset on mobile
3. click (i) button
4. no description is shown
5. close info panel
6. open it again and see description
```

**Comment by aviv926** [comment]
Although I was able to reproduce the problem, it seems that after 5 seconds of waiting, the description of the image is updated.

**Comment by waclaw66** [comment]
The problem is that the description is always shown after the second opening of info panel, no matter how long you wait.

**Comment by aviv926** [comment]
> The problem is that the description is always shown after the second opening of info panel, no matter how long you wait.

Oh yes I see what you mean.

**Comment by alessiozanutta** [comment]
also here, in immich web i can see my comments
in the app for ios no
true that you have to tap twice in the (i)
the first tap shows VOID field, the second the inserted comment

**Comment by RanKKI** [comment]
I'm happy to fix it.

https://github.com/immich-app/immich/blob/aea1c46bea9e7ae52ac22c66e54683cff8fe376c/mobile/lib/providers/asset_viewer/asset_description.provider.dart#L48-L61

It appeared that `_asset.exifInfo` is null when you open the sheet for the first time. When you close it and open it again, we get some value in `_asset.exifInfo`.

I'm still investigating where `exifInfo` changed.
