### ISSUE TITLE
Android Monochrome Icon Broken

### ISSUE THREAD

**Issue by CadeusTheGreat** [immich-app/immich#8103]
### The bug

Not sure if I'm remembering this incorrectly but the monochrome icon is no longer working and instead displays full colour icon.

### The OS that Immich Server is running on

Android 14 (OneUI 6.0)

### Version of Immich Server

v.1.98.2

### Version of Immich Mobile App

v1.99.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Install mobile app.
2. Set app icons to adaptive/monochrome.
3. Icon for the app won't switch to monochrome as it previously did.
```

**Comment by Wolfhound905** [comment]
https://github.com/immich-app/immich/pull/1457

This feature

**Comment by alextran1502** [comment]
@spiralham can you help point me to the generator you use for monochrome icon?

**Comment by eygraber** [comment]
It looks like the adaptive icons are still using the old logo:

https://github.com/immich-app/immich/blob/main/mobile/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
https://github.com/immich-app/immich/blob/main/mobile/android/app/src/main/res/drawable/ic_launcher_foreground.xml
https://github.com/immich-app/immich/blob/main/mobile/android/app/src/main/res/drawable/ic_launcher_monochrome.xml

**Comment by Edzioindra** [comment]
Same here in pixel device. Icon turned into full color. No more adaptive icon.

**Comment by alextran1502** [comment]
Fixed
