### ISSUE TITLE
Slideshow does not pause when video is played

### ISSUE THREAD

**Issue by JW-CH** [immich-app/immich#8132]
### The bug

The slideshow does not pause when a video is played. Also, it resumes to playing state when the video is over.

### The OS that Immich Server is running on

UnRaid

### Version of Immich Server

v1.99.0

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not required
```

### Your .env content

```Shell
Not required
```

### Reproduction steps

```bash
1. Open Album with videos in it
2. Start slideshow
3. Wait until video is playing
4. Press the pause button
...
```

**Comment by martabal** [comment]
#8032 should solve it
