### ISSUE TITLE
Tiny Logo with Shared Albums on mobile web

### ISSUE THREAD

**Issue by jna-358** [immich-app/immich#8144]
### The bug

When opening a shared album link on an iPhone, the logo seems tiny.
![IMG_2066](https://github.com/immich-app/immich/assets/99719897/5c4f44e7-53df-4554-84a5-80f5c5ac7f9f)

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.99.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Create a shared album
2. Visit the link on a the smartphone
```

**Comment by aviv926** [comment]
@alextran1502

**Comment by klaus1k** [comment]
Can confirm the same tiny logo on Android, when clicking on a shared link.

**Comment by Bhanubediya** [comment]
is this issue active?

**Comment by jna-358** [comment]
I just tested with v1.103.1 and the bug is still present.

**Comment by johnvanham** [comment]
I know this has been closed but @Snowknight26 it looks like it's still tiny on the shared album password page even though it's now fixed once you have put in the password. Tested on 1.105.1

**Comment by Snowknight26** [comment]
Good catch, didn't realize that one was a separate code path. I'll see if I can fix this one too.

**Comment by Snowknight26** [comment]
> I know this has been closed but @Snowknight26 it looks like it's still tiny on the shared album password page even though it's now fixed once you have put in the password. Tested on 1.105.1

https://github.com/immich-app/immich/pull/9567
