### ISSUE TITLE
Can view other users' photos

### ISSUE THREAD

**Issue by Pelukosa** [immich-app/immich#8176]
### The bug

From the android application, if you go to the search tab, and go to recently added, you can see the photos of other users.

### The OS that Immich Server is running on

Ubuntu 22

### Version of Immich Server

V1.99.0

### Version of Immich Mobile App

V1.99.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Don't important
```

### Your .env content

```Shell
Don't important
```

### Reproduction steps

```bash
Recently added on search tab
```

**Comment by alextran1502** [comment]
Hmm, this is by design, not a bug. Unless I am mistaken your intention

**Comment by Pelukosa** [comment]
> ~Hmm, this is by design, not a bug. Unless I am mistaken your intention~
> 
> Ah you said "can". Do you have partner sharing with show on timeline on?

Sorry Alex, I didn't understand that. In my case, I have two users, I am the admin user, and I have only shared some photos through an album with the other user, but in "Recently added" I can see all his photos, even if he hasn't shared them with me

In the picture, the photos mark with a red circle are from the other user

![IMG_20240322_002346.jpg](https://github.com/immich-app/immich/assets/20848123/d25f78e6-6331-45a4-a8a9-0bae027db90c)
