### ISSUE TITLE
Failed to get assets by city (500) when partner sharing is enabled

### ISSUE THREAD

**Issue by honulii** [immich-app/immich#8241]
### The bug

I encountered an error when I clicked "Explore" and selected "View All" next to "Places". Accessed via web, not mobile app.

The error says "Failed to get assets by city (500)" and has two lines:
ue@obscuringmyurlhere/_app/immutable/chunks/fetch-client.L65p5BQF.js:1:port
ie@obscuringmyurlhere/_app/immutable/chunks/fetch-client.L65p5BQF.js:1:port

I checked the logs for immich-server and found: QueryFailedError: invalid input syntax for type uuid (it lists 3 uuids)

The map view was working well.

### The OS that Immich Server is running on

Synology NAS with DSM. Immich installed with Portainer

### Version of Immich Server

v1.99.0

### Version of Immich Mobile App

v1.99.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I'm not sure where to find this when using Portainer. As far as I can tell, my docker compose matches the latest version provided with release 1.99 (I compared the one I downloaded at installation and didn't see any differences).
```

### Your .env content

```Shell
I'm not sure where to find this when using Portainer
```

### Reproduction steps

```bash
1. On web, go to Explore
2. In places section, click View All
3. Error appears if you have partner sharing on, but not if partner sharing is off. It happened even when I had partner sharing on but didn't have the "include in timeline" checked for myself. 
...
```

**Comment by danieldietzler** [comment]
Hey, I'm not able to reproduce this on the demo instance (https://demo.immich.app). Could you try it there as well?
