### ISSUE TITLE
Date is not in order

### ISSUE THREAD

**Issue by mio-19** [immich-app/immich#8243]
### The bug

See the screenshot. Sunday is first, then today.
![image](https://github.com/immich-app/immich/assets/57285379/9f024236-a6df-4fed-b304-8ef03c74c1eb)

### The OS that Immich Server is running on

Arch

### Version of Immich Server

1.99.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
https://github.com/immich-app/immich/releases/download/v1.99.0/docker-compose.yml
```

### Your .env content

```Shell
https://github.com/immich-app/immich/releases/download/v1.99.0/example.env
```

### Reproduction steps

```bash
1. Upload some videos
2. Where are my videos? 
3. Found videos after scrolling down
```

**Comment by alextran1502** [comment]
Have the job finished processing? Where are those videos uploaded from?

**Comment by mio-19** [comment]
> Have the job finished processing? Where are those videos uploaded from?

Yes, all jobs finished. I uploaded them using the `@immich/cli` cli tool

**Comment by mio-19** [comment]
Today is Tuesday. The "Today" yesterday is now Monday. 
![image](https://github.com/immich-app/immich/assets/57285379/8a2f9ccd-48ea-47dd-917d-003665c9f878)
