### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Thewinnawin** [immich-app/immich#827]
**Describe the bug**

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
- Phone OS [iOS, Android]: `<version>`
- Server Version: `<version>`
- Mobile App Version: `<version>`

**Additional context**

**Comment by alextran1502** [comment]
Hello, did you mistakenly open this?
