### ISSUE TITLE
[BUG] iOS - Delete confirmation popup in dark mode

### ISSUE THREAD

**Issue by ExcelsiorEyer** [immich-app/immich#828]
iOS16 - Delete confirmation popup in dark mode is displayed with white font on white background 

**Task List**
- [ x] I have read thoroughly the README setup and installation instructions.
- [NA ] I have included my `docker-compose` file.
- [NA ] I have included my redacted `.env` file.
- [x ] I have included information on my machine, and environment.

**To Reproduce**
1. Ensure dark mode is enabled
2. Select images
3. Press delete
4. Popup for confirmation shows up with low contrast - white font text with white background 

**Expected behavior**
The popup should be high contrast with dark background

**Screenshots**
![Screenshot 2022-10-15 at 6 48 57 AM](https://user-images.githubusercontent.com/75917861/195985233-6e2a7e3c-7faa-488a-92a1-8fd368d156ed.png)

**System**
- Phone OS [iOS]: `16.0.3`
- Server Version: `1.32.0`
- Mobile App Version: `1.31.0 build 64`

**Comment by alextran1502** [comment]
This issue is fixed in 1.32 which is currently in the review progress on the app store.

Thank you for reporting
