### ISSUE TITLE
[BUG] Archived photos shared with partners appears in their timeline

### ISSUE THREAD

**Issue by asoulier** [immich-app/immich#8295]
### The bug

Partner sharing enabled. Archived photos are removed form the user timeline, but appear in the partner timeline (also in "Search" > "Recently added").

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.99.0

### Version of Immich Mobile App

v1.99.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
1. User A enables partner sharing with user B
2. User A archives some photos
3. Archived photos are removed from the user's A timeline
4. On the partner timeline (user's B timeline), the photos are present
5. User's A archived photos are also present in "Search" > "Recently added" of user's B.
```

**Comment by Jaytie2k7** [comment]
I came across this behavior, too. Is this by design or a bug? 
Would be great, if archived photos don't show up in the shared library.

**Comment by w4usbanders** [comment]
Same issue in the Android Mobile-App (v1.102.0).

**Comment by mertalev** [comment]
> I came across this behavior, too. Is this by design or a bug? 
> 
> Would be great, if archived photos don't show up in the shared library. 

No, I don't think this is intentional.

**Comment by jrasm91** [comment]
Closing in favor of #12614
