### ISSUE TITLE
[BUG] Android app states that client and server are up-to-date, but they both aren't.

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#832]
**Describe the bug**
So when I open the Immich android app, it says in the side-menu that the client and server are up-to-date.
But that's not true.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Go to the Android app
2. Click on the top-left to open the side menu
3. See the message "client and server are up-to-date" while they are not.

**Expected behavior**
I expected the message to say something like "Client is outdated" and "Server is outdated" 

**System**
- Phone OS [iOS, Android]: `11`
- Server Version: `1.31.1_49-dev`
- Mobile App Version: `1.31.0 build 49`

**Comment by alextran1502** [comment]
You have both the server and client are on 1.31 so they are up-to-date, isn't that should be expected?

**Comment by JVT038** [comment]
Oh, I thought that considering the latest version is v1.32.0, the client and server would both be outdated.
This is not the case?

**Comment by alextran1502** [comment]
It reports the current version your system is running on. The message your saw compare the current version of the app vs the one that got released, it is built as a reminder to up date :)
