### ISSUE TITLE
Slideshow in backward order loops on video

### ISSUE THREAD

**Issue by ReDew96** [immich-app/immich#8344]
### The bug

When running the slideshow feature in backward order, the slideshow will loop on a video and the previous photo when the slideshow encounters a video.

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Play Slideshow in backward order.
2. Encounter video in the slideshow.
3. Observe the slideshow looping video and previous photo.
```

**Comment by mmomjian** [comment]
I am able to replicate this - in reverse order, the slideshow does not move on to the "next" image after a video.
