### ISSUE TITLE
Inconsistant number of items in album

### ISSUE THREAD

**Issue by chengguangnan** [immich-app/immich#8348]
### The bug

I have a album which immich reported has 6478 items, but when I click the Select All button, after a processing delay, the web UI shows about 33k items selected. 

By browser the timeline, it seems that all items are selected. So maybe there is is a counting error in considering how many items in an album?

I suspect that this is related to counting stacked Live Photo but I'm not sure. Moreover, by adding all the 33k selected items to a new albumn, immich will correctly report the new albumn has 33k items. 

Screenshot:

<img width="405" alt="Screenshot 2024-03-29 at 11 16 49 AM" src="https://github.com/immich-app/immich/assets/861069/5eccfd85-776a-4165-930c-9ee8eb58c165">

### The OS that Immich Server is running on

MacOS

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by danieldietzler** [comment]
Hey, could you check if that's still an issue? :)

**Comment by chengguangnan** [comment]
I upgraded to v1.102.3. Still see this in some albums. 

<img width="522" alt="Screenshot 2024-04-28 at 12 54 05 PM" src="https://github.com/immich-app/immich/assets/861069/1e2306c1-93b3-4d60-bacd-26ca3b6504a1">

**Comment by danieldietzler** [comment]
Ok @chengguangnan it would be awesome if you could test something for us:
Following the [guide in the docs](https://immich.app/docs/guides/database-queries), connect to the database.
Then, run the following query:
```sql
SELECT COUNT(*) FROM albums_assets_assets AS a, assets AS b WHERE "a"."assetsId" = "b"."id" AND NOT "b"."isVisible"
```
and share the result with us, please.
Thanks! :)

**Comment by chengguangnan** [comment]
@danieldietzler 

```
immich=# SELECT COUNT(*) FROM albums_assets_assets AS a, assets AS b WHERE "a"."assetsId" = "b"."id" AND NOT "b"."isVisible"
immich-# ;
 count
-------
 28644
(1 row)
```

**Comment by danieldietzler** [comment]
Oh sorry I missed something. Can you try
```sql
SELECT COUNT(*) FROM albums_assets_assets AS a, assets AS b WHERE "a"."assetsId" = "b"."id" AND "a"."albumsId" = '<album id>' AND NOT "b"."isVisible"
```
by replacing `<album id>` with the album id of the album that issue occurs in? (the album id should be part of the URL and look something like `0b0d5697-3347-4900-9d41-6679079fc218`)

**Comment by chengguangnan** [comment]
Hey @danieldietzler , yes,  those invisible assets adds up!

3215 selected + 198 invisible = 3413 items. 

<img width="517" alt="Screenshot 2024-05-05 at 11 00 45 AM" src="https://github.com/immich-app/immich/assets/861069/44d4583e-e5ba-4c5a-b472-0d1d377deb01">

**Comment by danieldietzler** [comment]
Thanks! Can you remove the `COUNT`? My guess is that those are all the motion (video) part of motion assets, so I'd like to verify/disprove that.
```sql
SELECT * FROM albums_assets_assets AS a, assets AS b WHERE "a"."assetsId" = "b"."id" AND "a"."albumsId" = '<album id>' AND NOT "b"."isVisible"
```

**Comment by danieldietzler** [comment]
And they are not visible, ok. Thanks for input! I think we should be able to work with that now :)

**Comment by jrasm91** [comment]
Maybe we should run a migration to remove these. What do you think @danieldietzler ?

**Comment by danieldietzler** [comment]
I am always a bit scared to run migrations that delete stuff. But I think this should be fine, yea
