### ISSUE TITLE
Slideshow option missing from Shared Album from link

### ISSUE THREAD

**Issue by mnjm97** [immich-app/immich#8383]
### The bug

When accessing a shared album from a shared link the option for slideshow is missing.
this is for a public link as well as shared folders with other users.

not sure if this is bug or just a feature request.

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

not using mobile app

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default settings
```

### Your .env content

```Shell
default settings
```

### Reproduction steps

```bash
1.setup default
2.add photos to shared album
3.share the album with users (or public link)
4.user access to shared album
5.missing slideshow
...
```

**Comment by mnjm97** [comment]
is there any other info that I need to provide?

**Comment by mgabor3141** [comment]
I noticed this issue as well, I'll have a PR open shortly

**Comment by mgabor3141** [comment]
#8757 Will add the slideshow button to albums shared to another user. Share links don't have this functionality at all currently, that will remain a feature request.

**Comment by zgr0629** [comment]
Hello everyone, has this bug been confirmed to be fixed? Now the slideshow button is still not visible in the shared album.

**Comment by zgr0629** [comment]
> Hello everyone, has this bug been confirmed to be fixed? Now the slideshow button is still not visible in the shared album.

demo site is v1.115.0
https://demo.immich.app/share/U3uebjyEDcsrlIXqiyKhMg_fKFmj1a7DgSuisO6-dufeOyx3TOkBFCjTxej8FVwaB28

**Comment by hofq** [comment]
Have the same behavior in my home instance too. Is there something i have to enable?

**Comment by bwolleb** [comment]
I'd be very interested to have this as well.
