### ISSUE TITLE
video/mpeg - supported extensions

### ISSUE THREAD

**Issue by mmomjian** [immich-app/immich#8393]
### The bug

According to the [source](https://github.com/immich-app/immich/blob/main/server/src/utils/mime-types.ts), Immich only allows the `.MPG` extension for the `video/mpeg` MIME type. According to [Wikipedia](https://en.wikipedia.org/wiki/MPEG-1), there a number of other extensions that are often used for MPEG, but `.MPEG` is a very commonly used one that Immich doesn't seem to support. If the fix is as simple as adding `'.mpeg': ['video/mpeg'],` to `mime-types.ts`, I'm happy to open a PR, but I am not sure where else this is referenced / used. We could also add `.MPE`, to mimic the support for `JPEG` (.jpg, .jpeg, .jpe).

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by mmomjian** [comment]
Similar question, but `.3gpp` is a [supported extension](https://en.wikipedia.org/wiki/3GP_and_3G2) for `video/3gpp` that Immich does not currently support.

**Comment by jrasm91** [comment]
Feel free to open a PR. There should only be one place where extensions are listed. Well that and the spec file
