### ISSUE TITLE
Spelling/Grammar issue

### ISSUE THREAD

**Issue by TaylorHassall** [immich-app/immich#8399]
### The bug

Not a critical issue in the slightest. But under the admin web portal /admin/repair then under offline paths the sentence:
These files are the results of manually deletion of the default upload library

should be something like
These files are the results of manual deletion of the default upload library 
or
These files are the results of manually deleting the default upload library

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Go to Web Portal for Immich as Admin
2. Go to the Repair Tab, left hand side, bottom.
3. Scroll to OFFLINE PATHS (X)
4. See content
```

### Additional information

Not critical at all.

**Comment by mmomjian** [comment]
Thanks!
