### ISSUE TITLE
[Feature]: gravatar for users profile picture

### ISSUE THREAD

**Issue by dapuzz** [immich-app/immich#840]
### Feature detail

It would be nice if users can automatically have their own profile photo using [gravatar ](https://en.gravatar.com/)

Just an idea with veeeery low priority ... :-)
Thank you

### Platform

Server

**Comment by bertmelis** [comment]
I'd rather not have this. I self host just to avoid these kind of privacy problems.

**Comment by alextran1502** [comment]
I agree with @bertmelis's statement. We are trying our best to not using any third party services.
