### ISSUE TITLE
Immich Logo changed by itself to something that is somewhat suspicious...

### ISSUE THREAD

**Issue by manosrh** [immich-app/immich#8424]
### The bug

The application changed its logo in all platforms (web, ios. android) and it looks like this: 
![image](https://github.com/immich-app/immich/assets/138120670/5405178b-1d38-4884-97f2-fb471f1e96b5)

### The OS that Immich Server is running on

Raspbian, Truenas

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.100.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
docker-compose.yml
```

### Your .env content

```Shell
.env
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by zerion87** [comment]
Look at the calendar ;)

**Comment by aminomaboul** [comment]
really guys, i shit my pants right now
just exposed my server to the internet via NPM yesterday, and thought i have been hacked or something

**Comment by manosrh** [comment]
April 1st...
I'm such a FOOL!!! XD

**Comment by Write** [comment]
lmao I'm so dumb I didn't realize either.
