### ISSUE TITLE
Space used metrics are inconsistent

### ISSUE THREAD

**Issue by mmomjian** [immich-app/immich#8426]
### The bug

When using external libraries, the space used metric is inconsistent. The user sees this:
![image](https://github.com/immich-app/immich/assets/50788000/9c1c757d-6098-4156-a61d-3350abc92ec2)

However, the Admin sees this on the Server Stats tab:

![image](https://github.com/immich-app/immich/assets/50788000/3822bb0b-7e3c-4408-a2e6-e29a664c6ca0)

The "4 GB" number matches the size of the External Library as shown in the External Libraries tab.

Solution: Immich should not count the size of an External Library as part of the user Usage. 

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.100.0

**Comment by jrasm91** [comment]
This is in the case the user has a quota and an external library? This should be an easy fix.

**Comment by mmomjian** [comment]
> This is in the case the user has a quota and an external library? This should be an easy fix.

Thats exactly correct.

**Comment by mycroftsnm** [comment]
Hello! i tried solving this issue since it was marked for newcomers, #10036
