### ISSUE TITLE
Weird logo displayed after the last update

### ISSUE THREAD

**Issue by avinal** [immich-app/immich#8431]
### The bug

After updating the mobile app to 1.100.0 I am noticing a weird logo instead of a regular one. IMO this is not expected.

![WhatsApp Image 2024-04-01 at 11 47 21](https://github.com/immich-app/immich/assets/74113200/0bd45429-aadf-472a-b3cd-c641a4a820d6)

### The OS that Immich Server is running on

Raspberry Pi OS based on Bookworm

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.100.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open the web and mobile app
2. Observe the logo
```

**Comment by avinal** [comment]
On a second thought, is this an April Fools' Joke 🤔, just asking.

**Comment by jrasm91** [comment]
It is indeed

**Comment by Pheggas** [comment]
I was wondering if anyone opens issue 🤣

**Comment by QYG2297248353** [comment]
#8430

**Comment by avinal** [comment]
I like this ❤️ , I should close the issue I guess or spoil the fun for other people 🤣

**Comment by aviv926** [comment]
LOLL 🤣

**Comment by stephanvane** [comment]
Hidden in an ['Update-dependency' commit](https://github.com/immich-app/immich/commit/50924f0b3dddb1fa86aec8e0f57b01ff562794bb). Nice work @renovate[bot]! 😆
/

**Comment by avinal** [comment]
> technically you can close it tomorrow for 'not being reproducible anymore' :P

😄  **This is the way**

**Comment by Pheggas** [comment]
> Hidden in an ['Update-dependency' commit](https://github.com/immich-app/immich/commit/50924f0b3dddb1fa86aec8e0f57b01ff562794bb). Nice work `@renovate[bot]`! 😆

But this shows how noone checks those commits. Even if it's open source, it doesn't mean it's safe.

**Comment by avinal** [comment]
Yeah, this one is just a joke, but also an important reminder that do not trust that legit maintainer merging random characters hidden in a JSON file is also legit. We can't be any less careful, especially after the `xz` CVE storm.

**Comment by HansAndreManfredson** [comment]
The logo drove me so crazy that I re-installed it and re-imported all my photos. 
Not too bad as I don't actively use Immich yet! 

The April Fool's joke was worth it! Next time I'd better have a look at the sources... :-D

**Comment by Chuckame** [comment]
Wondering the same, I love it 😂

**Comment by Blisterexe** [comment]
i think that things like this should have a toggle in settings, its a fine prank for home users but some people using may prefer to have that not happen

**Comment by Panic135** [comment]
> i think that things like this should have a toggle in settings, its a fine prank for home users but some people using may prefer to have that not happen

Don't be a fun sponge, its a single day and a toggle in the settings would really ruin the prank.

**Comment by PyroghostX** [comment]
I agree with @Blisterexe. This should have a toggle. we got the prank, we laughed, but now I want to turn it off for my immich. I have hated going into immich today
its not a fun sponge, its I dont want to look at an ugly logo every time im looking through my images

**Comment by alextran1502** [comment]
@PyroghostX thank you for the feedback and sorry for the inconvenience. Our first time doing April fools so we learned a few things.

**Comment by akwan** [comment]
I updated from 1.98 to 1.100 hours before april fools ran out and was like, cool new logo. Oh wait... and found this thread. Cheers folks - timing is definitely iffy with `xz` for sure.

**Comment by Panic135** [comment]
> I agree with @Blisterexe. This should have a toggle. we got the prank, we laughed, but now I want to turn it off for my immich. I have hated going into immich today
> 
> its not a fun sponge, its I dont want to look at an ugly logo every time im looking through my images

100% fun sponge, its a free open source project. Its one day. One. Singular. Day.

**Comment by taylort7147** [comment]
> @PyroghostX thank you for the feedback and sorry for the inconvenience. Our first time doing April fools so we learned a few things.

@alextran1502 I hope this feedback doesn't deter you from doing things like this in the future. There are always going to be people who can't take a joke, but that doesn't mean you stop. I'll bet most people who discovered this got a kick out of it.

For those that didn't appreciate the joke, it's not like major businesses don't do [this same thing](https://archive.google/mentalplex/).

**Comment by alextran1502** [comment]
@taylort7147 no worries, we will be more creative but leaving the option to opt out for others

**Comment by Blisterexe** [comment]
@alextran1502 to be clear, i thought it was funny, i just think that it would be a good idea to be able to opt out, dont let this discourage you of doing more seasonal events in the future

**Comment by sammypanda** [comment]
I love this and I thought it was so funny. I wanted to show someone else and realised no one knows or cares about my nerdy little self hosted image thing in my phone so it probably wouldn't hit the same. but I still hehehe to myself about it

Also people complaining gotta understand that's kinda wild, like talk about the first world problem of all superficial first world problems. I'll threaten to rally for "actually this logo is better, it has more character" xD

**Comment by signaleleven** [comment]
FWIW, it's still in there. I think that it's a valuable lesson on how stuff can be snuck into opensource software, but even a harmless "time bomb", where the behavior of the app changes "for fun" based on the calendar, is still bad. 
Call me a "fun sponge" but this is self hosted code, not a managed service (if there was a "public" immich instance that did this, I'd be shrugging it off), and people that trust a service to run on their infra don't like to be surprised. By people here I mean "me". 
I love immich, I don't love April fool's.

**Comment by signaleleven** [comment]
1.129

**Comment by caesay** [comment]
I don't really care, but fwiw I'm on 1.129.0 which is fairly recent and got the drawn logo today. It's actually a bit screwed up, margins/paddings are off. I assume the css has moved on since this was written and forgot about.
