### ISSUE TITLE
Some Videos in Web-Viewer only plays audio

### ISSUE THREAD

**Issue by DeltaTango69** [immich-app/immich#8435]
### The bug

In Chrome suddenly some videos are not playing. Only audio is to hear. On Android mobile there is no problem.

immich_server            |     at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE
immich_server            | [Nest] 7  - 04/01/2024, 6:56:51 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
immich_server            | [Nest] 7  - 04/01/2024, 6:56:51 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
immich_server            | [Nest] 7  - 04/01/2024, 6:56:52 PM   ERROR [Error: write EPIPE
immich_server            |     at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file
immich_server            | [Nest] 7  - 04/01/2024, 6:56:52 PM   ERROR [Error: write EPIPE
immich_server            |     at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE
immich_server            | [Nest] 7  - 04/01/2024, 6:56:59 PM   ERROR [Error: write EPIPE
immich_server            |     at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file
immich_server            | [Nest] 7  - 04/01/2024, 6:56:59 PM   ERROR [Error: write EPIPE
immich_server            |     at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE 

Mediainfo:
Allgemein
Vollständiger Name                       : V:\2010\10_06_20_Am_Duempel\20100620(154047).mp4
Format                                   : MPEG-4
Format-Profil                            : Base Media
Codec-ID                                 : isom (isom/iso2/mp41)
Dateigröße                               : 520 KiB
Dauer                                    : 2s 137 ms
Modus der Gesamtbitrate                  : variabel
Gesamte Bitrate                          : 1 993 kb/s
Bildwiederholungsrate                    : 25,000 FPS
Aufnahmedatum                            : 2010-06-20T15:40:47+0200
Kodierungs-Datum                         : 2010-06-20 13:40:47 UTC
Tagging-Datum                            : 2010-06-20 13:40:47 UTC
Kodierendes Programm                     : Lavf53.31.100

Video
ID                                       : 1
Format                                   : MPEG-4 Visual
Format-Profil                            : Advanced Simple@L1
Format-Einstellungen                     : BVOP
Format-Einstellungen für BVOP            : Ja
Format-Einstellungen für Qpel            : Nein
Format-Einstellungen für GMC             :  Keine warppoints
Format-Einstellungen für Matrix          : Default (H.263)
Codec-ID                                 : mp4v-20
Dauer                                    : 2s 80 ms
Bitraten-Modus                           : variabel
Bitrate                                  : 1 888 kb/s
maximale Bitrate                         : 5 000 kb/s
Breite                                   : 1 280 Pixel
Höhe                                     : 720 Pixel
Bildseitenverhältnis                     : 16:9
Modus der Bildwiederholungsrate          : konstant
Bildwiederholungsrate                    : 25,000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scantyp                                  : progressiv
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.082
Stream-Größe                             : 479 KiB (92%)
verwendete Encoder-Bibliothek            : Lavc53.60.100
Kodierungs-Datum                         : 2010-06-20 13:40:47 UTC
Tagging-Datum                            : 2010-06-20 13:40:47 UTC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec-ID                                 : mp4a-40-2
Dauer                                    : 2s 137 ms
Bitraten-Modus                           : konstant
Bitrate                                  : 132 kb/s
Kanäle                                   : 2 Kanäle
Channel layout                           : L R
Samplingrate                             : 44,1 kHz
Bildwiederholungsrate                    : 43,066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream-Größe                             : 34,5 KiB (7%)
Default                                  : Ja
Alternate group                          : 1
Kodierungs-Datum                         : 2010-06-20 13:40:47 UTC
Tagging-Datum                            : 2010-06-20 13:40:47 UTC

https://github.com/immich-app/immich/assets/82575543/19e49576-99aa-4aba-8e35-1b4c3564121b

### The OS that Immich Server is running on

Windows 11

### Version of Immich Server

V1.100.0

### Version of Immich Mobile App

V1.100.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
irrelevant
```

### Your .env content

```Shell
irrelevant
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by alextran1502** [comment]
Do you have transcoding disabled? Can you post your video transcoding options and configuration?

**Comment by DeltaTango69** [comment]
Yes transcoding is disabled. It works before?
