### ISSUE TITLE
[Feature]: Dark mode for web

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#844]
### Feature detail

Add a dark mode for web

### Platform

Web

**Comment by AlexeyKhalin** [comment]
I guess you just need to create a custom [theme ](https://docs.flutter.dev/cookbook/design/themes)

**Comment by alextran1502** [comment]
> I guess you just need to create a custom [theme ](https://docs.flutter.dev/cookbook/design/themes)

We are not using Flutter for the web app 😀
