### ISSUE TITLE
[BUG] Not possible to Sign Out with "Stay logged in" option enabled

### ISSUE THREAD

**Issue by pVer297** [immich-app/immich#845]
- [X] I have read thoroughly the README setup and installation instructions.
- [X] I have included information on my machine, and environment.

**To Reproduce**
1. Go to the login page (Android App)
2. Enter user login details
3. Enable "Stay logged in" option and log in
4. Sign out (user details are remembered)
5. Close the app / Clear app from memory
6. Open app (user is still logged in)
7. Sign out
8. Untick "Stay logged in" option and log in
9. Sign out (user details are cleared)

**Expected behavior**
The "Stay logged in" option should only keep login details in case the app is closed. 
If explicit "Sign out" happens login details shall be cleared.

**Screenshots**
If not reproducible I can provide video of the bug.

**System**
- Phone OS [Android]: `Android 11 / MIUI 12.5.8.0`
- Server Version: `v1.32.1`
- Mobile App Version: `1.32.1 build.51`

**Additional context**
Additional note, the server endpoint could be kept implicitly, user is changing more frequently than endpoint.

**Comment by zkhan93** [comment]
I did face this issue while working on back navigation fix
