### ISSUE TITLE
[BUG] Photos taken with the front camera are not visible

### ISSUE THREAD

**Issue by MozPri** [immich-app/immich#846]
**Describe the bug**
Photos taken with the front camera are not visible on web and mobile app.
Photos are backed up to the server, I can find them if I ssh into the server.
The asset count is correctly increased when a photo is taken.
When selecting "Backup Albums" the thumbnail for the front cam photo is correctly generated.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**System**
- Phone OS [iOS, Android]: `Android 10, Samsung Galaxy A7-2018`
- Server Version: `v1.32.1`
- Mobile App Version: `1.32.1 build.51`

**Comment by alextran1502** [comment]
Can you try taking one sample photo with that camera and attach the file here so we can take a look?

**Comment by MozPri** [comment]
From the phone:
![20221022_182203](https://user-images.githubusercontent.com/8180464/197350756-9b95d877-7bed-4b48-a67f-9a30957c6860.jpg)

From the Immich server:
![940405c0-7a51-4747-b0ad-98f96fdf544e](https://user-images.githubusercontent.com/8180464/197350766-46a57076-b4ef-49e7-9faa-fdce5d3fcc98.jpg)

**Comment by alextran1502** [comment]
Confirmed this is a bug for the thumbnail generation library.
