### ISSUE TITLE
Failed to get assets by city (500)

### ISSUE THREAD

**Issue by drifter75** [immich-app/immich#8462]
### The bug

Error when Explore > Places > View All

can be reproduced on demo site.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

Not Used

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-----------------
```

### Your .env content

```Shell
------------------
```

### Reproduction steps

```bash
Explore > Places > View All
```

**Comment by bo0tzz** [comment]
Please use the search before opening a new issue, there's been a few reports of this already ;) It's been fixed and will be in the next release.
