### ISSUE TITLE
Album Type Selector can Disappear on Web

### ISSUE THREAD

**Issue by NIronwolf** [immich-app/immich#8477]
### The bug

The nav bar to select the Album type can disappear.

My test user has 1 album shared with them.

If I go to Albums it defaults to "All".  This album appears.
If I select Shared, this album still appears.
If I select "Owned" (they don't have any Albums or photos yet), the nav bar gets hidden and you must create an album to get it back.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v.1.100.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Using unRAID containers.
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
My test user has 1 album shared with them.

If I go to Albums it defaults to "All".  This album appears.
If I select Shared, this album still appears.
If I select "Owned" (they don't have any Albums or photos yet), the nav bar gets hidden and you must create an album to get it back.
```

**Comment by aviv926** [comment]
I can't reproduce this problem, what browser are you using?

**Comment by NIronwolf** [comment]
Chrome.  I went back through it and I see now that I had my window a bit narrow & my zoom up a notch or two.  _This_ is the root cause.  If the window narrows to much, the nav and search drop below the line are next to the cards for the albums.  Then if the albums "go away" to show the create and album card they are not visible until the window is widened or the zoom is reduced so that the nav/search can fit above the line again.

**Comment by Snowknight26** [comment]
Is this still an issue? I can't reproduce on v1.105.1.

**Comment by jrasm91** [comment]
> Chrome. I went back through it and I see now that I had my window a bit narrow & my zoom up a notch or two. _This_ is the root cause. If the window narrows to much, the nav and search drop below the line are next to the cards for the albums. Then if the albums "go away" to show the create and album card they are not visible until the window is widened or the zoom is reduced so that the nav/search can fit above the line again.

If you can reproduce this, maybe you can send a video recording of it happening.

**Comment by jrasm91** [comment]
I cannot reproduce this either, so I'll mark it as resolved.
