### ISSUE TITLE
Not all pictures of a person showing in ios app

### ISSUE THREAD

**Issue by gtzapper** [immich-app/immich#8483]
### The bug

I am using immich since 6 months now, first time i faces this issue.
I have images stored these since 2015 to present and a large library of photos. When i go and search photos of a person, the old photos don't appear in the ios app, i can see pictures from recent years only. This is happening to the people who have a lot of photos (>3000-5000)
The faces with large number of pictures are the only ones having this issue, and that too not all the faces with large amount of photos.
In the web interface everything works perfect all pictures of a particular face appears perfectly right down to the oldest one, but in the app some of the oldest years would be skipped. I can see all the pictures in the home page of the app going back to the oldest pictures. Reinstalling the app didnt help, also the the issue is same on ipad. 
Last month i can confirm this issue was not there, its new domt know exactly since when as i didnt use the face menu since last month i guess.

### The OS that Immich Server is running on

unraid

### Version of Immich Server

1.100.0

### Version of Immich Mobile App

1.100.0 build.146

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Installed via community app store in unraid, running with external database container
```

### Your .env content

```Shell
Installed via, community app store
```

### Reproduction steps

```bash
1.open the ios app
2.go to search
3.tap a face
4.scroll to the bottom
```

**Comment by jimeelicious** [comment]
This seems to occur for me as well, on Android. I have quite a few photos of a particular person dating back to 2008 which show up normally on the web browser, but not the phone app. Running the latest version as of today.

**Comment by chodthewacko** [comment]
I have a person who has pictures dating back to 2012 on the web page, but I only see pictures after 2020 on the app.
This is only started happening recently - probably due to the timeline spacing changes.

**Comment by gtzapper** [comment]
Yes, this started happening recently but i cant pin point exactly when, as i guess i didn't use it for a couple of months i guess

**Comment by dgtal1** [comment]
Same here on both Android and iOS. Surprisingly the web app is not affected and shows the entire time range. I can scroll down endlessly until I hit the oldest photo of a person.

I've got a huge external library of >55k photos dated back to 2006. Depending on face I see results only back to 2019,2020 or 2021 in the mobile apps.

**Comment by chodthewacko** [comment]
I know what the problem is - the mobile app is capping the total number of pictures you can view for a person.
I'm not sure what the limit is, but if you start archiving pictures that you can see, then more start appearing at the bottom.
I don't see why the main page can show an arbitrarily large number of pictures, but we need to put a cap on 'faces just for one person'

**Comment by gtzapper** [comment]
Well, many of our libraries are large and this is a much required correction to be made. 
And many of us will benefit from it

**Comment by bo0tzz** [comment]
#5722
