### ISSUE TITLE
[BUG] Deleted images are synced again

### ISSUE THREAD

**Issue by ngugcx** [immich-app/immich#849]
**Describe the bug**
Images deleted from the web will be synced again to the server by the mobile app.
Is this an expected behaviour?

**Task List**

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Delete images using the web
2. Open the mobile app again, then click "Start Backup"
3. The deleted images will be synced again to the server.

**Expected behavior**
Images by the web should not be synced again.

**System**
- Phone OS [iOS, Android]: Android 11
- Server Version: v1.32.1
- Mobile App Version: v1.32.1

**Comment by alextran1502** [comment]
Yes this is the expected behavior

**Comment by ngugcx** [comment]
> Yes this is the expected behavior

What's the point of deleting on the web?

**Comment by ngugcx** [comment]
> One example is that I want to share photos between machine, I can quickly upload them to the web and access the web interface on another machine to download them. After that I don't need them anymore so I delete them

OK, I see, but it might still confuse other users.
