### ISSUE TITLE
[Feature]: Don't sync delete operations

### ISSUE THREAD

**Issue by ngugcx** [immich-app/immich#850]
### Feature detail

Currently, if a photo is deleted in the phone album, the mobile app will sync this delete operation to the server, and the image on the server will be deleted.
But many times, people delete photos just to save space on their phones, not because the photos are no longer needed.

Is it possible to add an option "Don't sync delete operations"?

### Platform

Mobile App

**Comment by alextran1502** [comment]
The photos which are seen on the mobile app are backed up and on the server. 

You are saving space on your phone by deleting the photos that are on your phone, not on the mobile app.  Is this what you mean?

**Comment by ngugcx** [comment]
> You are saving space on your phone by deleting the photos that are on your phone, not on the mobile app. Is this what you mean?

Yes, I want to keep the photos on the server, but delete them from my phone for saving space.

**Comment by alextran1502** [comment]
Then you will need to delete them from your native gallery app of your phone, not from Immich. I hope this will help.

**Comment by ngugcx** [comment]
> 



> Then you will need to delete them from your native gallery app of your phone, not from Immich. I hope this will help.

The delete ops from the native gallery app are not synced by immich mobile app? That's what I want.
