### ISSUE TITLE
Getting assets by city fails with a 500 error

### ISSUE THREAD

**Issue by whimsical-c4lic0** [immich-app/immich#8500]
### The bug

The issue is present on the demo website.
https://demo.immich.app/places

Web:
Clicking on the "View All" button in the "Places" section of the explore page results in a 500 error. The logs appear to point to the issue being converting the javascript array of user ids to a postgres array in the database query.

Mobile:
The equivalent feature on the mobile appears to work fine.

### The OS that Immich Server is running on

Demo website and docker

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Navigate to the explore page
2. Click on the "View All" button in the "Places" section
```

**Comment by mertalev** [comment]
Hi! This bug is already fixed on main, so just wait for the next release.

**Comment by whimsical-c4lic0** [comment]
Great! Thanks!
