### ISSUE TITLE
Failure to complete final assets in iOS backup. No failure messages to display problem files.

### ISSUE THREAD

**Issue by Krolitian** [immich-app/immich#8505]
### The bug

Unable to complete backup due to the following errors. Unlike other errors that listed failed files so that I could fix them, these assets don't and therefore leave the app perpetually backing up.

```
LogLevel.WARNING	HashService	Failed to get file for asset 6776F306-5137-4A73-8E90-A42A44EC92D0/L0/001, skipping		
LogLevel.WARNING	HashService	Failed to get file for asset C4E37EAC-2A35-4CC8-B22C-AB0A1B221925/L0/001, skipping		
LogLevel.WARNING	HashService	Failed to get file for asset D0201D61-AC23-4749-BB74-3C6A6550F2EA/L0/001, skipping		
LogLevel.WARNING	HashService	Failed to get file for asset C59668BD-3903-436C-B669-F3EC77E7EAED/L0/001, skipping		
LogLevel.WARNING	HashService	Failed to get file for asset 816367F0-E1D4-4557-892F-9514BB7ECD60/L0/001, skipping		
LogLevel.WARNING	HashService	Failed to get file for asset C510AD4E-ECFA-422E-BFC4-597E3A8F779A/L0/001, skipping		
LogLevel.WARNING	HashService	Failed to get file for asset 6958A343-CB15-4D2C-B0CE-3FC01DABAEFD/L0/001, skipping		
LogLevel.WARNING	HashService	Failed to get file for asset 387CEB66-B27E-415E-AE55-CC7B1FDA97BD/L0/001, skipping		
```

![IMG_59B492C2DE72-1](https://github.com/immich-app/immich/assets/82565931/533d2844-37ea-4839-86c6-a6e99987ae6d)

### The OS that Immich Server is running on

UnRaid Docker Container

### Version of Immich Server

1.100.0

### Version of Immich Mobile App

v1.100.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
docker run
  -d
  --name='immich'
  --net='bridge'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Monolith"
  -e HOST_CONTAINERNAME="immich"
  -e 'DB_HOSTNAME'='<URL>'
  -e 'DB_USERNAME'='postgres'
  -e 'DB_PASSWORD'='postgres'
  -e 'DB_DATABASE_NAME'='immich'
  -e 'REDIS_HOSTNAME'='localhost'
  -e 'DB_PORT'='5433'
  -e 'REDIS_PORT'='6379'
  -e 'REDIS_PASSWORD'=''
  -e 'MACHINE_LEARNING_GPU_ACCELERATION'=''
  -e 'MACHINE_LEARNING_WORKERS'='1'
  -e 'MACHINE_LEARNING_WORKER_TIMEOUT'='120'
  -e 'DOCKER_MODS'='imagegenius/mods:universal-redis'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png'
  -p '8008:8080/tcp'
  -v '/mnt/user/photos_immich/':'/photos':'rw'
  -v '/mnt/user/appdata/immich':'/config':'rw' 'ghcr.io/imagegenius/immich:latest'
```

### Your .env content

```Shell
Default I guess
```

### Reproduction steps

```bash
1. Try to run backup with 8 assets remaining.
2. Nothing happens as it just skips them without detailing what files it's trying to access.
```

**Comment by Krolitian** [comment]
v1.101.0 log now shows problem files and allows them to be fixed. Mostly corrupt files, but also normal files rejected due to long filename, but that's an issue for another day.

**Comment by cbass27** [comment]
I have this problem. What did you do to fix your issue? The file(s) that are indicated from the log as failing to get file for asset don't seem to exist on my server anywhere. I'm not clear on whether these are files on my iphone or supposedly the server? Of course, searching for the photo's filename directly from the photo's app on the iphone provides no results.

**Comment by Krolitian** [comment]
@cbass27 Searching the filename in the iOS Photos app won't show the images, the search is pretty bad. Look at the logs to see the dates of the problem files, and go to that time in your Library section (not Recents) till you get to the date in the log. Scroll through each one on that date till you find the right filename. If it's anything like mine, you'll get an error when viewing the broken file that it can't load it from the server. You'll have to delete it and redownload it from wherever it came from, like how mine were downloaded improperly from Snapchat and Google Photos and thankfully I didn't delete the originals from there so I downloaded them, fixed the dates, shared it off and back onto the phone to hard write the fixed dates, and uploaded it again.
