### ISSUE TITLE
Places search inaccurate with similar place names

### ISSUE THREAD

**Issue by honulii** [immich-app/immich#8516]
### The bug

I have photos from two locations. The reverse geocoding has determined the place names. I will use fake place names as an example for privacy. Imagine the two place names are:
Flower Hill
Hill Flowers

When I go to explore>places and click on either Flower Hill or Hill Flowers, the results I get include both locations. I can see that clicking on a place name is basically just the equivalent of an m: search. These two locations are hundreds of miles apart in different states. It seems like the search is looking for similar place names instead of an exact match. 

I haven't tried on web because of the related issue that causes a 500 error if you have partner sharing on and view places, but I would expect the same problem I'm seeing on mobile. 

### The OS that Immich Server is running on

Synology DSM

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.100.0 build 146

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not sure how to find on Portainer, but I believe it matches the latest file
```

### Your .env content

```Shell
Not sure how to find on Portainer
```

### Reproduction steps

```bash
1. Click explore
2. Click view all on places
3. Click a place that has a similar name to another place
```

**Comment by alextran1502** [comment]
The mobile search has been overhauled to look and behave exactly like the web, and it will be available in the next release. I will close this issue as it is no longer relevant.

Ref: #8392
