### ISSUE TITLE
[BUG] Some times, photos cannot be deleted on the mobile app

### ISSUE THREAD

**Issue by ngugcx** [immich-app/immich#852]
**Describe the bug**
Some times, when deleting photos on the mobile app, it fails without an error.

**Task List**

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included information on my machine, and environment.

**To Reproduce**
It's not always reproducible.
1. Delete some photos on the mobile app
2. Some times, the photos are not deleted, or it looks like deleted, but after some seconds, they show up again.

**Expected behavior**
The photos are deleted correctly.

**Screenshots**

https://user-images.githubusercontent.com/44153489/197401326-a2d50514-abc5-4b25-b7a9-68dd2c31c976.mp4

**System**
- Phone OS [iOS, Android]: Android 11
- Server Version: v1.32.1
- Mobile App Version: v1.32.1

**Comment by alextran1502** [comment]
You are having the auto foreground backup turning on, so if you delete the photo solely on the Immich's server without removing it from your phone, it will be reupload.

From the video, right at second 7, you see it flashes for a couple hundred milliseconds that the photo disappear then reappear.

Agreeing that I see some local state is not cleaning up properly. 

Can you try disable automatically foreground backup and try remove a photo and see if it is the behavior you are expecting.

**Comment by ngugcx** [comment]
> Can you try disable automatically foreground backup and try remove a photo and see if it is the behavior you are expecting.

I disabled automatically foreground backup, some times, it still failed to delete if I chose not to put the photo in the recycle bin.

https://user-images.githubusercontent.com/44153489/197402890-defe55dc-7768-406e-8eb2-095370c00ba2.mp4

**Comment by alextran1502** [comment]
Thank you for the report, I will investigate this issue. 

Just for a note for myself. This issue is currently not reproducible on iOS

**Comment by ngugcx** [comment]
Actually after disabled automatically foreground backup, some times it also failed even though I chose to put it into the recycle bin.

**Comment by alextran1502** [comment]
Hello, is this still relevant?

**Comment by bo0tzz** [comment]
@alextran1502 suggestion to close this as stale?
