### ISSUE TITLE
Renovate doesn't show changelogs for docker updates. Suspect its due to :latest being broken

### ISSUE THREAD

**Issue by halkeye** [immich-app/immich#8530]
### The bug

Looking at https://github.com/halkeye/home-k8s/pull/92, it doesn't have links to changelogs or anything else.

When i look at the labels, the source label is setup properly

```
regctl image config ghcr.io/immich-app/immich-server:v1.101.0 --format '{{ jsonPretty .Config.Labels }}'
{
  "org.opencontainers.image.created": "2024-04-05T02:56:41.512Z",
  "org.opencontainers.image.description": "High performance self-hosted photo and video management solution.",
  "org.opencontainers.image.licenses": "AGPL-3.0",
  "org.opencontainers.image.revision": "3b0fff3b3d06cfc6a8a201b20303d9007af5dbca",
  "org.opencontainers.image.source": "https://github.com/immich-app/immich",
  "org.opencontainers.image.title": "immich",
  "org.opencontainers.image.url": "https://github.com/immich-app/immich",
  "org.opencontainers.image.version": "v1.101.0"
}
```

But when I check the tagless version, I get null
```
regctl image config ghcr.io/immich-app/immich-server --format '{{ jsonPretty .Config.Labels }}'
null
```

Looking at what "latest" gives me
```
docker run -it --rm --entrypoint "" ghcr.io/immich-app/immich-server:latest grep version package.json
  "version": "1.5.1",
```
Which is really old, So it seems reasonable that this is the case.
Plus https://github.com/renovatebot/renovate/blob/fc315f446f2e9e6a6da54ae9fb2182a7870b9ca6/lib/modules/datasource/docker/readme.md?plain=1#L3 talks about "latest stable" though I havn't yet determined how it figures that out on.

Can you update the "latest" tag to something a bit more modern that has those labels?

### The OS that Immich Server is running on

github

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by halkeye** [comment]
digging around https://github.com/renovatebot/renovate/blob/fc315f446f2e9e6a6da54ae9fb2182a7870b9ca6/lib/modules/datasource/docker/index.ts#L1007-L1026 it seems like it uses "latest", otherwise finds the most recent valid version number tag.

So deleting latest is an option too

**Comment by mmomjian** [comment]
We use the `release`, not `latest` anymore. I believe that would have to be updated on your end?

**Comment by halkeye** [comment]
I think it only uses the tag to figure out what docker labels to use, to find out what is the github source repo, so I think deleting latest makes the most sense, since its not used, and it can easily lead to confusion if people don't provide a tag.

**Comment by mmomjian** [comment]
I suppose deleting latest would make sense, since we would rather someone gets an error when pulling that than to end up with v 1.52.

**Comment by halkeye** [comment]
👍 👍 two birds one docker tag!

**Comment by bo0tzz** [comment]
Fixed by deleting `latest`
