### ISSUE TITLE
(Un)stacking photos does not refresh the asset viewer

### ISSUE THREAD

**Issue by Funk66** [immich-app/immich#8538]
### The bug

I noticed inconsistent and erroneous behavior in how the stack operation works, likely caused by incorrect handling of async calls leading to race conditions.

### The OS that Immich Server is running on

Raspbian

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Same as docker-compose.prod.yml
```

### Your .env content

```Shell
Default
```

### Reproduction steps

```bash
1. Select and stash assets
2. Click on resulting stack to open the viewer component
3. The asset can't be loaded, or is still shown in its previous state: either unstacked or with fewer children
4. After refreshing the page, all assets are shown correctly
```

**Comment by Snowknight26** [comment]
Is this still an issue? I can't reproduce the stacking behavior in v1.105.1.

**Comment by Funk66** [comment]
I just tested it and wasn't able to reproduce it on v1.105.1 either.
