### ISSUE TITLE
Album filter hidden on narrow windows when no albums are shown

### ISSUE THREAD

**Issue by whimsical-c4lic0** [immich-app/immich#8547]
### The bug

When the browser window is narrower than normal and no albums are shown on the page, the album filter is hidden. The issue occurred for me on my 1920x1080 monitor at half width, so I had a window that was 960px wide.

https://github.com/immich-app/immich/assets/124305936/9b04d4a6-2ced-41dd-8894-58fc500bbb92

### The OS that Immich Server is running on

Demo

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Navigate to albums page on the demo website
2. Use a browser window that is 960px wide
3. Click on "Shared" in the album filter
4. The album filter is now hidden unless you change the browser window width
```

**Comment by Snowknight26** [comment]
Is this still an issue? I can't reproduce on v1.105.1.

**Comment by whimsical-c4lic0** [comment]
I am unable to replicate this issue using the latest version of immich locally. The demo site currently has shared albums, so I wasn't able to use that for testing though.
