### ISSUE TITLE
[BUG] Automatic background backup is not working on Android

### ISSUE THREAD

**Issue by ngugcx** [immich-app/immich#856]
**Describe the bug**
After enable "Automatic background service", automatic background backup is still not working.

**Task List**

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Turn on "Automatic background service" on the mobile app
2. Automatic background backup is not working.

**Expected behavior**
Automatic background backup should be running at background after enable "Automatic background service".

**System**
- Phone OS [iOS, Android]: Android 11
- Server Version: v1.32.1
- Mobile App Version: v1.32.1

**Comment by alextran1502** [comment]
Did you follow the prompt to disable battery optimization on your phone?

What is your phone model? I know the newer version of Samsung phone is very strict on battery optimization.

**Comment by ngugcx** [comment]
> Did you follow the prompt to disable battery optimization on your phone?
Yes, I put it in the whitelist.
> 
> What is your phone model? I know the newer version of Samsung phone is very strict on battery optimization.

Redmi Note 9 Pro.
Actually the backgroud service is not started from the beginning, even when I was using the phone.

**Comment by ngugcx** [comment]
So It's not working for the initial sync?

**Comment by alextran1502** [comment]
> So It's not working for the initial sync?

No, it should work for the initial sync. Try to add new photo to the album you are trying to backup in the background and see if the process starts.

**Comment by ngugcx** [comment]
After switch it to background, it's working, though very slow.

**Comment by alextran1502** [comment]
Slowness can come from multiple factors. If you are observing a different bugs, please help open a new issue. 

Thank you for reporting. I will probably need to put the inner working mechanism of background backup to the documentation somewhere.
