### ISSUE TITLE
Copy keyboard shortcuts do not work on Web

### ISSUE THREAD

**Issue by mmomjian** [immich-app/immich#8583]
### The bug

In both Firefox and Chrome, the "Ctrl+C" keyboard shortcut does not function to copy text. You can still copy by right clicking and selecting Copy. Having the Ctrl C shortcut is useful when working with filenames and GPS coordinates. Immich web UI should not preempt this keyboard combination, which is what I believe is currently happening, and can lead to user confusion.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.100.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by bo0tzz** [comment]
Does this happen to you on all pages, or only when viewing an asset? On the latter page, Ctrl+C is bound to copy the image file itself. However if text is selected we should probably skip the custom keyboard handler.

**Comment by mmomjian** [comment]
Yes, it’s on the asset page. Thanks, makes sense. I didn’t realize it copies the image.

**Comment by justin13888** [comment]
Agreed. I also want the delete keyboard button to delete photos
