### ISSUE TITLE
Return 404 on non-existing paths

### ISSUE THREAD

**Issue by Funk66** [immich-app/immich#8590]
### The bug

Immich shows a server error (500) with no information (defaults to 'Hmm, not sure about that. Check the logs or open a ticket?') whenever the user tries to access an undefined path. It should return a 404 'not found' error instead.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Go to any random path such as https://<immich domain>/whatever
2. The user is shown an unhelpful error message suggesting to open a bug ticket
```

**Comment by shubhrad1** [comment]
Can I work on this?

**Comment by shubhrad1** [comment]
I think the issue has already been solved. Accessing an undefined path already shows error 404. 

<img width="1438" alt="Screenshot 2024-07-22 at 11 07 04 PM" src="https://github.com/user-attachments/assets/5afb70e2-0844-45ba-9d70-4ff951f32278">
