### ISSUE TITLE
[BUG] Mobile does not use bulk endpoint when editing metadata

### ISSUE THREAD

**Issue by honulii** [immich-app/immich#8642]
### The bug

Anytime I try to change location for more than 100 photos, after they're done processing, I get a 504 error. It seems like the changes still apply but I'm not positive. I've tried to check a few times but sometimes I'm adding a location to photos that are missing a location and there can be over 400 at a time that I'm editing, so I don't want to check every photo by hand. Just thought I would report it too in case there might be other stuff going on that I'm not noticing, and because the error just makes me nervous as a non-advanced user!

I haven't updated to the latest version of Immich that just came out but this has been happening on the last 3 versions I've been on.

There isn't a visible error notification on mobile but the logs suggest something isn't quite right there either, although that might be on my end like my firewall, I'm not sure.

### The OS that Immich Server is running on

Synology DSM

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v.1.100.0 build 146

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: redacted for privacy?
    environment:
      - TZ=redacted for privacy?
    volumes:
      - /volume1/docker/immich/redis:/data
    restart: on-failure:5

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data
    environment:
      - TZ=redacted for privacy?
      - POSTGRES_DB=immich
      - POSTGRES_USER=redacted for privacy?
      - POSTGRES_PASSWORD=redacted for privacy?
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-server.sh"]
    container_name: Immich-SERVER
    hostname: immich-server
    user: redacted for privacy?
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:3001
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-microservices.sh"]
    container_name: Immich-MICROSERVICES
    hostname: immich-microservices
    user: redacted for privacy?
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
      - /volume1/docker/immich/micro:/usr/src/app/.reverse-geocoding-dump
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: redacted for privacy?
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
      - /volume1/docker/immich/cache:/cache
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
Don't know how to find this on Portainer
```

### Reproduction steps

```bash
On web version:
1. Select over 100 photos, at least 101
2. Select change location
3. Use the map and find a location, then click Confirm
4. Wait for the update to apply and the error will appear

On mobile app:
1. Select over 100 photos, at least 101
2. Select edit location
3. Use the map and find a location, then click Update
4. The Photos icon will repeatedly show a little spinner that starts to spin and appears and disappears like it's flickering. Wait for this to stop
```

### Additional information

Logs for a time when this happened are copied below.

[Nest] 8  - 04/08/2024, 2:16:12 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:12 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:20 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:23 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:24 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:24 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:24 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:24 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:25 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:26 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:26 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:26 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:26 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:26 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:26 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:16:26 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:19:34 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:19:34 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:19:34 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:19:40 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:19:40 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:19:40 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:19:40 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:19:40 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:19:40 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 2:22:57 PM     LOG [EventRepository] Websocket Disconnect: RvsBqthc5PPU8MvRAADl
[Nest] 8  - 04/08/2024, 2:22:57 PM     LOG [EventRepository] Websocket Connect:    mmCGpSbzbqbBCZk5AADn
[Nest] 8  - 04/08/2024, 2:22:58 PM     LOG [EventRepository] Websocket Disconnect: mmCGpSbzbqbBCZk5AADn
[Nest] 8  - 04/08/2024, 2:28:14 PM     LOG [ServerInfoService] Found 1.101.0, released at 4/4/2024, 7:56:13 PM
[Nest] 8  - 04/08/2024, 3:50:44 PM     LOG [EventRepository] Websocket Connect:    Tsnnmp8ZXCaJ7oGVAADp
[Nest] 8  - 04/08/2024, 3:50:50 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:50 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:52 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:52 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:52 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:52 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:52 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:52 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:54 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:54 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:57 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:57 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:57 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:57 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:57 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:57 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:57 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:57 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:57 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:50:57 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:51:43 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:52:35 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:52:35 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:58:29 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:58:29 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:58:29 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 3:59:50 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 04/08/2024, 4:00:37 PM     LOG [EventRepository] Websocket Connect:    exSRoW1wPRjgUu-gAADr
[Nest] 8  - 04/08/2024, 4:01:02 PM     LOG [EventRepository] Websocket Disconnect: exSRoW1wPRjgUu-gAADr
[Nest] 8  - 04/08/2024, 4:01:04 PM     LOG [EventRepository] Websocket Connect:    NnQzygHlSzUBXE2XAADt
[Nest] 8  - 04/08/2024, 4:01:25 PM     LOG [EventRepository] Websocket Disconnect: NnQzygHlSzUBXE2XAADt

Here are some of the logs after updating over 100 locations at once on mobile.

[Nest] 8  - 04/08/2024, 4:16:50 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect
[Nest] 8  - 04/08/2024, 4:16:50 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Failed to update asset
[Nest] 8  - 04/08/2024, 4:16:50 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect
[Nest] 8  - 04/08/2024, 4:16:50 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Failed to update asset
[Nest] 8  - 04/08/2024, 4:16:50 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Failed to update asset
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Failed to update asset
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Failed to update asset
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Failed to update asset
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Failed to update asset
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Failed to update asset
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Failed to update asset
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Failed to update asset
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Failed to update asset
[Nest] 8  - 04/08/2024, 4:16:51 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect
[Nest] 8  - 04/08/2024, 4:16:54 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Failed to get audit deletes
[Nest] 8  - 04/08/2024, 4:16:54 PM   ERROR [Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)] Error: timeout exceeded when trying to connect

And here are three errors on the mobile app logs after updating over 100 at once on mobile.

LogLevel.SEVERE	ImmichErrorLogger	PlatformDispatcher - Catch all	#0      AuditApi.getAuditDeletes (package:openapi/api/audit_api.dart:107)
<asynchronous suspension>
#1      AssetService._getRemoteAssetChanges (package:immich_mobile/shared/services/asset.service.dart:55)
<asynchronous suspension>
#2      SyncService._syncRemoteAssetChanges (package:immich_mobile/shared/services/sync.service.dart:160)
<asynchronous suspension>
#3      SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/shared/services/sync.service.dart:52)
<asynchronous suspension>
#4      AssetService.refreshRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:43)
<asynchronous suspension>
#5      AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:52)
<asynchronous suspension>

LogLevel.SEVERE	ImmichErrorLogger	PlatformDispatcher - Catch all	#0      AssetApi.updateAsset (package:openapi/api/asset_api.dart:1584)
<asynchronous suspension>
#1      Future.wait.<anonymous closure> (dart:async/future.dart:518)
<asynchronous suspension>
#2      AssetService.updateAssets (package:immich_mobile/shared/services/asset.service.dart:175)
<asynchronous suspension>

LogLevel.SEVERE	ImmichErrorLogger	PlatformDispatcher - Catch all	#0      AuditApi.getAuditDeletes (package:openapi/api/audit_api.dart:107)
<asynchronous suspension>
#1      AssetService._getRemoteAssetChanges (package:immich_mobile/shared/services/asset.service.dart:55)
<asynchronous suspension>
#2      SyncService._syncRemoteAssetChanges (package:immich_mobile/shared/services/sync.service.dart:160)
<asynchronous suspension>
#3      SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/shared/services/sync.service.dart:52)
<asynchronous suspension>
#4      AssetService.refreshRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:43)
<asynchronous suspension>
#5      AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:52)
<asynchronous suspension>

**Comment by bo0tzz** [comment]
When bulk changing location metadata from the app, it doesn't use the bulk endpoint but makes a separate API call for each asset:
https://github.com/immich-app/immich/blob/9e122764e7e795addd8c6d266806db78dec0b815/mobile/lib/shared/services/asset.service.dart#L176-L178
This causes a huge amount of requests to the server and a lot of postgres queries that eventually overload the database. 

The fix is for the app to use the bulk update endpoint.

**Comment by honulii** [comment]
Will the web version be fixed too? Interestingly, the app doesn't throw a visual error, only the web version does.

**Comment by bo0tzz** [comment]
Good shout, I hadn't caught that you're also seeing this on the web client.
Strangely, as far as I can tell the web client is using the bulk endpoint appropriately:
https://github.com/immich-app/immich/blob/9e122764e7e795addd8c6d266806db78dec0b815/web/src/lib/components/photos-page/actions/change-location-action.svelte#L16-L26
