### ISSUE TITLE
Using the scroll wheel on a timeline causes the whole page to jump slightly (around 1px) in Firefox

### ISSUE THREAD

**Issue by imler** [immich-app/immich#8675]
### The bug

Place a mouse cursor on a timeline and use the scroll wheel on a mouse - up and down multiple times.

You will see that the whole page including the left section with photos starts to jump up and down slightly (looks like just 1 pixel).

This bug is present in the Firefox browser. Chrome doesn’t have that effect.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
-
```

**Comment by jrasm91** [comment]
Fixed in #10646
