### ISSUE TITLE
New places aren’t showing on the “Explore” page and their cover photos are different than on the “Places” page

### ISSUE THREAD

**Issue by imler** [immich-app/immich#8676]
### The bug

I want to report a bug related to places. When you change the location of already geotagged photos, then two things happen - first, new locations ain’t showing on the “Explore” page, and second - thumbnails of locations are different on the “Explore” and “Places” pages.

Steps to reproduce and more info are in section below.

Note that I used real photos in this example, so that’s why I blurred them.

The only item on the “Explore” page is the same as the first on the list of four - same place, but different thumbnail because of the bug.

This bug doesn’t bother me personally, because I geotag all photos in an external tool before I upload them to Immich and I don’t have a need to change location inside Immich, so I won’t encounter this bug, but I was testing something else and noticed this by accident, so I thought it’s worth reporting

![place_thumb1](https://github.com/immich-app/immich/assets/28065743/fb06b32c-fd91-44e2-8f43-24b3078295b7)

![place_thumb2](https://github.com/immich-app/immich/assets/28065743/b89523b8-8772-4e11-ba03-94bff9bacdcd)

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v.1.101.0

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. I started with a fresh Immich instance
2. I uploaded a bunch of geotagged photos to Immich. All of them were taken in one city
3. Exactly one location was created automatically. Let’s call it “Place A”
4. A random thumbnail was assigned to this location, but was the same on both the “Explore” and “Places” pages
5. I have changed the location of three of those geotagged photos from “Place A” using the details pane. Each photo was assigned to a different city.
6. Note that I didn’t touch the photo that was chosen as a thumbnail and I chose three completely different photos on purpose.
7. Now I have four locations on “Places” - that’s correct, but on the “Explore” page those new locations aren’t visible. There is still only one place that was initially created
8. After this process, the thumbnail of Place A on the “Places” page has changed itself, even though the original photo wasn’t touched and is still there
9. The “Explore” page still has an old original thumbnail that is now different from the one on the “Places” page.
```

**Comment by jrasm91** [comment]
New places only show up on the explore page if there are at least 5 assets and the thumbnail is picked at random, so this is working as intended.
