### ISSUE TITLE
[FEEDBACK] Dark mode feedback

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#869]
**Describe the bug**
When enabling dark mode, some components aren't dark, but light. I suspect immich may be using components for individual parts of the page, and that these components aren't changing according to the theme. Though I don't know for sure, because I'm not involved in development.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Enable dark mode
2. Go to administration
3. See error at users tab, jobs tab & server stats tab
4. See error when hovering the question marks in the tabs on the left side of the gallery.

**Expected behavior**
I expected all tables and components to be dark, instead they were light.

**Screenshots**
![image](https://user-images.githubusercontent.com/47184046/198104580-0b26cb86-7198-402d-a2a5-77c68ee900d7.png)
![image](https://user-images.githubusercontent.com/47184046/198104600-dfc84865-b7f4-4bf3-92a2-afdc144b48a4.png)
![image](https://user-images.githubusercontent.com/47184046/198104616-82a8a60f-d69a-4839-9ac1-405686a63b4a.png)
![image](https://user-images.githubusercontent.com/47184046/198105009-dc1e75ed-82f5-4da9-95ed-dfb7de6cfa0b.png)

**System**
- Phone OS [iOS, Android]: `11.0`
- Server Version: `1.33.0`
- Mobile App Version: `1.32.1 build.51`

**Comment by alextran1502** [comment]
This is the color design choice :) I will leave this issue open to collect additional feedback

**Comment by palitu** [comment]
i am ok with the light portions.  I think that you will never win with theming as people are people.

Maybe you can provide a pallete list, that will allow people to set their own colour schemes?

**Comment by alextran1502** [comment]
Added improvement to the table 
![image](https://user-images.githubusercontent.com/27055614/200981576-536def1d-4cf9-4808-bb2e-60fd20a37f60.png)

![image](https://user-images.githubusercontent.com/27055614/200981590-9ec33977-3e9f-455a-b6fe-82abdea1dbf5.png)

![image](https://user-images.githubusercontent.com/27055614/200981607-ae33d454-6cda-4eae-bb99-c2454bed1ea7.png)

**Comment by Hukuma1** [comment]
I know this issue is closed, so not sure if you want me to make a new one? This is for the web upload. A few more dark variations I think need to be added for the uploading popups:

<img width="336" alt="popup" src="https://user-images.githubusercontent.com/54511555/215290216-06523b30-52d0-45c5-8db2-afd2d9d86674.png">

<img width="243" alt="infopanel" src="https://user-images.githubusercontent.com/54511555/215290217-83b1f735-4c51-49d7-868f-e675dc8e70bb.png">
