### ISSUE TITLE
Image shows wrong date on timeline, but correct date in details pane

### ISSUE THREAD

**Issue by Me-Mr** [immich-app/immich#8697]
### The bug

 This is similar to #5391 . 

When uploading a photo from desktop (regardless of browser, cookies, signing out, etc) the photo shows tomorrow's date on the timeline. It shows the correct date in the details pane, and the correct date on the timeline in the mobile app. 

Correct date: 4-10-2024

Timeline date: 4-11-2024

Timeline:

![Screenshot 2024-04-10 at 10 57 25 PM](https://github.com/immich-app/immich/assets/120990407/7d87aa30-1db0-4af7-b5ff-ed305545dfa4)

Detail:

![Screenshot 2024-04-10 at 10 58 21 PM](https://github.com/immich-app/immich/assets/120990407/dd8bae62-a361-4a2a-b490-794a198b49a4)

Exiftools Snippet:

![Screenshot 2024-04-10 at 11 01 26 PM](https://github.com/immich-app/immich/assets/120990407/19e1a79d-3649-47c0-832f-174a0ad7a0c3)

I've attached an example file:
![Screenshot 2024-04-10 at 10 43 49 PM](https://github.com/immich-app/immich/assets/120990407/bed8db37-b0f9-4615-940d-8e1c4d4fbdf0)

Thanks for the amazing app!

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.101

### Version of Immich Mobile App

1.101

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-Unrelated
```

### Your .env content

```Shell
-Unrelated
```

### Reproduction steps

```bash
Steps to reproduce:

1. Screenshot/download file
2. Upload to immich web
3. Verify uploaded file is tomorrow's date on timeline
```

**Comment by danieldietzler** [comment]
If you notice that it's similar to #5391, why open a duplicate then? ;)
