### ISSUE TITLE
(web) Server status changes from online to offline every second.

### ISSUE THREAD

**Issue by natedawg** [immich-app/immich#8735]
### The bug

Server status changes from online to offline every second on the web. I did not notice this before today. The only change to my setup is that docker itself was upgraded today to version [26.0.1](https://docs.docker.com/engine/release-notes/26.0/#2601). Although the server status is switching on and off the rest of the web app appears to be online and seems to function as normal. The mobile app also has no issues. 

I have restarted docker and my system but the issue remains. 

### The OS that Immich Server is running on

Docker on debian

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. Update docker?
2. Open web gui.
3. Observe server status changing every second. 
...
```

**Comment by mmomjian** [comment]
How are you connecting to your Immich server? What is the web URL you are using and are there any proxies between your client and the server?

**Comment by natedawg** [comment]
Ok I guess something is wrong with my setup and not immich. I'm using traeffik for a reverse proxy. Url is https like https://immich.example.com.

**Comment by natedawg** [comment]
Wow thanks! I even started looking through wireshark dumps to see if my hardware was messed up. So traefik introduced a default connection timeout of 2 sec in v2.11.1 but then reverted the change in v2.11.2. I thought I pulled the newest version today when debugging but I guess not. I pinned the version to v2.11.2 and its working.

**Comment by jrasm91** [comment]
Those patches were both released today afaik
