### ISSUE TITLE
Assets (mostly) fail to upload on iOS

### ISSUE THREAD

**Issue by awlsring** [immich-app/immich#8738]
### The bug

I'm having a strange issue with my instance.

Awhile back, my asset upload process on my iPhone 15 Pro started silently failing. Rather than throwing an error, I would see the upload status bar progress to the end, then move on to the next despite the asset not getting uploaded. However, some assets will occasionally upload. These tend to be screenshots and not images created by the camera.

This is not specific to my user. I have created numerous users and logged in on my device and attempt upload, all showing the same behavior. This includes successfully uploading on the same images.

This is not specific to a folder, and changing from recents to favorites produces the same error.

This is specific to my instance. I created a new instance to validate upload from my same device, and I was able to upload all files.

I verified my original account can upload images by logging into it on another device (A several years old Android) and was able to upload.

My partner is also on my instance with an iPhone 14 Pro and is able to upload everything successfully.

While attempting to troubleshoot, I have tried...

- Reinstalling the app
- Reinstalling the app with a power cycle inbetween
- Reinstalling the app, with power cycle, with a new user

I have set the finest logging and am not seeing anything relevant in the logs. Examining the server logs on DEBUG mode, I see no errors being posted.

I'm not sure how to proceed further, so any advice is appreciated! 

### The OS that Immich Server is running on

Ubuntu on K3s

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I use K3S
```

### Your .env content

```Shell
not .env, but env vars I pass to sever deployment

│     Environment:                                                                                                                                                                                                   │
│       UPLOAD_LOCATION:                 ./library                                                                                                                                                                   │
│       DB_HOSTNAME:                     immich-app-postgres-service-c8de0146                                                                                                                                        │
│       DB_USERNAME:                     immich                                                                                                                                                                      │
│       DB_DATABASE_NAME:                immich                                                                                                                                                                      │
│       DB_PORT:                         5432                                                                                                                                                                        │
│       DB_PASSWORD:                     <set to the key 'DATABASE_PASSWORD' in secret 'immich-database-password'>  Optional: false                                                                                  │
│       POSTGRES_PASSWORD:               <set to the key 'DATABASE_PASSWORD' in secret 'immich-database-password'>  Optional: false                                                                                  │
│       IMMICH_MACHINE_LEARNING_URL:     http://immich-app-machine-learning-service-c858f540:3003                                                                                                                    │
│       PUBLIC_IMMICH_SERVER_URL:        -                                                                                                                                                  │
│       REDIS_HOSTNAME:                  immich-app-redis-service-c85a9ac1                                                                                                                                           │
│       LOG_LEVEL:                       debug                                                                                                                                                                       │
│       MACHINE_LEARNING_EAGER_STARTUP:  false
```

### Reproduction steps

```bash
1. Allow asset upload to upload
```

**Comment by alextran1502** [comment]
Do you use a reverse proxy and not include the `client_max_body_size` clause or equivalent?

Ref: https://immich.app/docs/administration/reverse-proxy

**Comment by awlsring** [comment]
I do use nginx, although it is via nginix ingress provider in kubernetes

just for context, here are is my immich chart: https://github.com/awlsring/Homelab/blob/main/infrastructure/kubernetes/charts/immich.k8s.yaml

I don't have anything explicitly set for this. I'll look into how I can for my setup and see if that tries anything.

**Comment by awlsring** [comment]
Wow that was it! Thanks so much!
