### ISSUE TITLE
Thumbnail resolution can't be changed anymore

### ISSUE THREAD

**Issue by take31415** [immich-app/immich#8782]
### The bug

It's not possible to change the resolution settings for Thumbnail creation via Administration -> Settings -> Image Settings.
Changing it via API also doesn't work.
Tested version: v1.101.0

Performed workaround to set it properly: Using v1.98.0 -> Setting resolution -> upgrading to v1.101.0

Probably the bug was introduced with this [commit](https://github.com/immich-app/immich/commit/8edc2fb46f9b3d72c666ffaa4e9ebffd24f2d3df)

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Use latest version (v1.101.0)
2. Change resolution for Thumbnails
3. Click save and see that old value is configured again.
```

**Comment by alextran1502** [comment]
It has been fixed and will be available in the next release
