### ISSUE TITLE
Stacks not preserving image order in ios app

### ISSUE THREAD

**Issue by Emiliaaah** [immich-app/immich#8798]
### The bug

The first/ cover image for a stack seems to be placed at the end of the list of images in a stack in the ios app.
The image is also put at the far left side of the list, while on web it's on the right side. The list also seems to go from right to left, so the preview image being at the complete end seems a bit weird.

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0 build.147

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I don't feel like this is particularity relevant but I can provide if needed
```

### Your .env content

```Shell
I don't feel like this is particularity relevant but I can provide if needed
```

### Reproduction steps

```bash
1. Create a stack through the web UI
2. View that same stack in the mobile app
3. You will see that the order is preserved except for the first image which is now at the complete end of the stack.
```

**Comment by stephen304** [comment]
Noticed this as well in the Android app, the cover image is on the left which is opposite from the web. I don't really have an opinion on which way it should be as long as it's the same.

**Comment by jrasm91** [comment]
Cover image is on the left on the web as well now.
