### ISSUE TITLE
[BUG] Web : Change date modale / DEL key trash the selected pictures

### ISSUE THREAD

**Issue by jeanmatthieud** [immich-app/immich#8804]
### The bug

Pressing the DEL key when the "Change date" modale is visible delete the pictures instead of clearing a field.

*I did not tried on the "Change location" modale*

![image](https://github.com/immich-app/immich/assets/1443167/d5fa2f99-5f58-4099-9a5a-c303c708ef25)

### The OS that Immich Server is running on

TrueNas

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
TrueNas app
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open an album
2. Select some pictures
3. Click on the "..." menu (top right)
4. Click on "Change date"
5. Select a field and click "delete" key on your keyboard
```

**Comment by uniqueeest** [comment]
Hi ! @bo0tzz I am uniqueeest, a new contributor. I'd like to contribute to this issue! Can I proceed??

**Comment by bo0tzz** [comment]
Go ahead, thank you!
