### ISSUE TITLE
BUG: Search bar doesn't autofocus when adding photos to album.

### ISSUE THREAD

**Issue by halphalp** [immich-app/immich#8805]
### The bug

i'm not sure how recently this started happening, but when selecting photos to add to an album, the search bar doesn't auto-focus. i keep accidentally stacking multiple photos when trying to add them to an album because i start typing after clicking 'add'.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
same as provided
```

### Your .env content

```Shell
same as provided
```

### Reproduction steps

```bash
1. Select multiple photos
2. Click + sign
3. Click add to album
4. Note that the search bar doesn't autofocus
```

**Comment by ben-basten** [comment]
> i'm not even sure what the keyboard shortcut is for stacking photos, but i apparently keep hitting it when attempting to type my album names.

Yeah, the shortcut is "s" so it would be easy to unintentionally stack some photos! Looks to me like this is a similar issue to #8804.
