### ISSUE TITLE
Migrate ImmichLogger over to injected ILoggerRepository

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#8824]
#8823 introduces a new ILoggerRepository. All remaining usages of ImmichLogger should be migrated to use this new injected logger.

**Comment by iamamansharma** [comment]
can you assign this to me?

**Comment by jrasm91** [comment]
##7156 updates unit tests to use vitest, so make sure you start on this after that is merged (if you want to avoid merge conflicts)
