### ISSUE TITLE
Video transcoding always happens

### ISSUE THREAD

**Issue by MrSimmo** [immich-app/immich#8839]
### The bug

Hi all,

I've noticed an odd thing (maybe a bug?)

Context: I have a bunch of photos and videos, already in the correct format for browsers/target operating systems etc so they don't need to be transcoded.

I've set the video transcoding option to "never transcode".

When I add an external library, there is a video transcoding job that is added for around 1500 videos out of the total number.

I pause that job and then click clear to remove it.

But it's odd that that job is created in the first place due to the transcoding option being set to never.

Cheers

### The OS that Immich Server is running on

Ubuntu 20.04 Docker

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

unused

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Stock apart from I've added bind mount points for the external library.
```

### Your .env content

```Shell
Stock
```

### Reproduction steps

```bash
1. Disable video transcoding
2. Add external library
3. Video transcoding job appears
```

**Comment by bo0tzz** [comment]
The job always runs, it just doesn't do anything if the file doesn't need transcoding.

**Comment by MrSimmo** [comment]
Thanks,

What is confusing is why the transcoding job field has a number displayed above 0 in it if the video transcoding setting is set to 'never'. Surely it should display 0? 

If the displayed value in the jobs page is correct and there are videos in the transcoding queue; why are there videos in the queue if the transcoding setting is set to 'never'?

**Comment by bo0tzz** [comment]
> why are there videos in the queue if the transcoding setting is set to 'never'?

Because the determination whether to transcode is only made when the job runs, not before queueing it.

**Comment by MrSimmo** [comment]
> > why are there videos in the queue if the transcoding setting is set to 'never'?
> 
> Because the determination whether to transcode is only made when the job runs, not before queueing it.

Thanks, that makes sense. So maybe the request is to add a text narrative to the jobs page transcoding table to show that the setting has been set to ‘never transcode’ and therefore disregard anything displayed in the table?
