### ISSUE TITLE
[Bug] Memories appear as a gray box on mobile app

### ISSUE THREAD

**Issue by SerAlbi** [immich-app/immich#8876]
### The bug

As the title says, some of the Memories in the mobile app appear as a gray box (it keeps expanding if scrolling horizontally)

![Screenshot_20240417_113344](https://github.com/immich-app/immich/assets/24434712/7102850f-6047-4625-94ce-bf6e424e0e4f)

I already tried clearing the app cache but to no avail

### The OS that Immich Server is running on

Windows 11

### Version of Immich Server

1.101

### Version of Immich Mobile App

1.101

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by bo0tzz** [comment]
Dupe: #6538
