### ISSUE TITLE
Round icons lack transparency and displayed in gray circles instead when watching photos on Samsung TV browser

### ISSUE THREAD

**Issue by dgtal1** [immich-app/immich#8881]
### The bug

The web app has some UI bugs that cause the UI not to be displayed correctly on Tizen Samsung TV web browser. 

When I use immich on my PC the round icons are displayed nicely with transparency, not affecting the photo content:
![image](https://github.com/immich-app/immich/assets/27864579/2acaa2ed-84e3-4181-8133-ca32c81eba13)

but when I open immich on my TV - the icons are not transparent, but displayed in gray circles:
![image](https://github.com/immich-app/immich/assets/27864579/42961c00-14d9-459a-a438-3c0a1be7636d)

### The OS that Immich Server is running on

immich demo, but the same happens on my WSL+Ubuntu instance

### Version of Immich Server

demo

### Version of Immich Mobile App

not using

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant - happens also on immich demo website
```

### Your .env content

```Shell
not relevant - happens also on immich demo website
```

### Reproduction steps

```bash
1.browse a photo using this link: https://demo.immich.app/photos
2. icons displayed in the top right corner are not transparent
3.
...
```

**Comment by mertalev** [comment]
Thanks for the report, but I unfortunately have to close this issue as well since we don’t currently support this browser.

**Comment by dgtal1** [comment]
a note for others seeking for a fix to this in the future. I fixed it by using the Theme settings (administration panel), which fills in the 'custom.css' file allowing CSS overrides in immich.
You may add the following css code there:
```
@supports not selector(input:where([type=button])) {
button,
input[type="button"],
input[type="reset"],
input[type="submit"] {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
}
}
```
