### ISSUE TITLE
[BUG] Backup progress notifications don't disappear when disabling it in the settings

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#890]
**Describe the bug**
When running a backup, and disabling the notification setting about the detailed upload progress, the notifications don't disappear.

**Task List**

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Start backup
2. Disable either the detailed backup progress notification or the backup progress notification, or both.
3. See the disabled notification not disappearing and continuing. 

**Expected behavior**
I expected the notifications to disappear when I disable the setting.

**System**
- Phone OS [iOS, Android]: `11`
- Server Version: `1.33.0`
- Mobile App Version: `1.33.0 build.52`

**Comment by alextran1502** [comment]
This setting is designed to be in effect starting the next backup sequence

**Comment by JVT038** [comment]
So they don't disappear during the backup?
Could you make it so that does happen? Or is that too much work?

**Comment by alextran1502** [comment]
> So they don't disappear during the backup?
> Could you make it so that does happen? Or is that too much work?

Correct, since it is happen in the background thread, it is simpler to check for the state changed upon the next initialization of the background backup worker

**Comment by JVT038** [comment]
Oh ok, then I'll just close this issue.
