### ISSUE TITLE
[BUG] Backup resets when enabling foreground backup

### ISSUE THREAD

**Issue by assid2** [immich-app/immich#893]
**Describe the bug**
Backup settings reset once you enable foreground backup.  No backup takes place even after 2 minutes with the application running, and the start backup button is disabled.

**To Reproduce**
1. Go to Backup settings, choose your albums to backup
2. Click on  Turn on Foreground Backup 
3. All settings get reset including the albums marked to backup AND the trigger to start the backup. No backup takes place even after a few minutes, or on application restart (swipe away the application and re-launch)

**Expected behavior**
Turn on Foreground backup gets enabled with the correct updates. Even if no backup takes place  immediately but should start the backup after a minute or so including next application launched.

**Screenshots**
https://photos.app.goo.gl/7xs4ZkDqsGjAtxJd7

**System**
- Phone OS [iOS, Android]: `Android`
- Server Version: `1.33.0`
- Mobile App Version: `1.32.1b51`

**Comment by alextran1502** [comment]
Is this still the issue for the recent release 1.39?
