### ISSUE TITLE
Deleted asset still shows fullscreen image on mobile

### ISSUE THREAD

**Issue by JordyEGNL** [immich-app/immich#8944]
### The bug

When you click on an image and then delete it from your phone and Immich the image is still shown in the image viewer and info can be seen. Screen recording attached.

When you close the image viewer the deleted asset is also no longer available (as expected)

Expected behavior is that the image is also removed from the current image viewer

### The OS that Immich Server is running on

Ubuntu Server 22.04 LTS

### Version of Immich Server

v1.102.0

### Version of Immich Mobile App

v1.102.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
1. Create an image and upload it to Immich via the Android app
2. Tap on the taken image from within Immich and delete it (the trashcan icon on the bottom right)
3. Immich will now show you the previous image uploaded
4. Swipe to the right to see your deleted image (not expected)
5. If you close the image viewer (press back button) the image is deleted as expected
```

### Additional information

https://github.com/immich-app/immich/assets/65036298/00c7b328-412a-4ca6-81f2-ac07b376774f

**Comment by schuhbacca** [comment]
I believe should be fixed by: https://github.com/immich-app/immich/pull/9151

**Comment by JordyEGNL** [comment]
This issue is still present in V1.105.1

**Comment by JordyEGNL** [comment]
@schuhbacca can this be re-opened?
