### ISSUE TITLE
Mobile app keeps logging me out 

### ISSUE THREAD

**Issue by simon-vajda** [immich-app/immich#8945]
### The bug

Since the last update (1.102.0) the app keeps logging me out every few hours.

Phone: Samsung Galaxy S22+ (Android 14)

### The OS that Immich Server is running on

Unraid (Docker)

### Version of Immich Server

v1.102.0

### Version of Immich Mobile App

v1.102.0

### Platform with the issue

- [x] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. When updated the mobile app it requested me to log in so i did (the server was already running v1.102.0)
2. After a few hours when I opened the app it wanted me to login again. This keeps happening.
```

### Relevant log output

```shell
Unable to get user information from the server.

Unable to login through offline or online methods - logging out completely
```

**Comment by JordyEGNL** [comment]
I also encountered this today. It only happened once though. Will update this message when it happens again

**Comment by smogger** [comment]
Same here

**Comment by simon-vajda** [comment]
Just noticed this in the server logs:
```
ERROR [TypeError: Cannot read properties of undefined (reading 'id')
    at UserService.getMe (/usr/src/app/dist/services/user.service.js:70:42)
    at UserController.getMyUserInfo (/usr/src/app/dist/controllers/user.controller.js:39:29)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)] TypeError: Cannot read properties of undefined (reading 'id')
```

**Comment by clayauld** [comment]
I'm seeing this issue too, and also running it in docker on UnRAID. I also noticed that the web client has logged me out when previously my computer would stay logged in via the web client without requiring me to authenticate again.

**Comment by alextran1502** [comment]
Just for a data point, are you guys all use background backup?

**Comment by simon-vajda** [comment]
Yes I do

**Comment by JordyEGNL** [comment]
> Just for a data point, are you guys all use background backup?

Yes I am

**Comment by smogger** [comment]
Yes, altho I always has to open up the app to start the process. (i do have background backup set, and no battery save / restriction on the app at all)

**Comment by alextran1502** [comment]
I just merged #8594 which is a proper fix for Android. I will push out a release soon. If that doesn't work then I will merge this #8954

**Comment by JordyEGNL** [comment]
![Screenshot_20240420-151229_Immich.png](https://github.com/immich-app/immich/assets/65036298/941c62df-4678-4844-85fa-c0d2c38b3265)

This is the error I get when logged out randomly

**Comment by alextran1502** [comment]
Okay, I pushed out the new version and submitted it to the app store. Hopefully, it will be available soon since it is the weekend.

Please let me know if it keeps happening on `v1.102.1`; otherwise, I will use another fix mentioned above.

Thank you all

**Comment by JordyEGNL** [comment]
> Okay, I pushed out the new release and submitted it to the app store. Hopefully, it will be available soon since it is the weekend.
> 
> Please let me know if it keeps happening on `v1.102.1`; otherwise, I will use another fix mentioned above.
> 
> Thank you all

Thank you for the quick fix! It seems to be working fine, but it hasn't logged me out yet :)

**Comment by JordyEGNL** [comment]
Unfortunately I got logged out again...

On the 1.102.1 update
![Screenshot_20240420-174124_Immich.png](https://github.com/immich-app/immich/assets/65036298/8caab977-6416-4ccc-b843-555fbc4309c3)

**Comment by alextran1502** [comment]
Okay, another hotfix incoming

**Comment by simon-vajda** [comment]
It hasn't done it for me since the update, that being said it needed some time to happen before the fix too.

**Comment by alextran1502** [comment]
New release is submitted `v1.102.2` let me know if it ultimately solves this issue

**Comment by alextran1502** [comment]
`v1.102.2` is out on the PlayStore; please let me know if it fixes this for you guys.

**Comment by alextran1502** [comment]
@JordyEGNL it was released like 10-15 minutes ago. You can try with `/api`

**Comment by JordyEGNL** [comment]
> @JordyEGNL it was released like 10-15 minutes ago. You can try with `/api`

I'm using apk from GitHub directly :)

**Comment by JordyEGNL** [comment]
> @JordyEGNL I see, perfect. Now try with `/api` to see if it help

That's what I'm doing since the first time it logged me out (1.102.0), will keep you updated when it happens again

**Comment by simon-vajda** [comment]
I also updated my server and the app to 1.102.2 just now. Will get back to you after some time has passed and managed to test it.

**Comment by simon-vajda** [comment]
> I also updated my server and the app to 1.102.2 just now. Will get back to you after some time has passed and managed to test it.

I've got logged out on my phone using 1.102.2

**Comment by JordyEGNL** [comment]
> > I also updated my server and the app to 1.102.2 just now. Will get back to you after some time has passed and managed to test it.
> 
> I've got logged out on my phone using 1.102.2

Same for me twice

**Comment by alextran1502** [comment]
Ok, looks like a bigger problem. I will have to do a throughly check to spot the issue. Do can you guys export your logs and post it here?

**Comment by simon-vajda** [comment]
`/api/user/me` gives a 500 error simetimes with "Failed to get my user info".

And as I wrote in an earlier comment:
```
ERROR [TypeError: Cannot read properties of undefined (reading 'id')
    at UserService.getMe (/usr/src/app/dist/services/user.service.js:70:42)
    at UserController.getMyUserInfo (/usr/src/app/dist/controllers/user.controller.js:39:29)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)] TypeError: Cannot read properties of undefined (reading 'id')
```

The `id` is null but am not sure why.

**Comment by JordyEGNL** [comment]
> Ok, looks like a bigger problem. I will have to do a throughly check to spot the issue. Do can you guys export your logs and post it here? 

https://hastebin.nl/yumJgIa

**Comment by alextran1502** [comment]
This looks like a bug from the server, the web also got logged out after a while. We are looking into this

**Comment by simon-vajda** [comment]
> Ok, looks like a bigger problem. I will have to do a throughly check to spot the issue. Do can you guys export your logs and post it here?

[immich_server.log](https://github.com/immich-app/immich/files/15049523/immich_server.log)

**Comment by simon-vajda** [comment]
Thank you guys for the weekend work
