### ISSUE TITLE
"Search people" not working with non-english queries

### ISSUE THREAD

**Issue by krin-san** [immich-app/immich#8951]
### The bug

When filtering a list of "People" on `https://BASE_URL/people` web page, only special character queries or queries with English characters show results. Queries in a different language or with language-specific characters return no results.

### The OS that Immich Server is running on

TrueNAS SCALE

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

irrelevant

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
TrueCharts Kubernetes template in https://github.com/truecharts/charts/tree/master/charts/stable/immich
```

### Your .env content

```Shell
🤷‍♂️
```

### Reproduction steps

```bash
1. Name some person "Alex Влад Bülow" (english, cyrillic, german)
2. Search for english letter "A" – found a match
3. Search for cyrillic letter "В" – no matches
4. Search for german umlaut "ü" - no matches
```

### Additional information

Same steps attempted on the "Merge people" screen work just fine.

**Comment by martabal** [comment]
I think the issue is not related to non-English characters. The search function works the same way as the ***App-Which-Must-Not-Be-Named***, by matching the beginning of each word that makes up the name.

**Comment by krin-san** [comment]
> I think the issue is not related to non-English characters. The search for people works the same way as the _**App-Which-Must-Not-Be-Named**_, by matching the beginning of each word that makes up the name.

In this case searching for the first letter of a name should match it. It is only partially correct: it matches lowercase letters in beginning of words, but not uppercase letters.  
Anyway, this behavior is quite confusing. I would expect it to work the same way as on "Merge people" screen.
