### ISSUE TITLE
Poor HEIC WEB quality

### ISSUE THREAD

**Issue by maxwase** [immich-app/immich#8972]
### The bug

For some reason image quality for the same photo differs significantly depending on its format. The issue can be seen on mobile with `Prefer remote images` option selected.

### The OS that Immich Server is running on

6.6.19-1-MANJARO

### Version of Immich Server

1.102.2

### Version of Immich Mobile App

1.101.0 build.131

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
https://github.com/immich-app/immich/blob/e72e41a7aa5374ce763b7b779aed65f2ce761e01/docker/docker-compose.yml
```

### Your .env content

```Shell
https://github.com/immich-app/immich/blob/e72e41a7aa5374ce763b7b779aed65f2ce761e01/docker/example.env
```

### Reproduction steps

```bash
1. Take a photo in HEIC
2. Convert it using `heif-convert photo.HEIC photo.JPG`
3. Upload both photos to Immich
4. See poor HEIC quality compared to JPEG
```

### Additional information

Web screenshots:
![image](https://github.com/immich-app/immich/assets/23321756/4965d00b-3184-4e0a-8443-ad6c8c6cd406)
![image](https://github.com/immich-app/immich/assets/23321756/192b2ae8-8477-41f8-9949-9b28db2dfe44)

Option `Display original photos` does not affect

`admin/system-settings?isOpen=image` `QUALITY=100` setting makes the situation better, however it's still much worse then the converted JPG
![image](https://github.com/immich-app/immich/assets/23321756/253c2ebd-8299-45b8-ab29-0d584b08e3b3)

**Comment by mertalev** [comment]
Could you share an example image?

**Comment by mertalev** [comment]
Also related: #8016.

**Comment by maxwase** [comment]
I would love to, but github does not allow such large files to be attached 😅. I suddenly remembered that I have a dropbox, decided to use it [link to the source files](https://www.dropbox.com/scl/fo/catier7mo217sl4i5ezj1/AMjxl6mjccGAwT1_aFVJavQ?rlkey=ceqv0msjys0z20we3cvp58m14&st=ky5yutkw&dl=0)
I made a different image to compare: HEIC original, JPG original (adjusted camera settings) and JPG converted from the HEIC original

![image](https://github.com/immich-app/immich/assets/23321756/99fa3300-361c-4dac-b6d1-ac97a21661ee)
![image](https://github.com/immich-app/immich/assets/23321756/44ff4a27-8777-4828-ae66-d2e62ea320cc)
![image](https://github.com/immich-app/immich/assets/23321756/7c0b4e82-393c-4d86-a863-76540d1664cc)

**Comment by yydcool** [comment]
I also have the same issue.
*.HEIC original image won't load on web client (Chrome v124), the preview image is displayed instead.
I already turned on "Display original photos" knob on web.
Immich Server 1.102.3 (docker)

**Comment by maxwase** [comment]
Tested in Firefox:
![image](https://github.com/immich-app/immich/assets/23321756/f9019f98-de89-48a3-8e15-fce375b07a70)
![image](https://github.com/immich-app/immich/assets/23321756/59157788-c4d7-47cc-ba85-5d4f8b22e47f)
![image](https://github.com/immich-app/immich/assets/23321756/f998f962-000c-4b2c-b321-2e61b708bef4)

**Comment by mertalev** [comment]
I tested and this isn't actually a bug. It's just that HEIC isn't a web-compatible format so we never load the original, whereas we do load the original on zoom for JPG.

**Comment by jaisinghdhaliwal** [comment]
Could it be possible to add HEIC support for Safari? Safari 17+ supports HEIC.

**Comment by mertalev** [comment]
> Could it be possible to add HEIC support for Safari? Safari 17+ supports HEIC.

Sure, I made a PR for it.

**Comment by mailinglists35** [comment]
> > Could it be possible to add HEIC support for Safari? Safari 17+ supports HEIC.
> 
> Sure, I made a PR for it.

is that PR integrated by now? if not, where can it be tested? I'm using immich in Safari for mac and all my images are HEIC. Hate to zoom in and see the reduced quality instead of original, despite the setting to display original.

**Comment by mertalev** [comment]
There was a bug with displaying the preview instead of the HEIC original, but it should have been fixed in 1.132.0. Can you try clearing the browser cache?

**Comment by jaisinghdhaliwal** [comment]
I was testing this and on 1.132.2 and images on safari look more blurry/pixelated compared to chrome/brave. I can tell and have checked and both are viewing the original image however Safari images somehow look lower resolution. Turning off display original image makes it look even more blurry and compressed. This is for AVIF. 

HEIC also looks blurrier and downloading the original looks sharper and more detailed and I know Immich is trying to load the original as it is nowhere near as compressed as the preview image however it feels like it is loading it in some sort of low resolution container. 

On chrome I am seeing thin black lines in some sort of 3x6 grid though which I don’t see in Safari which might have something to do with it. This is for an AVIF image in chrome.

**Comment by jaisinghdhaliwal** [comment]
I think the black lines might be a bug with the way AVIF HDR images are displayed on Chromium based browsers as it does not happen on Firefox or Safari. Safari appears blurrier than original and Firefox is the only browser that seems to display the image correctly. I think this may be an unrelated bug though. 

![Image](https://github.com/user-attachments/assets/249a94c1-c8e8-4bf8-9947-9ebd3cea773f)
