### ISSUE TITLE
Panoramas/photospheres in shared link display incorrectly when download is disabled

### ISSUE THREAD

**Issue by jenda69** [immich-app/immich#9005]
### The bug

When you share an album using a link and disable download for it ("Allow public user to download" checkbox), photos load normally, but photospheres get displayed in really low thumbnail resolution. And if it's not full 360° sphere, it's also incorrectly projected (probably because the thumbnail is missing metadata).

![image](https://github.com/immich-app/immich/assets/932875/1a1fb429-8167-42b8-99d4-b2b47b3d0651)

I checked dev tools in the browser and it seems that it loads and displays just 250px thumbnail into the viewer, not even the large 1440px preview. The difference is that it loads photospheres from URL with "isWeb=false" parameter whereas normal pictures have "&isWeb=true".

### The OS that Immich Server is running on

Raspberry OS Bookworm

### Version of Immich Server

1.102.3

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Create album with a photosphere
2. Share link and copy it
3. Log out or use incognito mode
4. Browse album using link
5. Open a photosphere
```

**Comment by jrasm91** [comment]
Just tested and this is fixed. I think it might have actually been fixed with #12123, which will be in the next release.
