### ISSUE TITLE
Some HEIC photos have wrong orientation in web only

### ISSUE THREAD

**Issue by honulii** [immich-app/immich#9041]
### The bug

Some photos I've taken that are in HEIC format, that I've never rotated before, look correct on the Apple Photos app and in the Immich iPhone app, but then they are rotated left on Immich on web. 

The only difference about these photos is that I took them with a camera app called ProShot instead of the built in camera app. But they appear normal everywhere except Immich web so I don't think it's ProShot that's the problem. I can take photos in JPEG and RAW with ProShot as well, and they look fine in Immich mobile and web, no orientation problem. 

### The OS that Immich Server is running on

Synology DSM

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

v1.102.2 build 151

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/a
```

### Your .env content

```Shell
N/a
```

### Reproduction steps

```bash
1. Take an HEIC photo in portrait orientation
2. Backup to Immich
3. View on web, it has rotated left
```

### Additional information

Not sure if this is the same issue as this: https://github.com/immich-app/immich/issues/8355

I do also experience that problem, but the difference is that 8355 happens on photos I've rotated in the Apple Photos app, while this issue I'm reporting happens on photos I've never rotated at all. 

Same photo in immich mobile app vs web

correct orientation on mobile app
![IMG_5742](https://github.com/immich-app/immich/assets/5308687/59a9dfd0-8fdf-4043-9bde-a9b69e1d73ee)

rotated left on web
![IMG_5743](https://github.com/immich-app/immich/assets/5308687/9e04802a-2da7-41d8-8d77-d4c14fe2ae38)

**Comment by alextran1502** [comment]
Duplicate #8355
