### ISSUE TITLE
Change location dialog doesn't show result for latest value in search input

### ISSUE THREAD

**Issue by nghduc97** [immich-app/immich#9061]
### The bug

The change location dialog seems to show result for the previous value in the search input instead of the latest one. I recorded the demo on the demo server https://demo.immich.app/

Demo:

https://github.com/immich-app/immich/assets/8538104/cc41e7b0-a1ea-4718-a5cb-c130aa021d9d

### The OS that Immich Server is running on

https://demo.immich.app/

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

v1.102.3

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Irrelevant
```

### Your .env content

```Shell
Irrelevant
```

### Reproduction steps

```bash
1. Select a photo/video
2. Select "Change Location" in the drop down menu
3. Type `Hanoi` in the search input and wait for result -> this shows "Hong Kong" as result
4. Type a space to the search input to have `Hanoi ` -> shows correct result
...
```

**Comment by alextran1502** [comment]
Fixed in #9074
