### ISSUE TITLE
Immich android reports error in logs

### ISSUE THREAD

**Issue by zaggash** [immich-app/immich#9065]
### The bug

When I look at the journal on the android app, I see the following log.

`PlatformDispatcher - Catch all`

`type '_Map<String, dynamic>' is not a subtype of type 'String' in type cast`

```
#0      _CastListBase.[] (dart:_internal/cast.dart:99)
#1      ListBase.toList (dart:collection/list.dart:225)
#2      AuditDeletesResponseDto.fromJson (package:openapi/model/audit_deletes_response_dto.dart:54)
#3      ApiClient.fromJson (package:openapi/api_client.dart:252)
#4      ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#5      AuditApi.getAuditDeletes (package:openapi/api/audit_api.dart:74)
<asynchronous suspension>
#6      AssetService._getRemoteAssetChanges (package:immich_mobile/shared/services/asset.service.dart:55)
<asynchronous suspension>
#7      SyncService._syncRemoteAssetChanges (package:immich_mobile/shared/services/sync.service.dart:161)
<asynchronous suspension>
#8      SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/shared/services/sync.service.dart:53)
<asynchronous suspension>
#9      AssetService.refreshRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:43)
<asynchronous suspension>
#10     AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:52)
<asynchronous suspension>
#11     HomePage.build.refreshAssets (package:immich_mobile/modules/home/views/home_page.dart:87)
<asynchronous suspension>
#12     MultiselectGrid.build.wrapLongRunningFun.<anonymous closure> (package:immich_mobile/shared/ui/asset_grid/multiselect_grid.dart:415)
<asynchronous suspension>
#13     RefreshIndicatorState._show.<anonymous closure>.<anonymous closure> (package:flutter/src/material/refresh_indicator.dart:508)
<asynchronous suspension>
```

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

V1.102.3

### Version of Immich Mobile App

V1.102.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
Whenever I open the app and go on the journal, I see multiple occurence of it
```

**Comment by mmomjian** [comment]
I have noticed this on iOS, app version beta 1.102.4. I don't remember seeing it on 1.102.0.

**Comment by philippfeldner** [comment]
I can confirm the same behaviour on my setup (Ubuntu 22.04 - docker + Android device). For me my timeline does not load the most recent images uploaded from the web version.

**Comment by clayauld** [comment]
I'm seeing this as well in my setup.

UnRAID Server running using docker compose setup and paired with Android with backup service enabled.

**Comment by zaggash** [comment]
Now I have a slightly different error.

`Key 'currentUser' not found in Store`

**Comment by mPyKen** [comment]
same error in the logs. in my case photos get automatically uploaded from the phone but are still marked as 'only available locally'

**Comment by zaggash** [comment]
> same error in the logs. in my case photos get automatically uploaded from the phone but are still marked as 'only available locally'

Try to logout & login then wait a few minutes to fix this one

**Comment by mPyKen** [comment]
> > same error in the logs. in my case photos get automatically uploaded from the phone but are still marked as 'only available locally'
> 
> Try to logout & login then wait a few minutes to fix this one

that worked, thanks! I thought I tried that one already... The errors in the logs are also gone

**Comment by raimue** [comment]
I can confirm that logging out and logging back in with the same account did indeed fix the problem for me on Android. Thanks for the advice!

**Comment by raimue** [comment]
Sorry that my answer was not detailed enough. I saw the `PlatformDispatcher - Catch all` message as reported above in the log. I also had the problem that photos were not being marked with the "cloud checkmark" symbol, although they were already uploaded and visible on the web.

After logging out and back in again, photos are now correctly marked with the "cloud checkmark" symbol (also works for new photos). I also no longer see the error message `PlatformDispatcher - Catch all` in the log now.

**Comment by hydrandt** [comment]
I had the same error in the android app log, and the same behavior (assets not marked as uploaded, even though they have already been uploaded).

I was worried to log out and in again, as last time when I reinstalled the app, the whole library was reuploaded, as the duplicates detection only happens server-side. However, logging out and in again apparently keeps both the synced folders settings and the duplicates database - uff:)

Everything is fine now.

Android app: 1.102.3 build 2134

Server: 1.102.3

**Comment by philippfeldner** [comment]
All works fine again for me aswell. Thanks a lot for the solution. Great app!
