### ISSUE TITLE
Places missing on mobile app

### ISSUE THREAD

**Issue by honulii** [immich-app/immich#9073]
### The bug

All places are missing on the explore page on the mobile app. The map is there, and search by location shows locations exist that should appear in places. On web, the places are there. 

### The OS that Immich Server is running on

Synology DSM

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

v1.102.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/a
```

### Your .env content

```Shell
N/a
```

### Reproduction steps

```bash
1. Open Immich app
2. Click explore
3. No places, only map
```

### Relevant log output

```shell
The only errors in the mobile logs are flutter errors
```

### Additional information

Screenshot
![IMG_6027](https://github.com/immich-app/immich/assets/5308687/adb4b574-9511-4f99-97a7-00dffc14eba9)

**Comment by JordyEGNL** [comment]
Can confirm this on v1.102.3 Android, no places shown in app but all places are shown in the web version

**Comment by Liujun3712** [comment]
Also can confirm this on v1.102.3 iOS.
