### ISSUE TITLE
Mobile App - People View truncates after 1000 Pictures

### ISSUE THREAD

**Issue by TiloHeidasch** [immich-app/immich#9095]
### The bug

When having more than 1000 Pictures for a person, the Mobile App only ever shows the latest 1000 pictures.

Mobile:
![Screenshot_20240426-135645](https://github.com/immich-app/immich/assets/56626655/a06518cd-b441-414a-b0fb-1e85469bc555)

Same Person on Web:
![Screenshot 2024-04-26 at 14 04 00](https://github.com/immich-app/immich/assets/56626655/4f51c5a7-85aa-4a52-a6a7-766d6998170c)

This Issues is applicable to both the Android and the iOS App.

Initial Search within the Codebase pointed me towards
 https://github.com/immich-app/immich/blob/53d571d29e55f9a1ac71ee45f40ee0c8197b9949/mobile/lib/modules/search/services/search.service.dart#L74 
and
https://github.com/immich-app/immich/blob/53d571d29e55f9a1ac71ee45f40ee0c8197b9949/server/src/dtos/search.dto.ts#L121

Both allow for a maximum of 1000 entries. However I cannot understand why it would differ from Mobile to web.

### The OS that Immich Server is running on

Unraid / Docker

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

v1.102.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
Have a Person with at least 1001 Pictures
Select all Images for that Person on Web: More than 1000
Select all Images for that Person on Mobile (iOS / Android): exactly 1000
```

### Relevant log output

```shell
Server has no suspicious log entries
```

**Comment by alextran1502** [comment]
dup #8483

**Comment by TiloHeidasch** [comment]
now tracked in #5722
