### ISSUE TITLE
iOS upload freezes on upload errors, silently fails, never resumes

### ISSUE THREAD

**Issue by Thinkscape** [immich-app/immich#9130]
### The bug

Followup from https://github.com/immich-app/immich/issues/9108

Whenever an upload fails mid-way, the whole process hangs. There is no auto-retry, no errors in log, it never completes and never tries again (unless manually cancelled and restarted). 

In the original report it was failing with HTTP error 520.

![image](https://github.com/immich-app/immich/assets/270528/c2e2adbf-1a6e-43c5-974d-4040eea3a5e3)

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

1.102.3

### Version of Immich Mobile App

1.102.2 build.151

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

1. Open iOS app, auth to server
2. Choose a folder to upload, fg or bg uploading
3. Start upload
4. Disconnect wifi, or restart immich server.

### Expected

The upload of a file fails, it then start retrying with exponential backoff.

### Actual

The upload process hangs indefinitely.

### Relevant log output

```shell
nothing in iOS log
```

**Comment by m3yang** [comment]
My iOS app is experiencing the same issue. One image fails to sync due to an unsupported format. There is no way to ignore this particular image, and as a result, the subsequent images cannot be synced

**Comment by bo0tzz** [comment]
#2567
