### ISSUE TITLE
Cannot download images when browsing on Webview

### ISSUE THREAD

**Issue by nghduc97** [immich-app/immich#9133]
### The bug

Typically, when open a link from messaging apps, link is opened on webview (Android Webview in my case) instead of the browser. If I try to download in there, even after the download progress finish, there is no save file to storage prompt like on the browser.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

v1.102.3

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
irrelevant
```

### Your .env content

```Shell
irrelevant
```

### Reproduction steps

```bash
1. share an album
2. paste share link on some messaging app (Messenger, Telegram, etc)
3. click the link to open
4. try download an image to local device
...
```

**Comment by mmomjian** [comment]
Are you able to test downloading an image from a different website in Android Webview and see if it is allowed? Typically these browsers are more heavily sandboxed. Example: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_a_download

**Comment by nghduc97** [comment]
Yes, I have tried downloading other files. They work fine.

**Comment by nghduc97** [comment]
My bad, I got it wrong, other messaging apps like Telegram work fine. It is the problem of Zalo (a popular messaging app in my country) trying capture the download and save it in specific location that cause issues. I'll close this.

**Comment by Asis2019** [comment]
I've ran into this same issue, when sharing albums with my family on Telegram. I and everyone else cannot download, but works on an actual browser.

I can download the image from the test link above in Webview without issue.
