### ISSUE TITLE
Photos backed up on the background are displayed as displayed as not uploaded 

### ISSUE THREAD

**Issue by mio-19** [immich-app/immich#9136]
### The bug

My recent photos and videos have been processed by background backup. But they appear to be local only on the app even after refreshing.
![Screenshot_20240428_210205](https://github.com/immich-app/immich/assets/57285379/87d0aac3-7efd-4409-87d0-1ef9a65b6a72)
![Screenshot_20240428_210307](https://github.com/immich-app/immich/assets/57285379/10f134cd-af17-40f9-9b94-359bdd819549)
These two screenshots are processed by foreground backup and they also have incorrect state.
![Screenshot_20240428_210354](https://github.com/immich-app/immich/assets/57285379/d2d20abb-cb2b-4ddc-a24e-8ff95d25c258)
![Screenshot_20240428_210404](https://github.com/immich-app/immich/assets/57285379/0271df09-97fe-4339-8cf6-0064d8604d1b)

Log
[Immich_log_2024-04-28T210814.712809.log](https://github.com/immich-app/immich/files/15142232/Immich_log_2024-04-28T210814.712809.log)

### The OS that Immich Server is running on

Arch

### Version of Immich Server

1.102.3

### Version of Immich Mobile App

1.102.2 Android

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
https://github.com/immich-app/immich/releases/download/v1.102.3/docker-compose.yml
```

### Your .env content

```Shell
https://github.com/immich-app/immich/releases/download/v1.102.3/example.env
```

### Reproduction steps

```bash
1. Enable foreground and background backup
2. Take photos 
3. See the error
...
```

**Comment by thomasss02** [comment]
This happens to me too
To see the status of the backup I had to logout and re-login

**Comment by johnvanham** [comment]
Same problem for me with same versions. Logging out and back in as suggested by @thomasss02 fixed it for me as well.

**Comment by thomasss02** [comment]
In addition, when you try to add an asset (with the wrong backup status) to an album it says the asset hasn't been backed up yet.

**Comment by Tyree** [comment]
Same here...
For the past couple weeks the Android app shows none of the latest photos have been uploaded (cloud icon with a line through it). But if I look on the web, the photos have been uploaded. In the backup setting on the app, the Total and Backup numbers have been in-sync for months, but now Total is 7374 and Backup is 7428. I stay on top of the updates as they come out. Just updated to version 1.102.3.
Logging out and back in fixed it, but as soon as I took more photos, it did it again.

Also the photos show on the wrong days. Photos from 4/27 are listed under 4/25 and photos from 4/28 are listed under 4/27. (Only on Android app - on the web it's correct) - I know this is another documented issue.

**Comment by alextran1502** [comment]
Will be fixed in #9149

**Comment by mio-19** [comment]
> Will be fixed in #9149

I am still having this issue on 1.103.1

**Comment by thomasss02** [comment]
> > Will be fixed in #9149
> 
> I am still having this issue on 1.103.1

Also for me with version v1.103.1

**Comment by Tyree** [comment]
> > Will be fixed in #9149
> 
> I am still having this issue on 1.103.1

Same here. Definitely not fixed.

**Comment by Thoroslives** [comment]
Yes i am as well. Same issue latest release. Not fixed

**Comment by Tyree** [comment]
1.105 seems to have fixed it. All the cloud icon overlays have checks in them. Even when I take a new photo.
Thanks! @alextran1502  et al! :-)

**Comment by dennisfrijlink** [comment]
Still facing the same issue running version 1.105. Doing something wrong?
