### ISSUE TITLE
Videos cannot replay until going to a different photo

### ISSUE THREAD

**Issue by RobustMarker** [immich-app/immich#9137]
Attempting to replay a video after it has been played once requires you to swipe to a different photo/video and go back to be able to watch the video again. Im not sure if this expected behaviour, im used to other apps such as apple photos allows you to replay the same video multiple times in a row.

https://github.com/immich-app/immich/assets/74292007/a50ad148-8a11-4e8f-8e7e-9bc9eef4c034

### The OS that Immich Server is running on

Unraid 6.12.10

### Version of Immich Server

V 1.102.3

### Version of Immich Mobile App

V 1.102.2 Build 151

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Reproduction steps

```bash
1. Upload video via mobile app / web interface
2. View the video on mobile and wait for it to finish
3. Attempt to replay the video
```

### Additional information

No additional changes to immich, i have followed all the default recommendations and not modified anything.

### im new to github
sorry if this is formatted weirdly, i am new to reporting bugs and stuff.

**Comment by bo0tzz** [comment]
Confirmed

**Comment by haldi4803** [comment]
Same issue with Play/Pause button. Presses the left button instead.


https://github.com/immich-app/immich/assets/17104473/3351640f-d27c-4b10-af9f-785a7963c3e0

It's not only an issue in 9:16 Mobile Layout but also Desktop if you use F11 to Fullscreen the viewer on 16:9

**Comment by AlvaroMartinezB** [comment]
Can confirm the issue on Android too. Replay button is shown but unresponsive
