### ISSUE TITLE
[Feature]: Dynamic Photo Grid

### ISSUE THREAD

**Issue by imran0** [immich-app/immich#915]
### Feature detail

Similar to the view inside Google Photo's Library > Album screen, it would be great if we could have images displayed in a dynamic photo grid (as an option) instead of a fixed grid.

I've included an image below to display what I mean
[Imgur](https://imgur.com/PTHL42q)
### Platform

Mobile App

**Comment by alextran1502** [comment]
It is nice to have but I am not planning of doing this feature. Thank you for opening the issue.

**Comment by spupuz** [comment]
Why not leave this for future plan? When all major feature will be already implemented
