### ISSUE TITLE
Backup n restore documentation for windows needs small updates

### ISSUE THREAD

**Issue by amgschnappi** [immich-app/immich#9222]
### The bug

sleep & gc

### The OS that Immich Server is running on

Windows 10 with wsl2

### Version of Immich Server

Latest

### Version of Immich Mobile App

Latest

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Default
```

### Your .env content

```Shell
Default
```

### Reproduction steps

```bash
1. go to https://immich.app/docs/administration/backup-and-restore/
2. go to "Windows system based backup"

Issue : Docu says "sleep 10" . But
C:\Users\Username\Pictures\Immich>sleep 10
'sleep' is not recognized as an internal or external command,
operable program or batch file.

Issue : Docu says "gc". But
gc "C:\path\to\backup\dump.sql"gc "C:\path\to\backup\dump.sql"
'gc' is not recognized as an internal or external command,
operable program or batch file.
```

### Additional information

Use timeout /t 9 instead of sleep 9
Use type dump.sql | docker exec instead of "gc dump.sql | docker exec"

**Comment by mmomjian** [comment]
I’m pretty sure the commands are for power shell. Are you using legacy cmd?

**Comment by mmomjian** [comment]
Got it. Please use power shell as that is what it is designed for. We can add a note to the page covering this.
