### ISSUE TITLE
Cannot Login App IOS v1.103.0

### ISSUE THREAD

**Issue by ulimanaio** [immich-app/immich#9245]
### The bug

Hello, I would like to use Immich on my iPad.
Server URL: "http://192.168.178.57:8080/api" -> "Server is not reachable"
I am able to access "http://192.168.178.57:8080" in Chrome on the iPad and was able to use the Android App on a different device.

### The OS that Immich Server is running on

IOS

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

v1.103.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1.
2.
3.
...
```

### Relevant log output

```shell
Empty
```

**Comment by alextran1502** [comment]
Can you check the app permission if you allow the app to access local network?

**Comment by ulimanaio** [comment]
> Can you check the app permission if you allow the app to access local network?

Thank you very much - working now. Did not know this setting existed.
Maybe something to get checked when trying to login and it fails?
