### ISSUE TITLE
Edited photos on iPhone are not synced automatically

### ISSUE THREAD

**Issue by mplonski** [immich-app/immich#9250]
### The bug

Whenever you edit a photo on iPhone, immich app should detect it and reupload it automatically. Currently it's not detected and one needs to delete a photo in immich, and reupload it using in-app backup.

### The OS that Immich Server is running on

official docker image run within UnRaid

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

v1.103.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I don't have one - it's deployed using UnRaid plugin
```

### Your .env content

```Shell
I don't have one - it's deployed using UnRaid plugin
```

### Reproduction steps

```bash
1. take a picture on iPhone
2. upload it to Immich using in-app backup
3. make sure it's uploaded to Immich server
4. edit the photo on iPhone (e.g. crop it)
5. trigger backup in Immich app
6. nothing happens, the photo should be updated
```

**Comment by sidamos** [comment]
Same here. And your workaround does not work for me. When I delete the original photo in Immich web, it vanishes also in the iOS app but I cannot trigger manual backup because the button is disabled.

**Comment by mplonski** [comment]
@sidamos actually, for me the button on the picture view also doesn't do anything, the backup tool in the app does the thing.

**Comment by alextran1502** [comment]
When you edit a photo, the Photos app saves a separate XMP file, not a new file; that is why you cannot upload the edited photo

**Comment by sidamos** [comment]
> @sidamos actually, for me the button on the picture view also doesn't do anything, the backup tool in the app does the thing.

Not for me. Once I delete the original in Immich, the edited one never shows up in Immich. My workaround is to duplicate the edited photo in the iOS gallery app.

**Comment by mplonski** [comment]
@alextran1502 so... is it treated as a separate file when edited? Or backup mechanism in the app doesn't support updating edited files yet? Because at least in my case it uploads the edited version only when I delete the image in the UI, or when the image was never uploaded, it doesn't update it at all when I edit already synced image in the Photos app.

**Comment by alextran1502** [comment]
@mplonski 


> Or backup mechanism in the app doesn't support updating edited files yet

The library we used I believe isn't making this distinction. And we haven't worked on supporting this yet

**Comment by mplonski** [comment]
@alextran1502 ok, so it looks like it's something between a bug (since the backup function in the app works differently depending on if something was already uploaded) and a feature request (since re-uploading edited pictures is not implemented yet). What's next? I'm not a nodejs engineer, so I won't be able to help here.

**Comment by snatch84** [comment]
same problem on android..on the phone I see the edited photo while on the server the original version remains..

**Comment by justin13888** [comment]
I lost edited videos from this too before. I think the syncing on the mobile app should just be overhaulled with the caching which is unbelievably slow on mobile. I mentioned that in another discussion: <https://github.com/immich-app/immich/discussions/9706>

Are any devs looking into this? Otherwise, I may pick it up later when time allows.

**Comment by Alex9779** [comment]
This describes one of my major issues pretty much and is a deal breaker for me to use Immich.
When I found Immich it still had something like "photo backup" in its description but IMHO it never worked as a real backup solution for photos.
After the latest changes (in organization) this part has been removed and now it is "just" a photo management platform. I don't mean this in any negative way.
I like the overall concept, open source and everything.

What I expect to be the basic functionalty of every kind of automatic upload functionality is that it either reflects the state I have on my mobile or much better has an original and the edit.

But as this issue describes this is not the case.
If you take a photo and upload you have the original on Immich.
If you take a photo, edit and upload you have the edit on Immich.

And it is hard to clean this as this issue describes.

The problem with that is that using an automated upload you don't know when this actually runs and you don't know which version of an image is actually uploaded to Immich. Some photos you take and edit right away, some you edit minutes or hours later, some never...
That renders the auto upload unusable IMHO and doing everything manually again requires a lot of user interaction. But this is just for experienced users.

I'd love to use it for my whole family, to have an endpoint for all photos take on mobile automatically, but preserving the original photo at least, the latest edit would be a bonus.
But in the current state neither is guaranteed. Depending on when the auto upload actually runs, there might be some edit uploaded on Immich and maybe the one where someone accidentially cropped almost the whole picture.

**Comment by antonyoneill** [comment]
In case you find an alternative solution, I'd be very interested. My issue will be to find a reliable iOS sync to external library I think.

https://github.com/immich-app/immich/discussions/6439#discussioncomment-9912512

**Comment by Alex9779** [comment]
I really wonder why this issue is disregarded and is not number one priority.
Do just a few people have issues with that behavior? Does anybody want to have a reliable auto sync function to Immich?

I wouldnt argue this way if Immich would have always the latest edited version of a photo uploaded but that is also not the case. Basically it is totally random what you get and then it never gets updated.
Even worse you see the edited image in the Immich app on the iPhone but Immich has stored the original and shows that in the web or the other way round if you edited, uploaded and reset on your device.

Just to mention, it would be really a game changing feature if Immich would synch the original and the latest edit and have both versions in one "document", that would be some kind of "backup", that's what I am really looking for and something I didn't find in any app I tried yet...

**Comment by DMcWetty** [comment]
I just ran into this issue. I noticed that Immich  shows both edited and unedited images, however, only 1 is uploaded. I don’t really need the original, unless it’s RAW, but I can see the advantage of “hiding” or “stacking” both images. Is there a road map to support the additional XMP files?

**Comment by nZeus** [comment]
I would love to have support for XMP files, too! ❤️

**Comment by monoc44** [comment]
Lots of great features are being developed in Immich, for which we can only be grateful! My only complaint is that basic functionalities such as a proper sync are not mature yet, which prevents its adoption for many people.
Keeping original and edited versions would be a nice to have feature, but detection of edited pictures and sync them to the server is a must have imo.

**Comment by bo0tzz** [comment]
#6439

**Comment by pax0707** [comment]
Not just Immich "issues". 
Same thing as in Synology Photos. Their state is - working as intended.
