### ISSUE TITLE
App starts from beginning if scrolled after end

### ISSUE THREAD

**Issue by amgschnappi** [immich-app/immich#9266]
### The bug

App starts from beginning if scrolled after end

### The OS that Immich Server is running on

Win 10

### Version of Immich Server

latest

### Version of Immich Mobile App

latest

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Default
```

### Your .env content

```Shell
Default
```

### Reproduction steps

```bash
1.seach for videos only
2.scroll till the scroll " bar" goes till end
3.continue to scroll
...
Issue. The search scrolls up. But i want to see the earliest videos of my collection. Scrolling further at start defeats the purpose. I am forced to be very careful not to scroll further.
```

**Comment by thomasss02** [comment]
Confirmed. Not only for video filter but for all the filter in the search page.

**Comment by patienttruth** [comment]
I noticed the same thing a couple days ago and asked over on discord which brought me here. Not much info there, but here's the link to bring it full circle.

https://discord.com/channels/979116623879368755/1237198584534007919

**Comment by bo0tzz** [comment]
I think this is the same bug as #8635

**Comment by RaulGw4** [comment]
https://github.com/immich-app/immich/assets/116492323/4ad41008-7dcf-4cad-9288-ad9496478dc2



I was able to reproduce it. 
It happens as said on all filters.

For some reason it does not happen if there are only a few images. I got it to happen after about 100 images in a single search.

Here is a google drive that has all the images I used to replicate it: https://drive.google.com/drive/folders/1MYC4pwqSjLLoCcRpDPBr7790fWQLPwtW?usp=sharing

STEPS TO REPLICATE
1. Go into the "Search Tab"
2. Click on "Search your photos"
3. Select the "Date" filer
4. Select the date: Jul 6 - Jul 6 2024
5. Scroll to the bottom


Phone: Nothing Phone 2, running Android 14
Version of app: 1.107.1 build.146

If you can't replicate it send me a message on discord so we can get into a call: raul_gw4
