### ISSUE TITLE
Timeline slider dissapears behind bottom menu

### ISSUE THREAD

**Issue by RobustMarker** [immich-app/immich#9286]
### The bug

When using the timeline slider going back in time it goes behind the bottom menu making it impossible to access until you swipe up without using the slider. 

https://github.com/immich-app/immich/assets/74292007/c06320e0-29c1-48a0-8619-d95b239fc147

### The OS that Immich Server is running on

Unraid 6.12.10

### Version of Immich Server

V1.102.3

### Version of Immich Mobile App

V1.103.0 Build 155

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Reproduction steps

```bash
1. Go to to bottom of timeline
2. Try to use timeline slider to go forwards in time.
```

### Additional information

This is on an iphone 11 Pro, I do not have any more mobile devices to test so can others confirm, thanks.

**Comment by aviv926** [comment]
Can confirm that the bug also exists on Android.

**Comment by RobustMarker** [comment]
Closing this issue as solved by @ConnerWithAnE Thanks!

**Comment by interunivers** [comment]
Bug is saddly reappering in app version 1.114.0 on an iPhone 13.

**Comment by alextran1502** [comment]
@interunivers it was a regression, fixed, and will be available in the next release
