### ISSUE TITLE
[Feature]: Add already available photos directory

### ISSUE THREAD

**Issue by ashishjullia** [immich-app/immich#929]
### Feature detail

I want to look for a way to add an already available photos directory on my system.

I've ~10k photos on my backup storage which is currently mounted to my system and I just want to map that directory to Immich.

I'm not sure whether the feature is already there or not but I tried mapping that folder to `/usr/src/app/upload` and it is not working.

### Platform

Server

**Comment by spupuz** [comment]
You need to re-upload via cli scan existing path is not available at the moment. Use cli to re upload

**Comment by ashishjullia** [comment]
Re-upload as in re-upload my complete library of ~10k photos?

**Comment by alextran1502** [comment]
Hello, this application doesn't have the scanning capability of an existing directory at the moment. It was designed to be a backup tool for your mobile phones. You can however use the CLI to upload the existing directory to the Immich server. 

If you use your local network, uploading 10k photos or videos would probably take an hour or two

**Comment by ashishjullia** [comment]
Hi @alextran1502 thanks for responding.

I don't find this to be a good way to have a replica of my existing directory files and copy those (or upload in immich directory) is a good approach.

In that way I will still have my old directory and files under that + same files under the upload directory.

Although this tool is super super good at this stage I will highly suggest to add this capability, for me this might be the only reason to not to use this at the current moment.

I still appreciate your hard work and this product altogether.

**Comment by alextran1502** [comment]
Duplicated #7
