### ISSUE TITLE
Screen shaking when scrolling down memory

### ISSUE THREAD

**Issue by ayykamp** [immich-app/immich#9305]
### The bug

Video showing the Issue:
[Screencast from 2024-05-07 16-12-30.webm](https://github.com/immich-app/immich/assets/32194363/b09a3a30-b3e3-4559-b002-5c9014fe6305)
Browser is Firefox 125.0.2

### The OS that Immich Server is running on

TrueNas 

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Click on a memory
2. Click the downward facing arrow
3. Enjoy the screen shake
```

**Comment by schuhbacca** [comment]
I can reproduce. Seems to happen when there is not many photos below the memories area. Tested with many photos and works fine. Archived all except one and saw the screen shake.

**Comment by jrasm91** [comment]
I think this has been fixed. We've done a lot of memory lane rework recently. Let me know if it is still an issue.
