### ISSUE TITLE
immich web page jumps down when selecting a photo/video and pressing 3-dot menu

### ISSUE THREAD

**Issue by arieluchka** [immich-app/immich#9307]
### The bug

immich web page jumps down when selecting a photo/video and pressing 3-dot menu
[video showcase](https://www.youtube.com/watch?v=5nP-BflLV9o)

### The OS that Immich Server is running on

Proxmox (ubuntu 22.04 server vm)

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

Web browser

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. go to "photos" tab in the web browser
2. start selecting multiple photos
3. press on 3-dot menu on the right top corner
(will only happen occasionally)
...
```

**Comment by alextran1502** [comment]
Confirmed, I notice this occasionally too!

**Comment by dagstuan** [comment]
I have the same issue when using the plus-button as well. Only happening sometimes.

**Comment by jrasm91** [comment]
Looks like this has been fixed. At least I cannot produce it. We have done a bunch of changes around context menus/modals that rely on "out click", so it may have been fixed when that rework happened.
