### ISSUE TITLE
iOS app logs me out sometimes when Immich is down

### ISSUE THREAD

**Issue by freak12techno** [immich-app/immich#9330]
### The bug

I have a quite unstable server that is hosting Immich which sometimes shuts down or is inaccessible.
Some times when this happens, I am logged out of the app, and I have to specify the host of the app (the host is prefilled) and after that to enter my username and password again, which is somewhat annoying.

This happens quite often on my iOS app, I am not sure if this applies to Android as well.

Is it possible to just show the error instead and suggest the user to log out (by clicking the button or some other way, but so the user would log out manually)?

### The OS that Immich Server is running on

Unraid + docker-compose

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

v1.103.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
(The default one, should be irrelevant here.)
```

### Your .env content

```Shell
(The default one, should be irrelevant here.)
```

### Reproduction steps

```bash
1. Start Immich
2. Authorize against Immich in your iOS app
3. Shut down Immich
4. Wait for some time (not sure what is causing such a behaviour tbh; sometimes I didn't launch the app yet the auto-upload tried to upload files and obviously failed, maybe this can be related)
5. Start Immich
6. In the app, it'll suggest you to input your server/username/password instead of preserving a session
```

**Comment by bo0tzz** [comment]
Dupe: #2980
