### ISSUE TITLE
Symlinked photos in external library download as a zip of symlinks

### ISSUE THREAD

**Issue by rgilton** [immich-app/immich#9335]
### The bug

I have some photos that are presented to immich in an "external library".  That external library happens to be a git-annex repository, so all of the photos are actually symlinks to somewhere in its `.git` directory.  Immich displays these files with no problems.  However, if one tries to download a set of them, one ends up with a zip file full of symlinks and no actual images.

For example, here's what I get from unzipping a zip that immich generated that contained two images:

```
 ls -l
total 8
lrwxrwxrwx. 1 rob rob 207 May  8 20:17 IMG_6611.JPG -> ../../../.git/annex/objects/kp/74/SHA256E-s6007094--24cb5836a3634c8c663ea53846cf05d8c1471dbfbe6d61e346db0c944d002e42.JPG/SHA256E-s6007094--24cb5836a3634c8c663ea53846cf05d8c1471dbfbe6d61e346db0c944d002e42.JPG
lrwxrwxrwx. 1 rob rob 207 May  8 20:17 IMG_6613.JPG -> ../../../.git/annex/objects/vx/jw/SHA256E-s5979551--0895fe458d242ba5ea5fbefc3e7816c7621ed54e0bd8f06471f2431f30e64b5c.JPG/SHA256E-s5979551--0895fe458d242ba5ea5fbefc3e7816c7621ed54e0bd8f06471f2431f30e64b5c.JPG
```

As you can see, both of those files are symlinks, and not actually image files.

Downloading the images individually works fine.

### The OS that Immich Server is running on

nixos

### Version of Immich Server

1.103.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a: Not using docker-compose -- immich is running in podman.
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. Have an external library that has images that are symlinks to somewhere internally within the library.
2. Select two of those images in the immich web interface
3. Observe that the resulting zip file does not actually contain the images
...
```

**Comment by C-Otto** [comment]
Can confirm (I'm also using `git annex`)

**Comment by C-Otto** [comment]
`immich` uses archiver (archiverjs.com) internally, which does not seem to follow symlinks. A fix involving a manual symlink traversal might be easy to implement in the `addFile` callback function: https://github.com/immich-app/immich/blob/2dd551404360bd534ab5306b7a7a45769c947afe/server/src/repositories/storage.repository.ts#L54-L56

**Comment by C-Otto** [comment]
See https://github.com/archiverjs/node-archiver/issues/402
