### ISSUE TITLE
iOS App - Search Tab stutter with 120hz iPhones

### ISSUE THREAD

**Issue by ledahosn** [immich-app/immich#9339]
### The bug

When in the Search Tab, scrolling up and down is Frame-limited it is very noticable.
Already tried Demo Server aswell as my own, same issue

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.102.3

### Version of Immich Mobile App

1.103.0 build.155

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1.Open App
2. Go to Search Tab
3. Scroll up and down
```

**Comment by watn3y** [comment]
I can reproduce this on my iPhone 15 Pro. Not a huge issue since you can't do all that much scrolling in the Search tab but annoying nonetheless.

**Comment by alextran1502** [comment]
Solved in the new UI design
