### ISSUE TITLE
Android app more assets been uploaded than Total assets.

### ISSUE THREAD

**Issue by chengguangnan** [immich-app/immich#9365]
### The bug

In the Andorid app, it shows Total 5763 assets, but Backup 6000+ assets, and the "Uploading file info" progress box is still running. So why is more assets been uploaded?

### The OS that Immich Server is running on

MacOS

### Version of Immich Server

1.103.1

### Version of Immich Mobile App

1.103.1.build,137

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
/
```

### Your .env content

```Shell
/
```

### Reproduction steps

```bash
- Andorid app
- Click the "Uploading" icon on the top right navbar.
```

### Additional information

![3821715307859_ pic](https://github.com/immich-app/immich/assets/861069/38ab5a33-e96d-42e3-93ac-3f85b995b484)

**Comment by bo0tzz** [comment]
#7738
