### ISSUE TITLE
Video unmutes when scrubbing

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#9367]
### The bug

After muting a video in the player, using the scrub bar to move around in the video will cause it to unmute.

### Version of Immich Server

v1.103.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Reproduction steps

```bash
1. Open video in player
2. Press mute
3. Use scrub bar
```

**Comment by Tushar-Harsora** [comment]
Happens in Browser too with MacOs Chrome.

**Comment by bo0tzz** [comment]
Oops, just noticed that I'd accidentally checked the mobile box in the issue description - this is just a web bug afaik!
