### ISSUE TITLE
[Feature]: Notification when asset is added to shared album

### ISSUE THREAD

**Issue by matthinc** [immich-app/immich#938]
### Feature detail

It'd be nice if users could "subscribe" to shared albums so they get notifications whenever an asset is added to the album.

"User _xy_ uploaded _n_ new photos to album _abc_"

### Platform

Mobile App

**Comment by alextran1502** [comment]
We can make this happen with a combination of "Background task/Background fetch + Local Notification." The app would periodically ask the server if any new events were related to the shared albums available. Those events will be stored in either Redis Queue or the database. If there are events, the app will show a local notification.

**Comment by alextran1502** [comment]
Will emcompass in #627
