### ISSUE TITLE
Deleting an Album does not delete the photos from the DB

### ISSUE THREAD

**Issue by Matt-UKTX** [immich-app/immich#9395]
### The bug

When I delete and album in immich, it does not go to the recycle bin and the images are not removed from the DB.  I have to select each photo and delete it first, then delete the album to remove the images from the database.  Is this expected behavior?

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Select an album
2. Delete it
3. Photos are still in the DB
4. When I tried to re-upload the album, I was told they were duplicates.
...
```

**Comment by bo0tzz** [comment]
Yes, this is working as intended. On the web client you can use Ctrl+A to select all the assets in an album and then send them to the trash.

**Comment by Matt-UKTX** [comment]
Good to know.  Thanks for the help.
