### ISSUE TITLE
[Feature]: Add the ability to correct/train machine learning matches

### ISSUE THREAD

**Issue by esmondmissen** [immich-app/immich#942]
### Feature detail

Just a simple option to correct false positives in the search results.

If I teach "carrot" and it returns a beach umbrella, an option to say "Not a carrot" would be nice.

Could this also be used to train the model going forward?

### Platform

Server

**Comment by bo0tzz** [comment]
Editing tags will be supported in the future. Dynamic model training is unfortunately not as simple as adding some ui, it'd need some solid ML knowledge as well. And it wouldn't really be effective at the scale of just one immich instance, so we'd need to share training data around etc - it gets hairy pretty quick.
