### ISSUE TITLE
iOS: The app says to update but there is none

### ISSUE THREAD

**Issue by samip5** [immich-app/immich#9457]
### The bug

The app shouldn’t complain about app version on iOS if said update hasn’t been published to App Store. Like it is currently with the 1.104.0. 

### The OS that Immich Server is running on

Debian 12, but Kubernetes

### Version of Immich Server

V1.104.0

### Version of Immich Mobile App

v1.103.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open Immich when it’s out of date with server
2. See issue in profile menu.
```

### Additional information

![IMG_0233](https://github.com/immich-app/immich/assets/1703002/b0f50b07-ee97-4c72-b3a5-c3ffdd8e8f38)
![IMG_0232](https://github.com/immich-app/immich/assets/1703002/eca9f3e7-832d-4bd1-a890-744c8f810210)

**Comment by Meliox** [comment]
You have probably updated your server and that is telling the app that it is out of date. A version mismatch can break things.

**Comment by samip5** [comment]
> You have probably updated your server and that is telling the app that it is out of date. A version mismatch can break things.

No, it checks from Github but that doesn't mean it's available in the App Store which is confusing from UX perspective.

**Comment by gerwim** [comment]
The app is available on Android. It's probably awaiting Apple's review.

**Comment by samip5** [comment]
> The app is available on Android. It's probably awaiting Apple's review.

Thus a bug on iOS as it should complain about it only after it's in reality available on the platform.

**Comment by Prolonz** [comment]
It’s not waiting for App Store review. I got the update this morning. It’s probably due to a staggered rollout.

**Comment by danieldietzler** [comment]
I don't think that's something we can fix. I am not aware of any possibility to figure out programmatically when apple rolled out the update in your area.
