### ISSUE TITLE
External Library - Delete Library, also deletes all files on the storage 

### ISSUE THREAD

**Issue by monarc83** [immich-app/immich#9460]
### The bug

If you delete an external library, not only the assets in Immich will be deleted but also all assets from /import on your storage, even if the confirmation says otherwise.

"Are you sure you want to delete this library? This will delete all 90 contained assets from Immich and cannot be undone. Files will remain on disk."

if something is missing and the problem cannot be reproduced, please let me know what else is needed.

### The OS that Immich Server is running on

Unraid 6.10.12

### Version of Immich Server

v1.104.0

### Version of Immich Mobile App

1.103.1 build.137

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
1. Delete Library from Web app
2. Confirm deletion
```

**Comment by ThreeAurora** [comment]
In particular, there is a major update to the external library, which is already editable.

**Comment by monarc83** [comment]
Yes, that's exactly the problem. External libraries are now editable, we have all been waiting for that, but if you have to delete your library for some reason and it is :rw mounted, all photos are also deleted from the storage, not just removed from Immich. Even though Immich shows the following deletion confirmation.

 "Are you sure you want to delete this library? This will delete all 90 contained assets from Immich and cannot be undone. Files will remain on disk."

**Comment by guidovw** [comment]
Happened to me today, immich wouldn't read the data in the external library, so I decided to delete it, and it erased all my pictures (11,000). I'm hoping to recover them. This needs an urgent fix!

**Comment by alextran1502** [comment]
We are looking into this.
