### ISSUE TITLE
Photos are not updated in the Mobile version

### ISSUE THREAD

**Issue by mrxorao** [immich-app/immich#9471]
### The bug

I only use photos from the external library, I don't use photos sent by immich.

In the web version the photos appear but in the android app the new photos don't appear I have to reinstall the app for it to work but then it comes back to the same problem!
![Screenshot_2024-05-14-12-22-30-139_app alextran immich](https://github.com/immich-app/immich/assets/154644247/8fcda4a1-bb8f-4937-aec0-8c80d7aceb4c)

![Screenshot_2024-05-14-12-23-10-083_app alextran immich](https://github.com/immich-app/immich/assets/154644247/d0fc8028-efda-4c1c-9f2d-20cf81c78caa)

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

1.104.0

### Version of Immich Mobile App

1.104.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1.
2.
3.
...
```

### Relevant log output

```shell

Message: 
PlatformDispatcher - Catch all

Details:
type '_Map<String, dynamic>' is not a subtype of type 'String' in type cast

From:
ImmichErrorLogger

Stack Track:

#0      _CastListBase.[] (dart:_internal/cast.dart:99)
#1      ListBase.toList (dart:collection/list.dart:225)
#2      AuditDeletesResponseDto.fromJson (package:openapi/model/audit_deletes_response_dto.dart:54)
#3      ApiClient.fromJson (package:openapi/api_client.dart:264)
#4      ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#5      AuditApi.getAuditDeletes (package:openapi/api/audit_api.dart:74)
<asynchronous suspension>
#6      AssetService._getRemoteAssetChanges (package:immich_mobile/services/asset.service.dart:57)
<asynchronous suspension>
#7      SyncService._syncRemoteAssetChanges (package:immich_mobile/services/sync.service.dart:161)
<asynchronous suspension>
#8      SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/services/sync.service.dart:53)
<asynchronous suspension>
#9      AssetService.refreshRemoteAssets (package:immich_mobile/services/asset.service.dart:45)
<asynchronous suspension>
#10     AssetNotifier.getAllAsset (package:immich_mobile/providers/asset.provider.dart:52)
<asynchronous suspension>
```

**Comment by bo0tzz** [comment]
Please post the complete log output, not just the part you think is relevant.

**Comment by mrxorao** [comment]
> Please post the complete log output, not just the part you think is relevant.

Okay, I've updated!

**Comment by austinvaness** [comment]
I have the same issue

**Comment by alextran1502** [comment]
Hmm looks like the attempt to fix it didn't really do the job.

**Comment by dominik666692** [comment]
Having the same exact issues. Hoping for a fix. From me, signing out and in on the phone loads the new images, but then again doesn't load the newly taken ones, so I have to sign out and in again.
