### ISSUE TITLE
Cann't set language in Immich web

### ISSUE THREAD

**Issue by wx2020** [immich-app/immich#9474]
### The bug

Cann't set language in Immich web

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

v1.103.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by alextran1502** [comment]
There is no such feature yet
