### ISSUE TITLE
[BUG] Chinese file name becomes garbled

### ISSUE THREAD

**Issue by ngugcx** [immich-app/immich#951]
**Describe the bug**
I uploaded a photo named "微信图片_20220526164630.jpg" to immich server.
Chinese file name becomes garbled.

**To Reproduce**
1. Upload a photo with Chinese characters in the file name.
2. Go to the photo detail page
3. Will see the garbled file name

**Expected behavior**
Show Chinese characters in file name correctly.

**Screenshots**
![25ea8457af972aa671d9c8068a73e9d](https://user-images.githubusercontent.com/44153489/201028061-3661b837-5f73-4eec-84f0-bbb0ed5d9c2c.jpg)

**System**
- Phone OS [iOS, Android]: Android 11
- Server Version: v1.35.0
- Mobile App Version: v1.35.0

**Comment by jrasm91** [comment]
Fixed in #1147.
