### ISSUE TITLE
Storage reporting is still shows wrong size

### ISSUE THREAD

**Issue by picarica** [immich-app/immich#9514]
### The bug

my web ui installed within truenas shows 256kb of usage even when 600 pictures and several 100gb videos uploaded
i saw this issue #2462 and saw it was solved? but it doesnt seem like #2560 i thought this was a fix too, but sitll not
my behavior is same as in this 2 months old reddit thread https://www.reddit.com/r/immich/comments/1b4ai01/real_capacity_of_immich_with_truenas/

### The OS that Immich Server is running on

TrueNAS-SCALE-24.04.0

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not sure truenas default
```

### Your .env content

```Shell
not sure
```

### Reproduction steps

```bash
1. install truenas
2. install immich
3. issue exists
```

### Additional information

with truenas i am using default ixvolumes i wonder if host path would be used if it would fix the issue

**Comment by mertalev** [comment]
I think this might be a quirk of ZFS since everything is on a separate dataset. We only look at the library folder to get disk usage info, so in this case the used space is just the size of the library folder. I'm not sure what the best way to fix this would be.

**Comment by picarica** [comment]
idk this may sound amateurish but just getting size with **du** and report it to GUI? should work on zfs no ?

**Comment by mdafer** [comment]
One workaround, that worked for me (using geesefs to mount S3 buckets as local storage), is to set a limit on your account. Eg. instead of unlimited, use 100 TB for example. This way I can now see the used storage out of the limit.

Using du could deteriorate performance pretty quickly for us (who mount different kinds of storage, especially Object stores such as minio or s3), in my case, it could take hours to traverse the whole tree and get the total size.

I haven't checked how the size is being calculated when a limit is set, and I could be mistaken, but I'm assuming that it's calculated from the meta in Immich rather than from storage as I'm pretty sure it would be much slower to do it accurately from storage in my case.

**Comment by mertalev** [comment]
> I'm assuming that it's calculated from the meta in Immich rather than from storage

This is right. Usage is stored in the DB and updated when assets are added or deleted.

I suppose we could change to display the immich library size instead of the disk size. The latter is hard to get right since you can mount different drives for each folder, filesystems can handle usage differently, etc.

**Comment by danieldietzler** [comment]
This sounds like it has been clarified/become a feature request more than an issue.

**Comment by Elyviere** [comment]
So is there a feature request created for this? Because I'd definitely argue that installing Immich on TrueNAS Scale with the official app and default settings should warrant correctly showing the amount of used space. It not displaying correctly definitely sounds like a bug more so than a feature request.

**Comment by alextran1502** [comment]
@Elyviere the TrueNAS template is handled by the TrueNAS team, I think it will have to be handled from that end

**Comment by johansmolinski** [comment]
TrueNAS team claims it has to do with how Immich calculates the size. https://github.com/truenas/apps/issues/2249

**Comment by stavros-k** [comment]
No its not exactly that. I've said that it will probably get better after https://github.com/truenas/apps/issues/893.
But truenas/apps can't change how calculation is done.

**Comment by stavros-k** [comment]
Btw I just run this on the immich server container and it looks normal to me

```js
> const fs = require("fs");
undefined
> fs.statfs("/usr/src/app/upload/library", (err, stats) => {
...   if (err) {
...     console.error(err);
...     return;
...   }
...   console.log({
...     "available (GB)": (stats.bavail * stats.bsize / 1024 / 1024 / 1024).toFixed(2),
...     "free (GB)": (stats.bfree * stats.bsize / 1024 / 1024 / 1024).toFixed(2),
...     "total (GB)": (stats.blocks * stats.bsize / 1024 / 1024 / 1024).toFixed(2),
...   });
... });
undefined
> {
  'available (GB)': '421.07',
  'free (GB)': '421.07',
  'total (GB)': '421.07'
}
```

<img width="533" alt="Image" src="https://github.com/user-attachments/assets/3248ce5b-ac34-49f1-bf4a-fd826dde7502" />

(Based on code here https://github.com/immich-app/immich/blob/e7edbcdf0416a947860ab972520d5bbfa5d8e13a/server/src/repositories/storage.repository.ts#L166)

**Comment by Elyviere** [comment]
Appears to be working now, this is from my hosted immich web page today:

![Image](https://github.com/user-attachments/assets/ecb2aeec-61a5-4031-92c7-1bd7cb7a9888)

**Comment by johansmolinski** [comment]
I seem to still be triggering some edge case. I'll try to see whatever I can find out myself.

![Image](https://github.com/user-attachments/assets/9c604c36-b730-4c24-985f-744823a77edc)

**Comment by Elyviere** [comment]
I'm on TrueNAS 25.04 in case that helps, but seeing as you have the latest Immich version it appears you are too.

**Comment by johansmolinski** [comment]
I don't think so actually. Need to verify when I get home. I think I still am on 24.x. Thanks for the hint!

**Comment by mainman94** [comment]
I have the exact same issue. Fresh TrueNAS installation and fresh immich setup.
immich:
App Version: v1.132.3
Version: v1.7.44

TrueNAS: 25.04.0

**Comment by MrBacca** [comment]
> One workaround, that worked for me (using geesefs to mount S3 buckets as local storage), is to set a quota limit on your account. Eg. instead of unlimited, use 100 TB for example. This way I can now see the used storage out of the limit.
> 
> Using du could deteriorate performance pretty quickly for us (who mount different kinds of storage, especially Object stores such as minio or s3), in my case, it could take hours to traverse the whole tree and get the total size.
> 
> I haven't checked how the size is being calculated when a limit is set, and I could be mistaken, but I'm assuming that it's calculated from the meta in Immich rather than from storage as I'm pretty sure it would be much slower to do it accurately from storage in my case.

This works to fix the problem

**Comment by MichalCRP** [comment]
> > One workaround, that worked for me (using geesefs to mount S3 buckets as local storage), is to set a quota limit on your account. Eg. instead of unlimited, use 100 TB for example. This way I can now see the used storage out of the limit.
> > Using du could deteriorate performance pretty quickly for us (who mount different kinds of storage, especially Object stores such as minio or s3), in my case, it could take hours to traverse the whole tree and get the total size.
> > I haven't checked how the size is being calculated when a limit is set, and I could be mistaken, but I'm assuming that it's calculated from the meta in Immich rather than from storage as I'm pretty sure it would be much slower to do it accurately from storage in my case.
> 
> This works to fix the problem

Works for me too, thanks

**Comment by porjo** [comment]
>> set a quota limit on your account. Eg. instead of unlimited, use 100 TB

> Works for me too, thanks

Can sometime explain what is meant here? Are they talking about quota on the zfs dataset used by Immich?

**Comment by MrBacca** [comment]
In immich you edit the users space(storage) in the administration page.

**Comment by vkushwaha17** [comment]
Workaround works for me as well. 
login > click on profile > Administration > give specific storage and not unlimited
