### ISSUE TITLE
[Feature]: Public API (with docs)

### ISSUE THREAD

**Issue by Andrew-71** [immich-app/immich#957]
### Feature detail

Hey! I was recently looking into making website for personal image sharing links with Immich acting as host, however had a problem with API, lack thereof to be precise. _Technically_, there is obviously an API (Since mobile app connects to it), and there are a bunch of files related to it in the repository, but there is no clear way to connect and use it as a user, and no docs to know what you can do with it.

Therefore, I would like to ask developers to add some kind of public API docs, which would let users create their own apps around Immich. I remember a developer mentioning that they have auto-generated swagger docs somewhere, maybe something like this would be useful. :D

### Platform

Server

**Comment by bo0tzz** [comment]
Some generated api documentation is available on the server under `/api/doc/`, eg https://demo.immich.app/api/doc/.
