### ISSUE TITLE
[BUG] [WEB] Video previews in Gridview keep downloading, even if they are not visible anymore (reopen)

### ISSUE THREAD

**Issue by akoyaxd** [immich-app/immich#958]
**Describe the bug**
If I scroll through my assets and hover over an video, it starts to download and preview it, which is a great feature.

The Prolbem is, that it does not stop to download the video, even, if I scrolled away from that video, which makes previewing images very slow, since it blocks my bandwidth.

**To Reproduce**
1. I installed Immich through docker-compose
2. Placed an Nginx reverse proxy for ssl in front of it.
3. Upload assets from my phone
4. In Web: Hover over an video and scroll down. Keep an eye on networktraffic of my machine.

**Expected behavior**
The download of the video stops, as soon as I stop hovering with my mouse over an video (or at least as soon, as it is no longer visible in the browser through scrolling.

**Screenshots**

**System**
- Server Version: `<1.35>`
- Mobile App Version: `<1.35>`

**Additional context**
Browser is Firefox on MacOS 13

This is a reopened Ticket for  #875

**Comment by alextran1502** [comment]
This might be the Firefox problem only. I've tested on Chrome and Brave, and I cannot reproduce this issue. Hmm. Can you help check the network tab of Firefox?

**Comment by akoyaxd** [comment]
Sure! I'm not sure what I am looking for though.

I can see these GETs for media as soon as I scroll over them:
![grafik](https://user-images.githubusercontent.com/22196236/201399426-43aa9e9d-55c4-49d3-8861-2021b6857e86.png)

Maybe it's worth to mention, that they are h265 files, that can not be played in the browser..

**Comment by akoyaxd** [comment]
I can also still reproduce this on Chromium and Safari.

https://user-images.githubusercontent.com/22196236/201402669-129adaea-560d-4787-8666-892938c0f5d9.mov

**Comment by alextran1502** [comment]
H.265 can now be played in Chrome. They added that feature sometime last week, I believe. It still cannot be played on Firefox, though.

I see you have a group of videos you hovered over, correct? My test was conducted on a single photo hovering action.

**Comment by akoyaxd** [comment]
Yes it was a group of videos. Sorry I didn't consider this to have an impact. ^^

Yea, Firefox does not support it because of the royalty fees.
Plain Chromium does not support it as well, for the same reason. I try to avoid Google as much as I can, that's why I do not use Chrome.

Paitently waiting for #203 because of this :)

**Comment by alextran1502** [comment]
> Yes it was a group of videos. Sorry I didn't consider this to have an impact. ^^
> 
> Yea, Firefox does not support it because of the royalty fees. Plain Chromium does not support it as well, for the same reason. I try to avoid Google as much as I can, that's why I do not use Chrome.
> 
> Paitently waiting for #203 because of this :)

Got it! I will try to reproduce the scenario and get back to you on the fix

**Comment by akoyaxd** [comment]
What about a setting to disable video previews?
Not as a fix but as a workaround since a low bandwidth mode would be nice as well.

**Comment by Ensber** [comment]
I just noticed that this problem still exists in v2.7.5.

When i move my mouse over manny videos in the timeline, each starts the download of the complete video, and it does not cancel after i dont hover over it anymore.
this results in manny long running requests, where only 6 are processed in the case of http1.1 and this makes the UI not do anything:
* preview images dont load when scrolling down
* when i click on a image/video the UI hangs, until it can finish that request, that is blocked by the downloading of the videos

I tested this on Firefox/Chromium

**Comment by akoyaxd** [comment]
Can confirm, The issue is back for me as well.

From my first look, it seems it only affects videos, that started buffering through a mouse hover, but did not start yet playing, while scrolling further down the timeline.

**Comment by VerstandInvictus** [comment]
This still happens for me as well. It causes the entire UI to lock up and refuse to load thumbnails (because maxconns on the server/proxy are saturated by streaming motion photos) when served remotely and scrolling through the gallery. "mouse hover" includes "it was under your mouse for a millisecond while scrolling the gallery".
