### ISSUE TITLE
Date shortened while there is plenty of space

### ISSUE THREAD

**Issue by erikvanoosten** [immich-app/immich#9582]
### The bug

Date is shown as `zo 6 mei 2...` while there is plenty of space to include the full year.

<img width="179" alt="Scherm­afbeelding 2024-05-18 om 17 44 11" src="https://github.com/immich-app/immich/assets/630600/e025957e-b6d7-4eef-8e31-8e871ef41ffe">

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Open immich web
2. Login
3. Look at time line
```

Note: _sometimes_ the date _is_ displayed fully. While trying to debug, I noticed that as soon as you open the developer tools, the full date is displayed. If this happens, the correct display persists till a full-reload (Shift-Cmd-R). The developers tools need to be opened in a separate window.

### Additional information

Using Firefox 126.0 on MacOs (Arm), with ublock origin addon.

**Comment by erikvanoosten** [comment]
It seems that Firefox first determines the width of the span and then applies the elipses inside it.

<img width="1133" alt="Scherm­afbeelding 2024-05-18 om 17 54 13" src="https://github.com/immich-app/immich/assets/630600/506f5e8e-62eb-46be-a81d-411dc4fb3eee">

**Comment by Snowknight26** [comment]
Was able to reproduce in Firefox. A quick test showed that adding `width: 100%` to this element seems to fix the issue regardless of whether the select icon that conditionally appears to the left of the date is showing.
