### ISSUE TITLE
[BUG] Back gesture closes app when image select window is open

### ISSUE THREAD

**Issue by Shlokp** [immich-app/immich#960]
**Describe the bug**
With the latest update, the new image select window was introduced. When any image is selected, using the back gesture to try close this window results in the whole app closing instead.

**System**
- Phone OS [iOS, Android]: android 13
- Server Version: 1.35.0
- Mobile App Version: 1.35.0 build.54

**Comment by bo0tzz** [comment]
Screencap of the described behaviour: https://put.bo0tzz.me/screen-20221112-130456.mp4

**Comment by martyfuhry** [comment]
Fixed with #1464
