### ISSUE TITLE
Storage Usage on Truenas Scale

### ISSUE THREAD

**Issue by TechanisYT** [immich-app/immich#9602]
### The bug

Hello, I recently setup Immich on Truenas Scale and uploaded about 200 GB of Photos and Videos to it. But the Bar in The bottom left only shows 128KB of utilization. How can I fix this? I used the default settings of Truenas Scale when setting Immich up.
![grafik](https://github.com/immich-app/immich/assets/96913326/ca1ea8f0-688b-4822-ac0f-7927a761e277)
Kind regards.

### The OS that Immich Server is running on

Truenas Scale

### Version of Immich Server

1.105.1

### Version of Immich Mobile App

1.105.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default truenas scale config
```

### Your .env content

```Shell
default truenas scale config
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by bo0tzz** [comment]
#9514
