### ISSUE TITLE
No photos shown in Photos list when navigating to an Album via Photos, then back to Photos

### ISSUE THREAD

**Issue by Snowknight26** [immich-app/immich#9619]
### The bug

If you navigate to a photo that's part of an album from the Photos list, then navigate to an album that it's part of, attempting to go back (once to the photo, then once to the Photos list) shows nothing in the Photos list.

### The OS that Immich Server is running on

Windows 10 22H2 (19045.4291)

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Navigate to Photos
2. Click on a photo that's part of at least one album
3. Open the Info panel if it's not shown
4. Click on one of the albums in the Appears In section of the Info panel
5. Click the back button ("Close") in the top left or press escape to get back to the photo
6. Click the back button ("Go back") in the top left or press escape to get back to the Photos list
```

### Additional information

Normally there's a call to `/api/timeline/bucket?isArchived=false&size=MONTH&timeBucket=[time]&withPartners=true&withStacked=true` when viewing the Photos list (via the Photos route?), but with these steps, completing step 5 doesn't trigger this call. My guess is some event isn't firing that triggers this/populates the list.

**Comment by Snowknight26** [comment]
Coincidentally, if you do the reproduction steps up to and including step 4, then refresh the page, pressing back/escape doesn't show the issue.

The difference in behavior stems from `web/src/routes/(user)/albums/[albumId=id]/[[photos=photos]]/[[assetId=id]]/+page.svelte`, specifically in `afterNavigate`. 

In the case of the reproduction steps, the backUrl is `/photos/[id]`.
In other cases, such as when refreshing the `/albums/[id]` page with _no_ prior navigation/referrer, the backUrl is `/albums`.

I imagine the `AssetGrid` is loaded differently in those two scenarios., which is what loads the data via a call to `AssetStore.loadBucket`.

**Comment by alextran1502** [comment]
@midzelis I think this have something to do with hard url navigation, correct?

**Comment by jrasm91** [comment]
I can't reproduce this, so I assume it has been fixed.
