### ISSUE TITLE
Assets are sorted by UTC time, which leads to an inconsistant order with UTC and Local-time assets

### ISSUE THREAD

**Issue by Hely0n** [immich-app/immich#9637]
### The bug

I have videos of a trip and we made both gopro and iPhone videos.  The GoPro videos just have a time without a Timezone, while the iPhone videos have a Timezone (it shows GMT+03:00 in immich). I wonder how it's possible because as far as i know, Exif doesn't support timezones on videos.

Well the problem is now, that the mixed videos are in a wrong order and I think that's because the UTC time is considered for sorting instead of the local time.

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Add videos with and without timezone to your library
2. Look how the utc videos will be sorted like they happened later if recored in GMT+ zones
3.
...
```

**Comment by Hely0n** [comment]
The times are correct. An iPhone video has the time "15:23 GMT+3:00" and now there is a GoPro video that will be sorted as later even if it shows "12:37 UTC".

So in the time line, the UTC videos are considered some hours (should be 3?) later.

**Comment by bo0tzz** [comment]
`12:37 UTC` is after `15:23 GMT+3:00`, right?

**Comment by Hely0n** [comment]
I just found out that it's now possible to set the timezone of videos (it didn't commit the change when i tested it right after the feature was released).

Which exiftool command is used to set the timezone of a video via xmp? So I could just bulk-generate xmp files for them

**Comment by Hely0n** [comment]
> `12:37 UTC` is after `15:23 GMT+3:00`, right?

Yes

**Comment by bo0tzz** [comment]
So the gopro video is later, and is also sorted as later in the timeline? I don't think there's a problem then, right?

**Comment by Hely0n** [comment]
Technically yes, but it seems like it's not possible to set the timezone on the GoPro. So you just set it to your current local time and it will be saved as UTC.

But I think I could fix that if I apply the same exiftool command that it used by image because I didn't manage to set the timezone and read somewhere that exif doesn't support timezones on videos

**Comment by Hely0n** [comment]
It looks like it's just a problem with GoPros, so I'll close this and try to bulk edit the timezones of the videos. Thank you.
