### ISSUE TITLE
Microservices error contacting Machnie Learning when URL has trailing slash

### ISSUE THREAD

**Issue by AlmightyFrog** [immich-app/immich#9676]
### The bug

I was doing tests doing load balancing ML jobs to several systems in parallel. When i changed it back from nginx load balancer to direct container configured it like this `http://immich-machine-learning:3003/` including a trailing slash
![image](https://github.com/immich-app/immich/assets/2421469/df36fdac-82bc-4b8b-a984-68a5cbcc01c5)

This seems to break Microservices container issuing Machinelearning
```
immich_microservices           | [Nest] 7  - 05/22/2024, 7:35:18 PM   ERROR [ImmichMicroservices] [JobService] Object:
immich_microservices           | {
immich_microservices           |   "id": "d63c6a02-d2d7-4df9-be46-17c3432d4281"
immich_microservices           | }
immich_microservices           |
immich_microservices           | [Nest] 7  - 05/22/2024, 7:35:18 PM   ERROR [ImmichMicroservices] [JobService] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request for clip failed with status 404: Not Found
immich_microservices           | [Nest] 7  - 05/22/2024, 7:35:18 PM   ERROR [ImmichMicroservices] [JobService] Error: Machine learning request for clip failed with status 404: Not Found
immich_microservices           |     at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:23:19)
immich_microservices           |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_microservices           |     at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:86:31)
immich_microservices           |     at async /usr/src/app/dist/services/job.service.js:145:36
immich_microservices           |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_microservices           |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```

When I change it to `http://immich-machine-learning:3003` everything works fine.

Can someone else please confirm that this is a real issue, and if so, either sanitize the input or give a warning or at least document it somewhere that traling slash seems to make an issue?
Thanks!

---

I tried to get the exact url which is making issues by switching back to nginx load balancer and logging all access+error, but there then now only following popped up which i guess is something completely else.
```
==> access.log <==
172.16.19.7 - - [22/May/2024:20:01:37 +0000] "POST /predict HTTP/1.1" 504 167 "-" "node"

==> error.log <==
2024/05/22 20:01:37 [error] 29#29: *49 client intended to send too large body: 1266390 bytes, client: 172.16.19.7, server: , request: "POST /predict HTTP/1.1", host: "immich-machine-learning-nginx:3003"
```

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

does not matter

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
does not matter
```

### Your .env content

```Shell
pretty much default.
```

### Reproduction steps

```bash
1. Add slash
2. Issue e.g. face detection
3. notice error on console log
```

**Comment by safehome-jdev** [comment]
Looks like this would be due the fetch URL containing a forward slash after the variable; thus causing an invalid url situation.

I don't believe there's any input validation on the `config.machineLearning.url` config setting, but I'm not adept with svelte to say.

```ts
    const res = await fetch(`${url}/predict`, { method: 'POST', body: formData }).catch((error: Error | any) => {...
```
[link]("https://github.com/immich-app/immich/blob/main/server/src/repositories/machine-learning.repository.ts#L22")

**Comment by justin13888** [comment]
> Looks like this would be due the fetch URL containing a forward slash after the variable; thus causing an invalid url situation.
> 
> I don't believe there's any input validation on the `config.machineLearning.url` config setting, but I'm not adept with svelte to say.
> 
> ```ts
>     const res = await fetch(`${url}/predict`, { method: 'POST', body: formData }).catch((error: Error | any) => {...
> ```
> 
> [Link](https://github.com/immich-app/immich/blob/main/server/src/repositories/machine-learning.repository.ts#L22)
> 
> [Svelte config](https://github.com/immich-app/immich/blob/main/web/src/lib/components/admin-page/settings/machine-learning-settings/machine-learning-settings.svelte#L41)

There are two things it appears could be improved:

1. Normalize the base URLs to exclude trailing / (by modifying server code)
2. When joining URLs, use a function rather than appending obliviously (could do so regardless of assumption that the base URL is stored without the trailing /)

I don't think the frontend (e.g. Svelte web app, Fluter mobile app) should be handling this sanitization. If you want immediate user feedback, sure you could do form validation on the frontend too

**Comment by AlmightyFrog** [comment]
Further improvement I imagine beyond form validation could be a short query whether the url is reachable, otherwise give user a warning.

**Comment by safehome-jdev** [comment]
> > Looks like this would be due the fetch URL containing a forward slash after the variable; thus causing an invalid url situation.
> > I don't believe there's any input validation on the `config.machineLearning.url` config setting, but I'm not adept with svelte to say.
> > ```ts
> >     const res = await fetch(`${url}/predict`, { method: 'POST', body: formData }).catch((error: Error | any) => {...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [Link](https://github.com/immich-app/immich/blob/main/server/src/repositories/machine-learning.repository.ts#L22)
> > [Svelte config](https://github.com/immich-app/immich/blob/main/web/src/lib/components/admin-page/settings/machine-learning-settings/machine-learning-settings.svelte#L41)
> 
> There are two things it appears could be improved:
> 
> 1. Normalize the base URLs to exclude trailing / (by modifying server code)
> 2. When joining URLs, use a function rather than appending obliviously (could do so regardless of assumption that the base URL is stored without the trailing /)
> 
> I don't think the frontend (e.g. Svelte web app, Fluter mobile app) should be handling this sanitization. If you want immediate user feedback, sure you could do form validation on the frontend too

@justin13888 We should be able to use the `.endsWith('/')` JS function to modify the string with a conditional statement to provide a validated URL.

```js
// url = 'https://google.com/"

url.endsWith("/") ? url.slice(0, -1) : url

// "https://google.com"
```

**Comment by justin13888** [comment]
> > > Looks like this would be due the fetch URL containing a forward slash after the variable; thus causing an invalid url situation.
> > > I don't believe there's any input validation on the `config.machineLearning.url` config setting, but I'm not adept with svelte to say.
> > > ```ts
> > >     const res = await fetch(`${url}/predict`, { method: 'POST', body: formData }).catch((error: Error | any) => {...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > [Link](https://github.com/immich-app/immich/blob/main/server/src/repositories/machine-learning.repository.ts#L22)
> > > [Svelte config](https://github.com/immich-app/immich/blob/main/web/src/lib/components/admin-page/settings/machine-learning-settings/machine-learning-settings.svelte#L41)
> > 
> > 
> > There are two things it appears could be improved:
> > 
> > 1. Normalize the base URLs to exclude trailing / (by modifying server code)
> > 2. When joining URLs, use a function rather than appending obliviously (could do so regardless of assumption that the base URL is stored without the trailing /)
> > 
> > I don't think the frontend (e.g. Svelte web app, Fluter mobile app) should be handling this sanitization. If you want immediate user feedback, sure you could do form validation on the frontend too
> 
> @justin13888 We should be able to use the `.endsWith('/')` JS function to modify the string with a conditional statement to provide a validated URL.
> 
> ```js
> // url = 'https://google.com/"
> 
> url.endsWith("/") ? url.slice(0, -1) : url
> 
> // "https://google.com"
> ```

That would handle the case with a single trailing "/". But if we're going to validate a URL, while we're at it, we should validate the entire format of the string (e.g. it contains http or https). I'd just use regex in that case.

**Comment by safehome-jdev** [comment]
@justin13888 Would it make more sense then to use a button to indicate http/s to remove user typo errors, with validation needing minimal regex to sift through? 

For example:
```js
// This regex ensures only letters, numbers, periods, and semi-colons are present in the string.

url.match(/[^\w\.:]/) ? true : false
```

**Comment by justin13888** [comment]
I guess validation should just allow anything that could technically be
callable after appending like this: `${url}/some/endpoint/here`. So we
should accept any http/https URL not ending in a trailing slash (even if
it's a bogus URL). This also includes urls with subroutes (e.g. "
https://google.ca/en"). Also keep in mind URLs could contain non-latin
characters as well. Not sure if this could work: `https?:\/\/.*[^\/\s]$`.
Immich clients should also just give examples of valid domains to help
users.
