### ISSUE TITLE
[bug] Scroll indicator goes behind the topbar

### ISSUE THREAD

**Issue by teaalltr** [immich-app/immich#9677]
### The bug

Basically the scroll indicator on the right (in the photos list, main view) initially goes behind the top bar (the one with the Immich logo and the cloud icon etc).
It should start from below the top bar, so that the scroll handle can be used

### The OS that Immich Server is running on

RaspberryPi OS

### Version of Immich Server

Nn

### Version of Immich Mobile App

1.105.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
NN
```

### Your .env content

```Shell
NN
```

### Reproduction steps

```bash
1.NN
2.
3.
...
```

**Comment by alextran1502** [comment]
Do you mind capturing a screenshot or video showing this bug?

**Comment by teaalltr** [comment]
Sure, here it is
![Screenshot_20240522-224707~2](https://github.com/immich-app/immich/assets/11365978/2aac4bc2-8d0a-4b77-9e3a-e24c7806518a)

**Comment by alextran1502** [comment]
Can you capture a video? I cannot reproduce it in my end

**Comment by teaalltr** [comment]
Just tried to record a video but after force closing the app and reopening the bug seems to be gone, cannot reproduce. Dunno, maybe it's a load issue, some sort of a race condition on the UI or something, something not completely deterministic
