### ISSUE TITLE
[feature] Show and group places differently when photos are taken from a plane

### ISSUE THREAD

**Issue by teaalltr** [immich-app/immich#9681]
### The bug

So let's say you go for a plane trip and take some photos along the way, from the plane window. EXIF metadata are added to the image with the GPS coordinates and the altitude.
Using this information (specifically the altitude and possibly with some ML the kind of photo and subject too) we could group (and show on the map) the photos in a more meaningful way, let's say with a contiguous line between points on the map and have an album with the title "plane trip from here to there" or "plane trip <date>".
This would be pretty amazing to have, cause at the moment we have photos with random coordinates in the middle of the flight with the random corresponding places names down below the plane.

This could also be done for train trips for instance, but it's a bit more difficult I guess cause in that case we cannot rely on the altitude metadata.

It would also be awesome if we had some kind of API to gather all this random pieces of information about what we do and puzzle all them into a nice timeline like in Google Maps timeline feature, so this app and others can contribute to a local repository where some kind of other ML or rule-based service can process the infor in a cohesive and meaningful way (so toprovide the same level of event-aware assistance and reconstruction as Google does). Hope it makes sense

### The OS that Immich Server is running on

RaspberryPi OS

### Version of Immich Server

Nn

### Version of Immich Mobile App

1.105.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
NN
```

### Your .env content

```Shell
NN
```

### Reproduction steps

```bash
1.NN
2.
3.
...
```

**Comment by alextran1502** [comment]
Can you please open these as a feature requests since this is not currently available in the app to consider as a bug?

**Comment by alextran1502** [comment]
And please search for existing request before opening a new one, I think there is similar request for this one as well
