### ISSUE TITLE
Files edited in place cause inconsistency

### ISSUE THREAD

**Issue by HarHarLinks** [immich-app/immich#9695]
### The bug

When I edit a photo on android and save it in-place (e.g. to correct the rotation) after it was already uploaded, the state in the mobile app becomes inconsistent with the state on server:
- immich android continues to show the file as backed up
- it continues to show the old thumbnail 
- it will show the edited file when tapping the thumbnail (with appropriate default setting)
- when I delete the file on server, immich android also hides the file (because it thinks the edited one is the original) so this isn't a way to workaround 

### The OS that Immich Server is running on

Debian docker 

### Version of Immich Server

1.105.1

### Version of Immich Mobile App

1.105.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. Background sync file on android
2. Verify upload on PC
3. Edit file in place on android
4. Try to update the file on server
```

### Additional information

Related to #9250

**Comment by bo0tzz** [comment]
#6439
