### ISSUE TITLE
Images are cut-off when viewing in large view

### ISSUE THREAD

**Issue by Joly0** [immich-app/immich#9696]
### The bug

When viewing images in large view, images are cut-off at the top, because of the "edit-bar":
![image](https://github.com/immich-app/immich/assets/13993216/e1ad5cf6-157a-4701-818f-defb20d29c30)
(Normal preview-image)
![image](https://github.com/immich-app/immich/assets/13993216/7e2deec1-b0ae-4e01-b155-c66e7cf4983a)
(Large image with top being cut-off)

Imo, this shouldnt happen

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
NA
```

**Comment by safehome-jdev** [comment]
Can you please confirm this isn't due to some dark-mode extension that is running on your client? As of v1.105.1, the top bar is transparent

<img width="658" alt="image" src="https://github.com/immich-app/immich/assets/65427171/778e8c87-0462-4149-8617-d3a9a55f710f">

Using a dark-mode extension on my browser displays the same issue your machine does

**Comment by Joly0** [comment]
Hey  @safehome-jdev you are right, this was due to a dark-mode extension. Though i still think there should be the option, to view the image in full size without any menus in front of it :)

**Comment by roschaefer** [comment]
I just ran into this issue and was about to open a duplicate issue. I'm also using [Dark Reader](https://darkreader.org/) and for now I'm happy that I can just disable the browser extension for immich.

However, I would prefer if the top bar would *not* be transparent: Icon visibility depends on background image + image border runs through the top bar which doesn't look very nice either.

![image](https://github.com/user-attachments/assets/cd73384a-4a5f-4cb1-9c6e-782ba9f2f36e)

**Comment by danieldietzler** [comment]
Closing this as the issue has been resolved. Potential feature requests go to their respective section (if there isn't already one)
