### ISSUE TITLE
Search by filename

### ISSUE THREAD

**Issue by 0verEngineer** [immich-app/immich#9728]
### The bug

I want to search a Video by its filename and i get a lot of results but the video i am looking for is not in the results

### The OS that Immich Server is running on

Docker on Fedora

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

WEB

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Default, i do not have access to it atm.
```

### Your .env content

```Shell
Default, i do not have access to it atm.
```

### Reproduction steps

```bash
1. Upload a video
2. Use the searchbar and put in the filename
3. Look at results
```

**Comment by schuhbacca** [comment]
Did you switch the search type from context to file name when attempting?

**Comment by 0verEngineer** [comment]
@schuhbacca Oh sorry i am an idiot :D
