### ISSUE TITLE
App can't hit .well_known, hits incorrect API endpoint, then logs out

### ISSUE THREAD

**Issue by ddshd** [immich-app/immich#9745]
### The bug

```
> 172.24.0.7 - - [21/May/2024:21:36:52 +0000] "GET /api/server-info HTTP/1.1" 404 131 "-" "Dart/3.3 (dart:io)" "174.206.38.109" "<domain>" "/api/server-info" "-" "-"
> 172.24.0.7 - - [21/May/2024:21:36:52 +0000] "GET /api/asset/device/bf001c7874f972a4ddfceb3774bdce8261c269ce025ed8fe3882800fbc68e5bf HTTP/1.1" 200 36458 "-" "Dart/3.3 (dart:io)" "174.206.38.109" "<domain>" "/api/asset/device/bf001c7874f972a4ddfceb3774bdce8261c269ce025ed8fe3882800fbc68e5bf" "immich" "192.168.176.3:3001"
> 172.24.0.7 - - [21/May/2024:21:36:55 +0000] "GET /api/socket.io/?EIO=4&transport=websocket HTTP/1.1" 101 362 "-" "Dart/3.3 (dart:io)" "174.206.38.109" "<domain>" "/api/socket.io/?EIO=4&transport=websocket" "immich" "192.168.176.3:3001"
> 172.24.0.7 - - [22/May/2024:04:00:36 +0000] "GET /api/server-info/ping HTTP/1.1" 200 14 "-" "Dart/3.3 (dart:io)" "<ip>" "<domain>" "/api/server-info/ping" "immich" "192.168.176.3:3001"
> 172.24.0.7 - - [22/May/2024:04:00:36 +0000] "GET /.well-known/immich HTTP/1.1" 200 56 "-" "Dart/3.3 (dart:io)" "<ip>" "<domain>" "/.well-known/immich" "immich" "192.168.176.3:3001"
> 172.24.0.7 - - [22/May/2024:05:00:42 +0000] "GET /user/me HTTP/1.1" 204 0 "-" "Dart/3.3 (dart:io)" "<ip>" "<domain>" "/user/me" "-" "-"
> 172.24.0.7 - - [22/May/2024:05:00:42 +0000] "POST /auth/logout HTTP/1.1" 204 0 "-" "Dart/3.3 (dart:io)" "<ip>" "<domain>" "/auth/logout" "-" "-"
```
`204` response is due to my reverse proxy which is set to not send `404`, `503` etc..

My `/.well-known/immich` response:

```
{
     "api": {
         "endpoint": "/api"
    }
}
```

![image](https://github.com/immich-app/immich/assets/17243132/56636edc-a4ab-4da0-b5ef-a14491a5737a)

### The OS that Immich Server is running on

Ubuntu 20.04

### Version of Immich Server

v1.105

### Version of Immich Mobile App

v1.105.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1.
2.
3.
...
```

### Additional information

Discord discussion: https://discord.com/channels/979116623879368755/1049703391762321418

**Comment by mmomjian** [comment]
I know I mentioned this on Discord but this seems very related to #8146

**Comment by bo0tzz** [comment]
I agree it's related, though my hypothesis is that this is one of several bugs that trigger the logout bug, and thus both are things to be fixed separately.

**Comment by mmomjian** [comment]
I sent Alex the logs, but I just had the #8146 issue again after adding /api to the URL. No well know for me, and yet it falls back to /user/me and /auth/logout. So there’s definitely an issue in the fallback logic as well.

**Comment by ddshd** [comment]
> @ddshd how are you connected to Immich? Local, VPN, real domain name?

In this scenario it’s real domain but saw this on another device through local IP (no /api).

Honestly I think the app shouldn’t log out unless there is a valid logout response from /user/me (like a 403 or whatever response it sends for a if a user is actually supposed to be logged out). This would also help with the app being offline with the server.

**Comment by mmomjian** [comment]
> > @ddshd how are you connected to Immich? Local, VPN, real domain name?
> 
> In this scenario it’s real domain but saw this on another device through local IP (no /api).
> 
> Honestly I think the app shouldn’t log out unless there is a valid logout response from /user/me (like a 403 or whatever response it sends for a if a user is actually supposed to be logged out). This would also help with the app being offline with the server.

I would love for, at a minimum an option in the settings to disable auto-logout. It's happening 1-2/day for me currently, hitting the non-API endpoints and logging out.

**Comment by CommanderRedYT** [comment]
Same for me without VPN through the internet and probably also local. It's logging out because /api/user/me returns 404.

**Comment by bo0tzz** [comment]
@CommanderRedYT that's a different issue, you need to update your app.

**Comment by CommanderRedYT** [comment]
I got that with the latest version tho. Got logged out in app and web multiple times after upgrading. Maybe another issue?
