### ISSUE TITLE
External Libraries not finding files

### ISSUE THREAD

**Issue by ddshd** [immich-app/immich#9777]
### The bug

External libraries not finding files - even if using some of the force update options.

Here are all the logs. Contains entries after hitting any of the Scan Library options but nothing happen. No change in CPU usage either.
```
[Nest] 8  - 05/26/2024, 3:23:03 PM VERBOSE [ImmichServer] [LoggingInterceptor] [u3e32tun] GET /api/user/info/8f9c3933-1533-4d20-bb28-7e5475af550b 200 1.12ms ::ffff:192.168.176.1
[Nest] 8  - 05/26/2024, 3:23:05 PM VERBOSE [ImmichServer] [LoggingInterceptor] [qiih1asb] POST /api/library/748f0c0a-98d9-47a3-9794-973088ced227/validate 200 0.72ms ::ffff:192.168.176.1
[Nest] 8  - 05/26/2024, 3:25:57 PM VERBOSE [ImmichServer] [LoggingInterceptor] [lge1fweh] POST /api/library/748f0c0a-98d9-47a3-9794-973088ced227/scan 204 12.26ms ::ffff:192.168.176.1
[Nest] 8  - 05/26/2024, 3:25:58 PM VERBOSE [ImmichServer] [LoggingInterceptor] [r60akxtv] POST /api/library/748f0c0a-98d9-47a3-9794-973088ced227/scan 204 7.32ms ::ffff:192.168.176.1
[Nest] 8  - 05/26/2024, 3:25:59 PM VERBOSE [ImmichServer] [LoggingInterceptor] [3phemmzn] POST /api/library/748f0c0a-98d9-47a3-9794-973088ced227/scan 204 10.61ms ::ffff:192.168.176.1
[Nest] 8  - 05/26/2024, 3:26:02 PM VERBOSE [ImmichServer] [LoggingInterceptor] [411pcg5l] POST /api/library/90bc7ca9-7fbc-4629-bc89-e2cd3b74a079/scan 204 11.73ms ::ffff:192.168.176.1
[Nest] 8  - 05/26/2024, 3:26:02 PM VERBOSE [ImmichServer] [LoggingInterceptor] [mxssdzel] POST /api/library/6d17b379-1c1b-40ae-85f7-a42dfaaf165e/scan 204 11.58ms ::ffff:192.168.176.1
[Nest] 8  - 05/26/2024, 3:26:02 PM VERBOSE [ImmichServer] [LoggingInterceptor] [hlvlk6bg] POST /api/library/748f0c0a-98d9-47a3-9794-973088ced227/scan 204 8.90ms ::ffff:192.168.176.1
```

External library configuration:
- Just one import path at `/mnt/media/...`. The path does show up and exist inside the containers.

Works on `v1.104.0`.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v.1.105.1

### Version of Immich Mobile App

v.1.105

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
The latest release docker-compose
```

### Your .env content

```Shell
The latest release docker-compose, with UPLOAD_LIBRARY set to a path.
```

### Reproduction steps

```bash
1. Create a directory with subdirectories and files within the directories.
2. Create a external library with the new directory as import path
3. Use any of the library refresh options to force EL to update.
```

**Comment by aviv926** [comment]
Maybe also related to #9574

**Comment by Gloryandel** [comment]
Please ensure that the volume configuration for immch server and immch microservices is the same (it can be a bound mount). My first deployment was normal.

**Comment by aviv926** [comment]
Is this still a problem?

**Comment by Gloryandel** [comment]
> Is this still a problem?

I think it works great.

**Comment by ddshd** [comment]
> Is this still a problem?

It was on the latest major version, I have not tried yet after the minor version releases.

**Comment by aviv926** [comment]
> > Is this still a problem?
> 
> It was on the latest major version, I have not tried yet after the minor version releases.

It works perfectly fine for me, maybe try to check with the new version and update?

**Comment by Digital39999** [comment]
Not sure how new this is, issue still does occur, but it seems like if i move one layer deeper it starts scanning files. My only idea would that be it breaks because target directory contains windows folders like $RECYCLE.BIN and others with $.

**Comment by iplaughlin** [comment]
@ddshd - I had to add it as a separate line to both the `immich-server` and `immich-microservices` section. The documentation only states to add it to the `immich-server` section.

**Comment by ddshd** [comment]
> @ddshd - I had to add it as a separate line to both the `immich-server` and `immich-microservices` section. The documentation only states to add it to the `immich-server` section.

microservices was removed though https://github.com/immich-app/immich/discussions/10110#discussion-6807145

**Comment by iplaughlin** [comment]
> > @ddshd - I had to add it as a separate line to both the `immich-server` and `immich-microservices` section. The documentation only states to add it to the `immich-server` section.
> 
> microservices was removed though [#10110 (comment)](https://github.com/immich-app/immich/discussions/10110#discussion-6807145)

Well, now I feel stupid for not catching that.

**Comment by etnoy** [comment]
Please enable debug logging and try again, there should be much more in the logs.

**Comment by etnoy** [comment]
Closing this. If this is still an issue, please inform us
