### ISSUE TITLE
Deduplication of video files, false positives, 

### ISSUE THREAD

**Issue by GrumpyMeow** [immich-app/immich#9794]
### The bug

I had 17000 duplicates in my library. I was already antipating the deduplication functionality.
Many video-files (which i copied from VHS-tape) start with a few seconds of all-black screen. The deduplication-algorithm sees them all as duplicates, which i don't think it should. As this makes it very easy to delete files of which only the first frames match with each other.
I don't think the algorithm should only take the first frame into account. The algorithm is accurate for photos, but very inaccurate for video-files. It's too easy for people to delete their video files by mistake.

I also noticed that the algorithm marks images (black.gif) and movie files (with first black frame) as duplicates. I don't think this should be the case.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
NA
```

**Comment by bo0tzz** [comment]
#9784

**Comment by mertalev** [comment]
Fixed via #9747 and #9784
