### ISSUE TITLE
[QUESTION] There are two splash screens on Android 12 and higher

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#982]
**Describe the bug**
I've recently accidentally updated my Android version to Android v12.
This version apparently had a new 'splash screen' feature, which forced a splash screen to every app- regardless of whether the app supports it or not. More info: https://developer.android.com/develop/ui/views/launch/splash-screen 

I've noticed that when I open Immich, I have two splash screens. One of which was forced by Android 12, and the other built-in splash screen. Android does have an API to integrate the app's splash screen with the splash screen forced by Android 12, so this is fixable. I've also added a video recording.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Update to Android 12
2. Open Immich
3. See two splash screens

**Expected behavior**
I expected Immich to have one splash screen instead of two.

**Screenshots**

https://user-images.githubusercontent.com/47184046/202293016-a41743a1-20c8-454c-adb7-25cf501157b2.mp4

**System**
- Phone OS [iOS, Android]: `Android 12`
- Server Version: `1.35.0`
- Mobile App Version: `1.35.0`

**Comment by alextran1502** [comment]
The first splash screen is the native splash screen which we have no control over, and the second splash screen is the intended splash screen to perform the login action if you check the "Stay logged in" box

**Comment by alextran1502** [comment]
I apologize for not reading the link about Splash Screen you mentioned. I will take a look at this.

**Comment by JVT038** [comment]
> The first splash screen is the native splash screen which we have no control over
According to [the docs](https://developer.android.com/develop/ui/views/launch/splash-screen/migrate), you have to migrate your current splash screen to the new API for Android 12+ and that will fix this issue. So it can be fixed
