### ISSUE TITLE
Backup remainder says 0, while still uploading photos/videos on iOS

### ISSUE THREAD

**Issue by coltenkrauter** [immich-app/immich#9827]
### The bug

I noticed today on the iOS app that the __backup__ `Remainder` section said 0, indicating to me that all of my photos and videos had been backed up, but oddly, I can see upload progress still occurring at the bottom of the **Backup** section. Furthermore, the `Backed up photos and videos` number continues to increase as more photos and videos get backed up. In the below photos, see that it goes from `139` to `146` while `Remainder` says `0`.

Normally, when `Remainder` is at 0, I feel comfortable deleting photos off of my iOS device, but this time, I don't since uploads are still seemingly happening. Is this expected behavior?

| ![a24309892bf63da8836ffecb14529a88_exif](https://github.com/immich-app/immich/assets/18080897/6c2ec59d-537b-4b86-b97f-a5070659cc53) | ![Screenshot 2024-05-28 at 7 39 46 AM](https://github.com/immich-app/immich/assets/18080897/ea9527a2-6c07-4320-b9e9-d03b1c58b622) |
|--------------------------------|--------------------------------|

| ![f7500320674ee1e8c8d596691a4c80ce_exif](https://github.com/immich-app/immich/assets/18080897/1d88f035-4789-4fc9-9aa5-8c401f2b7758) | ![b1f22951a2de8493278f2006c7a03d94_exif](https://github.com/immich-app/immich/assets/18080897/5d73f2c4-d71c-4e0d-a016-7b64be838106) |  ![5f9f694e390b13ab077b5b5aac459663_exif](https://github.com/immich-app/immich/assets/18080897/a9fad937-40a8-4842-b338-6bb76f4dff7e) |
|--------------------------------|--------------------------------|--------------------------------|

### The OS that Immich Server is running on

iPhone 14

### Version of Immich Server

1.105.1

### Version of Immich Mobile App

1.105.0.build.157

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I'm running the Immich server on TrueNAS Server using TrueCharts, so not sure where to find the compose content. Let me know if you want me to grab any config details.
```

### Your .env content

```Shell
Let me know if you want me to grab any config details.
```

### Reproduction steps

```bash
As best as I can tell, here are the repro steps,

1. Take some photos or videos on iPhone 14
2. Start Immich app and what for upload to finish (remainder says 0)
3. Notice that uploads continue to happen
```

**Comment by bo0tzz** [comment]
Dupe: #8364
