### ISSUE TITLE
Unable to remove images from an owned shared album.

### ISSUE THREAD

**Issue by nickstrand** [immich-app/immich#9882]
### The bug

When uploading pictures to a shared album as a named user, the permissions on the image remain with said user - instead of allowing both that user and the owner of the album to remove the image.  It removes the image from the webui, however a refresh brings it back immediately

![image](https://github.com/immich-app/immich/assets/65183434/76499da2-4867-439f-a600-fa0063a7c8e9)
![image](https://github.com/immich-app/immich/assets/65183434/018748a0-5060-4604-a171-94666e3854e2)

### The OS that Immich Server is running on

Docker in Kubernetes (ghcr.io/immich-app/immich-server:release)

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.0 build.139

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Standard but migrated to a kubernetes yaml
```

### Your .env content

```Shell
Standard but migrated to a kubernetes yaml
```

### Reproduction steps

```bash
1. Create a shared album as user A (album owner) with one image
2. Share with user B
3. Upload an image to the shared album from user B (image owner)
4. Log into user A and select the image uploaded from user B
5. Click the three dots and select remove from album
- Expected result of it showing 1 removed from user A's album, without deleting the image from user B's files
```

### Relevant log output

```shell
[Nest] 1  - 05/30/2024, 3:02:04 AM VERBOSE [ImmichServer] [LoggingInterceptor] [x8g6lu4v] DELETE /api/album/84d611ec-6aaa-468a-be33-66d76548f7e6/assets 200 61.41ms ::ffff:192.168.2.244
[Nest] 1  - 05/30/2024, 3:02:04 AM VERBOSE [ImmichServer] [LoggingInterceptor] [x737v82p] GET /api/album/84d611ec-6aaa-468a-be33-66d76548f7e6 200 79.42ms ::ffff:192.168.2.244
[Nest] 1  - 05/30/2024, 3:02:04 AM VERBOSE [ImmichServer] [LoggingInterceptor] [6knz31d6] GET /api/activity 200 10.50ms ::ffff:192.168.2.244
[Nest] 1  - 05/30/2024, 3:02:04 AM VERBOSE [ImmichServer] [LoggingInterceptor] [2v4m4obg] GET /api/album/84d611ec-6aaa-468a-be33-66d76548f7e6 200 34.62ms ::ffff:192.168.2.244
[Nest] 1  - 05/30/2024, 3:02:04 AM VERBOSE [ImmichServer] [LoggingInterceptor] [7r62eb6t] GET /api/activity/statistics 200 35.83ms ::ffff:192.168.2.244
[Nest] 1  - 05/30/2024, 3:02:04 AM VERBOSE [ImmichServer] [LoggingInterceptor] [guo9knec] GET /api/activity 200 12.13ms ::ffff:192.168.2.244
[Nest] 1  - 05/30/2024, 3:02:04 AM VERBOSE [ImmichServer] [LoggingInterceptor] [b04dwvn6] GET /api/activity/statistics 200 11.62ms ::ffff:192.168.2.244
```

**Comment by chowhi123** [comment]
I am using docker via portainer 1.5.1 and app is 1.5.0 on both ios and android. I am experiencing the same issues.

**Comment by commanderalpha** [comment]
Hi,
I stumbled across the same problem while cleaning up the vacation pictures... after selecting over a hundred.
BR
