### ISSUE TITLE
[bug][web] Scroll position not restored when navigating backwards

### ISSUE THREAD

**Issue by Thinkscape** [immich-app/immich#9885]
## The bug

Scroll position is not being restored when closing full-screen viewer and going back to album view.

## The OS that Immich Server is running on

Ubuntu 24

### Version of Immich Server

v1.105.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

## Reproduction steps

1. Open an album
2. Scroll down a bit to older photos
3. Click any of the photos (opens full-screen view)
4. Click the ◀️  to go back

## Expected

Scroll position is restored and I'm back looking at the same group of photos as before opening full-screen viewer.

## Actual

I'm back at the top of the album (newest photos), confused...

**Comment by bo0tzz** [comment]
#3114
