### ISSUE TITLE
Huge jump in timeline after viewing a photo (web)

### ISSUE THREAD

**Issue by erikvanoosten** [immich-app/immich#9907]
### The bug

On web, clicking a photo from the timeline, and then going back to the timeline, the timeline is often shifted by up to 2 months in the past, this can mean many pages of scrolling before you're back where you were. Not only is this extremely annoying, there is also no way to avoid it, e.g. by opening the photo in another tab (e.g. with Ctrl-click/Cmd-click).

### The OS that Immich Server is running on

NA

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

NA

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. Open Immich webapp with thousands of photos in Firefox 126.0.1, land on the/photos path
2. Click a photo
3. Click the close icon, or press Esc
4. Totally different photos are displayed now

Note: this bug does not always occur.
```

**Comment by kixmto** [comment]
+1 Really annoying.

**Comment by bo0tzz** [comment]
#3114

**Comment by erikvanoosten** [comment]
Thanks for looking into this. The description on https://github.com/immich-app/immich/discussions/3114 is not entirely the same, but it might have the same underlying problem.

**Comment by waclaw66** [comment]
@erikvanoosten what browser do you use? Please check the behaviour I've described in the #3114.

**Comment by erikvanoosten** [comment]
@waclaw66 After reading #3114 from top to bottom I think it is indeed correct to mark this as a duplicate. As reported I am indeed using Firefox.
