### ISSUE TITLE
[BUG][WEB][CLI] <Uploads of large mp4 vidos (~150+ mb) refuse to upload>

### ISSUE THREAD

**Issue by darrylgibbs** [immich-app/immich#991]
**Describe the bug**
When uploading videos via the CLI or WEB, all videos that are 150+ mb in size refuse to upload, citing an error: "ERROR Cannot upload file xxx.mp4 undefinedundefined."

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x ] I have read thoroughly the README setup and installation instructions.
- [ x] I have included my `docker-compose` file.
- [ x] I have included my redacted `.env` file.
- [ x] I have included information on my machine, and environment.

**To Reproduce**
1. Upload a large .mp4 video file to an album directly using either the CLI tool or web interface.
2. Allow the upload attempt to complete.
3. See error.

**Expected behavior**
A normal upload of the video file as with the auto backup from my Android phone.

**Screenshots**

**System**
- Android: v12
- Server Version: `1.35`
- Mobile App Version: `1.35 build.54`

**Additional context**
[docker-compose.txt](https://github.com/immich-app/immich/files/10049457/docker-compose.txt)
[env.txt](https://github.com/immich-app/immich/files/10049458/env.txt)

I've tried uploading via the web using the local IP:port combo, as well as using my Tailscale VPN IP:port combo.  Same result.

**Comment by bo0tzz** [comment]
Are you using a reverse proxy in front of immich? If so, you probably need to set [client_max_body_size](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) (or the equivalent for your proxy software).

**Comment by bo0tzz** [comment]
Closing this. @darrylgibbs if you're still having this problem, please provide some more information and reopen the issue.
