### ISSUE TITLE
Notifications Overlap Uploading Queue Ui

### ISSUE THREAD

**Issue by kragleh** [immich-app/immich#9940]
### The bug

I have been uploading alot of images into an album today and I noticed that this ui is unusable since I want to change the settings of the upload but have to click trough the notifications first to access it, they should stack or move the upload ui to the other side or something so that you can access the settings / see the underlying queue menu when uploading into an opened album.
![image](https://github.com/immich-app/immich/assets/108424057/ad617822-0d89-4a6a-9bd1-086d0dd65176)

### The OS that Immich Server is running on

Ubuntu 24.04 LTS

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

Web Ui Issue

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Upload alot of images into an opened album by dragging them into the window.
2. Upload ui shows but gets flooded quickly by notifications that say "Info Added 1 asset to the album"
```

**Comment by bo0tzz** [comment]
#6102
