### ISSUE TITLE
Page Up, Page Down and arrow keys not working as they should on timeline

### ISSUE THREAD

**Issue by kikendo** [immich-app/immich#9947]
### The bug

I am trying to navigate the timeline with the arrrow keys and page up/down on my keyboard and it's not functioning as expected.
First, arrow up and down don't work unless I click an image, then press ESC. After that I can scroll the timeline using them.
Then, Page Up/Down go to the top or bottom of the timeline when I press them, instead of scrolling by page.

I am trying this on Microsoft Edge on Windows 10.

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.0 build.157

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
/
```

### Your .env content

```Shell
/
```

### Reproduction steps

```bash
1.Try using arrow keys or Page Up/Down as described
2.
3.
...
```

**Comment by bo0tzz** [comment]
#6202
