### ISSUE TITLE
【BUG】The video is completely gray after transcoding

### ISSUE THREAD

**Issue by Ador-able** [immich-app/immich#9963]
### The bug

After the video is transcoded, it becomes completely gray with only sound

I observed the transcoding log：Started encoding video 22420dac-4217-44e1-a3c0-f0aeb9df42d3 {"inputOptions":[],"outputOptions":["-c:v h264","-c:a copy","-movflags faststart","-fps_mode passthrough","-map 0:0","-map 0:1","-v verbose","-vf scale=-2:720,format=yuv420p","-preset ultrafast","-crf 23","-maxrate 4500","-bufsize 9000"],"twoPass":false}

The actual transcoding command:/usr/bin/ffmpeg -i /photo/VID_20240530_145018.mp4 -y -c:v h264 -c:a copy -movflags faststart -fps_mode passthrough -map 0:0 -map 0:1 -v verbose -vf scale=-2:720,format=yuv420p -preset ultrafast -crf 23 -maxrate 4500 -bufsize 9000 upload/encoded-video/bb95565c-a9d1-4f8f-bb28-7e584d41124d/22/42/22420dac-4217-44e1-a3c0-f0aeb9df42d3.mp4

I uploaded the video to this repository：https://github.com/Ador-able/immich-video

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
skip
```

### Your .env content

```Shell
skip
```

### Reproduction steps

```bash
skip
```

**Comment by Ador-able** [comment]
I found that "-bufsize 9000" was causing the video to turn gray after transcoding. But I don't see a place to set this, you should apply your own additions. What can I do to get the transcoding video back to normal

**Comment by mertalev** [comment]
Make sure the max bitrate has a `k` at the end.

**Comment by voltage6082** [comment]
> Make sure the max bitrate has a `k` at the end.

Thank you very much, that was my problem.
![Screenshot_20240813_090822](https://github.com/user-attachments/assets/0e4ba2bb-0d50-4663-8442-79f116bea3bf)

**Comment by meminens** [comment]
Had the same issue. Didn't have k at the end. Now I'm going to have to re-transcode all my videos :) It will take couple days. Thanks for the tip!
