### ISSUE TITLE
Not everything is uploaded from the Android App

### ISSUE THREAD

**Issue by 0verEngineer** [immich-app/immich#9997]
### The bug

As you can see in my two screenshots there are 4 videos and one picture which are not uploaded to the server. I don't know why but it seems like a bug or unexpected behavior.

![Screenshot_20240605-183319](https://github.com/immich-app/immich/assets/105462605/6161d043-d7a0-4146-b2a3-34c9364d1bda)
![Screenshot_20240605-183308](https://github.com/immich-app/immich/assets/105462605/5400decf-42f9-488b-ab0e-5ccda1849b4f)

### The OS that Immich Server is running on

Fedora (Docker)

### Version of Immich Server

1.102.3

### Version of Immich Mobile App

1.105.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Default
```

### Your .env content

```Shell
Default
```

### Reproduction steps

```bash
I don't know, it just happened
```

**Comment by alextran1502** [comment]
Please try update your server to the latest version, then logout and log back in

**Comment by 0verEngineer** [comment]
Thanks a lot it worked.
